(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 550,
	height: 400,
	fps: 12,
	color: "#FFFFFF",
	webfonts: {},
	manifest: [
		{src:"sounds/Bub.mp3", id:"Bub"},
		{src:"sounds/CrashMountain.mp3", id:"CrashMountain"},
		{src:"sounds/High_Screaming_Gtr.mp3", id:"High_Screaming_Gtr"},
		{src:"sounds/JingleNoun.mp3", id:"JingleNoun"},
		{src:"sounds/Mick.mp3", id:"Mick"},
		{src:"sounds/nounanounis.mp3", id:"nounanounis"},
		{src:"sounds/NounThing.mp3", id:"NounThing"},
		{src:"sounds/organ_f_chord.mp3", id:"organ_f_chord"},
		{src:"sounds/Rita.mp3", id:"Rita"},
		{src:"sounds/SECorrectAnswer.mp3", id:"SECorrectAnswer"},
		{src:"sounds/SENameofIdea.mp3", id:"SENameofIdea"},
		{src:"sounds/SENameOfPerson.mp3", id:"SENameOfPerson"},
		{src:"sounds/SENameOfPlace.mp3", id:"SENameOfPlace"},
		{src:"sounds/SENameofThing1.mp3", id:"SENameofThing1"},
		{src:"sounds/SENameofThing2.mp3", id:"SENameofThing2"},
		{src:"sounds/SESummary.mp3", id:"SESummary"},
		{src:"sounds/SEWrongAnswer.mp3", id:"SEWrongAnswer"},
		{src:"sounds/Skateboard.mp3", id:"Skateboard"},
		{src:"sounds/Slim.mp3", id:"Slim"},
		{src:"sounds/Stace.mp3", id:"Stace"}
	]
};



lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib.Thingbottomstill = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0000FF").s().p("Ag8CIQgWgEAAgPQAAgPAPAAQAHAAAOADQAPADASAAQAgAAANghQAIgVABgtQgKASgNAIQgNAKgPgBQggABgUgWQgUgWAAggQAAgwAcgdQAcgeAuAAQARAAALAEQALAEAFAJQATABAAAUQAAANgDAUIgFAhIgEA6QgBAigGAXQgIAcgSAOQgVAQgmAAQgXAAgQgDgAgfhXQgRAVAAAgQAAAaAKAKQAKANATAAQAQAAARgSQAPgSACgSQADgUAFgoQgHgGgIgCQgHgDgJAAQgfAAgSAXg");
	this.shape.setTransform(29.3,10.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0000FF").s().p("AAqBVIgFgmQgCgVAAgSIABgOIAAgRQAAgmgOAAQgUAAgQAXQgQAVgJAfIgCARIgBARIABAQIABAQQABAIgFAFQgFAFgIAAQgHAAgFgFQgFgFAAgIIgBgQIgBgQQAAgSACgeQADggAAgSIAAgRIgBgQQgBgIAGgFQAEgFAIAAQAQAAACAXIABAVQAdgoAdAAQAcAAALAZQAIARABAgIAAASIAAAOQAAAPADAXQAEAXAAAOQAAAIgFAFQgFAFgIAAQgPAAgCgRg");
	this.shape_1.setTransform(11.1,5.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0000FF").s().p("AgQB/QgFgFAAgIIAAgfIgBggIACgpQACgXAAgQQAAgIAEgFQAFgFAIAAQAFAAAFAFQAFAFAAAIQAAAQgCAXIgCApIABAgIAAAfQABAIgFAFQgFAFgFAAQgIAAgFgFgAgKhgQgGgGAAgIQAAgJAGgGQAGgGAGAAQAJAAAGAGQAGAGAAAJQAAAIgGAGQgGAGgJAAQgGAAgGgGg");
	this.shape_2.setTransform(-3.5,1.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0000FF").s().p("AAvCEQgEgOgDgbQgEgZAAgRIABgNIABgOQgBgfgQAAQgVAAgRASQgJAKgPAdQAABDgGANQgFALgLAAQgGAAgGgFQgFgFgBgHIACgIQABgEABgWIABgaIAAh/IACgdQAAgJgCgIQgCgIAAgJQAAgHAFgFQAFgFAHAAQAPAAACAQQADARAAANIgBAnIgBAmIAAAQQAOgTARgKQAPgKASAAQAdAAALATQAIAOABAdIABAiIAEAkQACAVAEAQIAAAFQABAHgGAFQgFAFgIAAQgMAAgEgOg");
	this.shape_3.setTransform(-19,1.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0000FF").s().p("AgKB7QgGgEABgHIAAgVIABgUIgEhkIgngDQgQgCAAgPQAAgIAFgFQAFgGAHABIAlADIgBgYIgBgWQAAgIAGgEQAFgFAHAAQAOAAACAaIABAQIAAAKIgBALIAagDQASAAAGACQAKADABANQAAAIgGAFQgEAFgIAAIgIAAIgJgBIgZADIAEBlIAAAIIABAJQAAAngTAAQgFAAgFgFg");
	this.shape_4.setTransform(-38.2,2.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-48.7,-27,90,54.2);


(lib.skiptomenu = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AATApQgLAGgMAAQgMAAgHgFQgJgGgBgKQgEgYABgQQgBgMADgPQABgIAHAAQAEAAADADQACACAAAEIgBANIgBANIABAXQABALACAGIAGADIAFAAQAKAAANgDIAAgSIgBgPQAAgTACgOQABgIAIAAQADAAADACQADADgBADIgBAhIAAARIAAATIAAAGIAAAGQABAEgDACQgDADgDAAQgHAAgCgJg");
	this.shape.setTransform(16.7,0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AAVAqIgDgTIgBgTIABgGIAAgJQAAgSgHgBQgKAAgHAMQgIALgFAOIgBAIIAAAJIAAAIIABAIQAAAEgCADQgDACgEAAQgDAAgDgCQgCgDAAgEIgBgIIAAgIIABgYIABgYIAAgIIAAgJQAAgDACgDQADgDADABQAIAAABALIAAAKQAPgUAOAAQAOAAAFANQAEAIAAAQIAAAJIAAAGIACATQACAMAAAHQAAAEgCADQgDABgEAAQgHABgBgJg");
	this.shape_1.setTransform(7.5,0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgdAmQgNgMAAgTQAAgVALgQQAMgQATgBQAOAAAJAGQALAFAAANQAAAJgKAHQgEADgOAFIggAQQAFAIAHADQAIADAIAAQAGAAAIgBQAKgDADgFQADgFAEAAQADAAACADQACACAAADQAAAKgPAGQgOAHgMAAQgSAAgNgKgAgRgWQgHAIgDAPIAbgLQAOgIAGgFQgHgIgNAAQgKABgHAIg");
	this.shape_2.setTransform(-2.2,0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgEAzQgCgCAAgEIgCggIgCgdQAAgJgDgGQgGADgHAHIgKALIgEAGIgBANIgBAPIAAAIIABAHQAAADgCADQgDACgEAAQgKAAAAgWIABgQIABgOIAAgOIgBgOQAAgUAJAAQADAAADADQADADAAAEIgBAFIAAAFIAAAJQAFgJAIgIQAJgHAHAAQANAAAEAOQAEgHAHgDQAHgDAIAAQAPAAAFAQQACADACAVIAGAxQABADgDADQgDACgDAAQgIAAgBgIIgDgbIgDgZQgBgGgCgGQgDgIgDAAQgEAAgJAGQgIAFgDADIABAQIACAWQACAOAAAJQAAAEgCACQgDADgEAAQgBAAgDgDg");
	this.shape_3.setTransform(-14.1,0.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(2,1,1).p("AkZh7IIzAAIAAD3IozAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AkZB8IAAj3IIzAAIAAD3g");

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAVAuQgMAGgOAAQgMAAgJgGQgJgGgBgMQgEgZAAgSQAAgNADgRQABgJAIAAQAEAAADADQADADAAAEIgCAOIgBAPIABAZQABAMACAHIAGADIAGAAQALAAAPgEIAAgTIAAgRQAAgVABgPQABgJAJAAQAEAAADACQADADgBAEIgBAlIAAATIAAAVIAAAGIAAAHQAAAEgCACQgDADgEAAQgIAAgCgJg");
	this.shape_6.setTransform(18.3,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AAXAvIgDgWIgBgVIAAgHIABgJQAAgVgIAAQgLAAgIANQgJALgFAQIgBAKIAAAJIAAAJIABAJQAAAEgDADQgCACgFAAQgEAAgCgCQgDgDAAgEIgBgJIAAgJIABgaIACgbIgBgJIAAgJQAAgFADgCQACgDAEAAQAJAAABANIAAALQARgWAPAAQAPAAAGAOQAFAJAAASIAAAKIAAAHQAAAIACAMQACANAAAIQAAAEgDADQgDADgEAAQgIAAgBgJg");
	this.shape_7.setTransform(8.2,0.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AggApQgPgMAAgWQAAgXAMgRQAOgSAVAAQAPAAAKAFQANAHAAAOQAAAJgMAIQgEAEgQAFIgjASQAFAIAJAEQAIAEAJAAQAHAAAIgDQALgDAEgFQADgFAEAAQADAAADACQADADAAADQAAALgRAIQgPAGgOAAQgVAAgNgLgAgTgZQgHAJgEARIAdgMQAQgJAIgGQgJgIgOAAQgLAAgIAJg");
	this.shape_8.setTransform(-2.4,0.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgEA5QgDgDAAgFQAAgLgCgXQgDgVAAgMQAAgKgCgGQgHADgHAHIgMANIgEAGIgCAPIgBARIABAIIABAIQAAAEgDACQgDADgEAAQgLAAAAgZIACgRIABgPIgBgQIgBgPQAAgWAKAAQADAAAEADQADAEAAADIgBAGIAAAGIAAAKQAFgKAKgJQAJgIAHAAQAPAAAEAPQAGgHAHgDQAHgEAKAAQAQAAAGARIAEAcIAHA1QAAAEgDADQgDACgEAAQgIAAgBgIQgCgLgCgTIgDgcIgDgNQgEgJgEAAQgDAAgKAGQgJAGgDADIAAASIADAYQACAQAAAJQAAAFgCADQgDACgEAAQgCAAgDgCg");
	this.shape_9.setTransform(-15.6,0.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#000000").ss(2,1,1).p("AE3CJIptAAIAAkRIJtAAg");
	this.shape_10.setTransform(0,0.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#00FFFF").s().p("Ak2CJIAAkRIJsAAIAAERg");
	this.shape_11.setTransform(0,0.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AATApQgLAGgMAAQgMAAgHgFQgJgGgBgKQgEgYABgQQgBgMADgPQABgIAHAAQAEAAADADQACACAAAEIgBANIgBANIABAXQABALACAGIAGADIAFAAQAKAAANgDIAAgSIgBgPQAAgTACgOQABgIAIAAQADAAADACQADADgBADIgBAhIAAARIAAATIAAAGIAAAGQABAEgDACQgDADgDAAQgHAAgCgJg");
	this.shape_12.setTransform(16.7,1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAVArIgDgUIgBgTIABgHIAAgHQAAgUgHAAQgKAAgHAMQgIALgFAOIgBAJIAAAIIAAAIIABAIQAAAEgCACQgDACgEAAQgDAAgDgCQgCgCAAgEIgBgIIAAgIIABgYIABgYIAAgJIAAgIQAAgEACgCQADgCADgBQAIAAABAMIAAAKQAPgTAOgBQAOAAAFANQAEAIAAARIAAAIIAAAGIACAUQACALAAAHQAAAEgCACQgDACgEABQgHgBgBgHg");
	this.shape_13.setTransform(7.5,0.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgdAlQgNgLAAgTQAAgVALgPQAMgSATABQAOAAAJAEQALAHAAAMQAAAJgKAHQgEADgOAFIggAQQAFAHAHAEQAIAEAIAAQAGgBAIgCQAKgDADgEQADgFAEAAQADAAACACQACACAAAEQAAAJgPAIQgOAFgMAAQgSAAgNgKgAgRgWQgHAIgDAPIAbgLQAOgIAGgGQgHgGgNgBQgKAAgHAJg");
	this.shape_14.setTransform(-2.2,0.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgEAzQgCgCAAgEIgCggIgCgdQAAgJgDgGQgGADgHAHIgKALIgEAGIgBANIgBAPIAAAIIABAHQAAADgCADQgDACgEAAQgKAAAAgWIABgQIABgOIAAgOIgBgOQAAgUAJAAQADAAADADQADADAAAEIgBAFIAAAFIAAAJQAFgJAIgIQAJgHAHAAQANAAAEAOQAEgHAHgDQAHgDAIAAQAPAAAFAQQACADACAVIAGAxQABADgDADQgDACgDAAQgIAAgBgIIgDgbIgDgZQgBgGgCgGQgDgIgDAAQgEAAgJAGQgIAFgDADIABAQIACAWQACAOAAAJQAAAEgCACQgDADgEAAQgBAAgDgDg");
	this.shape_15.setTransform(-14.1,1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#000000").ss(2,1,1).p("AEah7IAAD3IozAAIAAj3g");

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#0066CC").s().p("AkZB8IAAj3IIzAAIAAD3g");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},1).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12}]},1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-29.2,-16.9,58.6,30.5);


(lib.Copyright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAbAHIgDgKIgEAKQgEAIgDAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBgBAAgBIgCgIIgBgHQgGASgCAAIgDgBIgBgCIABgCQADgFABgFIACgNQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAEAAACAJIADAKIACgGIADgJQADgEACAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAEAKIACAGIACAIIABACIgBACIgCABQgDAAgDgJgAgTANIgBgIIAAgGIgBgHIgFAAIgGAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAgBAAAAQAAgBAAgBQAAAAABgBQAAAAABgBQAAAAABAAIAFABIAEAAIAPAAIADgBIAEAAQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAABAAAAQAAAAAAABQAAAAgBAAIgOAAIAAAIIABAFIABAEIABAEIgCACIgCABQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAgBAAAAg");
	this.shape.setTransform(57.3,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgLAYQgGgDgBgEIABgDQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAIAEACIAEABIAFABIAFgBQADgBAAgDQABgGgJgCIgCgBIgIgDQgEAAAAgFQAAgKAIgEIAHgCIAIgDIAEgBIADABIABAEIABADIAAAEIgBADIgCABQgBAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIgCgFIgJADQgFADgBAEIADABQAIACAFACQAHADAAAJQAAAHgGAEQgFADgGAAQgFAAgGgCg");
	this.shape_1.setTransform(51,2.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgLATQgHgGABgKQAAgGAFgKQAHgKAGAAQAEAAAGACQAGACABAEIgBADQgBAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgDgBIgBgBQgDgCgGAAQgCAAgFAIQgDAHAAADQAAAGADAEQAEADAEAAIAGgCIAEgCIACgBIAEABIABADQgBADgGADQgGADgEAAQgHAAgGgFg");
	this.shape_2.setTransform(46.6,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgDAfQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAAAIAAgJIAAgIIAAgKIAAgIQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBIACgBIACABQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABIAAAIIgBAKIAAAIIABAJQAAAAAAAAQAAABgBAAQAAABAAAAQAAAAgBAAIgBABIgDgBgAgBgXQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQAAAAAAAAQAAAAAAgBQABABAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBAAAAgBg");
	this.shape_3.setTransform(43.1,1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAKAVIgBgJIgBgKIABgDIAAgDQAAgKgEAAQgFAAgCAFQgEAGgCAGIgBAEIAAAFIAAADIAAAFIgBADIgDABIgDgBIgBgDIAAgFIgBgDIABgMIAAgLIAAgFIAAgEIABgDIAEgBQAEAAAAAFIAAAGQAHgKAGAAQAHAAADAGQACAEAAAJIAAAEIAAACIABAKIABAJIgBADIgDABQgEAAgBgEg");
	this.shape_4.setTransform(39.5,2.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_5.setTransform(34.8,2.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AALAhIgBgLIgBgKIAAgDIAAgEQAAgGgEAAQgFAAgDADIgGAKQAAARgCACQAAABgBABQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDIABgBIAAgHIAAgHIAAgeIABgHIgBgFIAAgEQAAAAAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQAEAAAAAEIABAIIAAAKIAAAJIAAAEQADgFAEgCQACgDAFAAQAHAAADAFQABADABAGIABAJIAAAIIACAKIAAABQAAABAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIgDABQgEAAgBgDg");
	this.shape_6.setTransform(30,1.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgLATQgHgGABgKQAAgGAFgKQAHgKAGAAQAEAAAGACQAGACABAEIgBADQgBAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgDgBIgBgBQgDgCgGAAQgCAAgFAIQgDAHAAADQAAAGADAEQAEADAEAAIAGgCIAEgCIACgBIAEABIABADQgBADgGADQgGADgEAAQgHAAgGgFg");
	this.shape_7.setTransform(25,2.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgOATQgGgGAAgKQAAgKAFgHQAGgJAJAAQAGABAFACQAGADAAAHQAAAEgFADIgKAEIgOAHQACAEAEABQAEADACAAIAIgBQAFgCABgDQABAAAAAAQAAgBABAAQAAAAABAAQAAAAAAAAIADAAIABADQAAAFgIADQgGADgHABQgIgBgGgEgAgIgKQgDAEgCAGIANgFQAGgDAEgDQgEgDgGgBQgEAAgEAFg");
	this.shape_8.setTransform(20.3,2.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAaAgIgCgGIgBgIQgCgHgEgWIgJAYIgDAJIgDAIQgBAEgCAAQgDgBgBgDIgCgEIgBgFIgIgfIgCAHIgFAWIgCAMQgBAEgDAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgEQAAgHADgLIAFgPIADgOQACgKABgDQACgCADAAQACAAACADQACAEABAMQADAOAFAPQAFgPAEgSIACgGIACgHQABgDADAAQAEAAACAIIACAKQADASADAOIACAHIACAHQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgCABQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBgBg");
	this.shape_9.setTransform(13.8,1.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgQAUIAAgdIAAgEIABgFQAAgEADAAQAFAAAAAHQAHgIAKAAQADAAACADQACACAAAGIAAADQgBAFgEAAQgEAAAAgEIAAgDIAAgEQgHABgCADQgEADgDAGIABAWQAAAEgFAAQgEAAAAgEg");
	this.shape_10.setTransform(5.1,2.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_11.setTransform(0.5,2.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgBAZQAAAAgBAAQAAgBAAAAQAAAAAAgBQgBAAAAgBIgBgPIgBgOQAAgFgBgCQgDABgDADIgFAGIgDADIAAAGIgBAHIABAEIAAADQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABQgFAAAAgLIAAgIIABgGIgBgHIAAgHQAAgKAFAAIACACQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAADIgBACIAAAFQADgFAEgDQAFgEADAAQAGAAACAHQACgEADgBQAEgCAEAAQAHAAADAIIACAMIADAYIgBADIgDABQgEAAgBgEIgBgOIgCgLIgBgGQgCgEgCAAIgFADIgGAEIAAAHIABALIABALIgBADIgDACQAAAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBg");
	this.shape_12.setTransform(-5.2,2.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgBAZQAAAAgBAAQAAgBAAAAQAAAAAAgBQgBAAAAgBIgBgPIgBgOQABgFgCgCQgDABgDADIgFAGIgCADIgBAGIgBAHIABAEIABADQAAABgBAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABQgFAAAAgLIABgIIAAgGIAAgHIgBgHQAAgKAEAAIADACQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAADIgBACIAAAFQADgFAEgDQAFgEADAAQAGAAABAHQADgEADgBQADgCAFAAQAHAAADAIIACAMIADAYIgCADIgCABQgEAAgBgEIgCgOIgBgLIgBgGQgCgEgCAAIgFADIgGAEIAAAHIABALIABALIgBADIgDACQAAAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBg");
	this.shape_13.setTransform(-12.2,2.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_14.setTransform(-18.1,2.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgQAUIAAgdIAAgEIABgFQAAgEADAAQAFAAAAAHQAHgIAKAAQADAAACADQACACAAAGIAAADQgBAFgEAAQgEAAAAgEIAAgDIAAgEQgHABgCADQgEADgDAGIABAWQAAAEgFAAQgEAAAAgEg");
	this.shape_15.setTransform(-22.4,2.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgVAeQgFgGgBgMQABgMAFgKQAFgMAIgIQAHgEAEAAQAEAAAGACQAIAEAAADIgBADIgEABIgCgBQgHgDgEAAQgDgBgCAEIgGAGQgKAOAAAOQABAIACADQACAEAIAAQAGgBAGgFQAGgEACgLQgMABgGAEIgDABQAAgBAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQAIgEAXAAIADABIABACQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQgDANgIAJQgJAHgKABQgKgBgGgFg");
	this.shape_16.setTransform(-27.7,1.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgNAhIgBgDIACgJIAKgWQAFgOAHgIIABgBIgVAAIgJgBQgFAAAAgEQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAQAAIAPABIAIAAQAFAAAAACQAAADgDADIgEAFQgGAGgFAKIgHAPIgCAKIgEAKQgBABAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIgDgBg");
	this.shape_17.setTransform(-36.2,1.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AABAiIgHAAIgFgBQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQgBgEAIAAIACAAIABAAIAAgHIgBgGIABgPIABgRQgFAFgCAAIgDgBIgBgDQAAgDADgCIAHgGQACgEAEAAQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAADIAAADIAAAEIAAAEIgBAPIgBANIAAAGIABAGIAFAAQAAAAAAAAQABAAAAABQABAAAAAAQAAAAABABIAAADIAAADIgDABg");
	this.shape_18.setTransform(-41,1.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgSAXQgFgKAAgNQAAgMAGgKQAHgMAKAAQAMABAGAJQAGAJAAANQAAARgGAKQgGAJgMAAQgMABgGgMgAgLgRQgEAIAAAJQAAAMAEAHQAEAHAHAAQAIABAEgLQADgIAAgJQAAgMgDgGQgEgGgIAAQgGAAgFAIg");
	this.shape_19.setTransform(-45.9,1.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AANAhIgDgBIgHAAIgFABIgFAAIgFAAIgBAAIgCAAQgDAAgBgDIAAgFQAAgKAGgHQACgDALgFIAHgHQADgEAAgGQAAgDgDgCQgDgCgDAAQgDAAgDADIgGAEIgDACQgFAAAAgEQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAFgFAEgCQAFgDAEAAQAHAAAFAEQAGAEAAAHIgBAIIgEAHQgDACgIAFQgGAFgDADQgFAFABAHIAJgBIALAAIAGABQAEABAAADQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAIgDABIgDAAg");
	this.shape_20.setTransform(-51.3,1.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgeAAQAAgKALgJQALgKALAAQAOAAAHAIQAHAIAAAMQAAAJgJAKQgKALgMAAIAAABQgeAAAAgegAgOgOQgIAGAAAIQAAAMAGAFQAGAEAKAAQAJAAAIgIQAGgIAAgGQAAgJgEgFQgFgGgIAAIgCAAQgKAAgIAHgAgKAJQgGgEAAgFQAAgGAIgFQAGgFAFAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAIgCgBIgBAAQgDAAgEADQgEACAAADQAAABADACIAFABQABAAAEgCIAEgCIADAAIABADQAAADgEADQgGADgDAAQgFAAgFgDg");
	this.shape_21.setTransform(-57.7,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.3,-7.1,126.6,16.6);


(lib.general_buttoncolor = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//this.play();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#D5FFD7","#61EF01","#1DA400","#004A00"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgvAAgjgjQgjgjAAgwQAAgvAjgjQAjgjAvAAQAwAAAjAjQAjAjAAAvQAAAwgjAjQgjAjgwAAIAAAAg");
	this.shape.setTransform(11.9,11.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,23.7,23.6);


(lib.Skater = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A06800").s().p("AAEASIgEgBQAAgEgEgBQgDgBgFAAIgHABIgGAAIgGAAIAAgDIgFAAQgMAAgCgJQAEABACgBQADgCgBgGIgBgCIAAgBQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAgBAAAAIgBgBIAGgBIAAAAIACAAIAOgDIACAAIAJgBIACAAIgBAAIgBABIgEAEIgBACIAAABIgJACIgCABQAAAAAAAAQAAAAAAABQAAAAAAAAQAAABgBAAIgCAAIgBAAIgBgBIgDACIAEAEQAGAGAOAAIABAAIAFAAIADABQAMADAEgJIADgBIAAAAIABAAIACAAIACAAIAGgBIACAAIAVABIACAAIgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBABAAAAIgBADIgBAAIgCACQgCACgBAEQgDAAgCgBQgHgFgMAAIAAAGQABAHgGAAIgBAAIgGgBg");
	this.shape.setTransform(14.1,-9.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000099").s().p("AgIATIAAgFIAAgBIAAgFIAAgQQAOgHAPgDIAAADQADAAACgCIACgCIALAEIAAAHIAAAGIgGgCIgMgEQgBAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgHAPgMAKIgFACIgBABIAAgBgAghALQgEgDgBgGIAAgBIAAgDIAAAAQAGgEAEgEQABgBAAAAQAAgBAAAAQABgBAAgBQAAAAAAgBIAGAAIAGAXIAAACIAAAEIgCAAIgEAAIgCAAQgHAAgEgDg");
	this.shape_1.setTransform(-0.5,5.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000000","#926130","#996633"],[0,0.169,1],9.5,-39.6,93.2,-39.6).s().p("AAJAQQgPgCgQgEIgGgBIABgEIADAAIABAAIAIgCIAGgDQAKgDAGgMIAEABQAMACAGAAIAAAHQgKAJAFAGQgFABgFgBIgCABIAAAAIAAABIACADIACAAIgDAAIgEABg");
	this.shape_2.setTransform(1.2,8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#C6FFFF").s().p("AAAgBIAAACIAAABg");
	this.shape_3.setTransform(19.8,-9.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFCC99").s().p("Ah7BYIgHgFIAFgHIABgGIAAgGQgBgagLgRQAAAAABAAQABAAAAAAQABAAAAAAQABgBAAAAQABgBAAAAQAAAAAAgBQABgBAAAAQAAgBAAgBIAAgGQAQgGAKAJIAGAIIALAOIgBAFIgCAFQgMAYgQAVIgFgBgAAuA0QAKABgEgNIAAgGIAAgGQgCgegRAXIgLgEQABgFgIgNIgBgGIgCgDIgFgKIgEgGIAAgDIgBgBIAAAAIACgDIACgBIADgCIACgBIAHgFIADgBIAHgDIAFgBIAJABIABAAIACADIADADIACABQAOADANAEIAEgBIAAAAIABAAIAFAAIABgFQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIAAgGQAIgDAKgCIANgBIAGAAIADAAQgLgHgNAAQgNAAgPAHIAAAGIgDgBQgDgLAAgNIAIgCQANgCAMAHIABAAIgCgDQgBgGAAgGIAGAAQAMAGAMADIAAgDIAAgGQAGgBADAAQAEACAAAFIgBAGQAAADACACQAFAIgKAHIgIAFIgBAAQAAABAAAAQAAABAAAAQAAABgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAQAIAEAHgDQAJgDAIgQQACgDAAgEQAAgDgDgDIAAgGIAAgGQAGAAAFADQAAAAAAAAQAAABABAAQAAAAAAABQAAABAAAAQAQAdgXARIgBABIgBAAIgFADIgOADIgBAJIAEAAIANAAIAGgBQAVAEASAGQAOAFANAFQAAAAAAAAQABAAAAAAQAAABAAABQAAAAAAABQAAABAAAAQAAABAAABQAAAAgBAAQAAABAAAAIghASIghAPQgBAAgBAAQAAAAgBAAQAAAAgBABQAAAAAAAAQgGAIgLADIgEAAIgGAAIgMAAIgBgGIgDgDIgCgDIgGABIgDACQgCgHgOgCIAAgBIACgCIAAgBQAHgDgCgCIABgCIACgBIACgCIABgBIABgBIAGAIQABAAAAABQABAAAAAAQABABAAAAQABAAABAAIAFAGIABAGQARALAPgQQABAAAAAAQABgBAAAAQABAAAAAAQABAAABAAQAZgGACgZIgDAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBAAAAAAQgRgEgTgDIAAgDQgTAJgSAMIgBAAIAAAAIgEACIgCABQgBAAAAAAQgBAAgBAAQAAABgBAAQAAAAgBABIgFADIgBABQgFACgCAEIgBABIAAACQgEAEgGABIAAAGIgBAEIgBABIgEAEIgBABIgBABIgBABIgBACIgBAAIgBAAQgDABgBACIgBABIgBABIAAgHgAA5A5IADgEIABAAIACgCIAAACIgBAAIgBAAIgBABIgCADIgBAAIAAAAgAhXAuIAFgHIABgFIALgIIAAAAIAEgEIgBgBIABAAQAFgGADgHIABgFIAEgCQAKgDAHgIIACgEQACgCAAgEQAGgJAKgGIADgCIAFgBIAAAAIADgBIAAABIgDAAIACADIABAAIAAADIADADIABADIABAGIAAAKIACAJIABAEQAAADgCACQgCAEgHADIgDAAQgEgmgXAgIAAAGQAAABAAABQAAAAgBABQAAABAAAAQAAAAgBABIgGAGIgBABIgCACIAAAAIgGAHIgDACIAAAAIgEADIgBAAIgGAFIAAAGIgGABIgFABQgIAAABgIgAjNAiIAFgIQACgFgDgDQgLgMgGgQIgDgKIgBgGIAAgGQAKAAAHgDIACgCIAFgBIALAAIACAAIAGAAIAAADIgBABIgBABQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAIAAAMIACAKIABACIADABQAKAUAQgXIABgCIABgBIABAAIABAAIAAAAIADgCQAHgEAEgJIABgBIABgCIAIgEQAIgGAIgHQASgPAQATIACAJQACAIADAHIAGAKIAEAEQAAABAAAAQABABAAAAQAAABAAAAQAAABAAABQgDAAgCABIgEAAIgFgKQgEgHgEgDQgJgFgNAFIgKAHIgFgBQgNADgLAHIgCgDQAAADgCACIAAAAIgEADQgMAOgTAGIgBAGQgCANgJAGQgQgBACgLgAgwgTIgBgBIgBAAIgFgBQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAAAgBIADgBIABAAQADABAGgDIABgBIAAAIQgBABAAABQgBAAAAABQgBAAAAAAQgBAAAAAAQgCAAgDgCgAgWgqIABABIgCAAIABgBg");
	this.shape_4.setTransform(0.1,2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AiCB0IgFgaIAGAAIgMg3QgfAKgMAeIAAAAQgTAEgLgNIAGgNIgZhBIAGAAIAAgGIAVgLQAWACAWgDIgCAEQgCADgDAIIgDAFIAAAVIARgLIABAAIAEgDQAEgBACgEQADgGAFgEIABAAIABAAIAAgBIAAAAIALgLQAQgKASABQANAEADALIAIAIIACACQACAHAIADIABAAQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIAGABIAAAAIABAAQAGAEADgEIABgIIAEgDQAFgFAGgFIADAAQAFAFAHgCIABAAIgGABIgDACQgJAGgHAJQAAACgBACIgDAEQgHAIgKAFIgDACIgBAFQgEAHgFAGIAAAAIABABIgEAEIgBAAIgLAIIgBAFIgFAHQAAAKANgDIAGgBIgyAugAiBAdIAAAGQAAABAAABQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAQALARABAaIAAAGIgBAGIgFAHIAHAFIAGABQAPgUAMgZIACgFIABgFIgKgOIgGgIQgHgFgIAAQgFAAgHACgAjJgRIgDACQgGADgLAAIAAAGIACAGIACAIQAGASAMAMQADADgDAFIgEAIQgDALAQABQAJgGADgNIAAgGQATgGAMgOIAEgFIABAAQABgCAAgDIADADQALgHANgDIAEABIAKgFQANgFAJAFQAFACADAGIAGAMIADgCQADgBADAAQAAgBAAAAQAAgBgBgBQAAAAAAgBQAAAAgBgBIgEgEIgFgIQgDgHgDgIIgBgJQgRgTgRAPQgIAHgJAGIgIAEIgBACIAAABQgEAIgIADIgCACIAAAAIgBAAIgCAAIgBABIgBACQgQAagKgXIgDgBIAAgCIgCgIIgBgMQABAAABAAQAAAAABAAQAAAAABAAQAAgBABAAIAAgBIABgBIAAgDIgGAAIgCAAIgKAAIgFABgAhhAIIgEABQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAIADAIIAEAGQAGAHALACIAFAAIACAAIgBgGQgEgSgKgDIgEgBIgFABgAAaBeIgCgCIAAgBIAAgBIACgBQAFACAFgCQgEgGAJgLIAAgGQgGAAgMgDIgEAAQgGAMgMAFIgEACIgIACIgBAAIgDAAIgBAFIgIgCIgHAAIAAgCIgCgCIgCAAIgQgRIgGAHIgKgBIAAgGIAGgFIAAAAIAEgDIABAAIACgCIAGgHIABAAIACgCIAAgBIAHgGQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAgBIAAgGQAYggAEAmIADAAQAGgDADgEQABgCAAgDIAAgGIgCgJIgCgIIAAgGIAAgDIgEgDIABgDIgBAAIgCgDIADAAIAAACQADgHAJgDQAQgPAVAFIAEACIACAFQAGgFgHgJIgFgCQgEgGgBgKIAfgJQgbAHgKgWQAYAHAGgKIgVgFIgDgKIABAAIAkAMQAEgIAIgJIACgBQAXgMAbAFIgQAMIAFAGIBCABIAAADIAAAGIgBABIgCABIgDAEQgHALAEAWQgBAAgBABQAAAAAAAAQgBAAAAAAQAAAAAAAAQgGAXgPAKIgHADIAAAGQAnAAAVAOQAFAEAEAFQAFAGADAGIgDAAQAAABAAABQAAAAgBABQAAAAAAABQAAAAgBAAQgIAGgFAIIgRAJIgUAKIgGADIgQADQAAABAAABQAAAAAAABQAAAAAAAAQAAAAgBAAQgIADgJAAIgBADQgNACgJAHIgZAEIgDAAIgCgBIgEgCIgDgDIgFgFIgBgCIgEgGQAAAAgBgBQAAAAgBAAQAAgBgBAAQgBAAAAAAIgBAAIAAgCIgBACIgBAAIgEAEIAAAAIgCABIgCABIAAAAIgNAJIgHAFIgBAAIgFABIgCAAgAAvBPIACgBIAAgBQACgCADgBIAAAAIABAAIABgCIABgBIACgBIABgBIADgEIABgBIABgEIAAgGQAHgBAEgEIAAgCIAAgBQADgEAEgCIABgBIAGgDQAAgBABAAQAAAAABAAQAAgBABAAQABAAAAAAIACgBIAEgCIABAAIABAAQASgNATgKIAAADQASADASAGQAAAAAAAAQAAAAABABQAAAAAAABQAAAAAAABIgDAAIgBgBIgDAAIgBAAIgKgBIgBAAIgFgBIgEgBIgEAAQAAAAAAAAQAAgBgBAAQAAAAgBAAQgBAAAAAAIgBAAIgBABIAAgCQgBAAgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgKALIgBAAIgDACIgFADIgHADQgBABAAAAQAAABgBAAQAAABAAAAQAAAAAAABQABADAEAAIABABIAFAGIAAAAIAEAAQAIAEAEgEIAGAAIABAAIAKgDIABAAIAAgBIADgBIACgCIAJgEIADgDIACgCIABgBIAAgBIABAAIACgCQACgCgBgDIABgDIADAAQgDAZgZAGQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAAAQgQAQgRgLIgBgGIgFgGQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAIgGgIIgBABIgBABIgDACIgBABIgBACQABACgGADIAAABIgCACIAAABQANACACAHIAEgCIAFgBIADADIACADIABAGIANAAIAGAAIAEAAQAKgDAGgIQABAAAAAAQAAAAABgBQAAAAABAAQABAAAAAAIAhgPIAhgSQABAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAAAgBgBQgMgGgPgFQgSgGgVgCIgGAAIgNAAIgDAAIAAgIIAOgDIAFgDIACAAIABgBQAWgRgQgdQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBAAQgFgDgGAAIAAAGIAAAGQADADAAADQAAAEgCADQgIAQgJADQgHADgHgEQAAAAABAAQABAAAAAAQABgBAAAAQABAAAAgBQABAAAAAAQAAgBAAAAQABgBAAgBQAAAAAAgBIAAAAIAIgFQALgHgGgIQgBgCAAgDIAAgGQABgFgFgCQgDAAgFABIAAAGIAAADQgNgDgMgGIgGAAQAAAGACAGIABADIgBAAQgLgHgOACIgIACQAAANADALIAEABIAAgGQAPgHANAAQANAAALAHIgDAAIgHAAIgNABQgJACgIADIAAAGQAAAAABAAQABAAAAAAQABABAAAAQABAAAAABQABAAAAABQAAAAAAABQABAAAAABQAAABAAAAIgBAFIgFAAIgCAAIAAAAIgEABQgNgEgNgDIgCgBIgEgDIgCgDIAAAAIgKgBIgEABIgIADIgCABIgHAFIgCABIgDACIgCABIgCADIgBAAIABAAIAAABIAAADIAEAGIAGAIIABADIABAGQAIAPgBAFIgBADQgDABgDAAIAAgDQgPADgNAHIAAASIAAAGIAAAAIAAAFIAAABIABAAIAEgDQAMgJAIgRQAAAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAIANAFIAGABIAAgGIAAgHQARgZABAgIAAAGIABAGQADANgKgBIAAAHgAggAuQgFAFgGADIAAAAIAAAGIAAAAQABAHAFADQAFADAIgBIADAAIADAAIgBgEIAAgCIgFgZIgHAAQAAABAAABQAAABAAAAQAAABgBAAQAAABAAAAgACHhPQAEABACAEIAEABIAHABQAGAAAAgHIgBgGQAMAAAIAEQACACADAAQABgEACgDIABgBIACAAIABgDQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABgBIAAAAIgCgBIgVAAIgBAAIgHABIgCAAIgCAAIAAABIAAABIgDABQgEAIgPgDIgCAAIgFAAIgBAAQgOAAgHgIIgEgFIADgBIABAAIACABIACgBQAAAAABAAQAAAAAAgBQAAAAAAAAQAAgBgBAAIADgBIAJgBIAAgBIAAgCIAFgFIABAAIABgBIgDAAIgIABIgDABIgOACIgBABIgBAAIgFABIAAAAQAAABABAAQAAAAAAABQAAAAABAAQAAAAABAAIAAAAIAAACQABAHgCACQgDACgDAAQABAJANAAIAEAAIAAADIAGAAIAHAAIAHgBIABAAIAGABgAA9BbIAAAAIAAAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-23.4,-11.9,46.8,23.8);


(lib.Skateboard_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.5,1,1).p("AAXgoQgCAAgDAAQgJgCgGgIQgDgHAAgJQAAgJAGgFQADgCADgBQAEgBAFABQABABACAAQAHACAEAHQAGAIAAAIQgBAJgGAFIgBAAQgEADgGAAgAAaBXQgHgCgGgHQgFgHABgJQABgJAGgFQAHgFAIACIAAAAQAFABADADQAEACACAEQAGAIAAAIQgBAJgHAFQgEADgFAAQgDAAgDAAQgBAAgBgBgAgihXQADgBAEABQAIACAGAIQAGAIgBAIQAAAJgHAFQgHAFgJgCQgDgBgDgBQgFgDgDgFQgBgBgBgBQgEgHABgHQABgIAFgFQABgBABAAQAEgDAEAAgAgjAqQAGgDAHACQAIACAGAHQAGAIgBAJQAAAJgHAEQgHAFgJgCQgCAAgBgBQgHgCgEgGQgBgBAAgBQgFgHABgIQAAgBABgBQABgHAGgFQABAAABgBg");
	this.shape.setTransform(0.6,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#33CCFF","#0615FF","#030BFF","#0000FF"],[0,1,1,1],-5.1,-8.8,5.1,8.9).s().p("AgIBpQgHgFgFgIQgDgEgCgGIgBgFIAEABQAJACAGgFQAHgEAAgJQAAgJgFgIQgFgHgJgCQgGgCgGADIgBgDQAAgKACgJIAAgCQAAgPgCgQQgBgRgBgQIAHACQAJACAGgFQAHgFABgJQAAgIgGgIQgFgIgJgCIgGAAQAEgLAKgIIAOACIAHAEQAGAIAFAJIgGADQgHAFgBAJQgBAJAGAHQAGAIAIACIAGAAIACAOIAAACIADAaIACAjIABAIQgIgCgHAFQgHAFgBAJQgBAJAGAHQAFAHAHACIgBAIQAAADgBACIgHAHQgEAFgGAFQgKgBgIgGg");
	this.shape_1.setTransform(0.2,-0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgYBrQgEgEgCgEIgKgaIgBgFIABACQAEAGAHACQgHgCgEgGIgBgCQgFgHABgIIABgCIgBgKIACgkQABgRgCgUIgBgHQgCgKAAgLIACACQADAFAFACQAAARACARQACAQAAAPIgBACQgCAJABAKIAAADQAGgDAHACQAIACAGAHQAGAIgBAJQAAAJgHAEQgHAFgJgCIgDgBIABAFQABAGAEAEQAEAIAHAFQAJAGAJABQAGgFAFgFIAGgHQACgCAAgDIABgIQgHgCgGgHQgFgHABgJQABgJAGgFQAHgFAIACIAAgIIgDgjIgDgaIAAgCIgCgOQAGAAAEgDIABgBIABAQQABAPACAPQADARgBATIgBALQgDgDgFgBIAAAAIAAAAQAFABADADIAGAGQAGAIAAAIQgBAJgHAFQgEADgFAAIgBAAIAAAAIgBAAIgBAAIgDAAIgCgBIACABIADAAIABAAIABAAIAAAAIABAAQgCAHgFAHQgEAFgFALIgTAFQgPgCgIgKgAglAnQgGAEgBAIQABgIAGgEIACgBIgCABgAASgsQgJgCgGgIQgDgHAAgJQAAgJAGgFIAGgDQAEgBAFABIADABIgDgBQgFgBgEABQgEgJgHgIIgHgEIgOgCQgKAIgEALIAHAAQAIACAGAIQAGAIgBAIQAAAJgHAFQgHAFgJgCIgGgDQgFgCgDgFIgCgCQgEgHABgHQABgIAFgFQADgJAFgIQADgEAEgDQASgNAQAMQANAHAEANIACAGQAHACAEAHQAGAIAAAIQgBAJgGAEIgBABQgEADgGAAIgBAAIgEAAgAgqhYIgCABIACgBQAEgDAEAAQgEAAgEADgAgvg8IAAAAg");
	this.shape_2.setTransform(0.6,-0.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(0.5,1,1).p("AAXgoQgCAAgDAAQgJgCgGgIQgDgHAAgJQAAgJAGgFQADgCADgBQAEgBAFABQABABACAAQAHACAEAHQAGAIAAAIQgBAJgGAFIgBAAQgEADgGAAgAAfAtQgIgCgHAFQgGAFgBAJQgBAJAFAHQAGAHAHACQABABABAAQADAAADAAQAFAAAEgDQAHgFABgJQAAgIgGgIQgCgEgEgCQgDgDgFgBgAglguQADABADABQAJACAHgFQAHgFAAgJQABgIgGgIQgGgIgIgCQgEgBgDABQgEAAgEADQgBAAgBABQgFAFgBAIQgBAHAEAHQABABABABQADAFAFADgAgdBSQABABACAAQAJACAHgFQAHgEAAgJQABgJgGgIQgGgHgIgCQgHgCgGADQgBABgBAAQgGAFgBAHQgBABAAABQgBAIAFAHQAAABABABQAEAGAHACg");
	this.shape_3.setTransform(0.6,-0.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#ED3DED","#4DFF00","#030BFF","#0000FF"],[0,1,1,1],-5.1,-8.8,5.1,8.9).s().p("AgIBpQgHgFgFgIQgDgEgCgGIgBgFIAEABQAJACAGgFQAHgEAAgJQAAgJgFgIQgFgHgJgCQgGgCgGADIgBgDQAAgKACgJIAAgCQAAgPgCgQQgBgRgBgQIAHACQAJACAGgFQAHgFABgJQAAgIgGgIQgFgIgJgCIgGAAQAEgLAKgIIAOACIAHAEQAGAIAFAJIgGADQgHAFgBAJQgBAJAGAHQAGAIAIACIAGAAIACAOIAAACIADAaIACAjIABAIQgIgCgHAFQgHAFgBAJQgBAJAGAHQAFAHAHACIgBAIQAAADgBACIgHAHQgEAFgGAFQgKgBgIgGg");
	this.shape_4.setTransform(0.2,-0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgYBrQgEgEgCgEIgKgaIgBgFIABACQAEAGAHACQgHgCgEgGIgBgCQgFgHABgIIABgCQABgIAGgEIACgBQAGgDAHACQAIACAGAHQAGAIgBAJQAAAJgHAEQgHAFgJgCIgDgBIABAFQABAGAEAEQAEAIAHAFQAJAGAJABQAGgFAFgFIAGgHQACgCAAgDIABgIQgHgCgGgHQgFgHABgJQABgJAGgFQAHgFAIACIAAgIIgDgjIgDgaIAAgCIgCgOQAGAAAEgDIABgBIABAQQABAPACAPQADARgBATIgBALIAGAGQAGAIAAAIQgBAJgHAFQgEADgFAAIgBAAIAAAAIgBAAIgBAAIgDAAIgCgBIACABIADAAIABAAIABAAIAAAAIABAAQgCAHgFAHQgEAFgFALIgTAFQgPgCgIgKgAAfApQAFABADADQgDgDgFgBIAAAAgAgtApIACgkQABgRgCgUIgBgHQgCgKAAgLIACACQADAFAFACQgFgCgDgFIgCgCQgEgHABgHQABgIAFgFIACgBQAEgDAEAAQgEAAgEADIgCABQADgJAFgIQADgEAEgDQASgNAQAMQANAHAEANIACAGQAHACAEAHQAGAIAAAIQgBAJgGAEIgBABQgEADgGAAIgFAAQgJgCgGgIQgDgHAAgJQAAgJAGgFIAGgDQAEgBAFABIADABIgDgBQgFgBgEABQgEgJgHgIIgHgEIgOgCQgKAIgEALIAHAAQAIACAGAIQAGAIgBAIQAAAJgHAFQgHAFgJgCIgGgDQAAARACARQACAQAAAPIgBACQgCAJABAKIAAADIgCABQgGAEgBAIIgBgKg");
	this.shape_5.setTransform(0.6,-0.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(0.5,1,1).p("AAXgoQgCAAgDAAQgJgCgGgIQgDgHAAgJQAAgJAGgFQADgCADgBQAEgBAFABQABABACAAQAHACAEAHQAGAIAAAIQgBAJgGAFIgBAAQgEADgGAAgAAiBYQAFAAAEgDQAHgFABgJQAAgIgGgIQgCgEgEgCQgDgDgFgBIAAAAQgIgCgHAFQgGAFgBAJQgBAJAFAHQAGAHAHACQABABABAAQADAAADAAgAgshTQgFAFgBAIQgBAHAEAHQABABABABQADAFAFADQADABADABQAJACAHgFQAHgFAAgJQABgIgGgIQgGgIgIgCQgEgBgDABQgEAAgEADQgBAAgBABgAgsA3QgBABAAABQgBAIAFAHQAAABABABQAEAGAHACQABABACAAQAJACAHgFQAHgEAAgJQABgJgGgIQgGgHgIgCQgHgCgGADQgBABgBAAQgGAFgBAHg");
	this.shape_6.setTransform(0.6,-0.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgYBrQgEgEgCgEIgKgaIgBgFQgFgHABgIIABgCQABgIAGgEIACgBQAGgDAHACQAIACAGAHQAGAIgBAJQAAAJgHAEQgHAFgJgCIgDgBQgHgCgEgGIgBgCIABACQAEAGAHACIABAFQABAGAEAEQAEAIAHAFQAJAGAJABQAGgFAFgFIAGgHQACgCAAgDIABgIIACABIACAAIACAAIABAAIABAAIgBAAIgBAAIgCAAIgCAAIgCgBQgHgCgGgHQgFgHABgJQABgJAGgFQAHgFAIACIAAAAQAFABADADQgDgDgFgBIAAAAIAAgIIgDgjIgDgaIAAgCIgCgOQAGAAAEgDIABgBIABAQQABAPACAPQADARgBATIgBALIAGAGQAGAIAAAIQgBAJgHAFQgEADgFAAQgCAHgFAHQgEAFgFALIgTAFQgPgCgIgKgAgtApIACgkQABgRgCgUIgBgHQgCgKAAgLIACACQADAFAFACQgFgCgDgFIgCgCQgEgHABgHQABgIAFgFQADgJAFgIQADgEAEgDQASgNAQAMQANAHAEANIACAGQAHACAEAHQAGAIAAAIQgBAJgGAEIgBABQgEADgGAAIgFAAQgJgCgGgIQgDgHAAgJQAAgJAGgFIAGgDQAEgBAFABIADABIgDgBQgFgBgEABQgEgJgHgIIgHgEIgOgCQgKAIgEALIAHAAQAIACAGAIQAGAIgBAIQAAAJgHAFQgHAFgJgCIgGgDQAAARACARQACAQAAAPIgBACQgCAJABAKIAAADIgCABQgGAEgBAIIgBgKgAgqhYIgCABIACgBQAEgDAEAAQgEAAgEADg");
	this.shape_7.setTransform(0.6,-0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},9).to({state:[{t:this.shape_1},{t:this.shape_7},{t:this.shape_6}]},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5.5,-12.1,12.3,24);


(lib.Rock3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#996600").s().p("AAFALQgIgJgHgJQABAAAAAAQABgBABAAQAAAAABAAQAAgBAAAAQACgBAAgEQAYgDgOAgQAAgBAAAAQAAgBAAgBQAAAAAAgBQgBAAAAAAg");
	this.shape.setTransform(-0.8,-2.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAQAwIABAAIgBABgAgNAYIAEgEIgPg+IAGAAIAAgGIAmAIIAGARIgEADQgIALgOgCQALgigYADQABAEgCABQAAAAgBABQAAAAgBAAQAAAAgBABQgBAAAAAAQAHALAJAJQABAAAAAAQAAABABAAQAAABAAABQAAAAAAABIAAAGQAFASgKAOg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2.6,-4.9,5.2,9.9);


(lib.Rock2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgQANQgGgFgBgIQABgGAGgGQAIgGAIAAQAJAAAIAGQAGAGABAGQgBAIgGAFQgIAGgJAAQgIAAgIgGg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2.4,-1.9,4.8,3.8);


(lib.Rock1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgqALIAAgLIAugSQgCADgBAEQgBAFgCACQgTAIgQABIAAAGIAwAGIAGAAQAkgSgdgIQgKgDgKgGIAAgGQAYACANASIACAEQgMAZgdAAIgFAAQgXAAgQgOg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#996600").s().p("AALASIgvgGIAAgGQAQgBASgIQACgCABgFQABgEADgDQAJAGAKADQAdAIgkASIgGAAg");
	this.shape_1.setTransform(0,-0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4.4,-2.5,8.8,5.2);


(lib.MickArm = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC99").s().p("AgDByIgBgCQgPgQgIgbIAAgEIABgEIAAgGIAAgCIAAgKIAAAAIALgNIABgFQABAAABgBQABAAAAAAQABAAAAAAQAAAAAAAAQAHgOADgOIAAAAIAAgCIABgBIACgKIgEAAIgBgDIgBgGQgBgGgDgFIgBgDIgGgZIgBgFQgVgNAEglQAVASAZAOQAAABAAAAQABAAAAABQAAAAAAABQAAABAAABIgDAAQgDAnASAWIAAAFQAAAeAGAYIgDAAIgDAQQgDANgGAKIgHAJIgIAHIAAAEIAAACIAAAGIAAAHIAAACIAAAJgAgIgdIAAgBIABABIAAACIACAHIgDgJg");
	this.shape.setTransform(0,0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAFB+IgCgDIAAgIIAAgDIAAgGIAAgGIAAgCIAAgEIAIgIIAHgJQAGgJADgNIADgQIADAAQgGgZAAgdIAAgGQgSgVADgoIADAAQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQgZgOgVgTIAAgGIASACIAHARQAOgCAKAMIABAFIgDAJIALAkQAFATAEATQAEAWABAZIAAABIgBAHIgBADIgHAQIgFALQgFAMgCAMIAAACIgFAXgAgbA7IgCgHIAAgNQADAAABgDQADgHAFgFIACgDQAEgEACgHIADgJIAAAAQAEgDAAgFQgCgDgBgEIAAgBIAAgEIgCgGIAAgCIgBgCIAAACIgBgCIAAgCIAAAAIgBgBIAAgCIAAgCIgCgJQgBgFgDgBIAAgCQgBgFgDgDIAAgDIgEgBIgDgEQgNgXACgbIAGAAQgEAmAVANIABAEIAGAZIAAADQAEAGABAGIABAGIABADIAEAAIgDAJIAAACIAAACIAAAAQgDANgHAOQAAABAAAAQgBAAAAAAQgBAAAAAAQgBAAgBAAIgBAGIgLANIAAAAIAAAKIAAACIAAAGIgBAEIAAgIgAgggoIAAAAIAAABIAAgBg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,-12.6,8.1,25.3);


(lib.SuicideMountainStill = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.3,1,1).p("AAzh4QABADACAFQABAFABAFQABAFABAEQADgEADgDQADgDAFgBQAIgCAFADQAEADACAHQABAGADAFQACAIABACQACAEACAEQAAABAAABQABADgBACQgBACgDABQgFABgCgEQgDgEgCgGQgDgHgBgEQAAgBgBgDQgBgCAAgBQgBgEgBAAQgBgDgBAAQgFACgEAGQgBADgCAIQAEARAAAEQgBAEgEABQgCABgDgBQgCgCgCgCQAAgBAAgCQAAgBgDgLQgCgKgGgWIgBgCQgBgFAAgCQAAgCgCgCQgBgDAAgCQgBgCABgDQADgCACgBQAFgBADAFgAAjhXQACAJgEABQgFABgCgDQgCAAgCAAQgMADABAEQABABAIACQAKABAEACQAIADACAGQACAJgGAGQgFAFgJACQgHACgGgBQgHAAgCgGQgBgEAGgCQACAAAFAAQAEAAACgBQAJgCAAgEQgBgCgIgCQgKgBgEgBQgHgDgBgHQgCgJAHgHQAGgDAMgDQAEgCADABQAEABABAEgAgIg4QACAJADAEQAAAAADAEQABAEAAAAQABADgBACQgBACgCABQgCAAgGgDQgDAEgDABQgEACgCABQgLADgHgEQgIgFgDgMQgDgLAGgLQAHgKALgDQAFgBAGABQAIABABAEQABABgBACQAAACABADQAAADABADgAAkgJQAGgCAEALIAAADQADgBACgBQAFgBACAAQAEAAABAFQABACgBACQgBADgDABQgBAAgBAAQgBABgCAAQgCAAgCABQAGATABAGQAAABABABQAAACABABQADALgHACQgDAAgCgBQgDgBgBgDQAAgBAAgEQgBgDgBgCQgBgFgGgTQgDABgGABQgHAAgBgFQgBgDACgCQABgCADgBQACAAAGgBQgBgCgBgDQgBgCAAgBQgBgDACgCQABgCAEgBgACDgYQgEAAgCgBQgDgBgBgDQgBgDACgDQABgDAEAAQADgBADABQACACABADQABADgBACQgCADgDABgABiACQgGACgEAGQgDAHACAGQABAHAEACQACADAFgBQADgBADgCQACgCABgCQgEgLgCgFQAAgCAAgCQgBgCAAgDQgBAAAAAAQgBAAgBAAgABqgHQAHABACAEQAAACgBAAQAAABABADQAAADABAEQACAJADADQAAABAEAEQACADAAABQACACgCACQgCACgDABQgBABgGgDQgEADgDACQgDACgDAAQgLADgHgEQgHgEgEgMQgDgMAHgKQAGgIAMgEQAEgBAHABgACIgQQACABABADQABAEACAGQABAFABAEQABADACAFQABAGABADQABADgCACQgBACgDABQgDABgCgCQgCgBgBgDQgBgCgCgGQgBgGgBgDQgBgEgBgGQgCgFgBgEQgBgDACgCQABgCADgBQADgBACACgACagZQAGgCADAIIAAAAQAFgJAHgCQAKgCAFAGQAEAFACAKIABADQABACAAABQABAEACAEQADAFABADQAAADgBACQgBADgDABQgGABgCgGQgCgEgCgFQgCgFgBgDQAAgBgBgDQgBgDAAgBIAAgCQgBgBAAgBQgBgEgCABQgEABgDAGQgCAGAAAHQAAABAAADQABACABADQAAABAAADQABACAAACQABACgBADQgCACgCABQgEABgCgCQgCgBgBgDQAAgBgBgDQgBgDgBgBQgBgEgBgJQgCgGgBgEQAAgCgCgDQgBgDAAgBQgBgDACgCQABgCADgBgAATAiIABADQAAACAAABQABAEADAGQADAFABADQAAADgBACQgBADgDABQgGABgCgGQgCgEgCgFQgCgFgCgFQAAgBgBgDQAAgDAAgBIgBgCQAAgBAAgBQgBgEgCABQgCABgDAGQgCAGgBAJQABABAAADQABACAAADQABABAAADQABACAAACQABACgCADQgBACgDABQgDABgCgCQgCgBgBgDQAAgBgCgDQgBgDAAgBQgBgEgCgJQgBgIgCgEQAAgCgBgDQgBgDAAgBQgBgDABgCQACgCADgBQAGgCACAIIABAAQAFgJAHgCQAHgCAGAGQADAFADAKgAhyhHQACAEABAFQABADgBABQgBAEgEABQgEABgDgEQgBgCgCgBQgBABgDAAQgGACgFALQgHAQADAMQABAFAFACQAEADAFgBQAFgBADgEQACgCAFgFQADgDACgBQADAAACABQACACABACQABADgCACQgKAOgNACQgLADgKgFQgJgEgCgKQgEgQAJgUQAIgRAMgEQACAAACAAQABAAACgBQACgCADgBQAEgBADAFgAgZhAQAAAAgBAAQgGABgEAHQgEAGACAHQACAGADACQADADAFgBQACgBADgBQACgCACgDQgEgKgCgGQAAgCgBgBQAAgCAAgDQgBAAgBAAgAhhg5QAFgBADAFQAGgIAKgDQAKgDADANQABACAAABQACAHgGACQgGABgCgGIgCgEQgKAEgCAKIAGAYQABADgBACQgBACgDABQgDABgCgBQgCgCgBgCIgIgfQgBgCgBgDQAAgCgBgCQAAgDABgCQABgCADgBgAghAfIADARQABADACAHQACAGABADQAAABABACQAAACABABQAAADgBACQgCACgCABQgEABgDgDQgGAEgGABQgHACgFgCQgGgBgCgGQgGgLgCgKQgCgGAAgIQgBgGAGgBQACgBADABQACACABACQABACAAAFQAAAFABACQACAHACAEQABAFACADQABAAABAAQACAAABAAQAFgBAGgEQgBgDgCgFQgBgGgBgCQgCgKgBgHQgBgGAGgBQACgBADACQACABABACgAhOBAQADALgDAKQgFAKgLADQgJADgIgFQgIgFgDgKQgEgLAEgKQAFgLANgEQAJgCAIAGQAGAFADAKgAhtBCQgCAFACAGQABAGAFACQADACADgBQAEgBACgEQADgEgBgGQgEgPgJACQgFACgCAGgAiSA0QAIAUAIAMQAIAOABABQAAADgBACQgCADgDABQgFABgEgHIgGgLQgFgHgGgPQgBAGgBAPIgBAKQAAAFgBAEQgBAFgFABQgEABgEgEIgFgIQgHgLgGgNQAAAJAAAQQAAAFABAGQAAAHgFACQgDAAgDgBQgCgCgBgCQgCgIAAgMQABgRAAgCQgBgIAAgIQgBgKACgEQABgEAEgBQAFgBADADQACAEAGAMQAGAMAHANQACgPAAgTIAAgLQABgIAFgBQAFgBAEAHQADADADAIg");
	this.shape.setTransform(1.3,-0.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0000FF").s().p("AjHB8QAAgBgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAQgCgIAAgMIAAgTIgBgQQgBgKACgEQABgEAEgBQAFgBADADIAIAQQAGAMAIANQACgPAAgTIgBgLQABgIAFgBQAFgBAEAHQADADADAIQAIAUAJAMIAIAPQAAADgBACQgCADgDABQgEABgFgHIgFgLQgGgHgGgPIgCAVIgBAKIAAAJQgCAFgFABQgEABgEgEIgEgIIgOgYIAAAZIABALQABAHgGACIgCAAIgEgBgAhvBgQgIgFgDgKQgEgLAFgKQAEgLANgEQAKgCAHAGQAGAFAEAKQACALgDAKQgEAKgMADIgGABQgFAAgGgDgAhmA6QgFACgCAGQgBAFABAGQACAGAEACQADACADgBQAEgBACgEQADgEgBgGQgEgNgHAAIgCAAgAg5BUQgGgBgDgGQgGgLgCgKQgCgGAAgIQgBgGAGgBIAFAAQADACAAACIABAHIABAHIAEALIADAIIADAAIACAAQAGgBAFgEIgCgIIgCgIIgEgRQgBgGAGgBQACgBADACQABAAAAAAQABABAAAAQABABAAAAQAAABABAAIACARIADAKIADAJIABADIABADQAAADgBACQgCACgCABQgEABgDgDQgFAEgHABIgGABIgFgBgAgMBKQgBAAAAAAQAAgBgBAAQAAgBAAAAQgBgBAAgBIgCgEIgBgEIgDgNIgCgMIgBgFIgCgEQgBgDABgCQACgCADgBQAGgCADAIIAAAAQAFgJAHgCQAIgCAFAGQAEAFACAKIABADIABADIADAKIAEAIQAAADgBACQgBADgDABQgGABgCgGIgEgJIgEgKIgBgEIAAgEIgBgCIAAgCQAAgBgBAAQAAgBAAgBQgBAAAAAAQgBAAAAAAQgCABgDAGQgCAGAAAJIABAEIABAFIAAAEIABAEQABACgCADQgBACgCABIgDAAIgDgBgAAyA5QgDgBAAgDIgBgFIgCgFIgHgYIgJACQgGAAgCgFQgBgDACgCQAAgBABAAQAAgBABAAQAAAAABAAQAAgBABAAIAIgBIgCgFIgBgDQAAgBAAAAQAAgBAAgBQAAAAAAgBQABAAAAgBQACgCACgBQAHgCAEALIAAADIAFgCIAHgBQAEAAACAFQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQgCADgDABIgCAAIgCABIgFABIAIAZIAAACIABADQADALgHACIgCAAIgDgBgABUArQgIgEgDgMQgDgMAHgKQAGgIAMgEQAEgBAGABQAJABAAAEIAAACIABAEIABAHQACAJADADIADAFIAEAEQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAIgFADQgBABgHgDIgGAFIgFACIgKACQgFAAgEgDgABYAKQgDAHABAGQACAHAEACQACADAFgBIAFgDIAEgEIgFgQIgBgEIgBgFIgBAAIgCAAQgGACgEAGgACLAfQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIgDgIIgDgJIgBgKIgDgJQgBgDACgCQABgCADgBQABAAAAAAQABAAABAAQAAAAABAAQAAAAABABQACABABADIACAKIACAJIAEAIIABAJQACADgCACQgCACgCABIgBAAIgEgBgACjAbQgCgBgBgDIgCgEIgBgEIgCgNIgEgKIgBgFIgBgEQgBgDABgCQACgCADgBQAGgCADAIIAAAAQAFgJAHgCQAKgCAFAGQADAFADAKIABADIAAADIAEAIIAEAIQABADgCACQgBADgDABQgGABgCgGIgEgJIgEgIIAAgEIgBgEIAAgCIgBgCQAAgBgBAAQAAgBAAgBQgBAAAAAAQAAAAgBAAQgEABgDAGQgCAGgBAHIABAEIACAFIAAAEIABAEQABACgBADQgCACgDABIgCAAIgDgBgAiTAAQgJgEgCgKQgEgQAJgUQAIgRAMgEIAEAAIADgBQACgCADgBQAFgBACAFIADAJIAAAEQgBAEgEABQgEABgCgEIgEgDIgDABQgHACgEALQgIAQADAMQACAFAEACQAFADAFgBQAEgBAEgEIAGgHIAFgEQADAAADABQAAABAAAAQABABAAAAQAAABABAAQAAABAAAAQABADgCACQgKAOgNACIgIABQgGAAgHgDgAhYgFIgDgEIgIgfIgCgFIgBgEQAAgDABgCQACgCACgBQAFgBADAFQAGgIAKgDQAKgDAEANIABADQABAHgGACQgGABgCgGIgCgEQgKAEgBAKIAGAYQABADgCACQAAABgBAAQAAABAAAAQgBAAgBABQAAAAgBAAIgCAAIgDAAgAgogXQgIgFgDgMQgDgLAGgLQAHgKALgDQAFgBAGABQAJABAAAEIAAADIABAFIABAGQACAJADAEIADAEIACAEQAAABAAAAQAAABAAABQAAAAAAABQgBAAAAABIgDADQgBAAgHgDIgGAFIgFADIgKABQgFAAgEgCgAgkg4QgDAGABAHQACAGAEACQACADAFgBIAFgCIAEgFIgFgQIgBgDIgBgFIgBAAIgCAAQgGABgEAHgAB9gZQgEgBAAgDQgBgDACgDQABgDAEAAQADgBACABQADACABADQABADgBACQgDADgDABIgBAAIgEgBgAAOgiQgIAAgCgGQAAgEAFgCIAHAAIAGgBQAJgCAAgEQAAgCgJgCIgOgCQgHgDgBgHQgCgJAHgHQAGgDAMgDQAFgCADABQADABABAEQACAJgEABQgFABgCgDIgEAAQgLADABAEQAAABAIACIAOADQAIADACAGQACAJgGAGQgFAFgJACIgJABIgDAAgAA6gvQgCgCgBgCIAAgDIgEgMIgIggIgBgCIgBgHIgBgEIgCgFQgBgCACgDIAEgDQAFgBACAFIAEAIIACAKIACAJQADgEADgDQADgDAFgBQAIgCAFADQAEADACAHIAEALIADAKIAEAIIABACQAAABAAAAQAAABAAABQAAAAAAABQgBAAAAABQAAAAgBABQAAAAgBABQAAAAgBAAQAAABgBAAQgEABgDgEIgGgKIgDgLIgBgEIgBgDIgCgEQAAgBAAgBQAAAAgBAAQAAgBgBAAQAAAAAAAAQgFACgEAGIgDALQAEARAAAEQgBAEgEABIgCAAIgDAAg");
	this.shape_1.setTransform(1.3,-0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-20.2,-14.2,43.1,27.1);


(lib.Thingbottom = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_20 = function() {
		this.gotoAndPlay(15);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(20).call(this.frame_20).wait(1));

	// Layer 1
	this.instance = new lib.Thingbottomstill();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(18).to({alpha:0},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-48.7,-27,90,54.2);


(lib.goNext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,11.3).s().p("AhLAqQghgSACgYQgCgXAhgRQAggTArAAQAsAAAgATQAfARAAAXQAAAYgfASQggASgsAAQgrAAgggSg");
	this.shape.setTransform(22.8,8.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.502)").s().p("AhThcICoBdIioBcg");
	this.shape_1.setTransform(25.1,20.4);

	this.blinker = new lib.general_buttoncolor();
	this.blinker.setTransform(23.4,20.1,1.5,1.5,0,0,0,11.9,11.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,14.8).s().p("AhiA3QgrgXACggQgCgfArgWQApgYA5AAQA5AAAqAYQAqAWAAAfQAAAggqAXQgqAXg5AAQg5AAgpgXg");
	this.shape_2.setTransform(23.4,8.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("rgba(0,0,0,0.502)").ss(1,1,1,3,true).p("AAACxQhIAAg0g0Qg0g1AAhIQAAhHA0g1QA0g0BIAAQBJAAA0A0QA0A1AABHQAABIg0A1Qg0A0hJAAg");
	this.shape_3.setTransform(23.3,20.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["rgba(103,103,103,0.839)","rgba(134,134,134,0)"],[0.678,0.918],-0.8,0,0,-0.8,0,24.9).s().p("AisCkQhFhEAAhgQAAhgBFhDQBEhFBhAAQBfAABBAwQBCAwAVCqQAVCskMAbQhhAAhEhFgAgHCQQBEAAAzgwIABAAIADgEQA0g0AAhHQAAhJg0g0IgFgFIgBgBQgyguhDAAIAAAAIgBAAIAAAAIgBAAQhEAAgyAuIgBABIgCACIgBABIAAAAIgCACQg0A0AABJQAABHA0A0IACACIABABQAzAxBHAAIAAAAIAAAAIAAAAIAAAAQhHAAgzgxIgBgBIgCgCQg0g0AAhHQAAhJA0g0IACgCIAAAAIABgBIACgCIABgBQAyguBEAAIABAAIAAAAIABAAIAAAAQBDAAAyAuIABABIAFAFQA0A0AABJQAABHg0A0IgDAEIgBAAQgzAwhEAAIAAAAIgBAAIABAAIAAAAg");
	this.shape_4.setTransform(24.2,23.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},2).wait(1));

	// Layer 2
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#33FFFF").s().p("AioCqQhGhHAAhjQAAhiBGhGQBGhHBiAAQBjAABGBHQBHBGgBBiQABBjhHBHQhGBGhjAAQhiAAhGhGg");
	this.shape_5.setTransform(24.4,21.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0099FF").s().p("AioCqQhGhHAAhjQAAhiBGhGQBGhHBiAAQBjAABGBHQBHBGgBBiQABBjhHBHQhGBGhjAAQhiAAhGhGg");
	this.shape_6.setTransform(24.4,21.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.5,46.7);


(lib.Main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_2 = function() {
		playSound("SENameofThing1");
	}
	this.frame_5 = function() {
		playSound("NounThing");
	}
	this.frame_40 = function() {
		playSound("SENameofThing2");
	}
	this.frame_53 = function() {
		playSound("Skateboard");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(2).call(this.frame_2).wait(3).call(this.frame_5).wait(35).call(this.frame_40).wait(13).call(this.frame_53).wait(59));

	// Skateboard Firing
	this.instance = new lib.Skateboard_1();
	this.instance.setTransform(27.1,-40.7,0.85,0.85,126.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:299.4,x:12.5,y:-34.6},4).to({scaleX:0.89,scaleY:0.89,rotation:464.4,x:7.1,y:-20.2},5).to({rotation:314.4,x:-7.5,y:-22.4},13).to({scaleX:1.05,scaleY:1.05,rotation:149.4,x:-34},21).to({scaleX:1.23,scaleY:1.23,rotation:89.4,x:-51.7,y:-21.4},13).wait(56));

	// Skater Falling
	this.instance_1 = new lib.Skater();
	this.instance_1.setTransform(38.1,-55.1,0.751,0.751,-39.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:1,scaleY:1,rotation:5.4,x:-6.7,y:40.5},43).wait(69));

	// Arm
	this.instance_2 = new lib.MickArm();
	this.instance_2.setTransform(-38.8,16.7,0.998,0.998,51.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(12).to({scaleX:1,scaleY:1,rotation:0,x:-48,y:11.4},43).wait(57));

	// Rock3
	this.instance_3 = new lib.Rock3();
	this.instance_3.setTransform(1.3,4.9);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0099").s().p("AgBAeIgCgDQAAgBAAAAQAAgBABAAQAAAAAAAAQAAgBABAAIABgBQAAAAAAAAQAAAAABAAQAAABAAAAQABAAAAABIACADIgBADIgDABIgBgCgAgBAOIAAgFIAAgFIAAgOIAAgRQAAgBAAgBQAAgBABAAQAAgBAAAAQAAAAAAAAQABAAABAAQAAAAABABQAAAAABABQAAABAAABIAAApQAAABAAAAQgBABAAAAQgBABAAAAQgBAAgBAAQAAAAAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBg");
	this.shape.setTransform(-27,-37.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0099").s().p("AgMAaQgGgFAAgJQAAgKAGgFQAFgGAHAAIAHABIAEADIABgWQAAgBAAgBQABAAAAgBQABAAAAgBQABAAAAAAQAEAAAAAEIgCAYIAAAKIABATIAAABIgBADIgDABQAAAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBIgGADIgFACQgHAAgFgGgAgIAAQgDAEAAAIQAAAFADAEQAEADAEAAQACAAACgBIAFgDIABgBIAAgHIAAgFIAAgEQgBgDgDAAQgDgCgDAAQgEAAgEACg");
	this.shape_1.setTransform(-30.2,-37.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF0099").s().p("AgOARIAAgZIAAgEIAAgEQAAgEAEAAQAEAAAAAHQAGgHAIAAQADAAACACQACACAAAFIAAADQgBAFgDAAQgEAAAAgEIAAgDIAAgDQgGABgCACQgDADgDAFIAAATQAAAEgDAAQgEAAAAgEg");
	this.shape_2.setTransform(-34.3,-36.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF0099").s().p("AAMAUIgDgDIgGADIgDABQgJAAgEgFQgEgFAAgKQAAgIAGgGQAHgHAHAAQADAAAEACQAGACAAADIgBACIgBAFIAAAGIABAIIACAHIABACIAAABIgBACIgCABIgDgBgAgFgIQgFAFAAAEQAAAHADADQACADAFAAQABAAADgBIAEgDIgBgOIAAgDIAAgFIgCgBIgCAAQgEAAgEAFg");
	this.shape_3.setTransform(-38.4,-36.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF0099").s().p("AgKAQQgFgFgBgKQAAgGAFgHQAFgIAIAAQAHAAAFAHQADAGAAAHQAAAHgEAHQgGAHgHAAQgFAAgFgFgAgGgHQgCAFAAADQAAAGADADQACADADAAQADAAADgDQAEgDgBgGQABgNgJAAQgDAAgEAFg");
	this.shape_4.setTransform(-42.6,-36.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF0099").s().p("AgKAdIgDABIgDgBQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgDIAAgDIAAgMIAAgLIAAgLIAAgLIABgDQAAgBABgBQAAAAAAAAQABgBAAAAQABAAAAAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAAABIAAABIAAAJIAAAKIAGgDIAEgBQAIgBAGAHQAEAEAAAJQAAAIgFAHQgGAGgHAAQgGAAgEgCgAgFAAIgFABIAAAIIAAAGIAAAGIAFACIAFABQAEgBAEgEQADgDAAgGQAAgGgDgEQgDgCgFAAIgFACg");
	this.shape_5.setTransform(-47,-37.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF0099").s().p("AgMAQQgGgEAAgJQAAgIAFgIQAFgHAIAAQAFAAAEACQAGADAAAFQAAAEgFAEIgIACIgNAHQADADACACQAEACACgBIAGgBQAFAAACgCQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAAAAAIADACIABACQAAAEgHADQgGADgGAAQgGAAgGgFgAgHgJQgDAEgBAFIALgEIAIgGQgDgDgFAAQgEAAgDAEg");
	this.shape_6.setTransform(-51.5,-36.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF0099").s().p("AgBAbQAAAAgBgBQAAAAAAAAQAAAAAAgBQAAAAAAgBIAAgEIAAgFIgBgUIgIgBQgEAAAAgEIABgCQAAgBABAAQAAAAAAgBQABAAAAAAQAAAAABAAIAIABIAAgGIAAgEQAAgBAAAAQAAgBAAAAQAAAAAAAAQABgBAAAAIACgBQACAAAAAGIABADIgBACIAAADIAGgBIAGABQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAIgBADIgDABIgCAAIgCAAIgFABIABAUIAAACIAAADQAAAIgEAAIgBgBg");
	this.shape_7.setTransform(-55.7,-37.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF0099").s().p("AAMAUIgDgDIgGADIgDABQgJAAgEgFQgEgFAAgKQAAgIAGgGQAHgHAHAAQADAAAEACQAGACAAADIgBACIgBAFIAAAGIABAIIACAHIABACIAAABIgBACIgCABIgDgBgAgFgIQgFAFAAAEQAAAHADADQACADAFAAQABAAADgBIAEgDIgBgOIAAgDIAAgFIgCgBIgCAAQgEAAgEAFg");
	this.shape_8.setTransform(-59.6,-36.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF0099").s().p("AAKAeIgGgKIgFgJIgHAEIgBAMIgBAEIgCABQgEgBAAgFIAAgKIABgKIAAgLIAAgOIAAgDIAAgFIABgCIACgBIADABIABACIAAAFIABAEIgBANIAAALIAIgHIAJgJIADgBIADABIABADIgBADIgMAJIAIAMQAGAIAAADIgBADIgDABQAAAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAAAg");
	this.shape_9.setTransform(-63.6,-37.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF0099").s().p("AgOAbQgHgEgBgFQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIACgBQABAAAAAAQABAAAAAAQABABAAAAQAAABABAAIADAEQAEACAGAAQAEAAAFgCQAHgEAAgGQAAgFgGgDQgEgCgFAAQgHAAgEgBQgFgDAAgGQAAgHAHgGQAIgFAGAAIAJABQAGACAAADQAAAAAAABQgBABAAAAQgBAAAAABQgBAAgBAAIgFgBIgGgBQgFAAgDADQgFADAAAFQAAADAGABIAGABQAJABAFAEQAFADAAAHQAAAJgJAGQgHAEgIAAQgHAAgGgCg");
	this.shape_10.setTransform(-68.7,-37.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3}]}).to({state:[{t:this.instance_3}]},34).to({state:[{t:this.instance_3}]},16).to({state:[{t:this.instance_3},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},3).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(51));
	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(34).to({x:-17.4,y:49.9},16).wait(62));

	// Rock2
	this.instance_4 = new lib.Rock1();
	this.instance_4.setTransform(20.1,-17.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(9).to({x:17.7,y:-16.5},0).to({rotation:-90,guide:{path:[17.6,-16.4,17.6,-16.4,17.5,-16.5,16.3,-18,14.3,-17.7,13.6,-17.4,12.8,-17,12.2,-16.8,11.7,-16.5,10.7,-15.6,9.7,-14.8,7.4,-12.8,5.3,-10.3,5.3,-10.3,5.3,-10.2,5.3,-10.1,5.3,-10,4.7,-9.4,4.4,-8.9,4.2,-8.5,4.1,-8.2,4,-8.1,3.8,-8,3.8,-7.8,3.7,-7.7,3.3,-7.4,3.2,-7,3.2,-6.9,3.2,-6.8,3,-6.7,2.9,-6.6,2.9,-6.5,2.8,-6.4,2.4,-5.6,2.3,-4.7,2.2,-4.3,1.9,-3.9,1.9,-2.7,1.8,-1.5,1.8,-0.8,1.9,-0.2]}},24).wait(1).to({x:1.2,y:2.8},0).to({rotation:-150,guide:{path:[1.1,2.9,-0.7,3,-2.6,3.1,-2.6,3.2,-2.7,3.3,-3.6,3.8,-4.4,4.3,-4.5,4.4,-4.7,4.4,-5.1,4.6,-5.2,4.9,-6.3,5.3,-7.2,6,-8.2,6.7,-9.2,7.6,-10,8.3,-11,8.7,-11,8.8,-11.1,8.9,-11.1,8.9,-11.1,9,-12,9.5,-12.9,10.1,-15,11.6,-16.8,13.5,-17.5,14.1,-18.2,14.8,-18.2,14.9,-18.3,15,-18.8,15.6,-19.2,16.3,-19.3,16.5,-19.3,16.5,-19.8,17.3,-20.3,18,-20.3,18.1,-20.3,18.2,-20.4,18.2,-20.4,18.2,-20.8,18.9,-21.2,19.5,-21.3,19.7,-21.3,19.8,-21.4,19.8,-21.5,19.9,-21.5,20,-21.5,20.1,-21.6,20.8,-21.9,21.5,-22,21.5,-22,21.6,-22.2,21.9,-22.4,22.2,-22.4,22.2,-22.4,22.2,-22.4,22.2,-22.4,22.3,-22.4,22.3,-22.5,22.5,-22.8,23.2,-23.2,23.8,-23.2,23.9,-23.3,24,-23.3,24.1,-23.3,24.2,-23.4,24.9,-23.8,25.5,-23.9,25.6,-23.9,25.7,-24.2,26.7,-24.7,27.6,-24.6,28.4,-25,29.2,-25.7,30.6,-26.3,32.2,-26.9,34.1,-27.6,35.9,-27.6,36,-27.7,36.1,-27.7,36.6,-27.8,37,-27.8,37.1,-27.8,37.1,-28.1,37.9,-28.3,38.7,-28.6,39.5,-28.7,40.4,-28.8,42.2,-29.4,43.7,-29.5,43.8,-29.5,43.9,-29.9,43.9,-30.2,43.8,-30.2,43.8,-30.2,43.8]}},17).wait(61));

	// Rock1
	this.instance_5 = new lib.Rock2();
	this.instance_5.setTransform(33,-33.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({x:23.4,y:44.8},48).wait(64));

	// Main
	this.instance_6 = new lib.SuicideMountainStill("synched",0);
	this.instance_6.setTransform(33.6,32.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#000000").ss(2,1,1).p("ArGGGIAAChIAAAiIWNAAIAAk5IAAkQIAAkEIAAjtIAAhXI2NAAArGpCIAAObIAAApIAAAA");
	this.shape_11.setTransform(-3.8,-1.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#000000").ss(1,1,1).p("ACrgxIlHBfIgOAE");
	this.shape_12.setTransform(37.9,39.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#000000").ss(1,1,1).p("ADKh6QgLABgMABIl8BlIAMArIAbBeIABADIABAC");
	this.shape_13.setTransform(29.7,28.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.lf(["#000000","#000000","#CC9900"],[0,0,0.773],-829.6,-38.8,808.8,-38.8).s().p("AACAYIgDgRIABADIAAACQABAFADADQADADAEACIgGAAIgDgBgAgKgXIAFgBIABAEIABACIgBAMIAAAEgAADgEIAAgBIAAABgAgEgUIgBgEIABAAIACAEIgBABIAAABgAgFgYg");
	this.shape_14.setTransform(14,43.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.lf(["#000000","#926130","#996633"],[0,0.169,1],-19.9,-40.5,63.8,-40.5).s().p("AAAgKIABAIIAAANg");
	this.shape_15.setTransform(11.7,42.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.lf(["#000000","#926130","#996633"],[0,0.169,1],-10.8,0.8,1.4,0.8).s().p("AgGADIgFgBIAXgFIgBADQgEAEgHAAIgGgBg");
	this.shape_16.setTransform(31.7,18.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.lf(["#000000","#000000","#CC9900"],[0,0,0.427],-847.9,-26.4,790.5,-26.4).s().p("AilCOIgCgCQgGgGgEgIIgBgIIAAAAIADgDIABgGIgCgFIgCgEIgGgTIgBgDIgCgFIAAAZIgBAAIgahdIgNgsIF8hkIAYgCQAAADACADIAAACIAGAJIAAABQABADACACIABAEIAFAQIAAACIAAAAIAAABQACACAAADIAAADIABgBIAAADIAEAEQAGAIgDATIgBAGIAEAHQAQAfAFAoIgGAHQhPAZhVATIgsAKIAAAGQgDAAgDABQgLAIgZgDIAAADQgQgBgCAKIgGAAIgYAAQAAABgBABQAAAAAAABQAAAAAAAAQAAABAAAAQgSAFgSAEIgGgBQgWAAgPAHQAEADAGACIgDABQgGACgGAAIgEAAgAgDg2IAAAAIABAAIgBAAgAjaAGIAEgBIAaBdIgEACg");
	this.shape_17.setTransform(32.3,30.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.lf(["#000000","#926130","#996633"],[0,0.176,1],-1.5,0,1.5,0).s().p("AgMgJQgCgCAAgDQARAJALAOIABAGQgRgJgKgPg");
	this.shape_18.setTransform(4.6,35.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.lf(["#000000","#926130","#996633"],[0,0.176,1],-1.7,0.4,3.2,0.4).s().p("AgOgIQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAgBAAAAQARAFAOAJIACALQgRgLgOgKg");
	this.shape_19.setTransform(4.8,31.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.lf(["#000000","#926130","#996633"],[0,0.176,1],-4.3,0,4.3,0).s().p("AgpAPIANgHIAYgKIAPgHIAXgJIADgBIAFgBIgBACIgGAJIgIAHQgLAGgPACQgLACgLAIQgGAEgEABIgCAAQgFAAgDgGg");
	this.shape_20.setTransform(3.1,21.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.lf(["#000000","#926130","#996633"],[0,0.176,1],-1,0,1,0).s().p("AgIAAQAIgHAFgCQAGgCgCAGQgFAPgEAAQgEAAgEgKg");
	this.shape_21.setTransform(4.1,9.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.lf(["#000000","#926130","#996633"],[0,0.176,1],-2,0,2,0).s().p("AgTgHIAGAAIAAgGQAPgUASARIgEAAQgQACgGAHQAAABAAABQAAAAAAABQABAAAAABQAAAAABAAQAPALgRAIQAAADgBACIgCAEQgDgTgHgNg");
	this.shape_22.setTransform(5.1,4.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.lf(["#000000","#926130","#996633"],[0,0.176,1],-0.7,0,0.8,0).s().p("AgGADIAEgHQADgKAEAKQAFAHgIAEQgCADgDAAQgEAAABgHg");
	this.shape_23.setTransform(26.6,-19.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.lf(["#000000","#926130","#996633"],[0,0.176,1],-1.2,0,1.2,0).s().p("AgIAPQgDgBAAgGIAAgGQAEgHAGgFQAEgEAJgBIgDACQgLAHgCATQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAIgCgBg");
	this.shape_24.setTransform(41.1,-35.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.lf(["#000000","#926130","#996633"],[0,0.176,1],-30.7,0,42.8,0).s().p("AAAHhQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAIgrgRIgLgEIAAAHIgGAAIAAAGQgPAAgPACIgFAAIgHgCQgLgFgPgBIAAAGIgNADQgQACADgKQAEgQgOADQgFABgIAEQAAAAgBAAQgBAAAAAAQgBABAAAAQAAAAgBABQgFAHgJgPIgGABQgQAEgCgLIAAgGQAAgDgCgCQgNgUgWgMQgMAAgHAGIgDADQgMgSgPAJIAAgGIAAAAIgRAAIgfAAIgHAAIgFgBQgfgFgfgDIAAAAQAPgSATgMQAIgFAHgGIAUgEIABgBIACgCIAEgCQAFgFAEgGIAJgKIACgDIAAgIIAAgCIAAgIIAAgBIACgDIABgBIAAgCIAAgCIACgCIAGgIIACgCIAQgBIABgBQACgFADgEIAAAAIAJgNIAHgKIAKgCIAFgIIACgCIAAgCIAAgCQACgCABgDIABgCIAHgBIABABIABABIACACIAJAAQADgDACgFIACgCIAAgEIAAgCIAAgBIACgCIACgCIAMgBIAHgBIAGgBIADADQABAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAIgBgEIgCgFIgGgPIgCgHIAAgFIAAgGQAXgHgKgYIgBgGQAUgHgCgXIgBgDQgJgUALgHIADgCQAIgGABgLIAAgGIAAgYIAAgBIAFgHIABgDQASAAASgDIABgBIAAgCIAGAAIAGAAIAAADIAAADQACAFAEAGQAFAGAIAEIAFABQAAADACACQAAAAABABQAAAAABAAQAAAAABAAQABABAAAAQAPgCgCgQIgDgKQAAgBAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAIAAgBIgCgFQgBgDgEgDIABgGQAIgVgVAVIABgGQAMgngTAUIgGgEIAAgCQAAgDABgCQAKgRAUgJIADAAIAEAFIgBABQABAWARgQQADgDAAgDQAAgLgIACIgEgJQAEgDADgRIABgKQABgHAIgDQAHgDAKAAQAAADABACQAGAIgHAKIgGAIQAJAbAFghIABgCIABgFQACgJAAgJIAAgGIABgJIAcgDQgEANAJABQAHABAEgCQAJgEACgDQADgEgDgCIgGgDIAAgDQgBgPgOAOIgFgEIAEgIIABgGIAAAAIgBAAIABgFIAVgTIAIgHQAAgBABAAQAAgBAAAAQAAgBAAgBQAAAAAAgBIADAAQABgJgEgFIgGgEIAWgHIACgBIAEgBQgLgHgLgCIAAgBQAdAAAHgTIABgGQABAAABAAQAAAAABAAQABABAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAABAAABQAAAAAAABQAEAUAQgZQAEgHABgMQAbgNgUgIQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIAEgBQACgFAAgCIAEgBIADgCIACgBIAAgCQALASADgEQATgdgQANQgDACgPgKQAAAAgBAAQAAgBAAAAQAAAAgBgBQAAAAgBAAIgDgEIgDgDQADgFADgLIABgGQAYgEAQgFIgCAEQgBACAAADIAYgRIAngfIABgBIgDAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQgBAAAAAAQgCgCgDAAIAAgGIAAgGQAhAAAUgPQAFgEAEgFIAFgGIAAgBQAIgHARABIAGAAQABAEABADQAHAJAWgJIACAAIAEgBIAAABQANAWAFAbIABAGQACAMgEALQgCAEgDADIgGAGQAEAbACAcIAAAGIgDABQgCAWgNAIQADAbANARQABAAAAABQAAAAAAABQABAAAAABQAAABAAABQgDAogMAbIADAAQADAMABgDIACAEQAHAagBAjIAAAGIgDAAQABAQgKACQAAAMAHAFQACACADAAQAHAeAMAZQAIAQgNAaQgFAMAJgBQAGAHABAMIAAAMIgBAGIAMBDIABAGIgBAGQgCANgKAGIABACQAAAKAHAFQAAAAABAAQAAAAABABQABAAAAAAQABAAABAAIAAAAIABAGQAIAPgDAcIgDABIgCAHQgFAOgJAJIABASIgBAGQAUAVgKAjIADAAQAGAJADAMIACAJIABAGIgBAGQgGAMgLAHQAAAGACAFQABAAAAAAQAAAAABABQAAAAABAAQAAAAABAAQAAAMgGAGIgDADQgMgTgQAKIAAANIAAAGIglgTIgYAAQgGAAgBgBQgCgMgJgDQgPgEgWAOIAAAGQgaACANgJIADgCQgYgSgWAVIAAAGQAAAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAAAIgFgHIgKAJIgBABIgDgRQgDgSgFgPQAVgKAbgFIABgBIAAgCIAYAAIAHAAQAZgOAfgHIAxgMQAJgCgEAQIADAAIAEgBQAIgDgIgPQgBgCAAgDIgBgGQgKgmgOgjIgGgNIABgGQAEgagLgLIAAAAIAAgBIgDgKQgBgGgEgGQgFgIgDgKQgCgGgFgDIgCAAIgCACIAAADIgXADIl8BkIANAtIgFACIAaBeIAGAUIADALIAFARIADABIAGAAIAQAAIADAAIABAAIAAgCQAJgDAJgDQAAAUACAPgAhHGzIAAgOIgCgIgAidFZQALARASAJIgBgGQgLgQgSgJQAAADABACgAidEtQAQANARALIgCgMQgNgKgTgGQAAABAAAAQAAABAAABQAAAAABAAQAAABAAAAgAi1D5IAAgBIgCAAIACABgAh5C8IgDABIgXAJIgRAHIgYAMIgNAHQAEAHAGgBQAFgBAFgEQALgIANgCQAQgDAKgHIAJgHIAGgJIABgCIgGABgABxC6IAFACQAOADAFgIIACgEIgaAHgAiPBPQgFACgKAIQAKAaAJggQABgBAAgBQAAgBAAAAQAAgBgBAAQAAgBgBAAIgDABgAiVBDIACgDQABgDAAgDQAUgHgSgNQAAgBgBAAQAAAAAAgBQAAAAgBgBQAAgBAAAAQAIgIAQgBIAEgBQgRgQgRAUIAAAGIgGAAQAGAPADASgABHjIIgEAJQgBAKALgGQAIgEgFgKQgCgFgCAAQgDAAgCAGgADZlyQgGAFgEAJIAAAGQAAAGADABQABAAABAAQAAABABgBQAAAAABgBQAAAAAAgBQACgVANgHIADgCQgJABgGAEgAALHIIABgGIgBgEQABgBAAAAQABAAAAAAQABgBAAgBQAAAAAAgBIACAAIABgBIAAgCIAOgCIgOAEIAOgEQAfgEAbgLQASgHAZAFQABAAAAAGIAAARIAAAHIgGgFQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQgRgGgaAHQgWAFgQgPIAAAGQgBAAAAAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgGAQgJAAQgGAAgHgFgAFnFPIABAGIgGABg");
	this.shape_25.setTransform(19.1,0.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFF00").s().p("AABA0IgBAAIgDgBIgCgBIgKgEIAAgDIgLgHIgCADIgCAEIAAgIQABghgXANIAAAGIAAABIAAAFQgRAGAIgQIAGgKQANgQgWgEQAsgbA1gLIADADIgEAEIAGAAIABAAIALAAQAIADAGAEIABAHQgGgCgJAAQALAQABATIABAGIAAAGQgDAAgCgBQgBAAAAgBQAAAAAAgBQAAgBgBAAQAAgBAAgBIAAgDIgFADIgBAAIAAABIgSALIAAAGQAAAEgCABQAAABAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAIAAAGQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQgCAHgGACQgEACgFAAIgEAAg");
	this.shape_26.setTransform(-57.7,11.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFCC99").s().p("AAwB3QAEgFAEgIIADgIIABgEQgbgLgZAbQgIABgCgMQAAAAAAgBQgBAAAAABQAAAAAAAAQgBABAAAAQgJAMgJAEQgEACgFAAQgHABgHgDQAKABgDgOIgBgFIAAgHIAIgFQANgLgIgPIgBgFIAAgHIAAgPIAAgJQAGgHACgJIACgLIAAgOIgBgDQgDAKgEAHIgGAHIgCACIAAACIAAAKIAAAGIAAAAQgDAAgCABIgPAIIgLAGIgSAJIAAAHIAAAGQgBAAAAAAQgBAAgBAAQAAAAgBABQAAAAAAAAQgSAXgdAKIgBABIgEAAIgHACIgBAAIAAgoIACAAQAAAGAGAAQABAAAAAAQAAAAAAAAQAAgBABAAQAAAAAAgBQABgCgCgDIAIgHIABABIAAgBIABgBIABgBIABAAIASgPIAFgEQACgCAAgDQALgFAFgLIADgIIACgDIADgIQAFgFAHgDQALgHAOgDIAGAAIACgHQADgFAGgDQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAVgBAMgLIAIgHIAEgGIABgDIADgHIABAAQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIAHgEQAHgEAFgGIACgDQAAgBABAAQAAAAAAAAQABgBAAAAQABAAABAAQACAEABABIACAAQAEgCACgJIABgGIAHgFQACgBADAAIAAAGIgBARQAAAVALgJIABABIAIgEIAlAAQAJAFABAJQABAJgDAGQgEAJgKAGIAAABQABAKgGAGIgCACIAAAJIgDABIgDANIgEALQgEAJgFAHIgFAGIAAADIAAADQAAABAAABQgBAAAAABQAAAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAIAAATIAAAGIgBAGQgEAMgFALIgJAOQgBAAAAAAQgBAAAAAAQgBAAgBABQAAAAAAAAQgFAFgHADQgGADgIAAIADgDgAAtgjQgOALgFATIAAACIABALIACAQIAAADIAAgDIACgQIADgLQADgLAGgKQAIgOgCAAIgEADg");
	this.shape_27.setTransform(-60.2,27);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#C6FFFF").s().p("ArGI4IAAihIABAAIACAAIAAABQAAAAABABQAAAAAAABQABAAAAAAQABAAABABIAAAAQADACAFgBQAAAAAAgBQABAAAAAAQAAgBAAAAQABgBgBAAQAdgOASgZQABgCAAgCIASgNIATgLIAGgBQAAAJADAIQAAABAAAAQAAAAABAAQAAAAABAAQABAAABAAIAAAHQACAVgPADIAAAGIAAAHQgGAFgHADIgCABIgEAEIgJAIQgHAFgIAEIgMABQgBgRgLAQQAAAJgFAGQgDAFgUAEIAAAEIgDApQAFAhAAAhgAKaHiIgPgGIAAgHQAIgPAFgLQADgGAAgHIAAgGQgCgIgFgGIgJgHQAGgagIgWQgFgTABgUQAGgHADgJQAGgQgDgRQgBgLgEgNIgBgCIgFgGQgDgIADgIIAEgKIABgDIAEgDQACgGgCgFQgHgegJgdQAJgLgGgSIgDgGIgGgIIgFgSIALgNQgCgugdgmIAAgSIADgBIACgBQAEgUgBgVQgBgUgNgRIgBgDIABgbQARgTABgYQgcgmAUgrIABgFQACgQgDgTIgDgaIAAAAIACAAQAQgSgBgZQgBgOgIgNIgPgWQgJgFgPAAQgMgBgFgHIgCgCIglACIAAAHQgbABgPAYQgZgFgSAQIAAAHIg3AeIAAAHIgFABIgaAqIAEAGIAFAAIAIAPIgNADIgEgKIglAQQAJAXgJAYQgEAKgJAEQgLAFgNABIAAAGIgeAMIgEAHIABAKQgCAJgKAAQgEAAgFACQgQADgPAHQASAJATgNIACABIAEgEIAHADQABADgBADIAAAAIAAABQgBADgEACIgHAEIAFACIgFAEIAKADIADgBIgCAEIAAAFIAAABQAAAGAEAEQAAAAAAAAQAAABABAAQAAAAAAAAQAAAAABgBIABgCIAFAEIgGAGIgeADIgHgPIAAAGIgRgFIgCABIgIAHQACAFABAFIAAAGQgUAQgFAaIAJAHIAEAJIgMAIIgEgFQgVgKgTANQgGAEgGAGIAGAMIAAAGQAAAKgCAIIgDAHIgIADIAAAHIgkAAIAAAFIArADIAAABQgSADgTAAIgBAFIgFAHIAAAAIgbAAIAPADIAAAhIgRAJQgDARAJARQAEAJgEAGQgFAIgJACIgCAMIAEAKIgBAEIAAACIgCACIgDADIgIAEIAAAGIgGAAIANAlIgXgEIgEAEIgCAAIAAACIgCACIAAABIAAADIAAAEIgCAEIgBACIgDAAIgCgCIgQABIgCABIgCAFIgBACIgEAIIAAACIgLADIgBAAQgEAEgDAFQgEAJgEAGIgFAHIgCACIgQACIgBABIgBABIgCACIgGAIIgCACIAAACIAAACIgCACIgBACIAAAHIAAACIAAAIIAAACIgEAGIgLALQgEAFgGAEIgRAEIgBABIgQAJQgLAHgJAKIgPAQIgPAAIAAgBIgDABIgDAAIgBABIAAAAIgFACIAAABIgGASIgHAFIgSgGIAAAZIgeAAIAAAFIgJASIgEgCQgYgTgeAGQgLABgHgFIAAgKIgJgCQgMACgLgHIAJgVIgVADIAAAGQgMAGgJgIQgGgFgCgIIgCgFIgRgMIAAAAIgBAAIgGgEIADgBIABgCIABgCIADgNIABgLIADgHIAAgFIAAgHIABgBIgBgBQARgZAKgcIAJgZIgJAAIAAAAQAFgGgBgKIAAgBQAKgGAEgJQADgHgBgIQAAgJgJgFIglAAIgJAEIAAgBIgBgDIAAgbIAIgNIgCgHIgHgsIgBgIIgBgIIgGABIgEgJQgfgVghASIgDAHIgFgGIgKAHQgQAQgVAGIAAANIgeAYIAXAOIAAAcQAIgBAGgHQAEgGABgKQAHAUALANQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAIAQgPIAAAQIAMAOIhoA4IAAAGIgDACIgEAGQgJANgCAQIgUAMIgBAAIgFADIgEAEIgHAEQgGAEgBAGIgCAAIAAuaIAAgHIWMAAIAABXIgFAAIgEAVIgCALQgDAeADAfIADA4QACAsgCAsIAIAAIAAECIgFAAIAEARIgBAuIAAClIAAAMQAAARgDAQIAAAAIgCAMQgGAmABAnIABAuIABA0IgFgCIgUAPQgEgEgFgCgAiPDhIAAAAIgBgBgAmSDEIABgDIABgEIgCAHgAANBQIgIATIABABQAIABABgIQADgSALgNgAgnBTIAGAFQARAAALgPIAEgEIABgGIgCgEgAmmA4IABgDIgCgCgAABAQIACgEIgDgBIABAFgAA3AFQAJgFAGgIIgBgCQgTASAFgDgAl8hIIAAAAIABgBIgBABgAiMhRIADABIgCgCgAjehTIABgDIgCAAIABADgAj5h7IACAAQgBAAAAAAQAAgBAAAAQAAAAgBAAQAAgBAAAAgAC1h8IAHgGIgPgFQAFAFADAGgABKihIABABIgBgBIAAAAIAAAAgArGGTIABAAIgBAAgAq1FjIACgCIAAAAIgBACIAAAAgAEajVIACgCIgCACg");
	this.shape_28.setTransform(-3.8,-3.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.lf(["#000000","#000000","#CC9900"],[0,0,0.427],35.4,47.1,35.4,47.1).s().p("AgDAAIAAAAIAHAAIgEABIgDgBg");
	this.shape_29.setTransform(35.4,47.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#00CC33").s().p("ArGCcIAAgiIAIAAQAAghgFggIADgqQAdAIALgFIAAgGQABgOgBgIIAMgBQAJATAPgTIADgEQAHgLANASQACADAHAAIABgEQAFgHAHgBQAHgBAKAEIAAgDIAFgDQAXgMAbgGIAAADQgMAIgDAHQgFAIAEAGQAAAAABAAQAAABAAAAQABAAABAAQAAAAABAAQASgGASgIIAAgBIAAgDQABAAABAAQAAAAABAAQAAAAABAAQAAABAAAAIAAACQADANgNACQAGATAQgXQAKgQAFAIIAEAJQAJANANALQACACADAAQADAQASgJIAGgEQALgHgBAKQgDAAgDABQgDACgDADQAOALAbgIIABgDQANAJANAGQACAAAEgCQAQgLAHAdQAaAEgEgdIADAAQABALALABIAGAAQAAABABABQAAAAAAABQAAAAAAABQABAAAAABQAAAAABABQAAAAABAAQAAABABAAQABAAABAAQgBAKANgEIAGAAIAkgGIgBAFQgFAVAfgUQANALAYgCIAAgDQAQgBANgEIABAAIAHgBQAAAAgBABQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQgBAAgBAAQAKAUAogFQAVgDAPgGQAFAHAEAEQAJAJADgJQAAgDABgHIAAgBIAAgBIAAgFQALAOAagFIABgDIALgNIABgFQALgBABAMIAAAJIAAAEIAAAAIAEgDQALgIAJgBQAMgBAKAJQAKAIgBgKIAHAAIAkAAIAGAAQALAQABgWIAAgGIAGABQAWAEAQAMQACABAEAAIAEABQALABgDgOIAAgGQATALASgQQADgBADAAIA3gGIAGgBQAHAfAVgVIADABQAGACAFAAQAMANAKgLIAIABIAAgHIAAgCIAAAAQANgBAFgHQABgCABgDQAggTgMAQQgMARAdgDQAMgCAGgJQAlgJgQANQgDACADADQAEAEAFAAQAZgQAXASQAAAAABAAQAAABAAAAQAAABAAAAQABABAAABIAwAPIAAgDQACgdAbAYQAGAGgEgNQAEgiAOAfQABADAEgDQAIgEgBgMQALgGAIACIAAgJIgBgyIgBgtQgBgoAGgmIACgLIAFAAIAAE3gADNAuIAEgBIAAABIgBAAIgBAAIgCAAg");
	this.shape_30.setTransform(-3.8,41.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.lf(["#000000","#926130","#996633"],[0,0.169,1],5.7,-46,89.4,-46).s().p("ABxAtQABgKgOACQgLACgIADQgoANgCgcIAAgEQggALgVgHIAAgEQgMgDgMAAIAAAHQgGAAgDgEIgGgFQgLgIgdAKIAAgGQAEgOgKgCQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAABAAAAQgGAPgPAGQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAAAAAAAQgJgFgCgKQAJAAAIgCQABAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAgBIAAgGIAAgMIAGAAIAGAAQARAQABgXIAEAAIACAAQABgFgBgFIAAgCIAAgBIAHABQAHAJACgRIAEAAIAAAAQAfACAfAFIgDAFIAAAEIACALQAHALANgIIADgCIABAAIAEgBQANADACgJQAAAAAAAAQABAAAAAAQABgBAAAAQABAAABAAQgCAbASgQQABAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQASAWAZgJIAGgBQADAAACABQAKAFgVAEQAFAKATgDIAGgBIgBAGQgCADABADQABAPgDAHIAAACQgDAEgGAAQgEAAgHgDgAAMgZIgBgBQgCgCAAgFIAAgGIABAAIAeAAQgBAEgLAFQAAAAAAAAQAAAAgBABQAAAAAAABQAAABAAAAIgBAAIgFABIgFABIgEAAg");
	this.shape_31.setTransform(-17.4,43.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgHHpQgEgEgFgIQAPAIADgJIABgCQADgHgCgOQAAgDACgEIABgFIgGAAQgSAEgFgKQAVgHgJgEQgCgCgEAAIgFABQgZAMgTgZQAAABAAABQAAAAAAABQAAAAAAABQgBAAAAABQgTARACgcQAAAAgBAAQgBAAAAAAQgBAAAAAAQAAAAAAABQgCAJgNgEIgEABIgBAAIgDACQgOAJgJgMIgBgLIAAgEIACgFIAGABIAGAAIgBABIAAAGQAAAEADACIABABQADABAGgBIAFgBIABAAQAAgBAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQAKgFACgEIARAAIAAABIAAAGQAPgJANASIADgDQAGgGAMAAQAWALAMAUQABACAAAEIAAAGQACAKARgEIAGAAQAJAPAFgIQAAAAABgBQAAAAAAAAQABAAABAAQAAAAABAAQAIgEAFgBQAOgDgFAPQgDALARgDIANgDIAAgGQAOACAMAEIAGADIAFAAQAPgDAPAAIAAgGIAGAAIAAgGIAMAEIArARQAAAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIADAAQgDgOAAgUQgKACgKAEIgDABIgRABQgDgCgDgDQgDgEgCgEIAAgCIgCgDIgDgLIAAgEIABgNIAAgBIAAgBIgBgEIAAgZIABAGIABADIAGASIACAEIACAGIgBAFIgCAEIgBgBIAAABIABAIQAEAHAGAHIACACQAIABAIgEIADgBQgFgCgFgDQAPgGAWAAIAGAAQASgDASgGQAAAAAAAAQABgBAAAAQAAAAAAgBQAAgBAAAAIAYAAIAHAAQABgLARACIAAgDQAYACANgHQADgCADAAIAAgGIAtgJQBVgTBOgaIAGgBIAAgGQgFgpgPgfIgEgIIAAgGQAEgTgHgIIgDgDIgBgDIgBAAIAAgDQAAgDgBgCIgBgBIAAAAIAAgBIgFgQIAAgFQgDgBgBgDIAAgBIgFgKIAAgCQgCgDgBgDIAAgDIABgCIACgBQAGADACAHQADAJAFAJQADAFABAHIADAKIAAAAIABAAQAKALgEAaIAAAGIAGAOQANAiALAmIAAAGQAAADACADQAIAPgIADIgFABIgDAAQAEgRgJACIgxAMQgeAHgaAOIgGAAIgZAAIAAADIAAAAQgbAGgWAJQAGAQADARIACARIABAAIALgKIAEAHQABABAAAAQABAAAAAAQABAAAAABQABAAABAAIAAgGQAVgWAZATIgEACQgMAIAZgBIAAgGQAWgPAQAFQAJADACAMQAAABAGAAIAZAAIAkASIAAgGIAAgMQARgLALAUIADgDQAGgGAAgMQAAAAgBAAQgBgBAAAAQAAAAgBAAQAAAAAAgBQgDgFAAgGQALgHAGgMIABgFIAAgGIgCgJQgDgNgHgJIgDAAQAKgjgTgUIAAgGIAAgTQAIgJAFgNIACgIIADAAQAEgcgJgQIgBgFIAAAAQgBAAAAAAQgBgBAAAAQgBAAgBAAQAAgBgBAAQgGgEgBgLIAAgCQAJgGADgMIAAgGIAAgGIgMhEIAAgGIABgMQgBgMgGgGQgKAAAGgMQANgagJgQQgMgZgHgeQgDAAgCgBQgHgFAAgMQALgCgCgQIADAAIABgHQAAgigHgbQANAQABAVQACAVgFAUIgCABIgDABIAAASQAdAoACAsIgLANIAFASIAHAIIACAFQAGATgJAKQAJAdAHAfQACAFgBAGIgFADIgBADIgEAKQgDAIADAIIAFAGIABACQAEAMABAMQADARgGAQQgDAIgGAIQgBAUAGASQAHAXgGAZIAJAHQAGAHABAIIAAAGQAAAHgDAGQgEALgJAPIAAAHIAPAFQAFADAFAEIATgQIAGADIAAAIQgJgCgKAHQAAAMgHAEQgFACgBgCQgOgfgEAhQAEANgGgFQgbgYgBAcIAAADIgxgPQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQgXgRgYAPQgGAAgDgDQgEgDADgDQARgNgmAKQgGAJgMABQgdADAMgQQAMgQggATQAAADgCACQgFAHgNAAIAAABIABACIgBAHIgIgCQgKAMgLgOIAJAAIgJgCIAAACQgGAAgGgCIgDgBQgVAWgHgfIgGAAIg3AGQgDAAgCACQgTAPgTgLIAAAGQADAOgKgBIgFAAQgDAAgDgCQgPgLgXgFIgFgBIgBAGQgBAXgLgRIgGAAIgjAAIgIAAQABAKgJgIQgKgJgMABQgKACgLAIIgDACIgBABIABgEIAAgKQgCgMgLABIgBAFIgLANIgBAEQgZAEgLgOIAAAGIAAAAIAAACQgBAGgCAEQgCAEgCAAQgCAAgFgEgAD7GzIAAADIgBAAIgBABQAAAAAAABQgBABAAAAQAAABgBAAQgBAAAAAAIAAAFIAAAGQATANAIgYQAAgBABAAQAAAAAAAAQABAAAAAAQABAAABAAIAAgGQAPAPAWgGQAbgHAQAGQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAgBIAHAGIAAgHIAAgRQAAgGgCAAQgZgFgSAHQgaAKgfAFIFIhhIlIBhIgPABgAhlHXQABAAAAAAQABAAABAAQAAAAABgBQAAAAAAAAQABgBAAAAQAAgBABAAQAAgBAAAAQAAgBAAgBIgGABIgBAAQgNAEgRABIAAADQgYADgNgMQgfAUAFgUIACgGIglAGIgGABQgNADABgKQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQAPgGAGgSQAAAAAAAAQAAAAABgBQAAAAABAAQABAAAAAAQAKACgDARIgBAGQAdgLALAJIAGAFQADADAGAAIAAgGQANAAALADIABADQAXAIAggLIAAADQACAdAogOQAHgDAMgBQANgCgBAJQgPAHgVACIgPABQgaAAgIgQgAkpHRQgIgdgQALQgEADgCgBQgNgFgNgJIAAADQgcAHgOgKQADgEADgBQADgCADAAQABgJgLAHIgGADQgSAJgDgQQgDAAgCgBQgNgLgIgQIgFgIQgFgIgKAQQgQAZgFgVQAMgCgCgNIgBgDQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgBAEIAAAAQgSAJgSAGQAAAAgBAAQgBgBAAAAQgBAAAAAAQAAAAgBgBQgDgGAEgHQAEgIALgIIAAgDQgbAGgWANIgGADIAAADQgKgFgHABQgHACgEAHIgCAEQgHAAgCgDQgNgSgHAKIgDAEQgPAVgJgUQAJgEAHgFIAIgJIAEgEIACAAQAHgDAGgGIAAgGIAAgGQAQgDgDgWIAAgGQgBAAgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgDgIAAgJIgFABIgUALIgRAMIAAgGIAAgGIARgKIALgFIAPgIQACgCADAAIABAAIAAgGIAAgJIAAgDIACgCIAGgIQAEgIADgJIAAADIABAOIgCANQgDAJgFAGIAAAKIAAAPIAAAGIABAGQAHAOgMALIgJAGIAAAGIABAGQADANgKgBQAIAEAHgBQAEgBAFgCQAJgEAIgLQABgBAAAAQABgBAAAAQAAAAAAAAQAAAAAAAAQADAMAJgBQAagaAbALIgCAEIgDAIQgDAHgFAGIgDADQAJgBAGgCQAHgDAEgFQABgBAAAAQABAAAAAAQABgBAAAAQABAAABAAIAJgOQAFgKADgNIABgGIAAgGIAAgSQABAAABAAQAAgBABAAQABAAAAAAQABAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIAAgDIAAgDIAGgHQAFgHAEgIIAEgNIADgOIADAAIAAgKIACgCIAAABIAJAAIgIAZQgLAbgRAaIABAAIgBACIAAAHIAAAFIgCAGIgBALIgEAOIgBACIgBABIgDABIAHAEIAAABIABAAIARALIABAGQADAHAGAGQAIAIAMgGIAAgGIAVgEIgJAWQALAHAMgCIAJACIABAKQAGAFALgCQAfgFAXATIAEACIAJgSIAAgGIAfAAIAAgYIASAGIAHgFIAFgSIAFAAIAAgDIAAgBIACAAIACAAIADAAIAPgBIAQgQQAIgJALgHIARgKIABAAIAQgEQAGgEAFgFIAKgLIAEgGIAAgCIAAgIIAAgCIAAgHIACgCIABgCIAAgCIAAgCIACgCIAHgIIABgCIABgCIABgBIAQgBIACgCIAFgHQAFgHADgIQADgFAEgEIABAAIALgDIAAgCIAEgIIABgCIADgGIABgBIARgBIACACIACAAIABgCIACgDIABgFIAAgCIAAgBIACgCIACgCIABgEIAaADIgOgkIAGAAIAAgGIAIgFIADgCIACgCIABgDIAAgDIgDgKIABgMQAKgCAEgIQAEgHgEgIQgIgRACgRIARgJIAAghIgPgDIAbAAIAAAYIAAAGQgBALgHAGIgDADQgMAHAKAUIABADQACAWgUAIIABAGQAKAXgYAIIAAAGIABAEIABAHIAGAPIACAFIABAEQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAgBgBIgDgCIgHAAIgGABIgMABIgCACIgCACIgBACIAAACIAAAEIAAACQgBAEgDADIgJAAIgCgBIgCgCIAAAAIgHAAIgCACQAAADgDADIAAACIAAACIgBACIgFAIIgKABIgHAKIgJANIgBABQgDADgBAGIgBAAIgRACIgCACIgGAHIgBACIAAACIAAACIgBACIgCACIAAACIAAAIIAAACIAAAHIgDAEIgIAJQgEAHgFAFIgEACIgDABIgBABIgTAEQgHAHgIAFQgTALgPATIAAAAIgBAAIgEAAQgCASgGgJIgHgCIAAACIAAACQAAAFgBAEIgBABIgEgBQgBAXgRgQIgGAAIgGAAIAAAMIAAAGQAAABAAAAQAAABAAABQAAAAgBAAQAAABAAAAQgIADgKAAQACAKAJAEQABAAAAABQAAAAABAAQAAABAAAAQAAABAAABIgHAAQgKgCgCgKIgDAAQAEAZgTAAIgGgBgAq7GkIABgEQAUgEADgFQAEgGAAgJQALgQACAQQABAIgCAQIAAAGQgEACgHAAQgLAAgSgEgAq6FyIAAgBQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAIAAgBIgCAAIAAgBIgBAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAIABAAIAHgCIAEgBIAAgBQAegKARgWQABgBAAAAQAAAAABAAQABgBAAAAQABAAABAAQAAADgCACQgSAYgcAOQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAABIgDAAIgFgBgAq+FBQAAgHAGgDIAHgFIAFgDIAFgEIABAAIATgMQAAAEgBABIgFAFIgSAPIgBAAIgBAAIAAAAIgDACIgIAHQACACgBADQAAAAAAAAQAAABAAAAQAAAAAAAAQgBABAAAAQgGgBAAgGgAoQEfIgCgPIAAgNIAAgCQAFgUANgLQALgJgMAVQgGAJgDAMIgDANIgCAPIAAAEgAqIEDIAFgGIADgCIAAgGIBng5IgMgNIAAgQIgQAPQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAgBAAQgLgOgGgTIAAgFIAAgBIAAgGQAXgNgBAgIgBAJIACgEIACgDIALAHIAAADIALAEIACABIACAAIAEABQAHAAAFgCQAGgDADgGQAAgBAAAAQABAAAAAAQAAAAABAAQABAAAAAAIAAgGQABAAABAAQAAgBABAAQABAAAAAAQABAAAAgBQABgBAAgEIAAgGIATgMIAAAAIAAAAIAGgDIAAADQAAABAAABQAAAAAAABQAAAAABABQAAAAAAABQACABADAAIAAgGIAAgGQgCgVgKgQQAJgBAGADIAHAsIABAIIgIANIAAAbIAAAAIAAABIAAgBIABADQgLAIAAgVIABgQIAAgHQgDAAgDACIgGAFIgBAFQgDAKgDABIgCAAQgCgBgCgDQAAAAgBAAQgBAAAAAAQAAAAgBAAQAAABAAAAIgCADQgFAHgHAEIgHADQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAgBAAIAAABIgDAGIgCADIgEAGIgHAIQgNAKgWACQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgGACgDAGIgCAGIgGABQgPACgLAHQgGAEgFAFIgEAIIgBAEIgDAJQgFALgMAEQACgPAJgNgAAyD1IABAAIAAABIgBgBgAFpD1IACAAIgCAAgApdCIIgXgOIAegYQAXAEgNASIgGAJQgJAQASgFQgBAKgFAGQgGAHgHABgAmLCUIAAADIgBAEIABgHgApWBVQAWgGAQgQIAKgIIAEAHIAEgHQAggSAgAVIADAJIAGgBIABAIQgFgEgIgDIgLAAIgBAAIgHAAIAEgEQADgFgGACQg2ALgtAbgAALA7IgBgBIAIgTIAQgSQgKANgDASQgBAHgHAAIgCAAgAgcAvIgGgFIAjgYIACAEIgBAFIgCAFQgKAPgRAAIgBAAgACVAXQgBgCAAgDIgGgBQgHgEgFgHQgEgFgDgGIAAgDIAAgDIgGAAIgGAAIAAADIgrgDIAAgGIAlAAIAAgGIAHgDIADgHQACgKAAgLIAAgGIgGgMQAGgFAHgEQASgNAVAKIgDAAQgTAIgKARQgCACAAADIAAADQABAIACAHQABAAAAAAQAAAAABAAQAAABABAAQAAAAABAAIAAgGIAAgGQATgVgMAnIgBAGQAVgVgIAVIgBAGQADADACAEIABAEIAAABQABAAABAAQAAAAABAAQAAABAAAAQABAAAAAAIADAKQACARgPABQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAgAmiAKIACACIgBADgABLgzIAAACQgGAKgJAFIAAAAQgCAAARgRgACmhOIABgBIANgIQAIgDAAAMQAAADgEADQgHAGgEAAQgGAAgBgMgACmhnQAFgaAUgQIAAgGQAAgFgCgFIAHgHIACgCIARAGIAAgGIAIAPIgBAKIgBAGQAAAJgCAIIgBAGIAAACQgGAggJgbIAGgHQAHgLgFgHQgCgCAAgDQgJAAgIADQgHADgBAGIgBALQgDARgEADgAECiPQgKgCAEgNIAGgGQAOgPABAPIAAADIAHADQADADgDADQgDAEgJAEQgCABgEAAIgEAAgACyiwIAPAFIgGAFQgDgFgGgFgAJZiwIgDAAQANgbACgpQAAgBAAAAQAAgBAAAAQAAgBAAgBQgBAAAAAAQgNgRgEgcQAOgHABgXIADAAIAAgGQgBgdgFgaIAGgHQAEgDABgDQAFgMgCgLIgBgGQgFgbgNgXIgBAAIgEAAIgBABQgWAIgHgJQgCgCgBgEIgGgBQgQgBgIAIIgBAAIgFAGQgDAGgFAEQgUAOgiAAIAAAGIAAAHQAEAAABABQABABAAAAQAAAAABABQAAABAAAAQAAABAAABIADAAIgBABIgoAeIgYASQAAgDACgDIABgDQgQAFgXAEIgBAGQgDAKgDAFIADADIADAFQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAQAQAKACgDQARgMgTAcQgEAFgKgSIgBACIgBABIgEABIgDABQAAADgDAFIgEABQAAAAAAABQABABAAAAQAAAAAAABQAAAAAAAAQAUAJgbAMQAAAMgFAIQgPAZgEgUQAAgBAAgBQAAAAAAgBQgBgBAAAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBAAgBAAQAAAAgBAAIgBAFQgIAUgcgBIgCABIABAAIABABQALACAKAGIgDACIgCABIgWAGIAFAEQAFAFgBAJIgDABQAAAAAAABQAAABAAAAQgBABAAAAQAAABgBAAIgHAIIgWASIgBAFIAAABIgEAIIgBADQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAgBgBAAQgCgCgBgEIgBgEIACgEIAEgIIgHAEIgEgCIgGgCIAHgEQAFgDABgDIAAgBQABgCgCgDIgHgDIgEAEIgCgBQgTANgSgKQAPgGAQgDQAFgCAFAAQAJAAACgJIAAgKIADgHIAfgMIAAgGQAMgCALgEQAJgFAEgJQAKgYgKgXIAlgQIAEAKIANgEIgIgOIgFAAIgEgHIAbgpIAEgCIAAgGIA3gfIAAgGQASgQAZAEQAPgXAcgBIAAgHIAkgDIACADQAFAGAMACQAQAAAIAFIAPAWQAIANABAOQACAZgRASIgBAAIAAAAIADAaQACASgBARIgCAFQgUAqAdAnQgCAYgRASIgBAcIgBAAQgBAAgDgJg");
	this.shape_32.setTransform(-4.4,0.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.instance_6}]}).wait(112));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,-73.2,144.2,131);


// stage content:



(lib.noun_Thing = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{scene4:0,scene4repeat:66});

	// timeline functions:
	this.frame_0 = function() {
		this.btn_menu.addEventListener("click", openMenu.bind(this));
		this.btn_goNext.addEventListener("click", openNext.bind(this));
		this.btn_goBack.addEventListener("click", openPrev.bind(this));
		
		function openMenu(){
		
		 window.open ("../menu/main_menu.html","_self");
		}
		
		function openNext(){
		
		 window.open ("noun_Idea.html","_self");
		}
		
		function openPrev(){
		
		 window.open ("noun_Person.html","_self");
		}
	}
	this.frame_86 = function() {
		this.gotoAndPlay("scene4repeat");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(86).call(this.frame_86).wait(1));

	// Buttons
	this.btn_goBack = new lib.goNext();
	this.btn_goBack.setTransform(57.6,339.3,1,1,0,0,180);
	new cjs.ButtonHelper(this.btn_goBack, 0, 1, 2, false, new lib.goNext(), 3);

	this.btn_goNext = new lib.goNext();
	this.btn_goNext.setTransform(494,339.3);
	new cjs.ButtonHelper(this.btn_goNext, 0, 1, 2, false, new lib.goNext(), 3);

	this.instance = new lib.Copyright("synched",0);
	this.instance.setTransform(275,389.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.btn_goNext},{t:this.btn_goBack}]}).wait(87));

	// Main
	this.btn_menu = new lib.skiptomenu();
	this.btn_menu.setTransform(514.1,20.3);
	new cjs.ButtonHelper(this.btn_menu, 0, 1, 2, false, new lib.skiptomenu(), 3);

	this.instance_1 = new lib.Thingbottom();
	this.instance_1.setTransform(275,356.3);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgMANQgFgGAAgHQAAgGAFgGQAGgEAGgBQAHABAFAEQAGAGAAAGQAAAHgGAGQgFAEgHAAQgGAAgGgEg");
	this.shape.setTransform(454.8,33.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgMANQgFgGAAgHQAAgGAFgGQAGgEAGgBQAHABAFAEQAGAGAAAGQAAAHgGAGQgFAEgHAAQgGAAgGgEg");
	this.shape_1.setTransform(447.4,33.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgMANQgFgGAAgHQAAgGAFgGQAGgEAGgBQAHABAFAEQAGAGAAAGQAAAHgGAGQgFAEgHAAQgGAAgGgEg");
	this.shape_2.setTransform(439.9,33.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAuBKQgGgGgDgEQgOAHgLAEQgLAEgFAAQgjAAgPgTQgPgSAAgmQAAghAYgZQAZgaAgAAQAMAAAQAHQAUAIAAAMQAAAEgDADQgCAFAAANIgBAfQAAASADAKIAJAaIADAIIABACQAAAGgEAEQgFAEgEAAQgDAAgIgHgAgXgjQgRASAAAWQAAAZAJAMQAIAMARAAQAMAAAJgGQAGgCAJgJQgEglAAgTIABgOIACgPIgJgEIgHgCQgUAAgQATg");
	this.shape_3.setTransform(428.5,27);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgXB8QgEgEAAgFIABgDQACgTAAgXIAAgoIAAgoIgXABQgPAAAAgOQAAgPAaAAIANgBIADgWQADggANgQQAOgSAgAAQAVAAAAAOQAAAOgTAAQgjAAgFAxIgBAJIAhgCQAXAAAAAPQAAALgLACQgFABgHgBIgiACIgBAgIABAbIAAAbQAAAcgCAPQgBAMgMAAQgFAAgFgEg");
	this.shape_4.setTransform(403.9,23.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgrA+QgTgUgCgjQAAgfARgZQAVgeAiAAQAeAAAPAbQAMAWgBAeQAAAfgRAXQgSAagdAAQgZAAgSgSgAgZgcQgKAQAAATQAAAWAMALQAKAKANAAQANAAALgLQAMgMABgVQACg3ghAAIAAAAQgTAAgMAVg");
	this.shape_5.setTransform(388.4,27);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgxA/QgXgSAAghQAAgkATgaQAUgcAhAAQAXAAAQAIQATAKAAAVQAAAPgRAMQgHAFgYAJIg2AbQAIAMAMAGQAMAGAPAAQAKAAANgEQASgFAFgHQAFgIAGAAQAFAAAEAEQADADAAAGQAAAQgaAMQgWAJgVAAQgfAAgVgQgAgdgmQgMAOgFAaIAtgUQAYgNALgJQgNgMgVAAQgRAAgMAOg");
	this.shape_6.setTransform(363.8,26.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgHBWQgEgEAAgHQAAgSgDgiQgEghAAgSQAAgPgFgJQgKAFgKAKIgSAUIgHAJIgCAYIgBAZIABANIABALQAAAGgEAEQgEAEgGAAQgRAAAAglIACgbIABgYIgBgXIgCgYQAAghAPAAQAGAAAFAFQAFAFAAAGIgBAJIgBAJIAAAPQAIgQAPgMQAPgNAKAAQAXAAAHAXQAIgLALgFQALgGAOAAQAZAAAJAbQACAFAEAkQAEAXAGA7QABAGgFAEQgEAEgGAAQgMAAgCgNQgDgQgDgdIgFgsQgBgKgEgJQgFgOgFAAQgGAAgPAKQgOAIgEAFIABAcIAEAlQADAXAAAPQAAAHgEAEQgEAEgHAAQgEAAgEgEg");
	this.shape_7.setTransform(343.9,26.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAuBKQgGgGgDgEQgPAHgKAEQgLAEgFAAQgjAAgPgTQgPgSAAgmQAAghAYgZQAZgaAgAAQANAAAPAHQAUAIAAAMQAAAEgDADQgCAFAAANIgBAfQAAASADAKIAJAaIADAIIABACQAAAGgEAEQgFAEgEAAQgDAAgIgHgAgXgjQgRASAAAWQAAAZAJAMQAIAMARAAQAMAAAJgGQAGgCAKgJQgFglAAgTIAAgOIADgPIgJgEIgHgCQgUAAgQATg");
	this.shape_8.setTransform(324.4,27);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAjBHIgEggQgCgRAAgPIABgMIAAgOQAAgggMAAQgQAAgNAUQgNARgIAaIgBAOIgBAOIABANIABANQAAAHgEAEQgFAEgGAAQgGAAgEgEQgEgEAAgHIgBgNIgBgNQAAgPACgZIACgqIAAgNIgBgOQAAgHAEgEQAEgEAHAAQANAAABATIABARQAYggAYAAQAYAAAJAUQAGAOABAbIAAAPIAAALQAAANADATQADATAAAMQAAAHgEAEQgEAEgHAAQgMAAgCgOg");
	this.shape_9.setTransform(309.2,26.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgxA/QgWgSAAghQAAgkASgaQAVgcAgAAQAXAAAPAIQATAKAAAVQAAAPgQAMQgIAFgXAJIg2AbQAIAMANAGQALAGAPAAQAKAAAOgEQARgFAFgHQAFgIAFAAQAGAAADAEQAFADAAAGQAAAQgaAMQgXAJgVAAQggAAgUgQgAgdgmQgMAOgGAaIAtgUQAZgNALgJQgMgMgWAAQgRAAgMAOg");
	this.shape_10.setTransform(275.1,26.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAoBuQgEgMgDgWQgDgVABgOIAAgLIABgMQgBgZgOAAQgRAAgNAOQgIAJgNAYQAAA4gFAKQgEAJgJAAQgGAAgEgEQgFgEAAgGIACgGQABgEAAgRIAAgWIABhqIABgYIgBgOIgBgOQgBgGAEgEQAFgEAGAAQAMAAACAMQACAPAAALIgBAgIgBAgIAAANQAMgQAOgIQAMgIAPAAQAZAAAJAQQAGALABAYIABAcIADAfQACARAEANIAAAEQAAAGgFAEQgEAEgGAAQgLAAgCgLg");
	this.shape_11.setTransform(258.2,22.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgIBnQgEgEgBgGIABgQIAAgRIgChUIghgCQgNgCAAgNQAAgGAEgFQAEgEAGAAIAfACIAAgTIgBgSQgBgHAFgDQAEgFAGAAQAMABACAVIAAANIAAAJIAAAIIAUgCQAPAAAFACQAJADAAAKQAAAHgEAEQgEAEgGAAIgIAAIgHAAIgUACIADBVIAAAGIAAAHQABAhgQgBQgEABgEgEg");
	this.shape_12.setTransform(242.2,24.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgoBRQgWgIAAgPQAAgGAEgEQAFgEAGAAQAEAAAIAHQADADAMACIARACQAKAAAKgDQANgEAAgJQAAgUgcgHIgNgEQgTgEgJgGQgLgGAAgQQAAgfAcgNQAJgEASgGIAbgJQAGgDAHAAQAHAAAEAFQAEAEAAAGIACANIABAMQAAAHgEAEQgEAEgGAAQgIAAgDgFQgCgEgCgMIgiAKQgWAJAAAOIAJACQAgAGAQALQAYANAAAeQAAAXgVANQgRAKgYAAQgTAAgSgHg");
	this.shape_13.setTransform(209.5,26.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgNBqQgEgFAAgGIAAgaIgBgaIABgjIACggQAAgHAEgEQAEgEAGAAQAFAAAEAEQAEAEAAAHIgCAgIgBAjIAAAaIABAaQAAAGgEAFQgEADgFABQgGgBgEgDgAgIhPQgFgGAAgHQAAgHAFgFQAFgEAFAAQAHAAAFAEQAFAFAAAHQAAAHgFAGQgFAEgHAAQgFAAgFgEg");
	this.shape_14.setTransform(198.7,23.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0000FF").s().p("AAjBHIgEggQgCgRAAgPIABgMIAAgOQAAgggMAAQgQAAgNAUQgNARgIAaIgBAOIgBAOIABANIABANQAAAHgEAEQgFAEgGAAQgGAAgEgEQgEgEAAgHIgBgNIgBgNQAAgPACgZIACgqIAAgNIgBgOQAAgHAEgEQAEgEAHAAQANAAABATIABARQAYggAYAAQAYAAAJAUQAGAOABAbIAAAPIAAALQAAANADATQADATAAAMQAAAHgEAEQgEAEgHAAQgMAAgCgOg");
	this.shape_15.setTransform(177.8,26.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#0000FF").s().p("AAgBGQgSAJgWAAQgTAAgNgIQgNgKgDgSQgGgnAAgcQAAgUAFgaQACgMAMAAQAGAAAEAEQAEAEAAAGIgCAVIgCAXQAAAYACAQQABARAEALQAEADAFABIAJABQASAAAWgGIAAgeIgBgaQAAggADgXQACgOAMAAQAHAAAEAFQAEAEAAAGIgDA3IAAAeIAAAfIABAKIAAAKQAAAGgEAFQgEADgGAAQgLAAgEgNg");
	this.shape_16.setTransform(161.8,26.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#0000FF").s().p("AgrA+QgTgUgCgjQAAgfARgZQAVgeAiAAQAeAAAPAbQAMAWgBAeQAAAfgRAXQgSAagdAAQgZAAgSgSgAgZgcQgKAQAAATQAAAWAMALQAKAKANAAQANAAALgLQAMgMABgVQACg3ghAAIAAAAQgTAAgMAVg");
	this.shape_17.setTransform(145.8,27);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#0000FF").s().p("AAjBHIgEggQgCgRAAgPIABgMIAAgOQAAgggMAAQgQAAgNAUQgNARgIAaIgBAOIgBAOIABANIABANQAAAHgEAEQgFAEgGAAQgGAAgEgEQgEgEAAgHIgBgNIgBgNQAAgPACgZIACgqIAAgNIgBgOQAAgHAEgEQAEgEAHAAQANAAABATIABARQAYggAYAAQAYAAAJAUQAGAOABAbIAAAPIAAALQAAANADATQADATAAAMQAAAHgEAEQgEAEgHAAQgMAAgCgOg");
	this.shape_18.setTransform(130.7,26.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AAzBLIgKguQgPACgYAGIglAIQgIATgRAlQgEAIgJAAQgFAAgFgFQgFgEAAgGQAAgHAXgvQgDgDAAgFQAAgMAOgDQARgeAagoQAgg4AJAAQALAAAEAQIAJAyIAXBjIAIAYQAEALAAAEQAAAGgEAEQgFAFgGAAQgNAAgKgjgAgSAKQASgEAigGIgLg4g");
	this.shape_19.setTransform(102.4,23.6);

	this.instance_2 = new lib.Main();
	this.instance_2.setTransform(282,204.5,2.241,2.241);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance_1},{t:this.btn_menu}]}).wait(87));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(284.2,199.1,537.1,399.8);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;