(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 550,
	height: 400,
	fps: 12,
	color: "#FFFFFF",
	manifest: [
		{src:"sounds/activevoiceiswhen.mp3?1497386750489", id:"activevoiceiswhen"},
		{src:"sounds/activevspassivevoice.mp3?1497386750489", id:"activevspassivevoice"},
		{src:"sounds/applause_cheering.mp3?1497386750489", id:"applause_cheering"},
		{src:"sounds/bgmusic.mp3?1497386750489", id:"bgmusic"},
		{src:"sounds/bgmusic2.mp3?1497386750489", id:"bgmusic2"},
		{src:"sounds/_3a.mp3?1497386750489", id:"_3a"},
		{src:"sounds/_4b.mp3?1497386750489", id:"_4b"},
		{src:"sounds/bubpitchedthe.mp3?1497386750489", id:"bubpitchedthe"},
		{src:"sounds/wrong_answer.mp3?1497386750489", id:"wrong_answer"},
		{src:"sounds/congratulationsgreg.mp3?1497386750489", id:"congratulationsgreg"},
		{src:"sounds/SENameofIdea.mp3?1497386750489", id:"SENameofIdea"},
		{src:"sounds/_7a.mp3?1497386750489", id:"_7a"},
		{src:"sounds/highclick.mp3?1497386750489", id:"highclick"},
		{src:"sounds/imagine_shuffle.mp3?1497386750489", id:"imagine_shuffle"},
		{src:"sounds/knowthedifference.mp3?1497386750489", id:"knowthedifference"},
		{src:"sounds/learntowriteintheactive.mp3?1497386750489", id:"learntowriteintheactive"},
		{src:"sounds/lowclick.mp3?1497386750489", id:"lowclick"},
		{src:"sounds/parrotmove1.mp3?1497386750489", id:"parrotmove1"},
		{src:"sounds/parrotmove2.mp3?1497386750489", id:"parrotmove2"},
		{src:"sounds/passivevoicewhenthesubject.mp3?1497386750489", id:"passivevoicewhenthesubject"},
		{src:"sounds/SENameOfPerson.mp3?1497386750489", id:"SENameOfPerson"},
		{src:"sounds/_6b.mp3?1497386750489", id:"_6b"},
		{src:"sounds/theballwaspitchedatbub.mp3?1497386750489", id:"theballwaspitchedatbub"},
		{src:"sounds/_2a.mp3?1497386750489", id:"_2a"},
		{src:"sounds/writeyouressayintheactivevoice.mp3?1497386750489", id:"writeyouressayintheactivevoice"}
	]
};



// symbols:



(lib.nextSEGMENT = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgEA5QgDgCAAgEIABgDIAAgEIAAgLIgBgMIgCgdIgCgfIgHAAQgRgBgKgCQgGgCAAgFQAAgEACgDQACgCAEAAIAMACIANAAIAOAAIAMAAIASABIASABQAEAAACACQACACAAAEQAAADgCADQgCACgEAAIgSgBIgRgBIgGAAIACAjIACAhIAAAIIABAJQAAAFgCAEQgCAFgEAAQgCAAgCgCg");
	this.shape.setTransform(-68.9,-51.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgzA9QgCgDAAgEIAAgKIABgJIAAgPIAAgOIAAgOIAAgQIgBgOIgBgPQAAgDADgDQADgDAEAAQAEAAAGAJQAUAdAOATQASAVAWAVIAAgKIAAgKQAAgggDgUIgCgJIgCgIQAAgJAJAAQANAAAAAzIAAAYIAAAZIgCANQgBAIgHAAQgEAAgGgGQgggdgng4IgBASIAAAQIABAUIAAATQAAAVgIAAQgFAAgCgCg");
	this.shape_1.setTransform(-81.3,-51.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AghA8QgIgHABgZIAAgLIABgNIgBgEQAAAAAAAAQAAAAAAAAQAAgBAAAAQABgBAAAAIACgiIgBgJIgBgIQAAgJAIAAQADAAACACIASgEIAOgBQASAAAMAEQAFADABAFQgBAEgCACQgCACgEAAIgCAAQgNgEgMAAIgNACIgPADIAAAIIgBAeIAggEIASgBQAEAAACACQACACAAAEQABAGgIAAIgSACIgiADIgBAKIAAAKQAAARADADQACACAKAAIANAAIAOAAIAFAAIAEgBQAIAAAAAIQAAAHgGABQgIABgWAAQgYAAgHgGg");
	this.shape_2.setTransform(-92.5,-51.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAvA6QgCgDgCgJIgCgOIgKg1IgQAtIgFAPQgDAJgDAGQgDAGgDAAQgFAAgDgFIgDgJIgDgIQgHgcgGgdIgDAOIgKAnQAAAHgEAOQgDAGgFAAQgDAAgDgCQgBgDgBgDQAAgNAGgTIAIgeIAFgYQADgSAEgFQADgEAFAAQAFAAADAFQADAHADAWQAEAZAJAcQAJgcAJggIACgMQACgHACgEQADgGAFAAQAHAAAEANIACATQAFAhAHAZIAEAOIACANQABADgDACQgDADgDAAQgEAAgDgFg");
	this.shape_3.setTransform(-104.7,-51.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgmA1QgKgLAAgWQAAgUAKgTQAJgVAPgOQAKgIAJAAQAHgBAMAFQAOAFAAAIQAAADgDACQgCADgDAAIgFgDQgMgGgIAAQgFAAgGAFIgJALQgSAYAAAaQAAAPAFAGQAFAGANAAQAMABALgKQAKgJAEgRQgVABgOAHIgDABQgDAAgDgDQgCgCAAgEQAAgEAEgCQAPgJAqAAQADAAACADQACAAABADQgBAGgEABQgFAZgPAOQgQAOgTAAQgTABgJgLg");
	this.shape_4.setTransform(-117.2,-51.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AghA8QgHgHgBgZIAAgLIABgNIgBgEQAAAAABAAQAAAAAAAAQAAgBAAAAQABgBAAAAIABgiIgBgJIAAgIQAAgJAHAAQAEAAADACIARgEIANgBQATAAAMAEQAGADgBAFQAAAEgCACQgCACgDAAIgDAAQgNgEgNAAIgLACIgRADIABAIIgBAeIAggEIATgBQADAAADACQACACAAAEQAAAGgIAAIgSACIgiADIAAAKIgBAKQAAARACADQACACALAAIAMAAIAPAAIAEAAIAFgBQAJAAAAAIQAAAHgHABQgHABgXAAQgYAAgHgGg");
	this.shape_5.setTransform(-127.5,-51.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgeA2QgPgHAAgMQAAgDACgDQADgBADAAQAEAAADAEQAEAGADACQAHAEAMABQAKgBALgFQANgHAAgMQAAgKgLgFQgKgFgMAAQgMAAgJgEQgLgGAAgMQAAgOAQgLQAPgLAOAAQAIAAAJACQANAEAAAFQAAAHgHAAIgLgCIgMgBQgKAAgJAFQgIAGAAAJQAAAHALACIAPACQASABAKALQAJAGAAANQAAAUgRAKQgPAKgSAAQgOAAgMgFg");
	this.shape_6.setTransform(-138.3,-51);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgEA5QgDgCAAgEIABgDIAAgEIAAgLIgBgMIgCgdIgCgfIgHAAQgRgBgKgCQgGgCAAgFQAAgEACgDQACgCAEAAIAMACIANAAIAOAAIAMAAIASABIASABQAEAAACACQACACAAAEQAAADgCADQgCACgEAAIgSgBIgRgBIgGAAIACAjIACAhIAAAIIABAJQAAAFgCAEQgCAFgEAAQgCAAgCgCg");
	this.shape_7.setTransform(-153.5,-51.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAlA8IgMgPIgLgQIgMgSIgZAfIgOARQgDACgDAAQgDAAgDgCQgCgDAAgDQAAgDACgCIAOgQIAdggIgSgXIgJgMQgFgIgFgEQgDgCAAgEQAAgDACgDQACgCAEAAQAGAAALAOIAJAOIAPAVIASgZQARgYAGAAQADAAACACQADADAAADQAAADgDACIgQAVIgJAPIgLAMIARAYQAKAPAIAKQACACAAADQAAADgCADQgCACgEAAQgDAAgCgCg");
	this.shape_8.setTransform(-165.5,-51.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AghA8QgIgHAAgZIAAgLIABgNIgBgEQAAAAABAAQAAAAAAAAQAAgBAAAAQABgBAAAAIACgiIgBgJIgBgIQAAgJAHAAQAEAAACACIASgEIAOgBQASAAAMAEQAGADAAAFQAAAEgDACQgCACgDAAIgDAAQgNgEgMAAIgNACIgQADIABAIIgBAeIAggEIASgBQAEAAADACQABACAAAEQABAGgIAAIgSACIgiADIgBAKIAAAKQAAARACADQACACALAAIAMAAIAPAAIAEAAIAFgBQAJAAAAAIQgBAHgGABQgIABgWAAQgYAAgHgGg");
	this.shape_9.setTransform(-175.9,-51.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgzA9QgCgDAAgEIAAgKIABgJIAAgPIAAgOIAAgOIAAgQIgBgOIgBgPQAAgDADgDQADgDAEAAQAEAAAGAJQAUAdAOATQASAVAWAVIAAgKIAAgKQAAgggDgUIgCgJIgCgIQAAgJAJAAQANAAAAAzIAAAYIAAAZIgCANQgBAIgHAAQgEAAgGgGQgggdgng4IgBASIAAAQIABAUIAAATQAAAVgIAAQgFAAgCgCg");
	this.shape_10.setTransform(-187.5,-51.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AghA8QgIgHAAgZIAAgLIABgNIgBgEQAAAAABAAQAAAAAAAAQAAgBAAAAQABgBAAAAIACgiIgCgJIAAgIQAAgJAHAAQAEAAADACIARgEIAOgBQATAAALAEQAGADAAAFQAAAEgDACQgCACgDAAIgDAAQgNgEgMAAIgNACIgQADIABAIIgBAeIAggEIASgBQAEAAADACQACACAAAEQAAAGgIAAIgSACIgiADIgBAKIAAAKQAAARACADQACACALAAIAMAAIAPAAIAEAAIAFgBQAJAAAAAIQgBAHgGABQgHABgXAAQgYAAgHgGg");
	this.shape_11.setTransform(-203.5,-51.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgwA+QgCgDAAgDIACgZIABgYIAAgMIgBgMIABgTIABgSQAAgEACgCQACgDADABQAEgBACADQACACAAAEIgBASIgBATIABARIAggEQATgEAOAAIABgiQAAgGACgFQACgJAFAAQADAAACACQADADAAADIgBADQgBADAAAGIAAAHIAAAIIgBAWIgCAWIABASIABASQAAADgCACQgCACgDABQgDgBgDgCQgCgCAAgDIgBgSIgBgSIABgLQgOAAgSADIggAHIgBAUIgCAUQAAADgCADQgCABgDAAQgEAAgCgBg");
	this.shape_12.setTransform(-214.8,-51.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgEA5QgDgCAAgEIABgDIAAgEIAAgLIgBgMIgCgdIgCgfIgHAAQgRgBgKgCQgGgCAAgFQAAgEACgDQACgCAEAAIAMACIANAAIAOAAIAMAAIASABIASABQAEAAACACQACACAAAEQAAADgCADQgCACgEAAIgSgBIgRgBIgGAAIACAjIACAhIAAAIIABAJQAAAFgCAEQgCAFgEAAQgCAAgCgCg");
	this.shape_13.setTransform(-225.8,-51.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgmAwQgRgOAAgWQABgZAPgXQASgYAZAAQAaAAAMALQAOAMAAAaQAAAZgPAWQgRAZgZAAQgWAAgPgNgAgagZQgNARAAAUQAAAPALAJQAMAJAPAAQARAAANgTQAKgRABgUQAAgSgJgIQgIgHgTAAQgRAAgNATg");
	this.shape_14.setTransform(-243,-51.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgEA5QgDgCAAgEIABgDIAAgEIAAgLIgBgMIgCgdIgCgfIgHAAQgRgBgKgCQgGgCAAgFQAAgEACgDQACgCAEAAIAMACIANAAIAOAAIAMAAIASABIASABQAEAAACACQACACAAAEQAAADgCADQgCACgEAAIgSgBIgRgBIgGAAIACAjIACAhIAAAIIABAJQAAAFgCAEQgCAFgEAAQgCAAgCgCg");
	this.shape_15.setTransform(-254.3,-51.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgmAwQgRgOAAgWQABgZAQgXQARgYAZAAQAaAAAMALQAOAMAAAaQAAAZgPAWQgRAZgZAAQgWAAgPgNgAgagZQgMARAAAUQgBAPALAJQALAJAQAAQARAAANgTQAKgRABgUQAAgSgJgIQgIgHgTAAQgRAAgNATg");
	this.shape_16.setTransform(-271.5,-51.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgmA1QgKgLAAgWQAAgUAKgTQAJgVAPgOQAKgIAJAAQAHgBAMAFQAOAFAAAIQAAADgDACQgCADgDAAIgFgDQgMgGgIAAQgFAAgGAFIgJALQgSAYAAAaQAAAPAFAGQAFAGANAAQAMABALgKQAKgJAEgRQgVABgOAHIgDABQgDAAgDgDQgCgCAAgEQAAgEAEgCQAPgJAqAAQADAAACADQACAAABADQgBAGgEABQgFAZgPAOQgQAOgTAAQgTABgJgLg");
	this.shape_17.setTransform(-283.3,-51.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(4));

	// Background
	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#000000").ss(2,1,1).p("A0ijoIa2AAIAAjOIOPG3IuPG2IAAjBI62AAg");
	this.shape_18.setTransform(-163.4,-52.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FCC547").s().p("AGVD2I62AAIAAneIa2AAIAAjOIONG3IuNG2g");
	this.shape_19.setTransform(-163.4,-52.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#5FFEFE").s().p("AGVD2I62AAIAAneIa2AAIAAjOIONG3IuNG2g");
	this.shape_20.setTransform(-163.4,-52.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18}]}).to({state:[{t:this.shape_20},{t:this.shape_18}]},1).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-295.9,-97.6,265,89.9);


(lib.fcb_rightOut = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// element
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#808080").s().p("AhABAIAAgKIB2AAIAAh2IAKAAIAACAg");
	this.shape.setTransform(6.5,6.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,13,13);


(lib.fcb_rightIn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// element
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D4D0D8").s().p("Ag2A2IAAgKIBiAAIAAhiIAKAAIAABsg");
	this.shape.setTransform(6.5,6.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1,1,11,11);


(lib.fcb_leftOut = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// element
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#808080").s().p("Ag7A7IAAh2IB2AAIAAAKIhsAAIAABsg");
	this.shape.setTransform(6,6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,12,12);


(lib.fcb_leftIn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// element
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D4D0D8").s().p("AgxAxIAAhiIBiAAIAAAKIhYAAIAABYg");
	this.shape.setTransform(6,6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1,1,10,10);


(lib.fcb_hitArea = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// element
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#808080").s().p("AhABAIAAiAICAAAIAACAg");
	this.shape.setTransform(6.5,6.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,13,13);


(lib.fcb_check_disabled = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// element
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#808080").s().p("AgLAiIAAAAIgVgWIgCgDIABgRQgBgGAGAAIAEACIAQAQIAggjIAFgCQAGAAAAAGIAAARIgCAEIgmAmIgEACg");
	this.shape.setTransform(3.6,3.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,7.1,7);


(lib.fcb_check = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// element
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgLAiIAAAAIgVgWIgCgDIABgRQgBgGAGAAIAEACIAQAQIAggjIAFgCQAGAAAAAGIAAARIgCAEIgmAmIgEACg");
	this.shape.setTransform(3.6,3.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,7.1,7);


(lib.fcb_background_pressed = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// element
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("AgsAtIAAhZIBZAAIAABZg");
	this.shape.setTransform(4.5,4.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,9,9);


(lib.fcb_background_disabled = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// element
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("AgsAtIAAhZIBZAAIAABZg");
	this.shape.setTransform(4.5,4.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,9,9);


(lib.fcb_background = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// element
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgsAtIAAhZIBZAAIAABZg");
	this.shape.setTransform(4.5,4.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,9,9);


(lib.blank_gr = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00CCFF").s().p("Aj9CqIAAlSIH7AAIAAFSg");
	this.shape.setTransform(32.5,17,1.275,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,65,34);


(lib.ButtonBackground = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF0000").ss(0.1,1,1).p("AEtC5IpZAAIAAlxIJZAAg");
	this.shape.setTransform(31.2,19);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFF00").s().p("AkrC5IAAlxIJYAAIAAFxg");
	this.shape_1.setTransform(31.2,19);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,-0.6,62.2,39.2);


(lib.anim_pro_pointer = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mainbody
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.1,1,1).p("AgOrGQAPAAAKgVQAkgHgKgdQAVgPgNgeQAOgPgKgZQAigWghgVQgFgDgHAAQAegigZgfQgEgFgEgDQgMgKAIgdQAFgQgUADQgKACgEAFQASgfgVgEQgTgDgFALQAPgngfgVQgFgCgCAAQgEABAAAIAEjj2QAJADAUgDQAlgDAmgGQAngHAigTQAigTAXgfQAVgdAHglQAIgmgFgnQgFgmgagcQgYgZglgMQgfgJgiAAQgIgagPgSQgXgcgbgTQgegVgkgMQgkgNgoAEQgjAEglAFQgTACgTACQgCAAgCABQgQABgQABQggADgUgKAC3kmQACAAABgBQAZgMACgSQAEgmAZgdQAYgcAggSQALgGALgGQgZgOgZgFQgegHgSgUQAAAVgHAWQgMAjgYAdQgQASgUAPQASAeAVAeQAAABABABQAAABAAAAQAVAfAIAkQAGAdgIAZQgFACgFACQACAGACAGQAJAcgCAgQgBAGAKAGQAUALAGAXQAOgFANgGQAkgQgLgkQgJgfgdADQgBALAFAKAFunYQgXAKgXAMABklMQAKgDANgIQAKgGAKgHQgCgCgBgCAAyleQASAgAUAfQAVAhgCAoQgCAbgJAXAEekSQAEAOABAOQgFgCgCgCAEEiNQAAgJAEgKQAHgUAKgVQAKgWAAgXADenwQgsgUgoAEAD2iKQAHgDAHAAAD2gyQAAAAABABQAAACABADQAGAkAKAkQAJAjAJAlQAKAmAJAhQAEAQAEAPQADAMADAMQABACABACQAAAAAAAAQAQAjglASQgRAJgQAKQAAAcACAaQADAoAFAmQAFAlAKAjQALAkAEAmQAFAngGAmQgGAmgFAlQgFAlACAnQACAnAFAlQAAAEABADQACALAFAKQgCgEgCgFQgDgFAAgHADIioQgSAIgRAJQgZAOghAVQghAWglAIQgjAHgmgBQglgCglgGQgUgEgTgGQgcgKgggCQAAgCgBgDQAAAAAAAAQgGgXgZgIQgLgEAAgIQACgigIgZQgJgbgTgMQgGgDgGgDQgSgKgNgRQgXgdgPghQAAgBgBgBQAAAAAAAAQAAgBgBgCQgBABAAABQgCACgCACABaAmQAFAlANAjQANAlAPAlQAFAKADAKAGFRgIAAAAQAJAwgugDQgogCgSgiQgTgigYgXQgXgWgfgbQgggaACgbIAAAAQAAgBAAAAQAAgBAAAAIAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgJABgNQADgjAFgnQAFgngMglQgMglgUgiQgUghgNglQgNgjgMgkQgMglAJgnQAHgdAJgcQAAgCABgDQAAgCgBgBQgDgLgFgMQgMgfgOgiQgBAAgBgBQgNgDgOgDQgfgJgIglQgJgigKgkQgCgGgBgGQguApg3AmQgrAegvATQgBgMgEgKQgGAZgRASQgaAcgdAQQgWANgMASQgBABAAAAQAJANASAKQAiATACApQABAigKAlQgLAkgHAkQgHAlALAkQAKAkALAkQALAhATAdQATAdAZASQAKAPAHAQQALAZgMAXQgQAcgrgBQgpgBgjAGQgiAGgTAcQgSAagfAKQgWAHgYAAQgpAAgEgUQgUAAAEgJQAAgEABgDQABgDABgDQgNgBAAgJQgOABAAgPQAAgOAKgGQAJgFACAAQAIgCAJgBQAWgCAZADQATACARgIQAcgMAegSQAcgRAGgjQADgMAAgMQACgYgGgYAEHEuQgNAIgNAJQgcAUgjAOQghAMgmgGQgWgDgWgFAGzQGQAAAAABAAQAbAUgcAWQgBAKgHANQgBABgBABQgCABgDACQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAgBQAHgRgKgIQgMgKgSABAGzQGQgGgFgHADAEvOQQANAZAPAXQAUAdAfAIQAgAIAVAZAGFRgQgHgkgjgPQgUgIgFANAGjRMQgNAfgRgLAGzQwQAAgUgbgFAhixqQAIgNATAHQAJAEAGAEQALAKgDANAinxkQAEgTATgMQAAAAABgBQAJgFAJABQAeAEgEAZQAAABABAAQgCACAAADQAAgDABgDAhkxlQgCACAAADAkvxeQgEgMARgPQAOgMAKgCQALgCAHALQADAEACAIQACAGABAIQABgIAEgIQAEgKAKgJQAIgIAMADQAGACAFACQAXALAAAZQgBAGAAAGAlNuvQAjAOAPgdQApAPAcgZQAqAfA4gLQAJgBAHgDQgZAgAzAJQAGABAGAAQAAADAAADQALgaAVAkQAEAHABAHQABALgGAKQgEAKgJAAQgFABgGgCAlfxBQgDgIAJgNQAVgcAVAUQACAFAHAFAlfxBQACAEAFADAlKu6QgBAGgCAFQAAAAAAAAQgGASgTAFQATAQgZAaQAiAGgQAuQAXAPgCAnQgBAhAWAYQAWAYAgAFQAFABAFABQABABAAAAQASAEAMAKQAcAZAqgNQASgFAHgOAkitXQACAAADABQAWAGALgKQABgBABgBQABgngfgIQgPgDgHAKIAAABIAAAAQATAEgEAeQgBAGgCAEQgDgCgDgBQgXgLAPgbQABgCABgBAiwtuQAHAAAKgDQAdgIgTgcQgIgNgLACQgRgEgIADQgGACgCAEQgGAJAHAUQACAHAFAEQAGAFALAAQACgEAAgGQgBghgagCAkSp4QgCgDAAgFQgKAEgPgCQgQgCgFgYQgNADgNgCQgngGAVgjQgKANgTgKQgUgLACgQQABgDACgDQgBAAAAAAQABgDACgDQgEACgHgDQgLgFgHgJQgFgHgCgGQgBgIACgKQABgCACgDQAFgHALgGQgQAGgQgMQgegUAYgUIABgBQAGgGALgFQgMAEgKgGQgNgJAAgNQACggAdgIQgLACgFgHQgOgQADgMQACgMAVgHQgTgIAGgRQABgEADgFQASghAcAIQgDgOADgNQACgIAEgIQADgFADgEQAYgcAcAcAjktAQgugCgBAkQgBAgAkgMQAMgEAKgIAg+uIQgCAGgCAIAhpskQAAAAABAAQACACADABAhpskQgPgJgKgRQALAmghAQQghAQghAJQAOAUAdAGQAPAEALgIQAWgSAJgfQAFgPAIgLgAgdrOQAHAFAIADQgGABgIgDQAEAQALAPQAFAHAIAIAgrtRQAOAUACAZQAIAZgIAdQgEARACAPQAAADABADAmdrYQABgDABgDAmYrkQADgBABgFAh4pHQA4gNAggwAjwqsQgQAagPAWQgBACgCABQAAABAAAAAlfpUQAMgCANgDQABAAABAAQAhgHARgYAlxlkQgBgBAAgCQgMgeAEgjAjZkRQALgMAMgJQARgOATgJAkekAQAJADALACQAOACAQgBAhjkwQgrgogRhBQgQg+ARg0AhYjSQABgBABgBQgegPAKgqAgZjaQghgWgcAcQACABADABQgQApArASAjWpVQAUANAWAEAhxiCQAagTAiAPAnGD7QgagIAYgoQAUggAQgbQASggAWghQAVgeATgfQATgbAjgPQARgHgCgOQgCgLgCgNQgBgIAHgGQASgTAcgKQAGgCAHgBIAAAAAlgDzQAagCAYAPQAfATAbAXQALAKAGAOAlgDzQAVgfATgiQAUghAWghAnGD7QAEABAEABQAnAFAkgLQAKgDAJgBAgfDYQgKgcgNgZQgSgkgegTAlVOIQgFgXgJgSQgOgdgRghQgRgigVgfQgTgdgJghQgIgigLglQgLglgQgcQgRgcgTgZQgTgbAKgpQAJgjAQgeQASgiASgbQAOgUAOgUAlUG5QgEAFgCAGAhcjLQgrgPgJAgAibj4QgYApAjA+AoFRBQAGgOAEgJQAPglAsATAoGP+QgkALALAYAoSQrQAKghAmAAAhOlMQA0gLA9AEAghiFQAKgqAsAT");
	this.shape.setTransform(323.2,118);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAcBmQgcgHgNgTQAfgKAhgQQAhgQgLgkQAKAPAPAJQgJALgEAPQgJAggWARQgIAGgKAAIgIgBgAhQgaIgFgBQACgEABgFQAEgfgTgEIAAAAQAHgLAPAEQAfAHgBAoIgCABQgHAGgLAAQgHAAgIgCgAAdg8QgBghgagCQACgEAFgCQAJgCARADQALgCAIANQATAcgdAJQgKACgHAAQACgEAAgGg");
	this.shape_1.setTransform(302.7,35.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AC2L5IgsgIIgCAAIgbgHQghgIgIglIgThGIgEgNQgJgcgNgZQgSgjgcgUQAcAUASAjQANAZAJAcQgtApg1AnQgrAdgvATQgBgMgEgKQgGgOgLgKQgbgWgfgUQgYgOgaABQAVgfATghQAUghAWgiQgWAigUAhQgTAhgVAfQgJABgKADQgkALgngFIgIgCQgagIAYgoIAkg7QASggAWghIAog8QATgeAjgOQARgIgCgOIgEgXQgBgIAHgHQASgTAcgJIAMgEIACAGQAgACAcAJQATAHAUADQAjAGAlACQAoACAjgIQAlgIAhgVQAhgWAZgOQARgJASgHIAEALQAJAdgCAgQgBAFAKAGQAUAMAGAWIACAHQAGAjAKAmIASBJIATBHIAIAeIAGAYIABAEIABABQAQAjglASQgRAIgRAKIgZARQgcAVgjANQgVAIgZAAQgMAAgNgCgAC7IBQANAlAPAkIAIAUIgIgUQgPgkgNglQgNgkgFglQAFAlANAkgAkRKFIAAAAgAjFjuQgKAEgPgCQgQgCgFgYQgNADgNgCQgngFAVgkQgKANgTgKQgUgLACgQIADgGIgBAAIACgGQAEgBABgFQgBAFgEABQgDACgHgCQgLgFgHgJQgFgIgCgGQgBgIACgKIACgFQAGgHALgGQgQAGgQgLQgegVAYgUIAAgBQAHgFALgGQgMAFgKgHQgNgIAAgOQACgfAdgJQgLACgFgGQgOgRACgLQADgNAVgHQgTgIAFgRIAFgJQASggAcAIQgDgPADgMQACgJAEgIIAGgJQAYgcAcAcQgDgIAJgMQAVgdAVAUQACAFAHAFQgHgFgCgFQgEgMARgPQAOgMAKgCQALgCAHALQADAFACAHIADAOQABgIADgIQAFgKAKgJQAIgIAMAEIALAEQAXALAAAYIgBAMIABgMQAEgTATgMIAAAAQAKgGAJABQAeAEgEAaIgCAFIADgFQAIgNARAIQAJADAFAFQAMAJgEANQgDABAAAIQAAgIADgBQADAAAFADQAfAUgPAnQAFgLATADQAXAFgSAeQAEgEAKgCQAUgEgFARQgIAcAMAKIAIAJQAZAfgeAhQAHAAAFADQAhAVgiAXQAKAYgOAQQANAegVAPQAKAdgkAHQgKAUgRABQgIgEgHgFQgCgPAEgQQAIgegJgYQgBgagOgTQAJgBAEgJQAGgLgBgKQgBgIgEgHQgVgkgLAbIAAgHIgMgBQgxgIAZghQgHADgJACQg4AKgqgeQgcAZgpgQQgPAdgjgNIAAAAIAAgBIADgLIgDALIAAABIAAAAQgGASgTAEQATAQgZAbQAiAFgQAuQAXAQgCAmQgBAiAWAYQAWAYAgAFIAKACIgfAvgAkJqoQgFgDgCgEQACAEAFADgAgXrOIABgFIgBAFgAjanIQgWgLAPgbIACgDIAAAAQATAEgEAfQgBAFgCAEIgHgDgAhznhQgEgEgCgGQgHgVAGgJQAaACABAhQAAAGgCAEIgBAAQgKAAgHgFg");
	this.shape_2.setTransform(315.3,77.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CC9A67").s().p("AFbQrQgogDgSgiQgTghgYgXQgXgXgfgaQgggbACgbIAAAAIAAgBIAAgBIAAAAIAAgBIAAgBIABgBIAAgBIABgWQADgjAFgnQAFgngMglQgMglgUgiQgUgggNglIgZhHQgMglAJgnQAGgdAKgdIABgEIgBgEIgIgXIgahBIAsAIQAmAHAhgNQAjgNAcgVIAZgQIADA2QADAoAFAlQAFAmAKAjQALAjAEAmQAFAngGAnIgLBKQgFAlACAnQACAnAFAlIABAIQAAAGADAGIAEAJQANAZAPAXQAUAdAfAHQAgAIAVAZIAAAAQgEgCgDAAIgBAAIAAAAIgDAAIgCAAIACAAIADAAIAAAAIABAAQADAAAEACIAAAAIAAABQAcATgdAWIAAAAQAAgTgagGQAaAGAAATIAAAAQAAAKgHAOIgCABIgFADIgBAAIAAAAIAAAAIAAgBQADgHAAgGQAAgIgGgFIgBAAIAAgBIgBAAQgKgHgOgBIgBAAIAAAAIgCAAIgBAAIABAAIACAAIAAAAIABAAQAOABAKAHIABAAIAAABIABAAQAGAFAAAIQAAAGgDAHIAAABIAAAAIgBABQgMAfgRgMQgHgjgjgPIgBgBQgHgCgFAAIAAAAIgBAAQgIAAgDAHIAAAAIAAAAIAAAAIAAAAQADgHAIAAIABAAIAAAAQAFAAAHACIABABQAjAPAHAjIAAABQAIAtgoAAIgFAAgAoKPeIAKgXIABgBQAKgXAVAAIAAAAIABAAQAJAAALAEIABAAIAAAAIAAAAIABABIAEABIgEgBIgBgBIAAAAIAAAAIgBAAQgLgEgJAAIgBAAIAAAAQgVAAgKAXIgBABIgKAXQgUAAAEgJIABgHIACgFQAKghAkgBIABAAIABAAIgBAAIgBAAQgkABgKAhQgNgBAAgJQgLgZAkgLIgBgHQAVgCAaADQATACARgHQAcgMAegSQAcgRAGgkQACgMABgMQgFgWgJgSIgfg/QgRgigVgeQgTgdgJgiQgIgigLglQgLgkgQgdQgRgbgTgaQgTgaAKgqQAJgjAQgeQASgiASgbIAcgnIAIABQAnAFAkgLQAJgDAKAAQAagCAYAOQAfAUAbAWQALAKAGAOQgHAagQARQgaAcgdARQgWANgNARIAAACQAIANATAKQAiASACApQABAigKAmQgLAkgHAjQgHAmALAjIAVBIQALAiATAdQATAdAYASQALAPAHAPQALAZgMAXQgQAcgrAAQgpgBgjAGQgiAGgTAbQgSAagfAKQgWAIgYAAQgqAAgDgVgAlaMlIAAgJQAAgTgEgUQAEAUAAATIAAAJgAlfFhIAGgKIgGAKgADXi3QgKgGABgFQACgggJgdIgEgLIAKgEQAFgOAAgPQAAgMgDgOQgJgkgUgfQAUAfAJAkQADAOAAAMQAAAPgFAOIgKAEQgSAHgRAJQgZAOghAWQghAVglAIQghAIgogCQglgCglgGQgUgDgTgHQgcgJgggCIgBgGIAAAAQgGgWgZgJQgLgEAAgHQACgigIgaQgJgbgTgMQAJAEALABQAIACAKAAIAMgBIgMABQgKAAgIgCQgLgBgJgEIgMgGQgSgJgNgSQgXgcgPghIgBgDIgBgCIgBgDQgJgXAAgaIABgRIgBARQAAAaAJAXIABADIgFAFIgEAEIgHggQggiFBBhUIAagFIACgBQAggGASgZIAAAAIADgEIAfgvIABAAQASAEAMALQASAQAYAAIABAAIAAAAQALAAAMgDIACgBIAAAAIACAAQASgGAHgOQgHAOgSAGIgCAAIAAAAIgCABQgMADgLAAIAAAAIgBAAQgYAAgSgQQgMgLgSgEIgBAAIgKgCQgggFgWgYQgWgYABgiQACgmgXgQQAQgugigFQAZgbgTgQQATgEAGgSQAjAOAPgeQApAQAcgZQAqAeA4gKQAJgCAHgDQgZAhAzAIIAMABIAAAHQALgbAVAkQAEAIABAHQABAKgGALQgFAJgIABQAOATABAaQAJAYgIAeQgEAQACAPIABAHQAHACAHAAQAUAJAggCIAfgDIAFAAIAmgFIBIgIQAogEAkAMQAkAMAeAVQAbATAXAcQAPASAHAaQAiAAAgAKQAlAMAYAZQAaAbAFAmQAFAngIAnQgHAkgVAeQgXAfgiATQgiASgnAHQgmAGglAEQgUACgKgDQABAYgKAWIgRApQgEAKAAAIQAdgDAJAfQALAlgkAQIgbALQgGgXgUgMgAEDjbQgEgIAAgKIAAgDIgOADIAOgDIAAADQAAAKAEAIgAh2jkIABgBIAAAAQAOgKAQAAIAAAAIABAAQALAAANAFIAAAAIABABIAAAAIAAAAIAAAAIABAAIACABIgCgBIgBAAIAAAAIAAAAIAAAAIgBgBIAAAAQgNgFgLAAIgBAAIAAAAQgQAAgOAKIAAAAIgBABgAgmjoIABgCIAAgBQAHgZAWgBIABAAIAAAAQAIABAOAFIABAAIgBAAQgOgFgIgBIAAAAIgBAAQgWABgHAZIAAABIgBACgAiVj0QgVgkAAgeQAAgUAKgRQgKARAAAUQAAAeAVAkgAg7j5QgfgOgBgZQAAgKAFgLIgFgCIABgBIAAAAIABAAQAOgOAQAAIAAAAIABAAQAMAAANAIIAAAAIACABIAAAAIABABIgBgBIAAAAIgCgBIAAAAQgNgIgMAAIgBAAIAAAAQgQAAgOAOIgBAAIAAAAIgBABIAFACQgFALAAAKQABAZAfAOgABmk5QgCAbgJAXQAJgXACgbIAAgIQAAgigTgfIgmg/IAmA/QATAfAAAiIAAAIgAiVkcIAAgBIABgBQAGgUAVAAIAAAAIABAAQAKAAANAEQgNgEgKAAIgBAAIAAAAQgVAAgGAUIgBABIAAABgAhdk0IACgDQgXgLAAgaQAAgJADgLQgDALAAAJQAAAaAXALIgCADgAEdlZQAAgOgEgOQAEAOAAAOQgEgBgCgDQACADAEABgAjHmJQgMAKgLAMQALgMAMgKQARgOATgJQgTAJgRAOgADSooQgMAkgYAdQgQASgVAPIAoA8IABACIAAAAIADgCQAZgLACgSQAEgnAZgcQAYgcAggTIAWgMQgZgNgZgGQgegGgTgVQAAAWgGAVgAikn7QARBAArAoQgrgogRhAQgIgfAAgcQAAgdAJgbQgJAbAAAdQAAAcAIAfgAhTmuIAEgBQAkgHAqAAIAAAAIAAAAIAfABIgfgBIAAAAIAAAAQgqAAgkAHIgEABgAB2m5QgNAHgKADQAKgDANgHIATgNIgCgFIACAFIgTANgAE7olQAWgMAYgKQgYAKgWAMgADYpTIgEgCIAAAAQghgOggAAIAAAAIAAAAIgOAAIAOAAIAAAAIAAAAQAgAAAhAOIAAAAIAEACgAixqmQgWgFgUgMQAUAMAWAFgAh9qpQA4gOAggwQggAwg4AOgAgSsMQAFAIAIAHQgIgHgFgIQgMgOgDgQQADAQAMAOgAidtrQghAQghAKQAOATAdAHQAPADALgIQAWgRAJggQAEgPAJgLIAAAAIAGADIgGgDIAAAAQgPgJgKgRQALAmghAQgAkGtpQAHAAAKgEQAMgEAKgIQgKAIgMAEQgKAEgHAAIAAAAIgBAAQgRAAAAgWIAAgBIAAgBQABgiAqAAIAAAAIAAAAIACAAIACAAIgCAAIgCAAIAAAAIAAAAQgqAAgBAiIAAABIAAABQAAAWARAAIABAAIAAAAgAgzuzIADAAIAAAAIAAAAIgDAAIAAAAIgBAAIgHgBIAAgBIAAABIAHABIABAAIAAAAgAkzvmIAAAAIgCAEQgQAaAXALIAHADIAFABQAVAGAMgJIACgCQABgngfgIIgHgBQgKAAgFAIgAjHwDQgFABgCAEQgHAJAIAVQACAHAEADQAHAGALAAQAHAAAKgDQAdgJgTgcQgIgNgLACQgJgCgHAAIgKACgAhHvdIAEgNIgEANgAkjljIAAAAgAl2nGIAAAAg");
	this.shape_3.setTransform(323.7,127.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(10));

	// fist
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(0.1,1,1).p("AgvkXQgEgMgKgIQgQgMgQADQgNADgKANQgBACgCACQgKARAFARQAGAQALAOQAEAFAFAEQAJAHAMABQAIAAAHgFQAPgLAHgSQAAAAAAAAIAAgBQgFgFgDgGQgEgIACgJQAAAAAAgBQABgEACgEgAh0kkQgJgJgNACQgQADgKATQgIAOACANQAAACAAACQABADABACQAFAPANAPQANANAOgCQACgBABAAQAOgEAIgKAiqj6QgJgFgKAIQgQAMAEASQADAPALAPQAEAGAGAFQgDAOAHANQAHAOAJAPQAJAPAHAOQADAGgCAHQAAACgBACQgGAPgJAPQgKARgJAQQgKAPgKARQgJAQgJAQQgJARgDASQgEATgCATQgBASgBATQgBASADASQADARAFARQAFASADAQQABARARAMQAQAMAQgCQARgBAPABQARACATAAQASABAPAAQATABARgCQAQgBAPgEQARgEAPgEQAOgEAPgJQABgBBdgeAixiwQAIAGAMAEQAQAGAKgRQAHgMABgLAANjxQAAgMACgOQACgUgPgKQgOgKgRAJQgMAGgGANAgOjkQgEABgDABQgLAEgIAEQgRALALAPQAEAHAIADQASAIAPgFQAHgDAGgGAgojyIAAABQAHAGAKAEQAEACAFABAAFjpQAAAAABgBQAEgDADgEAAOjpQgEAAgEAAQgBAAAAAAQgFAAgIADQgDABgDABAAOjpQAAgEgBgEAAOjpQAGABAGACQARAHAJAQQAIAPgFAUQgFAOgKAGQgQAKgFAQQgFARgOANQgNAMgOAOQgCATgCASQgDATgCAOQgCAUgFASQgGARgEASQgEATgGARQgGATgLAOQAAABAAAAQAAAAAAgBQAHgEAGgFQABgBACgBQAEgFAGgHQALgNATgIQAQgHAPgFQASgGAUgBQARgBARgCQgDAHgCAHADqAAQgCAAgCAAQg/AJgHABQgGACgJAGQgKAFgOAKQgPALgNANQgJAJgFAKAhQCPQgDAEgCADABQCpQgPALgSAIQgQAGgNAC");
	this.shape_4.setTransform(270.5,56.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#CC9A67").s().p("Ag+E1IghgBIgkgCQgPgBgRABQgQACgQgMQgRgMgBgRQgCgQgGgSIgIgiQgDgSABgSIACglQACgTAEgTQADgSAJgRIASggIAUggIATghQAJgPAGgPIABgEQACgHgDgGIgQgdIgQgdQgHgNADgOQgGgFgEgGQgLgPgDgPQgEgSAQgMQAKgIAJAFIAAAEIACAFQAFAPANAPIACACQAJAJALAAIAAAAIAAAAIAEAAIABAAIADgBQAOgEAIgKQgFgEgEgFQgLgOgGgQQgCgGAAgFQAAgMAHgLIADgEQAKgNANgDQAQgDAQAMQAKAIAEAMQAGgNAMgGQARgJAOAKQAPAKgCAUQgCAOAAAMIABAIQAGABAGACQARAHAJAQQAIAPgFAUQgFAOgKAGQgQAKgFAQQgFARgPANQgMAMgOAOIgEAlIgFAhQgCAUgFASIgKAjIgKAkQgGATgLAOIAAABIAAgBIANgJIADgCIAKgMQALgNATgIQAQgHAPgFQASgGAUgBIAigDQgDAHgCAHQACgHADgHQAFgKAJgJQANgNAPgLQAOgKAKgFQAJgGAGgCQAHgBA/gJIhID7IheAfQgPAJgOAEIggAIQgPAEgQABIggABIgEAAgAAxC8QgQAGgNACQANgCAQgGQASgIAPgLQgPALgSAIgAhTCWIAFgHIgFAHgAiTikQALAAAHgNQAHgMABgLQgBALgHAMQgHANgLAAIAAAAIAAAAIgIgCQgMgEgIgGQAIAGAMAEIAIACIAAAAIAAAAgAgLixQAGAAAFgCQAIgDAGgGQgGAGgIADQgFACgGAAIAAAAIgBAAQgJAAgLgFQgIgDgEgHQgEgGAAgFQAAgIAKgHQAIgEALgEIAHgCIgHACQgLAEgIAEQgKAHAAAIQAAAFAEAGQAEAHAIADQALAFAJAAIABAAIAAAAgAhJjPQAGAAAFgDIABgBIABgBQAPgLAHgSIAAAAIAAgBIAAABQAHAGAKAEIAJADIgJgDQgKgEgHgGIAAgBQgFgFgDgGQgCgFAAgGIAAgGIAAgBIADgIIgDAIIAAABIAAAGQAAAGACAFQADAGAFAFIAAABIAAAAQgHASgPALIgBABIgBABQgFADgGAAIgBAAIAAAAIAAAAIgBAAQgMgBgJgHQAJAHAMABIABAAIAAAAIAAAAIABAAgAgGjmIgGACIAGgCQAGgDAHAAQgHAAgGADgAAQjpIgBAAIgDAAIgCAAIgBAAIAAAAIgBAAIAAAAIAAAAIABAAIAAAAIABAAIACAAIADAAIABAAgAAIjpIAAgBQAEgDADgEQgDAEgEADIgBABIAAAAIABAAgAh+jIQgLAAgJgJIgCgCQgNgPgFgPIgCgFIAAgEQgCgNAIgOQAKgTAQgDQANgCAJAJIgDAEQgHALAAAMQAAAFACAGQAGAQALAOQAEAFAFAEQgIAKgOAEIgDABIgBAAIgEAAIAAAAIAAAAgAhgjXIAAAAgAgmjyIAAAAg");
	this.shape_5.setTransform(270.3,56.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(0.1,1,1).p("AmKj2QgRgDgQgBQgfgCghgbQgWgTAegDQAhgEAoAIQAkAHAjAJQAlAKAgAXQAfAWAXAdQAWAdAgATQAiAVAfAXQAeAXAfAXQAeAXAXAdQAXAaAVAdQAaAiAwgKQAvgLAcAFQAcAFAfAAQAdABAggCQACAAACgBQAkADAbgBQAcgBAjAMQAVAHAUAHADlDEQAkAHAdgTAFfEpQgfAGgdAAQgkABgkgKQgkgKghgUQghgUgkgGQgigGgjgXQgegUgfgWQgfgVgSgfQgSgfgTgiQgSgigUgbQgUgegegVQgfgVgigNIgBAAIABAAQAMgHAKgLAmKj2QAJABAJACQANADAOAFQgFAHgFAJQgKAXAGATQAEAMAKALQADACACACQAPAOAJgIQAIgHADgWQACgLADgLAmOiHQAFACAFABQAOAEALgHQAKgHAJgIAlAiQQARANgLASQgDAGgFAGQgLAKgPACQgBAAgBAAQgJABgKgBQgrgHAOgnQgkgMAbgaQgHgDgIgFQgIgFABgJQABgjAigQAlrixQgUANgWgIQgBgBgBAAAkhhgQgdATgegMAldjrQATgXAdAPQAmAUAPAd");
	this.shape_6.setTransform(252.8,48.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#CC9A67").s().p("ADbEmQgkgKghgUQghgUgkgGQgigGgjgXQgegUgfgWQgfgVgSgfIglhBQgSgigUgbQgUgegegVQgfgVgigNIAAAAIgBAAQgdATgegMQAPgCALgKIAIgMQAEgHAAgHQAAgJgKgIQAIgHADgWQACgLADgLQgDALgCALQgDAWgIAHQAKAIAAAJQAAAHgEAHIgIAMQgLAKgPACIgCAAQgJABgKgBQgrgHAOgnQgkgMAbgaIACABIABAAQAIADAHAAIABAAIAAAAQAMAAAMgIIAAAAIABAAQAEAMAKALIAFAEIAAABIACABIAAAAQAIAHAGAAIABAAIAAAAQAEAAADgDQgDADgEAAIAAAAIgBAAQgGAAgIgHIAAAAIgCgBIAAgBIgFgEQgKgLgEgMQgCgHgBgIQAAgNAHgOQAFgJAFgHQgOgFgNgDIgSgDQgRgDgQgBQgfgCghgbQgWgTAegDQAhgEAoAIQAkAHAjAJQAlAKAgAXQAfAWAXAdQAWAdAgATQAiAVAfAXIA9AuQAeAXAXAdQAXAaAVAdQAaAiAwgKQAvgLAcAFQAcAFAfAAQAdABAggCIAEgBQAkADAbgBQAcgBAjAMIApAOQhjAngoCDIgLAfQgfAGgdAAIgDAAQgjAAgigJgAD4DGQAYAAAVgNIABgBIgBABQgVANgYAAIgBAAIAAAAIgQgBIgCgBIACABIAQABIAAAAIABAAgAkghgQAMgHAKgLQgKALgMAHgAl7iDQAIAAAIgEQAKgHAJgIQgJAIgKAHQgIAEgIAAIAAAAIAAAAIgHAAIAAAAIgBAAIgBgBIgKgDIAKADIABABIABAAIAAAAIAHAAIAAAAIAAAAgAktjzQAmAUAPAdQgPgdgmgUIAAAAIgCgBIAAAAQgKgFgJAAIAAAAIAAAAQgQAAgLAOQALgOAQAAIAAAAIAAAAQAJAAAKAFIAAAAIACABIAAAAgAmFipQgHAAgIgDIgBAAIgCgBQgHgDgIgFQgIgFABgJQABgjAigQIASADQANADAOAFQgFAHgFAJQgHAOAAANQABAIACAHIgBAAIAAAAQgMAIgMAAIAAAAIgBAAgAlrixIAAAAg");
	this.shape_7.setTransform(252.8,48.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4}]}).to({state:[{t:this.shape_7},{t:this.shape_6}]},5).wait(5));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(246,0.4,134.1,235.2);


(lib.anim_slim_playsguitar = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// guitar
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.1,1,1).p("AE0lSQgCgHADgGQAEgIAKgBQALgBAGAFAFHlWQACgDAEgCQADgCADgDQABgCAAgCQABgEgFgDQgIgFgJAFQgIAEgGAGQgEAEADAGQABAEADABAEblNQACgEgDgCQgHgGgKAGQgFACgDADQgGAFgCAKQgBAFADACQACAAAEgBQgDgHAGgHQAFgHAKAAQAHAAABABQACACgFAEQgEADgCAEQgBgEgGABQgCAFAEAEQgHAAgFABAEVkbQAHgGAJgEQABgBACgBQAFgCAFgCQAJgEAIgEQADgCADgCQAOgIAQgJQAOgIATgFQAFgBAGgBAESlAQACADACACQAVgMAYgJQgDgDgBgCQgCAAgCACQgBAAgBACQgDAAgCgBAENk6QABACACABQADgCADgCAFKlTQgCgBgBgCQgCgEgCgFQgGAEACAGAEykrQAAAIACAHAFDlQQADgCAEgBAFDkzQgBAJAGAKAGOl0QgBgDgDgDQgFgDgFABQgLAAgGAFQgGAEgBAMQADABADABQgEgKAHgFQAFgEAKABQAIABAGACgAGClpQAEACAEgCQACAAABgBQADgGgCgEAF6lpQABgJAGAHQAAABABABAF9lhQADgBADgBQAAgBAAgBQgBgCAAgCAF6lpQABAEACAEQgbAFgYAJAFullQAFACAHgBQAAgDAAgCAGHkZQAAgBAAgBQAAgGAEgCQAKgGAGAFQAEAAABABQAAgDAAgEQgHAAgGABQgFAAgFABQgDACgBAEQgBAFACADQAAAAABABgAGgkjQABABgDADQgHAGgJABQgCABgBAAQgDAAgBgCAGDljQAbgFAegCIgMBAQgIAAgIAAAEQk3QgUAMgSAPIAeAiIgMAKQACABABACQABABABACQADAEABAGQAAABAAABQAAACAAABQAAABAAABQgBAKgLAFQgDACgDABQgBAAAAAAIAAAAQAAAAABAAQAGAAAHAAIAQgPQACADAHAEQAEACAFADAFmkEQADgBAEgBQAKgGgFgJQgCgCgCgBQgDAAgCABQgFAAgDADIAAAAQgDAMAIAEgAFhkUIAAAAAFhkUIAAAAAFjkDQABAAACgBAFckZIAAABQAAADADACQgBABgBABQAAAAgBABQgHAGAEAHQAFAAAFAAQgGgFgBgIAFckZQAAAAAAAAQAVgLAYgEAFJjiQAPgDgMgPQgOgCgMAAQATgWAXgNAFJjiQgEAAgEAAQgUgBgRACIgBAAQgGgDgEgCQgBgBAAAAQgBgBgBgBQgFgFACgFQABgCABgBQACgEAGgDQAAgBABAAQAAABAAAAQAAABABAAQADAEAFACQABAAABAAQABAAABAAIAAAAQAHAAAIAAAD+iqQABAAACAAQANABANABQAGAAAHAAQAUACAKgLQACgCgBgIQgBgBAAAAADriTQAGAQAVABQATABAHgJQAIgLgIgOQgCgEgDgBAEAjHQALgBAXgCQAMAGALAFQAGACAGABQAAAAABAAQAJABAIgFQAEgCAAgHQgCgSgQgHAEQjWQgFgHAQgEAFfkTQABgBABAAQgCgDgDgCAD8jwQgEgDgEgDQgEAEgCACQgJAMgSAGQgRAFgUgCQgGgBgBAEQgGAQAKAVIAXgRQADABAFABQACAAADAAQADAAADAAQAGAAAGgBQADAAADgBQADAAACgBQADgBADgBQgBAFACAHIAAAAQgLAOAWADADriTQAAgCgBgCQgFgVAZACADKiVQANAEAUgCADzi7IgpAmIjEC1QgFAUARALQASALAOgSQABAOABAUQACAUgKAAQgCAEgEADQgBABgBABQgGACgGADQgQACgJAIQgDACgCACQgKAJgLAKQgSAFgJANQgEAGgEAIQgJAPgEAPQAAABAAABQABAVgIAOQgIAPgKANQgKAOgMAKQgIAIgKAIQgNALgMAIQgOAJgPALQgOAKgUAFQgQADgUAAQgUAAgTAAQgUgBgMgLQgKgIgKgFQAKADALACQASAEASAAQATAAAUgCQATgCAQgIQARgIARgJQAKgFAIgHQANgLAPgJQAPgJAmg/QAFgaABgNQAGgIACgKQACgLAQgIQARgIANgEQAMgEAQgGAENkUQADgEAFgDAEUkLQgDgKAEgGAEkkWQgBgIACgHAljFkQgEgBgEgBQgEgBgDgBQgPgFgNgKQgPgNgJgRQgJgQgGgSQgGgSABgUQAAgQACgQQABgDABgJQABgJAQgSQAPgSAngbQAngbARgGQAEgCABgBQAFABAGABQASACAXgHQAWgHAPgMQAPgNAHgQQAFgMAGgLQAJgMANgNQAMgNAQgHQAPgHAWgDQAFAIAJAEQgIAUAMANQAFAEADABAlDDGQATgEAOABIHsmFAlGDgIgUgXIAQgMIAHAJIAMAOgAkQDHQgHgDgLgBIgVARIAJAMIAJALIgNALIgKgKIgKgMAkGDRQgDgGgHgEIgeAZIgOAMAhhguQgJANgFARQgFANALAHQAIAHAMgCQAIgCAGgDQAGgCAEgCIDoizAkmEEIAMgLIgLgOIAfgaAkeEOIgIgKIgMgOAkMD+IgGAFIACADAkMD+QgCADgCAFIAIAKIABAAIgLAKIgMgMAkEDmQgCALgGANIH4nDAkSEDIgMALAkaD5IAIAKAkEDmIgWATADhjDInnGUQAEAIgCANIHrmqADPjCInfGJ");
	this.shape.setTransform(76.2,77.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("Ah8DVQgUAAgMgLQgJgJgLgEIAWAFQARAEASAAQAUAAATgCQAUgCAQgIIAhgRQAKgGAHgGQANgLAPgJQAPgJAlg/IAHgnQAGgIACgLQABgIARgIQAQgJAOgEIAcgJIgFADIgVATQgSAGgJAKIgJAPQgIAPgEAPIgBACQABAVgIAOQgIAPgKANQgJANgMALIgSAQQgNALgNAIIgaATQgPALgTAFQgRADgUAAIgngBgABJihQgLgJAEgOQAFgQAJgNQAGAHAIAFQgHAUALANQAGAGADABQgGADgIACIgGAAQgIAAgGgFg");
	this.shape_1.setTransform(58.2,94.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CCCCCC").s().p("AkyE4IAMgKIgMAKIgIgJIgMgOIANgLIgNALIgKgLIAOgLIgOALIgKgLIAPgMIAJAMIAJALIALAOIgMALIAMgLIAIAKIACACIAIALIABAAIgLAKgAluD0IAQgMIAHAJIAMAOIgPAMgAlLD/gAD5kPQgEgFACgFQAGAAABADIAEAGIgGAEIgDgDgAErkrQgCgFAGgFIAEAKIADADIgHACIgEgFgAFmk/QABgJAGAIIABACIABADIAAADIgGABQgCgDgBgFg");
	this.shape_2.setTransform(78.2,73.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AAJA5QgEgGAHgHIABgBIABgBQgDgCAAgEIABAAIAEAEIgCACIACgCIABAAQgEAMAJAFIgEABQgFgFgBgJQABAJAFAFIgDAAIgGgBgAASA6IAAAAgAA1AaQAAgEADgBIAKgCIAOAAIAAAHQgBgBgEAAQgHgFgKAFQgEADAAAFIgBABQgBgCABgGgAhLgJQAGgHAKAAQAGAAACACQACACgFAEQgEADgCADQgBgDgGAAQgCAFADADIgMAAQgDgFAGgHgAgagTQgCgIADgGQADgIAKgBQALgBAFAFIgCAFIgEAFQgDACgCADIgFgKQgFAFACAFIgEACIgCACIgCAAIgDAAgAAdgmQgDgLAGgEQAGgEAJAAQAIABAHADQABAEgDAFQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAQgDACgFgBIgBgCQgGgIgBAJIAAAFIgFABIgHgBg");
	this.shape_3.setTransform(109.8,46);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#999999").s().p("AlAE/IAGgGIgEAJgAlIE1IgLgOIAfgaQAEAIgCANIgWATIAWgTQgCAKgGANIgGAGgAk6E5IAAAAgAlcEcIAegZQAHAEADAGIgfAagAlcEcIgKgMIAWgRQALAAAHAEIgeAZgAlmEQIgLgOQATgEAOABIgWARgAEzjYIAAgBIAIgDIAEAAQADABABACQAFAJgKAGIgGACQgJgEAEgMgAFZjdIgBgCQAAgGAEgCQAKgGAHAFQAEAAABABQAAAAAAABQAAAAAAAAQgBABAAABQgBAAgBABQgHAGgJABIgCAAIgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAgADLkDQABgKAHgFQADgDAFgCQAKgGAGAGQADACgBAEQgCgCgGABQgKAAgGAHQgFAHACAGIgGACQgCgCABgFgAEBkbQgDgGAFgEQAGgGAIgEQAIgFAIAFQAFACAAAFQgHgFgLABQgKABgDAIQgDAGACAHQgDgBgCgEgAE6krQABgMAFgEQAHgFAKAAQAGgBAEADQAEADABADQgHgCgIgBQgJgBgGAEQgGAFADAKIgFgCg");
	this.shape_4.setTransform(80.8,71.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFF00").s().p("AlOFoIgVgFIgIgCIgHgCQgPgFgNgKQgPgNgJgRQgJgQgGgSQgGgSABgUQAAgQACgQIACgMQABgJAQgSQAPgSAngbQAngbARgGIAFgDIALACQASACAXgHQAWgHAPgMQAPgNAHgQQAFgMAGgLQAJgMANgNQAMgNAQgHQAPgHAWgDQgJANgFARQgFANALAHQAIAHAMgCQAIgCAGgDQAGgCAEgCIDoizIAXgSIAIACInsGGQgOgBgTAEIgHgJIgQAMIAUAXIAKALIAKALIAMAOIAIAJIAMANIALgKIgBAAIgIgKIAEgJQAGgNACgKIHrmqInrGqQACgNgEgIIHnmUIAGgBIAFgBIAGgCQgBAEACAHIgpAmIjEC2QgFAUARALQASALAOgSIACAiQACAUgKAAQgCADgEAEIgCABIgMAFQgQADgJAIIgcAJQgNAFgRAIQgQAIgCALQgCAKgGAIIgGAnQgmA/gPAJQgPAJgNALQgIAHgKAFIgiARQgQAIgTACQgUACgTAAQgSAAgSgEgAkMD8IH4nCgAkQDGIHfmJIAGAAIAMgBInnGUQgDgGgHgEgAkiDCIHsmGIAFABInfGJQgHgDgLgBgADPjDIAAAAgADzjIIAGgDQALgFABgKIAAgCIAAgDIAAgDQgBgFgDgFIgCgCIgDgEIAMgJIgegiQASgPAUgMIAGgEQAVgMAYgJIAHgDQAYgJAbgFIAGgCQAbgFAegCIgMBAIgQAAIgNABIgKABQgYAEgVALIAAAAQgXANgTAWIgPAAIAAAAIgCAAIgCAAQgFgCgDgEIgBgBIAAgBIgBABQgGADgCAEIgCADQgCAFAFAFIACACIABABIAKAFQgQAEAFAHIgQAPIgKAAIgDAAgAEUkMIgBgIQAAgFACgDQgCADAAAFIABAIgAEokoIgDACQgJAEgHAGIgIAHIAIgHQAHgGAJgEIADgCIAKgEIgKAEgAEkkXIgBgFQAAgFACgFQgCAFAAAFIABAFgAE0kdQgCgHAAgHIAAgBIARgIIAGgEIAegRQAOgIATgFIALgCIgLACQgTAFgOAIIgeARIgGAEIgRAIIAAABQAAAHACAHgAFIkhQgFgIAAgIIAAgDIAAADQAAAIAFAIgAEVj+IABgBIAAABIABABg");
	this.shape_5.setTransform(76.2,77.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFCC99").s().p("AAGA9QgTgBgGgPIgBgFIAAgBQgEgSAUAAIAAAAIAAAAIADAAIABAAIABAAIAaACIgagCIgBAAQgPgCAAgGQAAgEAEgFIAAAAQgCgFABgEIgGABIgFACIgGABIgMABIgGgBIgFAAIgIgCIgXAQQgKgUAGgQQABgDAGAAQAUACARgFQASgGAJgLIAGgGIAIAFIACAEIABACQADAEABAGIAAADIAAACIAAADQgBAKgJAFIgGACIgBAAIAAABIABgBIALAAIAigDIAXAJQAGADAGAAIABABIABAAQABAJgCACQgKAKgUgBIgNgBQADACACADQAIAOgIALQgGAIgRAAIgDAAgAg0AqIApgmIAAAAQgEAFAAAEQAAAGAPACIgBAAIgDAAIAAAAIAAAAQgUAAAEASIAAABIABAFIgLAAQgNAAgJgDgAAAAVIAAAAgABGAEIgBgBQgGAAgGgDIgXgJIgJgFQgHgEgCgDQgFgGAQgFIgKgFIgBgBIgCgBQgFgFACgGIACgDQACgDAGgEIACABQADAFAFABIACAAIACAAIAAAAIAPAAIAaADQAMAPgPACIgFAAIgBAAIAAAAIgBAAIgBAAQgUAAgRABIgBAAIABAAQARgBAUAAIABAAIABAAIAAAAIABAAIAFAAQAQAHACATQAAAGgEABQgHAEgHAAIgDAAgAAQgVQACADAHAEIAJAFIgiADgAAigJIAAAAg");
	this.shape_6.setTransform(101.8,58.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(19));

	// main
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#000000").ss(0.1,1,1).p("AhJgdQABgDABgCQACgOgEgJQgDgIgIgFQgGgMgDgNQgKgjgFgmQgGgkgageQgHgRgEgPQgDgJgDgJQAjARAgARQAgASAjAJQAjAKAoAAQAkAAAoAAQAngBAngDQAkgCAhgRQAdgKAYgUQANgPACgUQAGghggAGQgLALgWAGQgeAKgoADQgnADglAHQgkAHgogCQgngCgfgPQgegOgmgGQgkgFgdgTQgcgSgcgXQgJgIgOgCQgQgDgIALQgKAPgOACQAGALAFAIAnEoQQANAQAIAPAnFogQATAPAKAQQACADgBAFAnFogQgBABAAACQgGAIgGAIQAKASALANQAHAJAMACQgBAFABAFQABATAPAOQAOANARgNQADgBgBgFQAKAUAHARQAJAVgQAKQgFADgIgBQgCAAgDgBQAGAEAFAFAmqnjQABgIAGgEQARgKASANQAGgKgHgKQgKgPgJgRQACgCABgDQAEgHADgGQADgHADgGQAEgLAKgKQADgDAEgCQADgDAEgCQgBgWgSgLAlTpeQAEgRgIgSQgIgSgQgJQgNALgJARQgJAPgJAOQgMASgMASQgLAQgLAPAkMorQgBgDgBgEQgFgWgZAEQgGgEgHgEQgNgHgNgLQgFgCgFAAQgGAAgFACAldpgQACgZgNgMQgEgDgEgBAmEo/QAAgRgJgLAk6pGQgMAEACAOAl2pUQgDgQgHgIAlYoBQgFAGgDAGQgEAIAAAKAmvomQAPALAKARQAEAIADAGAmRnTQACALALACAmQneQgBAHAAAEQAEAEAHgBAlgn1QAIARAVAFQASAFASgDQATgCAOgMQAJgHgEgMAkcmeQATgBARgDQASgDAIgOQAJgRABgUQAAgUgIgSQgHgRgMgMQgNgNgQgDQACARgMAKAkspEQgMAGADAWAlXonQgXgJABAXAmRolQgJgKgKgFAmKoyQgDgKgNgCAkcmeQgBAAgBAAQgVAAgPgFQgHgDgGgEAkMlyQgCgEgCgFQgJgQgDgTAmBl5QgMgCgKgGQgNgCgPADQgCABgBAAQgQAGgCARQgDAoACAmQABAoAFAmQAFAmgBAoQAAAoAFAkQAGAqAZASQAIAGAJAFAlwitQABgZACgYQACgpgRghAlsgzQgDgGAAgJQgCgmABgoQAAgPAAgOQAHAMAIAMQAVAeARAdQAOAWALASQACAlAMAZQACAEACACQAJAMAUgCQAmgEAngDQAngDAZgPQAXgLAGgVAkQASQgIAWgNAPQgLgGgCgBQgJAngrASQgdAMgfALQggAMAIAZQAIgCAIAAQAYgBAYAMQAfAOASAeQAGAKABAFQANgZAggRQAigTAdgWQAigYARgWQAUgZAaAnQAWAgARAZQAUAdAWAfQAIAMAEAPQAKgYARgWQAEgFAEgEQAYgaAmgFQASgDASgDIAOAVQAIgMALgNQgZgegggSQgdgQgfgXQgcgWgWgfQgXgegZgZABtCqQARgCAQgCAAiD4QAKAJALAIQAOAKAOAHQAAABAAABQAGBBBaA+QBcA/AVBhIgUAmQAHAWAbgJQBEgPAcAPIAAAAQAhAjA7gOQADgBAEgBQADAHAFABQAWAFgCgZQgBgCgBgCQAIAAAAgGQAAgFgCgCQABgCAAgDQgBgCgCgBQACgBAAgBQAEgGgHgEQgFgCgFAAQAFgIgKABQgJABgGAFQgBABAAABQhOgMhCgrQgCgBgBgCIjllWAAiD4QgRgPgOgRAlwKNQAbAMAwgcQgEgGA/gQQAqAIAbAAQAbAAAHgaQgFgNgTgRQgUgRgYgVQgYgWgVgdQgXgfgMgeQgMgegYgXQgZgYgdgUQghgWgigOQAqgNAigPQAOgHAIgKQAHgJACgMAgYEGQAggDAagLAlSDvQAJACAEgCQADgBAAgFAmzCtQAFgFAEgFAm6ClQAFAEACAEQgSATgRASQgYAWgUAZQgVAWABAPQAbAbAjAZQAkAZARANQASAOAhAZQAgAZAeAlQAdAlAHAIIhCBHQhCAMgggQQgHgCgIgCQgKgEgEAJQgDAGAEACQABABADACQADgDAIgCAlwKNQAEgBgBgEAmjKIQABAFADAFQAFALAPAAQAXABAEgRAnCJyQABgLARAAAnKJhQgFAFANAMIAAAAQAAADACAFQABAFAMABQAAgCAAgDQADgSAVgCAmzKAQABALAPgDQgCgNAKgIQAQgOAOAPAIBJRQADgCAEgBAITJcQgFgGgJAGAIPJxQAAgCgCgBQgOgOgNARAIVJkQgDgCgHAB");
	this.shape_7.setTransform(61.1,91.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#996600").s().p("AgqBRQgLgNgKgSIAMgQIACgDQASAPAKAQQACACAAAEIgBACIABgCQAAgEgCgCQgKgQgSgPIAVgfIAYgiIAQgdQAJgRANgLQAQAJAIASQAIASgEARQgFgCgFAAIAAgIQAAgTgLgKQgEgDgEgBQAEABAEADQALAKAAATIAAAIQgGAAgFACQgBgWgSgLQASALABAWIgHAFIgHAFQgCgQgIgIQAIAIACAQQgKAKgEAJQAAgPgJgLQAJALAAAPIgGANQgDgKgLgCQALACADAKIgHANQgGgKgLgFQALAFAGAKIgBAFQAHARAKAPQAHAKgGAKQgRgNgQAKQgGAEgBAIQgLgCgIgJgAgcBOQgIgPgNgQQANAQAIAPgAgDA1IAFAOIgFgOQgKgRgPgLQAPALAKARgAgxAfIAAAAg");
	this.shape_8.setTransform(20.8,34);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00FF00").s().p("ABxB3Igqg8Igng5QgaglgSAZQgRAUgiAYQgdAWgiATQggARgNAZQgBgFgGgKQAGAKABAFQABAFgEABQgEACgJgCQAHgJACgMQgSgegfgOQgXgMgZABIgIAKIgIgIIAQgCIgQACQgIgZAggMQAfgLAdgKQArgSAJgnIANAHQANgPAIgVQAJALAUgCIBNgHQAlgDAZgPQAYgNAGgVQAYAZAXAgQAWAfAeAWQAfAXAdAOQAgASAZAeIghAFIgkAFQgmAFgYAaIgIAJQAPARAQAPQgaALgiADQAKgYATgWQgTAWgKAYQgEgPgIgMgAEEA3IAhgFQgLANgIAMgAElAyIAAAAg");
	this.shape_9.setTransform(46,103.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFCC99").s().p("AmLJ/QgPAAgFgLIgEgKIAAgFQAAgKAIgGQAHgHAHAAIAAAAIAAAAQAIAAAHAHIABABIAAAAIAAAAIgBgBQgHgHgIAAIAAAAIAAAAQgHAAgHAHQgIAGAAAKIAAAFQgPADgBgLIAAgBIAAgEQADgSAVgCQgVACgDASIAAAEIAAABQgMgBgBgFQgCgFAAgDIAAAAQgNgMAFgFQADgDAIgCQgIACgDADIgEgDQgEgCADgGQAEgJAKAEIAPAEQAgAQBCgMIBChHIgkgtQgeglgggZIgzgnIg1gmQgjgZgbgbQgBgPAVgWQAUgZAYgWIAjglIAJgKQAYgBAYAMQAfAOASAeQgCAMgHAJQgIAKgOAHQgiAPgqANQAiAOAhAWQAdAUAZAYQAYAXAMAeQAMAeAXAfQAVAdAYAWIAsAmQATAQAFAOQgHAagbAAQgbAAgqgIQg/AQAEAGQgwAcgbgMQADgBAAgDIAAgBIAAABQAAADgDABQgEAQgVAAIgCAAgAnCJUQABgLARAAQgRAAgBALgAH9JrQgFgBgDgHIgHACQg7AOghgjIAAAAQgcgPhEAPQgbAJgHgWIAUgmQgVhhhcg/Qhag+gGhBIAAgCQgOgHgOgKIgVgRQgRgPgOgRIAIgJQAYgaAmgFIAkgGIAOAVIDlFWIADADQBCArBOAMIABgCQAGgFAJgBQAKgBgFAIQgEABgDACQADgCAEgBQAFAAAFACQAHAEgEAGIgCACQgFgGgJAGQAJgGAFAGQAAAAABAAQAAABABAAQAAABAAAAQAAABABAAQAAABAAABQAAAAgBABQAAAAAAABQAAAAAAABQACACAAAFQAAAGgIAAIgCgDIAAAAIgBAAQgFgGgGAAIgBAAIAAAAQgHAAgGAIIAAAAIAAAAIgBABIABgBIAAAAIAAAAQAGgIAHAAIAAAAIABAAQAGAAAFAGIABAAIAAAAIACADIACAEQACAVgQAAIgGgBgAIVJGQgBgBAAAAQgBAAgBAAQAAAAgBAAQAAgBgBAAIAAAAIgDABIgBAAIgBAAIABAAIABAAIADgBIAAAAQABAAAAABQABAAAAAAQABAAABAAQAAAAABABgAkQgKIgEgGQgMgbgCglIgZgoIgmg7IgPgYIADgxIAAgKQAAgjgPgdQAPAdAAAjIAAAKIgDAxIAAAdQgBAoACAmQAAAJADAGQANAngrAjQgJgFgIgGQgZgUgGgqQgFgkAAgoQABgogFgmQgFgmgBgoQgCgmADgoQACgRAQgGIADgBQAPgDANACQAKAGAMACIAFABQAIABAFgDQAQgKgJgVIgRglQABAFgDABQgRANgOgNQgPgOgBgTIAAgKQABgJAGgDQARgKASANQAGgKgHgKQgKgPgJgRIADgFIAHgNIAGgNQAEgLAKgKIAHgFIAHgFQAFgCAGAAQAFAAAFACQANALANAHIANAIQAZgEAFAWIACAHQAQADANANQAMAMAHARQAIASAAAUQgBAUgJARQgIAOgSADQgRACgTACQADATAJAQIAEAJIALATIgLgTQAOgCAKgPQAIgLAQADQAOACAJAIQAcAXAcASQAdATAkAFQAmAGAeAOQAfAPAnACQAoACAkgHQAlgHAngDQAogDAegKQAWgGALgLQAggGgGAhQgCAUgNAPQgYAUgdAKQghARgkACQgnADgnABIhMAAQgoAAgjgKQgjgJgggSIhDgiIAGASQAEAPAHARQAaAeAGAkQAFAmAKAjQADANAGAMQAIAFADAIQAEAJgCAOIgCAFQgGAVgXANQgZAPgnADIhNAHIgGAAQgQAAgHgKgAl2mOIgLgJIALAJgAkhm8IABAAIACAAIACAAIgCAAIgCAAIgBAAIAAAAIgBAAQgPAAgMgEIgCAAIAAgBIgDAAIgNgHIANAHIADAAIAAABIACAAQAMAEAPAAIABAAIAAAAgAmEnkQgLgCgCgLIABABQACACAFAAIAAAAIACAAIABAAIgBAAIgCAAIAAAAQgFAAgCgCIgBgBIAAgDIABgIIgBAIIAAADQACALALACgAkfn7QATgCAOgMQAGgFAAgHIgBgHIABAHQAAAHgGAFQgOAMgTACIgOABQgLAAgLgDQgVgFgIgRQAIARAVAFQALADALAAIAOgBgAlgoTQgEAIAAAKQAAgKAEgIQADgHAFgFQgFAFgDAHgAkWouQAKgJAAgNIAAgFIAAAFQAAANgKAJgAlto3IAAgCQAAgOAKAAIABAAIAAAAIAJABIAAAAIAAABIACAAIgCAAIAAgBIAAAAIgJgBIAAAAIgBAAQgKAAAAAOIAAACIAAAAgAk1pGIgBgIQAAgQAKgEQgKAEAAAQIABAIgAlEpSIAAgEQAAgKAKgEQgKAEAAAKIAAAEgAmRnxIAAAAg");
	this.shape_10.setTransform(61.1,94.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7}]}).wait(19));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(6.6,23.8,115,136);


(lib.SlimSliding = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.anim_slim_playsguitar();
	this.instance.setTransform(-5.7,-6.2,0.932,0.932,0,0,0,120,83.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:77.8},14).to({x:-5.7},15).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-110.5,-61,105.4,125);


(lib.fcb_background_pressed_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//var component = _parent._parent;
		////::: don't delete the above
		//
		////::: SKIN ELEMENT REGISTRATION
		///*      To add styleFormat properties to your skins :
		//   1) Break up your skin into individual movie clips (skinElements)
		//   2) add a registerSkinElement line of code for each skinElement
		//
		//component.registerSkinElement(skinElement, propertyName)
		//// makes the skinElement Listen to the propertyName specified (eg: "background")
		//
		//																		  n*/
		//component.registerSkinElement(background_mc, "backgroundDisabled");
		//
		//
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// skin element
	this.background_mc = new lib.fcb_background_pressed();
	this.background_mc.setTransform(2,2);

	this.timeline.addTween(cjs.Tween.get(this.background_mc).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(2,2,9,9);


(lib.fcb_background_disabled_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//var component = _parent._parent;
		////::: don't delete the above
		//
		////::: SKIN ELEMENT REGISTRATION
		///*      To add styleFormat properties to your skins :
		//   1) Break up your skin into individual movie clips (skinElements)
		//   2) add a registerSkinElement line of code for each skinElement
		//
		//component.registerSkinElement(skinElement, propertyName)
		//// makes the skinElement Listen to the propertyName specified (eg: "background")
		//
		//																		  n*/
		//
		//component.registerSkinElement(background_mc, "backgroundDisabled");
		//
		//
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// skin element
	this.background_mc = new lib.fcb_background_disabled();
	this.background_mc.setTransform(2,2);

	this.timeline.addTween(cjs.Tween.get(this.background_mc).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(2,2,9,9);


(lib.fcb_background_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//var component = _parent._parent;
		////::: don't delete the above
		//
		////::: SKIN ELEMENT REGISTRATION
		///*      To add styleFormat properties to your skins :
		//   1) Break up your skin into individual movie clips (skinElements)
		//   2) add a registerSkinElement line of code for each skinElement
		//
		//component.registerSkinElement(skinElement, propertyName)
		//// makes the skinElement Listen to the propertyName specified (eg: "background")
		//
		//																		  n*/
		//component.registerSkinElement(background_mc, "background");
		//
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// skin element
	this.background_mc = new lib.fcb_background();
	this.background_mc.setTransform(2,2);

	this.timeline.addTween(cjs.Tween.get(this.background_mc).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(2,2,9,9);


(lib.fcb_frame = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//var component = _parent._parent;
		////::: don't delete the above
		//
		////::: SKIN ELEMENT REGISTRATION
		///*      To add styleFormat properties to your skins :
		//   1) Break up your skin into individual movie clips (skinElements)
		//   2) add a registerSkinElement line of code for each skinElement
		//
		//component.registerSkinElement(skinElement, propertyName)
		//// makes the skinElement Listen to the propertyName specified (eg: "background")
		//
		//																		  n*/
		//component.registerSkinElement(shadow_mc, "shadow");
		//component.registerSkinElement(darkshadow_mc, "darkshadow");
		//component.registerSkinElement(highlight_mc, "highlight");
		//component.registerSkinElement(highlight3D_mc, "highlight3D");
		//
		//
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// skin elements
	this.darkshadow_mc = new lib.fcb_leftOut();

	this.shadow_mc = new lib.fcb_leftIn();

	this.highlight_mc = new lib.fcb_rightIn();

	this.highlight3D_mc = new lib.fcb_rightOut();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.highlight3D_mc},{t:this.highlight_mc},{t:this.shadow_mc},{t:this.darkshadow_mc}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,13,13);


(lib.fcb_check_disabled_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//var component = _parent._parent;
		////::: don't delete the above
		//
		////::: SKIN ELEMENT REGISTRATION
		///*      To add styleFormat properties to your skins :
		//   1) Break up your skin into individual movie clips (skinElements)
		//   2) add a registerSkinElement line of code for each skinElement
		//
		//component.registerSkinElement(skinElement, propertyName)
		//// makes the skinElement Listen to the propertyName specified (eg: "background")
		//
		//																		  n*/
		//component.registerSkinElement(check_mc, "foregroundDisabled");
		//
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// skin element
	this.check_mc = new lib.fcb_check_disabled();
	this.check_mc.setTransform(2.9,3.2);

	this.timeline.addTween(cjs.Tween.get(this.check_mc).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(2.9,3.2,7.1,7);


(lib.fcb_check_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//var component = _parent._parent;
		////::: don't delete the above
		//
		////::: SKIN ELEMENT REGISTRATION
		///*      To add styleFormat properties to your skins :
		//   1) Break up your skin into individual movie clips (skinElements)
		//   2) add a registerSkinElement line of code for each skinElement
		//
		//component.registerSkinElement(skinElement, propertyName)
		//// makes the skinElement Listen to the propertyName specified (eg: "background")
		//
		//																		  n*/
		//
		//component.registerSkinElement(check_mc, "check");
		//
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// skin element
	this.check_mc = new lib.fcb_check();
	this.check_mc.setTransform(2.9,3.2);

	this.timeline.addTween(cjs.Tween.get(this.check_mc).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(2.9,3.2,7.1,7);


(lib.blank = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.blank_gr("synched",0);
	this.instance.setTransform(32.6,17,1,1,0,0,0,32.5,17);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,0,65,34);


(lib.blank_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.blank_gr("synched",0);
	this.instance.setTransform(32.6,17,1,1,0,0,0,32.5,17);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,0,65,34);


(lib.fcb_states = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{up:0,press:1,uncheckedDisabled:2,checkedDisabled:3,checkedPress:4,checkedEnabled:5});

	// timeline functions:
	this.frame_0 = function() {
		/* stop();
		*/
	}
	this.frame_1 = function() {
		/* stop();
		*/
	}
	this.frame_2 = function() {
		/* stop();*/
	}
	this.frame_3 = function() {
		/* stop();
		*/
	}
	this.frame_4 = function() {
		/* stop();
		*/
	}
	this.frame_5 = function() {
		/* stop();
		*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1).call(this.frame_2).wait(1).call(this.frame_3).wait(1).call(this.frame_4).wait(1).call(this.frame_5).wait(1));

	// check_enabled
	this.instance = new lib.fcb_check_1();
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({_off:false},0).wait(2));

	// check_disabled
	this.instance_1 = new lib.fcb_check_disabled_1();
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(3).to({_off:false},0).to({_off:true},1).wait(2));

	// background pressed/disabled
	this.instance_2 = new lib.fcb_background_pressed_1();

	this.instance_3 = new lib.fcb_background_disabled_1();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_2}]},2).to({state:[]},1).wait(1));

	// background static
	this.frb_frame_mc = new lib.fcb_background_1();

	this.timeline.addTween(cjs.Tween.get(this.frb_frame_mc).wait(6));

	// check box frame
	this.fcb_frame_mc = new lib.fcb_frame();

	this.timeline.addTween(cjs.Tween.get(this.fcb_frame_mc).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,13,13);


// stage content:
(lib.active_Summary = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{Summary:0});

	// timeline functions:
	this.frame_0 = function() {
		/* url = "http://grammarmechanics.com/chapters/segmentscores.swf?userid=" + userid + "&sid=" + segmentid;
		
		depth = 1000;
		this.createEmptyMovieClip("scores", depth++);
		scores.loadMovie(url);
		scores._x = 10;
		scores._y = 100;
		
		var interval;
		
		function isloaded() {
			trace("check is loaded");
			if(scores.isloaded)
			{
				trace(scores.score);
				score = scores.score;
				clearInterval(interval);
			}
		}
		
		interval = setInterval( isloaded, 1000 );
		
		trace(scores.score + " Score");
		trace(scores.isloaded + " Score");
		
		var endurl = "http://www.grammarmechanics.com/chapters/scripts/endSegment.php";
		endurl += "?segmentid=" + segmentid + "&userid=" + userid;
		loadVariablesNum(endurl, 0);
		trace(endurl);
		
		stop();*/
		playSound("congratulationsgreg");
		playSound("applause_cheering");
		this.btn_menu.addEventListener("click", openMenu.bind(this));
		
		function openMenu(){
		
		 window.open ("../menu/menu.html","_self");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Navigation
	this.instance = new lib.anim_pro_pointer();
	this.instance.setTransform(476.3,234.9,0.457,0.457,0,0,0,309.2,87.4);

	this.btn_menu = new lib.nextSEGMENT();
	this.btn_menu.setTransform(425.1,353.9,0.844,0.844,0,0,0,-163.5,-52.6);
	new cjs.ButtonHelper(this.btn_menu, 0, 1, 2, false, new lib.nextSEGMENT(), 3);

	this.instance_1 = new lib.SlimSliding();
	this.instance_1.setTransform(92.8,327.5,0.791,0.791,0,0,0,-60.7,-5.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.btn_menu},{t:this.instance}]}).wait(1));

	// BackgroundScore
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(240,15,218,0.624)").s().p("Ag6BJQgagVAAgnQABgqAVgeQAYghAmAAQAbAAASAKQAWAMAAAYQAAARgUAOQgIAGgcALIg/AfQAKAOAOAIQAOAHARAAQAMAAAQgFQAUgFAFgJQAHgKAGAAQAGAAAFAFQAFAEgBAGQABATgfAOQgaAMgZAAQgkAAgZgUgAgigtQgOAQgHAfIA0gXQAegPAMgLQgOgOgZAAQgVAAgNAQg");
	this.shape.setTransform(502.5,69.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(240,15,218,0.624)").s().p("AgwBKQgYgWAAgkQAAghAXglQAZgpAfAAQAQAAAVAIQAaAKAAAPQAAAGgEAFQgEAFgHAAQgFAAgDgDIgHgGQgLgIgWAAQgQAAgRAfQgQAdAAATQAAAWAQANQAOAMAVAAQAKAAAMgFIATgLIAIgCQAGAAAFAFQAEAFAAAGQAAANgaALQgXALgPAAQghAAgYgWg");
	this.shape_1.setTransform(483.6,69.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(240,15,218,0.624)").s().p("AgQB7QgEgFAAgHIAAgfIgBgfQAAgPACgZIABglQAAgJAFgEQAEgFAIAAQAFAAAFAFQAEAEABAJIgCAlQgCAZAAAPIABAfIABAfQgBAHgFAFQgEAFgFAAQgIAAgFgFgAgKhdQgGgGAAgIQAAgIAGgGQAGgGAHAAQAIAAAFAGQAHAGAAAIQAAAIgHAGQgFAFgIABQgHgBgGgFg");
	this.shape_2.setTransform(470,65.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(240,15,218,0.624)").s().p("AgyBIQgXgXgBgoQgBglAUgeQAYgiApAAQAiAAASAfQAOAZgBAkQAAAkgTAbQgWAegiAAQgdAAgVgVgAgdghQgLASAAAYQAAAZANANQALALAQAAQAPAAANgMQAPgPABgYQAChBgmAAQgXAAgOAZg");
	this.shape_3.setTransform(455.2,70);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(240,15,218,0.624)").s().p("AgeB8QgVg0gZhfIgNgvQgKgkAAgLQAAgHAFgFQAFgFAHAAQANAAAEAOIAGAeIAQA6QARA9APAvIABgEIAsh5IAPgqQAJgZALgNQAGgIAIABQAHAAAFAFQAFAFAAAIQAAAFgDAEQgLAQgGASIgNAmIguB6QgIAVgLAVQgEALgJAAQgOAAgFgOg");
	this.shape_4.setTransform(436.1,65.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(240,15,218,0.624)").s().p("Ag5BJQgagVAAgnQgBgqAWgeQAXghAnAAQAbAAASAKQAWAMAAAYQAAARgTAOQgJAGgbALIhAAfQAJAOAPAIQAOAHARAAQAMAAAQgFQAUgFAGgJQAFgKAHAAQAGAAAFAFQAEAEABAGQgBATgeAOQgaAMgZAAQgkAAgYgUgAgigtQgOAQgHAfIA1gXQAcgPAOgLQgPgOgZAAQgUAAgOAQg");
	this.shape_5.setTransform(404,69.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(240,15,218,0.624)").s().p("AgSBOIgahFIgehMQgCgFAAgDQAAgHAFgFQAFgFAHAAQALAAAEAKIAsB2QAKgcAUgyIAOgmQAGgLAJAAQAHAAAGAFQAFAFAAAHQAAAGgcBDIgjBOQgBAQgNAAQgMAAgGgPg");
	this.shape_6.setTransform(385.8,69.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(240,15,218,0.624)").s().p("AgQB7QgEgFAAgHIgBgfIgBgfQAAgPADgZIABglQAAgJAFgEQAFgFAHAAQAFAAAFAFQAFAEgBAJIgBAlQgCAZAAAPIABAfIAAAfQAAAHgEAFQgFAFgGAAQgHAAgFgFgAgKhdQgGgGAAgIQAAgIAGgGQAGgGAGAAQAIAAAHAGQAFAGAAAIQAAAIgFAGQgHAFgIABQgGgBgGgFg");
	this.shape_7.setTransform(372.5,65.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(240,15,218,0.624)").s().p("AgvBeQgagJAAgRQAAgHAGgFQAFgFAGAAQAGAAAJAIQAEAEAOACQALACAIAAQAMAAAMgDQAPgFAAgLQAAgXgggIIgQgEQgWgFgLgHQgNgHAAgUQAAgjAigPQAKgFAUgGQAXgHAKgEQAGgDAJAAQAHAAAFAEQAFAFgBAIQAAAFADAJIACAPQAAAIgFAEQgFAFgHAAQgJAAgEgGQgCgFgCgOIgoAMQgZALAAAQIAKADQAkAHAUAMQAcAQgBAiQAAAcgXAOQgUAMgdAAQgWAAgVgIg");
	this.shape_8.setTransform(358.3,69.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(240,15,218,0.624)").s().p("AguBeQgbgJAAgRQAAgHAFgFQAGgFAHAAQAFAAAIAIQAFAEANACQAMACAIAAQANAAAKgDQAQgFAAgLQAAgXgggIIgQgEQgXgFgJgHQgOgHAAgUQAAgjAhgPQALgFAVgGQAWgHAJgEQAIgDAIAAQAHAAAFAEQAEAFABAIQgBAFADAJIACAPQAAAIgFAEQgEAFgIAAQgKAAgDgGQgDgFgBgOIgoAMQgZALgBAQIAKADQAmAHATAMQAbAQABAiQAAAcgZAOQgTAMgdAAQgXAAgTgIg");
	this.shape_9.setTransform(341.2,69.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(240,15,218,0.624)").s().p("AA2BXQgIgHgDgGIgdAOQgNAEgGAAQgoAAgSgWQgSgVAAgtQAAgnAdgdQAcgdAmgBQAPABASAHQAXAKAAAOQAAAEgDAEQgCAGgBAPIgBAkQAAAVADANQACAHAJAWIAEAJIABAEQAAAGgFAFQgFAFgGgBQgDABgJgIgAgcgqQgTAWAAAbQAAAcAKANQAKAOAUABQAOAAAMgHQAGgDALgJQgGgsAAgXIABgQIADgSIgLgEIgHgCQgYAAgUAVg");
	this.shape_10.setTransform(324.2,70);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("rgba(240,15,218,0.624)").s().p("AhICDQgEgFAAgGIAAgzQAAgZADgsIAEhGIAAgYQAAgRACgHQAEgPANACQAFgCAKgBIAZgBQAeAAAbAWQAeAXAAAhQAAArghAXQgcAWgmAAIgWgCIgBBbQABAGgFAFQgEAFgHAAQgHAAgFgFgAgbhmIgLABIAAAgIgDBEIATABQAaAAAUgOQAVgQABgbQgBgTgUgOQgTgMgUAAIgNAAg");
	this.shape_11.setTransform(306.4,65.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("rgba(240,15,218,0.624)").s().p("AgOAOQgGgGAAgIQAAgHAGgGQAGgHAIAAQAIAAAGAHQAHAGAAAHQAAAIgHAGQgGAHgIAAQgIAAgGgHg");
	this.shape_12.setTransform(282.4,77.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("rgba(240,15,218,0.624)").s().p("AgvBeQgagJAAgRQAAgHAFgFQAGgFAGAAQAGAAAJAIQADAEAOACQAMACAIAAQAMAAALgDQAQgFAAgLQAAgXgggIIgQgEQgXgFgJgHQgOgHAAgUQAAgjAigPQAKgFAUgGQAXgHAJgEQAHgDAJAAQAHAAAFAEQAFAFAAAIQAAAFACAJIACAPQAAAIgFAEQgFAFgHAAQgKAAgDgGQgDgFgCgOIgnAMQgaALABAQIAKADQAkAHAUAMQAbAQAAAiQABAcgYAOQgVAMgcAAQgWAAgVgIg");
	this.shape_13.setTransform(268.9,69.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("rgba(240,15,218,0.624)").s().p("AgSBOIgahFIgehMQgCgFAAgDQAAgHAFgFQAFgFAHAAQALAAAEAKIAsB2QAKgcAUgyIAOgmQAGgLAJAAQAHAAAGAFQAFAFAAAHQAAAGgcBDIgjBOQgBAQgNAAQgMAAgGgPg");
	this.shape_14.setTransform(252.6,69.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("rgba(240,15,218,0.624)").s().p("Ag6BJQgagVAAgnQAAgqAWgeQAYghAmAAQAbAAASAKQAWAMAAAYQAAARgTAOQgJAGgbALIhAAfQAKAOAOAIQAOAHARAAQAMAAAQgFQAUgFAGgJQAFgKAHAAQAGAAAFAFQAEAEAAAGQAAATgeAOQgaAMgZAAQgkAAgZgUgAgigtQgOAQgHAfIA0gXQAdgPANgLQgOgOgZAAQgUAAgOAQg");
	this.shape_15.setTransform(224.2,69.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("rgba(240,15,218,0.624)").s().p("AgwBKQgYgWAAgkQAAghAXglQAZgpAfAAQAQAAAVAIQAaAKAAAPQAAAGgEAFQgEAFgHAAQgFAAgDgDIgHgGQgLgIgWAAQgQAAgRAfQgQAdAAATQAAAWAQANQAOAMAVAAQAKAAAMgFIATgLIAIgCQAGAAAFAFQAEAFAAAGQAAANgaALQgXALgPAAQghAAgYgWg");
	this.shape_16.setTransform(205.3,69.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("rgba(240,15,218,0.624)").s().p("AgQB7QgEgFAAgHIAAgfIgCgfQABgPACgZIABglQAAgJAFgEQAFgFAHAAQAFAAAFAFQAFAEAAAJIgCAlQgCAZAAAPIABAfIAAAfQAAAHgEAFQgFAFgGAAQgHAAgFgFgAgKhdQgGgGAAgIQAAgIAGgGQAGgGAGAAQAIAAAHAGQAFAGABAIQgBAIgFAGQgHAFgIABQgGgBgGgFg");
	this.shape_17.setTransform(191.7,65.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("rgba(240,15,218,0.624)").s().p("AgyBIQgXgXgBgoQgBglAUgeQAYgiApAAQAiAAASAfQAOAZgBAkQAAAkgTAbQgWAegiAAQgdAAgVgVgAgdghQgLASAAAYQAAAZANANQALALAQAAQAPAAANgMQAPgPABgYQAChBgmAAQgXAAgOAZg");
	this.shape_18.setTransform(176.9,70);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("rgba(240,15,218,0.624)").s().p("AgeB8QgVg0gZhfIgNgvQgKgkAAgLQAAgHAFgFQAFgFAHAAQANAAAEAOIAGAeIAQA6QARA9APAvIABgEIAsh5IAPgqQAJgZALgNQAGgIAIABQAHAAAFAFQAFAFAAAIQAAAFgDAEQgLAQgGASIgNAmIguB6QgIAVgLAVQgEALgJAAQgOAAgFgOg");
	this.shape_19.setTransform(157.8,65.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("rgba(240,15,218,0.624)").s().p("Ag5BJQgagVAAgnQAAgqAVgeQAXghAnAAQAbAAASAKQAWAMAAAYQAAARgUAOQgIAGgcALIg/AfQAJAOAPAIQAOAHARAAQAMAAAQgFQAUgFAFgJQAHgKAGAAQAGAAAFAFQAFAEAAAGQAAATgfAOQgaAMgZAAQglAAgXgUgAgigtQgOAQgHAfIA1gXQAdgPANgLQgPgOgZAAQgVAAgNAQg");
	this.shape_20.setTransform(125.7,69.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("rgba(240,15,218,0.624)").s().p("AgSBOIgahFIgehMQgCgFAAgDQAAgHAFgFQAFgFAHAAQALAAAEAKIAsB2QAKgcAUgyIAOgmQAGgLAJAAQAHAAAGAFQAFAFAAAHQAAAGgcBDIgjBOQgBAQgNAAQgMAAgGgPg");
	this.shape_21.setTransform(107.5,69.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("rgba(240,15,218,0.624)").s().p("AgPB7QgFgFAAgHIgBgfIgBgfQAAgPACgZIACglQAAgJAFgEQAEgFAIAAQAFAAAFAFQAFAEgBAJIgBAlQgCAZAAAPIABAfIABAfQAAAHgGAFQgEAFgGAAQgHAAgEgFgAgKhdQgGgGAAgIQAAgIAGgGQAGgGAGAAQAJAAAGAGQAFAGAAAIQAAAIgFAGQgGAFgJABQgGgBgGgFg");
	this.shape_22.setTransform(94.2,65.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("rgba(240,15,218,0.624)").s().p("AgJB4QgGgFAAgGIAAgUIABgTIgDhiIgmgDQgQgCAAgPQABgHAEgFQAFgFAHAAIAkADIgBgYIAAgVQAAgHAEgFQAGgEAHAAQANAAADAZIAAAPIAAAKIAAAKIAXgCQATAAAFABQAKAEAAAMQAAAIgEAFQgFAFgIAAIgIgBIgJAAIgWADIACBjIABAHIAAAJQABAlgTAAQgFAAgEgEg");
	this.shape_23.setTransform(80.7,67);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("rgba(240,15,218,0.624)").s().p("AgwBKQgYgWAAgkQAAghAXglQAZgpAfAAQAQAAAVAIQAaAKAAAPQAAAGgEAFQgEAFgHAAQgFAAgDgDIgHgGQgLgIgWAAQgQAAgRAfQgQAdAAATQAAAWAQANQAOAMAVAAQAKAAAMgFIATgLIAIgCQAGAAAFAFQAEAFAAAGQAAANgaALQgXALgPAAQghAAgYgWg");
	this.shape_24.setTransform(63.5,69.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("rgba(240,15,218,0.624)").s().p("AA7BYQgEgPgHgnQgSADgcAGIgrAJQgJAXgUArQgGAJgJAAQgHAAgFgFQgGgFAAgHQAAgIAag2QgDgFAAgGQAAgOARgDQATgjAegwQAnhAAJAAQAOAAAFASIALA6IAZB1IAKAbQAFAOAAAEQAAAHgFAFQgGAFgHAAQgPAAgMgogAgVAMQAVgFAogHIgOhBg");
	this.shape_25.setTransform(41.4,66);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgGAHQgEgDAAgEQAAgDAEgDQADgEADAAQAEAAADAEQAEADAAADQAAAEgEADQgDAEgEAAQgDAAgDgEg");
	this.shape_26.setTransform(398.7,31.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AAWAsIgDgUIgBgUIAAgHIAAgIQAAgTgHgBQgKAAgHANQgIAKgFAPIgBAJIAAAJIAAAIIABAHQAAAFgDACQgCADgEAAQgEAAgCgDQgDgCAAgFIAAgHIgBgIIABgZIACgZIgBgJIAAgIQAAgEACgCQADgDAEAAQAIAAABAMIAAALQAPgVAOAAQAPAAAFANQAEAJAAAQIAAAJIAAAGQAAAIACAMQACAMAAAHQAAAEgCACQgDADgEAAQgHAAgBgIg");
	this.shape_27.setTransform(391.7,26.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgaAlQgMgMAAgUQgBgTALgPQANgTAUAAQASAAAJAQQAIAOgBASQAAASgKAPQgMAQgRAAQgPAAgLgMgAgPgRQgGAKAAAMQAAAMAIAIQAFAFAIABQAIAAAHgHQAHgIABgMQABghgUAAQgLAAgIAMg");
	this.shape_28.setTransform(381.8,27.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgHBBQgDgDAAgEIAAgQIAAgQIAAgVIABgTQABgEACgDQACgCAEAAQACAAADACQACADAAAEIgBATIgBAVIAAAQIABAQQAAAEgCADQgDACgCAAQgEAAgCgCgAgEgwQgEgDAAgFQAAgEAEgDQADgDACAAQAEAAADADQAEADAAAEQAAAFgEADQgDADgEAAQgCAAgDgDg");
	this.shape_29.setTransform(374.7,24.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgEA/QgDgDAAgDIAAgKIAAgLIgBgyIgUgCQgIgBAAgIQAAgEACgCQACgDAEAAIATACIAAgNIgBgLQAAgDADgDQADgCADAAQAGAAACANIAAAIIAAAFIAAAGIANgCQAJAAADABQAFACAAAHQAAADgCADQgDADgEAAIgEgBIgEAAIgNACIACAzIAAAEIAAAEQABAUgKAAQgCAAgCgCg");
	this.shape_30.setTransform(367.6,25.5);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgYAnQgNgLAAgUQAAgQAMgTQANgWAPAAQAJAAALAEQAOAGAAAHQAAADgDADQgCADgDgBQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAgBgBAAIgDgDQgGgEgMAAQgHAAgJAQQgIAPAAAJQAAAMAIAHQAIAGAJABQAGAAAGgEIAKgFIAEgBQAEAAACACQACADAAADQAAAHgNAGQgNAFgIAAQgQAAgMgLg");
	this.shape_31.setTransform(358.6,27);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgeAmQgNgLAAgUQAAgVALgQQAMgRAUAAQAOAAAJAEQAMAHAAAMQAAAKgKAHIgTAIIghAQQAFAIAIADQAHAFAIAAQAGAAAJgDQAKgDAEgEQADgGADAAQADABADACQACACAAAEQAAAJgQAIQgOAFgNAAQgSAAgNgKgAgRgXQgIAIgDAQIAbgLQAPgJAHgFQgIgIgNAAQgKAAgHAJg");
	this.shape_32.setTransform(349,27);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgYAyQgOgGAAgJQAAgDADgDQADgCAEgBQACAAAFAFQACACAIABIAKABQAFAAAGgBQAIgDAAgGQAAgMgRgFIgHgBQgMgDgFgEQgHgCAAgLQAAgSARgIIAQgGIARgGQADgBAFgBQAEABACACQADADAAADIABAIIABAIQAAAEgDACQgCACgEABQgFAAgCgEQgBgCgBgIIgVAHQgNAFAAAJIAGACQASAEAKAGQAPAHAAASQAAAPgNAHQgKAHgOgBQgMAAgLgDg");
	this.shape_33.setTransform(339,26.7);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgYAyQgOgGAAgJQAAgDADgDQADgCAEgBQACAAAFAFQACACAIABIAKABQAFAAAGgBQAIgDAAgGQAAgMgRgFIgHgBQgMgDgFgEQgHgCAAgLQAAgSARgIIAQgGIARgGQADgBAFgBQAEABACACQADADAAADIABAIIABAIQAAAEgDACQgCACgEABQgFAAgCgEQgBgCgBgIIgVAHQgNAFAAAJIAGACQASAEAKAGQAPAHAAASQAAAPgNAHQgKAHgOgBQgMAAgLgDg");
	this.shape_34.setTransform(324.5,26.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AgHBBQgDgDAAgEIAAgQIgBgQIABgVIACgTQAAgEACgDQADgCADAAQACAAACACQADADAAAEIgBATIgBAVIAAAQIABAQQAAAEgDADQgCACgCAAQgEAAgCgCgAgFgwQgCgDAAgFQAAgEACgDQAEgDACAAQAEAAAEADQACADAAAEQAAAFgCADQgEADgEAAQgCAAgEgDg");
	this.shape_35.setTransform(317.9,24.8);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AAYBDIgEgUIgCgWIABgHIAAgHQAAgPgIAAQgLAAgIAIQgFAGgHAPQAAAigDAGQgDAGgFAAQgEAAgCgDQgDgCAAgEIABgEIABgNIAAgNIAAhAIABgPIgBgJIgBgJQAAgDACgDQADgCAEAAQAHAAACAIIABAPIAAAUQgCAKABAKIAAAIQAIgKAIgFQAGgFAKAAQAPAAAFAKQAEAGAAAPIABARIACATIADASIABADQgBADgCADQgDACgEAAQgGAAgCgHg");
	this.shape_36.setTransform(309.9,24.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgEA/QgDgDAAgDIAAgKIAAgLIgBgyIgUgCQgIgBAAgIQAAgEACgCQACgDAEAAIATACIAAgNIgBgLQAAgDADgDQADgCADAAQAGAAACANIAAAIIAAAFIAAAGIANgCQAJAAADABQAFACAAAHQAAADgCADQgDADgEAAIgEgBIgEAAIgNACIACAzIAAAEIAAAEQABAUgKAAQgCAAgCgCg");
	this.shape_37.setTransform(300.1,25.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgfA9QgMgNAAgUQAAgYAMgMQANgPASAAQALAAAFAEIAJAGIADgzQABgIAHAAQAIAAAAAJQAAAMgDArIgBAYQAAAeACAQIABACQAAADgDADQgDACgDAAQgFAAgDgIQgHAFgGACQgHACgGAAQgTAAgMgMgAgUABQgIAJAAASQAAAMAJAIQAIAIALAAQAGAAAFgCIAKgIIACgDIAAgPIAAgLIAAgKQgDgHgGgCQgFgEgIAAQgNAAgIAHg");
	this.shape_38.setTransform(284.8,24.5);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgeAmQgNgLAAgUQAAgVALgQQAMgRAUAAQAOAAAJAEQAMAHAAAMQAAAKgKAHIgTAIIghAQQAFAIAIADQAHAFAIAAQAGAAAJgDQAKgDAEgEQADgGADAAQADABADACQACACAAAEQAAAJgQAIQgOAFgNAAQgSAAgNgKgAgRgXQgIAIgDAQIAbgLQAPgJAHgFQgIgIgNAAQgKAAgHAJg");
	this.shape_39.setTransform(274.6,27);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgEA/QgDgDAAgDIAAgKIAAgLIgBgyIgUgCQgIgBAAgIQAAgEACgCQACgDAEAAIATACIAAgNIgBgLQAAgDADgDQADgCADAAQAGAAACANIAAAIIAAAFIAAAGIANgCQAJAAADABQAFACAAAHQAAADgCADQgDADgEAAIgEgBIgEAAIgNACIACAzIAAAEIAAAEQABAUgKAAQgCAAgCgCg");
	this.shape_40.setTransform(265,25.5);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgeAmQgNgLAAgUQAAgVALgQQAMgRAUAAQAOAAAJAEQAMAHAAAMQAAAKgKAHIgTAIIghAQQAFAIAIADQAHAFAIAAQAGAAAJgDQAKgDAEgEQADgGADAAQADABADACQACACAAAEQAAAJgQAIQgOAFgNAAQgSAAgNgKgAgRgXQgIAIgDAQIAbgLQAPgJAHgFQgIgIgNAAQgKAAgHAJg");
	this.shape_41.setTransform(255.9,27);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgJBBIABghIABggIABgfIAAghQAAgJAHAAQAJAAAAAJIAAAhIgBAfIgBAsIgBAVQgBAJgGAAQgJAAAAgJg");
	this.shape_42.setTransform(248.1,24.5);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AghBJQgDgDAAgEIAAgkIAAgiIgBgkIgCgSQABgGACgFQACgFAGAAQADAAADACQACADAAADIAAADIAAAGQAHgGAHgCQAGgDAGAAQASAAAJAQQAGANABAWQAAARgKANQgMANgSAAQgHAAgLgDIAAArQAAAEgCADQgDACgEAAQgEAAgCgCgAgHguQgFACgHAHIABApQAKAEAIAAQALAAAGgIQAFgGAAgLQAAgRgEgIQgEgIgIAAQgHAAgGAEg");
	this.shape_43.setTransform(240.7,29.2);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgEA0QgCgCgBgEIgCggQgCgUAAgKQAAgKgDgFQgGADgHAGIgKAMIgFAGIgBAOIgBAPIABAIIABAHQAAAEgDACQgCACgEABQgKgBAAgXIABgPIABgOIgBgPIgBgOQAAgVAJAAQAEAAADADQADADgBAEIAAAFIAAAGIAAAJQAEgJAKgIQAJgIAGAAQAOAAAEAOQAEgGAIgEQAGgDAJAAQAPAAAGAQIADAaIAHAxQAAADgCADQgDACgEAAQgHAAgCgIIgDgcIgDgZIgDgMQgEgJgDABQgDgBgJAHQgJAEgCAEIAAAQIADAWIABAYQAAAEgCACQgCADgFAAQgCAAgCgDg");
	this.shape_44.setTransform(228.7,27.1);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgaAlQgMgMAAgUQgBgTALgPQANgTAUAAQASAAAJAQQAIAOgBASQAAASgKAPQgMAQgRAAQgPAAgLgMgAgPgRQgGAKAAAMQAAAMAIAIQAFAFAIABQAIAAAHgHQAHgIABgMQABghgUAAQgLAAgIAMg");
	this.shape_45.setTransform(216.4,27.1);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgYAnQgNgLAAgUQAAgQAMgTQANgWAPAAQAJAAALAEQAOAGAAAHQAAADgDADQgCADgDgBQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAgBgBAAIgDgDQgGgEgMAAQgHAAgJAQQgIAPAAAJQAAAMAIAHQAIAGAJABQAGAAAGgEIAKgFIAEgBQAEAAACACQACADAAADQAAAHgNAGQgNAFgIAAQgQAAgMgLg");
	this.shape_46.setTransform(207.1,27);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AAUAqQgMAHgMAAQgMAAgIgGQgIgGgCgKQgDgYAAgRQAAgNACgPQACgIAHAAQAEAAACACQADADAAAEIgBANIgCAOIABAYQABAKACAHIAGADIAGAAQAKAAANgDIAAgTIAAgPQAAgUACgOQABgIAHAAQAEgBADADQACADAAAEIgBAiIAAARIAAATIAAAHIAAAFQAAAEgCADQgDACgEAAQgGAAgCgJg");
	this.shape_47.setTransform(192,27.1);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AgaAlQgMgMAAgUQgBgTALgPQANgTAUAAQASAAAJAQQAIAOgBASQAAASgKAPQgMAQgRAAQgPAAgLgMgAgPgRQgGAKAAAMQAAAMAIAIQAFAFAIABQAIAAAHgHQAHgIABgMQABghgUAAQgLAAgIAMg");
	this.shape_48.setTransform(182.2,27.1);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AgSBEQgDgCAAgEQAAgDAJgQIALgUQgQgVgFgKQgEgKgKgPIgPgXQAAgBAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBQAAgEADgCQADgDADAAQAFAAADAEIAHALIAMAUQAHALAEAJQADAIAIAKIAUgwIAKgTQACgGAGAAQAEAAADADQACACAAAEQAAAEgEAJIgGAKIgQAmIgQAkIgLAUIgDAKQgDAFgFAAQgEAAgDgDg");
	this.shape_49.setTransform(171.4,25);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#000000").s().p("AgFBGQgDgEAAgEQAAgDACgDQADgCADAAQACAAAEAFQADAEAAAEQAAADgCACQgEADgCAAQgCAAgEgFgAgFAgIgBgKIAAgLIAAgmIABgnQAAgIAGAAQAIAAAAAIIAABiQAAAIgIAAQgGAAAAgIg");
	this.shape_50.setTransform(152.5,24.6);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("AgYAyQgOgGAAgJQAAgDADgDQADgCAEgBQACAAAFAFQACACAIABIAKABQAFAAAGgBQAIgDAAgGQAAgMgRgFIgHgBQgMgDgFgEQgHgCAAgLQAAgSARgIIAQgGIARgGQADgBAFgBQAEABACACQADADAAADIABAIIABAIQAAAEgDACQgCACgEABQgFAAgCgEQgBgCgBgIIgVAHQgNAFAAAJIAGACQASAEAKAGQAPAHAAASQAAAPgNAHQgKAHgOgBQgMAAgLgDg");
	this.shape_51.setTransform(145.7,26.7);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#000000").s().p("AAWAsIgDgUIgBgUIAAgHIAAgIQAAgTgHgBQgKAAgHANQgIAKgFAPIgBAJIAAAJIAAAIIABAHQAAAFgDACQgCADgEAAQgEAAgCgDQgDgCAAgFIAAgHIgBgIIABgZIACgZIgBgJIAAgIQAAgEACgCQADgDAEAAQAIAAABAMIAAALQAPgVAOAAQAPAAAFANQAEAJAAAQIAAAJIAAAGQAAAIACAMQACAMAAAHQAAAEgCACQgDADgEAAQgHAAgBgIg");
	this.shape_52.setTransform(136.9,26.9);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#000000").s().p("AgaAlQgMgMAAgUQgBgTALgPQANgTAUAAQASAAAJAQQAIAOgBASQAAASgKAPQgMAQgRAAQgPAAgLgMgAgPgRQgGAKAAAMQAAAMAIAIQAFAFAIABQAIAAAHgHQAHgIABgMQABghgUAAQgLAAgIAMg");
	this.shape_53.setTransform(126.9,27.1);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#000000").s().p("AgHBBQgDgDAAgEIAAgQIgBgQIABgVIACgTQAAgEACgDQADgCADAAQACAAACACQADADAAAEIgBATIgBAVIAAAQIABAQQAAAEgDADQgCACgCAAQgEAAgCgCgAgEgwQgDgDAAgFQAAgEADgDQADgDACAAQAEAAAEADQACADAAAEQAAAFgCADQgEADgEAAQgCAAgDgDg");
	this.shape_54.setTransform(119.9,24.8);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#000000").s().p("AgEA/QgDgDAAgDIAAgKIAAgLIgBgyIgUgCQgIgBAAgIQAAgEACgCQACgDAEAAIATACIAAgNIgBgLQAAgDADgDQADgCADAAQAGAAACANIAAAIIAAAFIAAAGIANgCQAJAAADABQAFACAAAHQAAADgCADQgDADgEAAIgEgBIgEAAIgNACIACAzIAAAEIAAAEQABAUgKAAQgCAAgCgCg");
	this.shape_55.setTransform(112.7,25.5);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#000000").s().p("AAcAtIgGgGIgPAHQgGADgDAAQgVAAgKgNQgJgLAAgXQAAgTAPgQQAPgPATAAQAIAAAKADQAMAFAAAIIgCAEIgBALIgBASQAAALACAHIAFAQIACAFIABABQAAAEgDACQgCADgDAAQgCAAgFgFgAgOgVQgKAMAAAMQAAAPAFAHQAGAIAKAAQAHAAAGgEIAJgGQgDgXAAgLIAAgIIACgKIgGgDIgEgBQgMAAgKAMg");
	this.shape_56.setTransform(103.7,27.1);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#000000").s().p("AgJBBIABghIABggIABgfIAAghQAAgJAHAAQAJAAAAAJIAAAhIgBAfIgBAsIgBAVQgBAJgGAAQgJAAAAgJg");
	this.shape_57.setTransform(96.5,24.5);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#000000").s().p("AAUAqQgMAHgMAAQgMAAgIgGQgIgGgCgKQgDgYAAgRQAAgNACgPQACgIAHAAQAEAAACACQADADAAAEIgBANIgCAOIABAYQABAKACAHIAGADIAGAAQAKAAANgDIAAgTIAAgPQAAgUACgOQABgIAHAAQAEgBADADQACADAAAEIgBAiIAAARIAAATIAAAHIAAAFQAAAEgCADQgDACgEAAQgGAAgCgJg");
	this.shape_58.setTransform(89.2,27.1);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#000000").s().p("AgEA/QgDgDAAgDIAAgKIAAgLIgBgyIgUgCQgIgBAAgIQAAgEACgCQACgDAEAAIATACIAAgNIgBgLQAAgDADgDQADgCADAAQAGAAACANIAAAIIAAAFIAAAGIANgCQAJAAADABQAFACAAAHQAAADgCADQgDADgEAAIgEgBIgEAAIgNACIACAzIAAAEIAAAEQABAUgKAAQgCAAgCgCg");
	this.shape_59.setTransform(80,25.5);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#000000").s().p("AAcAtIgGgGIgPAHQgGADgDAAQgVAAgKgNQgJgLAAgXQAAgTAPgQQAPgPATAAQAIAAAKADQAMAFAAAIIgCAEIgBALIgBASQAAALACAHIAFAQIACAFIABABQAAAEgDACQgCADgDAAQgCAAgFgFgAgOgVQgKAMAAAMQAAAPAFAHQAGAIAKAAQAHAAAGgEIAJgGQgDgXAAgLIAAgIIACgKIgGgDIgEgBQgMAAgKAMg");
	this.shape_60.setTransform(71,27.1);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#000000").s().p("AgiApIAAg9IABgJIAAgJQAAgJAIAAQAIAAABAPQAQgRAUAAQAHAAAEAGQADAFABALIAAAGQgBAMgIAAQgIAAAAgJIAAgGIgBgIQgOABgHAHQgHAGgGAMIAAAvQABAJgKAAQgIAAAAgJg");
	this.shape_61.setTransform(62.1,27.1);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#000000").s().p("AgeBFQgMgCAAgHQABgIAHAAIAMACQAHABAJAAQAPAAAHgRQAEgLABgWQgGAJgGAEQgHAEgGAAQgRAAgKgLQgKgLAAgPQAAgZAOgPQAOgPAXAAQAJAAAFACQAGACADAFQAKAAAAAKIgCASIgDAQIgCAdQAAASgDALQgFAPgJAHQgKAIgTAAQgMAAgIgCgAgQgsQgHALgBAQQABANAEAFQAFAGAKAAQAHAAAJgIQAHgJACgJIADgfQgDgDgEgBIgIgBQgPAAgKALg");
	this.shape_62.setTransform(52.4,29.4);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#000000").s().p("AAWAsIgDgUIgBgUIAAgHIAAgIQAAgTgHgBQgKAAgHANQgIAKgFAPIgBAJIAAAJIAAAIIABAHQAAAFgDACQgCADgEAAQgEAAgCgDQgDgCAAgFIAAgHIgBgIIABgZIACgZIgBgJIAAgIQAAgEACgCQADgDAEAAQAIAAABAMIAAALQAPgVAOAAQAPAAAFANQAEAJAAAQIAAAJIAAAGQAAAIACAMQACAMAAAHQAAAEgCACQgDADgEAAQgHAAgBgIg");
	this.shape_63.setTransform(43.1,26.9);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#000000").s().p("AgaAlQgMgMAAgUQgBgTALgPQANgTAUAAQASAAAJAQQAIAOgBASQAAASgKAPQgMAQgRAAQgPAAgLgMgAgPgRQgGAKAAAMQAAAMAIAIQAFAFAIABQAIAAAHgHQAHgIABgMQABghgUAAQgLAAgIAMg");
	this.shape_64.setTransform(33.1,27.1);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#000000").s().p("AgkA3QgNgOAAgTQABgcAZggQAWgbATAAIAIABIAGABQAEgFAEAAQAHAAABAIIABASQABAEgCADQgDADgEAAQgGAAgDgGQgCgHgCAAQgCgBgIAAQgNgBgOAVQgWAaAAAWQABAMAHAIQAHAJALAAQAIAAAJgFIAQgKQAGgEACAAQAEAAACADQADADAAADQAAAEgEADQgXAVgXAAQgSAAgNgOg");
	this.shape_65.setTransform(23.1,24.8);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f().s("#000000").ss(0.3,1,1).p("AAAABIAAgB");
	this.shape_66.setTransform(423.7,110.5);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.lf(["#FFFFFF","#FFFF66"],[0,1],-280.3,-23.5,-280.3,20.7).s().p("Egq9ADbIAAm1MBV7AAAIAAG1g");
	this.shape_67.setTransform(275.1,65.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Background
	this.scoretxt = new cjs.Text("", "210px 'Comic Sans MS'", "#FFEEF7");
	this.scoretxt.name = "scoretxt";
	this.scoretxt.textAlign = "center";
	this.scoretxt.lineHeight = 295;
	this.scoretxt.lineWidth = 429;
	this.scoretxt.setTransform(396.5,57.6);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.lf(["#FFFFFF","#FF0099"],[0,1],-0.3,-201.5,-0.3,199.2).s().p("Egq9AfPMAAAg+dMBV7AAAMAAAA+dg");
	this.shape_68.setTransform(275.1,200.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_68},{t:this.scoretxt}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(275.1,200.5,615,400);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;