(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.vol_pos = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.5,1,1).p("ABagwIAABgQAAAWgZAAIiBAAQgZAAAAgWIAAhgQAAgVAZAAICBAAQAZAAAAAVg");
	this.shape.setTransform(9,7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgKA0QgDgDAAgGIAAgfIgFABIgTAAQgVAAAAgNQAAgHAHgDQADAAALAAIAYgBIAAgQIABgRQABgFADgDQADgCAEAAQAFAAADADQAEAEgBAFIAAAHIgBAIIABAPIAAAAIAKABIAIAAIAHgBIABAAIAJABQAKABADAGIABAEIgBAFIgDADIgDADIgFABIgEgBIgCAAIgEAAIgNAAIgOAAIAAAgQAAAMgLAAQgGAAgDgDg");
	this.shape_1.setTransform(9.6,6.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00CCFF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICBAAQAYAAABAWIAABfQgBAWgYAAgAgHAqQAAAGADADQAEADAEAAQAMAAABgMIAAggIANAAIAOAAIADAAIACAAIAFABIAFgBIADgDIACgDIABgFIgBgEQgCgGgKgBIgJgBIgBAAIgHABIgIAAIgKgBIAAAAIgBgPIABgIIAAgHQAAgFgEgEQgDgDgGAAQgEAAgBACQgEADgBAFIgBARIAAAQIgYABQgKAAgDAAQgHADgBAIQABAMAUAAIATAAIAFgBg");
	this.shape_2.setTransform(9,7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0099FF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICBAAQAYAAABAWIAABfQgBAWgYAAgAgHAqQAAAGADADQAEADAEAAQAMAAABgMIAAggIANAAIAOAAIADAAIACAAIAFABIAFgBIADgDIACgDIABgFIgBgEQgCgGgKgBIgJgBIgBAAIgHABIgIAAIgKgBIAAAAIgBgPIABgIIAAgHQAAgFgEgEQgDgDgGAAQgEAAgBACQgEADgBAFIgBARIAAAQIgYABQgKAAgDAAQgHADgBAIQABAMAUAAIATAAIAFgBg");
	this.shape_3.setTransform(9,7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_1},{t:this.shape_2},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape_3},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,19.9,16);


(lib.vol_neg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.5,1,1).p("AhAhFICBAAQAZAAAAAVIAABgQAAAWgZAAIiBAAQgZAAAAgWIAAhgQAAgVAZAAg");
	this.shape.setTransform(9,7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgMALIgCAAIgPAAQgLAAAAgKQAAgJALAAIAdgBIAdgBIAEABQAIAAAAAJQAAAIgKABIgVABIgJABIgNAAg");
	this.shape_1.setTransform(9.1,6.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICAAAQAaAAAAAWIAABfQAAAWgaAAgAABgLIgdAAQgLAAAAAKQAAAJALAAIAPAAIACAAIANAAIAJAAIAVgBQAKgBAAgIQAAgJgIAAIgEgBIgdABg");
	this.shape_2.setTransform(9,7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00CCFF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICAAAQAaAAAAAWIAABfQAAAWgaAAgAABgLIgdAAQgLAAAAAKQAAAJALAAIAPAAIACAAIANAAIAJAAIAVgBQAKgBAAgIQAAgJgIAAIgEgBIgdABg");
	this.shape_3.setTransform(9,7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0099FF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICAAAQAaAAAAAWIAABfQAAAWgaAAgAABgLIgdAAQgLAAAAAKQAAAJALAAIAPAAIACAAIANAAIAJAAIAVgBQAKgBAAgIQAAgJgIAAIgEgBIgdABg");
	this.shape_4.setTransform(9,7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_1},{t:this.shape_3},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape_4},{t:this.shape}]},1).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,19.9,16);


(lib.vol_mute = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AASBRQAAgIgQgQQgMgNgHAAIAAhZQAHAAANgOQAPgOAAgHg");
	this.shape.setTransform(15.6,13.9,1.2,1.201);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AgGglIANAAQABAAAAABIAABJQAAABgBAAIgNAAQgBAAAAgBIAAhJQAAgBABAAg");
	this.shape_1.setTransform(10.5,13.8,1.2,1.201);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#990000").ss(1,1,1).p("AhHBRQgCgDgDgCQgDgDgBgCQgbgeAAgpQAAgsAfgfQAgggAsAAQAjAAAcAUQAGAEAHAIQACACADACQAbAeAAApQAAAtggAfQgfAggtAAQgpAAgegbICYiY");
	this.shape_2.setTransform(15.1,14.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1,1,1).p("AAJAAQAAANgJAJQgCAFgGACIAAg5QAGADACAFQAJAIAAAMg");
	this.shape_3.setTransform(20.6,13.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1.5,1,1).p("ACWAAQAAA7gsAoQgtAqg9AAQg+AAgsgqQgrgoAAg7QAAg6ArgqQAKgIAKgHQAFgDAGgDQAJgFAKgEQAEgBAFgCQAWgHAZAAQAaAAAXAHQAEACAEABQAKAEAJAFQAFADAFADQAKAHAKAIQAsAqAAA6g");
	this.shape_4.setTransform(15,14.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAAABtQAuAAAfggQAfggAAgsQAAgpgbgeIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfQgfAgAAAsQAAApAaAeIAFAFIAFAFQAeAbAoAAgAhGBSICXiYQAbAeAAApQAAAsgfAgQgfAgguAAQgoAAgegbgAAuAaQAHgCACgGQAJgJAAgMQAAgMgJgJQgCgFgHgDIAAA6IAAAAgAhGBSIAAAAgAhLBNIgFgFQgageAAgpQAAgsAfggQAggfArAAQAkAAAbAUQAHAEAHAHIAEAFIiXCYIgFgFgAAuAagAAuggQAHADACAFQAJAJAAAMQAAAMgJAJQgCAGgHACgABAgDIAAAAgABRhGIAAAAg");
	this.shape_5.setTransform(15,14.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#00CCFF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAhLhLQgfAgAAAsQAAApAaAeIAFAFIAFAFQAeAbAoAAQAuAAAfggQAfggAAgsQAAgpgbgeIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfg");
	this.shape_6.setTransform(15,14.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhHBRICYiYQAbAeAAApQAAAtggAfQgfAggtAAQgpAAgegbgAAuAZQAGgCADgGQAJgIAAgMQAAgNgJgJQgDgFgGgDIAAA6IAAAAgAhMBMIgEgFQgbgeAAgpQAAgsAfgfQAgggAsAAQAjAAAcAUQAGAEAHAIIAFAEIiYCYIgFgFgAAuAZgAAughQAGADADAFQAJAJAAANQAAAMgJAIQgDAGgGACgABAgDIAAAAg");
	this.shape_7.setTransform(15.1,14.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0099FF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAhLhLQgfAgAAAsQAAApAaAeIAFAFIAFAFQAeAbAoAAQAuAAAfggQAfggAAgsQAAgpgbgeIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfg");
	this.shape_8.setTransform(15,14.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAhGBSQAeAbAoAAQAuAAAfggQAfggAAgsQAAgpgbgeQAbAeAAApQAAAsgfAgQgfAgguAAQgoAAgegbICXiYIiXCYgAhqABQAAApAaAeIAFAFIAFAFIgFgFIgFgFQgageAAgpQAAgsAfggQAggfArAAQAkAAAbAUQAHAEAHAHIAEAFIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfQgfAgAAAsIAAAAgAAuAaQAHgCACgGQAJgJAAgMQAAgMgJgJQgCgFgHgDIAAA6IAAAAgAAuAagAAuggQAHADACAFQAJAJAAAMQAAAMgJAJQgCAGgHACgABAgDIAAAAg");
	this.shape_9.setTransform(15,14.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_2},{t:this.shape_4},{t:this.shape_3},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_7},{t:this.shape_8},{t:this.shape_2},{t:this.shape_4},{t:this.shape_3},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_9},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,32,30.1);


(lib.Tween25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AA8gZIAAhmIjMD/IEhgzIhDg3");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AA8h/IAABmIAGgCIgBAOIAIAIIAFARIAFAIIgFACIBDA3IkhAzg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-15.5,-13.7,31.1,27.5);


(lib.menu_main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgWAoQgQgMAAgdIAAgIIAAgIIABgHIAAgGQAAgFABgEQADgFAEgBQADAAADACQADADgBADIAAAKIAAAKIAAAIIAAAIQAAAJABAHQADAJAFAEQADABAIABQAPAAAGgaQADgNAAgaIABgFQADgFAFAAQADAAADAEQAAAAAAABQAAAAABABQAAAAAAABQAAAAAAABQAAAXgCANQgDATgKAOQgEAFgGAEQgHAFgIgBQgPABgGgGg");
	this.shape.setTransform(37.7,11.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgoAtQgDgCAAgDIABgIIAAgHIAAgKIAAgKIAAgKIAAgMIgBgKIAAgLQAAgDADgDQADgDAEAAQAEAAAFAIQAaAmAaAXIAAgJIgBgmIgBgGIAAgHQAAgIAJAAQAJAAAAAeIAAAJIgBAkIAAAJQgBAIgIAAQgEAAgFgFQgWgUgcgkIgBASIABAOIAAAOQAAARgJAAQgDAAgDgDg");
	this.shape_1.setTransform(28.5,10.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgaAsQgHgFAAgTIABgXIACgXIgBgGIgBgGQAAgJAJAAQAAAAABAAQABAAAAAAQABABAAAAQABAAAAAAIANgCIALgBQAPAAAIADQAGACAAAGQAAADgCACQgDADgDAAIgDAAQgJgDgJAAIgJABIgKACIgBAXIAWgDIAOgBQAEABACACQADACAAADQAAAHgIAAIgOABIgYADIAAAMQAAAMABABQABABAGAAIAKgBIALAAIAEAAIADAAQAEAAACABQADADAAAEQAAAGgHACQgGABgRAAQgUAAgFgGg");
	this.shape_2.setTransform(20,10.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAfAmIgCgOQgDgKgEgTIgJAXIgDALIgFALQgDAFgEAAQgFAAgEgHIgDgLIgIgeIgIAcIgBANQgDAJgHgBQgDAAgDgCQgCgDAAgDQAAgKAFgNIAGgWIADgSQADgMADgFQADgEAEAAQAGABACAFQADAFADAQQACAPAFARQAGgRAGgVIADgNQADgIAHAAQAGgBADAKIADAPQADAYAGASIAFAUQAAADgDACQgDACgDAAQgGABgEgKg");
	this.shape_3.setTransform(10.9,11);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1.5,1,1).p("Ai4hoIFxAAQAxAAAAAwIAABxQAAAwgxAAIlxAAQgxAAAAgwIAAhxQAAgwAxAAg");
	this.shape_4.setTransform(23.4,10.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ai4BpQgxAAAAgwIAAhxQAAgwAxAAIFxAAQAxAAAAAwIAABxQAAAwgxAAg");
	this.shape_5.setTransform(23.4,10.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(1.5,1,1).p("Ai4hoIFxAAQAxAAAAAwIAABwQAAAxgxAAIlxAAQgxAAAAgxIAAhwQAAgwAxAAg");
	this.shape_6.setTransform(23.4,10.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#00CCFF").s().p("Ai4BpQgxAAAAgxIAAhvQAAgxAxAAIFxAAQAxAAAAAxIAABvQAAAxgxAAg");
	this.shape_7.setTransform(23.4,10.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0099FF").s().p("Ai4BpQgxAAAAgxIAAhvQAAgxAxAAIFxAAQAxAAAAAxIAABvQAAAxgxAAg");
	this.shape_8.setTransform(23.4,10.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_8},{t:this.shape_6},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,48.8,23);


(lib.general_buttoncolor = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{resetRed:1});

	// timeline functions:
	this.frame_0 = function() {
		this.play();
	}
	this.frame_8 = function() {
		this.gotoAndPlay("resetRed");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(8).call(this.frame_8).wait(2));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#D5FFD7","#61EF01","#1DA400","#004A00"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgwAAgigjQgjgigBgxQABgwAjgiQAigjAwAAQAxAAAjAjQAjAigBAwQABAxgjAiQgjAjgxAAIAAAAg");
	this.shape.setTransform(11.9,11.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FFFFFF","#EC0000","#9D0000","#480000"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgwAAgigjQgjgigBgxQABgwAjgiQAigjAwAAQAxAAAjAjQAjAigBAwQABAxgjAiQgjAjgxAAIAAAAg");
	this.shape_1.setTransform(11.9,11.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},8).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,23.7,23.6);


(lib.Copyright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAcAIIgEgLIgDAKQgEAJgEAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBIgCgJIgCgHQgGATgDAAIgCgBIgBgDIABgCQACgEACgHIADgMQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQAFAAACAIIACALIADgGIADgJQACgFACAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIADAKIACAHIADAIIABABIgBADIgDABQgDAAgCgJgAgUANIgBgIIAAgGIgBgHIgFAAIgFgBQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAEAAIAFAAIAPAAIADAAIADAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABQAAABAAABQAAAAgBABQAAAAAAAAQgBAAgBAAIgNABIAAAHIABAHIAAAEIABADIgBADIgCAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAgBg");
	this.shape.setTransform(57.3,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgMAYQgGgCAAgEIABgDQAAgBABAAQAAAAABAAQAAgBABAAQAAAAAAAAIAEACIAFACIAEABIAGgBQAEgCAAgCQAAgGgIgCIgEgCIgIgCQgDgCAAgFQAAgJAIgEIAIgDIAIgDIADAAIAEABIABADIABAEIAAADIgBAEIgDABQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBIgCgEIgKADQgGACAAAFIACAAQAJACAGADQAHAEAAAJQAAAHgGADQgFADgIAAQgFAAgGgCg");
	this.shape_1.setTransform(51,2.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgLATQgHgGAAgJQAAgIAGgJQAGgLAIAAQAEAAAGACQAGADAAADIgBADQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgDgBIgCgCQgCgCgGAAQgEAAgEAIQgEAIAAAEQAAAGAEADQADADAGAAIAFgBIAFgDIACgBIADACIABADQAAADgGADQgHADgDAAQgJAAgFgGg");
	this.shape_2.setTransform(46.6,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgDAgQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgIIAAgIIABgKIAAgKQAAAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAIADgBIACABQABAAAAABQAAAAAAABQABAAAAABQAAAAAAAAIgBAKIAAAKIAAAIIAAAIQAAABAAAAQAAAAAAABQAAAAgBAAQAAABAAAAIgCABIgDgBgAgCgXQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAQAAgBgBAAg");
	this.shape_3.setTransform(43.1,1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AALAVIgBgJIgBgKIAAgDIAAgEQAAgKgDAAQgFABgEAFQgEAGgCAGIAAAFIgBAEIABAEIAAAEIgBADIgDACIgEgCIgBgDIAAgEIAAgEIAAgMIABgMIAAgEIAAgEIABgEIADgBQAEABAAAFIABAFQAHgKAHAAQAHAAADAHQABAEABAIIAAAFIAAACIABAKIAAAJIgBAEIgDABQgEAAAAgFg");
	this.shape_4.setTransform(39.5,2.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAOAWIgDgDIgHADIgFACQgKAAgFgGQgEgFAAgMQAAgKAHgHQAIgIAJAAQAEAAAEACQAGADAAADIgBACIAAAGIgBAJIABAIIADAJIABABIAAABIgBAEIgDABIgDgDgAgGgKQgFAGAAAGQAAAHACADQADAEAFAAQADAAADgBIAEgEIgBgQIAAgEIABgFIgDgBIgCgBQgFABgFAFg");
	this.shape_5.setTransform(34.8,2.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAMAiIgCgLIgBgLIAAgDIAAgDQAAgIgDABQgGAAgDADIgHAKQAAARgBADQgBABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgBgEIABgBIAAgGIAAgHIAAggIABgHIgBgEIAAgEQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBQADAAAAAEIABAIIAAAKIAAAJIAAAFQAEgFAEgDQADgDAFABQAGAAAEAEQABAEAAAHIABAIIAAAJIACAJIABACQAAAAgBAAQAAABAAAAQAAABAAAAQgBAAAAAAIgDABQgDAAgBgCg");
	this.shape_6.setTransform(30,1.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgLATQgHgGAAgJQAAgIAGgJQAGgLAIAAQAEAAAGACQAGADAAADIgBADQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgDgBIgCgCQgCgCgGAAQgEAAgEAIQgEAIAAAEQAAAGAEADQADADAGAAIAFgBIAFgDIACgBIADACIABADQAAADgGADQgHADgDAAQgJAAgFgGg");
	this.shape_7.setTransform(25,2.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgOATQgHgFAAgKQAAgLAGgHQAGgJAJAAQAHAAAFACQAFADAAAHQAAAEgFAEIgJAEIgQAHQADAFADABQAEACAEAAIAHgBQAFgCACgCQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAABAAIADABIABADQAAAEgIAEQgHADgGAAQgJAAgGgFgAgIgLQgEAFgCAGIAOgFQAHgEADgCQgDgEgHAAQgFAAgDAEg");
	this.shape_8.setTransform(20.3,2.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAbAhIgCgHIgCgIQgCgGgDgXIgJAZIgDAJIgEAIQgBADgCAAQgDAAgCgDIgBgFIgBgEIgIghIgCAIIgGAWIgBANQgCADgDAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBIAAgDQAAgHACgLIAGgQIACgPQACgJACgDQACgDACAAQADAAABAEQADAEABAMQADAOAFAPQAFgPAFgTIABgGIACgGQACgEADAAQAEAAABAIIADAKQACATADAOIADAIIACAHQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAAAIgDABQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAgBg");
	this.shape_9.setTransform(13.8,1.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgQAUIAAgeIAAgEIAAgEQAAgFAEAAQAEAAAAAIQAIgJAKAAQAEAAABADQACADAAAFIAAADQAAAGgEAAQgEAAAAgFIAAgDIAAgDQgHAAgEAEQgDACgDAGIAAAXQAAAFgEAAQgEAAAAgFg");
	this.shape_10.setTransform(5.1,2.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAOAWIgDgDIgHADIgFACQgKAAgFgGQgEgFAAgMQAAgKAHgHQAIgIAJAAQAEAAAEACQAGADAAADIgBACIAAAGIgBAJIABAIIADAJIABABIAAABIgBAEIgDABIgDgDgAgGgKQgFAGAAAGQAAAHACADQADAEAFAAQADAAADgBIAEgEIgBgQIAAgEIABgFIgDgBIgCgBQgFABgFAFg");
	this.shape_11.setTransform(0.5,2.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgBAaQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIgBgQIgBgPQAAgEgCgDQgDABgCAEIgGAFIgCADIAAAHIgBAIIABADIAAAEQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAABIgEABQgEAAAAgLIAAgIIABgHIgBgHIAAgHQgBgKAFAAIADABQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABIAAACIgBADIAAAFQACgFAFgEQAEgEADAAQAHAAACAHQADgDACgCQAEgBAFAAQAGAAADAIIACAMIAEAYIgCADIgDABQgEAAAAgDIgCgOIgCgNIgBgGQgCgEgBAAIgGADIgGAEIAAAIIACALIABAMIgBADIgEABQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAg");
	this.shape_12.setTransform(-5.2,2.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgCAaQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIgBgQIgBgPQAAgEgBgDQgEABgCAEIgGAFIgCADIgBAHIAAAIIAAADIABAEQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAABIgDABQgGAAAAgLIABgIIAAgHIAAgHIgBgHQABgKAEAAIADABQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAABIAAACIAAADIAAAFQADgFAEgEQAFgEADAAQAGAAACAHQACgDADgCQAEgBAEAAQAIAAACAIIACAMIAEAYIgCADIgDABQgDAAgBgDIgCgOIgCgNIgBgGQgBgEgCAAIgGADIgFAEIAAAIIABALIABAMIgBADIgEABQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAgBAAg");
	this.shape_13.setTransform(-12.2,2.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAOAWIgDgDIgHADIgFACQgKAAgFgGQgEgFAAgMQAAgKAHgHQAIgIAJAAQAEAAAEACQAGADAAADIgBACIAAAGIgBAJIABAIIADAJIABABIAAABIgBAEIgDABIgDgDgAgGgKQgFAGAAAGQAAAHACADQADAEAFAAQADAAADgBIAEgEIgBgQIAAgEIABgFIgDgBIgCgBQgFABgFAFg");
	this.shape_14.setTransform(-18.1,2.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgQAUIAAgeIAAgEIAAgEQAAgFAEAAQAEAAAAAIQAIgJAKAAQAEAAABADQACADAAAFIAAADQAAAGgEAAQgEAAAAgFIAAgDIAAgDQgHAAgEAEQgDACgDAGIAAAXQAAAFgEAAQgEAAAAgFg");
	this.shape_15.setTransform(-22.4,2.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgWAeQgFgGAAgMQAAgLAFgLQAGgMAIgIQAGgFAFAAQAEAAAGACQAJAEgBADIgBAEIgDABIgDgBQgGgEgFAAQgDAAgDAEIgFAFQgKAOAAAPQAAAIADAEQACADAHAAQAIAAAGgFQAGgFACgKQgNAAgHAEIgCABQgBAAAAAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgCgCQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAABAAQAJgFAWAAIAEABIABACQAAABAAABQAAAAgBABQAAAAAAABQgBAAAAABQgDANgJAIQgJAIgLAAQgKAAgGgGg");
	this.shape_16.setTransform(-27.7,1.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgOAhIgBgDIADgIIAKgXQAFgPAHgHIABgBIgVgBIgKAAQgEAAAAgEQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAIARABIAPAAIAIAAQAFAAAAADQAAACgDADIgEAFQgFAHgFAJIgIARIgDAKIgEAKQAAAAgBABQAAAAAAAAQgBABgBAAQAAAAgBAAIgDgCg");
	this.shape_17.setTransform(-36.2,1.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AABAiIgIAAIgEAAQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgFAHAAIACAAIACAAIAAgGIgBgGIABgQIABgRQgGAEgBAAIgDgBIgCgDQAAgCAEgDIAHgFQADgEADAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAADIAAADIAAAFIAAAEIgBAPIgCAOIABAGIABAGIAEAAQABAAAAAAQAAAAABAAQAAAAAAABQABAAAAAAIABADIgBADIgDABg");
	this.shape_18.setTransform(-41,1.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgTAXQgFgJAAgPQAAgMAGgKQAIgLALAAQAMAAAGAKQAGAJAAAMQAAATgHAJQgGAKgMAAQgNAAgGgMgAgLgRQgEAHAAAJQAAANAEAIQAEAHAHAAQAJAAAEgLQADgHAAgLQAAgLgEgHQgEgFgHAAQgHgBgFAJg");
	this.shape_19.setTransform(-45.9,1.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AANAhIgDgBIgGABIgGAAIgFAAIgFABIgCAAIgBAAQgDAAgBgDIgBgGQAAgKAGgGQADgDALgHIAHgGQAEgFAAgFQAAgDgEgCQgDgCgDAAQgDAAgEACIgGAFIgDABQgEAAAAgDQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQAFgFAEgCQAFgDAFAAQAHAAAGAEQAGAEAAAHIgBAJIgEAGQgDADgIAFQgIAFgCADQgFAFAAAHIAJAAIAMgBIAHABQAEACAAACQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBABIgCABIgEgBg");
	this.shape_20.setTransform(-51.3,1.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgeABQgBgLALgKQALgJANAAQANAAAHAIQAIAIAAAMQAAAKgJAKQgKALgNAAIAAAAQgfAAABgdgAgOgPQgJAHABAJQAAALAFAFQAHAFAKAAQAKAAAHgJQAGgIAAgHQAAgJgDgFQgFgFgJAAIgCAAQgLAAgHAGgAgLAJQgFgEAAgFQAAgHAHgFQAGgEAHAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAAAQABABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAABAAABQAAAAgBABQAAAAgBAAQgBAAgBAAIgBAAIgBAAQgEAAgEACQgFADAAADQAAACAEABIAEACQADAAADgDIAEgCIAEABIABADQgBADgEADQgGADgEAAQgFAAgFgEg");
	this.shape_21.setTransform(-57.7,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.3,-7.1,126.6,16.6);


(lib.blank_gr = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00CCFF").s().p("Aj+CqIAAlTIH9AAIAAFTg");
	this.shape.setTransform(32.5,17,1.275,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,65,34);


(lib.Back = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(3,1,1).p("EAnJAWlMhORAAAMAAAgtJMBORAAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FEDB4E","#FFFFDD"],[0,1],-0.6,-128.4,0.6,128.5).s().p("EgnIAWlMAAAgtJMBORAAAMAAAAtJg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-251.9,-146,504,292);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AggAAQgMAfgwAiQgxAjgmAAQgKAAgKgBQhJgIg7hAQgDgDgEgHQgEgGgFgKQgJgOgKgWQgCgFgDgGQgCgGgDgGQAAgBgBAAQgXg3gGgcQgDgKAAgHQAAgDABgDQAAgDABgDQABgPAGgQQAHgQAIgHQAHgHAHAAQgFgKgBgNQAAgBAAgBQAAgDADgOQADgNAFgVQACgIACgIQABgEABgEQAHgQAOgPQACgCACgCQAIgGAJgIQADgCADgDAF6EwQAEAFAEAGQAMAVAAAEQAHAkAEAL");
	this.shape.setTransform(108.8,52.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AhTDrIAkAAQAdAFBKAPIA7gEQAZAABSgKQAagCAfgMQAQgHAVgJQAcgKAWgcQAJgNAJgRQAYgwAAguQAAglgNgiQgJgYgmhKQgVgqgdgbQgUgUgOgEQgCABgCABAA6nlQACACABADQACAFACAFQAhBKBIBZQAlAvAvA1QAGAGAGAHQhmA8g2AUQgRAGg9AMQgMADgOACQhIAPglADQAUACAQAJQATAKAOARQAEAHAEAGQAXApAABKQAAAogRAdQgDAEgPATQgJALgMAOQgCADgCACQgKANgbAGQgdAIgwAAQgxAGgMAAQgNAEgFAAQgugJgbAAQgDAAgCAAQgIABgHAAQgNAAgHABQAJAGAJAJQAEAEAFAFQALAMAKARIAkgFQADAABFAPQAPADASAEQBuAWAxAAQDMAACvggQCrgfA3gxQgFgPgFgRQAJAHAKAJQACACACACQgBABAAAAQgFAGgHAFQAHAUAHASQADAIAEAIQAjBSApAlQggADhOAOQgTAEgSADQgmAGglACQgaADgaAAQgMAAgLAAIgUgBIgYgDAGaCXIABAAQACgBADgBQAKAAAgAIQA5AAAMAEQAPAFAdAYQABACACABAGZCYQgHAEgPAHAHCFlQAJgPAagPQAdgSAOAAQACAAADAAQAGABALABQAFAAAGABQACABADADAIVE1QgRAMgNAIQgkAZgDADAGUHVQgVAngLAKAHwHZQgWAWgSAbAIVE1QALgHANgJAKyGQQgBgBgBgBQgDAAgEAAQADADAEACQALAKAPAHQAZALAiAEQALACAMAAQgXAvhUBJQgKAJgLAJQg2AqgfAYQgJAIgHAFQgJAHgHAGQAVgHATgHQDkhPAIAAQAEAAAGAAQAHABAJADQgEgKgDgKIADAAQABAAAEABQARAEBBAGQASACAQADQArAIAQAQQgEADgHAQQgJASAAAKQAAAEAAAHQABAQADAlQAIAAAsgHQAJAAAtAPQAGACAIADIgEAHQAAABAHAaQACgBADgBAKCFNIAPAAAMxG2QgBgEAAgEQAAgCAAgCQgBgJACgIIgNAAQAAAHgCAIQgCAGgEAHQAFABAFAAQAFAAAGAAQADAAAEAAAJhHKQgFAEgzAoAqV1gQAGABAFAAQAAgZAbgFQAAAAAGAAQAEAAAGAAQAIAAAMAAQAIAAAJACQALADAOAEQACABABAAQADAAACAAQADAAAEgBQAJgCALgFQACgBACgBIAAAAQAEAAAQAIQAEACAEACQAAAAAVgFQACAAADgBQAHAAAFACQAFABAEACQABABABABQAFAEABAFQAEgGAOgGQAEAAAGACQAJAEAMAHQABABABABQAGADAFAEQAFAAAOgCQAOgCAYgGQAKAAAJAKQAHAHAGAMQAAABAAAAQABAAAAAAQAAACABABQAJAQANAGQABAAAAAAQAIAEAKgBQAIAAAGABQAgAGAGAnQABAKABAMQACARAAAVQALgGAJAFQAHAEAFAKQAKASgCAPQAAAFgCAFQgBADgBADQAAAFABAGQACAMAHADQAAABABAAQAHAEAHAEQAMAJAJAKQAAACgFAVQgCAIgDAKQAAAOARARQADACADADQAXATAAAKQAAAEgCAMQgBAHgBAIQAAAKAFAaQABAHACAIQAAAIAJANQAHAMAAAJQAAAMgIAOQgSgIgKgCQgLAvgTAAQgGAAgGgDQgIgEgIgJQgMgRgCgCQAAAXgKANQgBABgBAAQgIAKgJAAQgBgBgBAAIAAgBQgTgKgRAAIAAAAQgFAAgHASQgIASgQAAQgMAAgLgOQgDgEgDgGQgCABgCABQgFAEgFAIQgEAIgMAAQgHAAgFgEQgDgDgCgGQgIgJgBgFQAAgBAAgBQADgFADgFQAKgQAGgLQACgCABgCQAJgQAAgFQgUgXgCgLQAAgBAAgCQAKgwAAgEQgOglAAgRIACgIIAEgWQgDgEgCgEQgDgFgBgEQgBgEAAgEQACgNABgJQADgSAAgGQAAgBAAgBIgCgEQgFACgDgBQgKAAAAgNQADgGABgHQACgFAAgGQAAgDgGgFQgCgBgCgCQgKgFAAgJQADgIABgHQAEgLAAgDQAAgFgMgGIgBAAQgLgGAAgDQACgFABgFQABgCAAgDQAAAAAAAAQAAgIgBgBQgCgCgHgBQgDAAgFgBQACgEABgEQACgIgGgFQgCgBgDgBQgCgBgCAAQgGgIgIgGQgBgFgBgHQAAgBAAgDQgBAAgBAAQgEAAgDgBQgPgDgEAAQgBABgBAAQgXAFAAAAQgMAAgBgJQAAgBAAgCIAEgGAsxsOQgGgGgDgFIAAAAQgCgDAAgCQARgWABgQQAAgCAAgCQAAgFgMgMQgMgMAAgGQAAgGAJgJQASgUADgFQgJgEgFgEQgKgHAAgGQAAgHAHgIQAFgHAIgHQAFgEAEgDQABgBAAAAQAKgKAAgEQgJgEgHgGQgMgJAAgLQAAgFADgGIAAgBQABgBAAgCQAFgHAIgIQADgDADgDIAUgPIADgDQAAgBgDgCQgDgCgHgCQgHgCgDgEQgDgEAAgGQAAgHACgGQAGgNAQgFQAYgHAAgOQAAgGgGgKQAAAAgBgCQgFgIAAgFQAAgRATgLQADgCACgBQADgCACgBQAJgIAAgFQgCgGgBgFQgBgDAAgDQAAgHAGgLQAHgMAHAAQADAAADABQAEACAEABQADAAAGgRQAAAAAAgBQAFgNAGgEQABAAAAAAQACgBABAAQACAAACACQADACAFAEQAGAHAKABQADAAADAAQACAAAFgCQAIgFAQgLQADAAADABQAKADAPAJQABABABAAQAEAAALgGQADgCADgCQABgBABgBQASgMAGAAQABAAACABQADABACACApgxuQAEgMAAgHQAAgZgKgRQgKgQgOAAQgaAAgUAYQgIAMgFALQgFAMAAAMQAAAVASAUQABABABABQATAUAPAAQAUAAALgQQALgOAFgaQAFAAAEAAQAKAAAKgEAmnx3QAAgBAAgBQAAgWgQgSQgQgSgUAAQgQAAgUAUQgDAEgDADQgBABAAAAQgDAGgFASQgBAGgBAGQABACACACAm8xEQgDgBgDgCQgBAAgCgBQgMgGgEgKQgCgFAAgGIABgEIAAgCQgBABgBAAQgRADgOAAQgFAAgFgBQgJgCgIgFQABgDABgDAnWxpQAIgBAJgDQAMgDAOgFQACgBACgBAoGyXQgNAQAAAMQAAADADAFAoax1QAEAFAEADQgBAHAAAEQAAAMAWARQAUAQAKAAQAEAAAEAAQAMgCAKgIQADgDACgCQADgDACgDQABgBABgCQAMgQABgTQABgEAAgDQAVgIAXgMApgxuQgBAEgBAEQgDAJgGALQgCAGgDAFQABAAAAAAQADABADABApZxtQgDAAgEgBAq0yRQADADACACQANALAbAJQAFACAEABQAOAFAMACQADAAABAAApwxHQAAABgBABQgCADgCACApwxHQgDgBgDgCQgKgGAAgJQAAgIAKgMApIwlQgGAFAAADQAAAWAbAAQAHAAAQgIQAOgHADgDAntvIQAOABAGAAQAFAAARgIIAKAAQgEAKgHAKQgGAHgIAIQgIAJgNAJQgkAdgUAAQgwAAgTgTQgQgQgYg/QAOADAMABQBdAPAmAEgAm8xEQAEABADAAAkxs1QABACAAABQgIAQgBAAQgGAAgEACQAAAGABAFAsxsOQAMgPAPgYQAeAlAGAAQAUAAAAgYQAIAEANAKQANAIAJAAQAFAAAOgcQAEAOASAOQAIAAALgRQACgEADgFIAEAEAo1sjQANAZAKAdQgNgDgSAAQhNAAg4ArQgrAhg5BUQg4COgaAyQgTAjgbApQgQAegJAdQANACAJAEQAcAMAxAHQAgAEAnAXQAGAEAGAEQAPgiAUgcQAJgMBAhOQAAgDABgDAoertQALADAIAEAoertQAIAXAHAaAp1n2QgHACgEABAp1n2QAAAAABAAQASgDAnAAIAsAEQAKAAAogDQAAgCAAgCQABggAEgPQACgIANgYAkInrQgfgHgTgKQgKgFg0AAQg5AGgkACQgEABgEAAQAAAJAAAJQAAAvAQAUQAJAKAPAKIAAgGApYo1QgNAWgQApAj7npQgHgBgGgBQgEANgDAKQgCAIgBAGQgBABgBABAkInrQACgIADgKQAXhEAHgYAk+r/IBVAAQABABAAAAQALAFADAAQADAAAdgIQACAAAdAGQAIAAAagKQAEAAAqAYQAtAZAJALQAjAxAAA7QAAADgBAEQgCAPgOAeQAAAFgFAjQABgBACAAQAGgCAGgBQALgCAHAAQAEAAAPAEQAIABAKACQgKgMAAgOQAAAAAMg1QABgGASgHQARgHAGACIAAAaQgMAqggACQAPAAA0gOQAOAAAFAZQAAAXguACQgYgFgQgEQACAEAEADQgBAKgJAKQgKANgWAMQgTALgNAIQgVANgKAFQgBADgBADIAAAAQgUBUhQB5QggAvgaBEQgEAKgDAIQARABARABQANABAMABIAYABQAJAAAJABQgLABgIAAQgMgCgLgBIgZgBQgWABgHAHAgIoBQgBACAAACQgBAGgCAFQgEASgIAWQgFARgIASAgIoBQgPAEAAAAAqV1gQgFACgGACQgRAGgbAGQABgJAIgFQAHgDAKAAQAMAAARABQAEgBADgCArM1QQAAAEAAADQgKgBgIAFQgCABgCABArM1QQgCABgDAAQgIACgFADQgKAGAAAKQAAAFAEAMQgBACgDABQgHACgPADQgMADgRACQgYAEgLADQgKADAAACQAAAKAUAXQAAAGgYAEQgFABgEAAQgIACgGABQgKAEgFAEQgFAGAAAWQAAAMABAQQgBAJgLAEQgHADgKACQgEAAgEAAQgNABgIADQgOAEAAAIQAAAFAFAJQABACABACQAHAMAAAGQAAACgZAKQgCABgDAAQgeAMAAASQAAAEAHANQABACABACQAFAIACAHQACAFAAAEQgIAAgUAHQgDABgDABQgBABgBAAQgPAFgFAFQAMAEAIAKQAFAFADAHIgFAHQgGAHgNAOQgHAHgIAKQgGAGgHAHQAAADALAEQAPAFAIAIQAAABgWAPQgQALAAAHQAAAJALAGQACACADABQAQAIAAAGQAAAHgHAFQgDACgFACQgWAJgJAIAwmsoQAGALABAAQABACACAAQAAABAAAAQAGACAJAAQAOAAAXgQQADARAAAUQAAACAAABQABAOANAAQAHAAAGgFQAEgDAEgFQAJgNANAAQAEAGACAIQAEAJACAKQABAHAJAAQADAAASgTQASgTAHAAQADAAAKALQAKALAGAAQAEAAAIgIQAGgGAIgMQADAEAEAEQgPAHgGADAm3jIQgOg+gMgMQgagbgsgLQhCgIgYgHQgmgLgBgyQAAgBAAgBQAAgIAIgbQACgFACgHQAEgLAFgOQAAgCABgCQAHgTAGgRAu/kJQgQgDgWAAQgGAAgHAFQgGAFgMAAQgZAAgJAEQg4AZAAATQAAALARAMQghATAAAGQAAALATAEQABAAABgBQAKgHAPgIQAdgOAZgHAwyg1QABgHADgHQALgjAWgMQADAMAUAJQAVAJATAAQA+AABfgEAqQiRQgugSgUgJQgCgBg1ggAw4gNQABAsAVASQATAQArAAQBAAABQgMQA1gIBrgtIADgHQgjgYgUgLQgogbgdgRQgCgBgCgBQgQgKgNgGAxZhrQgNAMAAAJQAAACA0AfQgEAPgBAOQAAABAAABQgBAEAAAFIAAAAQhMALgQAdQgSAhgIAeQgBADgBAEQgGAXAAAWQAAArBFB/QA4BmBJBuQAdAqAvBSAxbiTQgPALAAAKQAAAGAJAIQADACAFADQAAAAAAAAQAHgHAKgHQAdgVAngQAwygOQgDABgDAAAxNi7QAFgDAGgEQAkgTAUgJAq9DVQgPg5AAgaQAAgOAkgnQAggiAWgGQgkgbgbgRAqjD5IgMgIQgBABgCABQgBAAgBABQgBgCAAgCQgEgOgEgNQAJACAEAAAtYCfQAIAEAOAGQAdAOANAAQAJAAApAQQAbALAOADAq0D0QABAEABADQAEANAEAOQAFAQAEAOQABADABADQAcBUAVAiQALAQARAdQABABAAAAQABABAAAAQAeAyAyBWQAFAJAFAHQA0BYAcAiQABACACACQAiBcAaAuQACAEAGAKQAFAJAJAOQABgEABgDQANAOAbAKAtgCbQABAAAHAEQAWArAqBWQAXAtANAiQACAEABAEQgDALgEAMAu0EJQAAgcAEgEQAHAOAWBCQAYBBAbAbIAAgMArxF3QAFALADALQAHAVACAPQAGAoAgCcQABADAAAHQABAJAAAPQAAAWAIAUQADAHAFAPQAGAPAJAZAq0D0QgaATgQAzQgIAYgLAlAh3mqQAAAIgIAXQAIgBAEAAAidlEQglAEgNAAQgCgGgcAAQg4AUggAAIgIgEAh/mLQgEAOgIAVQgGAXgMANAk8kYQARgGAggFQA3gIAfgJQAPgEAJgMAlDlUQA9gYBJgSQAqgKAUgDAh3mqQgSgCg/AMQhCAMg1AQAm3jIQAigMAAgQIgEg2IAAgGQAAgtAJgqQAAgCABgDQAHghArgLQACgBACAAQCCghAqAAQA2AAAAAgAm3jIQAAABAAAAQABAEABADAk5kgQgCAEgBAEAmNheQABgCAAgDQATg3AMgSQAOgXAOgfQAMggAJgWQgHACgEACAqQiRQAHACAHADQASALAoAfQANAGBKAUQAHADAIADQAQgQAygJQAKgBAJgCQgRAygJAMQgJgDgVgPQgPgJgOgHQgDADgCADApiAnQgBgEgFAAQgEAAgGACQAHAFAHAFQAqAZBTAbQAKAEA2AaQAVAEAPAHQANAHANAAQAiAAAZghQARgVAshUQAKgSAbhGAlthjQgIABgYAEAm3jIQgBAAgCABQgXAHgkAGQhZANhCAcAlBEqQACADABADQACAEACADQAEAGADAHQAaA1ATBSQABADAAADQACAIACAJQADAOAHAYQAEAQAGATQAJAgAOArQAZBSAHAwQABAEgCAEApSHdQgVgCgNgFQgZgIgCgdAnfFFQgEAXBECaAGwJSQgMALglAJQgVAFgfAEQheALhDAKQgzAHgjAHIgUgEASBO2QAAAAAAgBIAIgYIgQAAQgOAOgVAjQgZAoAAALQhIhAgTgLQgBAAAAgBQAAABAAACQAIAZgHAgQgHAhgOAAQgdAAgXgSQgTgPgggqQgBgBAAgBQgQAMgBAmQAAAQgFAOQgIATgSAOQgNgagGgZQgCgLgCgGQgBgHAAgBIgNAAIgRATIgeAhQgIgKgHgeQgHgegGgGQgVAUgOAgQgIASgOACQgBAAAAAAQgDAAgCgBQgMgBgMgHQgTgMgSgaQgEgHgEgHQgBAGgEAHQgMATgsAkQAAAAgBABQgHAFgIAHQgWAAgTgTQgNgOgMgNQgEgEgEgFQgNgNgNgNQADAOgEAdQgFAcgGAFQgFgEgLgxQgLgygFgEQgrAegJAGIAAgUQABgFAMgdQADgIAEgKIgIADIgEAJQgBABgCACQhsBpgIAHIgBABQgOAAgZgXQgIgGgIgJQgegdgrg2IAAAJQAEAAAEA8IAAAUIgMAAQhVg4gegcQgCgCgCgDQAAAFAAAEQgCAlgQAjQgBACgBACQgCADgCAEQgCgEgCgDQgBgCgBgCQhBh1gbioAkJT7QAIgFAMgFQAOgGATgGQACAAACgBQATgFAQgDQACAAAggCQABAAAMACIABAAQAWAEA8AMQAVAAAVgPQAUgOADgRQAAgCAAgCQAAgFgKgTQgLgUgVgmQglg/gTggQgEgHgDgFAmdL5QAEACAAAEIAAABQAAgBgBAAQgEgEgFgGAqCLpQAEgDA7AMQAyAKAOgGAuyQ8QgEgKgTgKQgQgJgFAAQgfAAgTARQgSAPAAAXQAAALAEAJQAKAWAgABQADABADAAQAEAAAugGQAagEAmgEQAlgFBTghQAGgCB7gaQB6ggAAghQAAgPgOgTQgHgJgKgLQgGgEgFgFIAEgBQAIADAGACQAQAFALADQAmALABAAQAKAAAHgLQAGgIAEgMQAJgZAAgTQABAAALAKQALAJATAQQAnAhALADQAGgEAEgNQAAAAAAgBQABAAAAgBQACgIABgGAozOyIgQADAozOyQgbgYgKgJQgXgVgehEQgdhAAAgXIACgKAkxPZQgEgHgGgJQgFgJgFgIQgHgLgFgJAkxPZQABAAAAgBQAAgDgBgCAkxPZQACADABACQAOAZADAKAmNTsIgKAAQgSAbAAAIQAAAVAcAGQAMADATAAQAhAAA5gjQA7gjAagDAprTQQgWABgSABQgDAAgEAAQgSAAgSgUQgEgEgCgDQgKgMAAgGQAAgdAYgQQAJgGAIgDQAOgFAOAAQAPAAARAAQAVABAXACQAOAAASgEQAbgGAhgNQAEgCBIgsQBTg0ARgbAprTQQAEgZARgHQAOgFAugNApeTQQgGAAgHAAQgBAGAAAHQAAAHADAFQABACABACQADAFAFADQAKAFAQAAQAOAAAOgFQgCgDgCgDQgFgIAAgLQAAgOAMgNQAQgPAbAAQAIAAAMAFAopT1QAJgCAJgFQADgBADgBAnuUGQgBgCAAgCQAAgBAAgBQAAgIANgRQAPgUAOAAIAGACAnuUGQADAAAEAAQAAAAABABAopT1QAQASArgBQACAJANAHQAMAFAIAAQAEAAAJgCQADAAAEgBAibQeIAAgJQADAEAJALQAIAPAAAbQAAAPgRAMQgKAGgNAHASBO2QgBAcgDAAIAAALQAMgMAyglQA1gmAJAAQgNAZgLAjQgIAbAAAFQAAATBdCVQBeCYAPAfQABADABACIAFACIADACIgEAAIgNAAQgGABgGACQgeAGghAHQhQAPhQAAQiggIgKAAQhOAIgKAAQgcAAg7gPQg7gQg1AAQl3AAisAaQhgAOgmADQhbAIibAAQhuAAjTgrQhdgUhMgLQgWgDgUgCQglgFgggBQgfgDgbAAQgqAAhRANQgDABgDABQgVADgRACQgzAIgOAAQgUAAiehbQhwhDg0gaQgCgBgCgBQAcggAYgdQB/iYAmgzQAMgPADgGIAIgFQACAFACAEQAWAvAeAAQALAAANgVQABgBAAgBQAEgGAEgIQALgXADgNQABgHAAgDIAEgIQAAALAPANQAGAGAIAFQABgCABgCQACgEACgGQAEgKAFgMIAUg3QAXgwA/hCQAqBJAcAhAuYKWQgBABgBABQgBgBgBgBQgBgDgCgCQgCgFgDgEQAFAFAEAGQACACABABQAAAAAAAAQAEgEAEgEAsYOZQAFgCAFgBQAKgEAIgDQgHgMgGgMQgIgTgbgnQggg4gbgoQgcgsgVgbAsYOZQgJgGgLgJQgBgBgBgBQgigbgLgIQgDgDgCgBQgBADgCACQgSAcgTAAQgUAAgQghQgEgJgEgLQgDACgIAHQgNAMgcAcQgagNgRgMQgFANgEADAydQpIgBAAQgigRAAgZQAAgLAHgFQACgBACgBQAEgBAFAAQABAAABAAQAOAAAhAKQACABACAAQAGAAAIgBQANgBATgEQAagGAlgJQANgEAPgEQAWgGAZgHQAegJAbgIQAWgHAUgGQAkgLAcgJQACgBACgBQABAAABABQARAKAOACAxYRSQgBAAAAgBQgNgMAAgVQAAgbAKgHQAKgIAeAAQAXAAAJAFQAHADALAQAydQpQgBgDAAgDQAAgCAAgBQACgWAbAAIAXAGAwsRjQgBgBgBgBQgdgCgNgNQhBAHgEgwAyZQnIgEACA2MSHQgIAJgIAJA2sR5QALAEAVAKAqXJxQATAEA9AdAqbOJQAFATAXA6ARwL0QgbAQgoANQhFAYhOAQQg7ANgOAAIAMgJQACgCACgCQAjgjAfghQARgSAQgRASBO2QAAAAABgCQACgCACgDQAGgIAEgHQAFgJAAgHQAAgUgOg2QgDgHgBgIQgCgIgCgJQgKgfgFgTANFIyIAJgEQgZhPgEgpAIZKmIgEgEQAJgEAJgDQgHAGgHAFgAH0LKQAKgMAbgY");
	this.shape_1.setTransform(145.3,142.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CCCC99").s().p("AoKDrQhcgThNgLIAHgBQgGgCgFgEIgJgHQgTAHgKABQglgEgggCQAgACAlAEIgGABIg/gHIghgDIgYABQgrAAhQANQBQgNArAAQgVACgWAEQghAGgvABIgKAAQgSAAgRAHQgzAIgNAAQgVAAidhcQhxhCg0gaIAwg/IAyhAQBRhoAjgjQARgRAGAAIAEAAQALACAHAKQAHAKgBALIAHABQAJAAAjgIIADAAIgBgCIAHgOQALgXADgNQgDANgLAXIgHAOQgHgLAAgJQAAgLAIgJQAIgJAMgBIACAAQACAAAQAGIAMAGIAFACIgCAEIACgEIAWAIQAKADAGAAQAAgIAHgJQAJgMAPAAIAMAHIAUAKIAmAUQAGAAAdgOIADgCIAEAAQAwABAAAfIgBAGIgCgCIgtgkIAtAkIACACQgBAGgDAFQgEAHgJAFIgfAOIgqAMQgZgCgoANIgmATIgdAIQgOgLgDAAQgCAAgYAQQgKAGgJAEIghAGIgSAAQghgLgNAAIgCAAIgGgDQgKgEgFgBIAIAMIAAABIAKAOIgBAIIASAaIAEAHIACACQAWAkAWABIASADQAUAEAXAMIACABIAOAHIAEACQAYAOAOAHQAMAFAFAAQAEAAAkgLQBEgUC5g7QA0gZBNgOQAUgEAHgGQAIgIAAgVQAAgHAEgHQAEgIAKgHIABgBIACgBQARgMARAAQAGAAAQALIACACQAIgVAIgQQAHgMAGgHQAKgMAJAAQAkAAgNAsQAPABAJATIAGgBQAHgBAKgFIACgBIAAAAQAHAAAHAEQAMAIAIAUIACAEIgBACIgKgQIgLgSIALASIAKAQIABgCIACAGIgBAAIgCgEQgSAbhTAzQhIAtgEABQghANgbAFIgTACIg5AAIgfgBQgPAAgNAFQgNADgIAFQgWAOgEAmIAPAMQAVAQAcALIAQAGQATAGAHAMIACADQACAFAAAEIAHgBQAWgEAbgCIAWAAIACAAIAmATIAIAEIgHABIgBgFIABAFIAHgBIACABIAnATQAkAQANABIACAAQBMAAAtgjIAdgWIACgCQAOgIARgCIAMgBIAJAAQAqgBAYgIIAAAAIBSAQQAVAAAVgOQAUgOADgRIAEgKIgNgSQgKgVgXgmIg4heIA4BeQAXAmAKAVIglgzQg0hFAAggIAAgBIgBgPIAAgDIAAgEQAAgSACgQQAEgaAMgNIAFgEQAJgHAOAAQAJAAAeAiQAYAcANASIAOgGQgIgeAAgOQAAgkAdAAQAWAAAUAwQAHATAIAZIAFASIALgDIALgEQAEAAAZAaIApguQA/hEAHAAIAFABIAIAEQAGAFAHAJIAHgGQAHgFAIAAQAjAAgPAtIADAGIAJgGQAIgGAIAAQAaAAAAAhIgagaQACAGAAAIQAAAMgDAQQgFAcgGAGQgEgEgMgyQgLgygFgEIg0AkIAAgUIANghIgNAhIAAAUIA0gkQAFAEALAyQAMAyAEAEQAGgGAFgcQADgQAAgMQAAgIgCgGIAaAaIgBAJIAAACIAJgCIAKgDQANAAAYALQAcAMAGAOIAAAAIABgCIASgbQAUgZASgDIAEAAIAJABQAWAFAPAhIAFAPQAGgEAMgBIAGAAIABgBQAMgEAFgRIABgDQACgMAEgHQAFgLAKgEQAFgUAQAAQAWAAADAYQACAMgCARIAHADIAXgHIAfgLIACAAQAXAAAFASIAAAXIAAABQAMgDAHgEQAJgGABgHQgEgQAAgGQAAggARgLQAHgEALAAQAdAAAGAZQAHAcAXAIQAEgGAPgpQAJgQAMgJIACgBQAQgLAVAAQAbAAAGAXQADANABATQAggMAMggQAIgaAjAAQAGAAAGADQgDAHgHAJIgDAEIgCADIAAgBIAIgYIgQAAQgNAOgWAjQgZAnAAAMQhIhAgSgLQASALBIBAQAAgMAZgnQAWgjANgOIAQAAIgIAYIAAABQAAAbgEAAIAAAMQANgNAxgkQA1gnAJAAQgNAZgLAkQgIAbAAAEQAAATBdCVQBeCXAPAgIgTALIg+ANQhQAQhRAAIiqgIQhOAIgKAAQgcAAg7gQQg7gQg0AAQl3AAitAaQhgAOgmAEQhbAIibAAQhuAAjTgsgAmADHQAhAAA5gjQA7gkAagCQgaACg7AkQg5AjghAAQgSAAgNgDQANADASAAIAAAAgAnxCvQAMAGAIAAIANgCIgNACQgIAAgMgGQgMgGgDgJIgEAAIAAAAIgBAAQgmgBgPgPIgBgBIASgHIgSAHIABABQAPAPAmABIABAAIAAAAIAEAAQADAJAMAGgApWCTQANAAAOgEIgEgHIAEAHQgOAEgNAAQgRAAgJgFQAJAFARAAIAAAAgAkHCLQAOgHATgFQgTAFgOAHgArQBYQATATASAAIAGAAIgGAAQgSAAgTgTIgGgIIAGAIgAwGAbQgggCgKgVQAKAVAgACgAqUg0IiBAcQhUAggkAFIhAAIIBAgIQAkgFBUggICBgcQB5ggAAghQAAgOgNgTQANATAAAOQAAAhh5AggAxAgEQgcgCgOgNIgBgBIABABIgPABIAAAAIAAAAQgwgBgGglIAAgEIAEgCIgEACIAAgHIAAgCIAAACIAAAHIAAAAQgigSAAgZQAAgLAHgEQgHAEAAALQAAAZAiASIAAAAIAAAEQAGAlAwABIAAAAIAAAAIAPgBQAOANAcACgA1qgcQB/iYAngzQgnAzh/CYgAMQhjQAGAZANAaQASgOAIgTQgIATgSAOQgNgagGgZIgEgRIAEARgAG5hKQAUASAVAAIAPgLIgPALQgVAAgUgSIgZgbIAZAbgAHyhFQAsgjAMgUQgMAUgsAjgALAhwQAHAeAIAKIAeghIgeAhQgIgKgHgeQgHgdgGgHQgVAVgOAfQgIATgOABQAOgBAIgTQAOgfAVgVQAGAHAHAdgACuhMIABAAQAJgIBrhpQhrBpgJAIIgBAAQgNAAgagWQAaAWANAAgAOHhmQAXASAdAAQAOAAAHghQADgOAAgOQAAgPgEgOQAEAOAAAPQAAAOgDAOQgHAhgOAAQgdAAgXgSQgTgPgggqQAgAqATAPgAJchVQgTgLgSgbQASAbATALgAAqhsIAMAAIAAgUQgEg8gEAAIAAgIQArA1AeAeQgegegrg1IAAAIQAEAAAEA8IAAAUIgMAAQhUg4gegcQAeAcBUA4gAhfhzQAQgjACgmQgCAmgQAjgAnxicQAKAAAIgMQgIAMgKAAIgmgLIAmALIAAAAgAlxigQAGgEAEgNQgEANgGAEQgLgDgmghIgegaIAeAaQAmAhALADIAAAAgAx1jIQALAAAMgWQgMAWgLAAQgeAAgWgwQAWAwAeAAIAAAAgAuZjkQASAAATgbQgTAbgSAAQgUAAgQghQAQAhAUAAgAv5joQAbgbANgMQgNAMgbAbQgbgMgQgMQAQAMAbAMgAwtjwQADgDAGgNQgGANgDADgAwkkAQgJgGgGgGQAGAGAJAGgAWYDjIAAgCIADACgAiPB1QAagIAYAAQAUAAAOAHQAPAGAMAAQAVAAAPgiQgDARgUAOQgVAOgVAAIhSgQgAAEBYIAAAAgAqaADIAfABIgYAAQgVABgOADQANgFAPAAgAnzgQQAEgBBIgtQBTgzASgbIACAEQiBBygcAJQgmAMgsADQAbgFAhgNgAxqgTIAAAAgAyvg8IAAAAgAGYhuIAAAAgAx7hvIAhgGQgOAGgNAAIgGAAgAy4h3IgFgDIACAAQANAAAhALQgggCgLgGgAxah1IAAAAgAy9h6IAAAAgAwciEIAdgIQgVAKgFAAIgDgCgAlAiIIAAAAgAv/iMIAAAAgAuYiqIAqgMIghAOIgJgCgAtui2IAAAAgAs+jbIAAAAg");
	this.shape_2.setTransform(147,255.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#56453A").s().p("AmgFNQgOAAgMgMIAAgDQAAgTgCgPQgXAQgOAAQgKAAgFgCIAAgBQAAgFAMgTIgGgGQAIgFAAgGQAAgHgQgHIgGgDQABgJAEgEQAJgJAmgQQgSgRgGgNIgMABIgKgLIAAgFQACgNANgEIgPARIAPgRQAJgDAOABIgEgTIAGgGQgEgHgEgGIgBgUIAAgEIACAAIgCAAQACgWAYgQIACAEIAHAPIgHgPIgCgEIAEgCQAWgNAGgMQgCgFAAgEIABgGIgEgFQAagKAAgBQAAgGgHgMIgDgFIAOADIgEgdQAIgCAMgBIAIgBQADAPAIAaIAAACIgEABQgZAEgIAFQgPAIAAATQAAAGAJAEQALAFAHAVIgVAFIAAgIIAAgCIgMAJIgEADIAJgBIgeAIIAAAAQgbAGgGANQgBADAAADQAAAaA1AhIgTAWQgKANAAALQAAAGALARQgUAQgJALIgBAAIgGAJIAAABQgCAEAAAEQAAARATAAIAHgFQABAAAAABQABAAAAABQAAAAABABQAAAAAAABQAAACgDAFQAIgCAMgBQAigEACgMQgJAFgIAAIgSgCQgDgBAAgIIAbgVIAEgCIAAgCQAdgYAAgGQAAgTgegDIABgCQAcgVAAgOQAAgLgTgMIgBgBQgFgVgCgKQAbgHAQgHQgDAHgBAHQgBALADAaQAAAQgcAgQAAADANAQIAAAAQAbgLACgIIAfAMIgmAiIAAAAIAAgEIAAgCIgIAEIABADQAAAFgEAGQgIALAAAJQAAAEAHAIQgBALgCAFQgJARgeANIgFABIAUgDQAMALAAACQAAAHgGAEIgGgOQgNAAgKANIgHAIIgCAAgAmXFFQAKgNANAAIAGAOQgLAHgZAAIAHgIgAm6FBIgHgJQgGgKgDgGQgQASgGAAQgFAAgDgCIgCgBQgDgCgBgDQgCgDAAgFQAFACAKAAQAOAAAXgQQACAPAAATIAAADIAAAAgAkyErQgFgJgBgFIAEAAQAhAAAAgPQAAgJgPgEIgFgCIAUgYQgVgDgDgNQAIgFAKgEQAVgJAAgQQAAgFgFgGIACgBIASgOIgVgOQAFgHAJgHIAIgHIgIAHQgJAHgFAHQgNgKgFgIIAZgQQAHgFADgGQAEgHAAgIQAAgFgDgEIAMAKQALAJAAAHQAAAQgRAFQAKgJAAgEQgKgFgHgFQAHAFAKAFQAAAEgKAJIgFABIADAAQAKABAJAJQAHgIARgIIAEALIgDAFQgKADgMAVQgMAUgBAKQgQAMgFAFQAUAMAAAOQAAAFgSAYIAAgDQAAgFgMgMQgMgMAAgGQAAgGAIgKIAWgYIgPgJIAPAJIgWAYQgIAKAAAGQAAAGAMAMQAMAMAAAFIAAADIgDAEQgVAbAAAGQAAAKAIgEIAAABQgGAOgMAAQgKAAgIgPgAFYEaQARAAATALIAAAAQAAASgRAAIgTgdgAEeEwIgHgKIgEADQgSgOgDgEIgDgEIgCgEQgDgIAAgMIACgFIgCAFIAAgBIAAgFIACABQAOAJAXALIAJAQQAAAKgHANIgBgBgAETEpIAEgDIAHAKIgLgHgAnwEqIAAAAgAGSEeIgBgCIAAAAQgDgFAAgFIAOgzQgYAHgFAAQgPAAgIgPQgGgLAAgGQAAgKAQgjIACgEIgHAfIADAPQAGANARAAQACAAAegPIgBADQgKAUAAARQAAAHAEAIQAIANAPAAQAFAAAFgFQgEAOgEAJQgIgEgIgIIgOgTQAAAWgKAOQAKgOAAgWIAOATQAIAIAIAEQgJASgJAAQgOAAgHgLgAFYEaIgCgFQAEgEAEgIQAIgPAAgJIgBgHQAXAlAAAWQgTgLgRAAgAjREMQgRgGAAgNQAAgEARgWIABgBQgQgGgDgHQAIAHATgDQgOAMAAAVIABALQAEALANAAQAPAAAGAGQAEAEAMACIgJAJQgOgLgbgKgAFYEaIAAAAgAlXEPIgBgBIANAJQgIgBgEgHgAnqELQgOgPAAgJIAAgEIAGADQAQAHAAAHQAAAGgIAFIAAAAgAj+EAIAAAAgAlFDyQAHgLAJgIQAEAMAGAIIgCAKQgPgEgJgHgAFIDYQgyABgDgBIAsgvQATgUAJgOIgRA6QAAACARAYQgHgEgMABgAHZDZQANgbAAgYQAEgegVgGIAAgDQgZgEgOgHQgBAFgHASIgEABQALgrAAgQQABgKgGgFQAKgQACgIIAAgCQgdACgHgPQgJASgOAUIgKADIABgCQA5hXADgQIAAgBQAAgQgLgJIACgGQACgFABgGQANAGAEAKIADAjIgOgIIAOAIIAAAEQACAaAOALIgFATQAAANARARQgRgRAAgNIAFgTIACACQAOALAAALQAAAQgBADIgDAGQgDAHgKALIgCAIQAXgCAQAVIADAGIgCAPQAAAKAFAZQgFgZAAgKIACgPQAIAMAAAIQAAAPgFAPIgBADQgGARgCAcQgCAIgGAAIgKgBgAjEClIADgEIABADIgFAEgAECCdIAIgaIgBgHIAAgHQAGAMAPAHIgbAbIgBgGgAkyCNIASgOIAFAbQgJgGgOgHgAlcB7QAAgLANgMIAIgIIgIggQAMgIAAgKQAAgZglgLQAZADAUgKIgBAFIADgHQAJgGAJgJIAAABQAOARAAACQAAAJgXARQgXASAAAUQAAARAaALIgBABQgJALgaAUQgGAEgDAFIgCgMgAjyB3IAAAAgAnQB2IgCgTQAEAGAEAHIgGAGIAAAAgAFqB1IASgEIgBAAQgKAEgGAAIgBAAgAmmBaIAFgBIADAHIgIgGgAE4BcIACgCIgBACIgBAAIAAAAgAj/A8IgBABQAEgIAIgIQgIAIgEAIIgDABIABACIABAAIgBAAIAAAAIAAAAQgIgEgNgCIAVgXQAHAEAHAGQAIAHAHAJQgCAGgFACIgTgJgAEYA1QgXAAgMgJIgCAAIgLgBIAAgGQARAMAvgGQgGAMgJALIgBgNgAkAA9IAAAAgAFUANIgcgJIACABIAFgJQgGgDgEgGIgBgBIAOgPQAUAGAhgFIAAABIgNATIgHABIgBAKIgIANIgGgDgADigIIAHgKIADgDIAPgRQAJgRAFgMQgPADgHAAQgeAAAAgRQAAgFACgGIgKgDIgBgEIADgOQAAgGgMgFQAMAFAAAGIgDAOIgJgZIAAAAIADgJIAJgVIgUAFQAAgIgBgBQgCgCgGgBIgGgIIABgFQAAgFgEgDQAEADAAAFIgBAFIgGgJIADgEIAGgJQgFgEgEgHIgCgLQAKgLASgaIALgRQACABAAAGQAAAGgRAYIAOAHQALgKAIgGQAJgPAJAAIALAJIAIgHIAOgFIAEADIAHgFIABACIgBgCIAEgDIgBADIgCACIgPAZQgKARAAAHQAAAFADAFQgIAHgIALIgIgBIAAAEIAGgBIgHAMQgTAhAAASIAAAQQADAMAPADIALABQAIAAAJgDIAGgBIgDAAIADgCQAMgFAOAAQgCAOAAASIAAAFIgbAaQgZAYgLAMIACgXIgCAXIgDACIgCgPgAC3ipIgBACIAYgGIACAAIAAgMIgOABIgLAPgADnAFIAAAAgAmegKIgBgBQgHgJAAgEQAAgWAYACIADAFQAHAMAAAGQAAABgaAKIAAAAgAj3gYQAOgGAJgPIABADQAAACgVATIgDgDgAlPgnIgIgoIAAgHIAAgCIgOgDIgDgDQgCgBAAAGIACAPIgIABQgMABgIACIgCgSQAAgpA6AKIAAAAIACAcQgCAIgLAEQALgEACgIIgCgcIAAAAIAIABIAAAEIATAnQAAAegiALIAEgFgAk6hKIAAAFIABgGIgBABgAkSgxQAEgLAAgKQgMgTgGgSQAIgFAegCIAAABQgBALAEAVQgBAGgYAYIgCACgAjQh9QAAgBgIgHIADAAIgDgHIABgJIgVgzIAZgTIAAAAQAFgEABgFIAFAAQAHAAAEADQAEACABAFQAGADABAKIgBAJIAKgDIAPgKQgLgPgLgLQgEgEAAgMIAAgEIABgGQAEgTAWAAIAAAAQAUAAAPABIAPADQAAADADAHIADgFIAjgoIAJAAIgJAAQAOgQAHgFQAHADAAAFQgHABgMAMIgPAUQgWAfAAAJIABAKQgQAVgLALIgCABQgfACgSAnIgUAHIAHAbIAAAGIgBAMIgFADQgTAMAAARQAAAEAFAJQgJALgMAFQAMgZAAgugAiZjOIABgBIgBgBIAAACgAjTjbIAWgGIgWAGgAiEjgQAHgMAQgSQgNAEgcAAQAHAOALAMgAizj/IADgCQAFgDAGAAIAAAAIAAAAIACAAIACABIABAAIAAgEIAAgDIgGABQgHABgFADQAFgDAHgBIAGgBIAAADIAAAEIgBAAIgCgBIgCAAIAAAAIAAAAQgGAAgFADIgDACgAigkKIArgNIgrANQABgKAHgEQgHAEgBAKIAAAAgAGhg/QgQgOgrAEQAFgMAAgMQgEgTgJgJQAIgMAAgEQAAgPgPAAQgaAAgMAZIgMACIADgHIgFgEIgFAMIghAFIABgCQAog2AAgLQAAgKgEgEIAGgJIAHACQAEgOAAgJIABAAIACABIAAAAQAGACAHAAIAAAAIABAAIAAAAIABAAIACAAIABAAIAAAAIAAAAIAMABIgMgBIAAAAIAAAAIgBAAIgCAAIgBAAIAAAAIgBAAIAAAAQgHAAgGgCIAAAAIgCgBIgBAAIABgEIARgkQARAIgCAkIgBAGQAAAHgIAiIAAABQADAIABAIQAcgGAQAIIACAnIABgBIABAAIAAAAQAFgDAFAAIAAAAIAAAAQAEAAADACIABAAIAAAAIAAACIgMAmQAUABANAGQgBAGgCAFIgCAGIAAAAgAEni3IAAgBIgBgBIABACgAjMhTQAAgRATgMIAFgDIgDAMQgFATgLAOQgFgJAAgEgAlohKIAAAAgAi0hzIAAAAgAk9iQQACgGAEgFQAFgHAIgDQACACgCAFIgNADIANgDIgDAIIABAMIgDABQgLAHgFAGQgCgKAEgKgAF7ikQAGADAFAFQALAMAAARIAAAAIgBAAQgDgCgEAAIAAAAIAAAAQgFAAgFADIAAAAIgBAAIgBABIgCgngAGRh/IAAAAgACyihQAGABACACQABABAAAIIgDABIgGgNgAkEitIAIAJQAAAKgBgBIgDAAQgEgMAAgGgACyihIAAAAgAhVjCIgIgHIATggIACABQAGAAAzhNQALACANAFQgNgFgLgCIADgEIgEgDIAEgBQAQAAAHAHIACAEIgEAEQgdAggZAoIgGATQgLACgFAGIgEAHQgFAGgEADIgFgHgAhOjBIAHgDIgHADIgHgBIAHABIAAAAgAAAjMIAGgEIgGAEQAAgDAEgGIACAFQACADAEACIgGACIgGgDgAAijdQA8hJAEgKIAEgBIANABIgNgBIgEABIAAgBIgFgFIAKgHQAMAKAAACIAAABQgCAMhGBMIgKAEIgKAEIALgNgAAnjZQgCgDgDgBQADABACADgAh1jQIACgBIgBABIAAAAIgBAAgAhzjRIAAAAgACHjZIAHABIgHgBQgCgCAAgDQAAgJAWgdQANgRANgLIACABIgNANQgdAgAAARIABAJIAAABIABAEIAAAAQgGgCgCgEgACHjZIAAAAgABdkQQAQgSAOgLIADACIgDgCQAPgNANgEQANAKAAACIgEAHQgGgCgFAAQAFAAAGACIgQATQAGgLAAgGIgBgEQgBgFgDgHQgIADgLALIgTAUQgYAdAAAIQAAAFACAEQAEAIAKAAIgDACIgLAAIgHAAIgBgCIAEgGIgEAGIABACIgSADQAEgTAdghgAgljeQAAgLAigrIAUgZIAIgCQgPAOgUAcQgUAagHAOIAAgBgABOjfIAAAAgAEzjqIAAAAgAEbkDIAAAAgAigkKIAAAAgAC3kfIAAAAgAC1kgQAHgHAIgEIgNAMIgCgBgAAnlDQAKAEAAAFIgBADIgDABIgGgEQgGADgIAIIgIACQAPgSAHgEgAAZkvIAAAAgAAtk2IADgBIgCADIgBgCgAgPk1IAAAAg");
	this.shape_3.setTransform(89.7,33.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AlAExQgKgBgJgFIgNgJIgEgDIgJgJQgIgIAAgEQAAgJAIgLIAMgMIAAAAIAlgiIgegMIgCgBQgNgGAAgKQAAgJAGgHQAEgFAGgEQAZgUAJgLIABgBQgagLAAgRQAAgUAXgSQAXgRAAgJQAAgCgOgSIAAgBQgIAJgJAGIgDACQgUALgZgDQAlALAAAZQAAAKgMAJQgFAEgJAEQgQAHgbAHIgYAGIgGABIAIAGIAdASIABABQASAMAAALQAAAOgcAVIgBACQAeADAAATQAAAGgcAYIgFAEIgbAVIgRAOIgIAFQgTAAAAgRQAAgEADgEIAGgKQAKgLATgQQgLgRAAgGQAAgLALgNIASgWQg1ghAAgaQAAgDACgDIAGgDQAUgGAIAAQAAgEgCgGIABAAIAegIIAGgBIAVgFQgGgVgMgFQgJgEAAgGQAAgUAPgHQAIgFAZgEIAEgBIALgDQAhgLAAgeIgTgnIABgEIAEgGQAGgGALgHIADgBQATgLAYgGIADAAQABABAAgKIgIgJQgRgUAAgJIADgFQALgEAYgDIAdgFIgdAFQgYADgLAEIAQgUQAVgXAJAAQAYAAAAAQIAAAGQgCAFgEAEIgBAAIgZATIAVAzIgBAJIgBAFIACACQAHAHAAABQAAAugLAZIgFAJQgJAPgOAGIADADIAGAHQgCAFAAAIQAAAFADAEQgDgEAAgFQAAgIACgFIAFAIQAAAGgEAIQgFAJgKAMIgFAGIgWAXQAOACAIAEQgDAGAAAGQAAAKAMAKQgMgKAAgKQAAgGADgGIABAAIAJAIQACAEAAAFQAAAIgDAHQgDAGgIAFIgYAQIgFAEIgSAOQAPAHAJAGQANAJAFAHQAEAGAAAFQAAAQgVAJQgJAEgJAFIgKAIQgJAIgHALQAJAHAQAEIAFACIAFACQAPAEAAAJQAAAPghAAIgDAAgAkphXQAGASAMATQAAAKgEALIAAABIABgBIABgCQAYgYABgGQgDgVAAgLIAAgBQgeACgIAFgAE0EsQgIgCgGgEIgSgIQgWgLgOgJQAJgQAAgEQgUgYgCgLQACALAUAYQAAAEgJAQIgCgBIgEgCQgPgLAAgGQAAgVAIgOIAEgHIAQgRIADgEIAbgbQgOgHgGgMQgFgHAAgKQAAgNAKgKIALgLQAJgLAFgMQguAGgSgMIgDgCIgBgHIADgXIgDAXIABAHIgHgRQAAgDAHgIIACgCQALgNAagXIAbgaIgBgFQAAgSACgOQgNAAgMAFIgEACIgCABQgKADgIAAIgLgBQgOgDgEgMIAAgQQAAgSATghIAIgMIACgCQAIgLAIgHQgEgFAAgFQAAgHALgRIAPgZIABgCIABgDIAAAAIgEABQgGgMgHgHQAYgMARAAQAPAAAAAPIgBADIgRAkIgBADQgNgGgJgQQAJAQANAGIgLAWIgFAJQADAEAAAKQAAALgoA2IgBACIAhgFIAIgBIAMgCQAMgZAZAAQAPAAAAAPQAAAEgHAMQAIAJAEATQAAAMgFAMQAsgEAQAOQALAJAAAQIAAABIgBAAQgHgEgCgLIgBgJIAAgCIAAACIABAJQACALAHAEIABAAQgDAQg6BXIgBACIAKgDQAUgFAFAAQAQAAAHAGQAGAFgBAKQAAAQgLArIADgBIAigLQAIAAAFACQAWAGgEAeQAAAYgNAbIgGAMQgKATgIAIQgGAFgEAAQgQAAgHgNQgEgIAAgHQAAgRAKgUIABgDQgeAPgCAAQgRAAgHgNIgDgPIAHgfIAHghIABgDIAAAAIgRAEIgGABQgCAIgHAJQgJAOgTAUIgtAvQAEABAxgBQAMgBAIAEQAIAFACAKIAAAHQAAAJgIAPQgDAIgFAEQgGAHgJAAIgKgEgAEvBwIACAAIAAgCgAEsAFIgLAMIgDADIARAEIAcAJIAGADIAJgNIAHgMIANgSIAAgBQggAFgVgGIgNAOgAinEsQgMgCgEgEQgGgGgQAAQgNAAgEgLIgBgLQAAgVAOgMQgSADgJgHQgIgHAAgPIABgDQABgKALgUQAMgVAKgDIAEgBIABAAQAGAAAEACQAFADAAAIIAAABIgFgMIAFAMIgEAIIgJAKIgDAEIgBADIAGgEIAEgFIAFgDIAHgCIADAAQATAAABAVQAAAEgFANIgSgmIASAmIgBAEIgJAUQAMAAAIALQAIALgDAGQAMgCAIABQAPADAAAOIAAACQAAASgnAAIgMAAgAi9CjIAAAAgAm5BMQACAGAAAEQgIAAgUAGIgGADQAGgNAagGgAkKBUIAAAAgAm5BMIAAAAgABeAQIgBAAQgRAAAAgOIABgCQAEAKAMAGQgMgGgEgKQABgCAFgGIAFgHIAFgEQAKgLAHAAQAFAAADACQADACABADIABAGQAAAYgQAHIACgCQALgQACgTQgCATgLAQIgCACQgFACgGAAIgCAAgABdgTIAZgJIgZAJgAhlAKQgBABAAgKQAAgFAGgPIAFgIIACgDQAEgGAEAAQAMAAAEAPIACAIIAAAFIgBAFIgGAHIgCADIAJgUIgJAUQgFAFgGACQgKgFAAgJQAAgIAKgLQgKALAAAIQAAAJAKAFIgGABQgDAAgJgFgAhBgVQgMgCgOgEQAOAEAMACgABrAOIAAAAgAj3AGIAAAAgABNAAIAAAAgAGkgRIAAAAgAgwixQgCgCAAgKIAAgBIABgCIAEgJQAHgOAUgaQAUgcAOgOQAJgCALgFIACACQAFAFAAABIgbArIAMgNQARgUAPgMIAIAFIAVgFIgVAFIgIgFQAKgIAIgEIAHAGIAEAFIAAABQgEAKg7BJIgDAAQgGAAgRAMIgCABIgBgFIgBgDQAAgIAEgKIgSAbIgHAIQgPgJgKgCQAKACAPAJQgFAHgDAAQgDAAgMgFgAAEi3QgEgCgCgDIACgBQARgMAGAAIADAAIgLANIgFAGIgGgBgACHi/IAAgEIgCgBIgBgJQAAgRAeggIAMgNIALAIIATgDIgTADIgLgIIANgMQALgIAIgFQAHADAAAFQAAAFgJARIgKAPIgLARQgRAagKALQgHAHgDAAQgHAAgEgFgACHi/IgCgEIAAgBIACABIAAAEgACFjEIAAAAgABajNQgKAAgEgIQgCgEAAgFQAAgIAZgdIASgUQAFAEABAGQAEgGAOgGIAAAEQAAAGgFALQgFAKgKAOQgUAfgLAAgAhTjVIgNgEIgBgEIgBgKQAAgJAWgfIAQgUIAUAAQAIAAAJACQgJgCgIAAIgUAAQALgMAHgBIABAAQAHAAAKAIIADADIgCAEQg0BNgGAAIgCgBgAEqjXIAAAAgADnjxQAAgDAYgNIAGgDQAHAHAGAMIgKAEIgOAFIgIACgAESjxIAAAAgACukLIAAAAgAB7kNQgBgGgFgEQAMgLAHgDQAEAHABAFQgOAGgEAGIAAAAgAB1kXIAAAAgACNkZIAAAAgAAekmIAGAEQgLAFgJACQAIgIAGgDgAAkkiIAAAAgAg8kjIAAAAg");
	this.shape_4.setTransform(90.6,31.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AWSVaIACAEIAFACIgFgCIgCgEIALgGIgBADIgDAJIAAACIgNAAIgNADIATgLgAveVLIAJAAIgGABIgmAGQARgHASAAgArbVGQAKgBASgHIAJAHQAGAEAGACIgIABIgpgGgAtaU+IAYgBIAiADQgfgCgbAAgA2cSgIA0g+IgwBAIgEgCgAJ2QyIAEAAIACAAIgCAAIgEAAQAJgIAKgMIAEgEIAAADQgFARgMAEIgCABIgFAAIABgBgAJ2QyIAAAAgAhfQOIABABIABADIgCgEgAzJQIIgIgMQAFABALAEIgBABIgEAEIgCADIgBgBgAzJQIIADgCIgDACgAlvO1IAKAWIAAAAIAAACIAAgCIAAAAIABABIgBABQgKAFgIABQAHgKABgUgAllPLIAAAAgAxbOeIABACIgCAAIABgCgAy0OCIAIgEIAEAIIgEAAQgFAAgSARIAPgVgAwhN6IAEgLIATATIgXgIgAxENsIgBAAIABgKIAEgIQAAAMAPAMQgQgGgDAAgANLJLIgFgEQARAEBAAHIAjAFQhbgCgUgKgAxqH1IACgBIAAADIABAHIgDgJgAK6G9QAZALAhAEIgFACQgbAAgagRgAMRHAQADgHAAgHIAMAAQgBAHABAKQgHgCgIgBgAJDEmIADgHIAGARIgJgKgAJADqIAEAEIgBABIgDgFgAy+BzIABACIgCADIgBABIACgGgAuwrSIgGgUQAGgEAAgHQAAgCgMgLIgUADIAFgBQAfgNAIgRQADgFABgLIAJAJIAEAEIAAABQAEAHAJABQAJAFAKAAQABAFAEAJQAIAPAKAAQAMAAAGgOIAJALIgOARQgIAIgEABQgGgBgKgKQgKgMgDAAQgHAAgSAUQgSATgDAAQgJAAgBgHgAv1rnIAAgDQALALAOABIACAAQgGAEgHAAQgNAAgBgNgAlOrmIBVAAIABABQgcACghAAQgRAAgIgDgAtBr1IAHAIIgVAJIAOgRgAkdr7IABAAQAHgNAAgJIgJgRIASAIQAGAFAIABIAKAEQAIAAAHgGIADAFIAAAAQgFAAgIASQgHARgQABQgMAAgLgOgAlNr0QgDgDgCgGIgBgLQAEgBAGAAQABgBAIgPQgIAPgBABQgGAAgEABIABALQgIgJgBgFIAGgMQAGgNAHgVIAEACIgBAFIAAABQAAAMAEAJIABADIADAEQAEAFASANQgFAEgFAIQgEAHgMABQgIAAgEgFgAlVsXIAQgaIgQAagAtKsAIAAAAIgCgGQARgVABgRQASgYAAgFQAAgOgUgLQAGgGAPgMIAAADQAAAPAIAHQADAHAQAGIgBABQgRAWAAAEQAAAOASAFQAbAKANAMIAKgKIAMABQAnAAAAgSIAAgCQAPAPARAOQgMAQgHABQgSgOgEgPQgOAdgFAAQgJgBgNgHQgNgLgIgEQAAAZgUAAQgGAAgeglIgbAnIgJgLgAtSsHQAAgGAVgbIADgEQgBARgRAVIACAGIgDAAQgFAAAAgHgAtKsAIAAAAgAi+sHIgBAAQAAgWgWgkQgCgLgJgEQgRgZAAgCIASg5QAHgKABgHIAHgBIAAAAQAHgBAKgEIgBADIgHAhIgCAFQgQAiAAALQAAAFAGALQAJAPAOAAQAFABAZgIIgOAzQAAAFACAFIgBABQgIAJgJAAIgCgBgAiCsUQAEgKAEgOQAIgIALgTIAFgLIALABQAFgBADgHQABgcAHgSIABgCIADAPQAAAIAIANQAIAMAAAJQAAALgIAPQgSgIgKgCQgLAvgTAAQgHAAgGgDgAv0seQAAAAAAgBQAAAAAAgBQgBgBAAAAQgBgBAAAAIARgOQABAIACACIASACQAIgBAJgFQgCANgiADQgLABgIACQACgEAAgDgAs6ssIAAAAgAtosuIABgLQgFgHgFgNIAKgIQAEANAUADIgUAZIgFgCgAwPs2IAGgJIABAAIgHAJIAAAAgArPtIQgIgMgMAAIAJgUIAJANIAHALIAUAYQgIgCgMACQADgFgIgLgAw+tMQAAgHAQgLIAWgQQgIgJgPgFQgLgDAAgDIANgOIgBAFIAKAMIAMgCQAHANARASQgmAPgJAJQgEAEgBAJQgKgHAAgIgAvFtJIAAACIgFACIAFgEgAuctVIAAgDIAHgDIAAABIAAAEIgLANQAEgHAAgFgApdt5QgKgBgMgMQgLgMgEgJIACgFIgNgWQAAgDAFgEQAEgEAEgBQBdAPAlADQAoAIABAGIgNAOQgWAPg8AaQgWgBgTgNgAu4uEQAcgfAAgQQgDgaACgLQABgHADgIQAIgEAGgEIAIAgIgIAHQgNAMAAALIACAMQgGAIAAAIQAAAKANAGIACABQgDAJgaAKIgBABQgNgRAAgDgAtWuRIgGgcIAFgEQAFAIANAKQgHAIAAAIQAAAFAJAHQgJgHAAgFQAAgIAHgIIAUAPIgSANIgBABQgGgHgMgIgAlFuwQgLgogCgJIAAgCIgBgdIAGAJIgFAWIAFgWIgGgJIAAgBIALABIADAAQAMAJAWAAIACANIgLALQgKALAAAMQAAAKAFAIIgBAGIACAHIgJAaIABAHIgDADQgDgQgHgbgAr9uKIAJgLIACAFIgFADIgEAFIgCgCgAniuUIAAAAgAnVuiIAAAAQAAAFgNAJIANgOgAtFufIAAAAgAwLu1IADATQgNgBgJACIATgUgAiMu4QAOAHAZAFIgBACQgGgCgHAAIgiALQAIgRABgGgAnVuigAswuzIgDAAIAFgCIgCACIACgCQARgFAAgQQAAgHgKgJIgMgJIgJgIIgBgBIgCgCIADgBIgBADIABgDIABgBIATAJQAFgBACgHQgHgJgHgGQgHgHgHgEIAFgFQAKgNAFgJQADAFAHABIAKAEIgBAHIgTAPIgGAGIAGgGIATgPIAAAGQAAAHACAKQACAfANAkQgRAHgGAIQgJgJgLAAgAsBuvIACAEIgBAAIgEABIADgFgAn+uwIAAAAgAqAvCIAEgBQBVALApAIQglgDhdgPgAsuu1IAAAAgAvavMIgDgHIAZgFQABAKAFAUIgcgSgAhNvCQgPgUgXABIACgIQAJgKAEgIIAGAGQAXATAAAKIgCAQIgEgGgAwivWQAFgFAOgFIAAADIABAVQgIgLgMgDgAipvwQgGAAgTAFQAPgUAJgRQAGAOAegCIAAACQgCAIgKARQgHgHgQAAgAs8vvIAAAAgAvTv9IAMgJIAAACIAAAHIgGACIgJAAIADgCgAsWwNIAAgGIAEgDQAAAAAAgBQAAAAAAgBQgBAAAAgBQgBAAgBgBQACgOAGgQQAGgQAJgIQgJAIgGAQQgGAQgCAOIgKgEQgHgBgDgFQAEgIAAgFIgFgJIgGgIQAVgSAAgCIgBgDIAFgKQALgFAJgLIABACQAGAKAAAGQAAANgYAIQgRAEgFAOQAFgOARgEQAYgIAAgNQAAgGgGgKIgBgCQAMgOAFgTIgBAOIAAAFIgDATQgDAOgFAQIgFANQgRAqAAAWIAAAHQgCgKAAgHgAr2xvIAAABIAAgBIADgSIgDASgAlTwAIAAAAgAv8wXQAAgSAegMIAEgCIAEAGIgBAHQAAAEACAFQgGALgWANIgEADQgHgNAAgEgAsVwaQABABABAAQAAABABAAQAAABAAAAQAAABAAAAIgEADIABgHgAnnwdQAMgCAKgIQgBANgOgBIgHgCgAnnwdQgKgEgRgNQgYgSAAgCQAAgHAJgEQAJgFAUAAQAGABAFACIADABIAHAFQgFAGgBADQgCgEAAgGIABgEIgBAEQAAAGACAEIgBADQAAANARAAIABAAIACAAIAAACIABAEIAAADQgKAIgMACIAAAAgAnSwuIgDgCIADACgAoHxMQAOAAAQgDQgQADgOAAIgKgBIAKABgAiAxGIAAgEQAMAJAJALIgGAXQgNgMgCgbgAq8wzIgMgNIgSghQAAgSARAAQgFAMAAAMQAAAUASAUQgSgUAAgUQAAgMAFgMIABAAIAJAAQAXADAYAPIAEACIgCADIgJgDQgbgJgNgLQANALAbAJIAJADIgFAIQgGAPAAAGQAAALABgCQAJAGADgBIAGAAQAGgCAFgGIACgCIAGgJIAAACQAAAGgMANIAAABIgBgBIgGgCIAGACIgBADIgEAEQgJAHgGABQgVAAgTgTgAqAwvIAFgKIgFAKgAspwkIAAAAgAnRwnIAAAAgAkDwoIgRgEIADgDIALgMIAAABQAEAGAHADIgFAKIgDgBgAt3wuIADgCIgEAIIABgGgAjXwzIAGgBIgHAMIABgLgAqAwvIABABIgCACIABgDgAp/wuIAAAAgAlbxDIgGgaIgFgTIgEgQIgEgMIAKADQgCAHAAAEQAAARAeAAQAHAAAPgDQgEAMgKARIgOARIgDADIgHALIgDgPgAlRw/IAAgBIgCgEIgGABIgBAAIgBAAIABAAIABAAIAGgBIACAEIAAABgAlhxdIACgLQAAgEgHgEQAHAEAAAEIgCALgAnlxAIAAAAgAuZxOQgHgagEgPIgCgOQAAgHADACIACACIAOAEIAAABIABAIQgHADgLABQALgBAHgDIAHAnIgDAGIgLACIAAgCgAvJxZQgFgIAAgFQAAgJAOgEIAEAdIgNgDgAqOxcIAAAAgAtOxeIABAAIgBABgAt2x3IABgBIgBAGIAAgFgAsDxzIAAAAgArJxzIAAAAgAuSx7IAAAAgAi1yEIAMglIAAgDQAGAEAGALQAJARgBAPQgMgFgUgCgAkwyEIADAAIgFABIACgBgAuHykQAAgXAFgFQAFgFAKgDQgEAFgCAGQgDAKABAKIgEAGIgIgBgAl4ypIgIgTIgCgFIADgBIAAABIgBAFIABgFIAAgBIAUgFIgJAWIgDAIIgBABIAAgBgAl3ypIgBAAgArvyyIgHgbIAUgHIgEAKQgGAPgDAPIAAgGgAkXy4IAEAEIgCAGIgIABIAGgLgAsTyyIgCgCIABgFIADAHgAtpzDIADgIIAKgBQAYgEAAgGQgUgYAAgJQAAgCAKgDIgDAGQAAAIARAUQAAAHAEAMQgYAFgTALIgCgMgAl/zCIAAAAgAjszTQgBgIgDgIIAAgBQAIghAAgHIABgHQAfAGAGAnIADAVQgRgIgcAGgAmEzWIALgPIAOgBIAAAMIgBAAIgZAGgAlNziIAJABIgCADIgHAAIAAgEgAmbznIAEACIAFACIgFgCIgEgCQgGgIgIgGQgCgFAAgGQAAAGACAFQgPgNgRgGIACAAIATACIgTgCIgCAAQgIgCgJgBIACgDIAAAAQALAAAUgfQAKgOAFgKIAPgTQAJADAMAIQgNALgNASQgWAdAAAIQAAADACACQACAEAGACIABAAIAAAAQADAFAIAAQADAAAHgHIACALQADAHAGAEIgHAJIgCAEIgHgIgAkVzmIABABIAAABIgBgCgArtz5QAAgLgGgDQgCgEgDgDIAEgCQgEgMAAgFQAAgLAKgGIgBAGIgDACIADgCIAAAFQAAALAEAEQAMALAKAPIgPALIgJADIAAgJgAqoz9IgEAAIgDAAIAAgBIADAAIAEABIgEgBIgDAAQALgLAQgUIABADIANAFIgTAfQgHgGgIgBgApFz8IATgbQgFAKAAAIIABADQgFAGgBAEIgJgEgArUz9IAAABIgBABIABgCgAkT0CIALgWIABABIgBgBIABgDIAAAEQgBAKgEANIgHgCgApp0TQAagnAeghIADABIAFAAIgVAZQgjArAAALIAAABIgDAJIgHABIgDAAIAFgTgAnI1dIAIADQgNAMgQARQgeAhgEATIgRAEQBGhMACgMgAl/0TQARgYAAgGQAAgGgCAAIAJgQIAngHQAKAAAIAJIgFADQgYANAAADIALALIAIgCIgJAIIgLgKQgIAAgKAPQgIAGgKALIgPgIgArS0nQAcABANgFQgPATgIALQgLgMgHgOgAkI0YIAAAAgAkq0uIAKgDIAEgCIAAAAIgDADIgBAAIAAgBIAAABIABAAIgIAFIgDgDgArv0sIAAAAgAoH1aQAAgCgFgFIACgDIAAAAQAEAAAQAIQgPAMgRATIgMAOIAbgrgAkf0wIAAAAgAqi1BIgPgCIAMgEIALABQAAgZAbgFIAGAAIgiAoIgEAFQgDgHAAgDgAqx1DQgPgCgTAAQAGgDALAAIAdABIgMAEIAAAAg");
	this.shape_5.setTransform(146.9,140.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#666666").s().p("AKiEoIBChEIhCBEQgFgDgDgFQgDgGAAgFQAAgRAxgTQAQgHAMgGQAdgPAHgQIAQgoQAMgZAOgFQADgCAEAAIACAAQAVACgMAmIgBAEIAJACIAcAAQAKAAAPgJQAGAAAIAGQAIAGAIAOIAMATQAAASgGAGQgJAKgeAAQi6A5gXAAQgHAAgEgCgAOfC8QgsgQgKAAQgsAIgIAAIgDg1IADA1QAIAAAsgIQAKAAAsAQgAskDnQgRgHgMgIQgdgTAAgUQAAgEADgFQAGgIAKAAIApATQArASAUACQBBAHAPAFQAQAFAAARQAAAYgoAAQg+AAg7gagArTDnQALAAAGgDQgGADgLAAIAAAAIgJAAIgcgEIgGgBIgBgBIgBAAIgCAAIgHgCIAAAAIgBAAIgCAAIgBgBIgHgBIgDgBIgEAAIAAAAIgBAAIgFgBIgFgBIgGgBIAAAAIgJgBIgCgBIgBAAIAAAAIgEAAIAAAAIgFABIAFgBIAAAAIAEAAIAAAAIABAAIACABIAJABIAAAAIAGABIAFABIAFABIABAAIAAAAIAEAAIADABIAHABIABABIACAAIABAAIAAAAIAHACIACAAIABAAIABABIAGABIAcAEIAJAAIAAAAgAg1CyQABgKgKAAQgxAOgPAAQgNAAgGgMQgDgHAAgHQAAgPCAgbQBCgJBegMQAegEAWgFQAMAGAAASQAAAEgLAUQAPAGAAASQAAAbhVAXQhOAUhJAAQgsAAATgwgACOCQQAJgBADgDIgDAAgAslCGQgRgMgIgIIABACQAAASgSAAQgSgHgKAAQgGAAgGgQIgBgBIgBgKQggicgGgnQgCgPgHgWIgCgMQAAgIAXg9QAYhAAIAAIACAAIAIAbIAJAeIACAGIgCgGIACgBIAAAHQABAlADAaQAAAlAFAyQAFAxAAAyQAAATAMAnQADgLAOAAQAOAAA+AdIA0ALQALADAAAHQAAAbg3AAQgiAAgkgZgAsGCAQg9gcgTgEQATAEA9AcgAGQB8QDkhQAHAAIAKABQgPALgtANIicA9QgUAAgJgGgAGQB8QgHgFgBgHIBUhCIAWgTIgWATIhUBCIAAgEQAAgMBDgrIAngaIAlgYIBPhdIAGAAIAFAAIAAgIQAQADAIAbQAHAZABAtIgBATIgBAIQgZhOgFgpIAIgBIgIABQAFApAZBOIgKADIAKgDQgCAIgCADIgGAFIgKgBQgHAAjkBQIAAAAgAAEBtQCNgcAgAAQAJAAAGADQgWAFgeAEQheAMhCAJIAYgFgAuSAHQgKg4gMhTQAHAWACAPQAGAnAgCcIABAKQgMgcgOhLgAKFAtIAAAAgAm1gGIgBgCIgKgnIgEgQIAAgDIgBgDQgUhSgZg1IgCgPIgGgDIgDgCIgEgGIAEAGQgGgFgGgIIgDgEQgKgOAAgEIAAgBQALANAKARIAlgFIBIAPIhIgPIglAFQgKgRgLgNQAAgQAJgJQAGgGAKgCIAMgCQAfgCBjAAIAQAAIA8ADQgdAHgwAAQgxAGgMAAQgNAEgFAAQgugIgbAAIgFAAIAFAAQAbAAAuAIQAFAAANgEQAMAAAxgGQAwAAAdgHIARABIARABIACAJQAAAGgFAIQgGAJgEABQAAgKgKAAQgZAHgOAAIhSAFQADADAAAGIgGAcIgUBVQABAPAGAkIAHAXIANAnQAAAJgFAFIAAABQAAAJgCAAQgBADgKAAQgNAAgJgLgAmrj/IgDAJIAKgKIgHABgAnDgtIAAgEIgBgOIAEAQIAKAnQgJgNgEgYgAnEg/IAAAAgAnThrIgMgyQgJgCgEgOIgBgLIgEgLIgBgJQAZA1AUBSQgHgPgHgXgAEMhiQAlgDAmgGIg2AXQgRAAgEgOgACthhIAUACIAWAAIgSAJQgRAAgHgLgAJshaIgGAAIAHgIIAEAAIAAAIIgFAAIAAAAgAJmhaIAAAAgACthhIgBgBQgDgFAAgIQAAgKBXgwIADgCQAfgRAWgLQAggQAPgCIAGgBIAFACIgLgBIALABIAFADQANALAbAfQAAA5g1AAIgTAHQgmAGglADQgBgDAAgMIABgGIg1AYIgWAAgAERirIAngcIgnAcgADXhfIAAAAgACthhgAJxhiIAAAAgAFXhrgAuoiEIAAAAgAnyjMIAAAAgAoWkEIAAAAg");
	this.shape_6.setTransform(164.4,195.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#999999").s().p("AG7HGIACgBIgCACIAAgBgAG7HGQgGgOgcgMQgYgKgNAAIgKADIgIgJIAIAJIgJACIAAgCIABgJQAAghgaAAQgIAAgIAGIgJAGIgDgGQAPgtgjAAQgIAAgHAFIgHAGQgHgKgGgEIAHgTIgIAEIgEAIIgDADIgFgBQgHAAg/BEIgpAtQgZgZgEAAIgLAEIgQgQQgIgZgHgSQgUgwgWAAQgcAAAAAkQAAAOAIAeIgOAGQgNgTgZgcQgeghgJAAQgOAAgJAHIgFgEIAAAIQgMANgEAaQgCAQAAASIgCADIgKgEQhBh1gbinQAbCnBBB1QgmgTgdhrIgbh0IABgGIAAgCQgHgvgZhTIgXhKIgIggQAJAMANAAQAKAAABgDQACgBAAgKIgBgBQAGgEAAgKIgNgmIgHgYQgGgkgCgOIAVhWIAGgbQAAgGgDgDIBSgGQANAAAZgHQAKAAAAAKQAFgBAFgIQAFgJAAgGIgCgJIgRAAIgRgBQAbgHAKgMIAEgFIAKAAIAQACQAKAAAhAQQAiAPAHAAQCXAAB/g2IAlgRQgWAcgcAKIglAQQgeAMgbACQhSAKgZAAIg6AEIhogUIgkABIAkgBIBoAUIA6gEQAZAABSgKQAbgCAegMIAlgQQAcgKAWgcIAVgKIAQgIIAGgDIABAAIABAAIAFgDQAKAAAgAIQA5AAAMAEQAPAFAdAZIADACIALAhIgLghIATARIADAFIALAVQAAAHgJAUIgNglIALgLIgLALIANAlIgDAGIAKALQAOAQAXAlIASAeQAOAUAOAPIACACQANAMAMAIQAaARAaAAIAGgCIAIgEQAKgHAJAAIACAAQAIAAAGACQAVAHADAbIAAABQgIgcgQgCIAAgFIAAAFIgEgBIgGAIIgKgBIAGgNIgGANIAKABIhQBfIglAYQBVhIAWgwQgWAwhVBIIgnAZQhDAqAAAMIAAAEQACAIAGAEQAKAHATAAICcg8QAtgOAQgKIAFgFQADgDACgIIABgJQACAGAEADIAFAEQAVAKBaACIAeAAQAkAAADAlQAAAOgOASIgHAKIgCAAQgDAAgEABIAAgKQAAgLAJgSQAHgPAEgDQgPgPgsgIQAsAIAPAPQgEADgHAPQgJASAAALIAAAKQgNAFgMAZIgRApQgHAPgdAQIAigkIgiAkQgMAGgQAGQgxAUAAAQQAAAGADAGQADAFAFACQAFADAGAAQAYAAC5g5QAeAAAJgKQAGgGAAgSIgLgUIAOAFIgEAIIAHAbQgaAPgpAOQhFAXhOAQQg7ANgOAAIAMgIIAEgFIgEAFIgMAIQAOAAA7gNQBOgQBFgXQApgOAagPIAPAxIAEARQABAIADAHQAOA2AAAUQAAAHgFAJQAFgJAAgHQAAgUgOg2QADAHAHAFQANALAAANQAAAagNAcIgBAAQgGgDgGAAQgjAAgIAZQgMAhggAMQgBgUgDgMQgGgXgbAAQgVAAgQALIgCgBIAAACQgMAJgJAQQgPAogEAHQgXgIgHgdQgGgYgdAAQgLAAgHAEIgBgBQgQALgBAmQAAAQgFAOQgHAEgMADIAAgBIAAgXQgFgSgXAAIgCAAIgBgIIgMAAIgSATIgXAHIgHgDQACgRgCgMQgDgYgWAAQgQAAgFAUQgKAEgFAKQgEAIgCALIgEAFQgKAMgKAHQgMgBgMgHQgPghgWgFIgIgNQAAAFgFAHQgSADgUAZIgRAbIgCABIAAAAgABBBoQgTAwAsAAQBKAABOgVQBVgXAAgaQAAgSgPgGQALgVAAgDQAAgSgMgGQAmgJALgKQgLAKgmAJQgGgDgJAAQggAAiNAcIgYAFQg0AHgjAHIgTgEIATAEQAjgHA0gHQiAAbAAAPQAAAGADAHQAGANANAAQAPAAAwgOQAKAAgBAKgAGsBuQAKgMAbgYIgEgEIASgGIgOAKIAOgKIgSAGIAEAEQgbAYgKAMgAHvAzIgQANIAogPIgoAPIAQgNIAQgOIgQAOgAMNgZIgGgTIACgBIAFABIgFgBIgCABIAGATIgQgDIAQADIAAAAgAGAhRQASgaAWgWQgWAWgSAagAEshVQALgKAVgmQgVAmgLAKgAHhhlIA4gsIg4AsgAGCi8QAAAMABAEQAFANAQAAIA2gWIATgIQA1AAAAg5QgbgegMgLIgGgEIgFgCIgGABIgRgCIgFAAQgOAAgdASQgZAPgJAPIgEACQhXAxAAAKQAAAHADAGIABABQAHAKARAAIATgIIA0gZIgBAGgALUimIgXgCIAXACgAFPipIA0gDIg0ADgAEkirIgYgCgAHzi7IglAGIAlgGQBOgPAggDQgpgkgjhSQAjBSApAkQggADhOAPgAJhjNIAHAGQAMAJAPAHQgPgHgMgJIgHgGIAHAAIgHAAIAAAAgAhdkKQDNAACugfQCrgfA4gxQg4AxirAfQiuAfjNAAQgwAAhvgWIgggHIAgAHQBvAWAwAAIAAAAgAHNkmIAYgQIgYAQgAE7m4IAWgLIgWALgAG9HFIAAAAgAImG1QAMAHAMABIgBACQgMABgGAEIgFgPgAMMGbQABgmAQgLIABABQgRAKAAAhQAAAGAEAPQgBAIgJAGQAFgOAAgQgAImG1IAAAAgABBGYIAQAQIgLADIgFgTgAFqGlIAAAAgALJGOIAMAAIABAIIgfALgAiXGaIACgDIAAADIgCAAgABBGYIAAAAgAiVGXIAAAAgALWGWIAAAAgAH4GOIgEAAQAFgHAAgFIAIANIgJgBgAH0GOIAAAAgAMeFrIAAAAgAppFaIAcAIIgCACIgBABQgNgEgMgHgAoVFiQAFgHAEgNQAJgZAAgTIANAKQgGAHgHAMQgIAQgIAVIgCgCgAppFaQgngWghgxQgvhGAAgpIAAgBQgVhLgLgzQAHAQAGAAQAKAAASAHQASAAAAgTIgBgCQAIAJARAMQAkAZAiAAQA3AAAAgcQAAgGgMgDIgzgLQg/gdgNAAQgPAAgCALQgMgmAAgUQAAgygFgyQgFgyAAgkQgEgbAAgkQAbBTAWAiIAcAuIAAAAIABABIgBgBIABABIAAABQAfBGAWAeIAlAzQBBBcAOAVIAKAQIAEAGIAAABQA1BZAFA0IABALIAAAFQgBAUgHAKIgGABQgJgTgPgBQANgsgkAAQgJAAgKAMIgNgKQAAATgJAZQgEANgFAHQgQgLgGAAQgRAAgRALIgcgIgAmvEkIAIANIgIgNQgagvgihcQAiBcAaAvgArjBeQgDAFAAAEQAAAUAdATQAMAHARAIQA6AaA/AAQAoAAAAgZQAAgQgQgGQgPgFhBgGQgUgCgsgTIgogSQgLAAgFAIgAnhCjIgKgKIAKAKgAnuCVIADAEIgDgEQgcgig0hXQA0BXAcAigAq8iEQANAEAWADQgWgDgNgEQgZgJgCgcQACAcAZAJgAOZFaIACABIgCABIAAgCgAppFaIAAAAgAD1FRIgIgEIADgDIAEgIIAIgEIgHATIAAAAgAiDFGIAFAEIgFAEIAAgIgAh+FKIAAAAgAtnE/QgJAAgIgGQADgFABgGIABgFQAAgfgwgBIgEgDIgDAEQgdAPgGAAIgmgUIgIgTIgMAJIgMgHQgPAAgJAMQgHAJAAAIQgGgBgKgCIgSgTIAIgWIAVg3QAWgwA/hBQAqBIAdAhQgdghgqhIQg/BBgWAwIgVA3IgIAWIgBgBQAAgQAnhXQAPgjANgWQAXgnAQAAIAFACIAEACIADADIgBAAIgCgDIACADIgCADIgBgDIgDgFIADAFIABADIACgDQAVAbAdAsIgDAFIAWAgIAbApIANASQAaAoAIASQADAHAAAEQAAAOgIAGIgJADIABABIgGABIAFgCIgVgPIAVAPIgFACIgDAAgAteE+IAAAAgAtfE9IAJgDQgDADgFABIgBgBgAtWE6IAAAAgAn2EsIAAAAgAunEGIAEADIgEAAIgDABIADgEgAwHD7IAMgJIAIATIgUgKgAj/CkQgQhHgMgkQgJgcgOg+IgDgPIAXBKQAZBTAHAvIAAACIgBAGIAAAAgANbCaIAAAAgAO6BfIACgEIABABIAHAEIgKgBgAEOBCIADAAQgCACgKACgAvgA6IAAAAgABjAoIAAAAgAMNgZIAAAAgAJpguIAAAAgAk1gwIAAAAgAlujTQgQgtgDgkIgBgEIAFADIACAPIgGgOIAGAOIACAJIADALIACAKQAEAOAJADIAMAxQAHAXAGAQIACAGIABAOQgYg6gLgegAlMiJIAAAAgAlOiPIACACIAAAEIgCgGgAlOiPIAAAAgAs7jrQAEgWAIgdQAVhNAbAAIACABIABAEIADgCQADADAEAGIgIgBIgCgGQgZASgRA0IgSA8IgDgHIADAHIgHAXQAAgMAEgSgAs4jkIASg8QARg0AZgSIACAGIgBAAQgIAAgYBAQgXA9AAAIIACANIgIgWgAs4jkIAAAAgAGdkUQAdgSAOAAIAFAAIARACQgPADgfAPIAdgUIgdAUQgXALgeARQAJgPAZgPgAl7kWIAAAAgAHekkIAAAAgAmalCQgLgOgCgHIAAgCQAAgIACgGIAPAAIgPAAQAGgPAUAAQAIAAAJAFIgLABQgLACgGAHQgIAIAAARIAAABQAAAEAKAOIgGgHgAmelOIgJgJIAJAJgAkzlKIAGAAIgJAJIADgJgAIOlUIAAAAgAr9lqIAEACIgDACIgBgEgAr9lqIAAAAgAEmmuIAAAAg");
	this.shape_7.setTransform(152.4,203);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#CDBEB4").s().p("ABPUoQgcgHAAgVQAAgIASgbIAKAAIgKAAQgSAbAAAIQAAAVAcAHQgNgBgkgQIAHgCIgHACIgmgTIgCgBIgIgEIAAgBQAAgIANgSQAOgTAOAAIAGACIgGgCQgOAAgOATQgNASAAAIIAAABIgmgTIgCAAIAGgDIgGADIgWAAQgEgIAAgLQAAgNAMgNQAPgQAbAAQAIAAAMAGQgMgGgIAAQgbAAgPAQQgMANAAANQAAALAEAIQgbACgWAEQgGgDgDgFIgCgDQgCgGAAgHIABgMQADgaASgHQAOgFAugNQguANgOAFQgSAHgDAaIgpABQgcgLgVgQQgJgLAAgHQAAgdAYgQQAIgGAJgDQgJADgIAGQgYAQAAAdQAAAHAJALIgPgMQAEgmAWgOQAIgFANgDQAOgDAVgBIAYAAIA5AAIATgCQAsgEAlgMQAcgJCBhyIABAAIgCgGIgCgEQgIgUgMgIIgMgTIACgHQANAOAbAKQgbgKgNgOIgCAHIAMATQgHgEgHAAIAAAAIgBgBIADgOIgOgYQgFg0g1hZIAAgBIAAABIAAgBQAAgDgEgDIgKgPQgOgWhAhcIgKgQIhQiIIAAgBIgBgBIAAAAIgcguQgWgigbhTIAAgIIgCABIgKgdIgIgbIAIAAQgEgGgDgDIACgBIAMAIIgMgIIgCABIgEgCIgHgbIANACIgNgCQgPg6AAgaQAAgOAkgmQAfgiAWgHIg/gsIA/AsQgWAHgfAiQgkAmAAAOQAAAaAPA6QgPgEgagKQgpgRgJAAQgNAAgegNIgWgKIBBCAQAWAuAOAiQgEASAAAMIAHgXIAIAWQALBTALA4QAOBMALAcIABABQALAzAVBMIgQgpIAQApIAAAAQAAAqAvBFQAhAxAnAXQAMAGANAEQgKAHgEAIQgHgKgLgKIgKgJIADgBIAOAFIgOgFIgDABIAKAJQALAKAHAKQgEAHAAAHQAAAVgIAIQgHAGgUAEQhNAOg0AZQi5A8hEAUIgyAGIgHAAQgOgHgYgOIgEgCQgDgJAAgMQAAgXASgPQATgQAfAAQAEAAAQAIQAUAKAEAKQgEgKgUgKQgQgIgEAAQgfAAgTAQQgSAPAAAXQAAAMADAJIgOgIIgCgBQgXgMgUgEQgMgMAAgWQAAgaAKgIQAJgIAfAAQAWAAAJAFQAHADAMAQQgMgQgHgDQgJgFgWAAQgfAAgJAIQgKAIAAAaQAAAWAMAMIgSgDQgWgBgWgkIgCgCIgEgHQABgXAcAAIAXAGIgXgGQgcAAgBAXIgSgaIABgIIgKgOIADgDIAEgEIAAgBIAGADIAFADQALAGAgACIASAAIAGAAQANAAAOgGQAJgEAKgGQAYgQACAAQADAAAOALIADACQAFAAAVgKIAmgTQAogNAZACIAJACIAhgOIAfgOQAJgFAEgHQAIAFAJAAIADAAIAGgBQAFgBADgDQAIgGAAgNQAAgEgDgHIAOAXIgTAHIATgHIgOgXQgIgTgagoQghg3gagpQgdgsgVgaIABgBIgDgCIgJgLQgwhSgcgrQhJhug4hlQhFiAAAgqQAAgWAFgYIACgBIACgDIgCgCQAJgfASghQAQgcBMgLIAAgBIAAgJIAAgBQABgPAEgOIAEgPQAMgiAVgNQADAMAVAKQAUAIAUABQA9AABggEIADACQAdARApAaQATAMAjAXIgCAIQhsAsg0AJQhRAMg/gBQgrABgTgRQgWgSAAgrIAGgBIgGABQAAArAWASQATARArgBQA/ABBRgMQA0gJBsgsIACgIQgjgXgTgMQgpgagdgRIgDgCIgdgRIAdARQhgAEg9AAQgUgBgUgIQgVgKgDgMQgVANgMAiIgEAPQgzggAAgCQAAgIAMgMIABgBIAQgOQAegUAngRQgnARgeAUIgQAOIgBABIgIgGQgIgIAAgFQAAgKAOgLIACgCQAKgHAQgHQAcgOAagIQgaAIgcAOQgQAHgKAHIgCACQgSgFAAgKQAAgHAggTQgQgLAAgLQAAgTA4gZQAIgFAaAAQAMAAAGgEQAGgGAHAAQAWAAAQADQAMADAJADQAcANAyAGQAgAFAmAXIAMAHIA4AiQATAJAvARQBBgbBZgOQAkgFAWgIIAEABIAHABQAcAAAAghQAAgSgFghIgBgGQAAguAJgpQgJApAAAuIABAGIgBgGQgDgVAJg1IADgNQAMggAsgSIAMgGIArgOQAIgEAFgEIACgCQAEgDAAgEIgBgGIAHgYIANADIgNgDIgHAYQgGgrhigBQhEAPgHABIgSgJIBcgIQA0AAAKAFQAUAJAeAHIAGgRIAdhcIgdBcIgGARQgegHgUgJQgKgFg0AAIhcAIIgIgEQAAggAEgOQACgJANgXQgNAXgCAJQgEAOAAAgIAAAFIgxADIgsgEQgoAAgSADIgBAAQAQgqAOgVQgOAVgQAqIgKADIAKgDIABAAIgEANQgHAagEABIABgEIANgkIgNAkIgBAEIgIAYIgBgCIgDAPQgIAbAAAIIAAACIgCAJIgDAQIgBAFIhJBbQgUAbgPAiIgMgHQgmgXgggFQgygGgcgNQgJgDgMgDQAIgcARgeQAbgpATgkQAagxA4iPQA5hUAqggQA4gsBOAAQARABAOADQgLgegMgZIAVACQAlgBAxgiQAwgjALgfQgLAfgwAjQgxAiglABIgVgCQhJgIg6g/IgIgKIgJgQQAFgNAAgEQgCgVgSAAIgEAAIgEgKIAEAKIgGACIgDgFIAFgHIAAgCQAAgIgGgDIAAgBQgYg2gGgcIAAgHQAAgWAQgqIAFgNQAGgQADgOIACgTIABgFIAAgOIADgLIABgNQADgPAFgPIAFgKQASgmAfgDIABAAIAEAAIAEAAQAIABAHAGIAIAIIAFAGQAEgDAFgGIAEgHQAFgFALgDIAEAAIAGgBIAAACIgGgBIgYAPIAYgPIAGABIAAABQAAAKACACQALAFAEAAQACAAAFgGIAIgJIAJAEQgLAGgDAAIgDgBIADABQADAAALgGIAHACIAGgCIAHABIAEgGIAKgEIAKgEIARgEIARgDIAHAAIALABQAJABAIACQASAGAPANQAHAGAHAIIAGAIIAGAJIAGAJIAGAMIADAFIAIATIAAABIAJAYIABAEIAEAMIAEAQIAFATIAFAaIADAPIACAQQgGAIAAADIAGAQIAEADIAAAFIAAABIABAdIAAACQABAJALAoQAIAbACAQIgPASIgFAGIAAgCQAKgwAAgEQgOgmAAgQIACgIIgCAIQAAAQAOAmQAAAEgKAwIAAACQgHAPAAAUQAAAHAPAKQgHAVgGANIgHAKIABACIgEAFQAGAKACAPQACAEAGADQAJADAQAAQAiAAAcgCQAKAFADAAIAggIIAfAGQAJAAAZgKQAFAAAqAYQAtAZAIALQAkAxAAA7IgBAGQgCAQgPAeIgFAnIADAAIANgDIgJAIIgKALIACgLIABgFQgPAEAAABQAAgBAPgEIgBAFIgCALQgOAQAAAQIACAIIACAGQAGAJAJACIAHAAIBCgdQAhBJBHBaQAlAuAwA1QhpA/gWAKQgpAVg3ASIgaAFQhJAOglAEQAUACAQAIQAUAKANASIgCACQAFAFADAHIACgBQAXAoAABKQAAApgRAcIgSAYIgVAZIAVgZIgLAaIgKgBIgEAFQgKAMgbAHIg7gDIgQAAQhjAAggACQgJgFgIAAQgUABgGAOIgUACQAJAGAJAIQgJgIgJgGIAUgCQgCAGAAAIIAAACQACAHALAOIAGAHIADAEQAGAIAFAFIAEACIABAFQADAjAQAuQALAdAYA6IAAAEQAEAYAIANIACACIAIAhIADAOQAOA/AJAcQAMAkAQBHIAbB0QAdBrAmATIAKAEIgEAHIAEgHIACAEIABAPIgHgMIgEgHIgCgEIACAEIAEAHIAHAMIAAABQAAAgA0BGIAlAzIAOASIgEAKIAAgFQAAgEgKgTQAKATAAAEIAAAFQgQAigVAAQgMAAgPgGQgOgHgUAAQgYAAgaAIIAAAAIgOgCIgiACQgQADgTAFIgEACIAEgCQATgFAQgDIAigCIAOACQgYAIgqABIgJAAIgMABQgRACgOAIIgCACQgMAFgIAFQAIgFAMgFIgdAWQgtAjhMAAIgCAAgAiNTOIANgBIgNABgAFERmIgXANIAXgNQARgMAAgPQAAgbgIgOIgMgPIAAAIIAAgIIAMAPQAIAOAAAbQAAAPgRAMgAhgRrQAPgBARgEQgRAEgPABIgsgDIAsADIAAAAgAC/P/QgDgLgOgZQAOAZADALgAqZP1IANgBIgNABIgFgBIAFABIAAAAgAprPuQAZgFAlgKQglAKgZAFgArYPrQAEgCAGAAQgGAAgEACgAnhPKIgvANIAvgNIA4gRIg4ARgAiiPTQgXg6gFgSQAFASAXA6gAhmOzIARgDIglgiQgYgVgehDQgchAAAgXIABgLIgBALQAAAXAcBAQAeBDAYAVIAlAigAl/OtIBAgVIhAAVgAkaOjQgNgBgSgLQASALANABgAjbKVQABAVAIAVIAHAVIgHgVQgIgVgBgVIgBgYIABAYgAm6KTIAIgIIgIAIgADvIpIgKgjIAKAjgAA9HzQg/iSAAgcIAAgDIAAADQAAAcA/CSgAm1E3QAYBBAbAbIAAgMIAAAMQgbgbgYhBQgWhDgHgNQgEADAAAcQAAgcAEgDQAHANAWBDgACjE1IgFgHIAFAHgAl7CdIgHgFIAHAFgAiVAiIAPAKQAqAZBSAcIA/AdQAVAEAQAIQAMAHANgBQAiABAaghQARgWArhTQAKgSAchHQgcBHgKASQgrBTgRAWQgaAhgigBQgNABgMgHQgQgIgVgEIg/gdQhSgcgqgZIgPgKQAGgBAFAAQAFAAABADQgBgDgFAAQgFAAgGABIAAAAgAAXg0QAWAOAIADQAJgLARgyIACgFQASg3AMgSQAPgXANgfIAVg3IgLAEIALgEIgVA3QgNAfgPAXQgMASgSA3IgCAFIgTADQgxAIgQARIgPgGQhKgVgMgFQgpgfgRgMIgOgFIAOAFQARAMApAfQAMAFBKAVIAPAGIgFAFIAFgFQANAGAPAKgAEVhHQAHgGAWgCIAZACIAXADIATgBIgSgBIgYgBIgZgDIghgCIAGgRQAbhEAfgwQBQh4AUhUIAAAAIADgGIgDAGIAAAAQgUBUhQB4QgfAwgbBEIgGARIAhACIAZADIAYABIASABIgTABIgXgDIgZgCQgWACgHAGgABPhgIAggGIggAGgApkjEIgMAGIAMgGQAjgUAVgJQgVAJgjAUgAAnjCIgBgHIABAHgACgkbQARgFAggFQA3gJAfgIQAPgFAKgLQAMgOAFgWIANgkQgVADgqALQhIASg+AXQA+gXBIgSQAqgLAVgDIgNAkQgFAWgMAOQgmADgNAAQgCgFgcAAQg4ATggABIgIgFIAIAFQAggBA4gTQAcAAACAFQANAAAmgDQgKALgPAFQgfAIg3AJQggAFgRAFIADgHIgDAHIAAAAgAEUmiQhCAMg1AQQA1gQBCgMIABgBIACAAIAGgBIABAAIABgBIAdgEIAEgBIAFgBIARgBIABAAIAIgBIAAAAIAEAAIABAAIABABQAAAHgHAXIALgBIgLABQAHgXAAgHQAAghg2ABQgqgBiBAiQCBgiAqABQA2gBAAAhIgBgBIgBAAIgEAAIAAAAIgIABIgBAAIgRABIgFABIgEABIgdAEIgBABIgBAAIgGABIgCAAIgBABgAG4mpIAegSIgeASgAG4mpIANgjIgNAjgAgyq/QgGgZgIgXQAKACAIAEQgIgEgKgCQAIAXAGAZgAiFuSQAUATAwAAQAUAAAkgdQALgKAJgJQANgJAAgFIAAAAQgCgGgmgIIATACQAFAAARgIIAKAAQgDAJgIALQAIgLADgJIgKAAQgRAIgFAAIgTgCQgqgIhUgLIgFABIgZgEQAYA/APAQgAhVwJQAHAAAQgIQAOgIACgCQgCACgOAIQgQAIgHAAQgbAAAAgWQAAgDAGgFQgGAFAAADQAAAWAbAAIAAAAgACawbIgEgJIAEAJgAgsxdQAAACAYASQARANAIAEIAIACQANABACgNIAAgDIgBgEIAGACIgFAFIAFgFIgGgCIgBgCQAHAAAFgCQAQgGAAgaIgBgGIAAgGQAVgJAXgLQgXALgVAJIAAAGQgBgDgDgCQgDgBgFAAQgHAAgLAKIgQAEIAQgEIgEAFIgGAGIgHgFIABgCIgDABQgEgCgGgBQgUAAgKAFQgIgCgIgGIABgGIADAFIgDgFIADgMQAEgRADgGQgNAPAAANQAAADADAEIgBAGQAIAGAIACQgIAEAAAHgAgCw3IAHgBIgHABQgJAAgVgQQgWgRAAgMIACgMIgIgHIAIAHIgCAMQAAAMAWARQAVAQAJAAIAAAAgAiqw3QATAAAMgQIgHgCIAHACQgMAQgTAAQgPAAgTgUIgDgDQATATAWAAQAGgBAIgHIAFgEIABgCIABgBQAMgNAAgGIAAgCIABgFIgBgFIADgHIgDAHIgBgIQgEgOgMgBQgEABgEAFIgEgCQgZgPgWgDIgFgFIAFAFIgJAAIgCAAQgQAAAAASIASAhIALANIADADQATAUAPAAIAAAAgAAhxHIAGACIgGgCIAFgGIgFAGIAAAAgAiLxHQAKgOAFgaIAKAAQAJAAALgEQgLAEgJAAIgKAAIgGgBIAGABQgFAagKAOgACHxrQAAAMAKABQgKgBAAgMIAFgNIgFANIAAAAgAkRxrQAHgGAIAAQgGgKAAgOQAAAOAGAKQgIAAgHAGgAiCxwQAEgMAAgHQAAgagKgQQgKgQgOAAQgaAAgUAYQgJALgFAMQAFgMAJgLQAUgYAaAAQAOAAAKAQQAKAQAAAaQAAAHgEAMIgEgBIAEABIAAAAgAA1x5IgEABIAEgBIAAgCQAAgWgQgSQgQgSgUAAQgPAAgUAUIgGAGIgBACIABgCIAGgGQAUgUAPAAQAUAAAQASQAQASAAAWIAAACgAB5ycQAAAIAKAGIAEADIgEgDQgKgGAAgIIAFgPIgFAPIAAAAgAj+y+IgIAiIAIgiQAKgHAAgFIgEgLQAHgQAPgPIAEgEIAIADQADAAAFgRIAGgFIgGAFIAAgBQAFgOAGgDQgGADgFAOIAAABIgQAOIgGgBQgHAAgHAMQgGAKAAAIIAAAGIgCAIIgEAPIgEAEIAEgEIAAAAgABpzNQAAADAMAGQgMgGAAgDIAEgKIgEAKIAAAAgABbzpIAJABIgJgBIADgIIgDAIIAAAAgAiz0RQAGAGAKACQgKgCgGgGIgHgHIAHAHgAAM0dIAXgGIgXAGQgLAAgBgKQABAKALAAgAiKTqQADAFAGADIgHABQAAgEgCgFgADnTvIAAAAgAiKTqIAAAAgAimTVIgQgGIApgBIgBAMQAAAHACAGQgHgMgTgGgAoXR/IAHAAIAygGQgkALgEAAQgFAAgMgFgAoXR/IAAAAgAneR5IAAAAgAGQQGIAAAAgACIOwIgKgWIAAgFIgBgLIAOAYIgDAOIAAAAgAB9OKIAAAAgAlbMoIgbgoIgWghIADgFQAaApAhA3IgNgSgABDL8IgEgGQAEADAAADIAAABIAAgBgABDL8IAAAAgAA/L2IAAAAgAnBKOIgFgIIAJALIgEgDgAnGKGIAAAAgAg+JBQgWgegfhGIBQCIIAKAQIglg0gAhzHdIAAAAgAB/DxIAAAAgAjfDTIAAAAgAiVAiIAAAAgAAXg0QgPgKgNgGQAQgRAxgIIATgDQgRAygJALQgIgDgWgOgAF1hLQAlgEBJgOIAagFIgxAPQgkALgPAHQgQgIgUgCgAgFhEIAAAAgAgFhEIAAAAgAlThaIAAAAgAH9hiIAAAAgACgkbIAAAAgAi6mGIAAAAgAi6mIQAAgIAIgbIgIAlIAAgCgAFemOIAAAAgAiymrIAAAAgAiYn4IAAAAgAHZorQAPgeACgQIAIAMQAMAVAAADQAHAlAFAKIgUgDIgSACIgNADIgDAAIAFgngAhArvIAAAAgACRsoIAHgKIgGAMIgBgCgAhXsmIAAAAgACYsyIAAAAgAiFuSQgPgQgYg/IAZAEQgDABgEAEQgFAEAAADIANAWIgCAFQAEAJALAMQAMAMAJABQATANAXABQA8gaAVgPQgJAJgLAKQgkAdgUAAQgwAAgUgTgACduIIAAAAgAj+utIAAAAgAALuvIAAAAgAkSvGIgBgEIgEgKQgOgkgBgfQAGAcAYA2IAAABQgEgCgGAAgAgQvLIAAAAgAkmwXIAAAAgAiLxHIAAAAgAAbxJIAAAAgAjPxOIAAAAgAAGxpIgCgBIADgBIgBACIAAAAgAAXxvIAAAAgAgzx2IAAAAgAg2x9QAAgNANgPQgDAGgEARIgDAMQgDgEAAgDgAj+y+IAAAAgAj6zNIACgIIAEALQAAAFgKAHIAEgPgAj4zVIAAgGQAAgIAGgKQAHgMAHAAIAGABIgEAEQgPAPgHAQIAAAAgAjez4IAQgOQgFARgDAAIgIgDgAh30aIAAAAg");
	this.shape_8.setTransform(97.5,142.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0099FF").s().p("ACJGcQghgQgKAAIgQgCIALgaIASgXQARgcAAgpQAAhKgXgpIgIgNQgNgSgUgKQAPgIAkgKIAxgQQA3gSApgUQAWgLBpg9IAFgEIAEgCQAOAEAVAUQAcAbAVApQAmBKAJAYQANAjAAAlQAAAvgYAvQgIARgKANIglARQh/A2iYAAQgHAAgigPgADuBEQgQAGg+AMQA+gMAQgGQA3gUBlg7IgLgNIALANQhlA7g3AUgABbCWIACgCIAIANIgCABQgDgHgFgFgAk2gPIAAgCQAhgMAAgQIgDg1QAFAhAAASQAAAggcAAIgHAAgAk6gQIAEgBIAAACIgEgBgAlRhbQgagagsgMQhCgIgXgGQgngMAAgyIAIgkIAEgNIAIgZQAEgBAHgZIAEgOQASgCAoAAIAsAEIAygEIAAgEIAIAEIASAIQAHAABEgPQBiAAAGArIABAGQAAAEgEAEIADgOIgDAOIgCACQgFAEgIAEIgrAOIgMAFIgFABQgrALgHAhIgBAGIgDAMQgJA2ADAVIABAGIADA1QAAAQghAMQgPg+gMgMgAk1jXIAAgGIAAAGQgPgKgJgLQgQgTAAgvIABgTIgBATQAAAvAQATQAJALAPAKIAAAAgAlclBIAIAAIgIAAgAkYhiIAAAAgAkQi/IAAAAgAkPjFQAHghArgLIAFgBQgsATgMAgIABgGgAjYjyIAAAAgAB5kCQgJgCgGgJIgCgGQAHgWAFgSQgFASgHAWIgCgHQAAgRAOgQIAKgKIAJgJIASgBIAUADIARADQgKgMAAgNIAMg1QABgGASgIQARgHAGADIAAAaQgMApggADQAPAAA0gOQAPAAAEAZQAAAWguADIgogKIAGAIQgBAJgIAKQgLANgWANIghASIAhgSQAWgNALgNIACAFIAFALIhCAdIgHgBg");
	this.shape_9.setTransform(132.4,124.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol12, new cjs.Rectangle(-1,0,292.5,284.2), null);


(lib.Symbol9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF00FF").ss(4,1,1).p("Ai8i7IF5F4");
	this.shape.setTransform(18.9,18.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FF0000").ss(4,1,1).p("Ai8i8IF5F5");
	this.shape_1.setTransform(18.9,18.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},3).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2,-2,41.7,41.7);


(lib.goNext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,11.3).s().p("AhLAqQghgRABgYQgBgZAhgRQAfgSAsAAQAsAAAgASQAgARAAAZQAAAYggARQggASgsAAQgsAAgfgSg");
	this.shape.setTransform(22.8,8.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.502)").s().p("AhUhcICpBdIipBcg");
	this.shape_1.setTransform(25.1,20.4);

	this.blinker = new lib.general_buttoncolor();
	this.blinker.parent = this;
	this.blinker.setTransform(23.4,20.1,1.5,1.5,0,0,0,11.9,11.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,14.8).s().p("AhjA3QgqgXABgfQgBggAqgXQAqgYA5AAQA6AAAqAYQApAXAAAgQAAAfgpAXQgqAYg6AAQg5AAgqgYg");
	this.shape_2.setTransform(23.4,8.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("rgba(0,0,0,0.502)").ss(1,1,1,3,true).p("AAACxQhIAAg0g0Qg1g0AAhJQAAhIA1g0QA0g0BIAAQBKAAA0A0QA0A0AABIQAABJg0A0Qg0A0hKAAg");
	this.shape_3.setTransform(23.3,20.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["rgba(103,103,103,0.839)","rgba(134,134,134,0)"],[0.678,0.918],-0.8,0,0,-0.8,0,24.9).s().p("AitClQhEhFAAhgQAAhgBEhEQBEhEBiAAQBfAABCAwQBBAvAWCrQAVCskNAbQhiAAhEhEgAgICRQBGAAAygwIABgBIAEgDQA0g0AAhIQAAhJg0g0IgGgGIAAAAQgyguhEAAIgBgBIAAAAIgBAAIAAABQhEAAgyAuIgBABIgCACIgCABIAAAAIgBACQg1A0AABJQAABIA1A0IABABIACACQAzAxBGAAIAAAAIABAAIgBAAIAAAAQhGAAgzgxIgCgCIgBgBQg1g0AAhIQAAhJA1g0IABgCIAAAAIACgBIACgCIABgBQAyguBEAAIAAgBIABAAIAAAAIABABQBEAAAyAuIAAAAIAGAGQA0A0AABJQAABIg0A0IgEADIgBABQgyAwhGAAIAAAAIAAAAIAAAAIAAAAg");
	this.shape_4.setTransform(24.2,23.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},2).wait(1));

	// Layer 2
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#33FFFF").s().p("AipCqQhGhHAAhjQAAhiBGhGQBGhHBjAAQBjAABHBHQBGBGAABiQAABjhGBHQhHBGhjAAQhjAAhGhGg");
	this.shape_5.setTransform(24.4,21.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0099FF").s().p("AipCqQhGhHAAhjQAAhiBGhGQBGhHBjAAQBjAABHBHQBGBGAABiQAABjhGBHQhHBGhjAAQhjAAhGhGg");
	this.shape_6.setTransform(24.4,21.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.5,46.7);


(lib.blank = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.blank_gr("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(32.6,17,1,1,0,0,0,32.5,17);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.blank, new cjs.Rectangle(0.1,0,65,34), null);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Tween25("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(80.5,19.3,0.998,0.998,53.2,0,0,6.6,-0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:7,regY:-0.1,scaleX:1,scaleY:1,rotation:0,x:12.6,y:13.5},12).wait(5));

	// Layer 9
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AgtgZQAFACADACQAEACADACQA5AdASAO");
	this.shape.setTransform(73.4,18.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AAjAWQgbgWgrgV");
	this.shape_1.setTransform(77.7,14.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF0000").s().p("AAdAqQgSgPg5gcIgHgEIgIgEIAAggIA1AAQAqAVAcAWIAAAog");
	this.shape_2.setTransform(75,16.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1,1,1).p("AAwAAQgXgTgigRQgCgCgDgBAgvACQAGADAGADQAlAVAOAL");
	this.shape_3.setTransform(76.4,16.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF0000").s().p("AAQAoQgOgLglgVIgMgGQATgTAOgWIAFADQAiARAXATIAAAog");
	this.shape_4.setTransform(76.4,16.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#000000").ss(1,1,1).p("AA/ALQgfgagzgWQgGgDgGgCQgEgCgEgCQgFgCgFgCAg+gCQAEACAFACQAEACAEACQA5AeATAP");
	this.shape_5.setTransform(74.9,15.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF0000").s().p("AAfAzQgTgPg5geIgIgEIgJgEIADgVIABAAIAJgbIAKAEIAIAEIAMAFQAzAWAfAaIAAAog");
	this.shape_6.setTransform(74.9,15.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#000000").ss(1,1,1).p("ABuAYQgfgZg0gXQg2gZhBgOAhtgXQAtAKAhAPQBWAsAXAS");
	this.shape_7.setTransform(70.2,14.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF0000").s().p("ABOBAQgXgShWgsQghgPgtgKIAHgRIAKgXQBBAOA2AZQA0AXAfAZIAAAog");
	this.shape_8.setTransform(70.2,14.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#000000").ss(1,1,1).p("AB5AbQgggagzgWQhEgfhVgOAh4gZQA7ALAoATQBWAsAXAS");
	this.shape_9.setTransform(69.1,14.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF0000").s().p("ABYBDQgXgShVgsQgpgTg7gKIACgOIADgcQBVAOBEAfQAzAWAgAaIAAAog");
	this.shape_10.setTransform(69.1,14.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#000000").ss(1,1,1).p("ACYAgQgggbgzgWQhfgqh9gLAiPgbQBfAJA5AcQBXArAXAS");
	this.shape_11.setTransform(66.1,13.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FF0000").s().p("AB3BHQgXgShXgrQg5gchfgJIgCgPIgFgcQB8ALBfAqQAzAWAfAbIAAAng");
	this.shape_12.setTransform(66.1,13.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#000000").ss(1,1,1).p("AC6AiQgfgbg0gWQh4g1iogEAi2gdQCTACBPAnQBWArAYAS");
	this.shape_13.setTransform(62.6,13.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FF0000").s().p("ACZBJQgXgShWgrQhPgniTgCIgCggIgBgLQCoAEB4A1QA0AWAfAbIAAAng");
	this.shape_14.setTransform(62.6,13.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#000000").ss(1,1,1).p("ADjAiQgfgbg0gWQiDg6i5AAQgbAAgbACAjXgcQAYgBAYAAQCmgBBWAqQBXArAXAT");
	this.shape_15.setTransform(58.5,13.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FF0000").s().p("ADDBKQgXgThXgrQhWgqimABIgvABQgDgZgJgSQAbgBAbgBQC5AACDA7QA0AVAfAbIAAAog");
	this.shape_16.setTransform(58.5,13.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#000000").ss(1,1,1).p("AEGAiQgfgbg0gWQiDg6i5AAQhAAAg8AIAj0gWQA1gHA8AAQCkgBBXAqQBXArAXAT");
	this.shape_17.setTransform(55,13.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FF0000").s().p("ADmBKQgXgThXgrQhXgqikABQg8AAg1AHIgCgFQgGgUgJgSQA8gHBAgBQC5AACDA7QA0AVAfAbIAAAog");
	this.shape_18.setTransform(55,13.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#000000").ss(1,1,1).p("AErAiQgfgbg0gWQiEg6i4AAQhnAAhfAVAkbgIQBWgUBmgBQClgBBXAqQBWArAXAT");
	this.shape_19.setTransform(51.3,13.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FF0000").s().p("AEKBKQgXgThWgrQhXgqilABQhmABhWAUIgDgUQgDgNgJgLQBfgUBngBQC4AACEA7QA0AVAfAbIAAAog");
	this.shape_20.setTransform(51.3,13.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#000000").ss(1,1,1).p("AFdAiQgfgbg0gWQiEg6i4AAQieAAiMAxAlMAXQB5gzCmgBQClgBBXAqQBWArAYAT");
	this.shape_21.setTransform(46.3,13.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FF0000").s().p("AE8BKQgXgThWgrQhXgqilABQimABh4AzIgRguQCMgyCeAAQC5AACDA7QA0AVAfAbIAAAog");
	this.shape_22.setTransform(46.3,13.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_4},{t:this.shape_3}]},1).to({state:[{t:this.shape_6},{t:this.shape_5}]},1).to({state:[{t:this.shape_8},{t:this.shape_7}]},1).to({state:[{t:this.shape_10},{t:this.shape_9}]},1).to({state:[{t:this.shape_12},{t:this.shape_11}]},1).to({state:[{t:this.shape_14},{t:this.shape_13}]},1).to({state:[{t:this.shape_16},{t:this.shape_15}]},1).to({state:[{t:this.shape_18},{t:this.shape_17}]},1).to({state:[{t:this.shape_20},{t:this.shape_19}]},1).to({state:[{t:this.shape_22},{t:this.shape_21}]},1).to({state:[{t:this.shape_22},{t:this.shape_21}]},1).to({state:[{t:this.shape_22},{t:this.shape_21}]},1).wait(5));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(56.3,9.4,34.7,22.2);


(lib.UI = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//Menu button -----------------------------------------
		this.btn_menu.addEventListener("click", openMenu.bind(this));
		
		//volume buttons -----------------------------------------
		this.vol_dwn.addEventListener("click", volDwn.bind(this));
		this.vol_up.addEventListener("click", volUp.bind(this));
		this.vol_mute.addEventListener("click", volMute.bind(this));
		
		//Nav buttons -----------------------------------------
		this.btn_goNext.addEventListener("click", openNext.bind(this));
		this.btn_goBack.addEventListener("click", openPrev.bind(this));
		
		//background music ---------------------------------------
		var bgm = createjs.Sound.play('bgmPA',{loop:-1});
		//var vo = createjs.Sound.play('VO');
		
		//volume vars -----------------------------------------
		var mute= false;
		bgm.volume = 0.05;
		var prev_vol = bgm.volume;
		
		//Menu function -----------------------------------------
		function openMenu(){
		
		 window.open ("../miniMenu/miniMenu.html","_self");
		}
		
		//volume functions -----------------------------------------
		function volDwn()
		{
			createjs.Sound.volume = createjs.Sound.volume -0.05;
			if(!mute){
				bgm.volume -= 0.05;
				prev_vol = bgm.volume;
			}
			console.log(bgm.volume);
			console.log(prev_vol);
		}
		function volUp()
		{
			createjs.Sound.volume = createjs.Sound.volume +0.05;
			if(!mute){
				bgm.volume += 0.05;
				prev_vol = bgm.volume;
			}
			console.log(bgm.volume);
			console.log(prev_vol);
		}
		
		function volMute()
		{
			if(!mute){
				mute = true
				bgm.volume = 0;
			}
			else{
				mute = false;
				bgm.volume = prev_vol;
			}
			console.log(mute);
		}
		
		
		//Nav functions -----------------------------------------
		
		function openNext(){
		
		 window.open ("predAdj_finish.html","_self");
		}
		
		function openPrev(){
		
		 window.open ("predAdj_scene6.html","_self");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// mute
	this.vol_mute = new lib.vol_mute();
	this.vol_mute.parent = this;
	this.vol_mute.setTransform(31.8,2.1,1,1,0,0,0,15,14.1);
	new cjs.ButtonHelper(this.vol_mute, 0, 1, 2, false, new lib.vol_mute(), 3);

	this.timeline.addTween(cjs.Tween.get(this.vol_mute).wait(1));

	// main
	this.instance = new lib.Copyright("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-220.6,376.5);

	this.btn_goBack = new lib.goNext();
	this.btn_goBack.parent = this;
	this.btn_goBack.setTransform(-438,335.3,1,1,0,0,180);
	new cjs.ButtonHelper(this.btn_goBack, 0, 1, 2, false, new lib.goNext(), 3);

	this.btn_goNext = new lib.goNext();
	this.btn_goNext.parent = this;
	this.btn_goNext.setTransform(-1.7,335.3);
	new cjs.ButtonHelper(this.btn_goNext, 0, 1, 2, false, new lib.goNext(), 3);

	this.vol_up = new lib.vol_pos();
	this.vol_up.parent = this;
	this.vol_up.setTransform(-6.7,2.6,1,1,0,0,0,9,7);
	new cjs.ButtonHelper(this.vol_up, 0, 1, 2, false, new lib.vol_pos(), 3);

	this.vol_dwn = new lib.vol_neg();
	this.vol_dwn.parent = this;
	this.vol_dwn.setTransform(-28.7,2.6,1,1,0,0,0,9,7);
	new cjs.ButtonHelper(this.vol_dwn, 0, 1, 2, false, new lib.vol_neg(), 3);

	this.btn_menu = new lib.menu_main();
	this.btn_menu.parent = this;
	this.btn_menu.setTransform(-89.6,2.6,1,1.143,0,0,0,23.4,10.5);
	new cjs.ButtonHelper(this.btn_menu, 0, 1, 2, false, new lib.menu_main(), 3);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.5,1,1).p("AAYBrQgBgLgUgUQgQgRgKAAIAAh1QAKAAASgTQATgTAAgKg");
	this.shape.setTransform(-47.7,2.3,0.687,0.681);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AADBMQgQgRgKAAIAAh1QAKgBASgSQATgTAAgJIAADTQgBgKgUgUg");
	this.shape_1.setTransform(-47.7,2.3,0.687,0.681);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s("#000000").ss(1.5,1,1).rr(-0.75,-3.45,1.5,6.9,0.2);
	this.shape_2.setTransform(-52.2,2.3,1,1.003);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1.5,1,1).p("AAHAAQAAAJgHAHQgCAEgEACIAAgrQAEACACAEQACACACACQADAFAAAGg");
	this.shape_3.setTransform(-43.2,2.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgGgUQAEABACAEIABAAIADAFQADAEAAAGQAAAJgGAHIgBAAQgCAEgEABg");
	this.shape_4.setTransform(-46.5,2.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.btn_menu},{t:this.vol_dwn},{t:this.vol_up},{t:this.btn_goNext},{t:this.btn_goBack},{t:this.instance}]}).wait(1));

	// vol_frame
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s("#000000").ss(1.5,1,1).rr(-33,-12,66,24,4.9);
	this.shape_5.setTransform(-24.7,2.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_5).wait(1));

}).prototype = getMCSymbolPrototype(lib.UI, new cjs.Rectangle(-486.5,-13,534.3,399), null);


// stage content:
(lib.predAdj_Scene7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{scene7:0,scene7repeat:37});

	// timeline functions:
	this.frame_0 = function() {
		playSound("funky_lead");
	}
	this.frame_11 = function() {
		playSound("sheishappy");
	}
	this.frame_36 = function() {
		/* _root.gonow = true;*/
	}
	this.frame_64 = function() {
		/* gotoAndPlay("scene7repeat");
		stopAllSounds();*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(25).call(this.frame_36).wait(28).call(this.frame_64).wait(1));

	// Layer 3
	this.instance = new lib.Symbol12();
	this.instance.parent = this;
	this.instance.setTransform(399,223.9,0.653,0.653,0,0,0,151,144);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(65));

	// Layer 2
	this.instance_1 = new lib.Symbol5();
	this.instance_1.parent = this;
	this.instance_1.setTransform(222.2,45.3,1.694,1.533,0,0,0,45,12.8);

	this.instance_2 = new lib.Symbol9();
	this.instance_2.parent = this;
	this.instance_2.setTransform(256.8,96,1,1,0,0,0,18.9,18.9);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF3FFF").s().p("AglB3QgHgHAAgJQAAgIAhg4Igjg0IgxhOQgEgGAAgFQAAgJAHgHQAHgFAJAAQAKAAAJAKIALATIAbAtQAQAcALARIAjhJIAOggQAGgOAPAAQAIAAAHAFQAGAGAAAKQAAAFgJASIgfBHQgVAtgOAaIgZAwQgJANgMAAQgIAAgHgFg");
	this.shape.setTransform(381,93);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF3FFF").s().p("AhGB3QgGgGAAgJIAAgrQAAgYADgvQADgwAAgYQABgpAWACIAOgCIAYgBQAdAAAbAUQAeAWAAAgQAAAoggAXQgcAVgmAAIgNgCIgBBIQAAAJgGAGQgGAGgIAAQgKAAgFgGgAgchTIAAAWIgEA2IALABQAYAAAPgLQARgMAAgVQAAgNgQgKQgPgKgRAAIgJAAIgGAAg");
	this.shape_1.setTransform(362.8,92.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF3FFF").s().p("AhGB3QgGgGAAgJIAAgrQAAgYADgvQADgwAAgYQAAgpAXACIAPgCIAWgBQAeAAAbAUQAeAWAAAgQAAAoggAXQgcAVgmAAIgNgCIgBBIQAAAJgGAGQgFAGgKAAQgIAAgGgGgAgdhTIAAAWIgDA2IALABQAXAAARgLQARgMAAgVQAAgNgQgKQgQgKgRAAIgJAAIgHAAg");
	this.shape_2.setTransform(345.7,92.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF3FFF").s().p("ABQB2QgNgBgMgcQgJgTgFgYQgMACgaACIglAEQgHARgSAjQgHALgMAAQgJAAgHgGQgHgGAAgJQAAgIAXguQgCgFAAgEQABgIAPgEQAWglAbgpQAmg8AJAAQARAAAGAVIAKAyQAJAtAOA5IAIAVQAGANAAAHQAAAJgHAGQgGAGgIAAIgBAAgAgLAPIAVgDIAWgCIgLgzIggA4g");
	this.shape_3.setTransform(325.2,93);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF3FFF").s().p("ABDB3QgHgGAAgIIgBgjIgBgiIAAgPQgYAAgjAHIg8AMIgDAgIgBAiQAAAIgGAGQgGAFgJAAQgKAAgGgGQgGgFAAgJQAAgPADgfQADgfAAgPIABg6IABg7QAAgIAGgGQAGgGAJAAQAJAAAGAGQAGAGAAAJIgBAkIgBAjIgBAPIAAAQIA8gLQAigHAZgBIACg4QAAgMAIgQQAIgUALAAQAJAAAGAFQAHAGAAAKIgBAEQgDAMAAAIIgBAOIgBANIgBAsIgCAsIACAiIACAjQAAAIgGAGQgGAGgJAAQgKAAgGgGg");
	this.shape_4.setTransform(301.7,92.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF0000").s().p("AhUBmQgTgPAAgTQAAgKAGgHQAGgGALAAQAOAAAGAOQAJAUAgAAQAZAAAagMQAagMAAgPQAAgTgRgHQgLgEgigBQgbAAgVgJQgdgNAAgYQABgfAggZQAggZAlAAQAQAAAWAHQAcAIAAAMQAAAIgGAGQgGAHgKAAQgHAAgPgDQgOgDgIAAQgUAAgRAKQgTAJAAAMQAAAGAGAEQAGADALACIAnACQAjADAUARQAWARAAAhQAAApguAVQgjAPgsAAQgoAAgXgRg");
	this.shape_5.setTransform(214.5,93.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF0000").s().p("AhKBxQgFgGAAgIQgBgJAHgHQAGgFALgBQALAAATgCIAAhHQAAgpADgnIgjABQgJAAgGgGQgHgGABgJQAAgJAFgGQAGgGAJAAQANgCAhAAQAdAAAuAHQASADABATQgBAJgGAGQgHAGgHAAQgHgBgigEQgCAcAAAwIgBBGIArgBQAJAAAHAGQAFAGABAKQgBAIgFAHQgHAFgKAAIgbABIgaAAQgJAAgWADQgVACgLAAQgJABgHgHg");
	this.shape_6.setTransform(194.5,92.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AhIB3QgRgPAAgyQAAgVADgpQADgqAAgVIgCgQIgBgQQAAgYAWAAQAHAAAFAEIAjgHQAQgCAOAAQAnAAAYAJQAOAGAAAOQAAAIgGAGQgGAHgJAAIgHAAQgZgHgYAAQgMAAgMACQgOABgPAEIgBA+IA8gGIAmgDQAJAAAGAGQAHAGAAAKQAAARgUADIglADIhCAGIgBAgQAAAeADAFQACACASAAIAcgBIAdAAIAKgBIAJgBQAJAAAGAFQAIAGAAAKQAAASgTADQgPADgxAAQgzAAgPgOg");
	this.shape_7.setTransform(132.4,92.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("ABDB3QgHgGAAgIIgBgjIgBgiIAAgPQgYAAgjAHIg8AMIgDAgIgBAiQAAAIgGAGQgGAFgJAAQgKAAgGgGQgGgFAAgJQAAgPADgfQADgfAAgPIABg6IABg7QAAgIAGgGQAGgGAJAAQAJAAAGAGQAGAGAAAJIgBAkIgBAjIgBAPIAAAQIA8gLQAigHAZgBIACg4QAAgMAIgQQAIgUALAAQAJAAAGAFQAHAGAAAKIgBAEQgDAMAAAIIgBAOIgBANIgBAsIgCAsIACAiIACAjQAAAIgGAGQgGAGgJAAQgKAAgGgGg");
	this.shape_8.setTransform(110,92.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AhUBmQgTgPAAgTQAAgKAGgHQAGgGALAAQAOAAAGAOQAJAUAgAAQAZAAAagMQAagMAAgPQAAgTgRgHQgLgEgigBQgbAAgVgJQgdgNAAgYQABgfAggZQAggZAlAAQAQAAAWAHQAcAIAAAMQAAAIgGAGQgGAHgKAAQgHAAgPgDQgOgDgIAAQgUAAgRAKQgTAJAAAMQAAAGAGAEQAGADALACIAnACQAjADAUARQAWARAAAhQAAApguAVQgjAPgsAAQgoAAgXgRg");
	this.shape_9.setTransform(86.3,93.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgRAPQgIgHAAgIQAAgHAIgHQAIgGAJAAQALgBAHAHQAIAGAAAIQAAAIgIAHQgHAHgLgBQgJABgIgHg");
	this.shape_10.setTransform(278.9,323.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AguB5QgGgGgBgJQAAgOAihIQgSghgkhCIgJgMQgDgHAAgGQgBgJAHgGQAHgGAIAAQALAAAGAHQAWAeAdA7IAUgtQALgWAKgSQAHgMAMABQAJAAAGAFQAIAHAAAIQgBAFgCAFIg2BuQgUApgKAbIgKAdQgGAPgOAAQgJgBgHgFg");
	this.shape_11.setTransform(263.1,320.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AhBB9QgGgGAAgJIABg6IAAg9QgBgigCgYIgCgfQAAgNAGgJQAHgKALAAQAJAAAGAFQAGAGAAAJIgBABQALgGALgCQAJgDALAAQAkAAAQAeQANAXAAAlQAAAhgUAWQgVAYgjAAQgNAAgOgDIgBBAQAAAJgGAGQgGAGgJAAQgJAAgHgGgAgIhKQgKAEgLAKQACAgAAAfQAOAFANAAQAQAAAJgLQAHgKAAgRQAAgWgBgIQgFgTgPAAQgKAAgJAFg");
	this.shape_12.setTransform(246,319.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AhBB9QgGgGAAgJIABg6IAAg9QgBgigCgYIgCgfQAAgNAGgJQAHgKALAAQAJAAAGAFQAGAGAAAJIgBABQALgGALgCQAJgDALAAQAkAAAQAeQANAXAAAlQAAAhgUAWQgVAYgjAAQgNAAgOgDIgBBAQAAAJgGAGQgGAGgJAAQgJAAgHgGgAgIhKQgKAEgLAKQACAgAAAfQAOAFANAAQAQAAAJgLQAHgKAAgRQAAgWgBgIQgFgTgPAAQgKAAgJAFg");
	this.shape_13.setTransform(228.9,319.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAmBIQgPAHgLADQgLAEgGAAQgmAAgTgUQgSgUAAgpQAAgkAbgbQAcgbAmAAQAPAAATAIQAYALAAANQAAAFgEAFIgCAPIgBAWQAAAdAEANIAHAQIAGAPQAAAIgGAFQgGAGgIAAQgIAAgPgOgAgVgfQgQARAAAVQAAAVAHAKQAIALAPAAQAIAAAJgDQAJgEAHgGQgEgkAAgTIABgLIACgPIgGgCIgEgBQgUAAgQARg");
	this.shape_14.setTransform(211.3,315.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AAlByQgEgMgEgXQgCgWAAgPIABgLIAAgMIAAgOQgCgHgHAAQgRAAgNAPQgIAIgMAXQAAA4gFALQgHAOgMAAQgJgBgHgFQgHgHAAgIIABgJQABgDABgmQgBggAChIIAAgFIABgZIgCgOIgBgOQAAgJAHgGQAGgGAJAAQAPAAAGARQACAJAAATIAAAgIgBAeQAMgLANgFQALgGAPAAQAbAAALAPQAKAMABAVIACAoIADAeIAGAeIAAAGQAAAJgGAGQgHAFgJAAQgQAAgEgQg");
	this.shape_15.setTransform(193.4,311.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgsBRQgXgIAAgRQAAgQATAAQAHAAANAEQAOAFAIAAQAeAAAAgNQAAgHgVgLQgggOgJgFQgWgPAAgWQAAggAhgLQAUgGAnAAQAPAAAIAEQAKAGAAAOQAAAcgPAAQgQAAgCgNIgOgBQgkAAAAALQAAAGAWAKQAfAOAKAIQAXAPAAAVQAAAbgZAOQgUALgcAAQgVAAgSgHg");
	this.shape_16.setTransform(161.9,315.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgTByQgGgGAAgJIAAgdIgBgdQAAgNACgVIABgiQAAgJAGgGQAGgGAKAAQAIAAAGAGQAGAGAAAJIgBAiIgCAiIABAdIAAAdQAAAJgGAGQgGAFgIAAQgKAAgGgFgAgOhPQgHgGAAgKQAAgKAHgHQAIgGAJAAQAKAAAHAGQAHAHAAAKQAAAKgHAGQgHAHgKAAQgJAAgIgHg");
	this.shape_17.setTransform(150.2,312.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("Ag1BEQgagUAAgkQAAgmAVgcQAXgeAmAAQAbAAASAJQAYALAAAZQAAARgTANQgJAGgaALIg0AXQAHAIALAEQALAEAMAAQAVAAAPgIQANgIAIAAQAQAAAAAQQAAASgaALQgWAJgZAAQgkAAgYgRgAgVglQgKAKgGAUIAjgQQAUgJANgIQgLgGgRAAQgNAAgLAJg");
	this.shape_18.setTransform(122.3,315.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AAlByQgEgMgEgXQgCgWAAgPIABgLIAAgMIAAgOQgCgHgHAAQgRAAgNAPQgIAIgMAXQAAA4gFALQgHAOgNAAQgIgBgHgFQgHgHAAgIIABgJQABgDABgmQAAggABhIIAAgFIABgZIgCgOIgBgOQAAgJAHgGQAGgGAJAAQAPAAAGARQADAJgBATIAAAgIgBAeQALgLAOgFQAMgGAOAAQAbAAALAPQAKAMABAVIACAoIADAeIAFAeIABAGQAAAJgGAGQgHAFgJAAQgQAAgEgQg");
	this.shape_19.setTransform(104.6,311.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AhUBmQgTgPAAgTQAAgKAGgHQAGgGALAAQAOAAAGAOQAJAUAgAAQAZAAAagMQAagMAAgPQAAgTgRgHQgLgEgigBQgbAAgVgJQgdgNAAgYQABgfAggZQAggZAlAAQAQAAAWAHQAcAIAAAMQAAAIgGAGQgGAHgKAAQgHAAgPgDQgOgDgIAAQgUAAgRAKQgTAJAAAMQAAAGAGAEQAGADALACIAnACQAjADAUARQAWARAAAhQAAApguAVQgjAPgsAAQgoAAgXgRg");
	this.shape_20.setTransform(84,312.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#000000").ss(4,1,1).p("A7yC9ISsAAIAAl4Ao/C9MAkyAAA");
	this.shape_21.setTransform(226.9,96);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance_2},{t:this.instance_1}]}).wait(65));

	// Layer 1
	this.UI = new lib.UI();
	this.UI.parent = this;
	this.UI.setTransform(548,53.9,1,1,0,0,0,54,40.5);

	this.instance_3 = new lib.Back("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(275.5,208.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3},{t:this.UI}]}).wait(65));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(282.5,200.6,534,398.7);
// library properties:
lib.properties = {
	id: 'C058E91979EAD3469C2E7AE4427D2788',
	width: 550,
	height: 400,
	fps: 12,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"sounds/wrong_answer.mp3", id:"wrong_answer"},
		{src:"sounds/funky_lead.mp3", id:"funky_lead"},
		{src:"sounds/High_Screaming_Gtr.mp3", id:"High_Screaming_Gtr"},
		{src:"sounds/powersynth.mp3", id:"powersynth"},
		{src:"sounds/bgmPA.mp3", id:"bgmPA"},
		{src:"sounds/salsa_groove.mp3", id:"salsa_groove"},
		{src:"sounds/sexy_sax.mp3", id:"sexy_sax"},
		{src:"sounds/sheishappy.mp3", id:"sheishappy"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['C058E91979EAD3469C2E7AE4427D2788'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;