(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.vol_pos = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.5,1,1).p("ABagwIAABgQAAAWgZAAIiBAAQgZAAAAgWIAAhgQAAgVAZAAICBAAQAZAAAAAVg");
	this.shape.setTransform(9,7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgKA0QgDgDAAgGIAAgfIgFABIgTAAQgVAAAAgNQAAgHAHgDQADAAALAAIAYgBIAAgQIABgRQABgFADgDQADgCAEAAQAFAAADADQAEAEgBAFIAAAHIgBAIIABAPIAAAAIAKABIAIAAIAHgBIABAAIAJABQAKABADAGIABAEIgBAFIgDADIgDADIgFABIgEgBIgCAAIgEAAIgNAAIgOAAIAAAgQAAAMgLAAQgGAAgDgDg");
	this.shape_1.setTransform(9.6,6.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00CCFF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICBAAQAYAAABAWIAABfQgBAWgYAAgAgHAqQAAAGADADQAEADAEAAQAMAAABgMIAAggIANAAIAOAAIADAAIACAAIAFABIAFgBIADgDIACgDIABgFIgBgEQgCgGgKgBIgJgBIgBAAIgHABIgIAAIgKgBIAAAAIgBgPIABgIIAAgHQAAgFgEgEQgDgDgGAAQgEAAgBACQgEADgBAFIgBARIAAAQIgYABQgKAAgDAAQgHADgBAIQABAMAUAAIATAAIAFgBg");
	this.shape_2.setTransform(9,7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0099FF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICBAAQAYAAABAWIAABfQgBAWgYAAgAgHAqQAAAGADADQAEADAEAAQAMAAABgMIAAggIANAAIAOAAIADAAIACAAIAFABIAFgBIADgDIACgDIABgFIgBgEQgCgGgKgBIgJgBIgBAAIgHABIgIAAIgKgBIAAAAIgBgPIABgIIAAgHQAAgFgEgEQgDgDgGAAQgEAAgBACQgEADgBAFIgBARIAAAQIgYABQgKAAgDAAQgHADgBAIQABAMAUAAIATAAIAFgBg");
	this.shape_3.setTransform(9,7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_1},{t:this.shape_2},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape_3},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,19.9,16);


(lib.vol_neg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.5,1,1).p("AhAhFICBAAQAZAAAAAVIAABgQAAAWgZAAIiBAAQgZAAAAgWIAAhgQAAgVAZAAg");
	this.shape.setTransform(9,7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgMALIgCAAIgPAAQgLAAAAgKQAAgJALAAIAdgBIAdgBIAEABQAIAAAAAJQAAAIgKABIgVABIgJABIgNAAg");
	this.shape_1.setTransform(9.1,6.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICAAAQAaAAAAAWIAABfQAAAWgaAAgAABgLIgdAAQgLAAAAAKQAAAJALAAIAPAAIACAAIANAAIAJAAIAVgBQAKgBAAgIQAAgJgIAAIgEgBIgdABg");
	this.shape_2.setTransform(9,7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00CCFF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICAAAQAaAAAAAWIAABfQAAAWgaAAgAABgLIgdAAQgLAAAAAKQAAAJALAAIAPAAIACAAIANAAIAJAAIAVgBQAKgBAAgIQAAgJgIAAIgEgBIgdABg");
	this.shape_3.setTransform(9,7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0099FF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICAAAQAaAAAAAWIAABfQAAAWgaAAgAABgLIgdAAQgLAAAAAKQAAAJALAAIAPAAIACAAIANAAIAJAAIAVgBQAKgBAAgIQAAgJgIAAIgEgBIgdABg");
	this.shape_4.setTransform(9,7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_1},{t:this.shape_3},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape_4},{t:this.shape}]},1).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,19.9,16);


(lib.vol_mute = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AASBRQAAgIgQgQQgMgNgHAAIAAhZQAHAAANgOQAPgOAAgHg");
	this.shape.setTransform(15.6,13.9,1.2,1.201);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AgGglIANAAQABAAAAABIAABJQAAABgBAAIgNAAQgBAAAAgBIAAhJQAAgBABAAg");
	this.shape_1.setTransform(10.5,13.8,1.2,1.201);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#990000").ss(1,1,1).p("AhHBRQgCgDgDgCQgDgDgBgCQgbgeAAgpQAAgsAfgfQAgggAsAAQAjAAAcAUQAGAEAHAIQACACADACQAbAeAAApQAAAtggAfQgfAggtAAQgpAAgegbICYiY");
	this.shape_2.setTransform(15.1,14.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1,1,1).p("AAJAAQAAANgJAJQgCAFgGACIAAg5QAGADACAFQAJAIAAAMg");
	this.shape_3.setTransform(20.6,13.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1.5,1,1).p("ACWAAQAAA7gsAoQgtAqg9AAQg+AAgsgqQgrgoAAg7QAAg6ArgqQAKgIAKgHQAFgDAGgDQAJgFAKgEQAEgBAFgCQAWgHAZAAQAaAAAXAHQAEACAEABQAKAEAJAFQAFADAFADQAKAHAKAIQAsAqAAA6g");
	this.shape_4.setTransform(15,14.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAAABtQAuAAAfggQAfggAAgsQAAgpgbgeIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfQgfAgAAAsQAAApAaAeIAFAFIAFAFQAeAbAoAAgAhGBSICXiYQAbAeAAApQAAAsgfAgQgfAgguAAQgoAAgegbgAAuAaQAHgCACgGQAJgJAAgMQAAgMgJgJQgCgFgHgDIAAA6IAAAAgAhGBSIAAAAgAhLBNIgFgFQgageAAgpQAAgsAfggQAggfArAAQAkAAAbAUQAHAEAHAHIAEAFIiXCYIgFgFgAAuAagAAuggQAHADACAFQAJAJAAAMQAAAMgJAJQgCAGgHACgABAgDIAAAAgABRhGIAAAAg");
	this.shape_5.setTransform(15,14.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#00CCFF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAhLhLQgfAgAAAsQAAApAaAeIAFAFIAFAFQAeAbAoAAQAuAAAfggQAfggAAgsQAAgpgbgeIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfg");
	this.shape_6.setTransform(15,14.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhHBRICYiYQAbAeAAApQAAAtggAfQgfAggtAAQgpAAgegbgAAuAZQAGgCADgGQAJgIAAgMQAAgNgJgJQgDgFgGgDIAAA6IAAAAgAhMBMIgEgFQgbgeAAgpQAAgsAfgfQAgggAsAAQAjAAAcAUQAGAEAHAIIAFAEIiYCYIgFgFgAAuAZgAAughQAGADADAFQAJAJAAANQAAAMgJAIQgDAGgGACgABAgDIAAAAg");
	this.shape_7.setTransform(15.1,14.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0099FF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAhLhLQgfAgAAAsQAAApAaAeIAFAFIAFAFQAeAbAoAAQAuAAAfggQAfggAAgsQAAgpgbgeIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfg");
	this.shape_8.setTransform(15,14.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAhGBSQAeAbAoAAQAuAAAfggQAfggAAgsQAAgpgbgeQAbAeAAApQAAAsgfAgQgfAgguAAQgoAAgegbICXiYIiXCYgAhqABQAAApAaAeIAFAFIAFAFIgFgFIgFgFQgageAAgpQAAgsAfggQAggfArAAQAkAAAbAUQAHAEAHAHIAEAFIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfQgfAgAAAsIAAAAgAAuAaQAHgCACgGQAJgJAAgMQAAgMgJgJQgCgFgHgDIAAA6IAAAAgAAuAagAAuggQAHADACAFQAJAJAAAMQAAAMgJAJQgCAGgHACgABAgDIAAAAg");
	this.shape_9.setTransform(15,14.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_2},{t:this.shape_4},{t:this.shape_3},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_7},{t:this.shape_8},{t:this.shape_2},{t:this.shape_4},{t:this.shape_3},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_9},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,32,30.1);


(lib.Tween25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AA8gZIAAhmIjMD/IEhgzIhDg3");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AA8h/IAABmIAGgCIgBAOIAIAIIAFARIAFAIIgFACIBDA3IkhAzg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-15.5,-13.7,31.1,27.5);


(lib.menu_main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgWAoQgQgMAAgdIAAgIIAAgIIABgHIAAgGQAAgFABgEQADgFAEgBQADAAADACQADADgBADIAAAKIAAAKIAAAIIAAAIQAAAJABAHQADAJAFAEQADABAIABQAPAAAGgaQADgNAAgaIABgFQADgFAFAAQADAAADAEQAAAAAAABQAAAAABABQAAAAAAABQAAAAAAABQAAAXgCANQgDATgKAOQgEAFgGAEQgHAFgIgBQgPABgGgGg");
	this.shape.setTransform(37.7,11.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgoAtQgDgCAAgDIABgIIAAgHIAAgKIAAgKIAAgKIAAgMIgBgKIAAgLQAAgDADgDQADgDAEAAQAEAAAFAIQAaAmAaAXIAAgJIgBgmIgBgGIAAgHQAAgIAJAAQAJAAAAAeIAAAJIgBAkIAAAJQgBAIgIAAQgEAAgFgFQgWgUgcgkIgBASIABAOIAAAOQAAARgJAAQgDAAgDgDg");
	this.shape_1.setTransform(28.5,10.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgaAsQgHgFAAgTIABgXIACgXIgBgGIgBgGQAAgJAJAAQAAAAABAAQABAAAAAAQABABAAAAQABAAAAAAIANgCIALgBQAPAAAIADQAGACAAAGQAAADgCACQgDADgDAAIgDAAQgJgDgJAAIgJABIgKACIgBAXIAWgDIAOgBQAEABACACQADACAAADQAAAHgIAAIgOABIgYADIAAAMQAAAMABABQABABAGAAIAKgBIALAAIAEAAIADAAQAEAAACABQADADAAAEQAAAGgHACQgGABgRAAQgUAAgFgGg");
	this.shape_2.setTransform(20,10.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAfAmIgCgOQgDgKgEgTIgJAXIgDALIgFALQgDAFgEAAQgFAAgEgHIgDgLIgIgeIgIAcIgBANQgDAJgHgBQgDAAgDgCQgCgDAAgDQAAgKAFgNIAGgWIADgSQADgMADgFQADgEAEAAQAGABACAFQADAFADAQQACAPAFARQAGgRAGgVIADgNQADgIAHAAQAGgBADAKIADAPQADAYAGASIAFAUQAAADgDACQgDACgDAAQgGABgEgKg");
	this.shape_3.setTransform(10.9,11);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1.5,1,1).p("Ai4hoIFxAAQAxAAAAAwIAABxQAAAwgxAAIlxAAQgxAAAAgwIAAhxQAAgwAxAAg");
	this.shape_4.setTransform(23.4,10.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ai4BpQgxAAAAgwIAAhxQAAgwAxAAIFxAAQAxAAAAAwIAABxQAAAwgxAAg");
	this.shape_5.setTransform(23.4,10.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(1.5,1,1).p("Ai4hoIFxAAQAxAAAAAwIAABwQAAAxgxAAIlxAAQgxAAAAgxIAAhwQAAgwAxAAg");
	this.shape_6.setTransform(23.4,10.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#00CCFF").s().p("Ai4BpQgxAAAAgxIAAhvQAAgxAxAAIFxAAQAxAAAAAxIAABvQAAAxgxAAg");
	this.shape_7.setTransform(23.4,10.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0099FF").s().p("Ai4BpQgxAAAAgxIAAhvQAAgxAxAAIFxAAQAxAAAAAxIAABvQAAAxgxAAg");
	this.shape_8.setTransform(23.4,10.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_8},{t:this.shape_6},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,48.8,23);


(lib.general_buttoncolor = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{resetRed:1});

	// timeline functions:
	this.frame_0 = function() {
		this.play();
	}
	this.frame_8 = function() {
		this.gotoAndPlay("resetRed");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(8).call(this.frame_8).wait(2));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#D5FFD7","#61EF01","#1DA400","#004A00"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgwAAgigjQgjgigBgxQABgwAjgiQAigjAwAAQAxAAAjAjQAjAigBAwQABAxgjAiQgjAjgxAAIAAAAg");
	this.shape.setTransform(11.9,11.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FFFFFF","#EC0000","#9D0000","#480000"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgwAAgigjQgjgigBgxQABgwAjgiQAigjAwAAQAxAAAjAjQAjAigBAwQABAxgjAiQgjAjgxAAIAAAAg");
	this.shape_1.setTransform(11.9,11.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},8).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,23.7,23.6);


(lib.Copyright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAcAIIgEgLIgDAKQgEAJgEAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBIgCgJIgCgHQgGATgDAAIgCgBIgBgDIABgCQACgEACgHIADgMQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQAFAAACAIIACALIADgGIADgJQACgFACAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIADAKIACAHIADAIIABABIgBADIgDABQgDAAgCgJgAgUANIgBgIIAAgGIgBgHIgFAAIgFgBQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAEAAIAFAAIAPAAIADAAIADAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABQAAABAAABQAAAAgBABQAAAAAAAAQgBAAgBAAIgNABIAAAHIABAHIAAAEIABADIgBADIgCAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAgBg");
	this.shape.setTransform(57.3,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgMAYQgGgCAAgEIABgDQAAgBABAAQAAAAABAAQAAgBABAAQAAAAAAAAIAEACIAFACIAEABIAGgBQAEgCAAgCQAAgGgIgCIgEgCIgIgCQgDgCAAgFQAAgJAIgEIAIgDIAIgDIADAAIAEABIABADIABAEIAAADIgBAEIgDABQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBIgCgEIgKADQgGACAAAFIACAAQAJACAGADQAHAEAAAJQAAAHgGADQgFADgIAAQgFAAgGgCg");
	this.shape_1.setTransform(51,2.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgLATQgHgGAAgJQAAgIAGgJQAGgLAIAAQAEAAAGACQAGADAAADIgBADQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgDgBIgCgCQgCgCgGAAQgEAAgEAIQgEAIAAAEQAAAGAEADQADADAGAAIAFgBIAFgDIACgBIADACIABADQAAADgGADQgHADgDAAQgJAAgFgGg");
	this.shape_2.setTransform(46.6,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgDAgQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgIIAAgIIABgKIAAgKQAAAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAIADgBIACABQABAAAAABQAAAAAAABQABAAAAABQAAAAAAAAIgBAKIAAAKIAAAIIAAAIQAAABAAAAQAAAAAAABQAAAAgBAAQAAABAAAAIgCABIgDgBgAgCgXQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAQAAgBgBAAg");
	this.shape_3.setTransform(43.1,1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AALAVIgBgJIgBgKIAAgDIAAgEQAAgKgDAAQgFABgEAFQgEAGgCAGIAAAFIgBAEIABAEIAAAEIgBADIgDACIgEgCIgBgDIAAgEIAAgEIAAgMIABgMIAAgEIAAgEIABgEIADgBQAEABAAAFIABAFQAHgKAHAAQAHAAADAHQABAEABAIIAAAFIAAACIABAKIAAAJIgBAEIgDABQgEAAAAgFg");
	this.shape_4.setTransform(39.5,2.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAOAWIgDgDIgHADIgFACQgKAAgFgGQgEgFAAgMQAAgKAHgHQAIgIAJAAQAEAAAEACQAGADAAADIgBACIAAAGIgBAJIABAIIADAJIABABIAAABIgBAEIgDABIgDgDgAgGgKQgFAGAAAGQAAAHACADQADAEAFAAQADAAADgBIAEgEIgBgQIAAgEIABgFIgDgBIgCgBQgFABgFAFg");
	this.shape_5.setTransform(34.8,2.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAMAiIgCgLIgBgLIAAgDIAAgDQAAgIgDABQgGAAgDADIgHAKQAAARgBADQgBABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgBgEIABgBIAAgGIAAgHIAAggIABgHIgBgEIAAgEQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBQADAAAAAEIABAIIAAAKIAAAJIAAAFQAEgFAEgDQADgDAFABQAGAAAEAEQABAEAAAHIABAIIAAAJIACAJIABACQAAAAgBAAQAAABAAAAQAAABAAAAQgBAAAAAAIgDABQgDAAgBgCg");
	this.shape_6.setTransform(30,1.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgLATQgHgGAAgJQAAgIAGgJQAGgLAIAAQAEAAAGACQAGADAAADIgBADQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgDgBIgCgCQgCgCgGAAQgEAAgEAIQgEAIAAAEQAAAGAEADQADADAGAAIAFgBIAFgDIACgBIADACIABADQAAADgGADQgHADgDAAQgJAAgFgGg");
	this.shape_7.setTransform(25,2.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgOATQgHgFAAgKQAAgLAGgHQAGgJAJAAQAHAAAFACQAFADAAAHQAAAEgFAEIgJAEIgQAHQADAFADABQAEACAEAAIAHgBQAFgCACgCQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAABAAIADABIABADQAAAEgIAEQgHADgGAAQgJAAgGgFgAgIgLQgEAFgCAGIAOgFQAHgEADgCQgDgEgHAAQgFAAgDAEg");
	this.shape_8.setTransform(20.3,2.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAbAhIgCgHIgCgIQgCgGgDgXIgJAZIgDAJIgEAIQgBADgCAAQgDAAgCgDIgBgFIgBgEIgIghIgCAIIgGAWIgBANQgCADgDAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBIAAgDQAAgHACgLIAGgQIACgPQACgJACgDQACgDACAAQADAAABAEQADAEABAMQADAOAFAPQAFgPAFgTIABgGIACgGQACgEADAAQAEAAABAIIADAKQACATADAOIADAIIACAHQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAAAIgDABQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAgBg");
	this.shape_9.setTransform(13.8,1.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgQAUIAAgeIAAgEIAAgEQAAgFAEAAQAEAAAAAIQAIgJAKAAQAEAAABADQACADAAAFIAAADQAAAGgEAAQgEAAAAgFIAAgDIAAgDQgHAAgEAEQgDACgDAGIAAAXQAAAFgEAAQgEAAAAgFg");
	this.shape_10.setTransform(5.1,2.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAOAWIgDgDIgHADIgFACQgKAAgFgGQgEgFAAgMQAAgKAHgHQAIgIAJAAQAEAAAEACQAGADAAADIgBACIAAAGIgBAJIABAIIADAJIABABIAAABIgBAEIgDABIgDgDgAgGgKQgFAGAAAGQAAAHACADQADAEAFAAQADAAADgBIAEgEIgBgQIAAgEIABgFIgDgBIgCgBQgFABgFAFg");
	this.shape_11.setTransform(0.5,2.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgBAaQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIgBgQIgBgPQAAgEgCgDQgDABgCAEIgGAFIgCADIAAAHIgBAIIABADIAAAEQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAABIgEABQgEAAAAgLIAAgIIABgHIgBgHIAAgHQgBgKAFAAIADABQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABIAAACIgBADIAAAFQACgFAFgEQAEgEADAAQAHAAACAHQADgDACgCQAEgBAFAAQAGAAADAIIACAMIAEAYIgCADIgDABQgEAAAAgDIgCgOIgCgNIgBgGQgCgEgBAAIgGADIgGAEIAAAIIACALIABAMIgBADIgEABQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAg");
	this.shape_12.setTransform(-5.2,2.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgCAaQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIgBgQIgBgPQAAgEgBgDQgEABgCAEIgGAFIgCADIgBAHIAAAIIAAADIABAEQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAABIgDABQgGAAAAgLIABgIIAAgHIAAgHIgBgHQABgKAEAAIADABQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAABIAAACIAAADIAAAFQADgFAEgEQAFgEADAAQAGAAACAHQACgDADgCQAEgBAEAAQAIAAACAIIACAMIAEAYIgCADIgDABQgDAAgBgDIgCgOIgCgNIgBgGQgBgEgCAAIgGADIgFAEIAAAIIABALIABAMIgBADIgEABQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAgBAAg");
	this.shape_13.setTransform(-12.2,2.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAOAWIgDgDIgHADIgFACQgKAAgFgGQgEgFAAgMQAAgKAHgHQAIgIAJAAQAEAAAEACQAGADAAADIgBACIAAAGIgBAJIABAIIADAJIABABIAAABIgBAEIgDABIgDgDgAgGgKQgFAGAAAGQAAAHACADQADAEAFAAQADAAADgBIAEgEIgBgQIAAgEIABgFIgDgBIgCgBQgFABgFAFg");
	this.shape_14.setTransform(-18.1,2.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgQAUIAAgeIAAgEIAAgEQAAgFAEAAQAEAAAAAIQAIgJAKAAQAEAAABADQACADAAAFIAAADQAAAGgEAAQgEAAAAgFIAAgDIAAgDQgHAAgEAEQgDACgDAGIAAAXQAAAFgEAAQgEAAAAgFg");
	this.shape_15.setTransform(-22.4,2.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgWAeQgFgGAAgMQAAgLAFgLQAGgMAIgIQAGgFAFAAQAEAAAGACQAJAEgBADIgBAEIgDABIgDgBQgGgEgFAAQgDAAgDAEIgFAFQgKAOAAAPQAAAIADAEQACADAHAAQAIAAAGgFQAGgFACgKQgNAAgHAEIgCABQgBAAAAAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgCgCQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAABAAQAJgFAWAAIAEABIABACQAAABAAABQAAAAgBABQAAAAAAABQgBAAAAABQgDANgJAIQgJAIgLAAQgKAAgGgGg");
	this.shape_16.setTransform(-27.7,1.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgOAhIgBgDIADgIIAKgXQAFgPAHgHIABgBIgVgBIgKAAQgEAAAAgEQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAIARABIAPAAIAIAAQAFAAAAADQAAACgDADIgEAFQgFAHgFAJIgIARIgDAKIgEAKQAAAAgBABQAAAAAAAAQgBABgBAAQAAAAgBAAIgDgCg");
	this.shape_17.setTransform(-36.2,1.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AABAiIgIAAIgEAAQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgFAHAAIACAAIACAAIAAgGIgBgGIABgQIABgRQgGAEgBAAIgDgBIgCgDQAAgCAEgDIAHgFQADgEADAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAADIAAADIAAAFIAAAEIgBAPIgCAOIABAGIABAGIAEAAQABAAAAAAQAAAAABAAQAAAAAAABQABAAAAAAIABADIgBADIgDABg");
	this.shape_18.setTransform(-41,1.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgTAXQgFgJAAgPQAAgMAGgKQAIgLALAAQAMAAAGAKQAGAJAAAMQAAATgHAJQgGAKgMAAQgNAAgGgMgAgLgRQgEAHAAAJQAAANAEAIQAEAHAHAAQAJAAAEgLQADgHAAgLQAAgLgEgHQgEgFgHAAQgHgBgFAJg");
	this.shape_19.setTransform(-45.9,1.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AANAhIgDgBIgGABIgGAAIgFAAIgFABIgCAAIgBAAQgDAAgBgDIgBgGQAAgKAGgGQADgDALgHIAHgGQAEgFAAgFQAAgDgEgCQgDgCgDAAQgDAAgEACIgGAFIgDABQgEAAAAgDQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQAFgFAEgCQAFgDAFAAQAHAAAGAEQAGAEAAAHIgBAJIgEAGQgDADgIAFQgIAFgCADQgFAFAAAHIAJAAIAMgBIAHABQAEACAAACQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBABIgCABIgEgBg");
	this.shape_20.setTransform(-51.3,1.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgeABQgBgLALgKQALgJANAAQANAAAHAIQAIAIAAAMQAAAKgJAKQgKALgNAAIAAAAQgfAAABgdgAgOgPQgJAHABAJQAAALAFAFQAHAFAKAAQAKAAAHgJQAGgIAAgHQAAgJgDgFQgFgFgJAAIgCAAQgLAAgHAGgAgLAJQgFgEAAgFQAAgHAHgFQAGgEAHAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAAAQABABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAABAAABQAAAAgBABQAAAAgBAAQgBAAgBAAIgBAAIgBAAQgEAAgEACQgFADAAADQAAACAEABIAEACQADAAADgDIAEgCIAEABIABADQgBADgEADQgGADgEAAQgFAAgFgEg");
	this.shape_21.setTransform(-57.7,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.3,-7.1,126.6,16.6);


(lib.blank_gr = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00CCFF").s().p("Aj+CqIAAlTIH9AAIAAFTg");
	this.shape.setTransform(32.5,17,1.275,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,65,34);


(lib.Back = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(3,1,1).p("EAnJAWlMhORAAAMAAAgtJMBORAAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FEDB4E","#FFFFDD"],[0,1],-0.6,-128.4,0.6,128.5).s().p("EgnIAWlMAAAgtJMBORAAAMAAAAtJg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-251.9,-146,504,292);


(lib.Symbol10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.3,1,1).p("ACnp8QAUgxAuAAQAgAAAcAsQAcAtAOAAQACAABAgrQBFgrAVAAQBWAAAOA5QAEARAGAtQAHAqARAhQADAFAEAEQANAMAbADQAGABBDADQBgAFAAA7QgvBXggALQgRAGg0AOQg3APgLAAQhjAAhchKQAVgeAHgTQgHABgFgCQgFgKgDgGIAXgGQAQgKAGgJIABAAQAAAAAAgBAIgn0QACAEABAFAGMn2QABgBABAAQArgaAZAAQAoAAAGAGQAHAFgBAgQACgBAYgNADNm7QATgOAWgQQBlhIApgWQARgKAGAAQBFAAAaARQAaAPAMAtQABgBACAAQAPAAAAATQAAARgVAYQgBABgCACQADAAADABQAvAEAQgRAGRofQgHAOAAAKQAAAJACAIQABAEABADQAFANALALQABgEABgEAGenXQADADAEAEQARAOAUAFQABgBAAAAQAAAAgBABIAAAAQgBAAgBABQgDACgDACQgrAcgcAAQgcAAgDgXQgBgDAAgDQAAggAxgdAHUnEIAAAAQADgCADgCQAdgXAFgQAHLm+QADgCADgCQABgBACgBQAIAEAPALQAFAEAHAFQABAAABABIALALIAEAEQgCgCgCgCIAAAAQABgBABgBQAEgEAEgDQgLgCgKAAAHCm2QgEAPgEALQAAACACAHAHCm2QAAgBAAgBAHKm9QgCADgGAEAH3msQgBAAgBAAQAGAFAJAHQgHgGgGgGgAHpmsQABAAAAgBQACgCAAgDQABgBAIAHAIam2QgSgDgMABQgSgCABAFAIam2QgFAGgHAHQANACAPADQApAIAZAAAGOnvQgYAMgLAXIAAAWIAWAAQAVgRAIgQAHQmCQAUgCAggcAgioMQApgcAIgeIAAAAQACgIAAgHQAAgFgGgJQgHgKgEAAQgZAAgiAWQgPAKgSAPQgCgDgCgDQgBgBAAgBQgEACgEACQgfgHADgtAhdpJQBRgrAsgNQAAAAABAAQACgBADgBQA1gOAdAAQAhAAAOAVQAMAQAAAeQAAAPgZAlQgLAQgPAUIgBAAQgsA6hTBbQAZgDBCAAQAEAAAEAAIAEAKQAAAqggA/QgDAYgDARIAAABQgHAtgCAEQgHAPgYAMQgTAIgNAGQgKAFgJAEQg0A1gKAIQgFgBgBgFQgBgHAFgQQABgEACgFQAOgjAAAEQgDgTgCALIgwgBQgEgFAAgIQAAgVBCgSQAGgCAHgBQBOgTAAgPQAAhtglAAQgWAAgRBFQgHAdgHAoQAAAEgBAEAAYopQABgMgBgFQAAgEABgGQAAgGASgTABLn8QgCAAgCAAQAAAAgOgKIAogbABLn8QAOgBAMgOQANgNALgZQAAgHgCgFQgXgEgJAAQgNAAgPAFQgSAGgVANAAYokQAAgCAAgDQgBABgCABQACACABABQACACACACQALANADACQACABABABQAHAFAFAEAA/o8QgIARgKAcAAqoRQgEAOgDAGQgGALgPAAQgCAAgMgGQAAgRAcgXAAVonQgFADgFADQgyAjAAAjQAAASARAAQAtAAA0gzAEnlJQgBAAgMgNIABADQAAABAAAAQAAABAAABQgBAAAAABQgNAwAQAiQADAFADAFQAcAoAZAAQAIAAAGgBQAAAHgBADQgEAKgGAQQgIAXgPAkQgCAGgCAHQgVA0AAAgQAAADABAMQADAfAKBYQAAACAAACQABADAAADQgyAihYAJQggAEgmAAQgiAAgegKQgCgBgBAAQgCgBgBAAQgBAAgBgBQgBAAgBAAQgMgGgGgfQgFghgBgCQgOg8AAhlQADgWAAgNADNm7QgNgHgLgPQgXgegEgrAA/o8QAJgSAGgGABblkQAIgIBqhPAGJkZQgDgHgFAAQgMAPgQgEQgLgRAAgJQABgJACgBQgegBgHAAQgKgGgHgJACtCgIAGgQQgShhAAgBQAAg+AahXQAahRAegwAFbioQASACAfAPQAhAQAmAHQgSAegbAdQgKALgLALQg5A0gTAWQAQAKAAAGQAAAEgTAVQAIAPAFgDQADgCAGgEQAOAAABAdQAAAagpgCQgCAAgDgBAE+B/QgBgDgEgCAGJkZQABAFAAADQAAAVgQAOQACAAACABQAAAIADAJQAAAOgbACAEsADIBlhcIAAgQQgugEgfAAAF6juQglgHgRgVQgCgCgbg9AG0lRQgQAYgbAgAhdpJQADgDgCgGQgEgLAGgeQAFgfgEAOAhhpGQACgCACgBAmkosQA3gMAAgyQAAgUgMgCQgSABgLgCQADgaAAgJQAAgYgZAAQgeAMgIADQAQgXAAgLQAAgFgQgRQAQgNAAgUQAAgfgMgNIgOAAQgNAthMAgQgDgEgBgHQgCgGAAgJQAAgNAtgoIAGgEQgiAAh5APIgGgCQAoArAMAdQgfAJgbAMQgPAGgLAHQgEgGgGgGQgLgJgLAAQgjAAgVAWQgUAVAAAcQAAAQAHAOQAAgBAAgCQAAgjAeAAQABAAASAHQAJAFAEAHQAFAGAAAIQAAAfglAAQgMAAgLgQQgEgFgDgFQABAmA5AGQAKABANAAQAUAAAagOQAbgNAhgbQALAWAKAUQAGAIAaAAQAmAAAGgMIAKAAQgEAMACAIQgNACgNAKQgXAQAAAZQAAANAHAZQABAEACAFQgEAAgDAAIgRgCQAAgBgBgBQgBgJgBgGQgRAMgSAIQgPAGgQAEQgKACgKABQgHgQAAgRQAAgPAJgRQAFgJAGgFQAFgEAGAAQANAAAKADQAfAJAIAmQAEgDAEgDAlymtQgfgSgRAAQgPAAgLAWQgKAUAAAUQAAApAUAuQAYA+AEAOIAAAQIgGAGQgYgQgLAAQgFANAFAQIgDACQgTgVgJAAQgIAAgFAOQgCAFgBAEQgBAEAAADQAAAfAlANQAcAKAYgFQAJguAOgqQABgDABgDQgBgagEgkQgLhDAAgKQAAgRAHgHQAQAEASAJQAOAHASANQAKgRAKgQIABgBQgngdgcgPgAkBldQAGAHAKACQANAEAbgEQA5AAA4gaQg6gYgLAAQgVAAgSAOQADgHgFgNQgVgJgNAEQgOAEgGAGQgGAGgFAGIgBAEQAAAOAFAIQABACABACQACBFArAAQAiAAAtgfQAPgLAKgLQARgQAEgQQABgBAAAAQgBAAgBAAAhppCQgHAEgXAOQhaA9hEBiQgFAIgFAIAmkosQAdA0AVBLAg0ogQgCgCgBgCQgPgUALgfAhvorQgfAIgOA7QAJAGAEAAQArAAA4gjQAFgDAFgEQgHgEgLgQQgTgFgCgDQgHAQgMAAQgTAAAAgTgAhho5QADgCACgDQAIAKALAMAhho5QgBABgCABIAAAAgAhppCQACADACAEQAAACABACIgIAGIgDAFIAAABAhXltQAAAAgBgBApwrGQACgMgHgRQAFgBAGgBIATAAArJrBQAEAIAAAJQAAAaghATQgEgCgBgCQgDgDAAgNQAAgVAlgVgAqNkpQgCgPgCgOQgEgrgnhbIAAAAQAAAAABAAQANAAAMgCQAGAPALAQQACACABABQAYAcAUAAQAOAAAEgLQADgLAFgKQAFgKgDgVQgCgIgBgHAqOnRIAAAIQAAASANAAQATAAAAgdQAAgDgBgEAq8nMQgqAAgZgaAoBnvQAVgMAXgTQAKAWAAAUQAAAYgPASQAAAAgBABQgNAQgJAAQgUAAgpgpQgCgCgBgBIAAgHAoBnvQAAACAAACQAAAXgPAAQgNAAgDgMQAOgFARgKgAnVoOQAJgIAKgJAnkopQADAEADAEQAFAKAEAJAnkopQAKABAMAAQAYAAASgEAoxncQAIgBAJgDAounSQgCgFgBgFIAAAAAr0pFQAiBEAWA1AoKpAQAFASAhAFAoBk9QAAADAAAEAphj2IAAguQADAAAIgGQAHAAAUAZIAAgpQAJABAeALQAJAAAJgNQABgBAAgBIAAgBQAHgMAHgMApRjgQAJAIAKAAQAqAAANgzQAAgCACgOQABgKACgPIABgCQAAgEAAgEQACAPACAOQAFAtAAAbQAAAagDAGQgGANgXAAQgkAAgVg0gApZjpQAEAFAEAEApcjuQAAABAAAAQACACABACgAphj2IAAACIAFAGQgDgEgCgEgApukOQAFAHAIARAqNkpQADAPADARQAHAkALAoQADALADAMAqIDTQAkh1AAinQAAgGAAgFQgBgngKgrQgTAoglAgQgDACgDADQgEADgYA0QgTArgWAAIgNgEQAAgRAOgRQAOgRAAgHQAAgQgygCQgzgCAAgXQAAgFAAgEQADgJAKAAQALAABFAZQAVAAATgQQAIAAAFgFQAQgQAAg/QAAhVAZgXAnrEpQAIgpANhaQAPhlADgsQACgPAAgIQAAgMgHgYApOEPQAUhEAOhuQAPh+gLg1AjFEnQgIiHAbiAQAKgsAPgzQAKggAMgjQAAAAAAgBQAJgaALgcQASgyAXg2AlZk3QgUArgQAvAmWh/QgPBHgFBOQgCAnAAApQAAApASBaQAHAnAGAZQAFAQADALQADgIAEgJQAMAIAUAKQAQAJALAEQgPhQgDgQQgBgLAAhhQAAhsAEgVQAYhRAmiMAhegtQgMA8gDBRQgCAygDBhQAEADAEADQgDADgGAEQgTANgyAYAlklzQAGAcAFAgAlElfQgLATgKAVAhyDzQgBAHAAAGAlDFSQAKADAFAAQAYAABPgmQADgBADgBQABgBAAAAAjFEnQAAACAAADQAAAAgBAAIABAAIAAAAQAHgEAGgDgAhKGdQAAgCAAgBIABACQAAABgBAAQgjAQgWAAQgXgDgRgCQgegEgMAAQgDAAgEACQgGAEgIAKQgMAPgOAAQgMAAgUgJQgTgKgKAAQgBAAgBAAQgdABgdAZQgbAWgSADQgCAAgDAAIgKgDIAAgTQAGgNAJgXQgCABgDAAQgCAAgDAAQg2AngIAYQAzACAcAlQASAXAkA7QADAEAXAOQASAMAfARQA9AkAAAPQAAAVhYAqQhWApgmAAQgZAAAAgSQAAgUBAgeQA/gcAAgSQAAgQgXgPQgHgFgLgFQgEgDhTgiQiBg0AAhFQAAgCAAgCQgTAGgTARQAXAEASAaQAUAegEAmQgDAhAOAXQAFAIAHAHQAjAkACAHQgRAHhMAyQgwAgg2AAIgOAAQgYgBAAgPQAAgwBDgRQASgFAdgHQAVgIAAgNQglgwgNgcQgnhYAAgYQAAgtAJgVQAQgdARgoQgBABgBABQgdAagOAAQgPAAgEgwQgGg2gPgIQgKgGg6gSQAggGAsgEQA3gLAcggQAFgFADgHAgFF7QATgIANgCIAHgDQgsgpgmggIgBAAQASgYAfghQAWgcAKgqAgFF7QgUAJgbAOQgLAGgKAEAhqD5QAbATAeAZAirGoQACAgAHBLQgwhOgKgfAi2J1IABAAQASANAlATQADAYAAAUQAAAbgNAoQgOAugSAHQgMgYgFg6QgBgSgBgSQgBgNAAgMQABgdAFgYQhWhCg3iDAh1JbQADAFADAEQAKAPAwAvQAPAPATASQBHBDAAAJQgEAagfAAQgeAAgjg4Qgcg3AAAAQgTgWgdgOQgBgBgBAAAhKGdQgRB/gaA/QgagogTggAmqGpQAPglAWhAAofGQQgIgEgIgEQg0gkgHAAQgRAAgbAaApOEPQAPAHARAFQAhAKAiAEAmNEpQgWADgZAAQgXAAgYgDAqMDjQACgIACgIAqQDfQACACACACQAWAbAoARAm0GqQgFABgGAAQgtAAgzgbApUHvQACgRAQggQATglAQgJAE+B/QA9BtBMBFQgTAkgjAAIgMgCIg2gIQgYAAgYAWQgDADgCACQgOgFgTgmQgjhCgQgaACyLgQAhgvAnhVQAghHAkhhQAAgegNgLQgVgLgSgOQAHgFAJgHACVFlQAEgBAEAAQAVAABGATQAIAAAKgFAB7DlQgcATgTBCQgOAxAAATQAAAJAGAIQgQALgDAAQgagTgWgFIgGgHACVFlQgXADgjAYQgLAHgIAGQAAAAAAAAQgCABgCABACyLgQgmA2geAAQgRAAgEgPQgCgGAAgHQAAgJAnhDQAmhEAAgfQgHgjAAgJQAAgXAaglQAXggASgNQgcgGgRgZQgNgBgRgxAGFFTQgIAvg8B8QggBDgPAlQgQAmAAAJQAAAtA5AmQBFAtABABQgPALgfAAQgXAAhGggQgtgUgXgN");
	this.shape.setTransform(84.1,82.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF6666").s().p("AjJB1IgHgGQAUgIANgCIAHgDQgtgpgmggIAAAAQARgZAfgfQAXgcALgrIABABIACABIADAAIADABQAeAKAiAAQAmAAAggDQBXgJAygjIgBgFIAFAAQA9BtBNBFQgUAkgjAAIgMgCIg2gJQgYAAgYAXIgFAEQgOgFgTglQgjhCgPgZQAPAZAjBCQATAlAOAFQgJAIgHAEQgKAGgHAAQhFgTgWAAIgIAAQgXAEgjAXIgTANIAAAAIgKgPQAAAKAHAIQgRALgCAAQgbgTgWgGgAiMBxIAAAAQAAgTAOgwQAUhBAbgTQgbATgUBBQgOAwAAATIAAAAg");
	this.shape_1.setTransform(104.4,109.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#99CC66").s().p("AjtByIAAgTIAPgkQAPglAWg/IAHgRQAMAIAUAKQAQAJALADQAKAEAFAAQAYAABPgmIAFgCIABgBIABAAIAAAAIANgHQAygYATgNIAJgHQAbATAeAZIABAAQAmAgAtAoIgHADQgNACgUAIQgUAJgbAOIgVAKIgBgDIAAAEQgjAQgWAAIgogFQgegEgLAAQgDAAgEACQgGAEgIAKQgMAPgOAAQgMAAgUgJQgTgKgKAAIgCAAQgdABgdAYQgbAXgSACIgFABg");
	this.shape_2.setTransform(63.7,119.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00FFFF").s().p("AA6BLIgPgIQgzgkgHAAQgRAAgcAaIgBACQgdAagOAAQgPAAgFgwQgFg1gPgIQgLgGg5gSQAfgFAtgFQA3gLAcggIADAEQAXAbAnARQAOAHASAFQAhAKAiAEQAXADAYAAQAYAAAXgDIAIAbQgWA/gPAlIgGABIgEAAIgMABQgsAAg0gbg");
	this.shape_3.setTransform(23.8,114.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E1BDB5").s().p("AnlA/IABABQAIAHAJAAIABAAIAAAAQApAAANgzIACgQIAEgYIAAgCIABgIIAEAdQAFAsAAAbQAAAagEAGQgGANgWAAIAAAAQgkAAgVg0gAGPAsIgGgKQgQgiANgvIAAgBIAAgCIABgBIgBgDQAMANAAAAQAHAKALAFIAlABQgCABgBAJQgBAKALAPQARAEALgOQAGAAACAGIACAIQAAAVgQAOIAEABQAAAJACAIQAAAOgaACIgOABQgZAAgcgogAGvAVQASAVAlAHQglgHgSgVIgdg+IAdA+gAnTBHQgJAAgIgHIgBgBIgIgJIgEgFIgEgIIAAgtQADAAAIgGQAGAAAVAYIAAgoQAJABAdALQAKAAAJgNIABgCIgBAHIAAACIgEAYIgCAQQgNAzgpAAIAAAAIgBAAgAhoAHQgsAAgBhEQAGAHAKACQANAEAagEIABAAQA0AAAygVIAHgDIADgCIABABQgEAQgQAQQgKALgQALQgsAegiAAIAAAAgAiFg0QgKgCgGgHIgCgEQgFgIAAgOIABgEIALgMQAGgGAOgEQANgEAVAJQAEANgDAHQATgOAUAAQALAAA6AYIgDACIgHADQgyAVg0AAIgBAAIgXACQgKAAgGgCg");
	this.shape_4.setTransform(73.3,53.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AIGBMQAFgLADgPIAJgHIAAAAIAGgEIADgCQAJADAOALIAMAKIgBAAQgJgHAAABIgDAFIAAABQgGAIgRALIgWAFIgDgJgAG3AzIAAgXQAMgXAYgKQAFAMAKAKQgHAQgWASgApCAfIAAgIQAQgDAPgGIACAGQAAAegUAAQgNAAAAgTgAnUAIQAPgEARgJIAAADQAAAXgPAAIAAAAQgOAAgDgNgABMgPQAAgQAdgXIANAOQgDAOgEAHQgGALgPAAQgCAAgMgHgAgjhBIAAgBIADgGIAJgFIAAAAIADgDIAFgEIARAVQgGARgMAAQgTAAAAgTg");
	this.shape_5.setTransform(76.4,33.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#A4A400").s().p("AI1BbIAUADIgHAHIgCABgAI1BbIgCAAIgNgJIAAAAQAAgDAJgBIAAAAIAEABIAEAAIABAAIABAAIACAAIADAAIAAAAIABAAIAOABIAGAAIADABIgNANIgUgDgAIQBDIAAgBIAGgDQAdgXAFgQQgFAQgdAXIgGADIAAABIgDACIgGAEIgBABQgUgFgRgOIgHgHIACgIIgCAIQgLgLgFgNIgCgHIACgBQArgZAZAAQAnAAAHAFQAGAFAAAgIAagOIADAJIgDgJIADgBQAPAAAAATQAAARgVAXIgDAEIgDgBIgGAAIgOgBIgBAAIAAAAIgDAAIgCAAIgBAAIgBAAIgEAAIgEgBIAAAAQgJABAAADIAAAAQgOgLgIgEgAptAYQAAgPAJgQQAFgJAFgFQAGgEAGAAQAMAAALADQAfAJAHAlQgQAMgSAIQgPAGgQAEIgUADQgHgQAAgRgAn4AiQgHgaAAgMQAAgYAXgQQANgKANgCQAFASAhAFIAGAIIAJATQgYASgUAMQgRAKgPAFQgIADgIABIgDgJgACDALIgOgKIAogaIgoAaIgMgIQAKgdAIgQQgIAQgKAdIgDgCIgOgPIgEgEIAAgFQAVgNASgGQAPgFANAAQAIAAAYAEQACAFAAAHQgMAZgMANQgMAMgOACIgDAAIgBAAgAAHgYIgDgEQgIgLAAgPQAAgMAEgNQAigXAZAAQAFAAAHALQAGAJAAAEQAAAIgCAIIAAAAQgJAegpAcQgHgEgLgQgAgNggIgTgWQASgPAOgKQgEANAAAMQAAAPAIALIADAEQgSgFgCgDg");
	this.shape_6.setTransform(78.1,30.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#CC9933").s().p("Ag8CJQAVgeAHgTQAUgCAegcIAFAEIgEgEIACgCIAHgHIATgMIgDgEQAVgYAAgQQAAgTgQAAIgCABQgNgsgZgQQgZgRhFAAQgGAAgRAKQgpAWhlBHIgpAfQgNgIgLgPQgXgcgFgrQAaglAAgQQAAgegMgQQATgxAvAAQAfAAAdAtQAcAsANAAQACAABBgqQBFgrAVAAQBVAAAOA4QAEASAGAsQAHArARAhQADAEAEAEQANALAbAEIBJAEQBgAFAAA6QgwBXgfALQgRAHg0ANQg3APgLAAQhjAAhbhKgAA5A2QAoAIAaAAQgaAAgogIIgdgFIAdAFgABAAmQAgAAANgNIABgBIgBABQgNANggAAIgBAAIAAAAIgPgBIgBAAIABAAIAPABIAAAAIABAAg");
	this.shape_7.setTransform(133.8,34.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF9900").s().p("ABtCGQghgEgFgSQgCgJAEgLIgKAAQgGAMgmAAQgYAAgHgIIgVgrQghAcgaANQgbAOgUAAIgXgBQg5gGgBgmIAHAKQALAPAMAAQAlAAAAgeQAAgIgEgHQgFgGgJgFIgTgHQgeAAAAAjIAAADQgHgOAAgQQAAgcAUgUQAVgWAjAAQALAAALAJQAGAFAEAHQALgHAPgGQAbgMAfgJQgMgdgogsIAGADQB4gPAiAAIgGAEQgtAoAAAMQAAAKACAGQABAHADADQBMgfANgtIAOAAQAMANAAAfQAAAUgQAMQAQASAAAFQAAAKgQAXIAmgOQAZAAAAAXQAAAIgDAbQALACASgBQAMACAAAUQAAAyg3AMQgSAEgYAAIgBAAIgVgCgAiTAsQAggSAAgaQAAgJgEgHQAEAHAAAJQAAAaggASQgFgBgBgCQgDgDAAgMIAAgBQAAgVAlgUQglAUAAAVIAAABQAAAMADADQABACAFABIAAAAgAgdgVIAAgFQAAgLgGgNIALgDIATAAIgTAAIgLADQAGANAAALIAAAFgAjVBJIgHgKIAAgDQAAgjAeAAIATAHQAJAFAFAGQAEAHAAAIQAAAeglAAQgMAAgLgPgAjcA/IAAAAg");
	this.shape_8.setTransform(24.7,13.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFF00").s().p("AgkKUIgDglIAAgYQAAgdAGgZIAAABQASANAkASQgkgSgSgNIAAgBQhXhBg2iDIACAAQAJAAAUAKQATAJAMAAQAOAAAMgQQAIgJAGgEQAKAeAwBPQgHhLgCghIAoAGQAWAAAigQQgRB/gZA/IgthIIAtBIIAFAJQAKAPAwAuIAjAhQBIBEAAAJQgEAZggAAQgeAAgjg3Igdg4QgTgWgcgNIgDgCQADAZAAATQAAAcgNAoQgNAtgRAHQgNgYgEg5gApBLgQgZgBAAgPQAAgwBEgRIAvgMQAVgIAAgNQgmgwgMgcQgnhZAAgYQAAgsAJgVQAPgdARgoQAcgaAQAAQAIAAAzAkIAQAIQAzAbAtAAIAMgBQg3AngIAYQA0ACAcAlQARAXAkA7QADAEAXAOIAxAdQA+AkAAAPQAAAVhZAqQhWApgmAAQgYAAAAgTQAAgTA/geQA/gdAAgRQAAgQgWgPIgSgLIhYgkQiBg0AAhFIAAgEQgTAGgSARQAXAEASAaQATAdgEAnQgDAgAPAYQAEAIAHAHQAkAkACAHQgRAHhMAyQgwAgg3AAgAmuFrQgQAggCARQACgRAQggQATglAQgJQgQAJgTAlgAGKKuQgsgUgXgOQAgguAnhVQAghHAlhiIAAAAQAAgdgOgLQgVgLgSgPQASAPAVALQAOALAAAdIAAAAQglBiggBHQgnBVggAuQgnA3geAAQgQAAgFgPQgBgGAAgHQAAgJAmhDQAmhEAAgfQgHgkABgIQAAgXAaglQAWggASgNQgbgGgRgZQgNgBgRgxIAIgBQAVAABGATQAHAAAKgGQAIgEAIgHIAFgFQAYgWAYAAIA2AIQgIAug8B9QgfBCgQAmQgQAlAAAJQAAAuA6AlIBFAvQgPAKgfAAQgXAAhGgfgAiuD+IgThfQgBgKAAhZIAAgJIAAgBQAAhrAFgUIA+jeIg+DeQgFAUAABrIAAABIAAAJQAABZABAKIATBfQgLgDgRgJQgUgKgMgIIgGAQIgIgbQgHgZgHgmQgShaAAgpIAAgDQAAgnADglQAEhPAPhHQgPBHgEBPQgDAlAAAnIAAADQAAApASBaQAHAmAHAZQgXAEgYAAQgYAAgXgDQAHgpANhbQAPhjAEgtIABgXQAAgMgHgZQAHAZAAAMIgBAXQgEAtgPBjQgNBbgHApQgigEghgKQgSgGgPgGQAVhEANhuQAJhLAAgxQAAgigEgWQAEAWAAAiQAAAxgJBLQgNBugVBEQgogRgWgbIAFgQQAkh1AAioIgBgLQgBgmgKgsIgGgXQgLgngHgkIgFghIAFAhQAHAkALAnIAGAXQgTApglAgIgFAFQgEADgYA0QgUArgVAAIgNgDQgBgSAPgRQAOgRAAgHQAAgQgygCQgzgCAAgXIAAgJQACgJAKAAQAMAABEAZQAWAAATgQQAHAAAGgFQAQgQAAhAQgBhUAagYIgEgdQgFgrgnhaIABAAIAZgCQAGAPAMAPIADAEQAXAcAVAAQAOAAADgLQAEgLAFgKQAEgKgDgVIgDgPIARACIAHgBIAAABIAAAHIADADQAqApATAAQAJAAAOgQIABgCQAOgSAAgXQAAgUgJgXIASgQIgSAQIgKgSIgFgJQAJACANAAQAXAAATgEQAcA0AVBLQgfgSgQAAQgQAAgKAWQgKATAAAUQAAAqATAuQAZA+ADANIAAAQIgGAHQgXgQgMAAQgCAGAAAHQAAAIACAHIgDADIgBgBIAAgBIgBAAQgQgTgJgBIAAAAIAAAAIAAAAIgBAAQgGABgFAKIgBACIgBACIgDAJIAAAGIAAAAQAAAfAkANQAUAHAQAAIABAAIAAAAIALAAIADgBIABAAIgBAAIgDABIgLAAIAAAAIgBAAQgQAAgUgHQgkgNAAgfIAAAAIAAgGIADgJIABgCIABgCQAFgKAGgBIABAAIAAAAIAAAAIAAAAQAJABAQATIABAAIAAABIABABIADgDQgCgHAAgIQAAgHACgGQAMAAAXAQIAGgHIAAgQQgDgNgZg+QgTguAAgqQAAgUAKgTQAKgWAQAAQAQAAAfASQAcAPAnAdIAAAAIgUAiIAUgiIAAAAIALgQQBDhiBZg9IAfgSIADAHIgGAKIgEAFIAAABQgfAIgMA7QAHAGAFAAQAqAAA4gjIALgHQApgdAJgdIAAgBQACgHAAgIQAAgEgGgJQgHgLgGAAQgYAAgiAXQgQAKgRAPIgEgGIgCgDIAFgCQBQgsAtgMIABAAIAFgCQA2gOAdAAQAgAAAPAUQAMARAAAeQgBAPgZAlIgaAjIAAABQgtA6hTBbQAagDBBAAQAIgIBrhPIApgeQBlhJAogVQASgKAGAAQBEAAAbAQQAZAQANAtIgbAOQABgggGgGQgHgFgoAAQgZAAgqAZIgCACQgCgIAAgJQAAgKAGgOQgGAOAAAKQAAAJACAIQgxAcAAAhIAAAGQADAXAcAAQAcAAAsgcIgBABQgDAQgFALIADAIIAHARQAGACAGgBQgGATgVAeQgRAXgbAhQgCgHgGAAQgLAPgRgEQgLgRABgJQAAgJADgBIglgBQgLgGgHgJQAAAAgMgNIABADIgBABIAAACIAAABQgNAwAQAhIAGALQAbAoAaAAIAOgBIgCAKIgJAZIgXA8IAXg8QARACAgAQQAgAQAnAHQgSAegbAcIgWAWQg5A2gSAWQAPAKAAAGQAAAEgTAVQAIAOAFgCIAJgGQAOAAACAcQAAAagpgCQgCgDgDgCIgNh2IBkhdIAAgQQgtgEgfAAIgFANQgUA0AAAgIABAQIANB2IAAAEIABAFQgyAjhZAJQggADglAAQgjAAgegJIgDgBIgDgBIgCgBIgBgBQgMgFgHgfIgFgjQgQg7AAhnQADgWAAgNIgDgGIAggOQAYgMAHgPQACgFAHgsIAAgBIAHgpQAfg/AAgrIgDgJIgJAAIAJAAIADAJQAAArgfA/IgHApIAAABQgHAsgCAFQgHAPgYAMIggAOIgTAJQg0A1gLAIQgEgBgBgFIgBgEQAAgHAEgMIADgJIAAAAIABgDIABgBQALgcABAAIAAAAIABAAIAAAAIAAAAIgBAAIAAgCIAAgCIgBgBIgCgGIAAAAIAAAAIAAAAIgBAAIgBADIAAAAIAAABIAAAAIgwgCQgDgEAAgJQAAgUBBgSIANgDQBPgTAAgPQAAhtglAAQgWAAgRBFQgHAdgHAoIgCAIQhBASAAAUQAAAJADAEIAwACIAAAAIAAgBIAAAAIABgDIABAAIAAAAIAAAAIAAAAIACAGIABABIAAACIAAACIABAAIgBAAIAAAAQgBAAgLAcIgBABIgBADIAAAAIgDAJQgEAMAAAHIABAEQgNA9gDBQIgFCTIAAANQgUANgxAYIgNACQgCgfAAgeQAAhnAWhiQAJgtAQgzQAIggAMgjIABgBIATg2QASgyAXg2QgXA2gSAyIgTA2IgBABQgMAjgIAgQgQAzgJAtQgWBiAABnQAAAeACAfIAAAFIgCAAIgFADQhQAmgXAAQgGAAgJgEgAFBBNIAHgQIgThhQAAg/AbhXQAZhRAegwQgeAwgZBRQgbBXAAA/IATBhgAjrkqQgNAqgKAuQAKguANgqIACgGQAQgwAVgrIAVgnQgSgNgOgHIALA7QgVArgQAwQAAgagFgkQgKhDAAgKQAAgRAGgHQARADASAKQgSgKgRgDQgGAHAAARQAAAKAKBDQAFAkAAAaIgCAGgAnMlHIAEAGIABABIACAEIAJAJQAVA0AkAAQAWAAAGgNQAEgHAAgZQAAgbgFguIgEgcIAOgZIgOAZIAAABIgBACQgJANgKAAQgdgLgJgBIAAApQgVgagGAAQgIAHgDAAIAAAtIgNgXIANAXgAhUnkQgNAEgGAFIgLAMIgBAFQAAAOAEAIIADAEQABBFArAAQAjAAArgfQAPgLALgLQARgRAEgPIAAgCIgBABQg7gZgKAAQgUAAgTAPQADgHgEgOQgPgGgKAAIgKACgACtp9IgEACIgJAHQgzAjAAAiQAAATARAAQAtAAA1gzQANgCANgNQAMgNALgZQAAgHgCgGQgXgDgJAAQgNAAgOAFQAIgSAHgGQgHAGgIASQgSAGgVAMIAAgJIAAgHIAAgEIAAgGQABgGARgTQgRATgBAGIAAAGIAAAEIAAAHIAAAJIAAAAgAj4DVIAAAAgAA2iAIAAAAgABLjAIAAAAIAAAAgABLjAIAAAAIAAAAIAAAAIAAAAgAjEmLIAAAAgAooofQgWg1gihEIAXABQAUAAAbgOQAagOAhgbIAVArQAHAIAaAAQAlAAAHgMIAJAAQgEALADAJQgNACgOAJQgWARAAAYQAAANAHAaIACAIIgHABIgRgCIAAgCIgDgPIAIgHIgIAHQgHgmgggJQgKgDgNAAQgGAAgFAEQgFAFgFAJQgKARAAAPQAAAQAHARIgZACIgBAAgAmdowgAm1oxgADUqPIAAAAg");
	this.shape_9.setTransform(69.2,90.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AIUBTIgIgQIAXgGQAQgKAGgJIAAAAIAAAAIADgGQABAAAIAHIAOALQgfAcgUACIgEABIgIgCgAo+ArIgDgEQgLgPgGgPIAUgEIgBAIQAAASAOAAQATAAAAgdIgBgGQASgIAQgMIADAPIABADIACANQAEAVgFAKQgFAKgDALQgEALgOAAQgVAAgXgbgAHKA6QgbAAgDgXIgBgGQAAgfAxgdIACAHQgYAMgLAWIAAAXIAWAAQAVgSAIgPIAHAGQARAOAUAFIgCABIgGAEQgrAcgcAAIgBAAgAneAEIgDgJIAAAAQAIgBAIgDQAEALANAAQAPAAAAgWIAAgEQAUgLAYgUQAKAWAAAVQAAAWgPASIgBABQgOAQgIAAQgUAAgpgpgAA5ANQgRAAAAgRQAAgiAzgjIAKgHIADAEIAEAEQgdAXAAAQQANAGACAAQAPAAAGgLQADgGAEgOIADACIAMAJIAOALIAEgBQg0AyguAAIAAAAgAhMgQQAOg7AegJQABAUATAAQAMAAAGgRQACADASAFQAMAQAHAEIgKAHQg3AjgrAAQgEAAgJgFg");
	this.shape_10.setTransform(76.1,35.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol10, new cjs.Rectangle(-1,-1,170.2,166.9), null);


(lib.Symbol9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF00FF").ss(4,1,1).p("Ai8i7IF5F4");
	this.shape.setTransform(18.9,18.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FF0000").ss(4,1,1).p("Ai8i8IF5F5");
	this.shape_1.setTransform(18.9,18.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},3).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2,-2,41.7,41.7);


(lib.goNext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,11.3).s().p("AhLAqQghgRABgYQgBgZAhgRQAfgSAsAAQAsAAAgASQAgARAAAZQAAAYggARQggASgsAAQgsAAgfgSg");
	this.shape.setTransform(22.8,8.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.502)").s().p("AhUhcICpBdIipBcg");
	this.shape_1.setTransform(25.1,20.4);

	this.blinker = new lib.general_buttoncolor();
	this.blinker.parent = this;
	this.blinker.setTransform(23.4,20.1,1.5,1.5,0,0,0,11.9,11.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,14.8).s().p("AhjA3QgqgXABgfQgBggAqgXQAqgYA5AAQA6AAAqAYQApAXAAAgQAAAfgpAXQgqAYg6AAQg5AAgqgYg");
	this.shape_2.setTransform(23.4,8.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("rgba(0,0,0,0.502)").ss(1,1,1,3,true).p("AAACxQhIAAg0g0Qg1g0AAhJQAAhIA1g0QA0g0BIAAQBKAAA0A0QA0A0AABIQAABJg0A0Qg0A0hKAAg");
	this.shape_3.setTransform(23.3,20.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["rgba(103,103,103,0.839)","rgba(134,134,134,0)"],[0.678,0.918],-0.8,0,0,-0.8,0,24.9).s().p("AitClQhEhFAAhgQAAhgBEhEQBEhEBiAAQBfAABCAwQBBAvAWCrQAVCskNAbQhiAAhEhEgAgICRQBGAAAygwIABgBIAEgDQA0g0AAhIQAAhJg0g0IgGgGIAAAAQgyguhEAAIgBgBIAAAAIgBAAIAAABQhEAAgyAuIgBABIgCACIgCABIAAAAIgBACQg1A0AABJQAABIA1A0IABABIACACQAzAxBGAAIAAAAIABAAIgBAAIAAAAQhGAAgzgxIgCgCIgBgBQg1g0AAhIQAAhJA1g0IABgCIAAAAIACgBIACgCIABgBQAyguBEAAIAAgBIABAAIAAAAIABABQBEAAAyAuIAAAAIAGAGQA0A0AABJQAABIg0A0IgEADIgBABQgyAwhGAAIAAAAIAAAAIAAAAIAAAAg");
	this.shape_4.setTransform(24.2,23.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},2).wait(1));

	// Layer 2
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#33FFFF").s().p("AipCqQhGhHAAhjQAAhiBGhGQBGhHBjAAQBjAABHBHQBGBGAABiQAABjhGBHQhHBGhjAAQhjAAhGhGg");
	this.shape_5.setTransform(24.4,21.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0099FF").s().p("AipCqQhGhHAAhjQAAhiBGhGQBGhHBjAAQBjAABHBHQBGBGAABiQAABjhGBHQhHBGhjAAQhjAAhGhGg");
	this.shape_6.setTransform(24.4,21.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.5,46.7);


(lib.blank = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.blank_gr("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(32.6,17,1,1,0,0,0,32.5,17);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.blank, new cjs.Rectangle(0.1,0,65,34), null);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Tween25("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(80.5,19.3,0.998,0.998,53.2,0,0,6.6,-0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:7,regY:-0.1,scaleX:1,scaleY:1,rotation:0,x:12.6,y:13.5},12).wait(5));

	// Layer 9
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AgtgZQAFACADACQAEACADACQA5AdASAO");
	this.shape.setTransform(73.4,18.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AAjAWQgbgWgrgV");
	this.shape_1.setTransform(77.7,14.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF0000").s().p("AAdAqQgSgPg5gcIgHgEIgIgEIAAggIA1AAQAqAVAcAWIAAAog");
	this.shape_2.setTransform(75,16.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1,1,1).p("AAwAAQgXgTgigRQgCgCgDgBAgvACQAGADAGADQAlAVAOAL");
	this.shape_3.setTransform(76.4,16.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF0000").s().p("AAQAoQgOgLglgVIgMgGQATgTAOgWIAFADQAiARAXATIAAAog");
	this.shape_4.setTransform(76.4,16.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#000000").ss(1,1,1).p("AA/ALQgfgagzgWQgGgDgGgCQgEgCgEgCQgFgCgFgCAg+gCQAEACAFACQAEACAEACQA5AeATAP");
	this.shape_5.setTransform(74.9,15.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF0000").s().p("AAfAzQgTgPg5geIgIgEIgJgEIADgVIABAAIAJgbIAKAEIAIAEIAMAFQAzAWAfAaIAAAog");
	this.shape_6.setTransform(74.9,15.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#000000").ss(1,1,1).p("ABuAYQgfgZg0gXQg2gZhBgOAhtgXQAtAKAhAPQBWAsAXAS");
	this.shape_7.setTransform(70.2,14.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF0000").s().p("ABOBAQgXgShWgsQghgPgtgKIAHgRIAKgXQBBAOA2AZQA0AXAfAZIAAAog");
	this.shape_8.setTransform(70.2,14.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#000000").ss(1,1,1).p("AB5AbQgggagzgWQhEgfhVgOAh4gZQA7ALAoATQBWAsAXAS");
	this.shape_9.setTransform(69.1,14.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF0000").s().p("ABYBDQgXgShVgsQgpgTg7gKIACgOIADgcQBVAOBEAfQAzAWAgAaIAAAog");
	this.shape_10.setTransform(69.1,14.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#000000").ss(1,1,1).p("ACYAgQgggbgzgWQhfgqh9gLAiPgbQBfAJA5AcQBXArAXAS");
	this.shape_11.setTransform(66.1,13.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FF0000").s().p("AB3BHQgXgShXgrQg5gchfgJIgCgPIgFgcQB8ALBfAqQAzAWAfAbIAAAng");
	this.shape_12.setTransform(66.1,13.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#000000").ss(1,1,1).p("AC6AiQgfgbg0gWQh4g1iogEAi2gdQCTACBPAnQBWArAYAS");
	this.shape_13.setTransform(62.6,13.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FF0000").s().p("ACZBJQgXgShWgrQhPgniTgCIgCggIgBgLQCoAEB4A1QA0AWAfAbIAAAng");
	this.shape_14.setTransform(62.6,13.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#000000").ss(1,1,1).p("ADjAiQgfgbg0gWQiDg6i5AAQgbAAgbACAjXgcQAYgBAYAAQCmgBBWAqQBXArAXAT");
	this.shape_15.setTransform(58.5,13.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FF0000").s().p("ADDBKQgXgThXgrQhWgqimABIgvABQgDgZgJgSQAbgBAbgBQC5AACDA7QA0AVAfAbIAAAog");
	this.shape_16.setTransform(58.5,13.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#000000").ss(1,1,1).p("AEGAiQgfgbg0gWQiDg6i5AAQhAAAg8AIAj0gWQA1gHA8AAQCkgBBXAqQBXArAXAT");
	this.shape_17.setTransform(55,13.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FF0000").s().p("ADmBKQgXgThXgrQhXgqikABQg8AAg1AHIgCgFQgGgUgJgSQA8gHBAgBQC5AACDA7QA0AVAfAbIAAAog");
	this.shape_18.setTransform(55,13.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#000000").ss(1,1,1).p("AErAiQgfgbg0gWQiEg6i4AAQhnAAhfAVAkbgIQBWgUBmgBQClgBBXAqQBWArAXAT");
	this.shape_19.setTransform(51.3,13.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FF0000").s().p("AEKBKQgXgThWgrQhXgqilABQhmABhWAUIgDgUQgDgNgJgLQBfgUBngBQC4AACEA7QA0AVAfAbIAAAog");
	this.shape_20.setTransform(51.3,13.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#000000").ss(1,1,1).p("AFdAiQgfgbg0gWQiEg6i4AAQieAAiMAxAlMAXQB5gzCmgBQClgBBXAqQBWArAYAT");
	this.shape_21.setTransform(46.3,13.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FF0000").s().p("AE8BKQgXgThWgrQhXgqilABQimABh4AzIgRguQCMgyCeAAQC5AACDA7QA0AVAfAbIAAAog");
	this.shape_22.setTransform(46.3,13.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_4},{t:this.shape_3}]},1).to({state:[{t:this.shape_6},{t:this.shape_5}]},1).to({state:[{t:this.shape_8},{t:this.shape_7}]},1).to({state:[{t:this.shape_10},{t:this.shape_9}]},1).to({state:[{t:this.shape_12},{t:this.shape_11}]},1).to({state:[{t:this.shape_14},{t:this.shape_13}]},1).to({state:[{t:this.shape_16},{t:this.shape_15}]},1).to({state:[{t:this.shape_18},{t:this.shape_17}]},1).to({state:[{t:this.shape_20},{t:this.shape_19}]},1).to({state:[{t:this.shape_22},{t:this.shape_21}]},1).to({state:[{t:this.shape_22},{t:this.shape_21}]},1).to({state:[{t:this.shape_22},{t:this.shape_21}]},1).wait(5));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(56.3,9.4,34.7,22.2);


(lib.UI = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//Menu button -----------------------------------------
		this.btn_menu.addEventListener("click", openMenu.bind(this));
		
		//volume buttons -----------------------------------------
		this.vol_dwn.addEventListener("click", volDwn.bind(this));
		this.vol_up.addEventListener("click", volUp.bind(this));
		this.vol_mute.addEventListener("click", volMute.bind(this));
		
		//Nav buttons -----------------------------------------
		this.btn_goNext.addEventListener("click", openNext.bind(this));
		this.btn_goBack.addEventListener("click", openPrev.bind(this));
		
		//background music ---------------------------------------
		var bgm = createjs.Sound.play('bgmPA',{loop:-1});
		//var vo = createjs.Sound.play('VO');
		
		//volume vars -----------------------------------------
		var mute= false;
		bgm.volume = 0.05;
		var prev_vol = bgm.volume;
		
		//Menu function -----------------------------------------
		function openMenu(){
		
		 window.open ("../miniMenu/miniMenu.html","_self");
		}
		
		//volume functions -----------------------------------------
		function volDwn()
		{
			createjs.Sound.volume = createjs.Sound.volume -0.05;
			if(!mute){
				bgm.volume -= 0.05;
				prev_vol = bgm.volume;
			}
			console.log(bgm.volume);
			console.log(prev_vol);
		}
		function volUp()
		{
			createjs.Sound.volume = createjs.Sound.volume +0.05;
			if(!mute){
				bgm.volume += 0.05;
				prev_vol = bgm.volume;
			}
			console.log(bgm.volume);
			console.log(prev_vol);
		}
		
		function volMute()
		{
			if(!mute){
				mute = true
				bgm.volume = 0;
			}
			else{
				mute = false;
				bgm.volume = prev_vol;
			}
			console.log(mute);
		}
		
		
		//Nav functions -----------------------------------------
		
		function openNext(){
		
		 window.open ("predAdj_scene6.html","_self");
		}
		
		function openPrev(){
		
		 window.open ("predAdj_scene4.html","_self");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// mute
	this.vol_mute = new lib.vol_mute();
	this.vol_mute.parent = this;
	this.vol_mute.setTransform(31.8,2.1,1,1,0,0,0,15,14.1);
	new cjs.ButtonHelper(this.vol_mute, 0, 1, 2, false, new lib.vol_mute(), 3);

	this.timeline.addTween(cjs.Tween.get(this.vol_mute).wait(1));

	// main
	this.instance = new lib.Copyright("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-220.6,376.5);

	this.btn_goBack = new lib.goNext();
	this.btn_goBack.parent = this;
	this.btn_goBack.setTransform(-438,335.3,1,1,0,0,180);
	new cjs.ButtonHelper(this.btn_goBack, 0, 1, 2, false, new lib.goNext(), 3);

	this.btn_goNext = new lib.goNext();
	this.btn_goNext.parent = this;
	this.btn_goNext.setTransform(-1.7,335.3);
	new cjs.ButtonHelper(this.btn_goNext, 0, 1, 2, false, new lib.goNext(), 3);

	this.vol_up = new lib.vol_pos();
	this.vol_up.parent = this;
	this.vol_up.setTransform(-6.7,2.6,1,1,0,0,0,9,7);
	new cjs.ButtonHelper(this.vol_up, 0, 1, 2, false, new lib.vol_pos(), 3);

	this.vol_dwn = new lib.vol_neg();
	this.vol_dwn.parent = this;
	this.vol_dwn.setTransform(-28.7,2.6,1,1,0,0,0,9,7);
	new cjs.ButtonHelper(this.vol_dwn, 0, 1, 2, false, new lib.vol_neg(), 3);

	this.btn_menu = new lib.menu_main();
	this.btn_menu.parent = this;
	this.btn_menu.setTransform(-89.6,2.6,1,1.143,0,0,0,23.4,10.5);
	new cjs.ButtonHelper(this.btn_menu, 0, 1, 2, false, new lib.menu_main(), 3);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.5,1,1).p("AAYBrQgBgLgUgUQgQgRgKAAIAAh1QAKAAASgTQATgTAAgKg");
	this.shape.setTransform(-47.7,2.3,0.687,0.681);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AADBMQgQgRgKAAIAAh1QAKgBASgSQATgTAAgJIAADTQgBgKgUgUg");
	this.shape_1.setTransform(-47.7,2.3,0.687,0.681);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s("#000000").ss(1.5,1,1).rr(-0.75,-3.45,1.5,6.9,0.2);
	this.shape_2.setTransform(-52.2,2.3,1,1.003);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1.5,1,1).p("AAHAAQAAAJgHAHQgCAEgEACIAAgrQAEACACAEQACACACACQADAFAAAGg");
	this.shape_3.setTransform(-43.2,2.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgGgUQAEABACAEIABAAIADAFQADAEAAAGQAAAJgGAHIgBAAQgCAEgEABg");
	this.shape_4.setTransform(-46.5,2.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.btn_menu},{t:this.vol_dwn},{t:this.vol_up},{t:this.btn_goNext},{t:this.btn_goBack},{t:this.instance}]}).wait(1));

	// vol_frame
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s("#000000").ss(1.5,1,1).rr(-33,-12,66,24,4.9);
	this.shape_5.setTransform(-24.7,2.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_5).wait(1));

}).prototype = getMCSymbolPrototype(lib.UI, new cjs.Rectangle(-486.5,-13,534.3,399), null);


// stage content:
(lib.predAdj_Scene5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{scene5:0,scene5repeat:60});

	// timeline functions:
	this.frame_0 = function() {
		playSound("sexy_sax");
	}
	this.frame_10 = function() {
		playSound("bananaslookgood");
	}
	this.frame_59 = function() {
		/* _root.gonow = true;*/
	}
	this.frame_82 = function() {
		/* gotoAndPlay("scene5repeat");
		stopAllSounds();*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(10).call(this.frame_10).wait(49).call(this.frame_59).wait(23).call(this.frame_82).wait(1));

	// Layer 4
	this.instance = new lib.Symbol10();
	this.instance.parent = this;
	this.instance.setTransform(401.7,208.5,1,1,0,0,0,84.1,82.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(83));

	// Layer 3
	this.instance_1 = new lib.Symbol9();
	this.instance_1.parent = this;
	this.instance_1.setTransform(371.8,93.3,1,1,0,0,0,18.9,18.9);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF3FFF").s().p("AgwB+QgTgEgKgHQgJAAgGgGQgHgGAAgJIACgvIACgvIgCgzIAAg0QAAgIAIgJQAIgIAKAAQAFAAAVAJIAcANQAuAPAgAfQAmAlAAAsQAAAbgNAZQgOAYgWAPQgbARgtAAQgMAAgOgDgAg2BPQAGAEAIACQAIACAKAAQAgAAAPgJQAOgJAIgPQAIgQAAgQQAAgmgtgcQgPgKgxgUg");
	this.shape.setTransform(477.7,90.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF3FFF").s().p("AhTBgQgigcAAgtQAAg0AhgsQAlgxA4AAQA3AAAbAZQAbAZAAAyQAAA0gfArQgjAyg3AAQgvAAghgbgAgxguQgYAfAAAmQAAAaAVAQQATAQAeAAQAhAAAWgiQAWgfAAgmQAAghgPgNQgOgMgkAAQgiAAgYAig");
	this.shape_1.setTransform(452.7,90.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF3FFF").s().p("AhTBgQgigcAAgtQAAg0AhgsQAlgxA4AAQA3AAAbAZQAbAZAAAyQAAA0gfArQgjAyg4AAQguAAghgbgAgxguQgYAfAAAmQAAAaAVAQQATAQAdAAQAiAAAWgiQAWgfAAgmQAAghgPgNQgOgMgkAAQghAAgZAig");
	this.shape_2.setTransform(427.2,90.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF3FFF").s().p("AhUBqQgVgWAAgsQAAgoAUgpQATgqAggaQAVgSAYAAQAPAAAaALQAfANAAAOQAAAJgGAHQgHAGgJAAQgEAAgRgJQgQgJgNAAQgNAAgYAfQgjAsAAAyQAAAaAIAKQAIAKAXAAQAXAAATgOQASgOAKgcQglADgaAMQgEACgFAAQgKAAgGgHQgGgGAAgJQAAgYA4gIQAfgFArAAQAJAAAHAGQAGAGAAAIQAAALgKAGQgKAvggAcQghAcgrAAQgqAAgUgWg");
	this.shape_3.setTransform(403.9,89.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("Ag2CIQgNgJgigjQgkgkgBgUQgCgXAkgiQAPgPAfgcQAggbAOgPIALgMQAFgJAEgEQARgRAPAQQAFAEACAIQAPAJAOAKQAMAKALAKQAcAcAKAXQAGAOgKAKQgGAGgIAAQgKAAgGgGQgDgCgBgDQgNgXgRgRQgJgIgKgIQgLgJgNgHIgsAqIAuAnIAdAXQAHAHAAAJQABAJgHAHQgNANgQgNIgcgYIgzgqIgXAVQgWAWAAAFQgBADANANIAVAUIAVAUIAHAGIAHAGQAHAGABAIQABAJgIAIQgHAHgIAAQgGAAgHgFg");
	this.shape_4.setTransform(218.9,206);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgeBoQgjgNggggQgcgcgEgcQgDgXANgNQAHgHAJgBQAIgBAIAIQAKAKgGAPQgHATAWAWQATATAbAJQAaAKAKgKQAOgOgIgQQgFgLgXgYQgSgUgJgWQgLgdARgRQAWgVAnAEQApAFAbAbQALALALAVQAOAZgIAJQgGAFgJABQgJABgHgHQgFgGgIgMQgIgNgGgFQgOgOgTgGQgUgHgIAIQgEAFABAGQABAHAHAJIAbAeQAWAaADAaQACAcgXAYQgSARgYAAQgPAAgSgHg");
	this.shape_5.setTransform(202.6,192.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AhcBSQghgggEgqQgFgrAgggQAmgmA2gHQA8gIApAoQAmAmABAlQACAjgkAkQglAlg0AJQgKACgMAAQgtAAgggggAgFhFQgmAGgbAbQgTATADAYQADAZAVAVQAYAYAngIQAkgHAcgbQAXgXgBgTQgBgTgagZQgTgTgeAAIgQABg");
	this.shape_6.setTransform(186.4,174.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgcCSQgHgHgBgIQAAgKAGgGIAYgYIAWgZIALgLQgSgRgdgVIgyghIgZAVQgQANgJAKQgFAFgJAAQgIgBgGgGQgHgGAAgJQAAgIAGgFIAigfQAYgUAKgLIArgoIApgpQAGgGAIAAQAIAAAHAHQAGAGABAIQgBAJgGAGIgZAZIgZAYIgLAKIgMALIAxAiQAdAUATARIApgmQAKgIAQgHQATgHAIAIQAGAGAAAIQABAJgGAFIgEADQgKAGgGAGIgKAJIgLAJQgKALgWATIggAeIgXAaIgXAZQgFAGgIAAQgJAAgGgGg");
	this.shape_7.setTransform(168.9,156.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AhwB0QgGgGgBgIQAAgKAGgHIAFgDIAFgFIAPgQIAPgQQAOgPAYgbIAjgqIgEgGQgZgZgLgRQgJgQALgLQAGgGAIgBQAKgBAHAJIAPATQAJAMAHAHIAVAUIAUAUIAYAaQAQARAIAIQAHAHAAAJQAAAIgGAGQgHAHgIAAQgJAAgHgHIgagcIgZgbIgpAvQgaAfgRAQIgKAMIgKAMQgJAJgKADIgIABQgHAAgGgGg");
	this.shape_8.setTransform(155.2,137);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF0000").s().p("AhQB2QgFgIgBgIIAChoQADhFAAgjQAAgJAGgGQAGgGAKAAQAJAAAHAGQAFAGAAAJIgBAmIgCAmQALgKBFhNQAHgIAKABQAIAAAHAFQAHAHAAAJQAAAKgmAoQgbAegdAcIAhAgQAUASAQAMQAIAGAJADQAQAGAAAOQAAAIgDAGQgHAIgKAAQgWAAgjgdIgygvIAABBQAAAIgEAFQgFAIgLAAQgMAAgHgKg");
	this.shape_9.setTransform(333.6,90.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF0000").s().p("AhTBgQgigcAAgtQAAg0AhgsQAmgxA3AAQA3AAAbAZQAbAZAAAyQAAA0gfArQgjAyg3AAQgvAAghgbgAgxguQgYAfAAAmQABAaATAQQAUAQAeAAQAhAAAWgiQAWgfAAgmQAAghgPgNQgOgMgkAAQgiAAgYAig");
	this.shape_10.setTransform(310.4,90.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FF0000").s().p("AhTBgQgigcAAgtQAAg0AhgsQAlgxA4AAQA3AAAbAZQAbAZAAAyQAAA0gfArQgjAyg4AAQguAAghgbgAgxguQgYAfAAAmQAAAaAVAQQATAQAdAAQAhAAAXgiQAWgfAAgmQAAghgPgNQgOgMgkAAQgiAAgYAig");
	this.shape_11.setTransform(284.9,90.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FF0000").s().p("AhSBeIACgxQAEhDABhTQgBgJAHgGQAGgHAJAAQAKAAAGAHQAHAGgBAJQABBTgFBFIgDAmQAlAAA5gSIAHgBQAKAAAGAHQAGAHgBAIQAAANgNAGQgSAIgnAHQgjAGgWAAQgmAAAAgig");
	this.shape_12.setTransform(263.8,90.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AhUBmQgTgPAAgTQAAgKAGgHQAGgGALAAQAOAAAGAOQAJAUAgAAQAZAAAagMQAagMAAgPQAAgTgRgHQgLgEgigBQgbAAgVgJQgdgNAAgYQABgfAggZQAggZAlAAQAQAAAWAHQAcAIAAAMQAAAIgGAGQgGAHgKAAQgHAAgPgDQgOgDgIAAQgUAAgRAKQgTAJAAAMQAAAGAGAEQAGADALACIAnACQAjADAUARQAWARAAAhQAAApguAVQgjAPgsAAQgoAAgXgRg");
	this.shape_13.setTransform(207.7,90.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("ABQB2QgNgBgMgcQgJgTgFgYQgMACgaACIglAEQgHARgSAjQgHALgMAAQgJAAgHgGQgHgGAAgJQAAgIAXguQgCgFAAgEQABgIAPgEQAWglAbgpQAmg8AJAAQARAAAGAVIAKAyIAXBmIAIAVQAGANAAAHQAAAJgHAGQgGAGgIAAIgBAAgAgLAPIAVgDIAWgCIgLgzIggA4g");
	this.shape_14.setTransform(184.8,90.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AhtB4QgGgGAAgJIABgSIABgTIAAgdIABgbIgBgdIAAgdIgCgcIgCgcQAAgJAIgIQAIgHALAAQALAAAOATQBGBmBFA/IAAgYQAAhMgBgbIgCgRIgCgRQAAgWAXAAQAaABAABOIgBAZIgBBiQAAAHgCARQgDAVgUAAQgLAAgOgNQg8g2hLhhIgBAxIABAlIABAlQAAAvgXgBQgLABgHgIg");
	this.shape_15.setTransform(160.3,90.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("ABQB2QgNgBgMgcQgJgTgFgYQgMACgaACIglAEQgHARgSAjQgHALgMAAQgJAAgHgGQgHgGAAgJQAAgIAXguQgCgFAAgEQABgIAPgEQAWglAbgpQAmg8AJAAQARAAAGAVIAKAyIAXBmIAIAVQAGANAAAHQAAAJgHAGQgGAGgIAAIgBAAgAgLAPIAVgDIAWgCIgLgzIggA4g");
	this.shape_16.setTransform(135.4,90.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AhtB4QgGgGAAgJIABgSIABgTIAAgdIABgbIgBgdIAAgdIgCgcIgCgcQAAgJAIgIQAIgHALAAQALAAAOATQBGBmBFA/IAAgYQAAhMgBgbIgCgRIgCgRQAAgWAXAAQAaABAABOIgBAZIgBBiQAAAHgCARQgDAVgUAAQgLAAgOgNQg8g2hLhhIgBAxIABAlIABAlQAAAvgXgBQgLABgHgIg");
	this.shape_17.setTransform(110.9,90.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("ABQB2QgNgBgMgcQgJgTgFgYQgMACgaACIglAEQgHARgSAjQgHALgMAAQgJAAgHgGQgHgGAAgJQAAgIAXguQgCgFAAgEQABgIAPgEQAWglAbgpQAmg8AJAAQARAAAGAVIAKAyIAXBmIAIAVQAGANAAAHQAAAJgHAGQgGAGgIAAIgBAAgAgLAPIAVgDIAWgCIgLgzIggA4g");
	this.shape_18.setTransform(86,90.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AhMB3QgIgIAAgJIAAikIgBgWQAAgMABgIQACgPAZgDQAMgDAcAAQAcgBAbAUQAgAWAAAhQAAASgGAMQgGAKgMALQAPAHALAPQAOARAAAQQAAAVgXASQgPAMgRAHQgjAOg4AAQgJgBgHgHgAgpBUQAbgCAegIQAbgIAAgJQAAgMgSgKQgNgIgMAAIgpgCgAgpgyIAAAhQAOACAHgBQAvgDAAggQAAgLgOgLQgOgKgQAAIgYAAg");
	this.shape_19.setTransform(64.9,89.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#000000").ss(4,1,1).p("Al9rdIAAF6I24AAIl0AAArzLeIxCxBAl9ljMAonAAA");
	this.shape_20.setTransform(274.9,147.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance_1}]}).wait(83));

	// Layer 1
	this.instance_2 = new lib.Symbol5();
	this.instance_2.parent = this;
	this.instance_2.setTransform(296.8,42.5,1.694,1.533,0,0,0,45,12.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgRAPQgIgHAAgIQAAgHAIgHQAIgGAJAAQALgBAHAHQAIAGAAAIQAAAIgIAHQgHAHgLgBQgJABgIgHg");
	this.shape_21.setTransform(470.5,327.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AArB2QgKAGgMACQgLACgLAAQgjAAgXgWQgYgXAAgkQAAgqAYgYQAXgaAmAAQALAAAKACQAJADAHAFQACg2ACgTQADgTASAAQAJAAAGAGQAFAGAAAIQAAAYgDAtQgEAsAAAXQAAA4AEATIAAAEQAAAJgGAGQgGAFgJAAQgLAAgGgKgAgfAHQgMANAAAbQAAARANAMQAMAMARAAQALAAAGgDQAEgBAKgJIAFgEIAAg6QgFgKgIgEQgIgEgMgBQgWAAgLANg");
	this.shape_22.setTransform(454,316.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgzBCQgWgWgCgkQgBgiAUgaQAYghApAAQAgAAASAaQARAWAAAhQAAAkgUAZQgVAdgkgBQgdABgVgUgAgWgaQgJAPAAATQAAASAKALQAJAHALABQANgBAKgIQALgMABgSQACgxgdAAQgSAAgLARg");
	this.shape_23.setTransform(436.2,320.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgzBCQgWgWgCgkQgBgiAUgaQAYghApAAQAgAAASAaQARAWAAAhQAAAkgUAZQgVAdgkgBQgdABgVgUgAgWgaQgJAPAAATQAAASAKALQAJAHALABQANgBAKgIQALgMABgSQACgxgdAAQgSAAgLARg");
	this.shape_24.setTransform(419.3,320.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AhQBkQABgIAFgGQAGgFAIAAQAHAAAOADQAMACAKAAQAXAAALgOQAKgOACgeQgHAIgLAEQgJAEgMAAQgfAAgTgUQgUgVAAgeQAAgrAagaQAbgbAtAAQAPAAAKADQALAEAHAHQATADAAAVQAAAKgCATQgIAkAAApQgCAygQAWQgUAfgzAAQg8AAgBgYgAgYhGQgNAQAAAZQAAASAIAKQAGAJAOgBQAMAAAOgNQALgOADgOIAGgvIgLgFIgJgBQgZAAgQARg");
	this.shape_25.setTransform(402.5,324.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AAkB1QgHgPgQgTIgYggIgUAOIgCAqQAAAJgGAGQgGAFgKAAQgWABAAgbIACglIACglIABgzIAAgzIAAgPIgBgRQAAgJAGgGQAGgFAKAAQAJAAAGAFQAGAGAAAJIABARIABAQIgBAsIgBAqQAVgPArgrQAHgHAIAAQAJAAAHAGQAHAHAAAIQAAAHgHAHQgSAUgZAWIAgAqQAYAfAAALQAAAIgHAHQgHAFgJAAQgMAAgHgLg");
	this.shape_26.setTransform(372.1,316);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgzBCQgWgWgCgkQgBgiAUgaQAYghApAAQAgAAASAaQARAWAAAhQAAAkgUAZQgVAdgkgBQgdABgVgUgAgWgaQgJAPAAATQAAASAKALQAJAHALABQANgBAKgIQALgMABgSQACgxgdAAQgSAAgLARg");
	this.shape_27.setTransform(354.3,320.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgzBCQgWgWgCgkQgBgiAUgaQAYghApAAQAgAAASAaQARAWAAAhQAAAkgUAZQgVAdgkgBQgdABgVgUgAgWgaQgJAPAAATQAAASAKALQAJAHALABQANgBAKgIQALgMABgSQACgxgdAAQgSAAgLARg");
	this.shape_28.setTransform(337.4,320.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgOB7QgHgGABgJIAAjXQAAgJAGgGQAHgGAHAAQAKAAAFAGQAGAGABAJIAADOQgBAegVAAQgJAAgFgGg");
	this.shape_29.setTransform(324.7,315.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgrBRQgYgIAAgRQAAgQASAAQAIAAAOAEQANAFAIAAQAeAAAAgNQABgHgXgLQgfgOgJgFQgWgPAAgWQAAggAigLQATgGAmAAQARAAAHAEQAKAGAAAOQAAAcgPAAQgQAAgDgNIgMgBQglAAAAALQAAAGAVAKQAfAOAMAIQAWAPAAAVQAAAbgZAOQgUALgdAAQgUAAgRgHg");
	this.shape_30.setTransform(298.6,320.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AAmBIQgPAHgLADQgLAEgGAAQgmAAgTgUQgSgUAAgpQAAgkAbgbQAcgbAmAAQAPAAATAIQAYALAAANQAAAFgEAFIgCAPIgBAWQAAAdAEANIAHAQIAGAPQAAAIgGAFQgGAGgIAAQgIAAgPgOgAgVgfQgQARAAAVQAAAVAHAKQAIALAPAAQAIAAAJgDQAJgEAHgGQgEgkAAgTIABgLIACgPIgGgCIgEgBQgUAAgQARg");
	this.shape_31.setTransform(282.2,320.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAgBIIgEggQgDgSAAgPIABgNIAAgOIABgFIAAgHQAAgNgGAAQgOAAgMARQgMARgIAZIgBAPIgBAOIgBANIgBAOQAAAJgGAGQgGAGgKAAQgJAAgGgGQgGgGAAgJIgBgOIgBgNQAAgPACgbIACgqIAAgOIgBgOQAAgJAHgGQAGgGAJAAQAVAAABAZIAAABQAXgXAYAAQAeAAALAZQAHARAAAhIAAALIAAAJQAAAMAEATQADAUAAAMQAAAIgGAGQgGAGgKAAQgTAAgCgTg");
	this.shape_32.setTransform(265,320.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AAmBIQgPAHgLADQgLAEgGAAQgmAAgTgUQgSgUAAgpQAAgkAbgbQAcgbAmAAQAPAAATAIQAYALAAANQAAAFgEAFIgCAPIgBAWQAAAdAEANIAHAQIAGAPQAAAIgGAFQgGAGgIAAQgIAAgPgOgAgVgfQgQARAAAVQAAAVAHAKQAIALAPAAQAIAAAJgDQAJgEAHgGQgEgkAAgTIABgLIACgPIgGgCIgEgBQgUAAgQARg");
	this.shape_33.setTransform(247.6,320.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AAgBIIgEggQgDgSAAgPIABgNIAAgOIABgFIAAgHQAAgNgGAAQgOAAgMARQgMARgIAZIgBAPIgBAOIgBANIgBAOQAAAJgGAGQgGAGgKAAQgJAAgGgGQgGgGAAgJIgBgOIgBgNQAAgPACgbIACgqIAAgOIgBgOQAAgJAHgGQAGgGAJAAQAVAAABAZIAAABQAXgXAYAAQAeAAALAZQAHARAAAhIAAALIAAAJQAAAMAEATQADAUAAAMQAAAIgGAGQgGAGgKAAQgTAAgCgTg");
	this.shape_34.setTransform(230.4,320.2);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAmBIQgPAHgLADQgLAEgGAAQgmAAgTgUQgSgUAAgpQAAgkAbgbQAcgbAmAAQAPAAATAIQAYALAAANQAAAFgEAFIgCAPIgBAWQAAAdAEANIAHAQIAGAPQAAAIgGAFQgGAGgIAAQgIAAgPgOgAgVgfQgQARAAAVQAAAVAHAKQAIALAPAAQAIAAAJgDQAJgEAHgGQgEgkAAgTIABgLIACgPIgGgCIgEgBQgUAAgQARg");
	this.shape_35.setTransform(213.1,320.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AguB3QgFAFgJAAQgIAAgGgFQgGgGAAgIIAAgMIABgLIAAiwQAAgLAFgJQAGgLAMAAQAQAAAAASIAAAGIgBAHIAAA8QAMgHAKgDQALgDAJAAQAlAAAWAbQAVAYAAAjQAAAkgYAaQgZAZgkAAQgWAAgUgHgAgRgDQgLAEgNAKIAABCQAWAJAPAAQATAAANgNQAMgOAAgUQAAgUgKgNQgLgNgSAAQgHAAgLAEg");
	this.shape_36.setTransform(194.6,316.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("Ag1BEQgagUAAgkQAAgmAVgcQAXgeAmAAQAbAAASAJQAYALAAAZQAAARgTANQgJAGgaALIg0AXQAHAIALAEQALAEAMAAQAVAAAPgIQANgIAIAAQAQAAAAAQQAAASgaALQgWAJgZAAQgkAAgYgRgAgVglQgKAKgGAUIAjgQQAUgJANgIQgLgGgRAAQgNAAgLAJg");
	this.shape_37.setTransform(162,320.3);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgsBRQgXgIAAgRQAAgQATAAQAHAAANAEQAOAFAIAAQAeAAAAgNQAAgHgVgLQgggOgJgFQgWgPAAgWQAAggAhgLQAUgGAnAAQAPAAAIAEQAKAGAAAOQAAAcgPAAQgQAAgCgNIgOgBQgkAAAAALQAAAGAWAKQAfAOAKAIQAXAPAAAVQAAAbgZAOQgUALgcAAQgVAAgSgHg");
	this.shape_38.setTransform(145.3,320.3);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgzBCQgWgWgCgkQgBgiAUgaQAYghApAAQAgAAASAaQARAWAAAhQAAAkgUAZQgVAdgkgBQgdABgVgUgAgWgaQgJAPAAATQAAASAKALQAJAHALABQANgBAKgIQALgMABgSQACgxgdAAQgSAAgLARg");
	this.shape_39.setTransform(129,320.5);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AAkByQgDgMgDgXQgDgWAAgPIAAgLIAAgMIAAgOQgBgHgHAAQgRAAgNAPQgHAIgNAXQAAA4gGALQgFAOgOAAQgJgBgGgFQgHgHAAgIIACgJQABgDABgmQgCggAChIIAAgFIABgZIgBgOIgCgOQAAgJAGgGQAHgGAJAAQAQAAAFARQACAJABATIgBAgIgBAeQALgLANgFQAMgGAPAAQAbAAAMAPQAIAMADAVIABAoIADAeIAFAeIABAGQAAAJgHAGQgGAFgJAAQgQAAgFgQg");
	this.shape_40.setTransform(111.9,316.1);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgOByQgHgHgBgJIABgGIABgHIgBgWIgBgWQAAgVgDgjIgFg4IgIAAQgjAAgUgFQgSgEAAgRQABgIAFgGQAHgIALABIAYADIAZABIAdAAIAcAAIAjACIAjABQAKAAAGAGQAHAGAAAJQAAAJgHAGQgGAGgKAAIgmgBQgZgCgNAAIAFBAQADAnAAAXIABAQIABAQQAAAMgEAJQgHAMgMAAQgIAAgGgFg");
	this.shape_41.setTransform(91.4,316.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.instance_2}]}).wait(83));

	// Layer 2
	this.UI = new lib.UI();
	this.UI.parent = this;
	this.UI.setTransform(548,53.9,1,1,0,0,0,54,40.5);

	this.instance_3 = new lib.Back("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(275.5,199.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3},{t:this.UI}]}).wait(83));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(282.5,200.6,534,398.7);
// library properties:
lib.properties = {
	id: '18AEAAF09F5DA74BB48497137B3DF611',
	width: 550,
	height: 400,
	fps: 12,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"sounds/bananaslookgood.mp3", id:"bananaslookgood"},
		{src:"sounds/wrong_answer.mp3", id:"wrong_answer"},
		{src:"sounds/High_Screaming_Gtr.mp3", id:"High_Screaming_Gtr"},
		{src:"sounds/powersynth.mp3", id:"powersynth"},
		{src:"sounds/bgmPA.mp3", id:"bgmPA"},
		{src:"sounds/salsa_groove.mp3", id:"salsa_groove"},
		{src:"sounds/sexy_sax.mp3", id:"sexy_sax"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['18AEAAF09F5DA74BB48497137B3DF611'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;