(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.vol_pos = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.5,1,1).p("ABagwIAABgQAAAWgZAAIiBAAQgZAAAAgWIAAhgQAAgVAZAAICBAAQAZAAAAAVg");
	this.shape.setTransform(9,7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgKA0QgDgDAAgGIAAgfIgFABIgTAAQgVAAAAgNQAAgHAHgDQADAAALAAIAYgBIAAgQIABgRQABgFADgDQADgCAEAAQAFAAADADQAEAEgBAFIAAAHIgBAIIABAPIAAAAIAKABIAIAAIAHgBIABAAIAJABQAKABADAGIABAEIgBAFIgDADIgDADIgFABIgEgBIgCAAIgEAAIgNAAIgOAAIAAAgQAAAMgLAAQgGAAgDgDg");
	this.shape_1.setTransform(9.6,6.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00CCFF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICBAAQAYAAABAWIAABfQgBAWgYAAgAgHAqQAAAGADADQAEADAEAAQAMAAABgMIAAggIANAAIAOAAIADAAIACAAIAFABIAFgBIADgDIACgDIABgFIgBgEQgCgGgKgBIgJgBIgBAAIgHABIgIAAIgKgBIAAAAIgBgPIABgIIAAgHQAAgFgEgEQgDgDgGAAQgEAAgBACQgEADgBAFIgBARIAAAQIgYABQgKAAgDAAQgHADgBAIQABAMAUAAIATAAIAFgBg");
	this.shape_2.setTransform(9,7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0099FF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICBAAQAYAAABAWIAABfQgBAWgYAAgAgHAqQAAAGADADQAEADAEAAQAMAAABgMIAAggIANAAIAOAAIADAAIACAAIAFABIAFgBIADgDIACgDIABgFIgBgEQgCgGgKgBIgJgBIgBAAIgHABIgIAAIgKgBIAAAAIgBgPIABgIIAAgHQAAgFgEgEQgDgDgGAAQgEAAgBACQgEADgBAFIgBARIAAAQIgYABQgKAAgDAAQgHADgBAIQABAMAUAAIATAAIAFgBg");
	this.shape_3.setTransform(9,7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_1},{t:this.shape_2},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape_3},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,19.9,16);


(lib.vol_neg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.5,1,1).p("AhAhFICBAAQAZAAAAAVIAABgQAAAWgZAAIiBAAQgZAAAAgWIAAhgQAAgVAZAAg");
	this.shape.setTransform(9,7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgMALIgCAAIgPAAQgLAAAAgKQAAgJALAAIAdgBIAdgBIAEABQAIAAAAAJQAAAIgKABIgVABIgJABIgNAAg");
	this.shape_1.setTransform(9.1,6.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICAAAQAaAAAAAWIAABfQAAAWgaAAgAABgLIgdAAQgLAAAAAKQAAAJALAAIAPAAIACAAIANAAIAJAAIAVgBQAKgBAAgIQAAgJgIAAIgEgBIgdABg");
	this.shape_2.setTransform(9,7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00CCFF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICAAAQAaAAAAAWIAABfQAAAWgaAAgAABgLIgdAAQgLAAAAAKQAAAJALAAIAPAAIACAAIANAAIAJAAIAVgBQAKgBAAgIQAAgJgIAAIgEgBIgdABg");
	this.shape_3.setTransform(9,7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0099FF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICAAAQAaAAAAAWIAABfQAAAWgaAAgAABgLIgdAAQgLAAAAAKQAAAJALAAIAPAAIACAAIANAAIAJAAIAVgBQAKgBAAgIQAAgJgIAAIgEgBIgdABg");
	this.shape_4.setTransform(9,7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_1},{t:this.shape_3},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape_4},{t:this.shape}]},1).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,19.9,16);


(lib.vol_mute = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AASBRQAAgIgQgQQgMgNgHAAIAAhZQAHAAANgOQAPgOAAgHg");
	this.shape.setTransform(15.6,13.9,1.2,1.201);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AgGglIANAAQABAAAAABIAABJQAAABgBAAIgNAAQgBAAAAgBIAAhJQAAgBABAAg");
	this.shape_1.setTransform(10.5,13.8,1.2,1.201);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#990000").ss(1,1,1).p("AhHBRQgCgDgDgCQgDgDgBgCQgbgeAAgpQAAgsAfgfQAgggAsAAQAjAAAcAUQAGAEAHAIQACACADACQAbAeAAApQAAAtggAfQgfAggtAAQgpAAgegbICYiY");
	this.shape_2.setTransform(15.1,14.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1,1,1).p("AAJAAQAAANgJAJQgCAFgGACIAAg5QAGADACAFQAJAIAAAMg");
	this.shape_3.setTransform(20.6,13.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1.5,1,1).p("ACWAAQAAA7gsAoQgtAqg9AAQg+AAgsgqQgrgoAAg7QAAg6ArgqQAKgIAKgHQAFgDAGgDQAJgFAKgEQAEgBAFgCQAWgHAZAAQAaAAAXAHQAEACAEABQAKAEAJAFQAFADAFADQAKAHAKAIQAsAqAAA6g");
	this.shape_4.setTransform(15,14.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAAABtQAuAAAfggQAfggAAgsQAAgpgbgeIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfQgfAgAAAsQAAApAaAeIAFAFIAFAFQAeAbAoAAgAhGBSICXiYQAbAeAAApQAAAsgfAgQgfAgguAAQgoAAgegbgAAuAaQAHgCACgGQAJgJAAgMQAAgMgJgJQgCgFgHgDIAAA6IAAAAgAhGBSIAAAAgAhLBNIgFgFQgageAAgpQAAgsAfggQAggfArAAQAkAAAbAUQAHAEAHAHIAEAFIiXCYIgFgFgAAuAagAAuggQAHADACAFQAJAJAAAMQAAAMgJAJQgCAGgHACgABAgDIAAAAgABRhGIAAAAg");
	this.shape_5.setTransform(15,14.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#00CCFF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAhLhLQgfAgAAAsQAAApAaAeIAFAFIAFAFQAeAbAoAAQAuAAAfggQAfggAAgsQAAgpgbgeIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfg");
	this.shape_6.setTransform(15,14.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhHBRICYiYQAbAeAAApQAAAtggAfQgfAggtAAQgpAAgegbgAAuAZQAGgCADgGQAJgIAAgMQAAgNgJgJQgDgFgGgDIAAA6IAAAAgAhMBMIgEgFQgbgeAAgpQAAgsAfgfQAgggAsAAQAjAAAcAUQAGAEAHAIIAFAEIiYCYIgFgFgAAuAZgAAughQAGADADAFQAJAJAAANQAAAMgJAIQgDAGgGACgABAgDIAAAAg");
	this.shape_7.setTransform(15.1,14.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0099FF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAhLhLQgfAgAAAsQAAApAaAeIAFAFIAFAFQAeAbAoAAQAuAAAfggQAfggAAgsQAAgpgbgeIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfg");
	this.shape_8.setTransform(15,14.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAhGBSQAeAbAoAAQAuAAAfggQAfggAAgsQAAgpgbgeQAbAeAAApQAAAsgfAgQgfAgguAAQgoAAgegbICXiYIiXCYgAhqABQAAApAaAeIAFAFIAFAFIgFgFIgFgFQgageAAgpQAAgsAfggQAggfArAAQAkAAAbAUQAHAEAHAHIAEAFIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfQgfAgAAAsIAAAAgAAuAaQAHgCACgGQAJgJAAgMQAAgMgJgJQgCgFgHgDIAAA6IAAAAgAAuAagAAuggQAHADACAFQAJAJAAAMQAAAMgJAJQgCAGgHACgABAgDIAAAAg");
	this.shape_9.setTransform(15,14.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_2},{t:this.shape_4},{t:this.shape_3},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_7},{t:this.shape_8},{t:this.shape_2},{t:this.shape_4},{t:this.shape_3},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_9},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,32,30.1);


(lib.Tween23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AC9DoQgJgPgIgjIgLg1QgMgxgbinIg+C5IgSA6QgMAjgMAWQgNAXgUAAQgTAAgKgTQgGgNgGgUIgJgiQgfhtgYh7IgLA3IgoCiQgCAcgNA4QgJAYgWAAQgOAAgKgLQgHgJAAgNQAAg0AVhKIAih7IAShhQAOhEAPgVQAMgSASAAQAUAAAKAXQAMAbANBUQARBmAjB0QAsh1AhiAIAKgtQAFgbAJgRQAMgXAVAAQAaAAAOAzQAFASAHA3QASCKAbBjIAQA0QALArAAAKQAAANgKAJQgKAJgNAAQgQAAgLgRg");
	this.shape.setTransform(298.1,3.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("ABrCfQgIgbgMhGQgfAFgzALIhRARQgPAogmBOQgJARgRAAQgNAAgJgJQgKgJAAgNQAAgPAuhiQgFgIAAgKQAAgZAegHQAjhBA2hVQBIh1ASAAQAYAAAJAiIATBnIAuDVIASAxQAJAZAAAIQAAANgKAJQgJAJgNAAQgcAAgVhJgAgnAWQAlgJBLgNIgZh3g");
	this.shape_1.setTransform(246.4,3.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AidDpQgIgKgBgNIgChIQgCgxAAgYQAAgcAGg3QAHg4gBgcQAAgQgCgfQgDgfAAgPQAAgSAKgNQALgQAUABIBLAGQAqAFAcAQQB8BCAABfQAAAvgqAjQgiAdg0APQBgAzAwA5QAIAKAAALQAAANgJAKQgKAJgNAAQgLAAgLgKQhlhkh8gjIACA8IACA9QAAANgJAKQgIAJgNAAQgOAAgJgJgAhiiKQACAXAAAOQAAAZgEAkIgHA9IAOAAIANAAQBPAAAmgVQASgIAOgQQAQgRAAgMQAAgrgwgkQgsgigwgGIgugDg");
	this.shape_2.setTransform(204.7,2.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AieDSQglgqAAhVQAAhPAlhUQAmhUA7g0QAngjArAAQAcAAAuASQA4AXAAAaQAAANgJAKQgJAKgNAAQgHAAgMgIQgvgdghAAQgWAAgZAYQgNAMgXAgQhHBeAABtQAAA6ASAXQATAZA0AAQA2AAApgiQAqglARhFQhVAEg8AdQgHADgHAAQgNAAgJgKQgIgKAAgMQAAgRAQgKQBBgoCjAAQANAAAJAJQAJAIAAAOQAAAUgRAIQgTBfg9A4Qg9A4hSAAQhMAAgmgqg");
	this.shape_3.setTransform(163.3,2.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("ABrCfQgIgbgMhGQgfAFgzALIhRARQgPAogmBOQgJARgRAAQgNAAgJgJQgKgJAAgNQAAgPAuhiQgFgIAAgKQAAgZAegHQAjhBA2hVQBIh1ASAAQAYAAAJAiIATBnIAuDVIASAxQAJAZAAAIQAAANgKAJQgJAJgNAAQgcAAgVhJgAgnAWQAlgJBLgNIgZh3g");
	this.shape_4.setTransform(117.9,3.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AiGDiQgKgJABgNQgBgNAKgKQAIgJANAAQAUAAAugGQADgZAAggQAAgVgCgfQgCgfAAgUQAAhHAIhqIgnABIgpABQgNAAgIgJQgKgJAAgNQAAgdAdgDQAagCBEAAQA8AABcANQAcAEAAAdQAAAOgLAJQgJAHgMAAQgUAAgdgEIgygGQgHBZAABRIABA1IABA1QAAAdgCAYIBhgCQANAAAJAKQAJAIAAAOQAAANgJAJQgJAJgNAAIg0ABIgzABQgUAAgoAGQgpAFgUAAQgNAAgIgJg");
	this.shape_5.setTransform(78.2,3.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AhgD3QgjgIgSgNIgCAAQgOAAgJgJQgJgJAAgOQAAggAEhBQAChAAAggIgBhqIgBhsQAAgNAMgOQANgOANAAQAIAAApAVQAvAXAIACQBWAfA+A9QBJBJgBBWQAAA1gZAxQgYAvgrAeQgvAghZABQgXAAgcgIgAh0hVIABBYIgFCnIAHAFQAbARApABQBFAAAggWQAegUARgjQASgiAAglQAAhWheg+QgfgUhygzg");
	this.shape_6.setTransform(39.3,3.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AibC+QhAg3AAhYQAAhpA/hXQBGhhBpAAQBlAAAxAuQAzAvAABnQAABpg5BVQhDBihoAAQhXAAg8g0gAhshoQgwBGAABRQAAA8AsAlQAqAjA+AAQBKAAAwhLQAshEAAhSQAAhKghgeQgggchKgBQhLABg0BKg");
	this.shape_7.setTransform(-28.3,3.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgVDiQgKgJAAgOIACgNIABgOIgCgtIgCguQAAgsgHhPQgHhWgBglIgcAAQhEAAgmgKQgZgGAAgYQAAgNAIgJQAJgLAPABIAxAFQAfAEATAAIA4gBIA3gBQAXAAAvAEQAvADAXAAQANAAAJAJQAJAJAAAOQAAANgJAJQgJAJgNAAQgXAAgvgDQgugEgYAAIgWAAQABArAHBfQAHBYAAAxIACAhIACAhQAAAVgGAPQgJAUgSAAQgLAAgKgIg");
	this.shape_8.setTransform(-72.4,2.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AjPDwQgIgKgBgNQAAgNADgaIACgnIABg5IABg5IgBg8IgBg+QAAgTgEgnQgDgmAAgTQAAgOAMgMQAMgMAPAAQARAAAYAkQBNBzA8BMQBJBZBWBSQABgNgBgaIAAgnQAAiGgLhQQgBgIgHgYQgGgVAAgMQAAgkAhAAQA1AAAADIIgBBlIgBBmQAAAPgFAiQgFAfgcAAQgQAAgYgWQh9h2ihjfIgCBGIgBBFIACBNIABBNQAABTghAAQgQAAgLgLg");
	this.shape_9.setTransform(-140,2.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AidDpQgIgKgBgNIgChIQgCgxAAgYQAAgcAGg3QAGg4AAgcQAAgQgCgfQgDgfAAgPQAAgSAKgNQALgQAUABIBKAGQArAFAcAQQB8BCAABfQAAAvgqAjQgiAdg0APQBhAzAvA5QAIAKAAALQAAANgJAKQgKAJgNAAQgMAAgJgKQhnhkh7gjIACA8IACA9QAAANgJAKQgIAJgNAAQgOAAgJgJgAhiiKQACAXAAAOQAAAZgEAkIgGA9IANAAIAOAAQBOAAAmgVQASgIAOgQQAQgRAAgMQAAgrgwgkQgsgigwgGIgugDg");
	this.shape_10.setTransform(-184.6,2.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("ABrCfQgIgbgMhGQgfAFgzALIhRARQgPAogmBOQgJARgRAAQgNAAgJgJQgKgJAAgNQAAgPAuhiQgFgIAAgKQAAgZAegHQAjhBA2hVQBIh1ASAAQAYAAAJAiIATBnIAuDVIASAxQAJAZAAAIQAAANgKAJQgJAJgNAAQgcAAgVhJgAgnAWQAlgJBLgNIgZh3g");
	this.shape_11.setTransform(-228.6,3.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AiHDsQgdgaAAhkIABgqIADgzQgEgHAAgIQAAgJAGgJQAGhYAAgrQAAgLgDgXQgDgWAAgLQAAglAeAAQAOABAJAIQAlgKAggEQAigFAbAAQBLAAAtARQAUAJAAAVQAAANgIAJQgJALgNAAIgKgCQgzgPgxAAQgZAAgdAFQgeAEgiAKQACAUAAAMQAAAqgEBMICFgOQA8gFANAAQANgBAKAJQAJAJAAAOQAAAbgdAEIhJAGIiNANIgCApIgBAkQAABEAKAMQAIAJAoAAIA6gBIA5gBIASgCIASgCQAgAAABAgQgBAagaAFQgdAGhfAAQhfAAgcgag");
	this.shape_12.setTransform(-270,2.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AiFDyQgSgNAAgjIAGhlQAIiMAAisQAAgNAJgJQAJgJAMAAQAOAAAJAJQAJAJAAANQAACugJCNIgEAwQgCAZAAAUQBRABB6goIAJgBQAOAAAIAKQAIAKAAANQAAATgTAJQgkAQhKANQhEANgrAAQgfAAgOgKg");
	this.shape_13.setTransform(-307.2,3.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-327.5,-45.9,655,91.8);


(lib.menu_main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgWAoQgQgMAAgdIAAgIIAAgIIABgHIAAgGQAAgFABgEQADgFAEgBQADAAADACQADADgBADIAAAKIAAAKIAAAIIAAAIQAAAJABAHQADAJAFAEQADABAIABQAPAAAGgaQADgNAAgaIABgFQADgFAFAAQADAAADAEQAAAAAAABQAAAAABABQAAAAAAABQAAAAAAABQAAAXgCANQgDATgKAOQgEAFgGAEQgHAFgIgBQgPABgGgGg");
	this.shape.setTransform(37.7,11.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgoAtQgDgCAAgDIABgIIAAgHIAAgKIAAgKIAAgKIAAgMIgBgKIAAgLQAAgDADgDQADgDAEAAQAEAAAFAIQAaAmAaAXIAAgJIgBgmIgBgGIAAgHQAAgIAJAAQAJAAAAAeIAAAJIgBAkIAAAJQgBAIgIAAQgEAAgFgFQgWgUgcgkIgBASIABAOIAAAOQAAARgJAAQgDAAgDgDg");
	this.shape_1.setTransform(28.5,10.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgaAsQgHgFAAgTIABgXIACgXIgBgGIgBgGQAAgJAJAAQAAAAABAAQABAAAAAAQABABAAAAQABAAAAAAIANgCIALgBQAPAAAIADQAGACAAAGQAAADgCACQgDADgDAAIgDAAQgJgDgJAAIgJABIgKACIgBAXIAWgDIAOgBQAEABACACQADACAAADQAAAHgIAAIgOABIgYADIAAAMQAAAMABABQABABAGAAIAKgBIALAAIAEAAIADAAQAEAAACABQADADAAAEQAAAGgHACQgGABgRAAQgUAAgFgGg");
	this.shape_2.setTransform(20,10.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAfAmIgCgOQgDgKgEgTIgJAXIgDALIgFALQgDAFgEAAQgFAAgEgHIgDgLIgIgeIgIAcIgBANQgDAJgHgBQgDAAgDgCQgCgDAAgDQAAgKAFgNIAGgWIADgSQADgMADgFQADgEAEAAQAGABACAFQADAFADAQQACAPAFARQAGgRAGgVIADgNQADgIAHAAQAGgBADAKIADAPQADAYAGASIAFAUQAAADgDACQgDACgDAAQgGABgEgKg");
	this.shape_3.setTransform(10.9,11);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1.5,1,1).p("Ai4hoIFxAAQAxAAAAAwIAABxQAAAwgxAAIlxAAQgxAAAAgwIAAhxQAAgwAxAAg");
	this.shape_4.setTransform(23.4,10.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ai4BpQgxAAAAgwIAAhxQAAgwAxAAIFxAAQAxAAAAAwIAABxQAAAwgxAAg");
	this.shape_5.setTransform(23.4,10.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(1.5,1,1).p("Ai4hoIFxAAQAxAAAAAwIAABwQAAAxgxAAIlxAAQgxAAAAgxIAAhwQAAgwAxAAg");
	this.shape_6.setTransform(23.4,10.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#00CCFF").s().p("Ai4BpQgxAAAAgxIAAhvQAAgxAxAAIFxAAQAxAAAAAxIAABvQAAAxgxAAg");
	this.shape_7.setTransform(23.4,10.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0099FF").s().p("Ai4BpQgxAAAAgxIAAhvQAAgxAxAAIFxAAQAxAAAAAxIAABvQAAAxgxAAg");
	this.shape_8.setTransform(23.4,10.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_8},{t:this.shape_6},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,48.8,23);


(lib.general_buttoncolor = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{resetRed:1});

	// timeline functions:
	this.frame_0 = function() {
		this.play();
	}
	this.frame_8 = function() {
		this.gotoAndPlay("resetRed");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(8).call(this.frame_8).wait(2));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#D5FFD7","#61EF01","#1DA400","#004A00"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgwAAgigjQgjgigBgxQABgwAjgiQAigjAwAAQAxAAAjAjQAjAigBAwQABAxgjAiQgjAjgxAAIAAAAg");
	this.shape.setTransform(11.9,11.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FFFFFF","#EC0000","#9D0000","#480000"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgwAAgigjQgjgigBgxQABgwAjgiQAigjAwAAQAxAAAjAjQAjAigBAwQABAxgjAiQgjAjgxAAIAAAAg");
	this.shape_1.setTransform(11.9,11.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},8).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,23.7,23.6);


(lib.Copyright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAcAIIgEgLIgDAKQgEAJgEAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBIgCgJIgCgHQgGATgDAAIgCgBIgBgDIABgCQACgEACgHIADgMQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQAFAAACAIIACALIADgGIADgJQACgFACAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIADAKIACAHIADAIIABABIgBADIgDABQgDAAgCgJgAgUANIgBgIIAAgGIgBgHIgFAAIgFgBQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAEAAIAFAAIAPAAIADAAIADAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABQAAABAAABQAAAAgBABQAAAAAAAAQgBAAgBAAIgNABIAAAHIABAHIAAAEIABADIgBADIgCAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAgBg");
	this.shape.setTransform(57.3,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgMAYQgGgCAAgEIABgDQAAgBABAAQAAAAABAAQAAgBABAAQAAAAAAAAIAEACIAFACIAEABIAGgBQAEgCAAgCQAAgGgIgCIgEgCIgIgCQgDgCAAgFQAAgJAIgEIAIgDIAIgDIADAAIAEABIABADIABAEIAAADIgBAEIgDABQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBIgCgEIgKADQgGACAAAFIACAAQAJACAGADQAHAEAAAJQAAAHgGADQgFADgIAAQgFAAgGgCg");
	this.shape_1.setTransform(51,2.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgLATQgHgGAAgJQAAgIAGgJQAGgLAIAAQAEAAAGACQAGADAAADIgBADQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgDgBIgCgCQgCgCgGAAQgEAAgEAIQgEAIAAAEQAAAGAEADQADADAGAAIAFgBIAFgDIACgBIADACIABADQAAADgGADQgHADgDAAQgJAAgFgGg");
	this.shape_2.setTransform(46.6,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgDAgQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgIIAAgIIABgKIAAgKQAAAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAIADgBIACABQABAAAAABQAAAAAAABQABAAAAABQAAAAAAAAIgBAKIAAAKIAAAIIAAAIQAAABAAAAQAAAAAAABQAAAAgBAAQAAABAAAAIgCABIgDgBgAgCgXQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAQAAgBgBAAg");
	this.shape_3.setTransform(43.1,1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AALAVIgBgJIgBgKIAAgDIAAgEQAAgKgDAAQgFABgEAFQgEAGgCAGIAAAFIgBAEIABAEIAAAEIgBADIgDACIgEgCIgBgDIAAgEIAAgEIAAgMIABgMIAAgEIAAgEIABgEIADgBQAEABAAAFIABAFQAHgKAHAAQAHAAADAHQABAEABAIIAAAFIAAACIABAKIAAAJIgBAEIgDABQgEAAAAgFg");
	this.shape_4.setTransform(39.5,2.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAOAWIgDgDIgHADIgFACQgKAAgFgGQgEgFAAgMQAAgKAHgHQAIgIAJAAQAEAAAEACQAGADAAADIgBACIAAAGIgBAJIABAIIADAJIABABIAAABIgBAEIgDABIgDgDgAgGgKQgFAGAAAGQAAAHACADQADAEAFAAQADAAADgBIAEgEIgBgQIAAgEIABgFIgDgBIgCgBQgFABgFAFg");
	this.shape_5.setTransform(34.8,2.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAMAiIgCgLIgBgLIAAgDIAAgDQAAgIgDABQgGAAgDADIgHAKQAAARgBADQgBABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgBgEIABgBIAAgGIAAgHIAAggIABgHIgBgEIAAgEQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBQADAAAAAEIABAIIAAAKIAAAJIAAAFQAEgFAEgDQADgDAFABQAGAAAEAEQABAEAAAHIABAIIAAAJIACAJIABACQAAAAgBAAQAAABAAAAQAAABAAAAQgBAAAAAAIgDABQgDAAgBgCg");
	this.shape_6.setTransform(30,1.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgLATQgHgGAAgJQAAgIAGgJQAGgLAIAAQAEAAAGACQAGADAAADIgBADQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgDgBIgCgCQgCgCgGAAQgEAAgEAIQgEAIAAAEQAAAGAEADQADADAGAAIAFgBIAFgDIACgBIADACIABADQAAADgGADQgHADgDAAQgJAAgFgGg");
	this.shape_7.setTransform(25,2.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgOATQgHgFAAgKQAAgLAGgHQAGgJAJAAQAHAAAFACQAFADAAAHQAAAEgFAEIgJAEIgQAHQADAFADABQAEACAEAAIAHgBQAFgCACgCQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAABAAIADABIABADQAAAEgIAEQgHADgGAAQgJAAgGgFgAgIgLQgEAFgCAGIAOgFQAHgEADgCQgDgEgHAAQgFAAgDAEg");
	this.shape_8.setTransform(20.3,2.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAbAhIgCgHIgCgIQgCgGgDgXIgJAZIgDAJIgEAIQgBADgCAAQgDAAgCgDIgBgFIgBgEIgIghIgCAIIgGAWIgBANQgCADgDAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBIAAgDQAAgHACgLIAGgQIACgPQACgJACgDQACgDACAAQADAAABAEQADAEABAMQADAOAFAPQAFgPAFgTIABgGIACgGQACgEADAAQAEAAABAIIADAKQACATADAOIADAIIACAHQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAAAIgDABQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAgBg");
	this.shape_9.setTransform(13.8,1.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgQAUIAAgeIAAgEIAAgEQAAgFAEAAQAEAAAAAIQAIgJAKAAQAEAAABADQACADAAAFIAAADQAAAGgEAAQgEAAAAgFIAAgDIAAgDQgHAAgEAEQgDACgDAGIAAAXQAAAFgEAAQgEAAAAgFg");
	this.shape_10.setTransform(5.1,2.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAOAWIgDgDIgHADIgFACQgKAAgFgGQgEgFAAgMQAAgKAHgHQAIgIAJAAQAEAAAEACQAGADAAADIgBACIAAAGIgBAJIABAIIADAJIABABIAAABIgBAEIgDABIgDgDgAgGgKQgFAGAAAGQAAAHACADQADAEAFAAQADAAADgBIAEgEIgBgQIAAgEIABgFIgDgBIgCgBQgFABgFAFg");
	this.shape_11.setTransform(0.5,2.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgBAaQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIgBgQIgBgPQAAgEgCgDQgDABgCAEIgGAFIgCADIAAAHIgBAIIABADIAAAEQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAABIgEABQgEAAAAgLIAAgIIABgHIgBgHIAAgHQgBgKAFAAIADABQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABIAAACIgBADIAAAFQACgFAFgEQAEgEADAAQAHAAACAHQADgDACgCQAEgBAFAAQAGAAADAIIACAMIAEAYIgCADIgDABQgEAAAAgDIgCgOIgCgNIgBgGQgCgEgBAAIgGADIgGAEIAAAIIACALIABAMIgBADIgEABQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAg");
	this.shape_12.setTransform(-5.2,2.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgCAaQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIgBgQIgBgPQAAgEgBgDQgEABgCAEIgGAFIgCADIgBAHIAAAIIAAADIABAEQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAABIgDABQgGAAAAgLIABgIIAAgHIAAgHIgBgHQABgKAEAAIADABQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAABIAAACIAAADIAAAFQADgFAEgEQAFgEADAAQAGAAACAHQACgDADgCQAEgBAEAAQAIAAACAIIACAMIAEAYIgCADIgDABQgDAAgBgDIgCgOIgCgNIgBgGQgBgEgCAAIgGADIgFAEIAAAIIABALIABAMIgBADIgEABQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAgBAAg");
	this.shape_13.setTransform(-12.2,2.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAOAWIgDgDIgHADIgFACQgKAAgFgGQgEgFAAgMQAAgKAHgHQAIgIAJAAQAEAAAEACQAGADAAADIgBACIAAAGIgBAJIABAIIADAJIABABIAAABIgBAEIgDABIgDgDgAgGgKQgFAGAAAGQAAAHACADQADAEAFAAQADAAADgBIAEgEIgBgQIAAgEIABgFIgDgBIgCgBQgFABgFAFg");
	this.shape_14.setTransform(-18.1,2.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgQAUIAAgeIAAgEIAAgEQAAgFAEAAQAEAAAAAIQAIgJAKAAQAEAAABADQACADAAAFIAAADQAAAGgEAAQgEAAAAgFIAAgDIAAgDQgHAAgEAEQgDACgDAGIAAAXQAAAFgEAAQgEAAAAgFg");
	this.shape_15.setTransform(-22.4,2.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgWAeQgFgGAAgMQAAgLAFgLQAGgMAIgIQAGgFAFAAQAEAAAGACQAJAEgBADIgBAEIgDABIgDgBQgGgEgFAAQgDAAgDAEIgFAFQgKAOAAAPQAAAIADAEQACADAHAAQAIAAAGgFQAGgFACgKQgNAAgHAEIgCABQgBAAAAAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgCgCQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAABAAQAJgFAWAAIAEABIABACQAAABAAABQAAAAgBABQAAAAAAABQgBAAAAABQgDANgJAIQgJAIgLAAQgKAAgGgGg");
	this.shape_16.setTransform(-27.7,1.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgOAhIgBgDIADgIIAKgXQAFgPAHgHIABgBIgVgBIgKAAQgEAAAAgEQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAIARABIAPAAIAIAAQAFAAAAADQAAACgDADIgEAFQgFAHgFAJIgIARIgDAKIgEAKQAAAAgBABQAAAAAAAAQgBABgBAAQAAAAgBAAIgDgCg");
	this.shape_17.setTransform(-36.2,1.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AABAiIgIAAIgEAAQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgFAHAAIACAAIACAAIAAgGIgBgGIABgQIABgRQgGAEgBAAIgDgBIgCgDQAAgCAEgDIAHgFQADgEADAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAADIAAADIAAAFIAAAEIgBAPIgCAOIABAGIABAGIAEAAQABAAAAAAQAAAAABAAQAAAAAAABQABAAAAAAIABADIgBADIgDABg");
	this.shape_18.setTransform(-41,1.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgTAXQgFgJAAgPQAAgMAGgKQAIgLALAAQAMAAAGAKQAGAJAAAMQAAATgHAJQgGAKgMAAQgNAAgGgMgAgLgRQgEAHAAAJQAAANAEAIQAEAHAHAAQAJAAAEgLQADgHAAgLQAAgLgEgHQgEgFgHAAQgHgBgFAJg");
	this.shape_19.setTransform(-45.9,1.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AANAhIgDgBIgGABIgGAAIgFAAIgFABIgCAAIgBAAQgDAAgBgDIgBgGQAAgKAGgGQADgDALgHIAHgGQAEgFAAgFQAAgDgEgCQgDgCgDAAQgDAAgEACIgGAFIgDABQgEAAAAgDQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQAFgFAEgCQAFgDAFAAQAHAAAGAEQAGAEAAAHIgBAJIgEAGQgDADgIAFQgIAFgCADQgFAFAAAHIAJAAIAMgBIAHABQAEACAAACQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBABIgCABIgEgBg");
	this.shape_20.setTransform(-51.3,1.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgeABQgBgLALgKQALgJANAAQANAAAHAIQAIAIAAAMQAAAKgJAKQgKALgNAAIAAAAQgfAAABgdgAgOgPQgJAHABAJQAAALAFAFQAHAFAKAAQAKAAAHgJQAGgIAAgHQAAgJgDgFQgFgFgJAAIgCAAQgLAAgHAGgAgLAJQgFgEAAgFQAAgHAHgFQAGgEAHAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAAAQABABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAABAAABQAAAAgBABQAAAAgBAAQgBAAgBAAIgBAAIgBAAQgEAAgEACQgFADAAADQAAACAEABIAEACQADAAADgDIAEgCIAEABIABADQgBADgEADQgGADgEAAQgFAAgFgEg");
	this.shape_21.setTransform(-57.7,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.3,-7.1,126.6,16.6);


(lib.MicStill = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.1,1,1).p("ACzAOIllgb");
	this.shape.setTransform(36.5,53.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AD/j+QBpBqAACUQAACVhpBpQhqBqiVAAQiUAAhqhqQhphpAAiVQAAiUBphqQBqhpCUAAQCVAABqBpg");
	this.shape_1.setTransform(36,36);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(0.1,1,1).p("Ah+gZQgGgDgDgLQgCgJgEgJQgCgJABgKQAAgEAAgFQAAgEAAgEQAAgEgBgDQgCgKABgKQABgKAFgIQAEgHAIgFQAIgGAIgFQAIgGAJgCQAJgCAIACQAKABAKABQAJABAJADQAKAEAGADQAIgFAHgIQAGgGAJgDQAIgCAJgDQAJgCAJgEQAJgDAKAAQAJgBAJACQAJACAHAGQAIAGAHAGQAHAGAGAHQAEAGADAIQACAFABAFQABAJADAJQACAJACAKQACAJgBAKQgBAJgEAJQgEAJgEAIQgBABgBABQgFgIgIgGQgEgCgEgBQgKgCgCgJQACgCACgCAgyiUQgJgBgJAFQgIAFgIAGQgIAGgDAJQgEAJAAAJQAAAKgBAKQgBAJAAAJAgciZQgHgDgJgCQgJgCgKAAQgJABgKABQgJAAgHAHQgHAGgGAHQgGAHgEAJQgDAIAAAJQAAAJAAAKQAAAFAAACAhggpQgFgEgHAAQgHABgFAFQgFAGgBAIAhZggQgBgJACgIQACAFACAFQAEALAHAHQgCgIgBgHQgBgKgBgJQgBgJAAgJQgBgKACgJQACgJAFgHQAGgIAHgHQAHgFAHgFQAIgFAJgCQALgCAFAKQABgGAJgDQAIgDAJgBQAKAAAKAAQAJABAJACQAKACAIAGQAIAGAFAIQAFAIAEAIQAEAJgCAKQgCAJgDAJQgCADgBACQACgBACgDQABgBACgCAhZggQgCgFgEgDQAAAAgBgBQAFAHADAGQgBgCAAgCgAgFiVQAGgFAHgGQAHgGAKgDQAJgCAKgCQAJgBAKABQAJACAJAEQAIADAJAFQAHAEAFAHQAFAHAEAIQADAJABAJQACAKgBAKQAAADgBADAAziiQAIgCAKAFQAHAEAIAGQAHAFAHAGQAHAGAEAIQAFAJACAJQACAJgBAKAgihgQgHgGgKAFQgJAFAAAJQgBADABAEAgXhLQgDgBgDAAQgLAAgEAJQgEAJACAKQADAJAGAGQAGAGALAAQAIgBAFgEQAEgEAAgHQAAgBAAgBQgBgJgEgHQgBAAAAgBQgDgDgCgDQgCgDgCgDQgBgCgEABgAgDgtQgBAAAAAAQgCACgCAAQgLAAgBgIQgCgLANAAAgOhEQgEgFgFgCAAThvQAFgJAKACQAGACACADABDhPQAAgCAAgDQgBgDgDgEQgEgGgCAEQgLABgGAGQgHAGgBAKQgBAKAHAFQAIAEAKgCQAJgDABgIQgFABgBgEQgEgMALAAgABChAQABgHAAgIAAFgdQAAAJAIAGQAGAEAIAAQAJgBAIgBQAJgCAJgDQAIgEgBgKQAAgIgHgCQgJgDgKAAQgDAAgDAAACAgpQAAAFABAFQABAEAAAEQAAAJgEAIQgDAIgDAJQgDAJgBAJQgCAJAAAKQgBAKgFAKQAAADgBADQAAACAAACQAAAJgHAHQgHAGgIAEQgIAEgIAEQgIAEgIAAAAzCDQAFAGALACQAFABAGABQAJADAJADQAHACAIADQAJACAJAFQAHADAHAFQAHAFAHAGQAGAFAHAEQAFADAEADABkALQgFAGgIAGQgHAFgJAEQgIADgJAFQgIAFgJAAQgKAAgKAAQgJAAgIgCQgKgCgHgFQgIgFgIgGQgHgFgEgGQgCACAAAEQgBADABADAgsAOQADgEAGgCAhRAkQABABAAABQAFAIADAJQAEAJAFAIQAEAHAGAHQAHAHAHAGQAIAGAJADQAIADAKADQAIACAKgBQAKAAAKAAQAIAAAJABQABAAABAAIAAAAQgDAHABAIQAAACAAABQABAKAFAJAhVAWQACgDADgDQAFgHgCgJAhVAWQgFADgEAAQgFABgEgDQgIgFgFgIQgEgHgDgIQgDgIAAgMAhRAkQAAAAAAAAQgEgHAAgHAiyCmQAIgFAKgDQAJgDAJgCQAGgCAIgBQAJgBAJgDQAJgDAJgDQAKgDAEgHQAEgIAAgKQAAgKgBgKQgBgJgBgJQgBgKAAgKQAAgIgCgIQAAgBgBgB");
	this.shape_2.setTransform(36.5,35.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgrAKQgCgKANAAIABAAQAEAHABAJIgBAAIgEACIgBAAQgKAAgBgIgAAlgFQgEgMALAAQABAIgCAHIgCAAQgDAAgBgDg");
	this.shape_3.setTransform(38.8,29.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgvAcQgGgGgCgJQgDgKAEgIQAFgJAKAAIAGABQAFACAFAFIAEAGQgNAAACAKQABAIAMAAIADgCIABACQAAAHgDAEQgFAEgJABIgBAAQgKAAgGgGgAAdAGQgHgFABgJQABgKAGgGQAHgGAKgBQACgEAFAGQADAEAAADIAAAFQgLAAAEAMQABAEAGgBQgCAHgJADIgGAAQgGAAgFgCg");
	this.shape_4.setTransform(37.4,29.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFCC97").s().p("AiyCOQAIgEAKgDIARgFIAPgDQAJgBAJgDIASgGQAKgDADgHQAFgJAAgKIgBgTIgCgTQgCgJABgKQAAgJgCgIIAAAAIAIASIAIAQQAEAIAGAGIAPANQAIAGAJAEIASAFIAHABIAHABIAAAAIAAAAIABAAIADAAIATAAIASAAIABAAIAAAAQgCAHABAIQAEAHAMABIALADIASAFIAPAFQAJADAJAEQAHAEAHAFIAOAKQAGAGAHAEIAJAGgAAzBvQABAKAFAIQgFgIgBgKIAAgEIAAAEgAAzBcIgSAAIgTAAIgDAAIgBAAIAAAAIAAAAIgHgBIgHgBIgSgFQgJgEgIgGIgPgNQgGgGgEgIIgIgQIgIgSIgBgBIAAgBQgEgHAAgGIAFgGQADgFAAgGIAAgEIAAAEQAAAGgDAFIgFAGQgFACgEABQgGAAgDgCQgJgFgEgHQgFgHgDgJQgCgJAAgLQABgIAFgGQAFgGAHAAQAHgBAFAFQAFAGACAHIAAgFQgBgIABgIIAFAKQADALAIAGIgDgPIgDgSIgBgSQAAgKACgKQABgIAGgIQAGgHAHgHIANgLQAJgFAJgCQALgCAFAKQABgGAJgDQAHgCAKgBIATAAIATADQAJACAIAGQAJAFAFAIIAJARQAEAIgCAKIgGASIgCAGIAEgEIADgEQACAKAJABIAIAEQAJAFAEAIIACAKIABAIQAAAJgEAJIgGARIgFARIgBATQgBALgGAJIAAAGIAAAEQAAAKgIAGQgGAHgIADIgQAIQgIAEgJAAIAAAAIgBAAgAghACIAPAKQAIAFAJACQAJACAJABIATgBQAKAAAIgEIARgJQAIgDAIgFQAIgFAFgHQgFAHgIAFQgIAFgIADIgRAJQgIAEgKAAIgTABQgJgBgJgCQgJgCgIgFIgPgKQgHgFgEgGQADgEAFgBQgFABgDAEQgCACAAAEIgBACIABADIgBgDIABgCQAAgEACgCQAEAGAHAFgAAZgiIABAAIAAAAIASgCIARgFQAIgDAAgJIAAgCQAAgHgIgDIgBAAQgGgCgIAAIAAAAIAAAAIgBAAIgCAAIgGAAIAGAAIACAAIABAAIAAAAIAAAAQAIAAAGACIABAAQAIADAAAHIAAACQAAAJgIADIgRAFIgSACIAAAAIgBAAIAAAAIAAAAQgHAAgFgDIAAgBQgJgFABgKQgBAKAJAFIAAABQAFADAHAAIAAAAIAAAAgAgthaQgEAIADAKQADAJAFAGQAHAHALgBQAIAAAFgFQADgDABgIIAAgCQgBgJgFgGIAAgCIgFgGIgEgFQgBgCgEAAIgGgBQgLABgFAJgAA5h0QgLAAgGAGQgHAHgBAJQgBALAHAEQAIAFAJgDQAKgCABgJQABgHAAgHIAAgFQgBgEgDgEQgDgDgBAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAABgAg8hkIgBgEIAAgDQABgIAJgFIABgBIAHgCIAAAAIABAAQAEAAADADIABABIgBgBQgDgDgEAAIgBAAIAAAAIgHACIgBABQgJAFgBAIIAAADIABAEgAASiHQAEgHAIAAIAAAAIAAAAIACAAIAAAAIABAAIABABQAGABACAEQgCgEgGgBIgBgBIgBAAIAAAAIgCAAIAAAAIAAAAQgIAAgEAHgAgsgJIAAAAg");
	this.shape_5.setTransform(36.5,37.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FEFF97").s().p("AhTBEIgEgKQgBAIAAAJQgBgFgFgDIgBgBQgFgEgHAAQgHABgFAFQgFAGgBAIQgGgDgDgLIgFgSQgDgJABgKIAAgJIAAgIIgBgHQgCgJABgKQABgKAFgIQAEgHAIgFIAQgLQAIgGAJgCQAJgCAIACIAUACQAJABAJADQAKAEAGADQAIgFAHgIQAGgGAJgDIARgFIASgGQAJgDAKAAQAJgBAJACQAJACAHAGIAPAMQAHAGAGAHQAEAGADAIIADAKIAEASIAEASQACAJgBAKQgBAJgEAJIgIARIgCACQgFgIgIgGIgIgDQgKgCgCgJIAEgEIgEAEIgDADIgBgBIAFgSQACgKgEgJIgJgPQgFgIgIgGQgIgGgKgCIgSgDIgUAAQgJABgIADQgJACgBAHQgFgKgLACQgJACgIAFIgOAKQgHAHgGAIQgFAGgCAJQgCAJABAKIABASIACATIADAPQgHgHgEgLgAhkAtIAAgGIABgMQABgKAAgKQAAgIAEgJQADgJAIgGQAIgGAIgFIABAAQAHgEAHAAIAAAAIAAAAIACAAIABAAIgBAAIgCAAIAAAAIAAAAQgHAAgHAEIgBAAQgIAFgIAGQgIAGgDAJQgEAJAAAIQAAAKgBAKIgBAMIAAAGgAg+g0IgTACQgJAAgHAHQgHAGgGAHQgGAHgEAJQgDAIAAAIIAAATIAAAHIAAgHIAAgTQAAgIADgIQAEgJAGgHQAGgHAHgGQAHgHAJAAIATgCIACAAIABAAIAAAAIABAAIANACIACAAIAQAFIgQgFIgCAAIgNgCIgBAAIAAAAIgBAAIgCAAIAAAAgAB2AUIAAgEQAAgIgBgHQgCgIgFgJQgEgIgHgGIgOgLIgPgKIgCgBQgGgDgEAAIgBAAIAAAAIgFABIAFgBIAAAAIABAAQAEAAAGADIACABIAPAKIAOALQAHAGAEAIQAFAJACAIQABAHAAAIIAAAEgAB9AMIgBAGIABgGIAAgIIgBgLQgBgJgDgJQgEgIgFgHQgFgHgHgEIgRgIQgJgEgJgCQgKgBgJABIgTAEQgKADgHAGIgNALIANgLQAHgGAKgDIATgEQAJgBAKABQAJACAJAEIARAIQAHAEAFAHQAFAHAEAIQADAJABAJIABALIAAAIg");
	this.shape_6.setTransform(36.4,24.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0000FF").s().p("Aj+D+QhphpAAiVQAAiUBphpQBqhqCUAAQCVAABqBqQBpBpAACUQAACVhpBpQhqBqiVAAQiUAAhqhqgAhJAxQgBAKACAKIACATIABATQAAAKgFAJQgDAGgKAEIgSAGQgJADgJAAIgPADIgRAGQgKADgIAEIFlAcIgJgHQgHgDgGgGIgOgKQgHgFgHgEQgJgEgJgDIgPgFIgSgFIgLgDQgMgBgEgHQgBgIACgHIAAAAQAJAAAIgEIAQgIQAIgDAGgHQAIgGAAgKIAAgEIAAgGQAGgJABgLIABgTIAFgSIAGgQQAEgJAAgJIgBgIIgCgKIADgCIAIgRQADgJABgJQACgJgCgKIgEgTIgFgSIgCgKQgDgIgFgFQgFgIgHgGIgPgMQgHgGgJgCQgJgCgKABQgKAAgIADIgTAHIgRAEQgJADgGAGQgGAIgIAGQgGgEgKgEQgJgDgJAAIgUgDQgIgBgJABQgKADgHAFIgQALQgIAFgEAIQgGAHgBALQAAAJACAKIABAHIAAAJIgBAJQAAAKADAJIAFASQACAKAHADQAAAMACAJQADAIAFAGQAEAIAJAGQADACAGgBQAEAAAFgDQAAAHAEAHIAAAAIABACIgBgCIABACIAAAAQACAIAAAIgAhbgtIABAAQAEADACAFIAAAEQgCgGgFgGgAAAgyIABAAIAAACgABfhIIACACIgEADIACgFgAgShQQAEAAABABIAEAGQgEgEgFgDg");
	this.shape_7.setTransform(36,36);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.MicStill, new cjs.Rectangle(-1,-1,74,74), null);


(lib.micktalk = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.1,1,1).p("ACzAOIllgb");
	this.shape.setTransform(0.5,18.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(0.1,1,1).p("Ah+gZQgHgDgCgLQgDgJgDgJQgCgJAAgKQABgEAAgFQAAgEAAgEQAAgEgBgDQgCgKAAgKQABgKAFgIQAFgHAIgFQAIgGAHgFQAIgGAKgCQAIgCAJACQAJABAKABQAKABAJADQAKAEAGADQAHgFAHgIQAHgGAJgDQAIgCAJgDQAJgCAJgEQAJgDAKAAQAJgBAJACQAJACAHAGQAIAGAHAGQAHAGAGAHQAEAGADAIQACAFABAFQABAJADAJQACAJACAKQACAJgBAKQgBAJgEAJQgEAJgEAIQgBABgBABQAAAFABAFQABAEAAAEQAAAJgEAIQgDAIgDAJQgDAJgBAJQgCAJAAAKQgBAKgFAKQAAADgBADQAAACAAACQAAAJgHAHQgHAGgIAEQgIAEgIAEQgIAEgIAAIAAAAQgDAHABAIQAFAGALACQAFABAGABQAJADAJADQAHACAIADQAJACAJAFQAHADAHAFQAHAFAHAGQAGAFAHAEQAFADAEADAgGiVQAHgFAHgGQAHgGAKgDQAJgCAKgCQAJgBAKABQAJACAJAEQAIADAJAFQAHAEAFAHQAFAHAEAIQADAJABAJQACAKgBAKQAAADgBADAhZggQgBgJABgIQACAFACAFQAEALAIAHQgCgIgBgHQgCgKgBgJQgBgJAAgJQAAgKACgJQABgJAGgHQAFgIAIgHQAGgFAHgFQAIgFAKgCQALgCAFAKQABgGAJgDQAHgDAKgBQAKAAAKAAQAJABAJACQAKACAIAGQAIAGAFAIQAFAIAEAIQAEAJgCAKQgCAJgDAJQgCADgBACQACgBACgDQABgBACgCAAziiQAIgCAKAFQAHAEAIAGQAHAFAHAGQAHAGAEAIQAFAJACAJQACAJgBAKABChAQgBAIgJADQgKACgIgEQgHgFABgKQABgKAHgGQAGgGALgBQACgEAEAGQADAEABADQAAADAAACQAAAIgBAHQgFABgBgEQgEgMALAAAAThvQAFgJAKACQAGACACADAAFgdQAAAJAIAGQAGAEAIAAQAJgBAIgBQAJgCAJgDQAIgEgBgKQAAgIgHgCQgJgDgKAAQgDAAgDAAAgXhLQgDgBgEAAQgKAAgFAJQgEAJADAKQACAJAGAGQAHAGAKAAQAJgBAFgEQADgEAAgHQAAgBAAgBQAAAAAAAAQgCACgCAAQgMAAgBgIQgCgLAOAAACAgpQgFgIgIgGQgEgCgEgBQgKgCgCgJQACgCACgCAgyiUQgJgBgJAFQgJAFgHAGQgIAGgEAJQgDAJAAAJQAAAKgCAKQgBAJABAJAgdiZQgGgDgKgCQgJgCgKAAQgJABgJABQgJAAgIAHQgHAGgFAHQgGAHgEAJQgEAIAAAJQAAAJAAAKQAAAFAAACAhWAWQgEADgFAAQgFABgEgDQgIgFgEgIQgFgHgDgIQgDgIABgMAhggpQgFgEgHAAQgIABgEAFQgFAGgBAIAgXhLQAFACAEAFQgCgDgCgDQgCgCgDABgAgihgQgHgGgKAFQgJAFgBAJQAAADABAEAhZggQgCgFgEgDQAAAAgBgBQAFAHACAGQAAgCAAgCgAgEgtQAAgJgFgHQAAAAAAgBAgOhEQACADADADAgsAOQgCACgBAEQAAADABADAgsAOQAEAGAHAFQAHAGAIAFQAIAFAJACQAJACAJAAQAKAAAKAAQAJAAAIgFQAJgFAIgDQAJgEAHgFQAIgGAFgGAgkAIQgFACgDAEAhWAWQADgDADgDQAEgHgBgJAhRAkQABABAAABQAEAIAEAJQAEAJAEAIQAEAHAGAHQAHAHAIAGQAHAGAJADQAJADAJADQAJACAKgBQAKAAAKAAQAIAAAJABQABAAABAAAhRAkQAAAAAAAAQgEgHgBgHAiyCmQAIgFAKgDQAIgDAJgCQAHgCAHgBQAJgBAKgDQAJgDAJgDQAJgDAEgHQAFgIgBgKQAAgKgBgKQAAgJgCgJQgBgKABgKQAAgIgCgIQAAgBgBgBAAzCDQAAACAAABQABAKAFAJ");
	this.shape_1.setTransform(0.5,0.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgrAKQgCgKANAAIABAAQAEAHABAJIgBAAIgEACIgBAAQgKAAgBgIgAAlgFQgEgMALAAQABAIgCAHIgCAAQgDAAgBgDg");
	this.shape_2.setTransform(2.8,-5.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgvAcQgGgGgCgJQgDgKAEgIQAFgJAKAAIAGABQAFACAFAFIAEAGQgNAAACAKQABAIAMAAIADgCIABACQAAAHgDAEQgFAEgJABIgBAAQgKAAgGgGgAAdAGQgHgFABgJQABgKAGgGQAHgGAKgBQACgEAFAGQADAEAAADIAAAFQgLAAAEAMQABAEAGgBQgCAHgJADIgGAAQgGAAgFgCg");
	this.shape_3.setTransform(1.4,-5.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFCC97").s().p("AiyCOQAIgEAKgDIARgFIAPgDQAJgBAJgDIASgGQAKgDADgHQAFgJAAgKIgBgTIgDgTQAAgJAAgKQAAgJgCgIIAAAAIAIASIAJAQQAEAIAFAGIAPANQAIAGAIAEIASAFIACAAIAMACIABAAIAAAAIADAAIABAAIAUAAIARAAIACAAIAAAAQgDAHABAIQAFAHAKABIAMADIASAFIAPAFQAJADAIAEQAIAEAHAFIAOAKQAGAGAHAEIAJAGgAAzBvQABAKAEAIQgEgIgBgKIAAgEIAAAEgAAzBcIgRAAIgUAAIgBAAIgDAAIAAAAIgBAAIgMgCIgCAAIgSgFQgIgEgIgGIgPgNQgFgGgEgIIgJgQIgIgSIgBgBIAAgBQgEgHgBgGIAGgGQADgFAAgGIAAgEIAAAEQAAAGgDAFIgGAGQgEACgFABQgEAAgFgCQgHgFgFgHQgFgHgDgJQgDgJABgLQABgIAFgGQAEgGAIAAQAHgBAFAFQAFAGACAHIAAgFQgBgIABgIIAFAKQAEALAHAGIgDgPIgDgSIgBgSQAAgKACgKQABgIAGgIQAFgHAIgHIANgLQAJgFAJgCQALgCAFAKQABgGAJgDQAIgCAJgBIATAAIATADQAJACAJAGQAIAFAFAIIAJARQAEAIgCAKIgGASIgCAGIAEgEIADgEQACAKAKABIAIAEQAHAFAFAIIACAKQABAEgBAEQAAAJgDAJIgHARIgDARIgCATQgCALgEAJIgBAGIAAAEQAAAKgIAGQgGAHgIADIgQAIQgIAEgIAAIgBAAIgBAAgAghACIAPAKQAIAFAKACQAIACAJABIATgBQAKAAAIgEIARgJQAJgDAHgFQAIgFAFgHQgFAHgIAFQgHAFgJADIgRAJQgIAEgKAAIgTABQgJgBgIgCQgKgCgIgFIgPgKQgHgFgEgGQADgEAFgBQgFABgDAEQgCACAAAEIgBACIABADIgBgDIABgCQAAgEACgCQAEAGAHAFgAAZgiIABAAIASgCIASgFQAHgDAAgJIAAgCQgBgHgGgDIgCAAQgGgCgIAAIAAAAIAAAAIgCAAIgBAAIgGAAIAGAAIABAAIACAAIAAAAIAAAAQAIAAAGACIACAAQAGADABAHIAAACQAAAJgHADIgSAFIgSACIgBAAIAAAAIgBAAQgGAAgGgEQgHgFAAgKQAAAKAHAFQAGAEAGAAIABAAIAAAAgAgthaQgDAIACAKQADAJAGAGQAGAHALgBQAIAAAFgFQAEgDAAgIIAAgCQgBgJgFgGIAAgCIgFgGIgEgFQgCgCgDAAIgGgBQgLABgFAJgAA4h0QgKAAgHAGQgGAHgBAJQgBALAHAEQAIAFAJgDQAKgCABgJQABgHAAgHIgBgFQAAgEgDgEQgDgDgBAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAAAgBABgAg8hkIgBgEIAAgDQABgIAJgFIABgBIAHgCIAAAAIABAAQAEAAAEAEQgEgEgEAAIgBAAIAAAAIgHACIgBABQgJAFgBAIIAAADIABAEgAASiHIABAAIABgCQAEgFAGAAIAAAAIAAAAIABAAIAAAAIADABQAGABACAEQgCgEgGgBIgDgBIAAAAIgBAAIAAAAIAAAAQgGAAgEAFIgBACIgBAAg");
	this.shape_4.setTransform(0.5,2.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FEFF97").s().p("AhTBEIgEgKQgBAIAAAJQgBgFgFgDIgBgBQgFgEgHAAQgHABgFAFQgFAGgBAIQgGgDgDgLIgFgSQgDgJABgKIAAgJIAAgIIgBgHQgCgJABgKQABgKAFgIQAEgHAIgFIAQgLQAIgGAJgCQAJgCAIACIAUACQAJABAJADQAKAEAGADQAIgFAHgIQAGgGAJgDIARgFIASgGQAJgDAKAAQAJgBAJACQAJACAHAGIAPAMQAHAGAGAHQAEAGADAIIADAKIAEASIAEASQACAJgBAKQgBAJgEAJIgIARIgCACQgFgIgIgGIgIgDQgKgCgCgJIAEgEIgEAEIgDADIgBgBIAFgSQACgKgEgJIgJgPQgFgIgIgGQgIgGgKgCIgSgDIgUAAQgJABgIADQgJACgBAHQgFgKgLACQgJACgIAFIgOAKQgHAHgGAIQgFAGgCAJQgCAJABAKIABASIACATIADAPQgHgHgEgLgAhkAtIAAgGIABgMQABgKAAgKQAAgIAEgJQADgJAIgGQAIgGAIgFQAHgEAIAAIAAAAIAAAAIACAAIABAAIgBAAIgCAAIAAAAIAAAAQgIAAgHAEQgIAFgIAGQgIAGgDAJQgEAJAAAIQAAAKgBAKIgBAMIAAAGgAg+g0IgTACQgJAAgHAHQgHAGgGAHQgGAHgEAJQgDAIAAAIIAAATIAAAHIAAgHIAAgTQAAgIADgIQAEgJAGgHQAGgHAHgGQAHgHAJAAIATgCIACAAIABAAIAAAAIACAAQAGAAAHACIABAAIAQAFIgQgFIgBAAQgHgCgGAAIgCAAIAAAAIgBAAIgCAAIAAAAgAB2AUIAAgEQAAgIgBgHQgCgIgFgJQgEgIgHgGIgOgLIgPgKQgHgEgGAAIgBAAIgEABIAEgBIABAAQAGAAAHAEIAPAKIAOALQAHAGAEAIQAFAJACAIQABAHAAAIIAAAEgAB9AMIgBAGIABgGIAAgIIgBgLQgBgJgDgJQgEgIgFgHQgFgHgHgEIgRgIQgJgEgJgCQgKgBgJABIgTAEQgKADgHAGIgNALIANgLQAHgGAKgDIATgEQAJgBAKABQAJACAJAEIARAIQAHAEAFAHQAFAHAEAIQADAJABAJIABALIAAAIg");
	this.shape_5.setTransform(0.4,-10.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(0.1,1,1).p("AgGiVQAHgFAHgGQAHgGAKgDQAJgCAKgCQAJgBAKABQAJACAJAEQAIADAJAFQAHAEAFAHQAFAHAEAIQADAJABAJQACAKgBAKQAAADgBADAh+gZQgHgDgCgLQgDgJgDgJQgCgJAAgKQABgEAAgFQAAgEAAgEQAAgEgBgDQgCgKAAgKQABgKAFgIQAFgHAIgFQAIgGAHgFQAIgGAKgCQAIgCAJACQAJABAKABQAKABAJADQAKAEAGADQAHgFAHgIQAHgGAJgDQAIgCAJgDQAJgCAJgEQAJgDAKAAQAJgBAJACQAJACAHAGQAIAGAHAGQAHAGAGAHQAEAGADAIQACAFABAFQABAJADAJQACAJACAKQACAJgBAKQgBAJgEAJQgEAJgEAIQgBABgBABQAAAFABAFQABAEAAAEQAAAJgEAIQgDAIgDAJQgDAJgBAJQgCAJAAAKQgBAKgFAKQAAADgBADQAAACAAACQAAAJgHAHQgHAGgIAEQgIAEgIAEQgIAEgIAAQgBAAgBAAQgJgBgIAAQgKAAgKAAQgKABgJgCQgJgDgJgDQgJgDgHgGQgIgGgHgHQgGgHgEgHQgEgIgEgJQgEgJgEgIQAAgBgBgBQAAAAAAAAQgEgHgBgHQgEADgFAAQgFABgEgDQgIgFgEgIQgFgHgDgIQgDgIABgMgAhZggQgBgJABgIQACAFACAFQAEALAIAHQgCgIgBgHQgCgKgBgJQgBgJAAgJQAAgKACgJQABgJAGgHQAFgIAIgHQAGgFAHgFQAIgFAKgCQALgCAFAKQABgGAJgDQAHgDAKgBQAKAAAKAAQAJABAJACQAKACAIAGQAIAGAFAIQAFAIAEAIQAEAJgCAKQgCAJgDAJQgCADgBACQACgBACgDQABgBACgCAAziiQAIgCAKAFQAHAEAIAGQAHAFAHAGQAHAGAEAIQAFAJACAJQACAJgBAKABChAQgBAIgJADQgKACgIgEQgHgFABgKQABgKAHgGQAGgGALgBQACgEAEAGQADAEABADQAAADAAACQAAAIgBAHQgFABgBgEQgEgMALAAAAThvQAFgJAKACQAGACACADAgXhLQgDgBgEAAQgKAAgFAJQgEAJADAKQACAJAGAGQAHAGAKAAQAJgBAFgEQADgEAAgHQAAgBAAgBQAAAAAAAAQgCACgCAAQgMAAgBgIQgCgLAOAAAAFgdQAAAJAIAGQAGAEAIAAQAJgBAIgBQAJgCAJgDQAIgEgBgKQAAgIgHgCQgJgDgKAAQgDAAgDAAACAgpQgFgIgIgGQgEgCgEgBQgKgCgCgJQACgCACgCAgdiZQgGgDgKgCQgJgCgKAAQgJABgJABQgJAAgIAHQgHAGgFAHQgGAHgEAJQgEAIAAAJQAAAJAAAKQAAAFAAACAgyiUQgJgBgJAFQgJAFgHAGQgIAGgEAJQgDAJAAAJQAAAKgCAKQgBAJABAJAhggpQgFgEgHAAQgIABgEAFQgFAGgBAIAgihgQgHgGgKAFQgJAFgBAJQAAADABAEAgXhLQAFACAEAFQgCgDgCgDQgCgCgDABgAhZggQgCgFgEgDQAAAAgBgBQAFAHACAGQAAgCAAgCgAgEgtQAAgJgFgHQAAAAAAgBQgDgDgCgDAhWAWQADgDADgDQAEgHgBgJAAzCDQAFAGALACQAFABAGABQAJADAJADQAHACAIADQAJACAJAFQAHADAHAFQAHAFAHAGQAGAFAHAEQAFADAEADIllgbQAIgFAKgDQAIgDAJgCQAHgCAHgBQAJgBAKgDQAJgDAJgDQAJgDAEgHQAFgIgBgKQAAgKgBgKQAAgJgCgJQgBgKABgKQAAgIgCgIQAAgBgBgBAAIA3QAJAKAVgCQAlgDAAgeQgbgLgeAJQgaAIAQATgAA1B0IAAAAQgDAHABAIQAAACAAABQABAKAFAJ");
	this.shape_6.setTransform(0.5,0.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgFBHQgRgTAagIQAfgJAaALQABAegmADIgGABQgQAAgHgJgAgzgRQgGgGgDgJQgCgKAEgJQAEgJALAAIAGABQAFACAFAFIAEAGQgNAAACALQABAIALAAIAEgCIABACQAAAHgEAEQgFAEgIABIgBAAQgKAAgGgGgAAYgnQgHgFABgKQABgKAHgGQAGgGALgBQACgEAEAGQADAEABADIAAAFQgLAAAEAMQABAEAFgBQgBAIgJADIgHABQgFAAgGgDg");
	this.shape_7.setTransform(1.9,-1.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFCC97").s().p("AiyCOQAIgEAKgDIARgFIAPgDQAJgBAJgDIASgGQAKgDADgHQAFgJAAgKIgBgTIgDgTQAAgJAAgKQAAgJgCgIIAAAAIgBgBIAAgBQgEgHgBgGIAGgGQADgFAAgGIAAgEIAAAEQAAAGgDAFIgGAGQgEACgFABQgEAAgFgCQgHgFgFgHQgFgHgDgJQgDgJABgLQABgIAFgGQAEgGAIAAQAHgBAFAFQAFAGACAHIAAgFQgBgIABgIIAFAKQAEALAHAGIgDgPIgDgSIgBgSQAAgKACgKQABgIAGgIQAFgHAIgHIANgLQAJgFAJgCQALgCAFAKQABgGAJgDQAIgCAJgBIATAAIATADQAJACAJAGQAIAFAFAIIAJARQAEAIgCAKIgGASIgCAGIAEgEIADgEQACAKAKABIAIAEQAHAFAFAIIACAKQABAEgBAEQAAAJgDAJIgHARIgDARIgCATQgCALgEAJIgBAGIAAAEQAAAKgIAGQgGAHgIADIgQAIQgIAEgIAAIgBAAIgBAAIgRAAIgUAAIgBAAIgDAAIAAAAIgBAAIgMgCIgCAAIgSgFQgIgEgIgGIgPgNQgFgGgEgIIgJgQIgIgSIAIASIAJAQQAEAIAFAGIAPANQAIAGAIAEIASAFIACAAIAMACIABAAIAAAAIADAAIABAAIAUAAIARAAIABAAIABAAIAAAAQgDAHABAIQAFAHAKABIAMADIASAFIAPAFQAJADAIAEQAIAEAHAFIAOAKQAGAGAHAEIAJAGgAAzBvQABAKAEAIQgEgIgBgKIAAgEIAAAEgAASAFQgaAIAQATQAIAKAWgCQAlgEAAgdQgPgHgQAAQgNAAgNAFgAAZgiIABAAIASgCIASgFQAHgDAAgJIAAgCQgBgHgGgDIgCAAQgGgCgIAAIAAAAIAAAAIgCAAIgBAAIgGAAIAGAAIABAAIACAAIAAAAIAAAAQAIAAAGACIACAAQAGADABAHIAAACQAAAJgHADIgSAFIgSACIgBAAIAAAAIgBAAQgGAAgGgEQgHgFAAgKQAAAKAHAFQAGAEAGAAIABAAIAAAAgAgthaQgDAIACAKQADAJAGAGQAGAHALgBQAIAAAFgFQAEgDAAgIIAAgCQgBgJgFgGIAAgCIgFgGIgEgFQgCgCgDAAIgGgBQgLABgFAJgAA4h0QgKAAgHAGQgGAHgBAJQgBALAHAEQAIAFAJgDQAKgCABgJQABgHAAgHIgBgFQAAgEgDgEQgDgDgBAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAAAgBABgAg8hkIgBgEIAAgDQABgIAJgFIABgBIAHgCIAAAAIABAAQAEAAAEAEQgEgEgEAAIgBAAIAAAAIgHACIgBABQgJAFgBAIIAAADIABAEgAASiHIABAAIABgCQAEgFAGAAIAAAAIAAAAIABAAIAAAAIADABQAGABACAEQgCgEgGgBIgDgBIAAAAIgBAAIAAAAIAAAAQgGAAgEAFIgBACIgBAAg");
	this.shape_8.setTransform(0.5,2.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#000000").ss(0.1,1,1).p("AgGiVQAHgFAHgGQAHgGAKgDQAJgCAKgCQAJgBAKABQAJACAJAEQAIADAJAFQAHAEAFAHQAFAHAEAIQADAJABAJQACAKgBAKQAAADgBADAh+gZQgHgDgCgLQgDgJgDgJQgCgJAAgKQABgEAAgFQAAgEAAgEQAAgEgBgDQgCgKAAgKQABgKAFgIQAFgHAIgFQAIgGAHgFQAIgGAKgCQAIgCAJACQAJABAKABQAKABAJADQAKAEAGADQAHgFAHgIQAHgGAJgDQAIgCAJgDQAJgCAJgEQAJgDAKAAQAJgBAJACQAJACAHAGQAIAGAHAGQAHAGAGAHQAEAGADAIQACAFABAFQABAJADAJQACAJACAKQACAJgBAKQgBAJgEAJQgEAJgEAIQgBABgBABQAAAFABAFQABAEAAAEQAAAJgEAIQgDAIgDAJQgDAJgBAJQgCAJAAAKQgBAKgFAKQAAADgBADQAAACAAACQAAAJgHAHQgHAGgIAEQgIAEgIAEQgIAEgIAAQgBAAgBAAQgJgBgIAAQgKAAgKAAQgKABgJgCQgJgDgJgDQgJgDgHgGQgIgGgHgHQgGgHgEgHQgEgIgEgJQgEgJgEgIQAAgBgBgBQAAAAAAAAQgEgHgBgHQgEADgFAAQgFABgEgDQgIgFgEgIQgFgHgDgIQgDgIABgMgAhZggQgBgJABgIQACAFACAFQAEALAIAHQgCgIgBgHQgCgKgBgJQgBgJAAgJQAAgKACgJQABgJAGgHQAFgIAIgHQAGgFAHgFQAIgFAKgCQALgCAFAKQABgGAJgDQAHgDAKgBQAKAAAKAAQAJABAJACQAKACAIAGQAIAGAFAIQAFAIAEAIQAEAJgCAKQgCAJgDAJQgCADgBACQACgBACgDQABgBACgCAAziiQAIgCAKAFQAHAEAIAGQAHAFAHAGQAHAGAEAIQAFAJACAJQACAJgBAKABChAQgBAIgJADQgKACgIgEQgHgFABgKQABgKAHgGQAGgGALgBQACgEAEAGQADAEABADQAAADAAACQAAAIgBAHQgFABgBgEQgEgMALAAAAThvQAFgJAKACQAGACACADAgXhLQgDgBgEAAQgKAAgFAJQgEAJADAKQACAJAGAGQAHAGAKAAQAJgBAFgEQADgEAAgHQAAgBAAgBQAAAAAAAAQgCACgCAAQgMAAgBgIQgCgLAOAAAAFgdQAAAJAIAGQAGAEAIAAQAJgBAIgBQAJgCAJgDQAIgEgBgKQAAgIgHgCQgJgDgKAAQgDAAgDAAACAgpQgFgIgIgGQgEgCgEgBQgKgCgCgJQACgCACgCAgyiUQgJgBgJAFQgJAFgHAGQgIAGgEAJQgDAJAAAJQAAAKgCAKQgBAJABAJAgdiZQgGgDgKgCQgJgCgKAAQgJABgJABQgJAAgIAHQgHAGgFAHQgGAHgEAJQgEAIAAAJQAAAJAAAKQAAAFAAACAhggpQgFgEgHAAQgIABgEAFQgFAGgBAIAgihgQgHgGgKAFQgJAFgBAJQAAADABAEAgXhLQAFACAEAFQgCgDgCgDQgCgCgDABgAhZggQgCgFgEgDQAAAAgBgBQAFAHACAGQAAgCAAgCgAgEgtQAAgJgFgHQAAAAAAgBAgOhEQACADADADAhWAWQADgDADgDQAEgHgBgJAAzCDQAFAGALACQAFABAGABQAJADAJADQAHACAIADQAJACAJAFQAHADAHAFQAHAFAHAGQAGAFAHAEQAFADAEADIllgbQAIgFAKgDQAIgDAJgCQAHgCAHgBQAJgBAKgDQAJgDAJgDQAJgDAEgHQAFgIgBgKQAAgKgBgKQAAgJgCgJQgBgKABgKQAAgIgCgIQAAgBgBgBAAXAxQADAMARgBQAQgBgIgQQgJgRgLAGQgLAFADAMgAA1B0IAAAAQgDAHABAIQAAACAAABQABAKAFAJ");
	this.shape_9.setTransform(0.5,0.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAOBDQgEgMALgGQALgFAJAQQAJARgRABIgCAAQgOAAgDgLgAgvgQQgGgGgCgJQgDgKAEgIQAFgJAKgBIAGACQAFACAFAEIAEAHQgNgBACAMQABAIAMgBIADgBIABABQAAAIgDADQgFAFgJAAIgBAAQgKAAgGgGgAAdgmQgHgEABgLQABgJAGgHQAHgGAKAAQACgEAFAFQADAEAAAEIAAAFQgLgBAEANQABADAGgBQgCAJgJACIgGABQgGAAgFgDg");
	this.shape_10.setTransform(1.4,-1.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFCC97").s().p("AiyCOQAIgEAKgDIARgFIAPgDQAJgBAJgDIASgGQAKgDADgHQAFgJAAgKIgBgTIgDgTQAAgJAAgKQAAgJgCgIIAAAAIgBgBIAAgBQgEgHgBgGIAGgGQADgFAAgGIAAgEIAAAEQAAAGgDAFIgGAGQgEACgFABQgEAAgFgCQgHgFgFgHQgFgHgDgJQgDgJABgLQABgIAFgGQAEgGAIAAQAHgBAFAFQAFAGACAHIAAgFQgBgIABgIIAFAKQAEALAHAGIgDgPIgDgSIgBgSQAAgKACgKQABgIAGgIQAFgHAIgHIANgLQAJgFAJgCQALgCAFAKQABgGAJgDQAIgCAJgBIATAAIATADQAJACAJAGQAIAFAFAIIAJARQAEAIgCAKIgGASIgCAGIAEgEIADgEQACAKAKABIAIAEQAHAFAFAIIACAKQABAEgBAEQAAAJgDAJIgHARIgDARIgCATQgCALgEAJIgBAGIAAAEQAAAKgIAGQgGAHgIADIgQAIQgIAEgIAAIgBAAIgBAAIgRAAIgUAAIgBAAIgDAAIAAAAIgBAAIgMgCIgCAAIgSgFQgIgEgIgGIgPgNQgFgGgEgIIgJgQIgIgSIAIASIAJAQQAEAIAFAGIAPANQAIAGAIAEIASAFIACAAIAMACIABAAIAAAAIADAAIABAAIAUAAIARAAIABAAIABAAIAAAAQgDAHABAIQAFAHAKABIAMADIASAFIAPAFQAJADAIAEQAIAEAHAFIAOAKQAGAGAHAEIAJAGgAAzBvQABAKAEAIQgEgIgBgKIAAgEIAAAEgAAfAIQgLAGADAMQADALARAAQAQgBgIgRQgHgMgIAAIgFABgAAZgiIABAAIASgCIASgFQAHgDAAgJIAAgCQgBgHgGgDIgCAAQgGgCgIAAIAAAAIAAAAIgCAAIgBAAIgGAAIAGAAIABAAIACAAIAAAAIAAAAQAIAAAGACIACAAQAGADABAHIAAACQAAAJgHADIgSAFIgSACIgBAAIAAAAIgBAAQgGAAgGgEQgHgFAAgKQAAAKAHAFQAGAEAGAAIABAAIAAAAgAgthaQgDAIACAKQADAJAGAGQAGAHALgBQAIAAAFgFQAEgDAAgIIAAgCQgBgJgFgGIAAgCIgFgGIgEgFQgCgCgDAAIgGgBQgLABgFAJgAA4h0QgKAAgHAGQgGAHgBAJQgBALAHAEQAIAFAJgDQAKgCABgJQABgHAAgHIgBgFQAAgEgDgEQgDgDgBAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAAAgBABgAg8hkIgBgEIAAgDQABgIAJgFIABgBIAHgCIAAAAIABAAQAEAAAEAEQgEgEgEAAIgBAAIAAAAIgHACIgBABQgJAFgBAIIAAADIABAEgAASiHIABAAIABgCQAEgFAGAAIAAAAIAAAAIABAAIAAAAIADABQAGABACAEQgCgEgGgBIgDgBIAAAAIgBAAIAAAAIAAAAQgGAAgEAFIgBACIgBAAg");
	this.shape_11.setTransform(0.5,2.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#000000").ss(0.1,1,1).p("Ah+gZQgHgDgCgLQgDgJgDgJQgCgJAAgKQABgEAAgFQAAgEAAgEQAAgEgBgDQgCgKAAgKQABgKAFgIQAFgHAIgFQAIgGAHgFQAIgGAKgCQAIgCAJACQAJABAKABQAKABAJADQAKAEAGADQAHgFAHgIQAHgGAJgDQAIgCAJgDQAJgCAJgEQAJgDAKAAQAJgBAJACQAJACAHAGQAIAGAHAGQAHAGAGAHQAEAGADAIQACAFABAFQABAJADAJQACAJACAKQACAJgBAKQgBAJgEAJQgEAJgEAIQgBABgBABQAAAFABAFQABAEAAAEQAAAJgEAIQgDAIgDAJQgDAJgBAJQgCAJAAAKQgBAKgFAKQAAADgBADQAAACAAACQAAAJgHAHQgHAGgIAEQgIAEgIAEQgIAEgIAAQgBAAgBAAQgJgBgIAAQgKAAgKAAQgKABgJgCQgJgDgJgDQgJgDgHgGQgIgGgHgHQgGgHgEgHQgEgIgEgJQgEgJgEgIQAAgBgBgBQAAAAAAAAQgEgHgBgHQgEADgFAAQgFABgEgDQgIgFgEgIQgFgHgDgIQgDgIABgMgAgGiVQAHgFAHgGQAHgGAKgDQAJgCAKgCQAJgBAKABQAJACAJAEQAIADAJAFQAHAEAFAHQAFAHAEAIQADAJABAJQACAKgBAKQAAADgBADAhZggQgBgJABgIQACAFACAFQAEALAIAHQgCgIgBgHQgCgKgBgJQgBgJAAgJQAAgKACgJQABgJAGgHQAFgIAIgHQAGgFAHgFQAIgFAKgCQALgCAFAKQABgGAJgDQAHgDAKgBQAKAAAKAAQAJABAJACQAKACAIAGQAIAGAFAIQAFAIAEAIQAEAJgCAKQgCAJgDAJQgCADgBACQACgBACgDQABgBACgCAAziiQAIgCAKAFQAHAEAIAGQAHAFAHAGQAHAGAEAIQAFAJACAJQACAJgBAKABChAQgBAIgJADQgKACgIgEQgHgFABgKQABgKAHgGQAGgGALgBQACgEAEAGQADAEABADQAAADAAACQAAAIgBAHQgFABgBgEQgEgMALAAAAThvQAFgJAKACQAGACACADAAFgdQAAAJAIAGQAGAEAIAAQAJgBAIgBQAJgCAJgDQAIgEgBgKQAAgIgHgCQgJgDgKAAQgDAAgDAAAgXhLQgDgBgEAAQgKAAgFAJQgEAJADAKQACAJAGAGQAHAGAKAAQAJgBAFgEQADgEAAgHQAAgBAAgBQAAAAAAAAQgCACgCAAQgMAAgBgIQgCgLAOAAACAgpQgFgIgIgGQgEgCgEgBQgKgCgCgJQACgCACgCAgdiZQgGgDgKgCQgJgCgKAAQgJABgJABQgJAAgIAHQgHAGgFAHQgGAHgEAJQgEAIAAAJQAAAJAAAKQAAAFAAACAgyiUQgJgBgJAFQgJAFgHAGQgIAGgEAJQgDAJAAAJQAAAKgCAKQgBAJABAJAhggpQgFgEgHAAQgIABgEAFQgFAGgBAIAgihgQgHgGgKAFQgJAFgBAJQAAADABAEAgOhEQgCgDgCgDQgCgCgDABQAFACAEAFgAhZggQgCgFgEgDQAAAAgBgBQAFAHACAGQAAgCAAgCgAgEgtQAAgJgFgHQAAAAAAgBQgDgDgCgDAhWAWQADgDADgDQAEgHgBgJAAzCDQAFAGALACQAFABAGABQAJADAJADQAHACAIADQAJACAJAFQAHADAHAFQAHAFAHAGQAGAFAHAEQAFADAEADIllgbQAIgFAKgDQAIgDAJgCQAHgCAHgBQAJgBAKgDQAJgDAJgDQAJgDAEgHQAFgIgBgKQAAgKgBgKQAAgJgCgJQgBgKABgKQAAgIgCgIQAAgBgBgBABTA1QgIAKgVADQgOABgRAEQgsAKACg2QAiAFAkAGQAVAEALALgAA1B0IAAAAQgDAHABAIQAAACAAABQABAKAFAJ");
	this.shape_12.setTransform(0.5,0.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AglAmIBGAMQAVAEALAKQgIALgVACQgOACgRAEIgLABQggAAABgugAg3gWQgGgGgDgJQgCgKAEgIQAEgJALgBIAGABQAFADAFAEIAEAGQgNAAACAMQABAIALgBIAEgBIABABQAAAIgEADQgFAFgIAAIgBAAQgKAAgGgGgAAUgsQgHgEABgLQABgJAHgHQAGgGALAAQACgEAEAFQADAEABAEIAAAFQgLgBAEANQABADAFgBQgBAJgJACIgHABQgFAAgGgDg");
	this.shape_13.setTransform(2.3,-0.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFCC97").s().p("AiyCOQAIgEAKgDIARgFIAPgDQAJgBAJgDIASgGQAKgDADgHQAFgJAAgKIgBgTIgDgTQAAgJAAgKQAAgJgCgIIAAAAIgBgBIAAgBQgEgHgBgGIAGgGQADgFAAgGIAAgEIAAAEQAAAGgDAFIgGAGQgEACgFABQgEAAgFgCQgHgFgFgHQgFgHgDgJQgDgJABgLQABgIAFgGQAEgGAIAAQAHgBAFAFQAFAGACAHIAAgFQgBgIABgIIAFAKQAEALAHAGIgDgPIgDgSIgBgSQAAgKACgKQABgIAGgIQAFgHAIgHIANgLQAJgFAJgCQALgCAFAKQABgGAJgDQAIgCAJgBIATAAIATADQAJACAJAGQAIAFAFAIIAJARQAEAIgCAKIgGASIgCAGIAEgEIADgEQACAKAKABIAIAEQAHAFAFAIIACAKQABAEgBAEQAAAJgDAJIgHARIgDARIgCATQgCALgEAJIgBAGIAAAEQAAAKgIAGQgGAHgIADIgQAIQgIAEgIAAIgBAAIgBAAIgRAAIgUAAIgBAAIgDAAIAAAAIgBAAIgMgCIgCAAIgSgFQgIgEgIgGIgPgNQgFgGgEgIIgJgQIgIgSIAIASIAJAQQAEAIAFAGIAPANQAIAGAIAEIASAFIACAAIAMACIABAAIAAAAIADAAIABAAIAUAAIARAAIABAAIABAAIAAAAQgDAHABAIQAFAHAKABIAMADIASAFIAPAFQAJADAIAEQAIAEAHAFIAOAKQAGAGAHAEIAJAGgAAzBvQABAKAEAIQgEgIgBgKIAAgEIAAAEgAAXAwQAQgEAOgCQAWgCAIgLQgLgKgVgEIhGgMQgBA3ArgKgAAZgiIABAAIASgCIASgFQAHgDAAgJIAAgCQgBgHgGgDIgCAAQgGgCgIAAIAAAAIAAAAIgCAAIgBAAIgGAAIAGAAIABAAIACAAIAAAAIAAAAQAIAAAGACIACAAQAGADABAHIAAACQAAAJgHADIgSAFIgSACIgBAAIAAAAIgBAAQgGAAgGgEQgHgFAAgKQAAAKAHAFQAGAEAGAAIABAAIAAAAgAgthaQgDAIACAKQADAJAGAGQAGAHALgBQAIAAAFgFQAEgDAAgIIAAgCQgBgJgFgGIAAgCIgFgGIgEgFQgCgCgDAAIgGgBQgLABgFAJgAA4h0QgKAAgHAGQgGAHgBAJQgBALAHAEQAIAFAJgDQAKgCABgJQABgHAAgHIgBgFQAAgEgDgEQgDgDgBAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAAAgBABgAg8hkIgBgEIAAgDQABgIAJgFIABgBIAHgCIAAAAIABAAQAEAAAEAEQgEgEgEAAIgBAAIAAAAIgHACIgBABQgJAFgBAIIAAADIABAEgAASiHIABAAIABgCQAEgFAGAAIAAAAIAAAAIABAAIAAAAIADABQAGABACAEQgCgEgGgBIgDgBIAAAAIgBAAIAAAAIAAAAQgGAAgEAFIgBACIgBAAg");
	this.shape_14.setTransform(0.5,2.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#000000").ss(0.1,1,1).p("AgGiVQAHgFAHgGQAHgGAKgDQAJgCAKgCQAJgBAKABQAJACAJAEQAIADAJAFQAHAEAFAHQAFAHAEAIQADAJABAJQACAKgBAKQAAADgBADAh+gZQgHgDgCgLQgDgJgDgJQgCgJAAgKQABgEAAgFQAAgEAAgEQAAgEgBgDQgCgKAAgKQABgKAFgIQAFgHAIgFQAIgGAHgFQAIgGAKgCQAIgCAJACQAJABAKABQAKABAJADQAKAEAGADQAHgFAHgIQAHgGAJgDQAIgCAJgDQAJgCAJgEQAJgDAKAAQAJgBAJACQAJACAHAGQAIAGAHAGQAHAGAGAHQAEAGADAIQACAFABAFQABAJADAJQACAJACAKQACAJgBAKQgBAJgEAJQgEAJgEAIQgBABgBABQgFgIgIgGQgEgCgEgBQgKgCgCgJQACgCACgCAhZggQgBgJABgIQACAFACAFQAEALAIAHQgCgIgBgHQgCgKgBgJQgBgJAAgJQAAgKACgJQABgJAGgHQAFgIAIgHQAGgFAHgFQAIgFAKgCQALgCAFAKQABgGAJgDQAHgDAKgBQAKAAAKAAQAJABAJACQAKACAIAGQAIAGAFAIQAFAIAEAIQAEAJgCAKQgCAJgDAJQgCADgBACQACgBACgDQABgBACgCAAziiQAIgCAKAFQAHAEAIAGQAHAFAHAGQAHAGAEAIQAFAJACAJQACAJgBAKABChAQgBAIgJADQgKACgIgEQgHgFABgKQABgKAHgGQAGgGALgBQACgEAEAGQADAEABADQAAADAAACQAAAIgBAHQgFABgBgEQgEgMALAAAAThvQAFgJAKACQAGACACADAgXhLQgDgBgEAAQgKAAgFAJQgEAJADAKQACAJAGAGQAHAGAKAAQAJgBAFgEQADgEAAgHQAAgBAAgBQAAgJgFgHQAAAAAAgBAAFgdQAAAJAIAGQAGAEAIAAQAJgBAIgBQAJgCAJgDQAIgEgBgKQAAgIgHgCQgJgDgKAAQgDAAgDAAACAgpQAAAFABAFQABAEAAAEQAAAJgEAIQgDAIgDAJQgDAJgBAJQgCAJAAAKQgBAKgFAKQAAADgBADQAAACAAACQAAAJgHAHQgHAGgIAEQgIAEgIAEQgIAEgIAAQgBAAgBAAQgJgBgIAAQgKAAgKAAQgKABgJgCQgJgDgJgDQgJgDgHgGQgIgGgHgHQgGgHgEgHQgEgIgEgJQgEgJgEgIQAAgBgBgBQAAAAAAAAQgEgHgBgHQgEADgFAAQgFABgEgDQgIgFgEgIQgFgHgDgIQgDgIABgMAgsAOQAEAGAHAFQAHAGAIAFQAIAFAJACQAJACAJAAQAKAAAKAAQAJAAAIgFQAJgFAIgDQAJgEAHgFQAIgGAFgGAA1B0IAAAAQgDAHABAIQAFAGALACQAFABAGABQAJADAJADQAHACAIADQAJACAJAFQAHADAHAFQAHAFAHAGQAGAFAHAEQAFADAEADIllgbQAIgFAKgDQAIgDAJgCQAHgCAHgBQAJgBAKgDQAJgDAJgDQAJgDAEgHQAFgIgBgKQAAgKgBgKQAAgJgCgJQgBgKABgKQAAgIgCgIQAAgBgBgBAAzCDQAAACAAABQABAKAFAJAgdiZQgGgDgKgCQgJgCgKAAQgJABgJABQgJAAgIAHQgHAGgFAHQgGAHgEAJQgEAIAAAJQAAAJAAAKQAAAFAAACAgyiUQgJgBgJAFQgJAFgHAGQgIAGgEAJQgDAJAAAJQAAAKgCAKQgBAJABAJAhggpQgFgEgHAAQgIABgEAFQgFAGgBAIAgihgQgHgGgKAFQgJAFgBAJQAAADABAEAgOhEQgCgDgCgDQgCgCgDABQAFACAEAFgAhZggQgCgFgEgDQAAAAgBgBQAFAHACAGQAAgCAAgCgAgEgtQAAAAAAAAQgCACgCAAQgMAAgBgIQgCgLAOAAQgDgDgCgDAgsAOQgCACgBAEQAAADABADAgkAIQgFACgDAEAhWAWQADgDADgDQAEgHgBgJ");
	this.shape_15.setTransform(0.5,0.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFCC97").s().p("AiyCOQAIgEAKgDIARgFIAPgDQAJgBAJgDIASgGQAKgDADgHQAFgJAAgKIgBgTIgDgTQAAgJAAgKQAAgJgCgIIAAAAIgBgBIAAgBQgEgHgBgGIAGgGQADgFAAgGIAAgEIAAAEQAAAGgDAFIgGAGQgEACgFABQgEAAgFgCQgHgFgFgHQgFgHgDgJQgDgJABgLQABgIAFgGQAEgGAIAAQAHgBAFAFQAFAGACAHIAAgFQgBgIABgIIAFAKQAEALAHAGIgDgPIgDgSIgBgSQAAgKACgKQABgIAGgIQAFgHAIgHIANgLQAJgFAJgCQALgCAFAKQABgGAJgDQAIgCAJgBIATAAIATADQAJACAJAGQAIAFAFAIIAJARQAEAIgCAKIgGASIgCAGIAEgEIADgEQACAKAKABIAIAEQAHAFAFAIIACAKQABAEgBAEQAAAJgDAJIgHARIgDARIgCATQgCALgEAJIgBAGIAAAEQAAAKgIAGQgGAHgIADIgQAIQgIAEgIAAIgCAAIgRAAIgUAAIgBAAIgDAAIAAAAIgBAAIgMgCIgCAAIgSgFQgIgEgIgGIgPgNQgFgGgEgIIgJgQIgIgSIAIASIAJAQQAEAIAFAGIAPANQAIAGAIAEIASAFIACAAIAMACIABAAIAAAAIADAAIABAAIAUAAIARAAIACAAIAAAAQgDAHABAIQAFAHAKABIAMADIASAFIAPAFQAJADAIAEQAIAEAHAFIAOAKQAGAGAHAEIAJAGgAAzBvQABAKAEAIQgEgIgBgKIAAgEIAAAEgAghACIAPAKQAIAFAKACQAIACAJABIATgBQAKAAAIgEIARgJQAJgDAHgFQAIgFAFgHQgFAHgIAFQgHAFgJADIgRAJQgIAEgKAAIgTABQgJgBgIgCQgKgCgIgFIgPgKQgHgFgEgGQADgEAFgBQgFABgDAEQgCACAAAEIgBACIABADIgBgDIABgCQAAgEACgCQAEAGAHAFgAAZgiIABAAIASgCIASgFQAHgDAAgJIAAgCQgBgHgGgDIgCAAQgGgCgIAAIAAAAIAAAAIgCAAIgBAAIgGAAIAGAAIABAAIACAAIAAAAIAAAAQAIAAAGACIACAAQAGADABAHIAAACQAAAJgHADIgSAFIgSACIgBAAIAAAAIgBAAQgGAAgGgEQgHgFAAgKQAAAKAHAFQAGAEAGAAIABAAIAAAAgAgthaQgDAIACAKQADAJAGAGQAGAHALgBQAIAAAFgFQAEgDAAgIIAAgCQgBgJgFgGIAAgCIgFgGIgEgFQgCgCgDAAIgGgBQgLABgFAJgAA4h0QgKAAgHAGQgGAHgBAJQgBALAHAEQAIAFAJgDQAKgCABgJQABgHAAgHIgBgFQAAgEgDgEQgDgDgBAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAAAgBABgAg8hkIgBgEIAAgDQABgIAJgFIABgBIAHgCIAAAAIABAAQAEAAAEAEQgEgEgEAAIgBAAIAAAAIgHACIgBABQgJAFgBAIIAAADIABAEgAASiHIABAAIABgCQAEgFAGAAIAAAAIAAAAIABAAIAAAAIADABQAGABACAEQgCgEgGgBIgDgBIAAAAIgBAAIAAAAIAAAAQgGAAgEAFIgBACIgBAAg");
	this.shape_16.setTransform(0.5,2.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#000000").ss(0.1,1,1).p("AgGiVQAHgFAHgGQAHgGAKgDQAJgCAKgCQAJgBAKABQAJACAJAEQAIADAJAFQAHAEAFAHQAFAHAEAIQADAJABAJQACAKgBAKQAAADgBADAh+gZQgHgDgCgLQgDgJgDgJQgCgJAAgKQABgEAAgFQAAgEAAgEQAAgEgBgDQgCgKAAgKQABgKAFgIQAFgHAIgFQAIgGAHgFQAIgGAKgCQAIgCAJACQAJABAKABQAKABAJADQAKAEAGADQAHgFAHgIQAHgGAJgDQAIgCAJgDQAJgCAJgEQAJgDAKAAQAJgBAJACQAJACAHAGQAIAGAHAGQAHAGAGAHQAEAGADAIQACAFABAFQABAJADAJQACAJACAKQACAJgBAKQgBAJgEAJQgEAJgEAIQgBABgBABQAAAFABAFQABAEAAAEQAAAJgEAIQgDAIgDAJQgDAJgBAJQgCAJAAAKQgBAKgFAKQAAADgBADQAAACAAACQAAAJgHAHQgHAGgIAEQgIAEgIAEQgIAEgIAAIAAAAQgDAHABAIQAAACAAABQABAKAFAJAhZggQgBgJABgIQACAFACAFQAEALAIAHQgCgIgBgHQgCgKgBgJQgBgJAAgJQAAgKACgJQABgJAGgHQAFgIAIgHQAGgFAHgFQAIgFAKgCQALgCAFAKQABgGAJgDQAHgDAKgBQAKAAAKAAQAJABAJACQAKACAIAGQAIAGAFAIQAFAIAEAIQAEAJgCAKQgCAJgDAJQgCADgBACQACgBACgDQABgBACgCAAziiQAIgCAKAFQAHAEAIAGQAHAFAHAGQAHAGAEAIQAFAJACAJQACAJgBAKABChAQgBAIgJADQgKACgIgEQgHgFABgKQABgKAHgGQAGgGALgBQACgEAEAGQADAEABADQAAADAAACQAAAIgBAHQgFABgBgEQgEgMALAAAAThvQAFgJAKACQAGACACADAgXhLQgDgBgEAAQgKAAgFAJQgEAJADAKQACAJAGAGQAHAGAKAAQAJgBAFgEQADgEAAgHQAAgBAAgBQAAAAAAAAQgCACgCAAQgMAAgBgIQgCgLAOAAAAFgdQAAAJAIAGQAGAEAIAAQAJgBAIgBQAJgCAJgDQAIgEgBgKQAAgIgHgCQgJgDgKAAQgDAAgDAAACAgpQgFgIgIgGQgEgCgEgBQgKgCgCgJQACgCACgCAgyiUQgJgBgJAFQgJAFgHAGQgIAGgEAJQgDAJAAAJQAAAKgCAKQgBAJABAJAgdiZQgGgDgKgCQgJgCgKAAQgJABgJABQgJAAgIAHQgHAGgFAHQgGAHgEAJQgEAIAAAJQAAAJAAAKQAAAFAAACAhWAWQgEADgFAAQgFABgEgDQgIgFgEgIQgFgHgDgIQgDgIABgMAhggpQgFgEgHAAQgIABgEAFQgFAGgBAIAgihgQgHgGgKAFQgJAFgBAJQAAADABAEAgXhLQAFACAEAFQgCgDgCgDQgCgCgDABgAhZggQgCgFgEgDQAAAAgBgBQAFAHACAGQAAgCAAgCgAgEgtQAAgJgFgHQAAAAAAgBAgOhEQACADADADAhWAWQADgDADgDQAEgHgBgJAhRAkQABABAAABQAEAIAEAJQAEAJAEAIQAEAHAGAHQAHAHAIAGQAHAGAJADQAJADAJADQAJACAKgBQAKAAAKAAQAIAAAJABQABAAABAAAhRAkQAAAAAAAAQgEgHgBgHAAzCDQAFAGALACQAFABAGABQAJADAJADQAHACAIADQAJACAJAFQAHADAHAFQAHAFAHAGQAGAFAHAEQAFADAEADIllgbQAIgFAKgDQAIgDAJgCQAHgCAHgBQAJgBAKgDQAJgDAJgDQAJgDAEgHQAFgIgBgKQAAgKgBgKQAAgJgCgJQgBgKABgKQAAgIgCgIQAAgBgBgBABTA1QgIAKgVADQgOABgRAEQgsAKACg2QAiAFAkAGQAVAEALALg");
	this.shape_17.setTransform(0.5,0.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFCC97").s().p("AiyCOQAIgEAKgDIARgFIAPgDQAJgBAJgDIASgGQAKgDADgHQAFgJAAgKIgBgTIgDgTQAAgJAAgKQAAgJgCgIIAAAAIAIASIAJAQQAEAIAFAGIAPANQAIAGAIAEIASAFIACAAIAMACIABAAIAAAAIADAAIABAAIAUAAIARAAIACAAIAAAAQgDAHABAIQAFAHAKABIAMADIASAFIAPAFQAJADAIAEQAIAEAHAFIAOAKQAGAGAHAEIAJAGgAAzBvQABAKAEAIQgEgIgBgKIAAgEIAAAEgAAzBcIgRAAIgUAAIgBAAIgDAAIAAAAIgBAAIgMgCIgCAAIgSgFQgIgEgIgGIgPgNQgFgGgEgIIgJgQIgIgSIgBgBIAAgBQgEgHgBgGIAGgGQADgFAAgGIAAgEIAAAEQAAAGgDAFIgGAGQgEACgFABQgEAAgFgCQgHgFgFgHQgFgHgDgJQgDgJABgLQABgIAFgGQAEgGAIAAQAHgBAFAFQAFAGACAHIAAgFQgBgIABgIIAFAKQAEALAHAGIgDgPIgDgSIgBgSQAAgKACgKQABgIAGgIQAFgHAIgHIANgLQAJgFAJgCQALgCAFAKQABgGAJgDQAIgCAJgBIATAAIATADQAJACAJAGQAIAFAFAIIAJARQAEAIgCAKIgGASIgCAGIAEgEIADgEQACAKAKABIAIAEQAHAFAFAIIACAKQABAEgBAEQAAAJgDAJIgHARIgDARIgCATQgCALgEAJIgBAGIAAAEQAAAKgIAGQgGAHgIADIgQAIQgIAEgIAAIgBAAIgBAAgAAXAwQAQgEAOgCQAWgCAIgLQgLgKgVgEIhGgMQgBA3ArgKgAAZgiIABAAIASgCIASgFQAHgDAAgJIAAgCQgBgHgGgDIgCAAQgGgCgIAAIAAAAIAAAAIgCAAIgBAAIgGAAIAGAAIABAAIACAAIAAAAIAAAAQAIAAAGACIACAAQAGADABAHIAAACQAAAJgHADIgSAFIgSACIgBAAIAAAAIgBAAQgGAAgGgEQgHgFAAgKQAAAKAHAFQAGAEAGAAIABAAIAAAAgAgthaQgDAIACAKQADAJAGAGQAGAHALgBQAIAAAFgFQAEgDAAgIIAAgCQgBgJgFgGIAAgCIgFgGIgEgFQgCgCgDAAIgGgBQgLABgFAJgAA4h0QgKAAgHAGQgGAHgBAJQgBALAHAEQAIAFAJgDQAKgCABgJQABgHAAgHIgBgFQAAgEgDgEQgDgDgBAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAAAgBABgAg8hkIgBgEIAAgDQABgIAJgFIABgBIAHgCIAAAAIABAAQAEAAAEAEQgEgEgEAAIgBAAIAAAAIgHACIgBABQgJAFgBAIIAAADIABAEgAASiHIABAAIABgCQAEgFAGAAIAAAAIAAAAIABAAIAAAAIADABQAGABACAEQgCgEgGgBIgDgBIAAAAIgBAAIAAAAIAAAAQgGAAgEAFIgBACIgBAAg");
	this.shape_18.setTransform(0.5,2.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#000000").ss(0.1,1,1).p("Ah+gZQgHgDgCgLQgDgJgDgJQgCgJAAgKQABgEAAgFQAAgEAAgEQAAgEgBgDQgCgKAAgKQABgKAFgIQAFgHAIgFQAIgGAHgFQAIgGAKgCQAIgCAJACQAJABAKABQAKABAJADQAKAEAGADQAHgFAHgIQAHgGAJgDQAIgCAJgDQAJgCAJgEQAJgDAKAAQAJgBAJACQAJACAHAGQAIAGAHAGQAHAGAGAHQAEAGADAIQACAFABAFQABAJADAJQACAJACAKQACAJgBAKQgBAJgEAJQgEAJgEAIQgBABgBABQgFgIgIgGQgEgCgEgBQgKgCgCgJQACgCACgCAgGiVQAHgFAHgGQAHgGAKgDQAJgCAKgCQAJgBAKABQAJACAJAEQAIADAJAFQAHAEAFAHQAFAHAEAIQADAJABAJQACAKgBAKQAAADgBADAhZggQgBgJABgIQACAFACAFQAEALAIAHQgCgIgBgHQgCgKgBgJQgBgJAAgJQAAgKACgJQABgJAGgHQAFgIAIgHQAGgFAHgFQAIgFAKgCQALgCAFAKQABgGAJgDQAHgDAKgBQAKAAAKAAQAJABAJACQAKACAIAGQAIAGAFAIQAFAIAEAIQAEAJgCAKQgCAJgDAJQgCADgBACQACgBACgDQABgBACgCAAziiQAIgCAKAFQAHAEAIAGQAHAFAHAGQAHAGAEAIQAFAJACAJQACAJgBAKABChAQgBAIgJADQgKACgIgEQgHgFABgKQABgKAHgGQAGgGALgBQACgEAEAGQADAEABADQAAADAAACQAAAIgBAHQgFABgBgEQgEgMALAAAAThvQAFgJAKACQAGACACADAAFgdQAAAJAIAGQAGAEAIAAQAJgBAIgBQAJgCAJgDQAIgEgBgKQAAgIgHgCQgJgDgKAAQgDAAgDAAAgXhLQgDgBgEAAQgKAAgFAJQgEAJADAKQACAJAGAGQAHAGAKAAQAJgBAFgEQADgEAAgHQAAgBAAgBQAAgJgFgHQAAAAAAgBACAgpQAAAFABAFQABAEAAAEQAAAJgEAIQgDAIgDAJQgDAJgBAJQgCAJAAAKQgBAKgFAKQAAADgBADQAAACAAACQAAAJgHAHQgHAGgIAEQgIAEgIAEQgIAEgIAAABkALQgFAGgIAGQgHAFgJAEQgIADgJAFQgIAFgJAAQgKAAgKAAQgJAAgJgCQgJgCgIgFQgIgFgHgGQgHgFgEgGAhRAkQABABAAABQAEAIAEAJQAEAJAEAIQAEAHAGAHQAHAHAIAGQAHAGAJADQAJADAJADQAJACAKgBQAKAAAKAAQAIAAAJABQABAAABAAIAAAAQgDAHABAIQAFAGALACQAFABAGABQAJADAJADQAHACAIADQAJACAJAFQAHADAHAFQAHAFAHAGQAGAFAHAEQAFADAEADIllgbQAIgFAKgDQAIgDAJgCQAHgCAHgBQAJgBAKgDQAJgDAJgDQAJgDAEgHQAFgIgBgKQAAgKgBgKQAAgJgCgJQgBgKABgKQAAgIgCgIQAAgBgBgBQAAAAAAAAQgEgHgBgHQgEADgFAAQgFABgEgDQgIgFgEgIQgFgHgDgIQgDgIABgMAAzCDQAAACAAABQABAKAFAJAgyiUQgJgBgJAFQgJAFgHAGQgIAGgEAJQgDAJAAAJQAAAKgCAKQgBAJABAJAgdiZQgGgDgKgCQgJgCgKAAQgJABgJABQgJAAgIAHQgHAGgFAHQgGAHgEAJQgEAIAAAJQAAAJAAAKQAAAFAAACAhggpQgFgEgHAAQgIABgEAFQgFAGgBAIAgihgQgHgGgKAFQgJAFgBAJQAAADABAEAgXhLQAFACAEAFQgCgDgCgDQgCgCgDABgAhZggQgCgFgEgDQAAAAgBgBQAFAHACAGQAAgCAAgCgAgEgtQAAAAAAAAQgCACgCAAQgMAAgBgIQgCgLAOAAAgOhEQACADADADAgkAIQgFACgDAEQgCACgBAEQAAADABADAhWAWQADgDADgDQAEgHgBgJ");
	this.shape_19.setTransform(0.5,0.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFCC97").s().p("AiyCOQAIgEAKgDIARgFIAPgDQAJgBAJgDIASgGQAKgDADgHQAFgJAAgKIgBgTIgDgTQAAgJAAgKQAAgJgCgIIAAAAIAIASIAJAQQAEAIAFAGIAPANQAIAGAIAEIASAFIACAAIAMACIABAAIAAAAIADAAIABAAIAUAAIARAAIACAAIAAAAQgDAHABAIQAFAHAKABIAMADIASAFIAPAFQAJADAIAEQAIAEAHAFIAOAKQAGAGAHAEIAJAGgAAzBvQABAKAEAIQgEgIgBgKIAAgEIAAAEgAAzBcIgRAAIgUAAIgBAAIgDAAIAAAAIgBAAIgMgCIgCAAIgSgFQgIgEgIgGIgPgNQgFgGgEgIIgJgQIgIgSIgBgBIAAgBQgEgHgBgGIAGgGQADgFAAgGIAAgEIAAAEQAAAGgDAFIgGAGQgEACgFABQgEAAgFgCQgHgFgFgHQgFgHgDgJQgDgJABgLQABgIAFgGQAEgGAIAAQAHgBAFAFQAFAGACAHIAAgFQgBgIABgIIAFAKQAEALAHAGIgDgPIgDgSIgBgSQAAgKACgKQABgIAGgIQAFgHAIgHIANgLQAJgFAJgCQALgCAFAKQABgGAJgDQAIgCAJgBIATAAIATADQAJACAJAGQAIAFAFAIIAJARQAEAIgCAKIgGASIgCAGIAEgEIADgEQACAKAKABIAIAEQAHAFAFAIIACAKQABAEgBAEQAAAJgDAJIgHARIgDARIgCATQgCALgEAJIgBAGIAAAEQAAAKgIAGQgGAHgIADIgQAIQgIAEgIAAIgBAAIgBAAgAghACIAPAKQAIAFAKACQAIACAJABIATgBQAKAAAIgEIARgJQAJgDAHgFQAIgFAFgHQgFAHgIAFQgHAFgJADIgRAJQgIAEgKAAIgTABQgJgBgIgCQgKgCgIgFIgPgKQgHgFgEgGQADgEAFgBQgFABgDAEQgCACAAAEIgBACIABADIgBgDIABgCQAAgEACgCQAEAGAHAFgAAZgiIABAAIASgCIASgFQAHgDAAgJIAAgCQgBgHgGgDIgCAAQgGgCgIAAIAAAAIAAAAIgCAAIgBAAIgGAAIAGAAIABAAIACAAIAAAAIAAAAQAIAAAGACIACAAQAGADABAHIAAACQAAAJgHADIgSAFIgSACIgBAAIAAAAIgBAAQgGAAgGgEQgHgFAAgKQAAAKAHAFQAGAEAGAAIABAAIAAAAgAgthaQgDAIACAKQADAJAGAGQAGAHALgBQAIAAAFgFQAEgDAAgIIAAgCQgBgJgFgGIAAgCIgFgGIgEgFQgCgCgDAAIgGgBQgLABgFAJgAA4h0QgKAAgHAGQgGAHgBAJQgBALAHAEQAIAFAJgDQAKgCABgJQABgHAAgHIgBgFQAAgEgDgEQgDgDgBAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAAAgBABgAg8hkIgBgEIAAgDQABgIAJgFIABgBIAHgCIAAAAIABAAQAEAAAEAEQgEgEgEAAIgBAAIAAAAIgHACIgBABQgJAFgBAIIAAADIABAEgAASiHIABAAIABgCQAEgFAGAAIAAAAIAAAAIABAAIAAAAIADABQAGABACAEQgCgEgGgBIgDgBIAAAAIgBAAIAAAAIAAAAQgGAAgEAFIgBACIgBAAgAgsgJIAAAAg");
	this.shape_20.setTransform(0.5,2.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_8},{t:this.shape_7},{t:this.shape_2},{t:this.shape_6}]},2).to({state:[{t:this.shape_5},{t:this.shape_11},{t:this.shape_10},{t:this.shape_2},{t:this.shape_9}]},2).to({state:[{t:this.shape_5},{t:this.shape_14},{t:this.shape_13},{t:this.shape_2},{t:this.shape_12}]},2).to({state:[{t:this.shape_5},{t:this.shape_8},{t:this.shape_7},{t:this.shape_2},{t:this.shape_6}]},2).to({state:[{t:this.shape_5},{t:this.shape_14},{t:this.shape_13},{t:this.shape_2},{t:this.shape_12}]},1).to({state:[{t:this.shape_5},{t:this.shape_16},{t:this.shape_3},{t:this.shape_2},{t:this.shape_15}]},2).to({state:[{t:this.shape_5},{t:this.shape_18},{t:this.shape_13},{t:this.shape_2},{t:this.shape_17}]},2).to({state:[{t:this.shape_5},{t:this.shape_20},{t:this.shape_3},{t:this.shape_2},{t:this.shape_19}]},6).wait(1));

	// Layer 2
	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#000000").ss(1,1,1).p("AD/j+QBpBqAACUQAACVhpBqQhqBpiVAAQiUAAhqhpQhphqAAiVQAAiUBphqQBqhpCUAAQCVAABqBpg");
	this.shape_21.setTransform(0,1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#0000FF").s().p("Aj+D/QhphqAAiVQAAiUBphqQBqhpCUAAQCVAABqBpQBpBqAACUQAACVhpBqQhqBpiVAAQiUAAhqhpg");
	this.shape_22.setTransform(0,1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_22},{t:this.shape_21}]}).wait(20));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-37,-36,74,74);


(lib.goNext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,11.3).s().p("AhLAqQghgRABgYQgBgZAhgRQAfgSAsAAQAsAAAgASQAgARAAAZQAAAYggARQggASgsAAQgsAAgfgSg");
	this.shape.setTransform(22.8,8.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.502)").s().p("AhUhcICpBdIipBcg");
	this.shape_1.setTransform(25.1,20.4);

	this.blinker = new lib.general_buttoncolor();
	this.blinker.parent = this;
	this.blinker.setTransform(23.4,20.1,1.5,1.5,0,0,0,11.9,11.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,14.8).s().p("AhjA3QgqgXABgfQgBggAqgXQAqgYA5AAQA6AAAqAYQApAXAAAgQAAAfgpAXQgqAYg6AAQg5AAgqgYg");
	this.shape_2.setTransform(23.4,8.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("rgba(0,0,0,0.502)").ss(1,1,1,3,true).p("AAACxQhIAAg0g0Qg1g0AAhJQAAhIA1g0QA0g0BIAAQBKAAA0A0QA0A0AABIQAABJg0A0Qg0A0hKAAg");
	this.shape_3.setTransform(23.3,20.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["rgba(103,103,103,0.839)","rgba(134,134,134,0)"],[0.678,0.918],-0.8,0,0,-0.8,0,24.9).s().p("AitClQhEhFAAhgQAAhgBEhEQBEhEBiAAQBfAABCAwQBBAvAWCrQAVCskNAbQhiAAhEhEgAgICRQBGAAAygwIABgBIAEgDQA0g0AAhIQAAhJg0g0IgGgGIAAAAQgyguhEAAIgBgBIAAAAIgBAAIAAABQhEAAgyAuIgBABIgCACIgCABIAAAAIgBACQg1A0AABJQAABIA1A0IABABIACACQAzAxBGAAIAAAAIABAAIgBAAIAAAAQhGAAgzgxIgCgCIgBgBQg1g0AAhIQAAhJA1g0IABgCIAAAAIACgBIACgCIABgBQAyguBEAAIAAgBIABAAIAAAAIABABQBEAAAyAuIAAAAIAGAGQA0A0AABJQAABIg0A0IgEADIgBABQgyAwhGAAIAAAAIAAAAIAAAAIAAAAg");
	this.shape_4.setTransform(24.2,23.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},2).wait(1));

	// Layer 2
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#33FFFF").s().p("AipCqQhGhHAAhjQAAhiBGhGQBGhHBjAAQBjAABHBHQBGBGAABiQAABjhGBHQhHBGhjAAQhjAAhGhGg");
	this.shape_5.setTransform(24.4,21.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0099FF").s().p("AipCqQhGhHAAhjQAAhiBGhGQBGhHBjAAQBjAABHBHQBGBGAABiQAABjhGBHQhHBGhjAAQhjAAhGhGg");
	this.shape_6.setTransform(24.4,21.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.5,46.7);


(lib.intro = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_25 = function() {
		this.stop();
		playSound("high_blip");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(25).call(this.frame_25).wait(81));

	// Layer 15
	this.instance = new lib.Tween23("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(58.1,-245);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(15).to({_off:false},0).to({scaleX:0.59,scaleY:0.59,x:47.1,y:-120},10).wait(81));

	// Layer 14
	this.instance_1 = new lib.micktalk();
	this.instance_1.parent = this;
	this.instance_1.setTransform(43,26,1,1,0,0,0,0,1);

	this.instance_2 = new lib.MicStill();
	this.instance_2.parent = this;
	this.instance_2.setTransform(43.5,26.5,2.195,2.195,0,0,0,36,36);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).to({state:[{t:this.instance_1}]},20).to({state:[{t:this.instance_2}]},1).wait(85));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:2.19,scaleY:2.19},20).to({_off:true},1).wait(85));

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.3,1,1).p("EAjjgWkMAAAAtJMhHFAAAMAAAgtJg");
	this.shape.setTransform(46.5,-9.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FFFFFF","#FF3366"],[0,1],-0.8,227.4,0.9,-227.3).s().p("EgjiAWlMAAAgtJMBHFAAAMAAAAtJg");
	this.shape_1.setTransform(46.5,-9.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(106));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-182,-154.6,457,291);


(lib.UI = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//Menu button -----------------------------------------
		this.btn_menu.addEventListener("click", openMenu.bind(this));
		
		//volume buttons -----------------------------------------
		this.vol_dwn.addEventListener("click", volDwn.bind(this));
		this.vol_up.addEventListener("click", volUp.bind(this));
		this.vol_mute.addEventListener("click", volMute.bind(this));
		
		//Nav buttons -----------------------------------------
		this.btn_goNext.addEventListener("click", openNext.bind(this));
		//this.btn_goBack.addEventListener("click", openPrev.bind(this));
		
		//background music ---------------------------------------
		var bgm = createjs.Sound.play('bgmDia',{loop:-1});
		
		//volume vars -----------------------------------------
		var mute= false;
		bgm.volume = 0.05;
		var prev_vol = bgm.volume;
		
		//Menu function -----------------------------------------
		function openMenu(){
		
		 window.open ("../menu/menu.html","_self");
		}
		
		//volume functions -----------------------------------------
		function volDwn()
		{
			createjs.Sound.volume = createjs.Sound.volume -0.1;
			if(!mute){
				bgm.volume -= 0.1;
				prev_vol = bgm.volume;
			}
			console.log(bgm.volume);
			console.log(prev_vol);
		}
		function volUp()
		{
			createjs.Sound.volume = createjs.Sound.volume +0.1;
			if(!mute){
				bgm.volume += 0.1;
				prev_vol = bgm.volume;
			}
			console.log(bgm.volume);
			console.log(prev_vol);
		}
		
		function volMute()
		{
			if(!mute){
				mute = true
				bgm.volume = 0;
			}
			else{
				mute = false;
				bgm.volume = prev_vol;
			}
			console.log(mute);
		}
		
		
		//Nav functions -----------------------------------------
		
		function openNext(){
		
		 window.open ("diag_Scene1.html","_self");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// mute
	this.vol_mute = new lib.vol_mute();
	this.vol_mute.parent = this;
	this.vol_mute.setTransform(31.8,2.1,1,1,0,0,0,15,14.1);
	new cjs.ButtonHelper(this.vol_mute, 0, 1, 2, false, new lib.vol_mute(), 3);

	this.timeline.addTween(cjs.Tween.get(this.vol_mute).wait(1));

	// main
	this.instance = new lib.Copyright("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-220.6,376.5);

	this.btn_goNext = new lib.goNext();
	this.btn_goNext.parent = this;
	this.btn_goNext.setTransform(-1.7,335.3);
	new cjs.ButtonHelper(this.btn_goNext, 0, 1, 2, false, new lib.goNext(), 3);

	this.vol_up = new lib.vol_pos();
	this.vol_up.parent = this;
	this.vol_up.setTransform(-6.7,2.6,1,1,0,0,0,9,7);
	new cjs.ButtonHelper(this.vol_up, 0, 1, 2, false, new lib.vol_pos(), 3);

	this.vol_dwn = new lib.vol_neg();
	this.vol_dwn.parent = this;
	this.vol_dwn.setTransform(-28.7,2.6,1,1,0,0,0,9,7);
	new cjs.ButtonHelper(this.vol_dwn, 0, 1, 2, false, new lib.vol_neg(), 3);

	this.btn_menu = new lib.menu_main();
	this.btn_menu.parent = this;
	this.btn_menu.setTransform(-89.6,2.6,1,1.143,0,0,0,23.4,10.5);
	new cjs.ButtonHelper(this.btn_menu, 0, 1, 2, false, new lib.menu_main(), 3);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.5,1,1).p("AAYBrQgBgLgUgUQgQgRgKAAIAAh1QAKAAASgTQATgTAAgKg");
	this.shape.setTransform(-47.7,2.3,0.687,0.681);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AADBMQgQgRgKAAIAAh1QAKgBASgSQATgTAAgJIAADTQgBgKgUgUg");
	this.shape_1.setTransform(-47.7,2.3,0.687,0.681);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s("#000000").ss(1.5,1,1).rr(-0.75,-3.45,1.5,6.9,0.2);
	this.shape_2.setTransform(-52.2,2.3,1,1.003);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1.5,1,1).p("AAHAAQAAAJgHAHQgCAEgEACIAAgrQAEACACAEQACACACACQADAFAAAGg");
	this.shape_3.setTransform(-43.2,2.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgGgUQAEABACAEIABAAIADAFQADAEAAAGQAAAJgGAHIgBAAQgCAEgEABg");
	this.shape_4.setTransform(-46.5,2.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.btn_menu},{t:this.vol_dwn},{t:this.vol_up},{t:this.btn_goNext},{t:this.instance}]}).wait(1));

	// vol_frame
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s("#000000").ss(1.5,1,1).rr(-33,-12,66,24,4.9);
	this.shape_5.setTransform(-24.7,2.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_5).wait(1));

}).prototype = getMCSymbolPrototype(lib.UI, new cjs.Rectangle(-283.9,-13,331.7,399), null);


// stage content:
(lib.diag_Scene0 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{scene0:0,Scene0Repeat:20});

	// timeline functions:
	this.frame_0 = function() {
		playSound("learntodiagram");
	}
	this.frame_126 = function() {
		/* gotoAndPlay("scene0Repeat");
		*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(126).call(this.frame_126).wait(1));

	// Main
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(4,1,1).p("EAjoAWlMhHPAAAMAAAgtJMBHPAAAg");
	this.shape.setTransform(274,187.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(127));

	// Layer 3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgjsAW0MAAAgtnMBHZAAAMAAAAtng");
	mask.setTransform(274.5,188);

	// Layer 1
	this.instance = new lib.intro();
	this.instance.parent = this;
	this.instance.setTransform(274,184,1,1,0,0,0,46,-12.7);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(127));

	// button
	this.UI = new lib.UI();
	this.UI.parent = this;
	this.UI.setTransform(548,54.9,1,1,0,0,0,54,40.5);

	this.timeline.addTween(cjs.Tween.get(this.UI).wait(127));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(319,201.6,497.5,398.7);
// library properties:
lib.properties = {
	id: '94D8BE42B5F64A4F858D864B719E8140',
	width: 550,
	height: 400,
	fps: 12,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"sounds/bgmDia.mp3", id:"bgmDia"},
		{src:"sounds/wrong_answer.mp3", id:"wrong_answer"},
		{src:"sounds/high_blip.mp3", id:"high_blip"},
		{src:"sounds/learntodiagram.mp3", id:"learntodiagram"},
		{src:"sounds/right_answer.mp3", id:"right_answer"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['94D8BE42B5F64A4F858D864B719E8140'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;