(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 550,
	height: 400,
	fps: 12,
	color: "#FFFFFF",
	webfonts: {},
	manifest: [
		{src:"sounds/BeautifulDrumnbass.mp3", id:"BeautifulDrumnbass"},
		{src:"sounds/wrong_answer.mp3", id:"wrong_answer"},
		{src:"sounds/high_blip.mp3", id:"high_blip"},
		{src:"sounds/learntodiagram.mp3", id:"learntodiagram"},
		{src:"sounds/right_answer.mp3", id:"right_answer"}
	]
};



lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib.Tween23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AC9DnQgJgPgIgiIgLg1QgNgxgbimIg+C3IgSA7QgLAigMAXQgNAXgTAAQgTAAgKgUQgHgNgGgUIgJgiQgehsgZh6IgKA3IgoCgQgCAdgNA4QgJAYgWAAQgPAAgJgLQgHgJgBgOQABgzAUhLIAih6IAShhQAOhEAPgVQAMgSATAAQATAAALAXQALAcAOBUQARBlAiB0QArh1AhiAIAKgtQAFgbAKgQQALgXAVAAQAbAAANAzQAFARAHA4QATCJAaBiIAQA1QALAqAAAKQAAANgKAJQgKAJgMAAQgRAAgKgRg");
	this.shape.setTransform(298.1,3.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("ABrCfQgIgcgMhFQggAEgzALIhPARQgQApglBNQgKARgRAAQgMAAgKgJQgJgJAAgNQAAgPAuhhQgFgIAAgKQAAgZAegHQAjhAA2hWQBGh0ASAAQAZAAAIAhIAUBoIAuDUIARAwQAJAZAAAIQAAAOgJAJQgKAIgMAAQgdAAgUhIgAgnAWQAlgKBKgMIgZh2g");
	this.shape_1.setTransform(246.4,3.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AicDoQgJgJAAgOIgChIQgDgwAAgZQABgcAFg2QAHg4AAgcQAAgQgDgeQgDgfAAgQQAAgRAKgNQAMgRAUACIBKAGQArAFAbAPQB8BCAABgQAAAugrAiQghAdg0APQBgA0AwA5QAHAKAAALQABANgKAJQgKAKgMAAQgMAAgKgKQhmhlh7gjIADA9IACA8QAAAOgJAJQgJAJgNAAQgNAAgJgJgAhiiKQADAXAAAPQAAAYgFAlIgGA7IAOAAIANABQBPAAAlgVQARgIAOgPQARgRAAgMQAAgrgwglQgrgigxgFIgugEg");
	this.shape_2.setTransform(204.7,2.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AidDSQgmgrAAhUQAAhQAmhSQAlhVA7g0QAogjAqAAQAcAAAuATQA4AWAAAbQAAAMgKAKQgJAKgNAAQgGAAgNgIQgvgcggAAQgVAAgZAYQgNAMgYAgQhHBeAABsQAAA6ASAXQATAZA0AAQA1AAApgjQArglARhEQhVAEg7AdQgHADgHAAQgOAAgJgLQgIgJAAgNQAAgRAQgKQBBgmCjAAQANAAAJAJQAJAGAAAOQAAAUgRAJQgTBeg9A5Qg+A4hRAAQhLAAgmgqg");
	this.shape_3.setTransform(163.3,2.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("ABrCfQgIgcgMhFQggAEgzALIhPARQgQApglBNQgKARgRAAQgMAAgKgJQgJgJAAgNQAAgPAuhhQgFgIAAgKQAAgZAegHQAjhAA2hWQBGh0ASAAQAZAAAIAhIAUBoIAuDUIARAwQAJAZAAAIQAAAOgJAJQgKAIgMAAQgdAAgUhIgAgnAWQAlgKBKgMIgZh2g");
	this.shape_4.setTransform(117.9,3.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AiGDiQgJgJAAgOQAAgNAJgJQAIgJAOAAQAUAAAtgHQADgZAAggQAAgVgCgeQgBgfAAgVQAAhFAIhqIgoABIgoABQgNAAgJgJQgJgJAAgOQAAgdAdgCQAZgDBEAAQA7AABcANQAcAEAAAdQAAAPgLAIQgJAHgLAAQgVAAgdgEIgxgGQgIBaABBPIABA1IAAA1QAAAdgBAYIBhgBQAMAAAJAJQAJAJAAANQAAAOgJAJQgJAJgMAAIg0ABIg0AAQgSAAgpAGQgoAGgUAAQgOAAgIgJg");
	this.shape_5.setTransform(78.2,3.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AhgD3QgjgJgRgNIgDAAQgOAAgIgJQgJgJAAgNQAAghADhAQAChAAAghIgBhpIgBhsQAAgNANgOQAMgNANAAQAIAAAqAUQAvAYAIACQBVAeA9A9QBJBJAABWQAAA0gZAxQgZAwgrAeQgvAghYAAQgWAAgdgHgAh0hVIABBXIgECoIAGAEQAbASApAAQBEAAAggVQAfgUARgjQARgiABglQAAhVhfg+QgegVhxgyg");
	this.shape_6.setTransform(39.3,3.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AibC+QhAg3AAhYQAAhpA/hXQBHhgBnAAQBlAAAyAuQAzAvAABmQAABpg6BVQhCBihoAAQhWAAg9g0gAhshnQgwBFAABRQAAA8AsAlQAqAiA+AAQBJABAxhMQArhDAAhSQAAhKghgdQgfgdhLAAQhJAAg1BLg");
	this.shape_7.setTransform(-28.3,3.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgVDhQgKgJAAgNIACgOIACgOIgCgtIgCgtQAAgsgIhOQgHhWgBgmIgcABQhDAAgngKQgZgHAAgYQAAgMAIgKQAKgLAOABIAxAGQAfADATAAIA4AAIA2gBQAYAAAvADQAuAEAYAAQANAAAJAJQAJAJAAANQAAAOgJAJQgJAJgNAAQgXAAgvgEQgvgDgYAAIgVAAQABAqAHBgQAHBXAAAxIACAhIACAgQAAAVgHAPQgIAVgSAAQgLAAgKgJg");
	this.shape_8.setTransform(-72.4,2.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AjODvQgJgJAAgNQAAgNACgbIACgnIABg5IACg5IgCg7IgBg9QABgUgEgmQgDgmAAgUQAAgOAMgMQAMgLAPAAQARAAAXAjQBNBzA9BMQBHBYBXBSQABgNgBgaIgBgnQAAiFgLhQQAAgIgIgYQgFgVAAgLQgBgkAhAAQA2AAgBDIIgBBkIgBBlQABAPgGAjQgEAfgcAAQgRAAgYgWQh9h3igjdIgCBGIgBBEIACBMIABBNQAABTggAAQgRAAgKgLg");
	this.shape_9.setTransform(-140,2.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AicDoQgJgJAAgOIgChIQgDgwAAgZQABgcAFg2QAHg4AAgcQAAgQgDgeQgDgfAAgQQAAgRAKgNQAMgRAUACIBKAGQArAFAbAPQB8BCAABgQAAAugrAiQgiAdgzAPQBgA0AvA5QAIAKAAALQAAANgJAJQgKAKgMAAQgMAAgKgKQhmhlh7gjIADA9IACA8QAAAOgJAJQgJAJgNAAQgNAAgJgJgAhiiKQACAXABAPQgBAYgEAlIgGA7IAOAAIANABQBPAAAkgVQASgIAOgPQARgRAAgMQAAgrgxglQgqgigxgFIgugEg");
	this.shape_10.setTransform(-184.6,2.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("ABrCfQgIgcgMhFQggAEgzALIhPARQgQApglBNQgKARgRAAQgMAAgKgJQgJgJAAgNQAAgPAuhhQgFgIAAgKQAAgZAegHQAjhAA2hWQBGh0ASAAQAZAAAIAhIAUBoIAuDUIARAwQAJAZAAAIQAAAOgJAJQgKAIgMAAQgdAAgUhIgAgnAWQAlgKBKgMIgZh2g");
	this.shape_11.setTransform(-228.6,3.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AiGDsQgdgbAAhjIABgrIACgyQgEgIABgHQAAgJAFgIQAHhZgBgrQAAgLgCgWQgEgWAAgLQAAglAfAAQANAAAJAJQAlgKAhgFQAhgFAbABQBKAAAtARQAUAJAAAVQAAAMgIAJQgIALgOAAIgJgCQg0gOgwAAQgZAAgcAEQgeAFgiAKQACATAAAMQAAArgFBLICEgNQA8gGANAAQAOAAAKAIQAJAJAAAPQgBAZgcAEIhJAHIiMAMIgCAqIgBAkQAABEAKAMQAIAJAoAAIA4gBIA6gBIASgDIASgCQAgAAAAAhQAAAagbAEQgcAHheAAQhggBgbgZg");
	this.shape_12.setTransform(-270,2.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AiEDxQgSgMAAgjIAFhmQAIiKAAisQABgNAIgKQAJgJANAAQAOAAAIAJQAJAKAAANQAACugJCMIgDAvQgDAZABAUQBQABB5gnIAJgBQAOAAAJAKQAIAKAAAMQgBATgTAKQgjAQhLANQhCAMgrAAQgfAAgOgKg");
	this.shape_13.setTransform(-307.2,3.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-327.5,-45.9,655,91.8);


(lib.skiptomenu = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AATApQgLAGgMAAQgMAAgHgFQgJgGgBgKQgEgYABgQQgBgMADgPQABgIAHAAQAEAAADADQACACAAAEIgBANIgBANIABAXQABALACAGIAGADIAFAAQAKAAANgDIAAgSIgBgPQAAgTACgOQABgIAIAAQADAAADACQADADgBADIgBAhIAAARIAAATIAAAGIAAAGQABAEgDACQgDADgDAAQgHAAgCgJg");
	this.shape.setTransform(16.7,0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AAVAqIgDgTIgBgTIABgGIAAgJQAAgSgHgBQgKAAgHAMQgIALgFAOIgBAIIAAAJIAAAIIABAIQAAAEgCADQgDACgEAAQgDAAgDgCQgCgDAAgEIgBgIIAAgIIABgYIABgYIAAgIIAAgJQAAgDACgDQADgDADABQAIAAABALIAAAKQAPgUAOAAQAOAAAFANQAEAIAAAQIAAAJIAAAGIACATQACAMAAAHQAAAEgCADQgDABgEAAQgHABgBgJg");
	this.shape_1.setTransform(7.5,0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgdAmQgNgMAAgTQAAgVALgQQAMgQATgBQAOAAAJAGQALAFAAANQAAAJgKAHQgEADgOAFIggAQQAFAIAHADQAIADAIAAQAGAAAIgBQAKgDADgFQADgFAEAAQADAAACADQACACAAADQAAAKgPAGQgOAHgMAAQgSAAgNgKgAgRgWQgHAIgDAPIAbgLQAOgIAGgFQgHgIgNAAQgKABgHAIg");
	this.shape_2.setTransform(-2.2,0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgEAzQgCgCAAgEIgCggIgCgdQAAgJgDgGQgGADgHAHIgKALIgEAGIgBANIgBAPIAAAIIABAHQAAADgCADQgDACgEAAQgKAAAAgWIABgQIABgOIAAgOIgBgOQAAgUAJAAQADAAADADQADADAAAEIgBAFIAAAFIAAAJQAFgJAIgIQAJgHAHAAQANAAAEAOQAEgHAHgDQAHgDAIAAQAPAAAFAQQACADACAVIAGAxQABADgDADQgDACgDAAQgIAAgBgIIgDgbIgDgZQgBgGgCgGQgDgIgDAAQgEAAgJAGQgIAFgDADIABAQIACAWQACAOAAAJQAAAEgCACQgDADgEAAQgBAAgDgDg");
	this.shape_3.setTransform(-14.1,0.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(2,1,1).p("AkZh7IIzAAIAAD3IozAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AkZB8IAAj3IIzAAIAAD3g");

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAVAuQgMAGgOAAQgMAAgJgGQgJgGgBgMQgEgZAAgSQAAgNADgRQABgJAIAAQAEAAADADQADADAAAEIgCAOIgBAPIABAZQABAMACAHIAGADIAGAAQALAAAPgEIAAgTIAAgRQAAgVABgPQABgJAJAAQAEAAADACQADADgBAEIgBAlIAAATIAAAVIAAAGIAAAHQAAAEgCACQgDADgEAAQgIAAgCgJg");
	this.shape_6.setTransform(18.3,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AAXAvIgDgWIgBgVIAAgHIABgJQAAgVgIAAQgLAAgIANQgJALgFAQIgBAKIAAAJIAAAJIABAJQAAAEgDADQgCACgFAAQgEAAgCgCQgDgDAAgEIgBgJIAAgJIABgaIACgbIgBgJIAAgJQAAgFADgCQACgDAEAAQAJAAABANIAAALQARgWAPAAQAPAAAGAOQAFAJAAASIAAAKIAAAHQAAAIACAMQACANAAAIQAAAEgDADQgDADgEAAQgIAAgBgJg");
	this.shape_7.setTransform(8.2,0.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AggApQgPgMAAgWQAAgXAMgRQAOgSAVAAQAPAAAKAFQANAHAAAOQAAAJgMAIQgEAEgQAFIgjASQAFAIAJAEQAIAEAJAAQAHAAAIgDQALgDAEgFQADgFAEAAQADAAADACQADADAAADQAAALgRAIQgPAGgOAAQgVAAgNgLgAgTgZQgHAJgEARIAdgMQAQgJAIgGQgJgIgOAAQgLAAgIAJg");
	this.shape_8.setTransform(-2.4,0.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgEA5QgDgDAAgFQAAgLgCgXQgDgVAAgMQAAgKgCgGQgHADgHAHIgMANIgEAGIgCAPIgBARIABAIIABAIQAAAEgDACQgDADgEAAQgLAAAAgZIACgRIABgPIgBgQIgBgPQAAgWAKAAQADAAAEADQADAEAAADIgBAGIAAAGIAAAKQAFgKAKgJQAJgIAHAAQAPAAAEAPQAGgHAHgDQAHgEAKAAQAQAAAGARIAEAcIAHA1QAAAEgDADQgDACgEAAQgIAAgBgIQgCgLgCgTIgDgcIgDgNQgEgJgEAAQgDAAgKAGQgJAGgDADIAAASIADAYQACAQAAAJQAAAFgCADQgDACgEAAQgCAAgDgCg");
	this.shape_9.setTransform(-15.6,0.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#000000").ss(2,1,1).p("AE3CJIptAAIAAkRIJtAAg");
	this.shape_10.setTransform(0,0.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#00FFFF").s().p("Ak2CJIAAkRIJsAAIAAERg");
	this.shape_11.setTransform(0,0.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AATApQgLAGgMAAQgMAAgHgFQgJgGgBgKQgEgYABgQQgBgMADgPQABgIAHAAQAEAAADADQACACAAAEIgBANIgBANIABAXQABALACAGIAGADIAFAAQAKAAANgDIAAgSIgBgPQAAgTACgOQABgIAIAAQADAAADACQADADgBADIgBAhIAAARIAAATIAAAGIAAAGQABAEgDACQgDADgDAAQgHAAgCgJg");
	this.shape_12.setTransform(16.7,1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAVArIgDgUIgBgTIABgHIAAgHQAAgUgHAAQgKAAgHAMQgIALgFAOIgBAJIAAAIIAAAIIABAIQAAAEgCACQgDACgEAAQgDAAgDgCQgCgCAAgEIgBgIIAAgIIABgYIABgYIAAgJIAAgIQAAgEACgCQADgCADgBQAIAAABAMIAAAKQAPgTAOgBQAOAAAFANQAEAIAAARIAAAIIAAAGIACAUQACALAAAHQAAAEgCACQgDACgEABQgHgBgBgHg");
	this.shape_13.setTransform(7.5,0.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgdAlQgNgLAAgTQAAgVALgPQAMgSATABQAOAAAJAEQALAHAAAMQAAAJgKAHQgEADgOAFIggAQQAFAHAHAEQAIAEAIAAQAGgBAIgCQAKgDADgEQADgFAEAAQADAAACACQACACAAAEQAAAJgPAIQgOAFgMAAQgSAAgNgKgAgRgWQgHAIgDAPIAbgLQAOgIAGgGQgHgGgNgBQgKAAgHAJg");
	this.shape_14.setTransform(-2.2,0.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgEAzQgCgCAAgEIgCggIgCgdQAAgJgDgGQgGADgHAHIgKALIgEAGIgBANIgBAPIAAAIIABAHQAAADgCADQgDACgEAAQgKAAAAgWIABgQIABgOIAAgOIgBgOQAAgUAJAAQADAAADADQADADAAAEIgBAFIAAAFIAAAJQAFgJAIgIQAJgHAHAAQANAAAEAOQAEgHAHgDQAHgDAIAAQAPAAAFAQQACADACAVIAGAxQABADgDADQgDACgDAAQgIAAgBgIIgDgbIgDgZQgBgGgCgGQgDgIgDAAQgEAAgJAGQgIAFgDADIABAQIACAWQACAOAAAJQAAAEgCACQgDADgEAAQgBAAgDgDg");
	this.shape_15.setTransform(-14.1,1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#000000").ss(2,1,1).p("AEah7IAAD3IozAAIAAj3g");

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#0066CC").s().p("AkZB8IAAj3IIzAAIAAD3g");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},1).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12}]},1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-29.2,-16.9,58.6,30.5);


(lib.general_buttoncolor = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{resetRed:1});

	// timeline functions:
	this.frame_0 = function() {
		this.play();
	}
	this.frame_8 = function() {
		this.gotoAndPlay("resetRed");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(8).call(this.frame_8).wait(2));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#D5FFD7","#61EF01","#1DA400","#004A00"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgvAAgjgjQgjgjAAgwQAAgvAjgjQAjgjAvAAQAwAAAjAjQAjAjAAAvQAAAwgjAjQgjAjgwAAIAAAAg");
	this.shape.setTransform(11.9,11.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FFFFFF","#EC0000","#9D0000","#480000"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgvAAgjgjQgjgjAAgwQAAgvAjgjQAjgjAvAAQAwAAAjAjQAjAjAAAvQAAAwgjAjQgjAjgwAAIAAAAg");
	this.shape_1.setTransform(11.9,11.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},8).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,23.7,23.6);


(lib.Copyright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAbAHIgDgKIgEAKQgEAIgDAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBgBAAgBIgCgIIgBgHQgGASgCAAIgDgBIgBgCIABgCQADgFABgFIACgNQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAEAAACAJIADAKIACgGIADgJQADgEACAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAEAKIACAGIACAIIABACIgBACIgCABQgDAAgDgJgAgTANIgBgIIAAgGIgBgHIgFAAIgGAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAgBAAAAQAAgBAAgBQAAAAABgBQAAAAABgBQAAAAABAAIAFABIAEAAIAPAAIADgBIAEAAQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAABAAAAQAAAAAAABQAAAAgBAAIgOAAIAAAIIABAFIABAEIABAEIgCACIgCABQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAgBAAAAg");
	this.shape.setTransform(57.3,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgLAYQgGgDgBgEIABgDQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAIAEACIAEABIAFABIAFgBQADgBAAgDQABgGgJgCIgCgBIgIgDQgEAAAAgFQAAgKAIgEIAHgCIAIgDIAEgBIADABIABAEIABADIAAAEIgBADIgCABQgBAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIgCgFIgJADQgFADgBAEIADABQAIACAFACQAHADAAAJQAAAHgGAEQgFADgGAAQgFAAgGgCg");
	this.shape_1.setTransform(51,2.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgLATQgHgGABgKQAAgGAFgKQAHgKAGAAQAEAAAGACQAGACABAEIgBADQgBAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgDgBIgBgBQgDgCgGAAQgCAAgFAIQgDAHAAADQAAAGADAEQAEADAEAAIAGgCIAEgCIACgBIAEABIABADQgBADgGADQgGADgEAAQgHAAgGgFg");
	this.shape_2.setTransform(46.6,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgDAfQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAAAIAAgJIAAgIIAAgKIAAgIQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBIACgBIACABQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABIAAAIIgBAKIAAAIIABAJQAAAAAAAAQAAABgBAAQAAABAAAAQAAAAgBAAIgBABIgDgBgAgBgXQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQAAAAAAAAQAAAAAAgBQABABAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBAAAAgBg");
	this.shape_3.setTransform(43.1,1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAKAVIgBgJIgBgKIABgDIAAgDQAAgKgEAAQgFAAgCAFQgEAGgCAGIgBAEIAAAFIAAADIAAAFIgBADIgDABIgDgBIgBgDIAAgFIgBgDIABgMIAAgLIAAgFIAAgEIABgDIAEgBQAEAAAAAFIAAAGQAHgKAGAAQAHAAADAGQACAEAAAJIAAAEIAAACIABAKIABAJIgBADIgDABQgEAAgBgEg");
	this.shape_4.setTransform(39.5,2.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_5.setTransform(34.8,2.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AALAhIgBgLIgBgKIAAgDIAAgEQAAgGgEAAQgFAAgDADIgGAKQAAARgCACQAAABgBABQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDIABgBIAAgHIAAgHIAAgeIABgHIgBgFIAAgEQAAAAAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQAEAAAAAEIABAIIAAAKIAAAJIAAAEQADgFAEgCQACgDAFAAQAHAAADAFQABADABAGIABAJIAAAIIACAKIAAABQAAABAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIgDABQgEAAgBgDg");
	this.shape_6.setTransform(30,1.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgLATQgHgGABgKQAAgGAFgKQAHgKAGAAQAEAAAGACQAGACABAEIgBADQgBAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgDgBIgBgBQgDgCgGAAQgCAAgFAIQgDAHAAADQAAAGADAEQAEADAEAAIAGgCIAEgCIACgBIAEABIABADQgBADgGADQgGADgEAAQgHAAgGgFg");
	this.shape_7.setTransform(25,2.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgOATQgGgGAAgKQAAgKAFgHQAGgJAJAAQAGABAFACQAGADAAAHQAAAEgFADIgKAEIgOAHQACAEAEABQAEADACAAIAIgBQAFgCABgDQABAAAAAAQAAgBABAAQAAAAABAAQAAAAAAAAIADAAIABADQAAAFgIADQgGADgHABQgIgBgGgEgAgIgKQgDAEgCAGIANgFQAGgDAEgDQgEgDgGgBQgEAAgEAFg");
	this.shape_8.setTransform(20.3,2.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAaAgIgCgGIgBgIQgCgHgEgWIgJAYIgDAJIgDAIQgBAEgCAAQgDgBgBgDIgCgEIgBgFIgIgfIgCAHIgFAWIgCAMQgBAEgDAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgEQAAgHADgLIAFgPIADgOQACgKABgDQACgCADAAQACAAACADQACAEABAMQADAOAFAPQAFgPAEgSIACgGIACgHQABgDADAAQAEAAACAIIACAKQADASADAOIACAHIACAHQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgCABQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBgBg");
	this.shape_9.setTransform(13.8,1.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgQAUIAAgdIAAgEIABgFQAAgEADAAQAFAAAAAHQAHgIAKAAQADAAACADQACACAAAGIAAADQgBAFgEAAQgEAAAAgEIAAgDIAAgEQgHABgCADQgEADgDAGIABAWQAAAEgFAAQgEAAAAgEg");
	this.shape_10.setTransform(5.1,2.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_11.setTransform(0.5,2.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgBAZQAAAAgBAAQAAgBAAAAQAAAAAAgBQgBAAAAgBIgBgPIgBgOQAAgFgBgCQgDABgDADIgFAGIgDADIAAAGIgBAHIABAEIAAADQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABQgFAAAAgLIAAgIIABgGIgBgHIAAgHQAAgKAFAAIACACQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAADIgBACIAAAFQADgFAEgDQAFgEADAAQAGAAACAHQACgEADgBQAEgCAEAAQAHAAADAIIACAMIADAYIgBADIgDABQgEAAgBgEIgBgOIgCgLIgBgGQgCgEgCAAIgFADIgGAEIAAAHIABALIABALIgBADIgDACQAAAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBg");
	this.shape_12.setTransform(-5.2,2.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgBAZQAAAAgBAAQAAgBAAAAQAAAAAAgBQgBAAAAgBIgBgPIgBgOQABgFgCgCQgDABgDADIgFAGIgCADIgBAGIgBAHIABAEIABADQAAABgBAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABQgFAAAAgLIABgIIAAgGIAAgHIgBgHQAAgKAEAAIADACQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAADIgBACIAAAFQADgFAEgDQAFgEADAAQAGAAABAHQADgEADgBQADgCAFAAQAHAAADAIIACAMIADAYIgCADIgCABQgEAAgBgEIgCgOIgBgLIgBgGQgCgEgCAAIgFADIgGAEIAAAHIABALIABALIgBADIgDACQAAAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBg");
	this.shape_13.setTransform(-12.2,2.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_14.setTransform(-18.1,2.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgQAUIAAgdIAAgEIABgFQAAgEADAAQAFAAAAAHQAHgIAKAAQADAAACADQACACAAAGIAAADQgBAFgEAAQgEAAAAgEIAAgDIAAgEQgHABgCADQgEADgDAGIABAWQAAAEgFAAQgEAAAAgEg");
	this.shape_15.setTransform(-22.4,2.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgVAeQgFgGgBgMQABgMAFgKQAFgMAIgIQAHgEAEAAQAEAAAGACQAIAEAAADIgBADIgEABIgCgBQgHgDgEAAQgDgBgCAEIgGAGQgKAOAAAOQABAIACADQACAEAIAAQAGgBAGgFQAGgEACgLQgMABgGAEIgDABQAAgBAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQAIgEAXAAIADABIABACQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQgDANgIAJQgJAHgKABQgKgBgGgFg");
	this.shape_16.setTransform(-27.7,1.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgNAhIgBgDIACgJIAKgWQAFgOAHgIIABgBIgVAAIgJgBQgFAAAAgEQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAQAAIAPABIAIAAQAFAAAAACQAAADgDADIgEAFQgGAGgFAKIgHAPIgCAKIgEAKQgBABAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIgDgBg");
	this.shape_17.setTransform(-36.2,1.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AABAiIgHAAIgFgBQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQgBgEAIAAIACAAIABAAIAAgHIgBgGIABgPIABgRQgFAFgCAAIgDgBIgBgDQAAgDADgCIAHgGQACgEAEAAQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAADIAAADIAAAEIAAAEIgBAPIgBANIAAAGIABAGIAFAAQAAAAAAAAQABAAAAABQABAAAAAAQAAAAABABIAAADIAAADIgDABg");
	this.shape_18.setTransform(-41,1.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgSAXQgFgKAAgNQAAgMAGgKQAHgMAKAAQAMABAGAJQAGAJAAANQAAARgGAKQgGAJgMAAQgMABgGgMgAgLgRQgEAIAAAJQAAAMAEAHQAEAHAHAAQAIABAEgLQADgIAAgJQAAgMgDgGQgEgGgIAAQgGAAgFAIg");
	this.shape_19.setTransform(-45.9,1.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AANAhIgDgBIgHAAIgFABIgFAAIgFAAIgBAAIgCAAQgDAAgBgDIAAgFQAAgKAGgHQACgDALgFIAHgHQADgEAAgGQAAgDgDgCQgDgCgDAAQgDAAgDADIgGAEIgDACQgFAAAAgEQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAFgFAEgCQAFgDAEAAQAHAAAFAEQAGAEAAAHIgBAIIgEAHQgDACgIAFQgGAFgDADQgFAFABAHIAJgBIALAAIAGABQAEABAAADQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAIgDABIgDAAg");
	this.shape_20.setTransform(-51.3,1.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgeAAQAAgKALgJQALgKALAAQAOAAAHAIQAHAIAAAMQAAAJgJAKQgKALgMAAIAAABQgeAAAAgegAgOgOQgIAGAAAIQAAAMAGAFQAGAEAKAAQAJAAAIgIQAGgIAAgGQAAgJgEgFQgFgGgIAAIgCAAQgKAAgIAHgAgKAJQgGgEAAgFQAAgGAIgFQAGgFAFAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAIgCgBIgBAAQgDAAgEADQgEACAAADQAAABADACIAFABQABAAAEgCIAEgCIADAAIABADQAAADgEADQgGADgDAAQgFAAgFgDg");
	this.shape_21.setTransform(-57.7,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.3,-7.1,126.6,16.6);


(lib.MicStill = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.1,1,1).p("ACzANIlkgZ");
	this.shape.setTransform(36.5,53.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AD+j9QBqBpAACUQAACVhqBpQhpBqiVAAQiUAAhphqQhqhpAAiVQAAiUBqhpQBphqCUAAQCVAABpBqg");
	this.shape_1.setTransform(36,36);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(0.1,1,1).p("Ah9gYQgHgEgCgKQgDgJgDgJQgDgJABgKQAAgFABgEQAAgFAAgEQgBgDgBgEQgBgKAAgJQABgKAFgIQAFgIAIgFQAIgFAHgGQAIgFAKgCQAIgCAJABQAJACAKABQAKAAAJAEQAKADAGAEQAHgGAHgHQAHgHAHgCQAJgCAIgDQAKgDAJgDQAIgEAKAAQAKAAAJACQAJABAHAGQAHAHAIAFQAHAGAFAIQAFAGACAHQACAFABAFQACAJACAJQADAKACAJQACAKgCAJQgBAJgDAJQgEAKgEAHQgBACgCAAQgFgIgIgFQgEgDgEgBQgJgBgCgKQABgCACgCAgxiTQgJgBgJAFQgJAEgHAGQgIAHgEAJQgDAIAAAKQAAAKgCAJQgBAJABAKAgciZQgGgCgKgCQgJgDgKABQgJAAgJABQgJABgIAGQgHAGgFAIQgGAHgEAIQgEAIAAAJQAAAKAAAKQAAAFAAABAhfgoQgGgFgGABQgIAAgEAGQgFAGgBAIAhYgfQgBgJABgIQACAFACAFQAEALAIAGQgCgHgBgIQgCgJgBgJQgBgJAAgJQAAgKACgKQABgIAGgIQAFgHAIgHQAGgGAHgFQAIgFAKgCQAKgCAFALQABgHAKgDQAGgCAKgBQAJgBAKABQAKABAJACQAJACAIAGQAIAFAGAIQAFAIAEAJQAEAIgCAKQgCAJgEAJQgBADgBADQABgCACgCQACgCACgCAhYgfQgCgFgEgEQgBAAAAAAQAFAHACAGQAAgCAAgCgAgFiVQAFgFAIgFQAHgHAJgCQAKgDAJgBQAKgCAJACQAKACAIADQAJAEAIAEQAIAEAFAHQAFAHADAIQAEAJABAKQABAKgBAJQAAADAAADAAyihQAJgDAJAGQAIAEAHAFQAIAGAHAGQAGAGAFAIQAEAIACAJQACAKAAAKAghhfQgHgGgKAFQgJAFgBAIQAAAEABADAgXhKQgCgCgEAAQgKABgFAJQgEAIADAKQACAJAGAGQAHAHAKgBQAJAAAFgFQADgDAAgIQAAgBAAgBQAAgJgFgGQAAgBgBAAQgCgEgCgDQgCgDgCgCQgCgCgEABgAgDgtQAAABgBAAQgCABgBAAQgMABgBgIQgCgMANABAgNhEQgFgEgFgCAAShvQAFgIALACQAGABACAEABChOQAAgDAAgCQAAgEgDgEQgFgFgCAEQgKAAgHAGQgGAHgBAJQgBALAHAEQAIAFAJgDQAJgCACgJQgGABgBgDQgEgNALABgABChAQABgHgBgHAAEgdQAAAKAIAFQAGAFAIgBQAJAAAJgCQAJgCAIgDQAJgDgBgLQgBgHgHgDQgIgDgKABQgDAAgDAAAB/gpQAAAFACAFQABAEgBAEQAAAJgDAJQgEAGgDAJQgCAJgCAJQgBAKgBAJQgBALgFAJQAAADAAAEQAAABAAACQgBAKgHAGQgHAHgHADQgJAEgHAEQgIAEgJAAAAyCCQAFAHALABQAGABAFACQAJADAJACQAIADAIACQAJADAIAEQAIAEAHAFQAHAFAHAFQAGAGAHAEQAEADAFADABkAKQgFAHgIAGQgIAFgIADQgJAEgIAFQgIAEgKAAQgJABgKAAQgKgBgHgCQgJgCgIgFQgIgFgHgFQgHgGgEgGQgCADgBADQAAAEABACAgrANQACgEAGgBAhQAkQAAABABAAQAEAJAEAJQAEAJAEAHQAEAIAGAGQAHAHAIAGQAHAGAJAEQAJADAJACQAIACAKAAQAKAAAJAAQAJAAAIAAQABAAABAAIAAABQgCAGAAAIQAAACABACQABAKAEAIAhVAVQADgCADgEQAEgGgBgJAhVAVQgEADgFABQgFAAgEgCQgIgGgEgHQgFgHgDgHQgDgJABgLAhQAkQAAAAAAgBQgEgHgBgHAixClQAIgEAKgDQAIgDAJgCQAHgCAHgBQAJgBAKgDQAJgDAJgDQAJgDAEgHQAFgJgBgKQAAgJgBgKQAAgKgCgJQgBgJABgKQAAgJgDgIQAAAAAAgB");
	this.shape_2.setTransform(36.5,35.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgrAKQgCgKAOAAIAAAAQAFAGAAAJIAAABIgEABIgBAAQgLAAgBgHgAAkgEQgEgNAMABQAAAHgBAHIgCAAQgEAAgBgCg");
	this.shape_3.setTransform(38.8,29.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AguAbQgGgGgDgJQgCgKAEgGQAEgJALgBIAGABQAFADAEAEIAFAGQgNAAACAKQABAIALgBIAEgBIABABQAAAIgEADQgFAFgIAAIgCAAQgJAAgGgGgAAcAFQgHgEABgJQABgJAHgHQAGgGALAAQACgEAEAFQADAEABAEIAAAFQgLgBAEANQABADAFgBQgBAHgJACIgHABQgGAAgFgDg");
	this.shape_4.setTransform(37.4,29.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFCC97").s().p("AixCOQAHgFALgDIARgFIAOgDQAJgBAJgDIASgGQAKgDAEgHQAFgIgBgKIgBgUIgCgSQgBgKAAgKQABgJgDgHIABAAIAIARIAIARQAEAHAGAHIAOANQAIAGAJADIASAGIAHABIAGAAIABAAIAAAAIABAAIACAAIAUAAIARABIACAAIAAAAQgCAHAAAIQAFAGALACIALACIASAGIAPAFQAKACAIAFQAHADAIAFIANALQAHAFAHAEIAJAGgAAyBuQACAKAEAJQgEgJgCgKIAAgDIAAADgAAyBcIgRgBIgUAAIgCAAIgBAAIAAAAIgBAAIgGAAIgHgBIgSgGQgJgDgIgGIgOgNQgGgHgEgHIgIgRIgIgRIgBgCIAAAAQgEgHgBgFIAGgGQADgFAAgHIgBgEIABAEQAAAHgDAFIgGAGQgEABgFAAQgFABgEgCQgIgEgEgIQgFgHgDgJQgDgIABgMQABgIAEgGQAFgFAIgBQAGAAAGAEQAFAHACAGIAAgEQgBgJABgIIAEAKQAEALAIAHIgEgPIgCgTIgBgSQgBgKACgJQACgJAGgHQAFgIAHgHIAOgKQAIgFAKgCQAKgCAFAKQABgHAKgCQAGgDAKgBIATAAIATADQAJACAIAGQAIAGAFAIIAJAQQAFAJgDAKIgFASIgCAFIADgEIADgDQACAJAKACIAIADQAIAGAFAIIABAKIABAIQAAAJgDAIIgHASIgEAQIgCATQgBAKgFAKIAAAGIAAAEQgBAJgHAHQgHAGgIAEIgQAIQgHAEgJAAIgBAAIgBAAgAghABIAQALQAHAFAKACQAHACAKAAIATAAQAJAAAJgFIARgIQAIgEAHgEQAJgFAFgGQgFAGgJAFQgHAEgIAEIgRAIQgJAFgJAAIgTAAQgKAAgHgCQgKgCgHgFIgQgLQgHgDgDgHQACgDAGgCQgGACgCADQgCADgBAEIAAACIABACIgBgCIAAgCQABgEACgDQADAHAHADgAAZghIAAAAIABAAIASgCIARgFQAIgDAAgJIgBgCQAAgIgHgCIgBgBQgHgCgHAAIgBAAIAAAAIgBAAIgBAAIgGAAIAGAAIABAAIABAAIAAAAIABAAQAHAAAHACIABABQAHACAAAIIABACQAAAJgIADIgRAFIgSACIgBAAIAAAAIgBAAIAAAAQgGAAgFgEIgBAAQgIgGAAgJQAAAJAIAGIABAAQAFAEAGAAIAAAAIABAAgAgshaQgEAJADAKQACAJAGAGQAGAGALAAQAJgBAFgEQADgEAAgHIAAgCQAAgKgFgGIgBgBIgEgGIgEgGQgCgCgEABIgGgBQgKAAgFAJgAA4h0QgLABgGAGQgHAGgBAKQgBAKAIAFQAIAEAJgCQAJgDABgIQACgIgBgHIAAgFQAAgDgDgEQgDgEgCAAQAAAAAAABQgBAAAAAAQAAAAgBAAQAAABAAAAgAg8hjIAAgFIAAgCQAAgJAKgFIAAAAIAHgCIABAAIAAAAQAEAAADACIACABIgCgBQgDgCgEAAIAAAAIgBAAIgHACIAAAAQgKAFAAAJIAAACIAAAFgAASiGQAEgHAHAAIABAAIAAAAIABAAIABAAIABAAIABAAQAFACACADQgCgDgFgCIgBAAIgBAAIgBAAIgBAAIAAAAIgBAAQgHAAgEAHgAgrgJIAAAAg");
	this.shape_5.setTransform(36.5,37.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FEFF97").s().p("AhTBEIgEgKQgBAIABAIQgCgFgEgDIgBAAQgGgFgGABQgIAAgEAGQgFAGgBAIQgHgEgCgKIgGgSQgCgJAAgKIABgJIAAgJIgBgHQgCgIAAgJQABgKAFgIQAFgIAIgFIAPgLQAIgFAKgCQAIgCAJABIATADQAKAAAJAEQAKADAGAEQAHgGAHgHQAGgHAIgCIARgFIATgGQAIgEAKAAQAKAAAJACQAJABAHAGIAPAMQAHAGAFAIQAFAGACAHIADAKIAEASIAFARQACAKgCAJQgBAJgDAJIgIARIgDACQgFgIgIgFIgIgEQgJgBgCgKIADgEIgDAEIgEAEIgBgCIAGgSQACgKgEgIIgJgPQgGgIgIgFQgIgGgJgCIgTgDIgTAAQgKABgHACQgIADgCAGQgFgKgKACQgKACgIAFIgNALQgIAHgFAHQgGAGgBAIQgCAKAAAKIABASIADASIADAPQgIgGgEgLgAhjAtIAAgHIAAgMQACgJAAgKQAAgIADgIQAEgJAIgHQAHgGAJgEIAAgBQAHgDAHgBIABAAIAAAAIABAAIACABIgCgBIgBAAIAAAAIgBAAQgHABgHADIAAABQgJAEgHAGQgIAHgEAJQgDAIAAAIQAAAKgCAJIAAAMIAAAHgAg+gzIgSABQgJABgIAGQgHAGgFAIQgGAHgEAIQgEAIAAAHIAAAUIAAAGIAAgGIAAgUQAAgHAEgIQAEgIAGgHQAFgIAHgGQAIgGAJgBIASgBIACgBIABAAIABAAIAAAAIANACIACABIAQAEIgQgEIgCgBIgNgCIAAAAIgBAAIgBAAIgCABIAAAAgAB2AUIAAgEQAAgIgCgIQgCgHgEgIQgFgIgGgGIgPgMIgPgJIgCgCQgFgCgFAAIAAAAIgBAAIgFABIAFgBIABAAIAAAAQAFAAAFACIACACIAPAJIAPAMQAGAGAFAIQAEAIACAHQACAIAAAIIAAAEgAB8ALIAAAGIAAgGIABgIIgBgJQgBgKgEgJQgDgIgFgHQgFgHgIgEIgRgIQgIgDgKgCQgJgCgKACIgTAEQgJACgHAHIgNAKIANgKQAHgHAJgCIATgEQAKgCAJACQAKACAIADIARAIQAIAEAFAHQAFAHADAIQAEAJABAKIABAJIgBAIg");
	this.shape_6.setTransform(36.4,24.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0000FF").s().p("Aj9D+QhphqgBiUQABiUBphpQBphqCUAAQCUAABqBqQBqBpgBCUQABCUhqBqQhqBpiUAAQiUAAhphpgAhJAxQAAAKABAJIACATIABATQABAKgFAJQgEAHgKADIgSAGQgJADgJABIgOADIgRAFQgLADgHAEIFkAcIgJgGQgHgEgHgFIgNgLQgIgFgHgEQgIgEgKgCIgPgGIgSgFIgLgDQgLgBgFgHQAAgHACgHIAAAAQAJAAAHgFIAQgIQAIgDAHgHQAHgGABgKIAAgDIAAgHQAFgJABgLIACgTIAEgSIAHgPQADgIAAgKIgBgIIgBgKIACgBIAIgSQAEgJABgJQABgJgBgJIgFgTIgEgSIgDgKQgDgIgEgGQgFgIgIgFIgPgNQgHgFgIgCQgJgCgKAAQgKAAgIAEIgTAGIgRAFQgKADgEAGQgHAHgIAGQgFgEgLgDQgIgDgKgBIgUgCQgIgCgJACQgJACgIAGIgPAKQgJAFgEAIQgFAIgBAKQAAAKACAKIABAGIAAAJIgBAJQgBAKADAJIAGASQACALAHADQgBALADAJQADAJAFAFQAEAHAIAGQAEACAFAAQAFgBAEgDQABAIAEAHIAAAAIAAABIAAgBIABABIgBAAQADAIgBAJgAhagtIAAAAQAFAEACAFIAAAEQgCgGgFgHgAAAgxIAAAAIAAACgABfhIIABACIgDAEIACgGgAgShPQAEgBACACIAEAFQgFgEgFgCg");
	this.shape_7.setTransform(36,36);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,74,74);


(lib.micktalk = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.1,1,1).p("ACzANIllgZ");
	this.shape.setTransform(0.5,18.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(0.1,1,1).p("Ah+gYQgGgEgDgKQgCgJgDgJQgDgJABgKQAAgFAAgEQABgFAAgEQgBgDgBgEQgCgKABgJQABgKAFgIQAEgIAIgFQAIgFAIgGQAIgFAJgCQAJgCAIABQAKACAKABQAJAAAJAEQAKADAGAEQAIgGAHgHQAGgHAIgCQAJgCAIgDQAKgDAJgDQAIgEAKAAQAKAAAJACQAJABAHAGQAHAHAIAFQAHAGAFAIQAFAGACAHQACAFABAFQACAJACAJQADAKACAJQACAKgCAJQgBAJgDAJQgEAKgEAHQgBACgCAAQAAAFACAFQABAEgBAEQAAAJgDAJQgEAGgDAJQgCAJgCAJQgBAKgBAJQgBALgFAJQAAADAAAEQAAABAAACQgBAKgHAGQgHAHgHADQgJAEgHAEQgIAEgJAAIAAABQgCAGAAAIQAFAHALABQAGABAFACQAJADAJACQAIADAIACQAJADAIAEQAIAEAHAFQAHAFAHAFQAGAGAHAEQAEADAFADAgFiVQAFgFAIgFQAHgHAJgCQAKgDAJgBQAKgCAJACQAKACAIADQAJAEAIAEQAIAEAFAHQAFAHADAIQAEAJABAKQABAKgBAJQAAADAAADAhZgfQAAgJABgIQACAFACAFQAEALAHAGQgCgHgBgIQgBgJgBgJQgBgJAAgJQgBgKACgKQACgIAFgIQAGgHAHgHQAHgGAHgFQAIgFAJgCQALgCAFALQABgHAJgDQAHgCAKgBQAJgBAKABQAKABAJACQAJACAIAGQAIAFAGAIQAFAIAEAJQAEAIgCAKQgCAJgEAJQgBADgBADQABgCACgCQACgCACgCAAyihQAJgDAJAGQAIAEAHAFQAIAGAHAGQAGAGAFAIQAEAIACAJQACAKAAAKABChAQgCAJgJACQgJADgIgFQgHgEABgLQABgJAGgHQAHgGAKAAQACgEAFAFQADAEAAAEQAAACAAADQABAHgBAHQgGABgBgDQgEgNALABAAShvQAFgIALACQAGABACAEAAEgdQAAAKAIAFQAGAFAIgBQAJAAAJgCQAJgCAIgDQAJgDgBgLQgBgHgHgDQgIgDgKABQgDAAgDAAAgXhKQgCgCgEAAQgLABgEAJQgEAIACAKQADAJAGAGQAGAHALgBQAIAAAFgFQAEgDAAgIQAAgBAAgBQAAABgBAAQgCABgCAAQgLABgBgIQgCgMANABAB/gpQgFgIgIgFQgEgDgEgBQgJgBgCgKQABgCACgCAgyiTQgJgBgJAFQgIAEgIAGQgIAHgDAJQgEAIAAAKQAAAKgBAJQgBAJAAAKAgciZQgHgCgJgCQgJgDgKABQgJAAgKABQgJABgHAGQgHAGgGAIQgGAHgEAIQgDAIAAAJQAAAKAAAKQAAAFAAABAhVAVQgEADgFABQgFAAgEgCQgIgGgFgHQgEgHgDgHQgDgJAAgLAhfgoQgGgFgHABQgHAAgFAGQgFAGgBAIAgXhKQAFACAFAEQgCgDgDgCQgBgCgEABgAgihfQgHgGgKAFQgJAFAAAIQgBAEABADAhZgfQgBgFgFgEQAAAAAAAAQAFAHACAGQAAgCgBgCgAgDgtQAAgJgFgGQAAgBgBAAAgNhEQACADACAEAgsANQgBADgBADQgBAEABACAgsANQAEAGAHAGQAIAFAIAFQAHAFAKACQAHACAKABQAKAAAJgBQAKAAAIgEQAIgFAJgEQAIgDAIgFQAIgGAFgHAgjAIQgGABgDAEAhVAVQADgCACgEQAFgGgCgJAhQAkQAAABAAAAQAFAJADAJQAEAJAFAHQAEAIAGAGQAHAHAHAGQAIAGAJAEQAIADAKACQAIACAKAAQAKAAAJAAQAJAAAIAAQABAAABAAAhQAkQAAAAgBgBQgDgHgBgHAiyClQAIgEAKgDQAJgDAJgCQAHgCAHgBQAJgBAJgDQAJgDAJgDQAKgDAEgHQAEgJAAgKQAAgJgBgKQgBgKgBgJQgBgJAAgKQABgJgDgIQAAAAAAgBAAyCCQAAACABACQABAKAEAI");
	this.shape_1.setTransform(0.5,0.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgrAKQgCgKAOAAIAAAAQAFAGAAAJIAAABIgEABIgBAAQgLAAgBgHgAAkgEQgEgNAMABQAAAHgBAHIgCAAQgEAAgBgCg");
	this.shape_2.setTransform(2.8,-5.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AguAbQgGgGgDgJQgCgKAEgGQAEgJALgBIAGABQAFADAEAEIAFAGQgNAAACAKQABAIALgBIAEgBIABABQAAAIgEADQgFAFgIAAIgCAAQgJAAgGgGgAAcAFQgHgEABgJQABgJAHgHQAGgGALAAQACgEAEAFQADAEABAEIAAAFQgLgBAEANQABADAFgBQgBAHgJACIgHABQgGAAgFgDg");
	this.shape_3.setTransform(1.4,-5.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFCC97").s().p("AixCOQAHgFALgDIARgFIAOgDQAJgBAJgDIASgGQAKgDAEgHQAFgIgBgKIgBgUIgCgSQgBgKABgKQAAgJgDgHIABAAIAHARIAJARQAEAHAGAHIAOANQAIAGAJADIASAGIABAAIAMABIABAAIAAAAIACAAIABAAIAUAAIARABIACAAIAAAAQgCAHAAAIQAFAGALACIALACIASAGIAQAFQAJACAIAFQAIADAGAFIAOALQAGAFAHAEIAJAGgAAyBuQABAKAFAJQgFgJgBgKIAAgDIAAADgAAyBcIgRgBIgUAAIgBAAIgCAAIAAAAIgBAAIgMgBIgBAAIgSgGQgJgDgIgGIgOgNQgGgHgEgHIgJgRIgHgRIgBgCIgBAAQgDgHgBgFIAGgGQADgFAAgHIAAgEIAAAEQAAAHgDAFIgGAGQgEABgFAAQgFABgEgCQgIgEgEgIQgFgHgDgJQgDgIAAgMQACgIAEgGQAFgFAHgBQAHAAAGAEQAFAHACAGIAAgEQgBgJABgIIAEAKQAEALAHAHIgDgPIgCgTIgBgSQAAgKACgJQABgJAGgHQAFgIAHgHIAOgKQAIgFAJgCQALgCAFAKQABgHAJgCQAHgDAJgBIAUAAIATADQAJACAIAGQAIAGAGAIIAIAQQAEAJgCAKIgFASIgDAFIAEgEIADgDQACAJAKACIAIADQAIAGAFAIIACAKQAAAEAAAEQAAAJgDAIIgHASIgEAQIgCATQgBAKgFAKIAAAGIgBAEQAAAJgHAHQgHAGgHAEIgRAIQgHAEgJAAIgBAAIgBAAgAggABIAPALQAIAFAJACQAHACAJAAIAUAAQAKAAAIgFIAQgIQAJgEAHgEQAIgFAGgGQgGAGgIAFQgHAEgJAEIgQAIQgIAFgKAAIgUAAQgJAAgHgCQgJgCgIgFIgPgLQgIgDgDgHQACgDAGgCQgGACgCADQgCADgBAEIAAACIAAACIAAgCIAAgCQABgEACgDQADAHAIADgAAZghIABAAIARgCIASgFQAIgDAAgJIgBgCQAAgIgHgCIgBgBQgHgCgHAAIgBAAIAAAAIgBAAIgCAAIgFAAIAFAAIACAAIABAAIAAAAIABAAQAHAAAHACIABABQAHACAAAIIABACQAAAJgIADIgSAFIgRACIgBAAIgBAAIAAAAQgHgBgFgDQgIgGAAgJQAAAJAIAGQAFADAHABIAAAAIABAAgAgshaQgEAJACAKQADAJAGAGQAGAGALAAQAIgBAGgEQADgEAAgHIAAgCQAAgKgFgGIgBgBIgEgGIgFgGQgBgCgEABIgGgBQgLAAgEAJgAA4h0QgKABgHAGQgGAGgCAKQgBAKAIAFQAIAEAJgCQAJgDACgIQABgIgBgHIAAgFQgBgDgCgEQgDgEgCAAQAAAAAAABQgBAAAAAAQAAAAgBAAQAAABAAAAgAg7hjIgBgFIAAgCQAAgJAKgFIABAAIAGgCIABAAIAAAAQAFAAAEADQgEgDgFAAIAAAAIgBAAIgGACIgBAAQgKAFAAAJIAAACIABAFgAASiGIAAgBIABgBQAEgFAGAAIABAAIAAAAIAAAAIABAAIACAAQAHACABADQgBgDgHgCIgCAAIgBAAIAAAAIAAAAIgBAAQgGAAgEAFIgBABIAAABg");
	this.shape_4.setTransform(0.5,2.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FEFF97").s().p("AhTBEIgEgKQgBAIABAIQgCgFgEgDIgBAAQgGgFgGABQgIAAgEAGQgFAGgBAIQgHgEgCgKIgGgSQgCgJAAgKIABgJIAAgJIgBgHQgCgIAAgJQABgKAFgIQAFgIAIgFIAPgLQAIgFAKgCQAIgCAJABIATADQAKAAAJAEQAKADAGAEQAHgGAHgHQAGgHAIgCIARgFIATgGQAIgEAKAAQAKAAAJACQAJABAHAGIAPAMQAHAGAFAIQAFAGACAHIADAKIAEASIAFARQACAKgCAJQgBAJgDAJIgIARIgDACQgFgIgIgFIgIgEQgJgBgCgKIADgEIgDAEIgEAEIgBgCIAGgSQACgKgEgIIgJgPQgGgIgIgFQgIgGgJgCIgTgDIgTAAQgKABgHACQgIADgCAGQgFgKgKACQgKACgIAFIgNALQgIAHgFAHQgGAGgBAIQgCAKAAAKIABASIADASIADAPQgIgGgEgLgAhjAtIAAgHIAAgMQACgJAAgKQAAgIADgIQAEgJAIgHQAHgGAJgEQAHgEAHgBIABAAIAAAAIABAAIACABIgCgBIgBAAIAAAAIgBAAQgHABgHAEQgJAEgHAGQgIAHgEAJQgDAIAAAIQAAAKgCAJIAAAMIAAAHgAg+gzIgSABQgJABgIAGQgHAGgFAIQgGAHgEAIQgEAIAAAHIAAAUIAAAGIAAgGIAAgUQAAgHAEgIQAEgIAGgHQAFgIAHgGQAIgGAJgBIASgBIACgBIABAAIABAAIABAAQAHABAGABIABABIAQAEIgQgEIgBgBQgGgBgHgBIgBAAIgBAAIgBAAIgCABIAAAAgAB2AUIAAgEQAAgIgCgIQgCgHgEgIQgFgIgGgGIgPgMIgPgJQgGgEgGAAIgCAAIgEABIAEgBIACAAQAGAAAGAEIAPAJIAPAMQAGAGAFAIQAEAIACAHQACAIAAAIIAAAEgAB8ALIAAAGIAAgGIABgIIgBgJQgBgKgEgJQgDgIgFgHQgFgHgIgEIgRgIQgIgDgKgCQgJgCgKACIgTAEQgJACgHAHIgNAKIANgKQAHgHAJgCIATgEQAKgCAJACQAKACAIADIARAIQAIAEAFAHQAFAHADAIQAEAJABAKIABAJIgBAIg");
	this.shape_5.setTransform(0.4,-10.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(0.1,1,1).p("AgFiVQAFgFAIgFQAHgHAJgCQAKgDAJgBQAKgCAJACQAKACAIADQAJAEAIAEQAIAEAFAHQAFAHADAIQAEAJABAKQABAKgBAJQAAADAAADAh+gYQgGgEgDgKQgCgJgDgJQgDgJABgKQAAgFAAgEQABgFAAgEQgBgDgBgEQgCgKABgJQABgKAFgIQAEgIAIgFQAIgFAIgGQAIgFAJgCQAJgCAIABQAKACAKABQAJAAAJAEQAKADAGAEQAIgGAHgHQAGgHAIgCQAJgCAIgDQAKgDAJgDQAIgEAKAAQAKAAAJACQAJABAHAGQAHAHAIAFQAHAGAFAIQAFAGACAHQACAFABAFQACAJACAJQADAKACAJQACAKgCAJQgBAJgDAJQgEAKgEAHQgBACgCAAQAAAFACAFQABAEgBAEQAAAJgDAJQgEAGgDAJQgCAJgCAJQgBAKgBAJQgBALgFAJQAAADAAAEQAAABAAACQgBAKgHAGQgHAHgHADQgJAEgHAEQgIAEgJAAQgBAAgBAAQgIAAgJAAQgJAAgKAAQgKAAgIgCQgKgCgIgDQgJgEgIgGQgHgGgHgHQgGgGgEgIQgFgHgEgJQgDgJgFgJQAAAAAAgBQAAAAgBgBQgDgHgBgHQgEADgFABQgFAAgEgCQgIgGgFgHQgEgHgDgHQgDgJAAgLgAhZgfQAAgJABgIQACAFACAFQAEALAHAGQgCgHgBgIQgBgJgBgJQgBgJAAgJQgBgKACgKQACgIAFgIQAGgHAHgHQAHgGAHgFQAIgFAJgCQALgCAFALQABgHAJgDQAHgCAKgBQAJgBAKABQAKABAJACQAJACAIAGQAIAFAGAIQAFAIAEAJQAEAIgCAKQgCAJgEAJQgBADgBADQABgCACgCQACgCACgCAAyihQAJgDAJAGQAIAEAHAFQAIAGAHAGQAGAGAFAIQAEAIACAJQACAKAAAKABChAQgCAJgJACQgJADgIgFQgHgEABgLQABgJAGgHQAHgGAKAAQACgEAFAFQADAEAAAEQAAACAAADQABAHgBAHQgGABgBgDQgEgNALABAAShvQAFgIALACQAGABACAEAgXhKQgCgCgEAAQgLABgEAJQgEAIACAKQADAJAGAGQAGAHALgBQAIAAAFgFQAEgDAAgIQAAgBAAgBQAAABgBAAQgCABgCAAQgLABgBgIQgCgMANABAAEgdQAAAKAIAFQAGAFAIgBQAJAAAJgCQAJgCAIgDQAJgDgBgLQgBgHgHgDQgIgDgKABQgDAAgDAAAB/gpQgFgIgIgFQgEgDgEgBQgJgBgCgKQABgCACgCAgciZQgHgCgJgCQgJgDgKABQgJAAgKABQgJABgHAGQgHAGgGAIQgGAHgEAIQgDAIAAAJQAAAKAAAKQAAAFAAABAgyiTQgJgBgJAFQgIAEgIAGQgIAHgDAJQgEAIAAAKQAAAKgBAJQgBAJAAAKAhfgoQgGgFgHABQgHAAgFAGQgFAGgBAIAgihfQgHgGgKAFQgJAFAAAIQgBAEABADAgXhKQAFACAFAEQgCgDgDgCQgBgCgEABgAhZgfQgBgFgFgEQAAAAAAAAQAFAHACAGQAAgCgBgCgAgDgtQAAgJgFgGQAAgBgBAAQgCgEgCgDAhVAVQADgCACgEQAFgGgCgJAAyCCQAFAHALABQAGABAFACQAJADAJACQAIADAIACQAJADAIAEQAIAEAHAFQAHAFAHAFQAGAGAHAEQAEADAFADIllgcQAIgEAKgDQAJgDAJgCQAHgCAHgBQAJgBAJgDQAJgDAJgDQAKgDAEgHQAEgJAAgKQAAgJgBgKQgBgKgBgJQgBgJAAgKQABgJgDgIQAAAAAAgBAAIA3QAIAKAWgCQAlgDAAgeQgbgLgfAJQgZAIAQATgAA0BzIAAABQgCAGAAAIQAAACABACQABAKAEAI");
	this.shape_6.setTransform(0.5,0.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgEBHQgRgTAYgIQAfgKAbAMQAAAeglADIgHAAQgQAAgFgIgAgzgRQgGgGgCgJQgDgKAEgIQAFgJAKgBIAHABQAFADAEAEIAFAGQgOAAACAMQABAIAMgBIAEgBIAAABQAAAIgDADQgFAFgJAAIgBAAQgJAAgHgGgAAYgnQgHgEABgLQABgJAGgHQAHgGAKAAQACgEAFAFQADAEAAAEIABAFQgMgBAEANQABADAGgBQgCAJgJACIgGABQgGAAgFgDg");
	this.shape_7.setTransform(1.9,-1.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFCC97").s().p("AixCOQAHgFALgDIARgFIAOgDQAJgBAJgDIASgGQAKgDAEgHQAFgIgBgKIgBgUIgCgSQgBgKABgKQAAgJgDgHIABAAIgBgCIgBAAQgDgHgBgFIAGgGQADgFAAgHIAAgEIAAAEQAAAHgDAFIgGAGQgEABgFAAQgFABgEgCQgIgEgEgIQgFgHgDgJQgDgIAAgMQACgIAEgGQAFgFAHgBQAHAAAGAEQAFAHACAGIAAgEQgBgJABgIIAEAKQAEALAHAHIgDgPIgCgTIgBgSQAAgKACgJQABgJAGgHQAFgIAHgHIAOgKQAIgFAJgCQALgCAFAKQABgHAJgCQAHgDAJgBIAUAAIATADQAJACAIAGQAIAGAGAIIAIAQQAEAJgCAKIgFASIgDAFIAEgEIADgDQACAJAKACIAIADQAIAGAFAIIACAKQAAAEAAAEQAAAJgDAIIgHASIgEAQIgCATQgBAKgFAKIAAAGIgBAEQAAAJgHAHQgHAGgHAEIgRAIQgHAEgJAAIgBAAIgBAAIgRgBIgUAAIgBAAIgCAAIAAAAIgBAAIgMgBIgBAAIgSgGQgJgDgIgGIgOgNQgGgHgEgHIgJgRIgHgRIAHARIAJARQAEAHAGAHIAOANQAIAGAJADIASAGIABAAIAMABIABAAIAAAAIACAAIABAAIAUAAIARABIABAAIABAAIAAAAQgCAHAAAIQAFAGALACIALACIASAGIAQAFQAJACAIAFQAIADAGAFIAOALQAGAFAHAEIAJAGgAAyBuQABAKAFAJQgFgJgBgKIAAgDIAAADgAARAEQgZAIAPATQAJAKAWgCQAlgDAAgeQgPgGgQAAQgNAAgOAEgAAZghIABAAIARgCIASgFQAIgDAAgJIgBgCQAAgIgHgCIgBgBQgHgCgHAAIgBAAIAAAAIgBAAIgCAAIgFAAIAFAAIACAAIABAAIAAAAIABAAQAHAAAHACIABABQAHACAAAIIABACQAAAJgIADIgSAFIgRACIgBAAIgBAAIAAAAQgHgBgFgDQgIgGAAgJQAAAJAIAGQAFADAHABIAAAAIABAAgAgshaQgEAJACAKQADAJAGAGQAGAGALAAQAIgBAGgEQADgEAAgHIAAgCQAAgKgFgGIgBgBIgEgGIgFgGQgBgCgEABIgGgBQgLAAgEAJgAA4h0QgKABgHAGQgGAGgCAKQgBAKAIAFQAIAEAJgCQAJgDACgIQABgIgBgHIAAgFQgBgDgCgEQgDgEgCAAQAAAAAAABQgBAAAAAAQAAAAgBAAQAAABAAAAgAg7hjIgBgFIAAgCQAAgJAKgFIABAAIAGgCIABAAIAAAAQAFAAAEADQgEgDgFAAIAAAAIgBAAIgGACIgBAAQgKAFAAAJIAAACIABAFgAASiGIAAgBIABgBQAEgFAGAAIABAAIAAAAIAAAAIABAAIACAAQAHACABADQgBgDgHgCIgCAAIgBAAIAAAAIAAAAIgBAAQgGAAgEAFIgBABIAAABg");
	this.shape_8.setTransform(0.5,2.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#000000").ss(0.1,1,1).p("AgFiVQAFgFAIgFQAHgHAJgCQAKgDAJgBQAKgCAJACQAKACAIADQAJAEAIAEQAIAEAFAHQAFAHADAIQAEAJABAKQABAKgBAJQAAADAAADAh+gYQgGgEgDgKQgCgJgDgJQgDgJABgKQAAgFAAgEQABgFAAgEQgBgDgBgEQgCgKABgJQABgKAFgIQAEgIAIgFQAIgFAIgGQAIgFAJgCQAJgCAIABQAKACAKABQAJAAAJAEQAKADAGAEQAIgGAHgHQAGgHAIgCQAJgCAIgDQAKgDAJgDQAIgEAKAAQAKAAAJACQAJABAHAGQAHAHAIAFQAHAGAFAIQAFAGACAHQACAFABAFQACAJACAJQADAKACAJQACAKgCAJQgBAJgDAJQgEAKgEAHQgBACgCAAQAAAFACAFQABAEgBAEQAAAJgDAJQgEAGgDAJQgCAJgCAJQgBAKgBAJQgBALgFAJQAAADAAAEQAAABAAACQgBAKgHAGQgHAHgHADQgJAEgHAEQgIAEgJAAQgBAAgBAAQgIAAgJAAQgJAAgKAAQgKAAgIgCQgKgCgIgDQgJgEgIgGQgHgGgHgHQgGgGgEgIQgFgHgEgJQgDgJgFgJQAAAAAAgBQAAAAgBgBQgDgHgBgHQgEADgFABQgFAAgEgCQgIgGgFgHQgEgHgDgHQgDgJAAgLgAhZgfQAAgJABgIQACAFACAFQAEALAHAGQgCgHgBgIQgBgJgBgJQgBgJAAgJQgBgKACgKQACgIAFgIQAGgHAHgHQAHgGAHgFQAIgFAJgCQALgCAFALQABgHAJgDQAHgCAKgBQAJgBAKABQAKABAJACQAJACAIAGQAIAFAGAIQAFAIAEAJQAEAIgCAKQgCAJgEAJQgBADgBADQABgCACgCQACgCACgCAAyihQAJgDAJAGQAIAEAHAFQAIAGAHAGQAGAGAFAIQAEAIACAJQACAKAAAKABChAQgCAJgJACQgJADgIgFQgHgEABgLQABgJAGgHQAHgGAKAAQACgEAFAFQADAEAAAEQAAACAAADQABAHgBAHQgGABgBgDQgEgNALABAAShvQAFgIALACQAGABACAEAgXhKQgCgCgEAAQgLABgEAJQgEAIACAKQADAJAGAGQAGAHALgBQAIAAAFgFQAEgDAAgIQAAgBAAgBQAAABgBAAQgCABgCAAQgLABgBgIQgCgMANABAAEgdQAAAKAIAFQAGAFAIgBQAJAAAJgCQAJgCAIgDQAJgDgBgLQgBgHgHgDQgIgDgKABQgDAAgDAAAB/gpQgFgIgIgFQgEgDgEgBQgJgBgCgKQABgCACgCAgyiTQgJgBgJAFQgIAEgIAGQgIAHgDAJQgEAIAAAKQAAAKgBAJQgBAJAAAKAgciZQgHgCgJgCQgJgDgKABQgJAAgKABQgJABgHAGQgHAGgGAIQgGAHgEAIQgDAIAAAJQAAAKAAAKQAAAFAAABAhfgoQgGgFgHABQgHAAgFAGQgFAGgBAIAgihfQgHgGgKAFQgJAFAAAIQgBAEABADAgXhKQAFACAFAEQgCgDgDgCQgBgCgEABgAhZgfQgBgFgFgEQAAAAAAAAQAFAHACAGQAAgCgBgCgAgDgtQAAgJgFgGQAAgBgBAAAgNhEQACADACAEAhVAVQADgCACgEQAFgGgCgJAAyCCQAFAHALABQAGABAFACQAJADAJACQAIADAIACQAJADAIAEQAIAEAHAFQAHAFAHAFQAGAGAHAEQAEADAFADIllgcQAIgEAKgDQAJgDAJgCQAHgCAHgBQAJgBAJgDQAJgDAJgDQAKgDAEgHQAEgJAAgKQAAgJgBgKQgBgKgBgJQgBgJAAgKQABgJgDgIQAAAAAAgBAAXAxQADAMAQgBQARgBgJgRQgJgQgLAFQgLAGAEAMgAA0BzIAAABQgCAGAAAIQAAACABACQABAKAEAI");
	this.shape_9.setTransform(0.5,0.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AANBCQgDgLALgGQALgGAJARQAIAQgQABIgCAAQgPAAgDgLgAgugPQgGgGgDgJQgCgKAEgJQAEgJALAAIAGABQAFACAEAFIAFAGQgNAAACALQABAIALAAIAEgCIABACQAAAHgEAEQgFAEgIABIgCAAQgJAAgGgGgAAcglQgHgFABgKQABgKAHgGQAGgGALgBQACgEAEAGQADAEABADIAAAFQgLAAAEAMQABAEAFgBQgBAIgJADIgHABQgGAAgFgDg");
	this.shape_10.setTransform(1.4,-1.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFCC97").s().p("AixCOQAHgFALgDIARgFIAOgDQAJgBAJgDIASgGQAKgDAEgHQAFgIgBgKIgBgUIgCgSQgBgKABgKQAAgJgDgHIABAAIgBgCIgBAAQgDgHgBgFIAGgGQADgFAAgHIAAgEIAAAEQAAAHgDAFIgGAGQgEABgFAAQgFABgEgCQgIgEgEgIQgFgHgDgJQgDgIAAgMQACgIAEgGQAFgFAHgBQAHAAAGAEQAFAHACAGIAAgEQgBgJABgIIAEAKQAEALAHAHIgDgPIgCgTIgBgSQAAgKACgJQABgJAGgHQAFgIAHgHIAOgKQAIgFAJgCQALgCAFAKQABgHAJgCQAHgDAJgBIAUAAIATADQAJACAIAGQAIAGAGAIIAIAQQAEAJgCAKIgFASIgDAFIAEgEIADgDQACAJAKACIAIADQAIAGAFAIIACAKQAAAEAAAEQAAAJgDAIIgHASIgEAQIgCATQgBAKgFAKIAAAGIgBAEQAAAJgHAHQgHAGgHAEIgRAIQgHAEgJAAIgBAAIgBAAIgRgBIgUAAIgBAAIgCAAIAAAAIgBAAIgMgBIgBAAIgSgGQgJgDgIgGIgOgNQgGgHgEgHIgJgRIgHgRIAHARIAJARQAEAHAGAHIAOANQAIAGAJADIASAGIABAAIAMABIABAAIAAAAIACAAIABAAIAUAAIARABIABAAIABAAIAAAAQgCAHAAAIQAFAGALACIALACIASAGIAQAFQAJACAIAFQAIADAGAFIAOALQAGAFAHAEIAJAGgAAyBuQABAKAFAJQgFgJgBgKIAAgDIAAADgAAeAIQgLAFADAMQAEAMAQgBQARgBgJgQQgHgNgHAAIgGACgAAZghIABAAIARgCIASgFQAIgDAAgJIgBgCQAAgIgHgCIgBgBQgHgCgHAAIgBAAIAAAAIgBAAIgCAAIgFAAIAFAAIACAAIABAAIAAAAIABAAQAHAAAHACIABABQAHACAAAIIABACQAAAJgIADIgSAFIgRACIgBAAIgBAAIAAAAQgHgBgFgDQgIgGAAgJQAAAJAIAGQAFADAHABIAAAAIABAAgAgshaQgEAJACAKQADAJAGAGQAGAGALAAQAIgBAGgEQADgEAAgHIAAgCQAAgKgFgGIgBgBIgEgGIgFgGQgBgCgEABIgGgBQgLAAgEAJgAA4h0QgKABgHAGQgGAGgCAKQgBAKAIAFQAIAEAJgCQAJgDACgIQABgIgBgHIAAgFQgBgDgCgEQgDgEgCAAQAAAAAAABQgBAAAAAAQAAAAgBAAQAAABAAAAgAg7hjIgBgFIAAgCQAAgJAKgFIABAAIAGgCIABAAIAAAAQAFAAAEADQgEgDgFAAIAAAAIgBAAIgGACIgBAAQgKAFAAAJIAAACIABAFgAASiGIAAgBIABgBQAEgFAGAAIABAAIAAAAIAAAAIABAAIACAAQAHACABADQgBgDgHgCIgCAAIgBAAIAAAAIAAAAIgBAAQgGAAgEAFIgBABIAAABg");
	this.shape_11.setTransform(0.5,2.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#000000").ss(0.1,1,1).p("Ah+gYQgGgEgDgKQgCgJgDgJQgDgJABgKQAAgFAAgEQABgFAAgEQgBgDgBgEQgCgKABgJQABgKAFgIQAEgIAIgFQAIgFAIgGQAIgFAJgCQAJgCAIABQAKACAKABQAJAAAJAEQAKADAGAEQAIgGAHgHQAGgHAIgCQAJgCAIgDQAKgDAJgDQAIgEAKAAQAKAAAJACQAJABAHAGQAHAHAIAFQAHAGAFAIQAFAGACAHQACAFABAFQACAJACAJQADAKACAJQACAKgCAJQgBAJgDAJQgEAKgEAHQgBACgCAAQAAAFACAFQABAEgBAEQAAAJgDAJQgEAGgDAJQgCAJgCAJQgBAKgBAJQgBALgFAJQAAADAAAEQAAABAAACQgBAKgHAGQgHAHgHADQgJAEgHAEQgIAEgJAAQgBAAgBAAQgIAAgJAAQgJAAgKAAQgKAAgIgCQgKgCgIgDQgJgEgIgGQgHgGgHgHQgGgGgEgIQgFgHgEgJQgDgJgFgJQAAAAAAgBQAAAAgBgBQgDgHgBgHQgEADgFABQgFAAgEgCQgIgGgFgHQgEgHgDgHQgDgJAAgLgAgFiVQAFgFAIgFQAHgHAJgCQAKgDAJgBQAKgCAJACQAKACAIADQAJAEAIAEQAIAEAFAHQAFAHADAIQAEAJABAKQABAKgBAJQAAADAAADAhZgfQAAgJABgIQACAFACAFQAEALAHAGQgCgHgBgIQgBgJgBgJQgBgJAAgJQgBgKACgKQACgIAFgIQAGgHAHgHQAHgGAHgFQAIgFAJgCQALgCAFALQABgHAJgDQAHgCAKgBQAJgBAKABQAKABAJACQAJACAIAGQAIAFAGAIQAFAIAEAJQAEAIgCAKQgCAJgEAJQgBADgBADQABgCACgCQACgCACgCAAyihQAJgDAJAGQAIAEAHAFQAIAGAHAGQAGAGAFAIQAEAIACAJQACAKAAAKABChAQgCAJgJACQgJADgIgFQgHgEABgLQABgJAGgHQAHgGAKAAQACgEAFAFQADAEAAAEQAAACAAADQABAHgBAHQgGABgBgDQgEgNALABAAShvQAFgIALACQAGABACAEAAEgdQAAAKAIAFQAGAFAIgBQAJAAAJgCQAJgCAIgDQAJgDgBgLQgBgHgHgDQgIgDgKABQgDAAgDAAAgXhKQgCgCgEAAQgLABgEAJQgEAIACAKQADAJAGAGQAGAHALgBQAIAAAFgFQAEgDAAgIQAAgBAAgBQAAABgBAAQgCABgCAAQgLABgBgIQgCgMANABAB/gpQgFgIgIgFQgEgDgEgBQgJgBgCgKQABgCACgCAgciZQgHgCgJgCQgJgDgKABQgJAAgKABQgJABgHAGQgHAGgGAIQgGAHgEAIQgDAIAAAJQAAAKAAAKQAAAFAAABAgyiTQgJgBgJAFQgIAEgIAGQgIAHgDAJQgEAIAAAKQAAAKgBAJQgBAJAAAKAhfgoQgGgFgHABQgHAAgFAGQgFAGgBAIAgihfQgHgGgKAFQgJAFAAAIQgBAEABADAgNhEQgCgDgDgCQgBgCgEABQAFACAFAEgAhZgfQgBgFgFgEQAAAAAAAAQAFAHACAGQAAgCgBgCgAgDgtQAAgJgFgGQAAgBgBAAQgCgEgCgDAhVAVQADgCACgEQAFgGgCgJAAyCCQAFAHALABQAGABAFACQAJADAJACQAIADAIACQAJADAIAEQAIAEAHAFQAHAFAHAFQAGAGAHAEQAEADAFADIllgcQAIgEAKgDQAJgDAJgCQAHgCAHgBQAJgBAJgDQAJgDAJgDQAKgDAEgHQAEgJAAgKQAAgJgBgKQgBgKgBgJQgBgJAAgKQABgJgDgIQAAAAAAgBABTA0QgJALgVACQgOACgQAEQgrAKABg3QAiAGAkAGQAVAEALAKgAA0BzIAAABQgCAGAAAIQAAACABACQABAKAEAI");
	this.shape_12.setTransform(0.5,0.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgkAmIBFALQAVAEALALQgJAKgVADQgOABgQAEIgLACQgfAAABgugAg3gVQgGgGgCgJQgDgKAEgJQAFgJAKAAIAHABQAFACAEAFIAFAGQgOAAACALQABAIAMAAIAEgCIAAACQAAAHgDAEQgFAEgJABIgBAAQgJAAgHgGgAAUgrQgHgFABgKQABgKAGgGQAHgGAKgBQACgEAFAGQADAEAAADIABAFQgMAAAEAMQABAEAGgBQgCAIgJADIgGAAQgGAAgFgCg");
	this.shape_13.setTransform(2.3,-0.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFCC97").s().p("AixCOQAHgFALgDIARgFIAOgDQAJgBAJgDIASgGQAKgDAEgHQAFgIgBgKIgBgUIgCgSQgBgKABgKQAAgJgDgHIABAAIgBgCIgBAAQgDgHgBgFIAGgGQADgFAAgHIAAgEIAAAEQAAAHgDAFIgGAGQgEABgFAAQgFABgEgCQgIgEgEgIQgFgHgDgJQgDgIAAgMQACgIAEgGQAFgFAHgBQAHAAAGAEQAFAHACAGIAAgEQgBgJABgIIAEAKQAEALAHAHIgDgPIgCgTIgBgSQAAgKACgJQABgJAGgHQAFgIAHgHIAOgKQAIgFAJgCQALgCAFAKQABgHAJgCQAHgDAJgBIAUAAIATADQAJACAIAGQAIAGAGAIIAIAQQAEAJgCAKIgFASIgDAFIAEgEIADgDQACAJAKACIAIADQAIAGAFAIIACAKQAAAEAAAEQAAAJgDAIIgHASIgEAQIgCATQgBAKgFAKIAAAGIgBAEQAAAJgHAHQgHAGgHAEIgRAIQgHAEgJAAIgBAAIgBAAIgRgBIgUAAIgBAAIgCAAIAAAAIgBAAIgMgBIgBAAIgSgGQgJgDgIgGIgOgNQgGgHgEgHIgJgRIgHgRIAHARIAJARQAEAHAGAHIAOANQAIAGAJADIASAGIABAAIAMABIABAAIAAAAIACAAIABAAIAUAAIARABIABAAIABAAIAAAAQgCAHAAAIQAFAGALACIALACIASAGIAQAFQAJACAIAFQAIADAGAFIAOALQAGAFAHAEIAJAGgAAyBuQABAKAFAJQgFgJgBgKIAAgDIAAADgAAWAvQARgEAOgBQAVgDAJgKQgLgLgWgEIhFgLQgBA2AqgKgAAZghIABAAIARgCIASgFQAIgDAAgJIgBgCQAAgIgHgCIgBgBQgHgCgHAAIgBAAIAAAAIgBAAIgCAAIgFAAIAFAAIACAAIABAAIAAAAIABAAQAHAAAHACIABABQAHACAAAIIABACQAAAJgIADIgSAFIgRACIgBAAIgBAAIAAAAQgHgBgFgDQgIgGAAgJQAAAJAIAGQAFADAHABIAAAAIABAAgAgshaQgEAJACAKQADAJAGAGQAGAGALAAQAIgBAGgEQADgEAAgHIAAgCQAAgKgFgGIgBgBIgEgGIgFgGQgBgCgEABIgGgBQgLAAgEAJgAA4h0QgKABgHAGQgGAGgCAKQgBAKAIAFQAIAEAJgCQAJgDACgIQABgIgBgHIAAgFQgBgDgCgEQgDgEgCAAQAAAAAAABQgBAAAAAAQAAAAgBAAQAAABAAAAgAg7hjIgBgFIAAgCQAAgJAKgFIABAAIAGgCIABAAIAAAAQAFAAAEADQgEgDgFAAIAAAAIgBAAIgGACIgBAAQgKAFAAAJIAAACIABAFgAASiGIAAgBIABgBQAEgFAGAAIABAAIAAAAIAAAAIABAAIACAAQAHACABADQgBgDgHgCIgCAAIgBAAIAAAAIAAAAIgBAAQgGAAgEAFIgBABIAAABg");
	this.shape_14.setTransform(0.5,2.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#000000").ss(0.1,1,1).p("AgFiVQAFgFAIgFQAHgHAJgCQAKgDAJgBQAKgCAJACQAKACAIADQAJAEAIAEQAIAEAFAHQAFAHADAIQAEAJABAKQABAKgBAJQAAADAAADAh+gYQgGgEgDgKQgCgJgDgJQgDgJABgKQAAgFAAgEQABgFAAgEQgBgDgBgEQgCgKABgJQABgKAFgIQAEgIAIgFQAIgFAIgGQAIgFAJgCQAJgCAIABQAKACAKABQAJAAAJAEQAKADAGAEQAIgGAHgHQAGgHAIgCQAJgCAIgDQAKgDAJgDQAIgEAKAAQAKAAAJACQAJABAHAGQAHAHAIAFQAHAGAFAIQAFAGACAHQACAFABAFQACAJACAJQADAKACAJQACAKgCAJQgBAJgDAJQgEAKgEAHQgBACgCAAQgFgIgIgFQgEgDgEgBQgJgBgCgKQABgCACgCAhZgfQAAgJABgIQACAFACAFQAEALAHAGQgCgHgBgIQgBgJgBgJQgBgJAAgJQgBgKACgKQACgIAFgIQAGgHAHgHQAHgGAHgFQAIgFAJgCQALgCAFALQABgHAJgDQAHgCAKgBQAJgBAKABQAKABAJACQAJACAIAGQAIAFAGAIQAFAIAEAJQAEAIgCAKQgCAJgEAJQgBADgBADQABgCACgCQACgCACgCAAyihQAJgDAJAGQAIAEAHAFQAIAGAHAGQAGAGAFAIQAEAIACAJQACAKAAAKABChAQgCAJgJACQgJADgIgFQgHgEABgLQABgJAGgHQAHgGAKAAQACgEAFAFQADAEAAAEQAAACAAADQABAHgBAHQgGABgBgDQgEgNALABAAShvQAFgIALACQAGABACAEAgXhKQgCgCgEAAQgLABgEAJQgEAIACAKQADAJAGAGQAGAHALgBQAIAAAFgFQAEgDAAgIQAAgBAAgBQAAgJgFgGQAAgBgBAAAAEgdQAAAKAIAFQAGAFAIgBQAJAAAJgCQAJgCAIgDQAJgDgBgLQgBgHgHgDQgIgDgKABQgDAAgDAAAB/gpQAAAFACAFQABAEgBAEQAAAJgDAJQgEAGgDAJQgCAJgCAJQgBAKgBAJQgBALgFAJQAAADAAAEQAAABAAACQgBAKgHAGQgHAHgHADQgJAEgHAEQgIAEgJAAQgBAAgBAAQgIAAgJAAQgJAAgKAAQgKAAgIgCQgKgCgIgDQgJgEgIgGQgHgGgHgHQgGgGgEgIQgFgHgEgJQgDgJgFgJQAAAAAAgBQAAAAgBgBQgDgHgBgHQgEADgFABQgFAAgEgCQgIgGgFgHQgEgHgDgHQgDgJAAgLAgsANQAEAGAHAGQAIAFAIAFQAHAFAKACQAHACAKABQAKAAAJgBQAKAAAIgEQAIgFAJgEQAIgDAIgFQAIgGAFgHAA0BzIAAABQgCAGAAAIQAFAHALABQAGABAFACQAJADAJACQAIADAIACQAJADAIAEQAIAEAHAFQAHAFAHAFQAGAGAHAEQAEADAFADIllgcQAIgEAKgDQAJgDAJgCQAHgCAHgBQAJgBAJgDQAJgDAJgDQAKgDAEgHQAEgJAAgKQAAgJgBgKQgBgKgBgJQgBgJAAgKQABgJgDgIQAAAAAAgBAAyCCQAAACABACQABAKAEAIAgciZQgHgCgJgCQgJgDgKABQgJAAgKABQgJABgHAGQgHAGgGAIQgGAHgEAIQgDAIAAAJQAAAKAAAKQAAAFAAABAgyiTQgJgBgJAFQgIAEgIAGQgIAHgDAJQgEAIAAAKQAAAKgBAJQgBAJAAAKAhfgoQgGgFgHABQgHAAgFAGQgFAGgBAIAgihfQgHgGgKAFQgJAFAAAIQgBAEABADAgNhEQgCgDgDgCQgBgCgEABQAFACAFAEgAhZgfQgBgFgFgEQAAAAAAAAQAFAHACAGQAAgCgBgCgAgDgtQAAABgBAAQgCABgCAAQgLABgBgIQgCgMANABQgCgEgCgDAgsANQgBADgBADQgBAEABACAgjAIQgGABgDAEAhVAVQADgCACgEQAFgGgCgJ");
	this.shape_15.setTransform(0.5,0.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFCC97").s().p("AixCOQAHgFALgDIARgFIAOgDQAJgBAJgDIASgGQAKgDAEgHQAFgIgBgKIgBgUIgCgSQgBgKABgKQAAgJgDgHIABAAIgBgCIgBAAQgDgHgBgFIAGgGQADgFAAgHIAAgEIAAAEQAAAHgDAFIgGAGQgEABgFAAQgFABgEgCQgIgEgEgIQgFgHgDgJQgDgIAAgMQACgIAEgGQAFgFAHgBQAHAAAGAEQAFAHACAGIAAgEQgBgJABgIIAEAKQAEALAHAHIgDgPIgCgTIgBgSQAAgKACgJQABgJAGgHQAFgIAHgHIAOgKQAIgFAJgCQALgCAFAKQABgHAJgCQAHgDAJgBIAUAAIATADQAJACAIAGQAIAGAGAIIAIAQQAEAJgCAKIgFASIgDAFIAEgEIADgDQACAJAKACIAIADQAIAGAFAIIACAKQAAAEAAAEQAAAJgDAIIgHASIgEAQIgCATQgBAKgFAKIAAAGIgBAEQAAAJgHAHQgHAGgHAEIgRAIQgHAEgJAAIgCAAIgRgBIgUAAIgBAAIgCAAIAAAAIgBAAIgMgBIgBAAIgSgGQgJgDgIgGIgOgNQgGgHgEgHIgJgRIgHgRIAHARIAJARQAEAHAGAHIAOANQAIAGAJADIASAGIABAAIAMABIABAAIAAAAIACAAIABAAIAUAAIARABIACAAIAAAAQgCAHAAAIQAFAGALACIALACIASAGIAQAFQAJACAIAFQAIADAGAFIAOALQAGAFAHAEIAJAGgAAyBuQABAKAFAJQgFgJgBgKIAAgDIAAADgAggABIAPALQAIAFAJACQAHACAJAAIAUAAQAKAAAIgFIAQgIQAJgEAHgEQAIgFAGgGQgGAGgIAFQgHAEgJAEIgQAIQgIAFgKAAIgUAAQgJAAgHgCQgJgCgIgFIgPgLQgIgDgDgHQACgDAGgCQgGACgCADQgCADgBAEIAAACIAAACIAAgCIAAgCQABgEACgDQADAHAIADgAAZghIABAAIARgCIASgFQAIgDAAgJIgBgCQAAgIgHgCIgBgBQgHgCgHAAIgBAAIAAAAIgBAAIgCAAIgFAAIAFAAIACAAIABAAIAAAAIABAAQAHAAAHACIABABQAHACAAAIIABACQAAAJgIADIgSAFIgRACIgBAAIgBAAIAAAAQgHgBgFgDQgIgGAAgJQAAAJAIAGQAFADAHABIAAAAIABAAgAgshaQgEAJACAKQADAJAGAGQAGAGALAAQAIgBAGgEQADgEAAgHIAAgCQAAgKgFgGIgBgBIgEgGIgFgGQgBgCgEABIgGgBQgLAAgEAJgAA4h0QgKABgHAGQgGAGgCAKQgBAKAIAFQAIAEAJgCQAJgDACgIQABgIgBgHIAAgFQgBgDgCgEQgDgEgCAAQAAAAAAABQgBAAAAAAQAAAAgBAAQAAABAAAAgAg7hjIgBgFIAAgCQAAgJAKgFIABAAIAGgCIABAAIAAAAQAFAAAEADQgEgDgFAAIAAAAIgBAAIgGACIgBAAQgKAFAAAJIAAACIABAFgAASiGIAAgBIABgBQAEgFAGAAIABAAIAAAAIAAAAIABAAIACAAQAHACABADQgBgDgHgCIgCAAIgBAAIAAAAIAAAAIgBAAQgGAAgEAFIgBABIAAABg");
	this.shape_16.setTransform(0.5,2.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#000000").ss(0.1,1,1).p("AgFiVQAFgFAIgFQAHgHAJgCQAKgDAJgBQAKgCAJACQAKACAIADQAJAEAIAEQAIAEAFAHQAFAHADAIQAEAJABAKQABAKgBAJQAAADAAADAh+gYQgGgEgDgKQgCgJgDgJQgDgJABgKQAAgFAAgEQABgFAAgEQgBgDgBgEQgCgKABgJQABgKAFgIQAEgIAIgFQAIgFAIgGQAIgFAJgCQAJgCAIABQAKACAKABQAJAAAJAEQAKADAGAEQAIgGAHgHQAGgHAIgCQAJgCAIgDQAKgDAJgDQAIgEAKAAQAKAAAJACQAJABAHAGQAHAHAIAFQAHAGAFAIQAFAGACAHQACAFABAFQACAJACAJQADAKACAJQACAKgCAJQgBAJgDAJQgEAKgEAHQgBACgCAAQAAAFACAFQABAEgBAEQAAAJgDAJQgEAGgDAJQgCAJgCAJQgBAKgBAJQgBALgFAJQAAADAAAEQAAABAAACQgBAKgHAGQgHAHgHADQgJAEgHAEQgIAEgJAAIAAABQgCAGAAAIQAAACABACQABAKAEAIAhZgfQAAgJABgIQACAFACAFQAEALAHAGQgCgHgBgIQgBgJgBgJQgBgJAAgJQgBgKACgKQACgIAFgIQAGgHAHgHQAHgGAHgFQAIgFAJgCQALgCAFALQABgHAJgDQAHgCAKgBQAJgBAKABQAKABAJACQAJACAIAGQAIAFAGAIQAFAIAEAJQAEAIgCAKQgCAJgEAJQgBADgBADQABgCACgCQACgCACgCAAyihQAJgDAJAGQAIAEAHAFQAIAGAHAGQAGAGAFAIQAEAIACAJQACAKAAAKABChAQgCAJgJACQgJADgIgFQgHgEABgLQABgJAGgHQAHgGAKAAQACgEAFAFQADAEAAAEQAAACAAADQABAHgBAHQgGABgBgDQgEgNALABAAShvQAFgIALACQAGABACAEAgXhKQgCgCgEAAQgLABgEAJQgEAIACAKQADAJAGAGQAGAHALgBQAIAAAFgFQAEgDAAgIQAAgBAAgBQAAABgBAAQgCABgCAAQgLABgBgIQgCgMANABAAEgdQAAAKAIAFQAGAFAIgBQAJAAAJgCQAJgCAIgDQAJgDgBgLQgBgHgHgDQgIgDgKABQgDAAgDAAAB/gpQgFgIgIgFQgEgDgEgBQgJgBgCgKQABgCACgCAgyiTQgJgBgJAFQgIAEgIAGQgIAHgDAJQgEAIAAAKQAAAKgBAJQgBAJAAAKAgciZQgHgCgJgCQgJgDgKABQgJAAgKABQgJABgHAGQgHAGgGAIQgGAHgEAIQgDAIAAAJQAAAKAAAKQAAAFAAABAhVAVQgEADgFABQgFAAgEgCQgIgGgFgHQgEgHgDgHQgDgJAAgLAhfgoQgGgFgHABQgHAAgFAGQgFAGgBAIAgihfQgHgGgKAFQgJAFAAAIQgBAEABADAgXhKQAFACAFAEQgCgDgDgCQgBgCgEABgAhZgfQgBgFgFgEQAAAAAAAAQAFAHACAGQAAgCgBgCgAgDgtQAAgJgFgGQAAgBgBAAAgNhEQACADACAEAhVAVQADgCACgEQAFgGgCgJAhQAkQAAABAAAAQAFAJADAJQAEAJAFAHQAEAIAGAGQAHAHAHAGQAIAGAJAEQAIADAKACQAIACAKAAQAKAAAJAAQAJAAAIAAQABAAABAAAhQAkQAAAAgBgBQgDgHgBgHAAyCCQAFAHALABQAGABAFACQAJADAJACQAIADAIACQAJADAIAEQAIAEAHAFQAHAFAHAFQAGAGAHAEQAEADAFADIllgcQAIgEAKgDQAJgDAJgCQAHgCAHgBQAJgBAJgDQAJgDAJgDQAKgDAEgHQAEgJAAgKQAAgJgBgKQgBgKgBgJQgBgJAAgKQABgJgDgIQAAAAAAgBABTA0QgJALgVACQgOACgQAEQgrAKABg3QAiAGAkAGQAVAEALAKg");
	this.shape_17.setTransform(0.5,0.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFCC97").s().p("AixCOQAHgFALgDIARgFIAOgDQAJgBAJgDIASgGQAKgDAEgHQAFgIgBgKIgBgUIgCgSQgBgKABgKQAAgJgDgHIABAAIAHARIAJARQAEAHAGAHIAOANQAIAGAJADIASAGIABAAIAMABIABAAIAAAAIACAAIABAAIAUAAIARABIACAAIAAAAQgCAHAAAIQAFAGALACIALACIASAGIAQAFQAJACAIAFQAIADAGAFIAOALQAGAFAHAEIAJAGgAAyBuQABAKAFAJQgFgJgBgKIAAgDIAAADgAAyBcIgRgBIgUAAIgBAAIgCAAIAAAAIgBAAIgMgBIgBAAIgSgGQgJgDgIgGIgOgNQgGgHgEgHIgJgRIgHgRIgBgCIgBAAQgDgHgBgFIAGgGQADgFAAgHIAAgEIAAAEQAAAHgDAFIgGAGQgEABgFAAQgFABgEgCQgIgEgEgIQgFgHgDgJQgDgIAAgMQACgIAEgGQAFgFAHgBQAHAAAGAEQAFAHACAGIAAgEQgBgJABgIIAEAKQAEALAHAHIgDgPIgCgTIgBgSQAAgKACgJQABgJAGgHQAFgIAHgHIAOgKQAIgFAJgCQALgCAFAKQABgHAJgCQAHgDAJgBIAUAAIATADQAJACAIAGQAIAGAGAIIAIAQQAEAJgCAKIgFASIgDAFIAEgEIADgDQACAJAKACIAIADQAIAGAFAIIACAKQAAAEAAAEQAAAJgDAIIgHASIgEAQIgCATQgBAKgFAKIAAAGIgBAEQAAAJgHAHQgHAGgHAEIgRAIQgHAEgJAAIgBAAIgBAAgAAWAvQARgEAOgBQAVgDAJgKQgLgLgWgEIhFgLQgBA2AqgKgAAZghIABAAIARgCIASgFQAIgDAAgJIgBgCQAAgIgHgCIgBgBQgHgCgHAAIgBAAIAAAAIgBAAIgCAAIgFAAIAFAAIACAAIABAAIAAAAIABAAQAHAAAHACIABABQAHACAAAIIABACQAAAJgIADIgSAFIgRACIgBAAIgBAAIAAAAQgHgBgFgDQgIgGAAgJQAAAJAIAGQAFADAHABIAAAAIABAAgAgshaQgEAJACAKQADAJAGAGQAGAGALAAQAIgBAGgEQADgEAAgHIAAgCQAAgKgFgGIgBgBIgEgGIgFgGQgBgCgEABIgGgBQgLAAgEAJgAA4h0QgKABgHAGQgGAGgCAKQgBAKAIAFQAIAEAJgCQAJgDACgIQABgIgBgHIAAgFQgBgDgCgEQgDgEgCAAQAAAAAAABQgBAAAAAAQAAAAgBAAQAAABAAAAgAg7hjIgBgFIAAgCQAAgJAKgFIABAAIAGgCIABAAIAAAAQAFAAAEADQgEgDgFAAIAAAAIgBAAIgGACIgBAAQgKAFAAAJIAAACIABAFgAASiGIAAgBIABgBQAEgFAGAAIABAAIAAAAIAAAAIABAAIACAAQAHACABADQgBgDgHgCIgCAAIgBAAIAAAAIAAAAIgBAAQgGAAgEAFIgBABIAAABg");
	this.shape_18.setTransform(0.5,2.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#000000").ss(0.1,1,1).p("Ah+gYQgGgEgDgKQgCgJgDgJQgDgJABgKQAAgFAAgEQABgFAAgEQgBgDgBgEQgCgKABgJQABgKAFgIQAEgIAIgFQAIgFAIgGQAIgFAJgCQAJgCAIABQAKACAKABQAJAAAJAEQAKADAGAEQAIgGAHgHQAGgHAIgCQAJgCAIgDQAKgDAJgDQAIgEAKAAQAKAAAJACQAJABAHAGQAHAHAIAFQAHAGAFAIQAFAGACAHQACAFABAFQACAJACAJQADAKACAJQACAKgCAJQgBAJgDAJQgEAKgEAHQgBACgCAAQgFgIgIgFQgEgDgEgBQgJgBgCgKQABgCACgCAgFiVQAFgFAIgFQAHgHAJgCQAKgDAJgBQAKgCAJACQAKACAIADQAJAEAIAEQAIAEAFAHQAFAHADAIQAEAJABAKQABAKgBAJQAAADAAADAhZgfQAAgJABgIQACAFACAFQAEALAHAGQgCgHgBgIQgBgJgBgJQgBgJAAgJQgBgKACgKQACgIAFgIQAGgHAHgHQAHgGAHgFQAIgFAJgCQALgCAFALQABgHAJgDQAHgCAKgBQAJgBAKABQAKABAJACQAJACAIAGQAIAFAGAIQAFAIAEAJQAEAIgCAKQgCAJgEAJQgBADgBADQABgCACgCQACgCACgCAAyihQAJgDAJAGQAIAEAHAFQAIAGAHAGQAGAGAFAIQAEAIACAJQACAKAAAKABChAQgCAJgJACQgJADgIgFQgHgEABgLQABgJAGgHQAHgGAKAAQACgEAFAFQADAEAAAEQAAACAAADQABAHgBAHQgGABgBgDQgEgNALABAAShvQAFgIALACQAGABACAEAAEgdQAAAKAIAFQAGAFAIgBQAJAAAJgCQAJgCAIgDQAJgDgBgLQgBgHgHgDQgIgDgKABQgDAAgDAAAgXhKQgCgCgEAAQgLABgEAJQgEAIACAKQADAJAGAGQAGAHALgBQAIAAAFgFQAEgDAAgIQAAgBAAgBQAAgJgFgGQAAgBgBAAAB/gpQAAAFACAFQABAEgBAEQAAAJgDAJQgEAGgDAJQgCAJgCAJQgBAKgBAJQgBALgFAJQAAADAAAEQAAABAAACQgBAKgHAGQgHAHgHADQgJAEgHAEQgIAEgJAAABkAKQgFAHgIAGQgIAFgIADQgJAEgIAFQgIAEgKAAQgJABgKAAQgKgBgHgCQgKgCgHgFQgIgFgIgFQgHgGgEgGAhQAkQAAABAAAAQAFAJADAJQAEAJAFAHQAEAIAGAGQAHAHAHAGQAIAGAJAEQAIADAKACQAIACAKAAQAKAAAJAAQAJAAAIAAQABAAABAAIAAABQgCAGAAAIQAFAHALABQAGABAFACQAJADAJACQAIADAIACQAJADAIAEQAIAEAHAFQAHAFAHAFQAGAGAHAEQAEADAFADIllgcQAIgEAKgDQAJgDAJgCQAHgCAHgBQAJgBAJgDQAJgDAJgDQAKgDAEgHQAEgJAAgKQAAgJgBgKQgBgKgBgJQgBgJAAgKQABgJgDgIQAAAAAAgBQAAAAgBgBQgDgHgBgHQgEADgFABQgFAAgEgCQgIgGgFgHQgEgHgDgHQgDgJAAgLAAyCCQAAACABACQABAKAEAIAgyiTQgJgBgJAFQgIAEgIAGQgIAHgDAJQgEAIAAAKQAAAKgBAJQgBAJAAAKAgciZQgHgCgJgCQgJgDgKABQgJAAgKABQgJABgHAGQgHAGgGAIQgGAHgEAIQgDAIAAAJQAAAKAAAKQAAAFAAABAhfgoQgGgFgHABQgHAAgFAGQgFAGgBAIAgihfQgHgGgKAFQgJAFAAAIQgBAEABADAgXhKQAFACAFAEQgCgDgDgCQgBgCgEABgAhZgfQgBgFgFgEQAAAAAAAAQAFAHACAGQAAgCgBgCgAgDgtQAAABgBAAQgCABgCAAQgLABgBgIQgCgMANABAgNhEQACADACAEAgjAIQgGABgDAEQgBADgBADQgBAEABACAhVAVQADgCACgEQAFgGgCgJ");
	this.shape_19.setTransform(0.5,0.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFCC97").s().p("AixCOQAHgFALgDIARgFIAOgDQAJgBAJgDIASgGQAKgDAEgHQAFgIgBgKIgBgUIgCgSQgBgKABgKQAAgJgDgHIABAAIAHARIAJARQAEAHAGAHIAOANQAIAGAJADIASAGIABAAIAMABIABAAIAAAAIACAAIABAAIAUAAIARABIACAAIAAAAQgCAHAAAIQAFAGALACIALACIASAGIAQAFQAJACAIAFQAIADAGAFIAOALQAGAFAHAEIAJAGgAAyBuQABAKAFAJQgFgJgBgKIAAgDIAAADgAAyBcIgRgBIgUAAIgBAAIgCAAIAAAAIgBAAIgMgBIgBAAIgSgGQgJgDgIgGIgOgNQgGgHgEgHIgJgRIgHgRIgBgCIgBAAQgDgHgBgFIAGgGQADgFAAgHIAAgEIAAAEQAAAHgDAFIgGAGQgEABgFAAQgFABgEgCQgIgEgEgIQgFgHgDgJQgDgIAAgMQACgIAEgGQAFgFAHgBQAHAAAGAEQAFAHACAGIAAgEQgBgJABgIIAEAKQAEALAHAHIgDgPIgCgTIgBgSQAAgKACgJQABgJAGgHQAFgIAHgHIAOgKQAIgFAJgCQALgCAFAKQABgHAJgCQAHgDAJgBIAUAAIATADQAJACAIAGQAIAGAGAIIAIAQQAEAJgCAKIgFASIgDAFIAEgEIADgDQACAJAKACIAIADQAIAGAFAIIACAKQAAAEAAAEQAAAJgDAIIgHASIgEAQIgCATQgBAKgFAKIAAAGIgBAEQAAAJgHAHQgHAGgHAEIgRAIQgHAEgJAAIgBAAIgBAAgAggABIAPALQAIAFAJACQAHACAJAAIAUAAQAKAAAIgFIAQgIQAJgEAHgEQAIgFAGgGQgGAGgIAFQgHAEgJAEIgQAIQgIAFgKAAIgUAAQgJAAgHgCQgJgCgIgFIgPgLQgIgDgDgHQACgDAGgCQgGACgCADQgCADgBAEIAAACIAAACIAAgCIAAgCQABgEACgDQADAHAIADgAAZghIABAAIARgCIASgFQAIgDAAgJIgBgCQAAgIgHgCIgBgBQgHgCgHAAIgBAAIAAAAIgBAAIgCAAIgFAAIAFAAIACAAIABAAIAAAAIABAAQAHAAAHACIABABQAHACAAAIIABACQAAAJgIADIgSAFIgRACIgBAAIgBAAIAAAAQgHgBgFgDQgIgGAAgJQAAAJAIAGQAFADAHABIAAAAIABAAgAgshaQgEAJACAKQADAJAGAGQAGAGALAAQAIgBAGgEQADgEAAgHIAAgCQAAgKgFgGIgBgBIgEgGIgFgGQgBgCgEABIgGgBQgLAAgEAJgAA4h0QgKABgHAGQgGAGgCAKQgBAKAIAFQAIAEAJgCQAJgDACgIQABgIgBgHIAAgFQgBgDgCgEQgDgEgCAAQAAAAAAABQgBAAAAAAQAAAAgBAAQAAABAAAAgAg7hjIgBgFIAAgCQAAgJAKgFIABAAIAGgCIABAAIAAAAQAFAAAEADQgEgDgFAAIAAAAIgBAAIgGACIgBAAQgKAFAAAJIAAACIABAFgAASiGIAAgBIABgBQAEgFAGAAIABAAIAAAAIAAAAIABAAIACAAQAHACABADQgBgDgHgCIgCAAIgBAAIAAAAIAAAAIgBAAQgGAAgEAFIgBABIAAABgAgrgJIAAAAg");
	this.shape_20.setTransform(0.5,2.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_8},{t:this.shape_7},{t:this.shape_2},{t:this.shape_6}]},2).to({state:[{t:this.shape_5},{t:this.shape_11},{t:this.shape_10},{t:this.shape_2},{t:this.shape_9}]},2).to({state:[{t:this.shape_5},{t:this.shape_14},{t:this.shape_13},{t:this.shape_2},{t:this.shape_12}]},2).to({state:[{t:this.shape_5},{t:this.shape_8},{t:this.shape_7},{t:this.shape_2},{t:this.shape_6}]},2).to({state:[{t:this.shape_5},{t:this.shape_14},{t:this.shape_13},{t:this.shape_2},{t:this.shape_12}]},1).to({state:[{t:this.shape_5},{t:this.shape_16},{t:this.shape_3},{t:this.shape_2},{t:this.shape_15}]},2).to({state:[{t:this.shape_5},{t:this.shape_18},{t:this.shape_13},{t:this.shape_2},{t:this.shape_17}]},2).to({state:[{t:this.shape_5},{t:this.shape_20},{t:this.shape_3},{t:this.shape_2},{t:this.shape_19}]},6).wait(1));

	// Layer 2
	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#000000").ss(1,1,1).p("AD+j9QBqBpAACUQAACVhqBpQhpBqiVAAQiUAAhphqQhqhpAAiVQAAiUBqhpQBphqCUAAQCVAABpBqg");
	this.shape_21.setTransform(0,1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#0000FF").s().p("Aj9D+QhqhqAAiUQAAiUBqhpQBqhpCTgBQCUABBqBpQBqBpAACUQAACUhqBqQhqBqiUgBQiTABhqhqg");
	this.shape_22.setTransform(0,1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_22},{t:this.shape_21}]}).wait(20));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-37,-36,74,74);


(lib.goNext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,11.3).s().p("AhLAqQghgSACgYQgCgXAhgRQAggTArAAQAsAAAgATQAfARAAAXQAAAYgfASQggASgsAAQgrAAgggSg");
	this.shape.setTransform(22.8,8.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.502)").s().p("AhThcICoBdIioBcg");
	this.shape_1.setTransform(25.1,20.4);

	this.blinker = new lib.general_buttoncolor();
	this.blinker.setTransform(23.4,20.1,1.5,1.5,0,0,0,11.9,11.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,14.8).s().p("AhiA3QgrgXACggQgCgfArgWQApgYA5AAQA5AAAqAYQAqAWAAAfQAAAggqAXQgqAXg5AAQg5AAgpgXg");
	this.shape_2.setTransform(23.4,8.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("rgba(0,0,0,0.502)").ss(1,1,1,3,true).p("AAACxQhIAAg0g0Qg0g1AAhIQAAhHA0g1QA0g0BIAAQBJAAA0A0QA0A1AABHQAABIg0A1Qg0A0hJAAg");
	this.shape_3.setTransform(23.3,20.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["rgba(103,103,103,0.839)","rgba(134,134,134,0)"],[0.678,0.918],-0.8,0,0,-0.8,0,24.9).s().p("AisCkQhFhEAAhgQAAhgBFhDQBEhFBhAAQBfAABBAwQBCAwAVCqQAVCskMAbQhhAAhEhFgAgHCQQBEAAAzgwIABAAIADgEQA0g0AAhHQAAhJg0g0IgFgFIgBgBQgyguhDAAIAAAAIgBAAIAAAAIgBAAQhEAAgyAuIgBABIgCACIgBABIAAAAIgCACQg0A0AABJQAABHA0A0IACACIABABQAzAxBHAAIAAAAIAAAAIAAAAIAAAAQhHAAgzgxIgBgBIgCgCQg0g0AAhHQAAhJA0g0IACgCIAAAAIABgBIACgCIABgBQAyguBEAAIABAAIAAAAIABAAIAAAAQBDAAAyAuIABABIAFAFQA0A0AABJQAABHg0A0IgDAEIgBAAQgzAwhEAAIAAAAIgBAAIABAAIAAAAg");
	this.shape_4.setTransform(24.2,23.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},2).wait(1));

	// Layer 2
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#33FFFF").s().p("AioCqQhGhHAAhjQAAhiBGhGQBGhHBiAAQBjAABGBHQBHBGgBBiQABBjhHBHQhGBGhjAAQhiAAhGhGg");
	this.shape_5.setTransform(24.4,21.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0099FF").s().p("AioCqQhGhHAAhjQAAhiBGhGQBGhHBiAAQBjAABGBHQBHBGgBBiQABBjhHBHQhGBGhjAAQhiAAhGhGg");
	this.shape_6.setTransform(24.4,21.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.5,46.7);


(lib.intro = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_25 = function() {
		this.stop();
		playSound("high_blip");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(25).call(this.frame_25).wait(81));

	// Layer 15
	this.instance = new lib.Tween23("synched",0);
	this.instance.setTransform(58.1,-245);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(15).to({_off:false},0).to({scaleX:0.59,scaleY:0.59,x:47.1,y:-120},10).wait(81));

	// Layer 14
	this.instance_1 = new lib.micktalk();
	this.instance_1.setTransform(43,26,1,1,0,0,0,0,1);

	this.instance_2 = new lib.MicStill();
	this.instance_2.setTransform(43.5,26.5,2.195,2.195,0,0,0,36,36);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).to({state:[{t:this.instance_1}]},20).to({state:[{t:this.instance_2}]},1).wait(85));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:2.19,scaleY:2.19},20).to({_off:true},1).wait(85));

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.3,1,1).p("EAjigWkMAAAAtJMhHDAAAMAAAgtJg");
	this.shape.setTransform(46.5,-9.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FFFFFF","#FF3366"],[0,1],-0.8,227.4,0.9,-227.3).s().p("EgjhAWlMAAAgtIMBHDAAAMAAAAtIg");
	this.shape_1.setTransform(46.5,-9.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(106));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-182,-154.6,457,291);


// stage content:



(lib.diag_Scene0 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{scene0:0,Scene0Repeat:20});

	// timeline functions:
	this.frame_0 = function() {
		playSound("BeautifulDrumnbass",-1);
		playSound("learntodiagram");
		this.btn_menu.addEventListener("click", openMenu.bind(this));
		this.btn_goNext.addEventListener("click", openNext.bind(this));
		
		function openMenu(){
		
		 window.open ("../menu/menu.html","_self");
		}
		
		function openNext(){
		
		 window.open ("diag_Scene1.html","_self");
		}
		
		/*function openPrev(){
		
		 window.open ("puzzle_aux.html","_self");
		}*/
	}
	this.frame_126 = function() {
		/* gotoAndPlay("scene0Repeat");
		*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(126).call(this.frame_126).wait(1));

	// Main
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(4,1,1).p("EAjoAWkMhHPAAAMAAAgtHMBHPAAAg");
	this.shape.setTransform(274,187.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(127));

	// Layer 3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgjrAWzMAAAgtlMBHXAAAMAAAAtlg");
	mask.setTransform(274.5,188);

	// Layer 1
	this.instance = new lib.intro();
	this.instance.setTransform(274,184,1,1,0,0,0,46,-12.7);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(127));

	// button
	this.btn_menu = new lib.skiptomenu();
	this.btn_menu.setTransform(514.1,20.3);
	new cjs.ButtonHelper(this.btn_menu, 0, 1, 2, false, new lib.skiptomenu(), 3);

	this.instance_1 = new lib.Copyright("synched",0);
	this.instance_1.setTransform(275,393.5);

	this.btn_goNext = new lib.goNext();
	this.btn_goNext.setTransform(494,352.3);
	new cjs.ButtonHelper(this.btn_goNext, 0, 1, 2, false, new lib.goNext(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.btn_goNext},{t:this.instance_1},{t:this.btn_menu}]}).wait(127));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(319,201.8,502.3,401.2);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;