(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 550,
	height: 400,
	fps: 12,
	color: "#FFFFFF",
	webfonts: {},
	manifest: [
		{src:"sounds/wrong_answer.mp3", id:"wrong_answer"},
		{src:"sounds/Flying.mp3", id:"Flying"},
		{src:"sounds/right_answer.mp3", id:"right_answer"},
		{src:"sounds/thediagramformconsistsof2.mp3", id:"thediagramformconsistsof2"}
	]
};



lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib.Tween7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("AAABNIAAiZ");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-8.7,2,17.4);


(lib.Tween5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.3,1,1).p("AAAhNIAACb");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-8.8,2,17.7);


(lib.Tween3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.8,1,1).p("AhtAAIDbAA");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-12,-1,24,2);


(lib.skiptomenu = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AATApQgLAGgMAAQgMAAgHgFQgJgGgBgKQgEgYABgQQgBgMADgPQABgIAHAAQAEAAADADQACACAAAEIgBANIgBANIABAXQABALACAGIAGADIAFAAQAKAAANgDIAAgSIgBgPQAAgTACgOQABgIAIAAQADAAADACQADADgBADIgBAhIAAARIAAATIAAAGIAAAGQABAEgDACQgDADgDAAQgHAAgCgJg");
	this.shape.setTransform(16.7,0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AAVAqIgDgTIgBgTIABgGIAAgJQAAgSgHgBQgKAAgHAMQgIALgFAOIgBAIIAAAJIAAAIIABAIQAAAEgCADQgDACgEAAQgDAAgDgCQgCgDAAgEIgBgIIAAgIIABgYIABgYIAAgIIAAgJQAAgDACgDQADgDADABQAIAAABALIAAAKQAPgUAOAAQAOAAAFANQAEAIAAAQIAAAJIAAAGIACATQACAMAAAHQAAAEgCADQgDABgEAAQgHABgBgJg");
	this.shape_1.setTransform(7.5,0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgdAmQgNgMAAgTQAAgVALgQQAMgQATgBQAOAAAJAGQALAFAAANQAAAJgKAHQgEADgOAFIggAQQAFAIAHADQAIADAIAAQAGAAAIgBQAKgDADgFQADgFAEAAQADAAACADQACACAAADQAAAKgPAGQgOAHgMAAQgSAAgNgKgAgRgWQgHAIgDAPIAbgLQAOgIAGgFQgHgIgNAAQgKABgHAIg");
	this.shape_2.setTransform(-2.2,0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgEAzQgCgCAAgEIgCggIgCgdQAAgJgDgGQgGADgHAHIgKALIgEAGIgBANIgBAPIAAAIIABAHQAAADgCADQgDACgEAAQgKAAAAgWIABgQIABgOIAAgOIgBgOQAAgUAJAAQADAAADADQADADAAAEIgBAFIAAAFIAAAJQAFgJAIgIQAJgHAHAAQANAAAEAOQAEgHAHgDQAHgDAIAAQAPAAAFAQQACADACAVIAGAxQABADgDADQgDACgDAAQgIAAgBgIIgDgbIgDgZQgBgGgCgGQgDgIgDAAQgEAAgJAGQgIAFgDADIABAQIACAWQACAOAAAJQAAAEgCACQgDADgEAAQgBAAgDgDg");
	this.shape_3.setTransform(-14.1,0.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(2,1,1).p("AkZh7IIzAAIAAD3IozAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AkZB8IAAj3IIzAAIAAD3g");

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAVAuQgMAGgOAAQgMAAgJgGQgJgGgBgMQgEgZAAgSQAAgNADgRQABgJAIAAQAEAAADADQADADAAAEIgCAOIgBAPIABAZQABAMACAHIAGADIAGAAQALAAAPgEIAAgTIAAgRQAAgVABgPQABgJAJAAQAEAAADACQADADgBAEIgBAlIAAATIAAAVIAAAGIAAAHQAAAEgCACQgDADgEAAQgIAAgCgJg");
	this.shape_6.setTransform(18.3,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AAXAvIgDgWIgBgVIAAgHIABgJQAAgVgIAAQgLAAgIANQgJALgFAQIgBAKIAAAJIAAAJIABAJQAAAEgDADQgCACgFAAQgEAAgCgCQgDgDAAgEIgBgJIAAgJIABgaIACgbIgBgJIAAgJQAAgFADgCQACgDAEAAQAJAAABANIAAALQARgWAPAAQAPAAAGAOQAFAJAAASIAAAKIAAAHQAAAIACAMQACANAAAIQAAAEgDADQgDADgEAAQgIAAgBgJg");
	this.shape_7.setTransform(8.2,0.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AggApQgPgMAAgWQAAgXAMgRQAOgSAVAAQAPAAAKAFQANAHAAAOQAAAJgMAIQgEAEgQAFIgjASQAFAIAJAEQAIAEAJAAQAHAAAIgDQALgDAEgFQADgFAEAAQADAAADACQADADAAADQAAALgRAIQgPAGgOAAQgVAAgNgLgAgTgZQgHAJgEARIAdgMQAQgJAIgGQgJgIgOAAQgLAAgIAJg");
	this.shape_8.setTransform(-2.4,0.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgEA5QgDgDAAgFQAAgLgCgXQgDgVAAgMQAAgKgCgGQgHADgHAHIgMANIgEAGIgCAPIgBARIABAIIABAIQAAAEgDACQgDADgEAAQgLAAAAgZIACgRIABgPIgBgQIgBgPQAAgWAKAAQADAAAEADQADAEAAADIgBAGIAAAGIAAAKQAFgKAKgJQAJgIAHAAQAPAAAEAPQAGgHAHgDQAHgEAKAAQAQAAAGARIAEAcIAHA1QAAAEgDADQgDACgEAAQgIAAgBgIQgCgLgCgTIgDgcIgDgNQgEgJgEAAQgDAAgKAGQgJAGgDADIAAASIADAYQACAQAAAJQAAAFgCADQgDACgEAAQgCAAgDgCg");
	this.shape_9.setTransform(-15.6,0.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#000000").ss(2,1,1).p("AE3CJIptAAIAAkRIJtAAg");
	this.shape_10.setTransform(0,0.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#00FFFF").s().p("Ak2CJIAAkRIJsAAIAAERg");
	this.shape_11.setTransform(0,0.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AATApQgLAGgMAAQgMAAgHgFQgJgGgBgKQgEgYABgQQgBgMADgPQABgIAHAAQAEAAADADQACACAAAEIgBANIgBANIABAXQABALACAGIAGADIAFAAQAKAAANgDIAAgSIgBgPQAAgTACgOQABgIAIAAQADAAADACQADADgBADIgBAhIAAARIAAATIAAAGIAAAGQABAEgDACQgDADgDAAQgHAAgCgJg");
	this.shape_12.setTransform(16.7,1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAVArIgDgUIgBgTIABgHIAAgHQAAgUgHAAQgKAAgHAMQgIALgFAOIgBAJIAAAIIAAAIIABAIQAAAEgCACQgDACgEAAQgDAAgDgCQgCgCAAgEIgBgIIAAgIIABgYIABgYIAAgJIAAgIQAAgEACgCQADgCADgBQAIAAABAMIAAAKQAPgTAOgBQAOAAAFANQAEAIAAARIAAAIIAAAGIACAUQACALAAAHQAAAEgCACQgDACgEABQgHgBgBgHg");
	this.shape_13.setTransform(7.5,0.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgdAlQgNgLAAgTQAAgVALgPQAMgSATABQAOAAAJAEQALAHAAAMQAAAJgKAHQgEADgOAFIggAQQAFAHAHAEQAIAEAIAAQAGgBAIgCQAKgDADgEQADgFAEAAQADAAACACQACACAAAEQAAAJgPAIQgOAFgMAAQgSAAgNgKgAgRgWQgHAIgDAPIAbgLQAOgIAGgGQgHgGgNgBQgKAAgHAJg");
	this.shape_14.setTransform(-2.2,0.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgEAzQgCgCAAgEIgCggIgCgdQAAgJgDgGQgGADgHAHIgKALIgEAGIgBANIgBAPIAAAIIABAHQAAADgCADQgDACgEAAQgKAAAAgWIABgQIABgOIAAgOIgBgOQAAgUAJAAQADAAADADQADADAAAEIgBAFIAAAFIAAAJQAFgJAIgIQAJgHAHAAQANAAAEAOQAEgHAHgDQAHgDAIAAQAPAAAFAQQACADACAVIAGAxQABADgDADQgDACgDAAQgIAAgBgIIgDgbIgDgZQgBgGgCgGQgDgIgDAAQgEAAgJAGQgIAFgDADIABAQIACAWQACAOAAAJQAAAEgCACQgDADgEAAQgBAAgDgDg");
	this.shape_15.setTransform(-14.1,1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#000000").ss(2,1,1).p("AEah7IAAD3IozAAIAAj3g");

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#0066CC").s().p("AkZB8IAAj3IIzAAIAAD3g");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},1).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12}]},1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-29.2,-16.9,58.6,30.5);


(lib.general_buttoncolor = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{resetRed:1});

	// timeline functions:
	this.frame_0 = function() {
		this.play();
	}
	this.frame_8 = function() {
		this.gotoAndPlay("resetRed");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(8).call(this.frame_8).wait(2));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#D5FFD7","#61EF01","#1DA400","#004A00"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgvAAgjgjQgjgjAAgwQAAgvAjgjQAjgjAvAAQAwAAAjAjQAjAjAAAvQAAAwgjAjQgjAjgwAAIAAAAg");
	this.shape.setTransform(11.9,11.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FFFFFF","#EC0000","#9D0000","#480000"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgvAAgjgjQgjgjAAgwQAAgvAjgjQAjgjAvAAQAwAAAjAjQAjAjAAAvQAAAwgjAjQgjAjgwAAIAAAAg");
	this.shape_1.setTransform(11.9,11.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},8).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,23.7,23.6);


(lib.Copyright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAbAHIgDgKIgEAKQgEAIgDAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBgBAAgBIgCgIIgBgHQgGASgCAAIgDgBIgBgCIABgCQADgFABgFIACgNQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAEAAACAJIADAKIACgGIADgJQADgEACAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAEAKIACAGIACAIIABACIgBACIgCABQgDAAgDgJgAgTANIgBgIIAAgGIgBgHIgFAAIgGAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAgBAAAAQAAgBAAgBQAAAAABgBQAAAAABgBQAAAAABAAIAFABIAEAAIAPAAIADgBIAEAAQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAABAAAAQAAAAAAABQAAAAgBAAIgOAAIAAAIIABAFIABAEIABAEIgCACIgCABQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAgBAAAAg");
	this.shape.setTransform(57.3,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgLAYQgGgDgBgEIABgDQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAIAEACIAEABIAFABIAFgBQADgBAAgDQABgGgJgCIgCgBIgIgDQgEAAAAgFQAAgKAIgEIAHgCIAIgDIAEgBIADABIABAEIABADIAAAEIgBADIgCABQgBAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIgCgFIgJADQgFADgBAEIADABQAIACAFACQAHADAAAJQAAAHgGAEQgFADgGAAQgFAAgGgCg");
	this.shape_1.setTransform(51,2.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgLATQgHgGABgKQAAgGAFgKQAHgKAGAAQAEAAAGACQAGACABAEIgBADQgBAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgDgBIgBgBQgDgCgGAAQgCAAgFAIQgDAHAAADQAAAGADAEQAEADAEAAIAGgCIAEgCIACgBIAEABIABADQgBADgGADQgGADgEAAQgHAAgGgFg");
	this.shape_2.setTransform(46.6,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgDAfQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAAAIAAgJIAAgIIAAgKIAAgIQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBIACgBIACABQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABIAAAIIgBAKIAAAIIABAJQAAAAAAAAQAAABgBAAQAAABAAAAQAAAAgBAAIgBABIgDgBgAgBgXQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQAAAAAAAAQAAAAAAgBQABABAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBAAAAgBg");
	this.shape_3.setTransform(43.1,1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAKAVIgBgJIgBgKIABgDIAAgDQAAgKgEAAQgFAAgCAFQgEAGgCAGIgBAEIAAAFIAAADIAAAFIgBADIgDABIgDgBIgBgDIAAgFIgBgDIABgMIAAgLIAAgFIAAgEIABgDIAEgBQAEAAAAAFIAAAGQAHgKAGAAQAHAAADAGQACAEAAAJIAAAEIAAACIABAKIABAJIgBADIgDABQgEAAgBgEg");
	this.shape_4.setTransform(39.5,2.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_5.setTransform(34.8,2.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AALAhIgBgLIgBgKIAAgDIAAgEQAAgGgEAAQgFAAgDADIgGAKQAAARgCACQAAABgBABQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDIABgBIAAgHIAAgHIAAgeIABgHIgBgFIAAgEQAAAAAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQAEAAAAAEIABAIIAAAKIAAAJIAAAEQADgFAEgCQACgDAFAAQAHAAADAFQABADABAGIABAJIAAAIIACAKIAAABQAAABAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIgDABQgEAAgBgDg");
	this.shape_6.setTransform(30,1.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgLATQgHgGABgKQAAgGAFgKQAHgKAGAAQAEAAAGACQAGACABAEIgBADQgBAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgDgBIgBgBQgDgCgGAAQgCAAgFAIQgDAHAAADQAAAGADAEQAEADAEAAIAGgCIAEgCIACgBIAEABIABADQgBADgGADQgGADgEAAQgHAAgGgFg");
	this.shape_7.setTransform(25,2.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgOATQgGgGAAgKQAAgKAFgHQAGgJAJAAQAGABAFACQAGADAAAHQAAAEgFADIgKAEIgOAHQACAEAEABQAEADACAAIAIgBQAFgCABgDQABAAAAAAQAAgBABAAQAAAAABAAQAAAAAAAAIADAAIABADQAAAFgIADQgGADgHABQgIgBgGgEgAgIgKQgDAEgCAGIANgFQAGgDAEgDQgEgDgGgBQgEAAgEAFg");
	this.shape_8.setTransform(20.3,2.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAaAgIgCgGIgBgIQgCgHgEgWIgJAYIgDAJIgDAIQgBAEgCAAQgDgBgBgDIgCgEIgBgFIgIgfIgCAHIgFAWIgCAMQgBAEgDAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgEQAAgHADgLIAFgPIADgOQACgKABgDQACgCADAAQACAAACADQACAEABAMQADAOAFAPQAFgPAEgSIACgGIACgHQABgDADAAQAEAAACAIIACAKQADASADAOIACAHIACAHQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgCABQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBgBg");
	this.shape_9.setTransform(13.8,1.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgQAUIAAgdIAAgEIABgFQAAgEADAAQAFAAAAAHQAHgIAKAAQADAAACADQACACAAAGIAAADQgBAFgEAAQgEAAAAgEIAAgDIAAgEQgHABgCADQgEADgDAGIABAWQAAAEgFAAQgEAAAAgEg");
	this.shape_10.setTransform(5.1,2.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_11.setTransform(0.5,2.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgBAZQAAAAgBAAQAAgBAAAAQAAAAAAgBQgBAAAAgBIgBgPIgBgOQAAgFgBgCQgDABgDADIgFAGIgDADIAAAGIgBAHIABAEIAAADQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABQgFAAAAgLIAAgIIABgGIgBgHIAAgHQAAgKAFAAIACACQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAADIgBACIAAAFQADgFAEgDQAFgEADAAQAGAAACAHQACgEADgBQAEgCAEAAQAHAAADAIIACAMIADAYIgBADIgDABQgEAAgBgEIgBgOIgCgLIgBgGQgCgEgCAAIgFADIgGAEIAAAHIABALIABALIgBADIgDACQAAAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBg");
	this.shape_12.setTransform(-5.2,2.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgBAZQAAAAgBAAQAAgBAAAAQAAAAAAgBQgBAAAAgBIgBgPIgBgOQABgFgCgCQgDABgDADIgFAGIgCADIgBAGIgBAHIABAEIABADQAAABgBAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABQgFAAAAgLIABgIIAAgGIAAgHIgBgHQAAgKAEAAIADACQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAADIgBACIAAAFQADgFAEgDQAFgEADAAQAGAAABAHQADgEADgBQADgCAFAAQAHAAADAIIACAMIADAYIgCADIgCABQgEAAgBgEIgCgOIgBgLIgBgGQgCgEgCAAIgFADIgGAEIAAAHIABALIABALIgBADIgDACQAAAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBg");
	this.shape_13.setTransform(-12.2,2.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_14.setTransform(-18.1,2.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgQAUIAAgdIAAgEIABgFQAAgEADAAQAFAAAAAHQAHgIAKAAQADAAACADQACACAAAGIAAADQgBAFgEAAQgEAAAAgEIAAgDIAAgEQgHABgCADQgEADgDAGIABAWQAAAEgFAAQgEAAAAgEg");
	this.shape_15.setTransform(-22.4,2.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgVAeQgFgGgBgMQABgMAFgKQAFgMAIgIQAHgEAEAAQAEAAAGACQAIAEAAADIgBADIgEABIgCgBQgHgDgEAAQgDgBgCAEIgGAGQgKAOAAAOQABAIACADQACAEAIAAQAGgBAGgFQAGgEACgLQgMABgGAEIgDABQAAgBAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQAIgEAXAAIADABIABACQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQgDANgIAJQgJAHgKABQgKgBgGgFg");
	this.shape_16.setTransform(-27.7,1.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgNAhIgBgDIACgJIAKgWQAFgOAHgIIABgBIgVAAIgJgBQgFAAAAgEQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAQAAIAPABIAIAAQAFAAAAACQAAADgDADIgEAFQgGAGgFAKIgHAPIgCAKIgEAKQgBABAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIgDgBg");
	this.shape_17.setTransform(-36.2,1.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AABAiIgHAAIgFgBQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQgBgEAIAAIACAAIABAAIAAgHIgBgGIABgPIABgRQgFAFgCAAIgDgBIgBgDQAAgDADgCIAHgGQACgEAEAAQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAADIAAADIAAAEIAAAEIgBAPIgBANIAAAGIABAGIAFAAQAAAAAAAAQABAAAAABQABAAAAAAQAAAAABABIAAADIAAADIgDABg");
	this.shape_18.setTransform(-41,1.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgSAXQgFgKAAgNQAAgMAGgKQAHgMAKAAQAMABAGAJQAGAJAAANQAAARgGAKQgGAJgMAAQgMABgGgMgAgLgRQgEAIAAAJQAAAMAEAHQAEAHAHAAQAIABAEgLQADgIAAgJQAAgMgDgGQgEgGgIAAQgGAAgFAIg");
	this.shape_19.setTransform(-45.9,1.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AANAhIgDgBIgHAAIgFABIgFAAIgFAAIgBAAIgCAAQgDAAgBgDIAAgFQAAgKAGgHQACgDALgFIAHgHQADgEAAgGQAAgDgDgCQgDgCgDAAQgDAAgDADIgGAEIgDACQgFAAAAgEQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAFgFAEgCQAFgDAEAAQAHAAAFAEQAGAEAAAHIgBAIIgEAHQgDACgIAFQgGAFgDADQgFAFABAHIAJgBIALAAIAGABQAEABAAADQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAIgDABIgDAAg");
	this.shape_20.setTransform(-51.3,1.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgeAAQAAgKALgJQALgKALAAQAOAAAHAIQAHAIAAAMQAAAJgJAKQgKALgMAAIAAABQgeAAAAgegAgOgOQgIAGAAAIQAAAMAGAFQAGAEAKAAQAJAAAIgIQAGgIAAgGQAAgJgEgFQgFgGgIAAIgCAAQgKAAgIAHgAgKAJQgGgEAAgFQAAgGAIgFQAGgFAFAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAIgCgBIgBAAQgDAAgEADQgEACAAADQAAABADACIAFABQABAAAEgCIAEgCIADAAIABADQAAADgEADQgGADgDAAQgFAAgFgDg");
	this.shape_21.setTransform(-57.7,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.3,-7.1,126.6,16.6);


(lib.text_predicate = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#993300").s().p("AgcAlQgPgLgBgTQAAgVAMgQQAOgQATAAQAPAAALAEQANAHAAAOQAAAKgLAHQgFADgPAFIgbANQAEAFAGACQAGACAGAAQALAAAJgFQAHgEAEAAQAKAAAAAJQgBAKgOAHQgNAEgNAAQgTABgNgLgAgKgTQgHAFgDAKIAUgIIARgKQgGgDgKAAQgGAAgFAGg");
	this.shape.setTransform(141.8,17.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#993300").s().p("AgHA9QgDgDAAgFIAAgKIAAgJIgBgsIgRgBQgLgBAAgKQAAgFADgEQAEgDAFAAIAPABIAAgJIAAgJQgBgFAEgDQAEgEAEAAQAMAAAAAWIAAAIIAJgBQAJAAAEABQAHADAAAIQAAAFgEADQgDADgFAAIgFAAIgDAAIgJABIACAsIAAAFIAAAFQAAAUgNAAQgDAAgEgDg");
	this.shape_1.setTransform(132.6,16);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#993300").s().p("AAVAoIgPAGQgGACgCAAQgVAAgLgLQgKgMAAgWQAAgUAPgOQAQgQAUAAQAIAAALAFQANAGAAAHQAAADgCADIgBAJIgBAMQAAAOADAIIAEAJIADAIQAAAFgDADQgEADgEAAQgEAAgJgIgAgLgRQgJAKAAALQAAALAEAGQAEAGAJAAQADAAAFgCQAFgCAEgDQgCgUAAgKIAAgGIABgIIgDgCIgCAAQgKAAgJAJg");
	this.shape_2.setTransform(123.4,17.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#993300").s().p("AgaAmQgOgMAAgSQAAgQAMgSQAPgWAQAAQAKAAALAFQAQAGgBAIQAAAEgCADQgDAEgFAAQgEAAgGgEQgFgEgLAAQgEAAgJANQgHANAAAIQAAAIAGAGQAHAFAIAAQAHAAAIgFQAJgEABAAQAFAAAEADQADAEAAAEQAAAHgPAHQgNAGgJAAQgRAAgNgLg");
	this.shape_3.setTransform(113.6,17.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#993300").s().p("AgKA/QgDgDAAgFIgBgQIAAgQIABgUIABgSQAAgFAEgDQADgDAFAAQADAAAEADQADADAAAFIAAASIgBAUIAAAQIAAAQQAAAFgEADQgDADgDABQgGgBgDgDgAgHgsQgEgDAAgGQAAgFAEgEQAFgEADABQAGgBAEAEQAEAEAAAFQAAAGgEADQgEAEgGABQgDgBgFgEg");
	this.shape_4.setTransform(106.8,15.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#993300").s().p("AAYBCQgGADgHABIgLABQgUAAgNgMQgNgNAAgUQAAgXANgNQAOgPATAAQAHAAAFACIAJAEQABgeACgLQABgLAKAAQAFAAAEAEQADADAAAFIgCAnIgCAjQAAAgACALIAAACQAAAFgDAEQgEACgFAAQgGAAgDgFgAgRAEQgGAHAAAPQAAAJAHAHQAHAHAJAAQAFAAADgBIAIgGIADgDIAAggQgDgGgEgBQgFgCgGAAQgLAAgHAGg");
	this.shape_5.setTransform(98.7,15.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#993300").s().p("AgdAlQgOgLAAgTQAAgVALgQQANgQAVAAQAOAAALAEQANAHAAAOQAAAKgLAHQgEADgPAFIgcANQAEAFAGACQAGACAGAAQAMAAAHgFQAIgEAFAAQAIAAABAJQAAAKgPAHQgMAEgOAAQgTABgOgLgAgLgTQgFAFgEAKIAUgIIARgKQgGgDgJAAQgHAAgGAGg");
	this.shape_6.setTransform(88.4,17.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#993300").s().p("AgiAtQgCgDAAgFIAAg4IAAgIIAAgIQAAgFADgDQADgDAFAAQAKAAACAKQAOgMASAAQASAAAAAXIAAAGQAAAOgMAAQgLAAAAgMIAAgIQgSADgJARIAAAqQAAAFgEADQgDAEgFAAQgGAAgDgEg");
	this.shape_7.setTransform(79.3,17.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#993300").s().p("AgnBDQgDgEAAgEIAAgZIACgmIACgpQAAgXAMABIAJgBIAMgBQAQAAAPAMQARAMAAASQAAAWgSAMQgQALgUAAIgHAAIgBApQAAAEgDAEQgDACgFAAQgFAAgEgCgAgPguIAAANIgCAeIAGABQAMAAAJgHQAJgHAAgLQAAgIgJgFQgIgGgJAAIgEAAIgEAAg");
	this.shape_8.setTransform(70.1,15.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#993300").s().p("AgdAlQgOgLAAgTQAAgVAMgQQAMgQAVAAQAOAAALAEQANAHAAAOQAAAKgKAHQgFADgPAFIgcANQAEAFAGACQAGACAGAAQALAAAIgFQAIgEAFAAQAIAAABAJQAAAKgPAHQgMAEgOAAQgTABgOgLgAgLgTQgFAFgEAKIAUgIIARgKQgGgDgJAAQgHAAgGAGg");
	this.shape_9.setTransform(52.3,17.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#993300").s().p("AgHA9QgDgDAAgFIAAgKIABgJIgDgsIgPgBQgMgBAAgKQAAgFAEgEQADgDAFAAIAPABIgBgJIAAgJQAAgFAEgDQADgEAGAAQALAAgBAWIAAAIIAJgBQALAAADABQAHADAAAIQAAAFgEADQgCADgGAAIgEAAIgFAAIgIABIABAsIAAAFIAAAFQAAAUgMAAQgDAAgEgDg");
	this.shape_10.setTransform(43.1,16);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#993300").s().p("AgdAlQgPgLAAgTQAAgVANgQQANgQAUAAQAOAAALAEQANAHAAAOQAAAKgKAHQgGADgOAFIgcANQAEAFAGACQAGACAGAAQAMAAAHgFQAIgEAEAAQAJAAAAAJQAAAKgOAHQgNAEgNAAQgTABgOgLgAgLgTQgFAFgEAKIAUgIIARgKQgGgDgJAAQgHAAgGAGg");
	this.shape_11.setTransform(33.7,17.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#993300").s().p("AgHBEQgEgDAAgFIAAh3QAAgGAEgDQADgDAEAAQAFAAADADQADADAAAGIAAByQABARgMAAQgEAAgDgEg");
	this.shape_12.setTransform(26.3,15);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#993300").s().p("AgkBGQgCgDAAgFIAAghIAAghIgBghIgCgRQAAgHADgFQAEgGAGAAQAFAAAEADQADADAAAFIAAABIAMgFQAEgCAFAAQAVAAAJARQAHANAAAVQAAARgLANQgMANgTAAIgOgBIAAAkQAAAFgEADQgEADgFAAQgFAAgEgDgAgDgpQgHADgFAFIABAiQAIADAGAAQAJAAAFgEQAEgGAAgKIgBgRQgDgKgJAAQgFAAgDACg");
	this.shape_13.setTransform(19.2,19.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#993300").s().p("AgGAyQgEgDAAgFIgCgdIgCgcIgBgJQgKAGgKAOIgCABIAAAaIAAAHIgBAGQAAAFgEADQgDACgFAAQgIAAgCgGQgCgFAAgJIAAgfIgBgNIAAgNQAAgIADgGQADgIAHAAQAFAAADAEQAEAEAAAEIgBAIQAOgPAMAAQANAAAEAKQAGgFAGgCQAHgDAHAAQASAAAGASQABADADAUIAGAuQAAAFgEADQgDADgFAAQgLAAgBgKIgEgZIgCgYQgDgQgDAAQgDAAgHAEIgKAHQAAAKACARQADATAAAKQAAAFgEADQgDAEgGAAQgDAAgDgEg");
	this.shape_14.setTransform(7.4,17.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#993300").s().p("AgcAkQgMgLgBgVQgBgRAMgPQANgTAWABQARAAALANQAJANAAATQAAASgLAPQgMAPgTAAQgQAAgMgLgAgLgOQgGAJAAAJQAAAKAGAGQAFAEAGABQAGAAAGgGQAGgFABgLQABgagQgBQgJABgGAJg");
	this.shape_15.setTransform(-4.5,17.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#993300").s().p("AgmA1QgNgOAAgSQAAgcAagfQAWgaAVAAIAHAAIAFABQAEgDAFAAQAJAAADAKIABARQAAAFgDADQgDAFgGAAQgIAAgEgJQgCgEgBAAQgCgBgFAAQgLAAgNASQgUAWAAAVQAAAJAGAHQAHAHAJAAQAGAAAJgFIAOgIQAGgFAEAAQAFAAAEAEQADAEAAAEQAAAGgEADQgYAVgXgBQgUAAgOgOg");
	this.shape_16.setTransform(-14.6,15.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#993300").s().p("AgdAlQgOgLAAgTQAAgVAMgQQAMgQAVAAQAOAAALAEQANAHAAAOQAAAKgKAHQgFADgPAFIgcANQAEAFAGACQAGACAGAAQALAAAIgFQAIgEAFAAQAIAAABAJQAAAKgPAHQgMAEgOAAQgTABgOgLgAgLgTQgFAFgEAKIAUgIIARgKQgGgDgJAAQgHAAgGAGg");
	this.shape_17.setTransform(-33.2,17.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#993300").s().p("AAUBAQgCgHgCgNIgBgVIAAgGIAAgHIAAgHQgBgDgEAAQgJAAgGAHQgEAEgHANQAAAggEAGQgDAHgHAAQgFAAgEgDQgEgDAAgFIABgFQABgCAAgVIAAg5IAAgDIABgOIgBgIIgBgIQAAgFAEgDQADgEAGAAQAIAAADAKQACAFAAALIgBASIAAARQAGgGAIgEQAFgDAIAAQAPAAAHAJQAFAGABALIABAWIACARIADARIAAADQAAAFgEAEQgDADgFAAQgJAAgDgJg");
	this.shape_18.setTransform(-43.2,15.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#993300").s().p("AgHA/QgEgDAAgFIAAgEIABgEIgBgMIgBgMIgBgeIgDggIgFAAQgTAAgMgDQgJgCAAgJQAAgFADgEQADgEAGABIAOABIAOABIARAAIAOAAIAUABIAUABQAFAAAEADQADADAAAFQAAAFgDAEQgEADgFAAIgWgBIgVAAIACAjIACAiIABAJIAAAJQAAAGgCAGQgEAGgGAAQgEAAgDgDg");
	this.shape_19.setTransform(-54.6,15.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.1,0,212.1,29.1);


(lib.Dynamo_motion = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.3,1,1).p("A+To9QgDgCgDgCIAAAAQgagVgQghQgUgpgIguQgIgwAEgwQACgXgGgSQASAjAhAXQAfAXAlAcQAeAYArALQAuAMAjAaQAfAWASAgQAJAPAEANQASgNARgPQAdgaAsgJQARgDAXAAQgagig3gLQgUgEgQgHQArgSAwAPQAwANAaAaQALgmAngbQAhgXAngSQgHAlgTAkQgNAWgLAbQAtgGApAQQAoARAbAbQACADADADQAWAaALAmQAGAXAIATQADgzAVgkQAXgpAlgVQAkgUAvgOQAvgNAhgVQAJgFAKgHQgMApgGAwQAAABAAABQgGAmAIAuQAFAogFA0QgEAuglAfQgvAng1gcQgDgBgDgCQAAAAgBAAQgKgGABAAAr+i9QgFiIAMiCQAOiRgNiOQgMiIhxhPQh9hYhxgvQh+g0iKgPQiPgPiGAjQiGAihsA8QiCBIhBBqQhHB1gHCXQgGCIAECXQAECTgBCTQAAAJAAAJQgSAGgPAHQgpATgjAUQgjAWgsANQgqAOgfAYQggAbghAPQgnASghAaQgWATgWAUQgVATgaARIAAAAQAQAlAYAbQAbAeAXAmQAYAlAbAaQAcAZAdAjQAbAgApAcQAqAdAZAdQAbAgAtATQArASAjAQQAqATAnAXQAUAMAgARQAtAaAyAIQAxAIApAPQAmAOAuAIQAtAIAyAEQAyAFAyAGQAzAGAxAIQAyAIAtgEQAygFAzAGQAqAEAsgEQAEAAAEgBQACABADABQAeAMAhATQAgATAnANQADABACABQAjANAlAMQAqAOAtAMQAuAMAqAMQAqANAtALQAnAKAvAMQAwAMAwAIQAqAHAyAJQAxAJAvgHQAygHAvAAQAVAAAJgIQgLgFgLgGQgfgQglgZQgpgcgigiQgegegeghQgdghgegnQgKgNgIgNQgRgZgLgaQgTgrgZggQgcgjgOgoQgPgqgBgxQgBg2AlgMQgfgWgrgNQgvgOgwgHQgygIgygCQg0gCgzgCQgxgBgzAFQgwAGg1gBQg0gBgsALQgyANgxAEQguAEgvAMQgwALgsAHQgwAJgfAaQATAhAeAgQAeAiAeAcQAdAcAeAiQAbAeAlAdQAaAVAiAYQAhAYAlAaQAlAaAuAPQAEACAEABA8vmBQgsgFgXgWQgbgcACgvQACgwgJgjQAAgBgBgCQgBgEgBgEQgOgpgPgsQAcAdAzAEQA7AGA4AMQAnAJARAhQACACACADQAQAmgFAuA8GmKQADAAAEAAA8GmKQAEgDAFgDQAKgHANgFQAXgGAYgBQAhgBAcAKQAuARAQAjQATAngLA2QgIAigTAfQgVAjg3ADQgxACgagbA8vmBQAHABAHAAA8GmKQgXACgSAHA8Nj1QgEgJgEgJQgTgnALg0QAFgYASgQA64o9QARgIAPgKAzupZQAJgrAXglQAVgkAigSQAigSAigWQAjgXAhgVQAmgZAfgUQAhgWAggLQgBAlgRAoQgOAgAFAyQAGAzgPAeQgJATgQAFQgBAAAAAAQgFABgFAAAy/nvQACAEACAEA2MqVQAAABgBABQgBAEgBADA2Dm4QgKACgIAEA23kYQgEgLgBgMQgIg4AVghQATgbAZgVA15nAQgFAEgFAEQAZgGAgAFQAqAHArAVQArAVAEA3QACAdgDAdQgFAvglATQgoAWg2gFQgtgEgdgeQgKgKgHgLAxYl0QgJAqgRAiQgPAegXAPQgBAAAAAAQgEgDgFgCAn8ieQAKgnAZgcQACgCACgDQAXgcAcggQAcggAjgYQAggXAngaQAkgXAmgVQAngVArgIQAsgJA2ACQgSAkgLAsQgMAvAHA0QAGAuAAA2QAAAVABAVQAAAdABAdQABAZgCAWQAMAEALAEQATAIAVAFQADABADAAQAEAAADgBQAVgFAUgHQAlgNAdgXIg2ANIhJAAAhEAdQAEgFADgGAg5gxQgCAcgGAXQgEAPABAMQABALAGAIAATgZQADAAADABAATgZQAAgCAAgBAAMgbQADABAEABQACAvAAAvQABA1AAAsQAAA0ADAzQACAtAAA1QAAAzAFA0QAFAxgHAwQgEAXABAXQABADAAACQAEAAADgBIALgCIAAAAQAAAAAAABQgHAHgJAIIgBAAQABADAAADApEAiQBYBCCXAQQCdARBWhHQARgOANgTAr+i9QARACAPADQAxALAwADQAIABAJAAQADAAADAAQABAAABAAQATAEAUADQAUADAXABQAKAAALAAQABAAAAAAQAAADgBACQgLAugUAkQgUAjgPAqQgEAMgBAQQgBAHAAAHAAdJ3QgeAegjAWQghAVgmAVQgjAUgiAVQglAXgoAPQgnAPgvAMQgrAMgrANQguAOgzABAAuJnQAEgDACgDAAuJoQgFAAgGABAAcJqQAAAHABAGAxti9QAsgLA2AHQAzAHAxgBQAvAAA1gDQAlgCAgADQAAAGABAGQAGCSgGCLA7UAbQgsACgpAOQguAQglAgQggAdgOAqQgRAzA2AaQAcAOAWAPQAUAOAkADQAzAFAyAEQAxADAzACQAzABA0gBQA0AAAzADQAyADAyAHQAyAHAwgMQAwgMAvgMQAsgLAvgXQApgVAZgjQASgbgCgqQgDg2ghgRQgogWgzgJQgngHgigEQAFgJADgKQANguACg2QACgtgMgkAyYj7QAXANAOAhQADAIADAIA1WhHQgBASgBAUQgEAtgWArQglAHgxgHQgtgHglgLQgFAFgEAHA1WhHQgaAHgVAHQgpANglAbQghAWghAbQgDACgCADQgDgBgDgBA1WhHQABgDAAgDA0whQQgUAEgSAFA4PB0QArAGAwgFQAxgFA0gEQAUgBATgDAx6ALQgNAagaAPQgkAVguARQgaAJgbAFIAAAAQAEArgEAnQAAABAAABQgEAEgGACQgNAEgOADQgNADgPAAQgNABgOgBQgPAAgPABQgOAAgPAAQgOgBgOgBQgNgBgOgDQgNgDgNgEQABgkAAgoQgEAAgCAAQgygHgvgOQgvgOgagbQgMgMgJgPAjcR6QAAAAAAABQAEABADACA4xiTQAjAiAsgeQAHgFADgHA7ji/QgCACgBACQgEgEgDgEQgEgFgDgEA74iAQAEgjAOgYA74iAQgBAKAAAKQgBAyAPAoQAJAYAOAVQAEAAAGgBEgiAAAAQADgBADgBQAYgLAXgJQAsgRApgNQAqgNAqgSQAmgQAygIQAtgIAlgNA4PB0QAAAAAAAAEgiAAAAQgBBpgGBHA50InQACgCACgBQgCgDgCgDAawAcICzAuQgoAPgWAjINFhEIAAA0Io9C/Ih5gRIjECIIgeAAIk1BpQgmgkAXgnIBMg9IiXAAIBTgtIAtAAQAZgXArABIlEguIEAhDICIhMIhLgtIgugCIDeg4IgLgCEAgtAErIFqAzIq2DLQgvAIAEgzQgZAWglAGIgXAAIpqCQIg9AAICQA0IjMAAItQh3AQkCnQgSgJgFAAAQkCnIAAACIquCIIAABpIK2hEIgaAtIgqBMIkQAAIhTBpIE1ByIgOAAAXSBUImQBkQgRgKgMgHQgBAAAAAAALYiMIj4BzIAABgICthZIGXBgIAABZAawAcIEbhEIuJAAIDEhMIAAgWIougCIA9gcIgug9IppCZQAEgEAFgEAQSGDIgbAAAVDGDIkxAAAjUR1IW9AA");
	this.shape.setTransform(-11.7,21.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0000CC").s().p("AAZI1QgwgFgzAEQgtAEgygIIhjgOQgzgGgygFQgygEgtgHQgugIgmgOQgpgQgxgIQgygIgtgZIg0geQgngWgqgTIhOgjQgtgTgbgfQgZgegqgcQgpgcgbghQgdgigcgaQgbgZgYgmQgXgmgbgbQgYgcgQgkIABAAQAZgRAVgTQAWgVAWgSQAhgbAogSQAggPAggaQAfgZAqgNQAsgOAjgVQAjgVApgSIAhgPIAGgDIAvgTQAsgSApgMQAqgOAqgSQAmgQAygIQAtgHAlgNIgBAUQgBAyAPAnQAJAbAOAUQgsADgpAOQguAQgkAgQghAcgOAqQgRAzA2AaQAcAOAWAPQAUAOAkAEIBlAIQAxADAzACQAzABA0AAQA0gBAzADQAyADAwAHQAyAIAwgMIBfgYQAsgLAvgYQApgVAZgjQASgbgCgpQgDg2ghgSQgogWgzgJQgngHgigDQAFgKADgLQANgvACg1QACgugMgkQAsgLA2AIQAzAGAxAAQAvgBA1gDQAlgCAgAEQARABAPAEQAxAKAwADIARABIAGAAIACABIAnAGQAUADAXABIAVABIAAAEQgLAugUAlQgTAigQAtQgEAMgBAPQBYBDCXAQQCdAQBWhGQARgOANgUQABALAGAJQgGgJgBgLIAHgKIgHAKQgBgMAEgPQAGgZACgbIAXAIQATAHAXAFIAGACIAHABIACBgIABBiQAAAzADAzQACAtAAA1QAAAyAFAzQAFAygHAvQgEAYABAXIABAFIABANQggAdgjAXQghAUgmAVQgjAUgiAVQglAXgoAQQgnAOgvANQgrALgrANQguAOgzACQgRgagLgaQgTgqgZggQgcgjgOgoQgPgrgBgxQgBg1AlgMQgfgWgrgNQgvgOgwgIQgygIgygBIhngEQgxgCgzAGQgwAFg1gBQg0AAgsALQgwAMgxAFQguAEgvALQgwALgsAIQgwAIgfAbQATAgAeAhQAeAhAeAdQAdAbAeAiQAbAeAlAdQAaAVAjAZIBDAxQAlAaAuAQIAAAEQgVABgUAAQgXAAgWgCgAlQC0IAEgCIgEgGIAEAGIgEACgAtijBQAFhHABhqQgBBqgFBHgAIlkEQADhFAAhFQAAhKgDhLIgBgMIABAMQADBLAABKQAABFgDBFgALdlAIABgPIgBAPg");
	this.shape_1.setTransform(-143.3,58.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00CCFF").s().p("AGMMvIhcgQQgwgIgwgMIhXgWQgsgLgqgMQgogNgugMQgtgMgqgNQglgMgjgOIgFgCQgngNgggTQghgTgegMIgFgBIgJgEQgtgPglgaIhGgxQgigZgagVQglgdgbgeQgegigdgcQgegcgeghQgeghgTghQAfgaAwgIQAsgIAwgLQAvgMAugEQAxgEAygNQAsgLA0ABQA1ABAwgFQAzgGAxACIBnADQAwACAyAIQAwAIAvAOQArAMAeAWQgkAMABA2QABAxAPAqQAOAoAcAkQAZAgATAqQALAaARAZIASAaQAeAnAdAhQAeAhAeAeQAiAiApAcQAlAZAfAQIAVALQgIAIgVABQgvgBgyAHQgVADgVAAQgbAAgbgFgAqVDDIgYAJQgIAGgEALQgEAOAHAOQAXAiAjgWQAHgIAEgKIACgLQABgKgGgHIgIgLIgJgFIgPgEIgBAAgABDCmQgIAHgEAKQgEAOAHAOQAXAiAjgWQAHgIAEgKIACgKQABgKgGgIIgIgLIgKgFIgOgEIgBABIgYAIgAnDCmQgJAHgDAKQgEAOAGAOQAYAiAjgWQAHgIADgKIADgKQABgKgGgIIgIgLIgKgFIgPgEIAAABIgYAIgAiyCHIgYAJQgJAGgDAKQgEAPAGAOQAXAhAkgWQAHgHADgKIADgLQABgKgGgHIgIgLIgKgFIgPgFIAAABgAHyjiQiXgQhZhCQACgQAEgLQAPgtAUgjQAUgkALguIABgFQAKgnAZgcIAEgEIAzg8QAcghAigYIBIgwQAkgYAmgVQAngVArgIQAsgJA1ACQgRAkgLAsQgMAvAHA0QAGAuAAA2IABAqIABA7QABAYgCAWQgCAcgGAZQgEAPABAMQgNATgRAPQhGA4h0AAQgbAAgegDgAIvlSIgYAJQgJAGgDAKQgEAPAGAOQAXAhAkgWQAHgHADgKIADgLQABgKgGgHIgIgLIgKgFIgPgFIAAABgAF6lwIgYAIQgJAHgDAKQgEAPAGAOQAbAjAngYQAHgIADgJIAEgLQAAgKgGgIIgIgLIgKgEIgWgFIAAABgAK+l3IgYAIQgJAGgDAKQgEAPAHAOQAXAiAjgXQAHgHADgKIADgLQABgKgGgHIgIgLIgKgFIgOgFIgBACg");
	this.shape_2.setTransform(-95.8,55.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF9933").s().p("ApTDHIk0hxIBThnIEPAAIAqhMIExAAICXAAIhLA9QgYAlAnAkIEzhoIAeAAIDEiHIB4ARIFqAzIq1DJQgwAIAEgzQgZAVglAHIgXAAIpoCPg");
	this.shape_3.setTransform(143.4,69.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFCC33").s().p("AivCSIgBAAIAAhZImXhgIitBYIAAhgID4hzIIsACIAAAXIjCBLIOHAAIkbBFIgLgDIALADIjeA4ImOBkIgdgRg");
	this.shape_4.setTransform(112.1,23.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFF00").s().p("AoHCsIBMg9IiXAAIBTgtIAtAAQAZgXArAAIlEgrIEAhEICIhLIhLgtIgugCIDeg4ICzAuQgoAOgWAjINDhEIAAA1Io9C9Ih5gRIjCCHIgeAAIk1BqQgmgkAXgng");
	this.shape_5.setTransform(182.6,49.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF9900").s().p("AppA5IKsiGIABgBIAdAQIGQhkIAuACIBLAuIiIBLIkABCIFEAtQgrgBgZAYIgtAAIhTAtIkxAAIAagtIq0BEg");
	this.shape_6.setTransform(87.6,46.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF99FF").s().p("AgKHuIgcgBIgcgFIgagGIABhMIADAAQAWADAWAAIAAAAIABAAQATAAATgCIACAAIAAAAIADgBQAwgFA0gDQAUgCATgDQgTADgUACQg0ADgwAFIgDABIAAAAIgCAAQgTACgTAAIgBAAIAAAAQgWAAgWgDIgDAAIAAgBIgGAAQgxgHgvgOQgvgOgagaQgMgNgKgPIAKAAIgKAAQgNgVgJgaQgPgnABgyIABgUQAEgkAOgXQAaAaAxgCQA3gDAVgjQATgeAHgjQALg0gSgmQgQgkgugQQgcgLghACQgYABgXAGQgNAEgKAHIgJAHQgXABgSAHQgsgFgXgWQgbgbACgwQACgvgJgkIgBgCIgCgIIgdhVQAcAcAzAFQA7AFA4ANQAnAIARAhQARgIAPgKQASgMARgQQAdgaAsgJQARgDAXAAQgbgig2gKQgUgEgQgHQArgSAwAOQAwAOAaAZQALgmAlgbQAhgXAngRQgHAkgUAkQgMAWgLAcQAtgHApARQAoAQAbAcIAFAFQAWAaALAmQAGAXAIATQADgzAUgkQAYgoAlgVQAkgVAvgNQAvgOAggUIAUgNQgMAqgGAwIAAABIgIABIgBAAIgBAAIABAAIABAAIAIgBQgGAnAHAtQAGAogFA1QgEAuglAfQgvAng1gcIgGgDIgBgBIgJgGIAAAAIAAAAIAJAGIABABQgJApgRAjQgPAcgXAOIgBAAIgJgEIAJAEIABAAQAXANAOAhIAGAQQAMAkgCAuQgCA1gNAvQgEALgEAKQgOAagZAOQgkAVgvARQgZAJgbAFIAAAAQAEArgEAnIAAACQgEAEgGACIgbAHQgNADgPABIgbAAIgeAAIgOAAIgNAAgAAtDmQgoANgkAcQggAXghAbIgFAFQAkALAuAHQAvAIAlgIQAWgqADgvIADgnIAlgIIglAIIABgGIgBAGQgaAHgWAHgAhuFSQAEgGAFgGIgGgCIAGACQgFAGgEAGgAhUCeQASAAAUgNQAHgFAEgIQgEAIgHAFQgUANgSAAIAAAAIgBAAQgUAAgSgRIgBgBIABABQASARAUAAIABAAIAAAAgAAwiWQgZAUgTAcQgTAgAHA4QACAMADAJIABAIIABAGQAEAJAGAGQAHAMAKAKQAdAdAtAEQA2AFAogVQAlgTAFgvQADgcgCgdQgEg3grgVQgrgUgqgHQgggFgZAGIAKgIIgKAIIAAAAgAAeiRQAIgDAKgCQgKACgIADgAj0jDIABgVQAAghgNgdIgDgGIADAGQANAdAAAhIgBAVgAD4jGIgEgIIAEAIgAAmlxIgCAHIACgHIABgCIgBACgAHslYIAAAAg");
	this.shape_7.setTransform(-157.8,-7.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFCCFF").s().p("ADqCeQgLgmgWgaQAJgrAXglQAWghAigTQAhgSAigWIBEgsIBFgtQAhgVAhgLQgCAlgRAnQgOAgAGAzQAFAxgOAdQgKAUgQAEIgBgBQAHgwALgnIgTAMQghATgvANQguANglAVQglAVgXAoQgVAlgDAyQgHgSgHgYgAk2BRQg5gMg7gGQgygFgcgcIAcBVIgEAEQgagWgQggQgUgpgHgtQgJgvAEgwQACgYgGgSQASAkAhAXIBEAzQAeAXAsAMQAtAMAjAXQAfAWASAgQAJAPAEANQgPAKgQAIQgSghgmgIg");
	this.shape_8.setTransform(-158.2,-48.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AjyBzIADgEIACgFQAwAQAYhEIgKgWQgEgKgHgHQgFgDgFgBQgOgEgPgCIgMADQgYAGgOAUQgEALgBAMIgIgSQgTgnALgyQAFgYASgQIAGAAIgGAAIAIgGQAKgHAOgFQAWgGAZgBQAggBAdAKQAtARARAjQASAngLA0QgHAigTAfQgWAjg2ADIgHAAQgtAAgYgZgACjBqQgtgEgcgeIADgGQAYANAigKQAPgJAEgRIACgLIgCgGQgVgug0AFIgMACIgFACIgGADIgGAGIgFAEIgCAFIgCAMIAAADQgDgLgCgLQgHg3AVghQATgbAYgVQAagGAfAFQArAHArAVQArAVAEA3QABAdgCAbQgFAvglATQghASgqAAIgUgBg");
	this.shape_9.setTransform(-164.2,-8.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF0000").s().p("Ax+JDIAIADIgIABgAOzF9ItPh3IAGgGIgGAGIgBAAIgKACIgIABIAAgFQgCgXAEgXQAHgwgEgxQgFg0AAg0QgBgygCguQgDgyAAg0IAAhiIgDhgIAGACIgGgCIAAgCQAWgFATgHQAmgOAcgWIJqiZIAtA9Ig9AcIj4BzIAABiICthbIGXBiIAABZIgBgBIgHgDIgBgBIgFgCIAAAAIgCgBIgBAAIgBAAIAAgBIgBAAIgCAAIgBAAIAAgBIAAAAIAAAAIAAABIABAAIACAAIABAAIAAABIABAAIABAAIACABIAAAAIAFACIABABIAHADIABABIAAACIquCHIAABoIK2hCIgaArIgbAAIAbAAIgqBMIkPAAIhTBpIE0BxICQA1gAPvFIIgOAAgARHAigAnIn/IABAAIgBAFg");
	this.shape_10.setTransform(-17,56.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("An1G/QgHgOAEgPQADgKAJgHIAYgIIABgBIAOAFIAKAEIAIALQAGAIgBAKIgDALQgDAKgHAHQgOAJgMAAQgTAAgNgUgAD7GZQgHgOAEgPQADgKAJgGIAYgJIABgBIAOAFIAKAFIAIALQAGAHgBAKIgDALQgDAKgHAHQgOAJgMAAQgTAAgNgUgAkMGZQgGgOAEgPQADgKAJgGIAYgJIAAgBIAPAFIAKAFIAIALQAGAHgBAKIgDALQgDAKgHAHQgOAJgMAAQgTAAgOgUgAgTGCQgHgOAFgOQADgKAJgHIAWgIIAAgBIAPAEIAKAFIAIALQAGAIgBAJIgDALQgEAKgGAIQgPAJgMAAQgQAAgOgVgAkXClQgxgHgygDQgzgDg0ABQg0ABg0gCQgygBgygEIhkgIQgkgDgUgPQgWgPgcgOQg2gaARgzQANgnAhgdQAlggAugQQAogOAsgDQAKAQAMAMQAaAbAvAOQAvAOAxAGIAGABIgBBKIAaAGIAcAFIAcABIAdAAIAeAAIAbAAQAPAAANgDIAbgIQAGgBAEgFIAAgCQAEgngEgpIAAAAQAbgFAZgJQAvgRAkgUQAZgPAOgaQAiADAnAIQAxAJAoAVQAhASADA2QACAogTAaQgYAjgpAVQgtAYgsALIhfAYQgeAHgeAAQgTAAgUgDgALOhXQgHgOAFgOQADgKAJgHIAYgIIAAgBIAPAEIAKAFIAIALQAGAIgBAJIgDALQgEAKgGAIQgPAJgMAAQgSAAgOgVgAIZh1QgHgOAFgOQADgLAJgGIAYgIIAAgBIAWAEIAKAFIAIALQAGAHgBAKIgDALQgDAKgHAHQgQAKgOAAQgUAAgQgVgANdh8QgGgOAEgPQADgKAJgHIAYgIIAAgBIAPAFIAKAEIAIALQAGAIgBAKIgDALQgDAJgHAIQgOAJgMAAQgTAAgOgUgArYlWQgJgDgJgGQgJgFgKgIQgFgLgBgLIAAgFQABgMAFgMQANgUAYgGIAMgCQAPACAPADQAEABAFADQAHAIAFAJIAJAXQgTA3gkAAQgIAAgJgDgAmMl+QgLgGgJgJQgGgHgGgJIgBgFIgBgIIABgEIABgLIACgFIAGgGIAFgGIAGgDIAGgCIALgDQA1gEAUAwIACAFIgCAMQgDARgPAJQgPAEgNAAQgRAAgOgHg");
	this.shape_11.setTransform(-115.1,36.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#CCCCCC").s().p("AAAABIABgBIgBABg");
	this.shape_12.setTransform(-206.1,-36.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#000000").ss(0.3,1,1).p("Ar+i9QgFiIAMiCQAOiRgNiOQgMiIhxhPQh9hYhxgvQh+g0iKgPQiPgPiGAjQiGAihsA8QiCBIhBBqQhHB1gHCXQgGCIAECXQAECTgBCTQAAAJAAAJQADgBADgBQAYgLAXgJQAsgRApgNQAqgNAqgSQAmgQAygIQAtgIAlgNQAEgjAOgYA6YpPQASgNARgPQAdgaAsgJQARgDAXAAQgagig3gLQgUgEgQgHQArgSAwAPQAwANAaAaQALgmAngbQAhgXAngSQgHAlgTAkQgNAWgLAbQAtgGApAQQAoARAbAbQACADADADQAWAaALAmQAGAXAIATQADgzAVgkQAXgpAlgVQAkgUAvgOQAvgNAhgVQAJgFAKgHQgMApgGAwQAAABAAABQgGAmAIAuQAFAogFA0QgEAuglAfQgvAng1gcQgDgBgDgCQAAAAgBAAQgKgGABAAA+To9QgDgCgDgCIAAAAQgagVgQghQgUgpgIguQgIgwAEgwQACgXgGgSQASAjAhAXQAfAXAlAcQAeAYArALQAuAMAjAaQAfAWASAgQAJAPAEANA8vmBQgsgFgXgWQgbgcACgvQACgwgJgjQAAgBgBgCA64o9QgRghgngJQg4gMg7gGQgzgEgcgdQAPAsAOApQABAEABAEA64o9QACACACADQAQAmgFAuA8GmKQADAAAEAAA8GmKQAEgDAFgDQAKgHANgFQAXgGAYgBQAhgBAcAKQAuARAQAjQATAngLA2QgIAigTAfQgVAjg3ADQgxACgagbA8vmBQAHABAHAAA8Nj1QgEgJgEgJQgTgnALg0QAFgYASgQQgXACgSAHA64o9QARgIAPgKAzupZQAJgrAXglQAVgkAigSQAigSAigWQAjgXAhgVQAmgZAfgUQAhgWAggLQgBAlgRAoQgOAgAFAyQAGAzgPAeQgJATgQAFQgBAAAAAAQgFABgFAAAy/nvQACAEACAEA2MqVQAAABgBABQgBAEgBADA2Dm4QgKACgIAEA23kYQgEgLgBgMQgIg4AVghQATgbAZgVA15nAQgFAEgFAEQAZgGAgAFQAqAHArAVQArAVAEA3QACAdgDAdQgFAvglATQgoAWg2gFQgtgEgdgeQgKgKgHgLAxYl0QgJAqgRAiQgPAegXAPQgBAAAAAAQgEgDgFgCAn8ieQAKgnAZgcQACgCACgDQAXgcAcggQAcggAjgYQAggXAngaQAkgXAmgVQAngVArgIQAsgJA2ACQgSAkgLAsQgMAvAHA0QAGAuAAA2QAAAVABAVQAAAdABAdQABAZgCAWQAMAEALAEQATAIAVAFQADABADAAQAEAAADgBQAAABAAACQADAAAFABQAAgCAAgCQABgCAAgDAhEAdQAEgFADgGAg5gxQgCAcgGAXQgEAPABAMAAbgYQgBAVAEATQAHAwgFAyQgFAzAAA0QAAAngBAkQgBALAAAMQgDAzAAAzQAAAsgBA2QAAAvgCAxAgBg/IBCAAAAMgbQADABAEABApEAiQBYBCCXAQQCdARBWhHQARgOANgTQABALAGAIAr+i9QARACAPADQAxALAwADQAIABAJAAQADAAADAAQABAAABAAQATAEAUADQAUADAXABQAKAAALAAQABAAAAAAQAAADgBACQgLAugUAkQgUAjgPAqQgEAMgBAQQgBAHAAAHA5wIkQAfgaAwgJQAsgHAwgLQAvgMAugEQAxgEAygNQAsgLA0ABQA1ABAwgGQAzgFAxABQAzACA0ACQAyACAyAIQAwAHAvAOQArANAfAWQglAMABA2QABAxAPAqQAOAoAcAjQAZAgATArQALAaARAZQAzgBAugOQArgNArgMQAvgMAngPQAogPAlgXQAigVAjgUQAmgVAhgVQAjgWAegeQgBgGAAgHQADAAADgBQAEABAEABQgGAGgGAGIgBAAQABADAAADAATJlQAEABAFABQADABADABAAqJrQAJADAJADQACABADABQAiANAbAVQAEAEAFAEABBKIIAHAAIA2ANAxti9QAsgLA2AHQAzAHAxgBQAvAAA1gDQAlgCAgADQAAAGABAGQAGCSgGCLA7UAbQgsACgpAOQguAQglAgQggAdgOAqQgRAzA2AaQAcAOAWAPQAUAOAkADQAzAFAyAEQAxADAzACQAzABA0gBQA0AAAzADQAyADAyAHQAyAHAwgMQAwgMAvgMQAsgLAvgXQApgVAZgjQASgbgCgqQgDg2ghgRQgogWgzgJQgngHgigEQAFgJADgKQANguACg2QACgtgMgkAyYj7QAXANAOAhQADAIADAIA1WhHQgBASgBAUQgEAtgWArQglAHgxgHQgtgHglgLQgFAFgEAHA1WhHQgaAHgVAHQgpANglAbQghAWghAbQgDACgCADQgDgBgDgBA1WhHQABgDAAgDA0whQQgUAEgSAFA4PB0QArAGAwgFQAxgFA0gEQAUgBATgDAx6ALQgNAagaAPQgkAVguARQgaAJgbAFIAAAAQAEArgEAnQAAABAAABQgEAEgGACQgNAEgOADQgNADgPAAQgNABgOgBQgPAAgPABQgOAAgPAAQgOgBgOgBQgNgBgOgDQgNgDgNgEQABgkAAgoQgEAAgCAAQgygHgvgOQgvgOgagbQgMgMgJgPAjcR6QgJAIgVAAQgvAAgyAHQgvAHgxgJQgygJgqgHQgwgIgwgMQgvgMgngKQgtgLgqgNQgqgMgugMQgtgMgqgOQglgMgjgNQgCgBgDgBQgngNgggTQghgTgegMQgDgBgCgBQgEgBgEgCQgugPglgaQglgaghgYQgigYgagVQglgdgbgeQgegigdgcQgegcgegiQgegggTghQgCABgCACAyrOnQgEABgEAAQgsAEgqgEQgzgGgyAFQgtAEgygIQgxgIgzgGQgygGgygFQgygEgtgIQgugIgmgOQgpgPgxgIQgygIgtgaQgggRgUgMQgngXgqgTQgjgQgrgSQgtgTgbggQgZgdgqgdQgpgcgbggQgdgjgcgZQgbgagYglQgXgmgbgeQgYgbgQglIAAAAQAagRAVgTQAWgUAWgTQAhgaAngSQAhgPAggbQAfgYAqgOQAsgNAjgWQAjgUApgTQAPgHASgGQgBBpgGBHAjcR6QAAAAAAABQAEABADACAoKNnQAIANAKANQAeAnAdAhQAeAhAeAeQAiAiApAcQAlAZAfAQQALAGALAFA4xiTQAjAiAsgeQAHgFADgHA7ji/QgCACgBACQgEgEgDgEQgEgFgDgEA74iAQgBAKAAAKQgBAyAPAoQAJAYAOAVQAEAAAGgBA4PB0QAAAAAAAAA50IeQACADACADEAgtAEcII9C/IAAA1ItFhEQAWAjAoAOIizAuIEbBHIuJAAIDEBLIAAAXIouABIA9AdIguA8IppiZAVDDEICXAAIhMg9QgXgnAmgkIE1BqIAeAAIDECHIB5gRAO6hgIA9AAIJqCNIAXAAQAlAHAZAVQgEgzAvAIIK2DLIlqAzAXSHzIAugCIBLgtIiIhLIkAhEIFEgtQgrABgZgYIgtAAIhTgtIkxAAIAaAtIq2hEIAABqIKuCHIAAACQgSAKgFAAABBggIM9h1IDMAAIiQA1Ik1BvIBTBpIEQAAIAqBMIgbAAAO6hgIgOAAAQkGgIAABZImXBiIithbIAABiID4BzAQkGgQAAAAABAAQAMgGARgLIGQBkAawIrIjeg4AawIrIgLADAjUR1IW9AA");
	this.shape_13.setTransform(-11.7,21.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#0000CC").s().p("AAbI1QgwgFgzAEQgtAEgxgIIhkgOQgzgGgygFQgxgEgugHQgugIgmgOQgpgQgwgIQgzgIgtgZIg0geQgngWgqgTIhNgjQgugTgagfQgagegqgcQgpgcgbghQgcgigdgaQgbgZgXgmQgXgmgbgbQgZgcgQgkIABAAQAagRAUgTQAWgVAWgSQAhgbAogSQAhgPAggaQAegZAqgNQAsgOAkgVQAigVApgSIAhgPQgBBqgFBHQAFhHABhqIAGgDIAvgTQAsgSApgMQAqgOAqgSQAmgQAygIQAtgHAmgNIgBAUQgCAyAPAnQAKAbANAUQgsADgpAOQguAQgkAgQghAcgOAqQgRAzA2AaQAcAOAWAPQAVAOAjAEIBlAIQAyADAyACQAzABA0AAQA1gBAyADQAzADAvAHQAyAIAwgMIBggYQAsgLAvgYQApgVAYgjQATgbgDgpQgDg2gggSQgogWgzgJQgogHgigDQAFgKADgLQANgvACg1QACgugLgkQArgLA2AIQAzAGAxAAQAvgBA2gDQAkgCAgAEQARABAQAEQAwAKAxADIAQABIAHAAIABABIAnAGQAVADAWABIAVABIAAAEQgLAugUAlQgTAigQAtQgEAMgBAPQBZBDCXAQQCcAQBWhGQASgOANgUIAGgKIgGAKQgBgMADgPQAGgZADgbIAWAIQAUAHAWAFIAHACIAGABIADBgIAABiQAAAzADAzIABAXIgBAXQgDAzAAAyIAABhIgDBgIAAADIAJACIAAADIACANQghAdgiAXQghAUgmAVQgkAUgiAVQglAXgoAQQgmAOgwANQgrALgrANQgtAOg0ACQgRgagLgaQgTgqgZggQgcgjgOgoQgPgrgBgxQgBg1AlgMQgfgWgrgNQgvgOgwgIQgygIgygBIhngEQgwgCgzAGQgxAFg0gBQg1AAgsALQgvAMgxAFQgvAEgvALQgvALgsAIQgwAIggAbQATAgAeAhQAfAhAdAdQAeAbAeAiQAaAeAlAdQAaAVAjAZIBEAxQAlAaAtAQIAAAEQgUABgVAAQgWAAgXgCgAlNC0IADgCIgDgGIADAGIgDACgAInkEQADhFAAhFQAAhKgDhLIgBgMIABAMQADBLAABKQAABFgDBFgATnlAQgFgJgBgLQABALAFAJgALflAIABgPIgBAPgAlKCyIAAAAg");
	this.shape_14.setTransform(-143.5,58.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FF0000").s().p("Ax+IgIAIADIgIAAgACzERQgbgVgigOIgFgCIgSgFIgIgCIgGgCIgJgCIAAgDIADhgIAAhiQAAgxADgzIABgXIAChLQAAg0AFgzQAEgygHgvQgDgWAAgVIABgEIAAgFIAIACIAKABIABAAIASgCIM9h1IDMAAIiQA1IgOAAIAOAAIk0BxIBTBqIEPAAIAqBLIAaAuIq2hFIAABqIKuCGIAAACIgFADIgBAAQgMAGgEAAIAAAAIAAAAQAEAAAMgGIABAAIAFgDIAABYImXBiIithaIAABiID4BzIA9AcIgtA8gARHi/IgbAAgAPvnlgAnIojIABAAIgBAFg");
	this.shape_15.setTransform(-17,60.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FF9900").s().p("ABhA/IgdAQIgBgBIqsiGIAAhqIK0BEIgagtIExAAIBTAtIAtAAQAZAYArgBIlEAtIEABCICIBLIhLAuIguACg");
	this.shape_16.setTransform(87.6,55.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFCC33").s().p("Ar0AwIAAhgICtBYIGXhgIAAhZIABAAIAdgRIGOBkIDeA4IEbBFIuHAAIDCBLIAAAXIosABgAHPgDIALgDg");
	this.shape_17.setTransform(112.1,77.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FF9933").s().p("ADiBAIgeAAIkzhoQgnAkAYAlIBLA9IiXAAIkxAAIgqhMIkPAAIhThnIE0hxIA9AAIJoCPIAXAAQAlAHAZAVQgEgzAwAIIK1DJIlqAzIh4ARg");
	this.shape_18.setTransform(143.4,31.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFF00").s().p("AnDC/IAugCIBLgtIiIhLIkAhEIFEgrQgrAAgZgXIgtAAIhTgtICXAAIhMg9QgXgnAmgkIE1BqIAeAAIDCCHIB5gRII9C9IAAA1ItDhEQAWAjAoAOIizAug");
	this.shape_19.setTransform(182.6,52.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_8},{t:this.shape_7},{t:this.shape_12},{t:this.shape_9},{t:this.shape_11},{t:this.shape_2},{t:this.shape_14},{t:this.shape_13}]},1).wait(4));

	// Layer 2
	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#000000").ss(0.3,1,1).p("AFjiiQAEgCAGgBAIbBnQBiA9CeACQCjADBlgzAFWiCQACgGABgHAwdA6QgBgHgCgIQgBgHgBgI");
	this.shape_20.setTransform(-123.9,15.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.lf(["#0066FD","#FFFFFF","#FFFFFF","#996600","#FFFFFF","#FFCC00"],[0,0.533,0.969,0.988,1,1],-89.3,-61.8,87.4,60).s().p("Ag7L5QiIgpiHgjQiSgmhnhKQhmhJgbh3IAAgDIAAgQQABiTgEiTQgEiVAGiIQAHiXBHh0QBBhqCChIQBsg8CGgjQCGgjCNAQQCKAPB+A0QBxAuB9BYQBxBQAMCIQAMCOgNCQQgLBvADB2QgaAJANAXQgaBjgxB1QgzB5hqBmQhdBZiFAqQhKAYhKAAQhHAAhEgVg");
	this.shape_21.setTransform(-158.3,-16.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20}]}).wait(5));

	// Layer 4
	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#999999").s().p("AA6FJQg0gJglgnQgfgfgMgnQgIgZABgcQgBhGAwgyQgugMglgiQg3g4AAhOQAAhOA3g3QA3g3BMAAQAXAAAVAEQAzAMAmAnQA4A3AABOIgBATQgGBCgxAxIgCADQAlAKAeAeQAzAzAABIQAAAcgIAZQgMAngfAfQgyAyhIAAQgRAAgPgCgAGEC0QgxAAgigiQgigiAAgwQAAgeAMgYQAJgNANgOQASgSAWgJQAUgHAXAAQAWAAAUAHQAWAJASASQAOAOAIANQANAYAAAeQAAAwgjAiQgiAigwAAIAAAAgAnGB8QgygyABhGQgBhFAygxQAygyBGAAQBGAAAyAyQAyAxAABFQAABGgyAyQgyAxhGAAQhGAAgygxg");
	this.shape_22.setTransform(267.1,32.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f().s("#000000").ss(0.3,1,1).p("AkgkNIOgAAAnKmFIf1AAAqcQ4IJ2AAA4qw3MAtRAAAAvSsfISQAA");
	this.shape_23.setTransform(31,13);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f().s("#000000").ss(0.3,1,1).p("Ap8DEIBCAAAkhh3ITpAAAvljDIc8AAAlqDEIVQAAAqMA8IYnAA");
	this.shape_24.setTransform(351.1,40.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f().s("#000000").ss(0.3,1,1).p("A4/kNIOiAAAUnHZIhCAAAN8BRIc+AAAZACcITrAAAX3HZIVTAAATWFRIYoAAEgjxgMfISSAAEgtJgQ3MAtSAAAA+7Q4IJ2AAA7pmFIf2AA");
	this.shape_25.setTransform(162,13);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22,p:{x:267.1,y:32.1}}]}).to({state:[{t:this.shape_22,p:{x:265.5,y:59.3}},{t:this.shape_25}]},1).wait(4));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-279.3,-96,731.4,235);


(lib.bracketdisplay = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 4 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("ApvEXIAAouITgAAIAAIug");
	var mask_graphics_1 = new cjs.Graphics().p("ApvEXIAAouITgAAIAAIug");
	var mask_graphics_2 = new cjs.Graphics().p("ApvEXIAAouITgAAIAAIug");
	var mask_graphics_3 = new cjs.Graphics().p("ApvEXIAAouITgAAIAAIug");
	var mask_graphics_4 = new cjs.Graphics().p("AguEXIAAouITgAAIAAIug");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:52.1,y:6.2}).wait(1).to({graphics:mask_graphics_1,x:83.6,y:6.2}).wait(1).to({graphics:mask_graphics_2,x:115.1,y:6.2}).wait(1).to({graphics:mask_graphics_3,x:146.6,y:6.2}).wait(1).to({graphics:mask_graphics_4,x:120.3,y:6.2}).wait(1));

	// right
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(3,1,1).p("AJOByQg+i6lGA6QlDA4i/gjQi+gghXhY");
	this.shape.setTransform(177,11.4);

	this.shape.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(5));

	// Layer 2 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("AguEXIAAouITgAAIAAIug");
	var mask_1_graphics_1 = new cjs.Graphics().p("ApwEXIAAouIThAAIAAIug");
	var mask_1_graphics_2 = new cjs.Graphics().p("ApwEXIAAouIThAAIAAIug");
	var mask_1_graphics_3 = new cjs.Graphics().p("ApwEXIAAouITgAAIAAIug");
	var mask_1_graphics_4 = new cjs.Graphics().p("ApwEXIAAouITgAAIAAIug");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:120.3,y:6.2}).wait(1).to({graphics:mask_1_graphics_1,x:147.6,y:6.2}).wait(1).to({graphics:mask_1_graphics_2,x:117.1,y:6.2}).wait(1).to({graphics:mask_1_graphics_3,x:86.6,y:6.2}).wait(1).to({graphics:mask_1_graphics_4,x:56.1,y:6.2}).wait(1));

	// left
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(3,1,1).p("AJOhxQhhBKi1AuQi1AwlIg+QlKhAg+C5");
	this.shape_1.setTransform(59,11.4);

	this.shape_1.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(5));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(115.6,-1.5,4,25.8);


(lib.goNext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,11.3).s().p("AhLAqQghgSACgYQgCgXAhgRQAggTArAAQAsAAAgATQAfARAAAXQAAAYgfASQggASgsAAQgrAAgggSg");
	this.shape.setTransform(22.8,8.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.502)").s().p("AhThcICoBdIioBcg");
	this.shape_1.setTransform(25.1,20.4);

	this.blinker = new lib.general_buttoncolor();
	this.blinker.setTransform(23.4,20.1,1.5,1.5,0,0,0,11.9,11.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,14.8).s().p("AhiA3QgrgXACggQgCgfArgWQApgYA5AAQA5AAAqAYQAqAWAAAfQAAAggqAXQgqAXg5AAQg5AAgpgXg");
	this.shape_2.setTransform(23.4,8.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("rgba(0,0,0,0.502)").ss(1,1,1,3,true).p("AAACxQhIAAg0g0Qg0g1AAhIQAAhHA0g1QA0g0BIAAQBJAAA0A0QA0A1AABHQAABIg0A1Qg0A0hJAAg");
	this.shape_3.setTransform(23.3,20.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["rgba(103,103,103,0.839)","rgba(134,134,134,0)"],[0.678,0.918],-0.8,0,0,-0.8,0,24.9).s().p("AisCkQhFhEAAhgQAAhgBFhDQBEhFBhAAQBfAABBAwQBCAwAVCqQAVCskMAbQhhAAhEhFgAgHCQQBEAAAzgwIABAAIADgEQA0g0AAhHQAAhJg0g0IgFgFIgBgBQgyguhDAAIAAAAIgBAAIAAAAIgBAAQhEAAgyAuIgBABIgCACIgBABIAAAAIgCACQg0A0AABJQAABHA0A0IACACIABABQAzAxBHAAIAAAAIAAAAIAAAAIAAAAQhHAAgzgxIgBgBIgCgCQg0g0AAhHQAAhJA0g0IACgCIAAAAIABgBIACgCIABgBQAyguBEAAIABAAIAAAAIABAAIAAAAQBDAAAyAuIABABIAFAFQA0A0AABJQAABHg0A0IgDAEIgBAAQgzAwhEAAIAAAAIgBAAIABAAIAAAAg");
	this.shape_4.setTransform(24.2,23.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},2).wait(1));

	// Layer 2
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#33FFFF").s().p("AioCqQhGhHAAhjQAAhiBGhGQBGhHBiAAQBjAABGBHQBHBGgBBiQABBjhHBHQhGBGhjAAQhiAAhGhGg");
	this.shape_5.setTransform(24.4,21.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0099FF").s().p("AioCqQhGhHAAhjQAAhiBGhGQBGhHBiAAQBjAABGBHQBHBGgBBiQABBjhHBHQhGBGhjAAQhiAAhGhGg");
	this.shape_6.setTransform(24.4,21.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.5,46.7);


(lib.Scene1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		playSound("Flying");
	}
	this.frame_9 = function() {
		playSound("Flying");
	}
	this.frame_21 = function() {
		playSound("Flying");
	}
	this.frame_32 = function() {
		playSound("Flying");
	}
	this.frame_43 = function() {
		playSound("Flying");
	}
	this.frame_57 = function() {
		this.stop();
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(9).call(this.frame_9).wait(12).call(this.frame_21).wait(11).call(this.frame_32).wait(11).call(this.frame_43).wait(14).call(this.frame_57).wait(1));

	// Layer 1
	this.instance = new lib.Dynamo_motion();
	this.instance.setTransform(370.6,-114.6,0.143,0.143,0,0,0,86.4,21.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.32,scaleY:0.32,x:-307.5,y:-63.6},8).wait(1).to({skewY:180,x:-316.5,y:16.4},0).to({scaleX:0.57,scaleY:0.57,x:507.4,y:20.4},10).wait(2).to({regX:86.5,regY:21.5,scaleX:0.57,scaleY:0.57,rotation:-51.4,skewY:0,x:94.6,y:-370.3},0).to({regY:21.6,scaleX:0.57,scaleY:0.57,rotation:-81.7,guide:{path:[94.5,-370.2,57.2,-330.4,29.7,-282.9,1,-233.1,-16.1,-172.2,-34.2,-107.8,-42.6,-28.8,-44.9,-7.4,-46.4,15.2]}},5).to({regY:21.4,rotation:-120.4,x:39.1,y:403.1},5).wait(1).to({regX:86.6,regY:21.5,scaleX:0.57,scaleY:0.57,rotation:-244.5,x:-32.4,y:487},0).to({scaleX:0.56,scaleY:0.56,rotation:-289.6,guide:{path:[-32.3,486.9,-2,444,19.8,397.8,45.8,342.1,62.4,279.6,80.8,210,92.5,147.3,105.5,77.6,105.8,0.1,106.2,-77.7,96.5,-152,86.9,-225.1,70.4,-295.6,57.5,-350.3,31.6,-399.9]}},10).wait(1).to({regX:86.4,regY:21.4,scaleX:0.32,scaleY:0.32,rotation:-360,skewY:180,x:-320.2,y:-59.4},0).to({scaleX:0.57,scaleY:0.57,x:524.4,y:-58.6},13).wait(2));

	// Layer 9
	this.instance_1 = new lib.Tween7("synched",0);
	this.instance_1.setTransform(97.5,26.3,1,1,0,0,0,0.3,7.9);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(36).to({_off:false},0).to({scaleY:3.77,y:26.5},5).wait(17));

	// Layer 8
	this.instance_2 = new lib.Tween5("synched",0);
	this.instance_2.setTransform(-34,-32.7,1,1,0,0,0,0,-7.8);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(26).to({_off:false},0).to({scaleY:7},4).wait(28));

	// Layer 5
	this.instance_3 = new lib.Tween3("synched",0);
	this.instance_3.setTransform(-102,26.4,1,1,0,0,0,-11,0);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(13).to({_off:false},0).to({scaleX:13.26,x:-102.6},3).wait(42));

	// Layer 12
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgGA5QgEgDAAgEIABgJIAAgJIgCgpIgPgBQgLgCAAgJQAAgFADgDQAEgDAFAAIAOABIgBgJIAAgIQAAgFADgDQAEgDAFAAQAKAAAAAUIAAAHIAIAAIANABQAHACAAAIQAAAFgDADQgEADgFAAIgEAAIgEAAIgIAAIACAqIAAAEIAAAFQAAATgMAAQgDAAgDgDg");
	this.shape.setTransform(-56.9,-48.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgZAkQgNgLAAgSQAAgPAMgRQANgUAQAAQAIAAAMAEQAOAGAAAIQAAAEgDADQgDADgFAAQgDAAgFgDQgFgFgKAAQgFAAgHANQgHAMAAAHQAAAJAGAEQAGAGAIAAQAFgBAJgEIAKgEQAEAAADADQAEAEAAADQAAAHgPAHQgMAFgIAAQgQAAgNgKg");
	this.shape_1.setTransform(-65.5,-47.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgbAjQgOgKAAgTQAAgTALgPQAMgQATAAQAOAAAKAFQANAGAAANQAAAJgKAHQgGADgNAEIgaANQADAEAHACQAFACAFAAQALAAAIgEQAHgEAEAAQAJAAAAAIQAAAKgOAGQgMAFgNAAQgRAAgNgKgAgKgTQgGAFgDALIASgIQAKgFAGgFQgFgDgJAAQgGAAgFAFg");
	this.shape_2.setTransform(-74.5,-47.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgdA6IgBgFQAAgFAEgDQADgDAFAAQAFAAAEAGIAHAKQACAGADAAQAEAAABgMIgDguIgDgqQAAgFADgEQAEgEAFAAQADAAAFACQAEADAAAEIADAsIACAxQAAAMgIAKQgIALgMAAQgTAAgNgcgAADhAQgDgEAAgFQAAgFADgEQAEgDAFAAQAFAAAEADQAEAEAAAFQAAAFgEAEQgEADgFAAQgFAAgEgDg");
	this.shape_3.setTransform(-83.4,-46.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgXA/QgEADgEAAQgEAAgEgDQgDgDAAgFIAAgGIABgGIAAhcQAAgGACgFQAEgFAGgBQAJAAAAAKIgBAEIAAADIAAAfQAGgDAGgBIAJgCQATAAAMAOQAMALAAATQAAAUgNANQgOANgRAAQgMAAgKgDgAgIgBIgNAGIAAAjQAMAFAIAAQAIAAAHgHQAHgHAAgLQAAgKgGgHQgGgGgJAAQgDAAgFACg");
	this.shape_4.setTransform(-91.1,-49.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAQApQgLAEgJAAQgMAAgIgFQgJgGgCgLQgDgVAAgOQAAgLADgNQABgKAKAAQAFAAADADQADADAAAFIgBALIgBAMIABASIACAPIAEABIAEABQAHAAALgDIAAgPIAAgLQAAgRACgNQABgKAKAAQAFAAADADQAEADAAAFIgCAdIAAAPIAAARIAAAFIABAFQAAAFgEADQgDADgFAAQgHAAgDgGg");
	this.shape_5.setTransform(-100.6,-47.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgsA1QgKgHAAgLQAAgEADgEQAEgEAFABQAIAAADAHQAFALAQAAQANgBANgGQAOgGAAgIQAAgLgJgDQgGgCgQAAQgPgBgLgEQgPgGAAgMQAAgRARgNQARgOATAAQAIAAAMAEQAPAEAAAHQAAAEgDAEQgEADgFAAIgMgBIgLgCQgLAAgIAFQgKAFAAAGQAAADADACQADADAGAAIAUABQASACALAJQAMAHAAASQAAAVgZALQgSAJgWAAQgVAAgNgKg");
	this.shape_6.setTransform(-110.9,-48.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},47).wait(11));

	// Layer 11
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgXA/QgEADgEAAQgEAAgEgDQgDgDAAgFIAAgGIABgGIAAhcQAAgGACgFQAEgFAGgBQAJAAAAAKIgBAEIAAADIAAAfQAGgDAGgBIAJgCQATAAAMAOQAMALAAATQAAAUgNANQgOANgRAAQgMAAgKgDgAgIgBIgNAGIAAAjQAMAFAIAAQAIAAAHgHQAHgHAAgLQAAgKgGgHQgGgGgJAAQgDAAgFACg");
	this.shape_7.setTransform(51.5,-49.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AggAqQgCgCAAgFIAAg1IAAgHIAAgHQAAgGADgCQADgDAFAAQAJgBACAKQANgLASAAQAQAAAAAWIAAAFQgBANgLABQgKgBAAgKIgBgJQgQADgIARIAAAnQAAAFgDADQgEADgFAAQgEAAgEgEg");
	this.shape_8.setTransform(42.6,-47.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgbAjQgOgKAAgTQAAgTALgPQAMgQATAAQAOAAAKAFQANAGAAANQAAAJgKAHQgGADgNAEIgaANQADAEAHACQAFACAFAAQALAAAIgEQAHgEAEAAQAJAAAAAIQAAAKgOAGQgMAFgNAAQgRAAgNgKgAgKgTQgGAFgDALIASgIQAKgFAGgFQgFgDgJAAQgGAAgFAFg");
	this.shape_9.setTransform(33.5,-47.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgRA6QgKgXgMgsIgHgXQgFgPAAgGQAAgFAEgDQADgDAFAAQAIgBADAJIADAOIAIAbIANAoIARgwIAIgUQAEgLAGgHQAEgFAFAAQAFAAADAEQAEADAAAFQAAADgCADQgFAHgEAJIgGAQIgWA4IgJAUQgEAHgFgBQgIAAgEgIg");
	this.shape_10.setTransform(23.2,-49.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7}]},51).wait(7));

	// Layer 10
	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgGA5QgEgDAAgEIABgJIAAgJIgCgpIgPgBQgLgCAAgJQAAgFADgDQAEgDAFAAIAOABIgBgJIAAgIQAAgFADgDQAEgDAFAAQAKAAAAAUIAAAHIAIAAIANABQAHACAAAIQAAAFgDADQgEADgFAAIgEAAIgEAAIgIAAIACAqIAAAEIAAAFQAAATgMAAQgDAAgDgDg");
	this.shape_11.setTransform(198.9,-48.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AARAmIgDgSIgBgRIAAgFIAAgIIAAgCIABgEQAAgHgDAAQgIAAgFAJQgGAJgEAMIgBAIIgBAHIAAAHIAAAHQAAAFgDADQgEAEgFAAQgFAAgDgEQgEgDAAgEIAAgIIgBgHIACgWIABgVIgBgHIAAgIQAAgFAEgDQADgDAFAAQALAAAAANIAAABQANgMAMAAQAPAAAGANQAEAJAAARIAAAGIAAAEIACAQQABAKAAAHQAAAFgDADQgDADgFAAQgKAAgBgKg");
	this.shape_12.setTransform(190.5,-47.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgbAjQgOgKAAgTQAAgTALgPQAMgQATAAQAOAAAKAFQAMAGAAANQAAAJgKAHQgFADgOAEIgaANQAEAEAGACQAGACAGAAQAKAAAIgEQAHgEAEAAQAJAAAAAIQAAAKgOAGQgLAFgNAAQgTAAgMgKgAgKgTQgFAFgEALIASgIQAKgFAGgFQgFgDgJAAQgGAAgFAFg");
	this.shape_13.setTransform(181.1,-47.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgGAvQgDgDAAgEIgCgcIgCgaIgBgJQgKAGgJANIgCACIAAAYIAAAGIAAAGQAAAFgEACQgDACgFAAQgHAAgDgGQgCgEAAgJIAAgdIAAgMIAAgMQAAgHACgGQAEgIAGAAQAEAAAEAEQADADAAAFIAAAHQAMgPALAAQANAAAEAKQAFgFAGgCQAHgCAHAAQAQAAAGAQIADAXIAGArQABAEgEADQgDADgFAAQgKAAgBgJIgEgYIgCgWQgDgPgDAAIgJADIgKAHQAAAKADAPIACAcQAAAEgDADQgEAEgFAAQgDAAgDgEg");
	this.shape_14.setTransform(170,-47.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgbAjQgOgKAAgTQAAgTALgPQAMgQATAAQAPAAAJAFQAMAGAAANQABAJgLAHQgEADgOAEIgaANQAEAEAFACQAGACAFAAQALAAAIgEQAHgEAEAAQAJAAAAAIQAAAKgOAGQgMAFgNAAQgRAAgNgKgAgKgTQgGAFgDALIATgIQAJgFAHgFQgGgDgJAAQgFAAgGAFg");
	this.shape_15.setTransform(158.4,-47.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgGBBQgEgDAAgFIAAhxQAAgFAEgDQADgDADAAQAFAAADADQADADAAAFIAABsQAAAQgLAAQgEAAgCgDg");
	this.shape_16.setTransform(151.4,-49.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AghBCQgDgDAAgFIAAgfIAAgeIgBggIgCgQQAAgHADgFQAEgFAGAAQAFAAADADQADADAAAFIAAABQAFgEAGgCIAJgBQATAAAJARQAHALAAAUQAAAQgLAMQgLANgSAAQgGAAgHgCIgBAiQAAAFgDADQgDADgFAAQgFAAgDgDgAgDgmQgGACgFAFIABAgQAHADAGAAQAIgBAFgEQAEgFAAgJIgBgPQgDgKgIAAQgFAAgDACg");
	this.shape_17.setTransform(144.7,-45.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgGAvQgDgDAAgEIgCgcIgCgaIgBgJQgKAGgJANIgCACIAAAYIAAAGIAAAGQAAAFgEACQgDACgFAAQgHAAgDgGQgCgEAAgJIAAgdIAAgMIAAgMQAAgHACgGQAEgIAGAAQAEAAAEAEQADADAAAFIAAAHQAMgPALAAQANAAAEAKQAFgFAGgCQAHgCAHAAQAQAAAGAQIADAXIAGArQABAEgEADQgDADgFAAQgKAAgBgJIgEgYIgCgWQgDgPgDAAIgJADIgKAHQAAAKADAPIACAcQAAAEgDADQgEAEgFAAQgDAAgDgEg");
	this.shape_18.setTransform(133.6,-47.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgaAiQgMgLgBgTQAAgRAKgOQANgRAUAAQARAAAKANQAJAMAAASQAAARgLANQgLAQgSAAQgPAAgLgLgAgLgNQgFAIAAAJQAAAJAGAGQAEAEAGAAQAGAAAFgFQAGgGAAgKQACgYgQAAQgIAAgGAJg");
	this.shape_19.setTransform(122.2,-47.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgkAyQgMgNAAgSQAAgaAYgdQAVgYATAAIAIAAIAEABQAEgEAFAAQAJAAACAKIABAQQAAAEgCAEQgDAEgHAAQgHAAgEgIIgCgEIgIgBQgKAAgMARQgTAVAAATQABAJAFAHQAGAGAJAAQAGAAAIgEIAOgIQAGgFADAAQAFAAAEAEQADAEAAAEQAAAFgEADQgXAUgWAAQgSAAgOgOg");
	this.shape_20.setTransform(112.7,-49.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11}]},54).wait(4));

	// Layer 2
	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.lf(["#FFFFFF","#FF3366"],[0,1],-0.8,227.4,0.9,-227.3).s().p("EgjhAWlMAAAgtIMBHDAAAMAAAAtIg");
	this.shape_21.setTransform(46.5,-9.1);

	this.timeline.addTween(cjs.Tween.get(this.shape_21).wait(58));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-181,-153.6,603.7,289);


// stage content:
(lib.diag_Scene1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{scene1:0,scene1repeat:237});

	// timeline functions:
	this.frame_0 = function() {
		this.btn_menu.addEventListener("click", openMenu.bind(this));
		this.btn_goNext.addEventListener("click", openNext.bind(this));
		this.btn_goBack.addEventListener("click", openPrev.bind(this));
		
		
		function openMenu(){
		
		 window.open ("../menu/menu.html","_self");
		}
		
		
		function openNext(){
		
		 window.open ("diag_Scene2.html","_self");
		}
		
		function openPrev(){
		
		 window.open ("diag_Scene0.html","_self");
		}
	}
	this.frame_30 = function() {
		playSound("thediagramformconsistsof2");
	}
	this.frame_253 = function() {
		this.gotoAndPlay("scene1repeat");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(30).call(this.frame_30).wait(223).call(this.frame_253).wait(1));

	// predicate
	this.instance_4 = new lib.text_predicate("synched",0);
	this.instance_4.setTransform(324.1,81.5,1,1,0,0,0,43,14.6);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(222).to({_off:false},0).to({x:324.6,y:81.2,alpha:1},6).wait(26));

	// bracket
	this.instance_5 = new lib.bracketdisplay("synched",0,false);
	this.instance_5.setTransform(324,109.3,1,1,0,0,0,118,11.4);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(222).to({_off:false},0).wait(32));

	// Highlights
	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f().s("#FFFFFF").ss(10,1,1).p("A2tAAMAtbAAA");
	this.shape_22.setTransform(271.9,222.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f().s("#FFFFFF").ss(10,1,1).p("A2tAAIKnAAMAi0AAA");
	this.shape_23.setTransform(271.9,222.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f().s("#FF0000").ss(8,1,1).p("AAAojIAAJBIAAIG");
	this.shape_24.setTransform(194.4,219.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f().s("#FFFFFF").ss(10,1,1).p("AxaAAMAi1AAA");
	this.shape_25.setTransform(305.9,222.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("#00CC00").ss(8,1,1).p("AAAkaIAAI0");
	this.shape_26.setTransform(325.9,190.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f().s("#FFFFFF").ss(10,1,1).p("AlSAAIKlAA");
	this.shape_27.setTransform(160.4,222.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f().s("#FF0000").ss(4,1,1).p("AjlAAIHLAA");
	this.shape_28.setTransform(266.5,160.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f().s("#00CC00").ss(4,1,1).p("AldAAIK8AA");
	this.shape_29.setTransform(384.2,160.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_22}]},62).to({state:[{t:this.shape_24},{t:this.shape_23}]},29).to({state:[{t:this.shape_24},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25}]},37).to({state:[]},64).to({state:[{t:this.shape_28}]},11).to({state:[{t:this.shape_29},{t:this.shape_28}]},11).wait(40));

	// main
	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f().s("#000000").ss(4,1,1).p("EAjoAWkMhHPAAAMAAAgtHMBHPAAAg");
	this.shape_30.setTransform(274,187.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_30).wait(254));

	// Mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgjrAWzMAAAgtlMBHXAAAMAAAAtlg");
	mask.setTransform(274.5,188);

	// Scene
	this.instance_6 = new lib.Scene1();
	this.instance_6.setTransform(274,184,1,1,0,0,0,46,-12.7);

	this.instance_6.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(254));

	// buttons
	this.btn_menu = new lib.skiptomenu();
	this.btn_menu.setTransform(514.1,20.3);
	new cjs.ButtonHelper(this.btn_menu, 0, 1, 2, false, new lib.skiptomenu(), 3);

	this.instance_7 = new lib.Copyright("synched",0);
	this.instance_7.setTransform(275,393.5);

	this.btn_goBack = new lib.goNext();
	this.btn_goBack.setTransform(57.6,352.3,1,1,0,0,180);
	new cjs.ButtonHelper(this.btn_goBack, 0, 1, 2, false, new lib.goNext(), 3);

	this.btn_goNext = new lib.goNext();
	this.btn_goNext.setTransform(494,352.3);
	new cjs.ButtonHelper(this.btn_goNext, 0, 1, 2, false, new lib.goNext(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.btn_goNext},{t:this.btn_goBack},{t:this.instance_7},{t:this.btn_menu}]}).wait(254));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(284.2,201.8,537.1,401.2);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;