(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 550,
	height: 400,
	fps: 12,
	color: "#FFFFFF",
	webfonts: {},
	manifest: [
		{src:"sounds/_12a.mp3", id:"_12a"},
		{src:"sounds/_12b.mp3", id:"_12b"},
		{src:"sounds/_13b.mp3", id:"_13b"},
		{src:"sounds/_13c.mp3", id:"_13c"},
		{src:"sounds/_16a.mp3", id:"_16a"},
		{src:"sounds/_18b.mp3", id:"_18b"},
		{src:"sounds/_19b.mp3", id:"_19b"},
		{src:"sounds/_2a.mp3", id:"_2a"},
		{src:"sounds/_3a.mp3", id:"_3a"},
		{src:"sounds/_4a.mp3", id:"_4a"},
		{src:"sounds/_6a.mp3", id:"_6a"},
		{src:"sounds/_7b.mp3", id:"_7b"},
		{src:"sounds/_9a.mp3", id:"_9a"},
		{src:"sounds/bgmusic.mp3", id:"bgmusic"},
		{src:"sounds/JinglePronoun.mp3", id:"JinglePronoun"},
		{src:"sounds/MenuPronoun.mp3", id:"MenuPronoun"},
		{src:"sounds/s_coolcheer.mp3", id:"s_coolcheer"},
		{src:"sounds/hesheit.mp3", id:"hesheit"},
		{src:"sounds/himherit.mp3", id:"himherit"},
		{src:"sounds/i.mp3", id:"i"},
		{src:"sounds/me.mp3", id:"me"},
		{src:"sounds/nominative.mp3", id:"nominative"},
		{src:"sounds/objectis.mp3", id:"objectis"},
		{src:"sounds/objectivecase.mp3", id:"objectivecase"},
		{src:"sounds/objectsof.mp3", id:"objectsof"},
		{src:"sounds/replaces.mp3", id:"replaces"},
		{src:"sounds/subjectis.mp3", id:"subjectis"},
		{src:"sounds/subjectof.mp3", id:"subjectof"},
		{src:"sounds/substitutes.mp3", id:"substitutes"},
		{src:"sounds/them.mp3", id:"them"},
		{src:"sounds/they.mp3", id:"they"},
		{src:"sounds/us.mp3", id:"us"},
		{src:"sounds/we.mp3", id:"we"},
		{src:"sounds/you.mp3", id:"you"}
	]
};



lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib.skiptomenu = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AATApQgLAGgMAAQgMAAgHgFQgJgGgBgKQgEgYABgQQgBgMADgPQABgIAHAAQAEAAADADQACACAAAEIgBANIgBANIABAXQABALACAGIAGADIAFAAQAKAAANgDIAAgSIgBgPQAAgTACgOQABgIAIAAQADAAADACQADADgBADIgBAhIAAARIAAATIAAAGIAAAGQABAEgDACQgDADgDAAQgHAAgCgJg");
	this.shape.setTransform(16.7,0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AAVAqIgDgTIgBgTIABgGIAAgJQAAgSgHgBQgKAAgHAMQgIALgFAOIgBAIIAAAJIAAAIIABAIQAAAEgCADQgDACgEAAQgDAAgDgCQgCgDAAgEIgBgIIAAgIIABgYIABgYIAAgIIAAgJQAAgDACgDQADgDADABQAIAAABALIAAAKQAPgUAOAAQAOAAAFANQAEAIAAAQIAAAJIAAAGIACATQACAMAAAHQAAAEgCADQgDABgEAAQgHABgBgJg");
	this.shape_1.setTransform(7.5,0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgdAmQgNgMAAgTQAAgVALgQQAMgQATgBQAOAAAJAGQALAFAAANQAAAJgKAHQgEADgOAFIggAQQAFAIAHADQAIADAIAAQAGAAAIgBQAKgDADgFQADgFAEAAQADAAACADQACACAAADQAAAKgPAGQgOAHgMAAQgSAAgNgKgAgRgWQgHAIgDAPIAbgLQAOgIAGgFQgHgIgNAAQgKABgHAIg");
	this.shape_2.setTransform(-2.2,0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgEAzQgCgCAAgEIgCggIgCgdQAAgJgDgGQgGADgHAHIgKALIgEAGIgBANIgBAPIAAAIIABAHQAAADgCADQgDACgEAAQgKAAAAgWIABgQIABgOIAAgOIgBgOQAAgUAJAAQADAAADADQADADAAAEIgBAFIAAAFIAAAJQAFgJAIgIQAJgHAHAAQANAAAEAOQAEgHAHgDQAHgDAIAAQAPAAAFAQQACADACAVIAGAxQABADgDADQgDACgDAAQgIAAgBgIIgDgbIgDgZQgBgGgCgGQgDgIgDAAQgEAAgJAGQgIAFgDADIABAQIACAWQACAOAAAJQAAAEgCACQgDADgEAAQgBAAgDgDg");
	this.shape_3.setTransform(-14.1,0.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(2,1,1).p("AkZh7IIzAAIAAD3IozAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AkZB8IAAj3IIzAAIAAD3g");

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAVAuQgMAGgOAAQgMAAgJgGQgJgGgBgMQgEgZAAgSQAAgNADgRQABgJAIAAQAEAAADADQADADAAAEIgCAOIgBAPIABAZQABAMACAHIAGADIAGAAQALAAAPgEIAAgTIAAgRQAAgVABgPQABgJAJAAQAEAAADACQADADgBAEIgBAlIAAATIAAAVIAAAGIAAAHQAAAEgCACQgDADgEAAQgIAAgCgJg");
	this.shape_6.setTransform(18.3,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AAXAvIgDgWIgBgVIAAgHIABgJQAAgVgIAAQgLAAgIANQgJALgFAQIgBAKIAAAJIAAAJIABAJQAAAEgDADQgCACgFAAQgEAAgCgCQgDgDAAgEIgBgJIAAgJIABgaIACgbIgBgJIAAgJQAAgFADgCQACgDAEAAQAJAAABANIAAALQARgWAPAAQAPAAAGAOQAFAJAAASIAAAKIAAAHQAAAIACAMQACANAAAIQAAAEgDADQgDADgEAAQgIAAgBgJg");
	this.shape_7.setTransform(8.2,0.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AggApQgPgMAAgWQAAgXAMgRQAOgSAVAAQAPAAAKAFQANAHAAAOQAAAJgMAIQgEAEgQAFIgjASQAFAIAJAEQAIAEAJAAQAHAAAIgDQALgDAEgFQADgFAEAAQADAAADACQADADAAADQAAALgRAIQgPAGgOAAQgVAAgNgLgAgTgZQgHAJgEARIAdgMQAQgJAIgGQgJgIgOAAQgLAAgIAJg");
	this.shape_8.setTransform(-2.4,0.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgEA5QgDgDAAgFQAAgLgCgXQgDgVAAgMQAAgKgCgGQgHADgHAHIgMANIgEAGIgCAPIgBARIABAIIABAIQAAAEgDACQgDADgEAAQgLAAAAgZIACgRIABgPIgBgQIgBgPQAAgWAKAAQADAAAEADQADAEAAADIgBAGIAAAGIAAAKQAFgKAKgJQAJgIAHAAQAPAAAEAPQAGgHAHgDQAHgEAKAAQAQAAAGARIAEAcIAHA1QAAAEgDADQgDACgEAAQgIAAgBgIQgCgLgCgTIgDgcIgDgNQgEgJgEAAQgDAAgKAGQgJAGgDADIAAASIADAYQACAQAAAJQAAAFgCADQgDACgEAAQgCAAgDgCg");
	this.shape_9.setTransform(-15.6,0.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#000000").ss(2,1,1).p("AE3CJIptAAIAAkRIJtAAg");
	this.shape_10.setTransform(0,0.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#00FFFF").s().p("Ak2CJIAAkRIJsAAIAAERg");
	this.shape_11.setTransform(0,0.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AATApQgLAGgMAAQgMAAgHgFQgJgGgBgKQgEgYABgQQgBgMADgPQABgIAHAAQAEAAADADQACACAAAEIgBANIgBANIABAXQABALACAGIAGADIAFAAQAKAAANgDIAAgSIgBgPQAAgTACgOQABgIAIAAQADAAADACQADADgBADIgBAhIAAARIAAATIAAAGIAAAGQABAEgDACQgDADgDAAQgHAAgCgJg");
	this.shape_12.setTransform(16.7,1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAVArIgDgUIgBgTIABgHIAAgHQAAgUgHAAQgKAAgHAMQgIALgFAOIgBAJIAAAIIAAAIIABAIQAAAEgCACQgDACgEAAQgDAAgDgCQgCgCAAgEIgBgIIAAgIIABgYIABgYIAAgJIAAgIQAAgEACgCQADgCADgBQAIAAABAMIAAAKQAPgTAOgBQAOAAAFANQAEAIAAARIAAAIIAAAGIACAUQACALAAAHQAAAEgCACQgDACgEABQgHgBgBgHg");
	this.shape_13.setTransform(7.5,0.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgdAlQgNgLAAgTQAAgVALgPQAMgSATABQAOAAAJAEQALAHAAAMQAAAJgKAHQgEADgOAFIggAQQAFAHAHAEQAIAEAIAAQAGgBAIgCQAKgDADgEQADgFAEAAQADAAACACQACACAAAEQAAAJgPAIQgOAFgMAAQgSAAgNgKgAgRgWQgHAIgDAPIAbgLQAOgIAGgGQgHgGgNgBQgKAAgHAJg");
	this.shape_14.setTransform(-2.2,0.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgEAzQgCgCAAgEIgCggIgCgdQAAgJgDgGQgGADgHAHIgKALIgEAGIgBANIgBAPIAAAIIABAHQAAADgCADQgDACgEAAQgKAAAAgWIABgQIABgOIAAgOIgBgOQAAgUAJAAQADAAADADQADADAAAEIgBAFIAAAFIAAAJQAFgJAIgIQAJgHAHAAQANAAAEAOQAEgHAHgDQAHgDAIAAQAPAAAFAQQACADACAVIAGAxQABADgDADQgDACgDAAQgIAAgBgIIgDgbIgDgZQgBgGgCgGQgDgIgDAAQgEAAgJAGQgIAFgDADIABAQIACAWQACAOAAAJQAAAEgCACQgDADgEAAQgBAAgDgDg");
	this.shape_15.setTransform(-14.1,1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#000000").ss(2,1,1).p("AEah7IAAD3IozAAIAAj3g");

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#0066CC").s().p("AkZB8IAAj3IIzAAIAAD3g");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},1).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12}]},1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-29.2,-16.9,58.6,30.5);


(lib.pronounheader = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAdA7IgDgbQgCgOAAgMIABgKIAAgMQAAgagKAAQgOAAgKAQQgLAPgGAVIgBAMIgCALIACALIAAAMQAAAFgDAEQgDADgGAAQgFAAgEgDQgDgEAAgFIAAgMIgBgLIABghIACgiIAAgMIgBgLQABgFADgEQADgEAFAAQAMAAABAQIAAAPQAUgcAUABQATgBAJASQAFALAAAWIAAANIAAAJQAAALACAPQAEAQAAALQgBAFgDAEQgEACgFAAQgLAAgBgLg");
	this.shape.setTransform(134.8,3.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAbA6QgQAHgRAAQgQAAgLgGQgLgJgDgPQgEgfAAgYQAAgQADgWQACgLAKAAQAFAAAEAEQADADAAAGIgCASIgBASIABAhQABAPADAIIAIAEIAIABQAOAAASgGIAAgYIAAgWQAAgbACgSQABgMALAAQAFAAAEAEQADADAAAFIgCAuIAAAZIAAAaIABAIIAAAJQAAAFgEADQgDADgFABQgKgBgCgLg");
	this.shape_1.setTransform(121.5,4.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgjAzQgRgRgBgcQAAgaAOgVQARgYAdAAQAYAAANAWQAKASAAAZQgBAagOATQgPAVgYAAQgVAAgOgPgAgVgXQgIANAAAQQAAASAKAKQAIAIALAAQALAAAJgJQAKgLABgRQACgtgcgBQgQAAgKASg");
	this.shape_2.setTransform(108.2,4.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AhRBfQgDgEgBgFIABgPIABgQIAAgXIABgWIAAgXIgBgYIgBgXIgCgXQAAgGAGgEQAEgFAHAAQAFAAALAOQAdAuAYAeQAcAiAjAgIAAgPIgBgPQAAg0gEggIgDgNQgDgIAAgEQAAgPANAAQAVAAAABQIAAAmIgBApIgCATQgCAMgKAAQgHAAgJgJQgygvg/hWIAAAbIgBAaIABAfIAAAeQAAAhgMAAQgHAAgEgEg");
	this.shape_3.setTransform(92.1,1.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAnA+IgJgJIgUAKQgJADgEAAQgdAAgNgQQgMgPAAggQAAgbAUgVQAVgVAaAAQAKAAAOAFQAQAHAAAKQAAADgCADIgCAPIgBAZQAAAPACAJIAIAWIADAGIAAACQAAAFgDADQgDADgFAAQgCAAgGgFgAgTgdQgOAPAAASQAAAUAHAKQAHAKAOAAQAKAAAIgEIANgJQgEgfAAgQIAAgLIACgNIgHgDIgGgCQgRAAgNAQg");
	this.shape_4.setTransform(68.1,4.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AghBDQgTgHAAgLQAAgFAEgEQAEgEAFAAQAEAAAGAGQADADAKACIAOABQAIAAAIgCQALgEAAgIQAAgQgXgGIgLgDQgQgEgHgEQgKgFAAgOQAAgZAYgLQAIgDAOgFIAXgHQAFgDAGAAQAFAAADAEQAEADAAAGIABAKIACAKQAAAGgEADQgDAEgFgBQgHABgDgFQgCgDgBgKQgJACgTAGQgSAIAAALIAHADQAaAFAOAIQAUALAAAYQAAAVgRAKQgPAIgTAAQgQAAgPgGg");
	this.shape_5.setTransform(47.8,3.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgoA1QgTgQAAgcQAAgdAPgWQARgXAbAAQATAAANAHQAQAIAAARQAAANgOAKQgGAFgUAGIgtAXQAHAKALAFQAKAFALAAQAJAAALgDQAOgEAFgHQAEgGAEAAQAFAAADADQADADAAAFQAAANgVAKQgTAIgSAAQgZAAgRgNgAgYggQgKAMgFAVIAmgQQAUgLAJgIQgKgJgSAAQgOAAgKALg");
	this.shape_6.setTransform(35.4,4.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgiA1QgRgQAAgaQAAgWAQgbQASgdAVAAQAMAAAPAGQATAHAAAKQAAAFgDADQgDAEgFAAQgDAAgDgCIgFgEQgHgGgRAAQgKAAgMAWQgLAVAAAMQAAARALAJQAKAIAOAAQAHAAAJgDIAOgIIAFgCQAEAAAEAEQADADAAAFQAAAJgTAIQgQAHgLAAQgXAAgRgPg");
	this.shape_7.setTransform(22,4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAnA+IgJgJIgUAKQgJADgEAAQgdAAgNgQQgMgPAAggQAAgbAUgVQAVgVAaAAQAKAAAOAFQAQAHAAAKQAAADgCADIgCAPIgBAZQAAAPACAJIAIAWIADAGIAAACQAAAFgDADQgDADgFAAQgCAAgGgFgAgTgdQgOAPAAASQAAAUAHAKQAHAKAOAAQAKAAAIgEIANgJQgEgfAAgQIAAgLIACgNIgHgDIgGgCQgRAAgNAQg");
	this.shape_8.setTransform(9.1,4.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgMBYIABgsIABgsIABgrIAAgsQABgMAJAAQAMAAABAMIgBAsIAAArIgDA8IgBAcQAAAMgKAAQgLAAAAgMg");
	this.shape_9.setTransform(-0.7,0.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AguBjQgDgEAAgFIAAgxIAAgvQAAgbgCgVIgCgZQAAgJADgGQAEgHAHAAQAFAAADAEQADACAAAGIAAADIgBAIQALgIAJgDQAJgEAIAAQAZAAAMAWQAJASAAAdQAAAYgOARQgPATgZAAQgLAAgOgFIgBA7QAAAFgDAEQgDADgFAAQgGAAgDgDgAgKg/QgHADgKAJQACAcAAAcQANAGAMgBQAPABAIgLQAHgJAAgPQAAgXgFgLQgGgLgLAAQgJAAgJAGg");
	this.shape_10.setTransform(-10.7,7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgoA1QgTgQAAgcQAAgdAPgWQARgXAbAAQATAAANAHQAQAIAAARQAAANgOAKQgGAFgUAGIgtAXQAHAKALAFQAKAFALAAQAJAAALgDQAOgEAFgHQAEgGAEAAQAFAAADADQADADAAAFQAAANgVAKQgTAIgSAAQgZAAgRgNgAgYggQgKAMgFAVIAmgQQAUgLAJgIQgKgJgSAAQgOAAgKALg");
	this.shape_11.setTransform(-24.1,4.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AguA4IAAhUIABgMIAAgMQgBgNALAAQAMAAAAAVQAXgXAbAAQALAAAEAIQAFAHAAAPIAAAJQgBAPgMAAQgKAAAAgMIAAgJIAAgKQgUACgKAJQgKAIgIAQIABBBQAAAMgNAAQgKAAAAgMg");
	this.shape_12.setTransform(-36.8,4.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#9C30CE").s().p("AAdA7IgDgbQgCgOAAgMIABgKIAAgMQAAgagKAAQgOAAgKAQQgLAPgGAVIgBAMIgCALIACALIAAAMQAAAFgDAEQgDADgGAAQgFAAgEgDQgDgEAAgFIAAgMIgBgLIABghIACgiIAAgMIgBgLQABgFADgEQADgEAFAAQAMAAABAQIAAAPQAUgcAUABQATgBAJASQAFALAAAWIAAANIAAAJQAAALACAPQAEAQAAALQgBAFgDAEQgEACgFAAQgLAAgBgLg");
	this.shape_13.setTransform(-56.9,3.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#9C30CE").s().p("AAbA6QgQAHgRAAQgQAAgLgGQgLgJgDgPQgEgfAAgYQAAgQADgWQACgLAKAAQAFAAAEAEQADADAAAGIgCASIgBASIABAhQABAPADAIIAIAEIAIABQAOAAASgGIAAgYIAAgWQAAgbACgSQABgMALAAQAFAAAEAEQADADAAAFIgCAuIAAAZIAAAaIABAIIAAAJQAAAFgEADQgDADgFABQgKgBgCgLg");
	this.shape_14.setTransform(-70.2,4.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#9C30CE").s().p("AgjAzQgRgRgBgcQAAgaAOgVQARgYAdAAQAYAAANAWQAKASAAAZQgBAagOATQgPAVgYAAQgVAAgOgPgAgVgXQgIANAAAQQAAASAKAKQAIAIALAAQALAAAJgJQAKgLABgRQACgtgcgBQgQAAgKASg");
	this.shape_15.setTransform(-83.5,4.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#9C30CE").s().p("AAdA7IgDgbQgCgOAAgMIAAgKIABgMQAAgagKAAQgNAAgLAQQgLAPgGAVIgCAMIgBALIABALIABAMQAAAFgDAEQgEADgFAAQgFAAgEgDQgDgEAAgFIAAgMIgBgLIACghIABgiIAAgMIgBgLQABgFADgEQADgEAFAAQAMAAABAQIAAAPQAUgcAUABQATgBAIASQAGALAAAWIAAANIAAAJQAAALACAPQAEAQAAALQAAAFgEAEQgDACgGAAQgLAAgBgLg");
	this.shape_16.setTransform(-96.1,3.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#9C30CE").s().p("AgjAzQgRgRgBgcQAAgaAOgVQARgYAdAAQAYAAANAWQAKASAAAZQgBAagOATQgPAVgYAAQgVAAgOgPgAgVgXQgIANAAAQQAAASAKAKQAIAIALAAQALAAAJgJQAKgLABgRQACgtgcgBQgQAAgKASg");
	this.shape_17.setTransform(-109.8,4.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#9C30CE").s().p("AguA4IAAhUIAAgMIAAgMQAAgNALAAQANAAAAAVQAWgXAbAAQALAAAEAIQAFAHAAAPIAAAJQgBAPgMAAQgKAAAAgMIAAgJIAAgKQgUACgKAJQgKAIgIAQIABBBQAAAMgNAAQgKAAAAgMg");
	this.shape_18.setTransform(-121.7,4.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#9C30CE").s().p("AgyBdQgEgDAAgFIAAgkQAAgRADggIACgyIAAgRQAAgMACgFQADgLAJABIALgBIASgBQAUAAATAQQAWAQAAAYQAAAfgXAPQgVAQgaAAIgPgBIgBBAQAAAFgDADQgEAEgEAAQgFAAgDgEgAgahHIAAAWIgDAxIAOAAQASAAAOgJQAQgMAAgTQAAgOgPgJQgOgJgNAAIgKAAIgHABg");
	this.shape_19.setTransform(-134.5,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-143.2,-19.4,286.4,38.8);


(lib.prowordstill = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgcApQgNgOgBgWQAAgUALgRQAOgUAXAAQATAAAKASQAIAOAAAUQAAAUgLAQQgNARgTAAQgQAAgMgMgAgQgTQgGAMAAAMQAAAOAHAIQAHAGAIAAQAJAAAHgHQAIgIABgOQABgkgWAAQgMAAgIANg");
	this.shape.setTransform(9.9,1.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AglAsIAAhCIABgKIAAgJQAAgKAIAAQAKAAAAAQQASgSAWAAQAIAAADAGQAEAGABAMIAAAHQgBAMgJAAQgJAAABgKIgBgHIAAgIQgPACgIAHQgIAGgHANIABAzQAAAKgKAAQgJAAAAgKg");
	this.shape_1.setTransform(0.3,1.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgoBLQgCgDAAgEIAAgcIABgoIACgnIAAgOQAAgJABgFQACgIAIABIAJgCIAOAAQAQAAAQAMQAQAOAAASQABAYgTANQgQAMgVAAIgMgBIgBA0QAAAEgDADQgCACgDAAQgEAAgDgCgAgPg5IgGAAIAAASIgCAnIALAAQAOAAALgIQANgIAAgQQAAgLgMgHQgLgIgKAAIgIABg");
	this.shape_2.setTransform(-9.8,-1.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-17.3,-18,34.6,31.9);


(lib.proboxingstill = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgLAMQgFgFAAgHQAAgFAFgGQAFgFAGAAQAHAAAFAFQAFAGAAAFQAAAHgFAFQgFAFgHAAQgGAAgFgFg");
	this.shape.setTransform(170,11.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgxBgQgUgUAAgfQAAgmAUgVQAUgWAeAAQAQAAAJAEIAOAKQACg8ACgUQACgNALAAQANAAAAAOQAAATgGBEIgBAoQAAAvAEAYIAAADQAAAGgEADQgEAEgFAAQgJAAgEgNQgKAIgLADQgLAFgKAAQgdAAgTgUgAggACQgMAOAAAcQAAATANAMQANAOARAAQAKAAAIgFQAFgCALgKIAEgEIAAgYIAAgRIAAgRQgFgKgJgFQgJgFgNAAQgVAAgMAMg");
	this.shape_1.setTransform(157.7,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgpA8QgTgUgBghQgBgeARgYQAUgdAhAAQAdAAAOAaQAMAVgBAdQAAAegQAWQgSAZgcAAQgYAAgRgRgAgYgcQgJAQAAATQAAAVALALQAJAKANAAQANAAAKgLQAMgMABgUQACg1gfAAQgTAAgMATg");
	this.shape_2.setTransform(141.3,4.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgpA8QgTgUgBghQgBgeARgYQAUgdAhAAQAdAAAOAaQAMAVgBAdQAAAegQAWQgSAZgcAAQgYAAgRgRgAgYgcQgJAQAAATQAAAVALALQAJAKANAAQANAAAKgLQAMgMABgUQACg1gfAAQgTAAgMATg");
	this.shape_3.setTransform(126.1,4.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgwBuQgSgEAAgLQAAgNAMAAIASADQAMACAOgBQAZAAALgaQAGgRABgkQgIAOgKAIQgLAGgMAAQgZAAgRgRQgPgRAAgbQgBglAWgYQAXgYAlAAQAOAAAIADQAJAEAFAGQAPABAAAQQAAALgDAQIgEAbIgDAuQgBAcgFASQgGAXgOAKQgRAOgfAAQgSAAgNgCgAgZhGQgNARAAAZQAAAVAIAJQAIAKAPAAQANAAANgOQAMgPACgOIAGgxQgFgEgHgCQgFgDgHAAQgZABgPASg");
	this.shape_4.setTransform(110.8,8.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgnBOQgVgHAAgPQAAgFAEgEQAEgFAGAAQAFAAAGAHQAEADAMACQAJACAHAAQAKAAAJgDQANgEAAgJQAAgTgbgHIgNgDQgSgFgJgFQgLgGABgQQgBgeAcgMQAJgEARgFIAagJQAGgCAGgBQAHAAAEAFQADADABAHIABALIACAMQAAAHgDAEQgEAEgGAAQgJAAgCgGQgDgDgCgLIggAKQgVAIAAANIAJADQAeAGAQAKQAXANAAAcQAAAXgUAMQgRAJgXAAQgTABgRgHg");
	this.shape_5.setTransform(87.3,4.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgMBmQgFgEAAgGIAAgaIgBgZIACghIABgfQAAgHAEgEQAEgEAGAAQAEAAAEAEQAEAEAAAHIgCAfIgBAhIAAAZIABAaQAAAGgDAEQgEAEgFAAQgGAAgDgEgAgIhNQgFgFAAgGQAAgHAFgFQAFgFAFAAQAHAAAFAFQAEAFAAAHQAAAGgEAFQgFAFgHAAQgFAAgFgFg");
	this.shape_6.setTransform(76.8,1.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgLAMQgFgFAAgHQAAgFAFgGQAFgFAGAAQAHAAAFAFQAFAGAAAFQAAAHgFAFQgFAFgHAAQgGAAgFgFg");
	this.shape_7.setTransform(8.4,11.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgwBuQgSgEAAgLQAAgNANAAIARADQAMACAOgBQAZAAALgaQAGgRABgkQgIAOgKAIQgLAGgLAAQgbAAgQgRQgQgRAAgbQAAglAXgYQAWgYAlAAQAOAAAIADQAJAEAFAGQAPABAAAQQAAALgDAQIgEAbIgDAuQgBAcgFASQgGAXgOAKQgRAOgeAAQgTAAgNgCgAgZhGQgNARAAAZQAAAVAIAJQAHAKAQAAQANAAANgOQAMgPACgOIAGgxQgGgEgGgCQgFgDgHAAQgZABgPASg");
	this.shape_8.setTransform(-3.2,8.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAiBEIgEgfQgCgQAAgPIAAgLIABgNQAAgfgLAAQgQAAgMATQgOARgHAYIgBAOIgBAOIABANIAAAMQABAHgEAEQgEAEgGAAQgGAAgEgEQgEgEAAgHIgBgMIgBgNIACgnIACgoIgBgOIAAgNQAAgGAFgEQADgEAGAAQANAAACATIAAAQQAYggAXAAQAWAAAKAUQAGAOAAAaIAAAOIAAALQAAAMADATQADASAAAMQAAAGgEAEQgEAEgGAAQgNAAgBgOg");
	this.shape_9.setTransform(-18,4.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgNBmQgEgEAAgGIAAgaIAAgZIABghIABgfQAAgHAEgEQAEgEAGAAQAEAAAEAEQAEAEAAAHIgCAfIgBAhIAAAZIABAaQAAAGgDAEQgFAEgEAAQgGAAgEgEgAgIhNQgFgFAAgGQAAgHAFgFQAFgFAEAAQAHAAAGAFQAEAFAAAHQAAAGgEAFQgGAFgHAAQgEAAgFgFg");
	this.shape_10.setTransform(-29.7,1.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAsBMQgNgPgfgsIgcAdIgYAXQgFAFgFAAQgFAAgEgEQgFgEAAgGQAAgEAEgFIAMgMIANgMIAegeIgSgaQgLgQgJgIQgFgFAAgFQAAgGAEgEQAEgFAFAAQAIAAARAWIAXAiIAcgaQARgQAGgJQAEgHAHAAQAFAAAEAEQAFAEAAAGQAAAIgNANIgVAUIgZAZIAuA6QADAFAAAEQAAAFgEAFQgEAEgFAAQgGAAgEgFg");
	this.shape_11.setTransform(-42.7,4.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgpA8QgTgUgBghQgBgeARgYQAUgdAhAAQAdAAAOAaQAMAVgBAdQAAAegQAWQgSAZgcAAQgYAAgRgRgAgYgcQgJAQAAATQAAAVALALQAJAKANAAQANAAAKgLQAMgMABgUQACg1gfAAQgTAAgMATg");
	this.shape_12.setTransform(-59.1,4.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgqBqQgFAGgGAAQgFAAgEgEQgEgDAAgGIABgLIAAgKIgBgtIgBgrIAAgoIAAgnQAAgIAEgIQAFgIAIAAQALAAgBANIAAAFIgBAGIgBAfIAAAkQAMgJAMgEQALgDAHAAQAfgBATAXQASAVAAAfQAAAhgVAWQgVAXgcAAQgXAAgRgIgAgVgGIgVANIAAAYIAAAWIAAAYIATAHQAKADALAAQASAAANgPQANgOAAgWQAAgUgKgPQgMgNgUAAQgJAAgMAGg");
	this.shape_13.setTransform(-74.7,0.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgmBOQgWgHAAgPQAAgFAFgEQAEgFAFAAQAFAAAGAHQAEADAMACQAKACAGAAQAKAAAJgDQANgEAAgJQAAgTgbgHIgMgDQgUgFgHgFQgLgGAAgQQAAgeAbgMQAIgEASgFIAagJQAGgCAGgBQAHAAAEAFQAEADAAAHIACALIABAMQAAAHgDAEQgFAEgFAAQgIAAgEgGQgCgDgBgLIghAKQgVAIAAANIAJADQAeAGAQAKQAXANAAAcQAAAXgUAMQgQAJgYAAQgSABgRgHg");
	this.shape_14.setTransform(-99.7,4.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgMBmQgFgEAAgGIAAgaIgBgZIACghIABgfQAAgHAEgEQAEgEAGAAQAEAAAEAEQAEAEAAAHIgCAfIgBAhIAAAZIABAaQAAAGgDAEQgFAEgEAAQgGAAgDgEgAgIhNQgFgFAAgGQAAgHAFgFQAFgFAEAAQAHAAAGAFQAEAFAAAHQAAAGgEAFQgGAFgHAAQgEAAgFgFg");
	this.shape_15.setTransform(-110.1,1.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-116.7,-22.2,292.2,44.4);


(lib.proboxstill = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.5,1,1).p("AE0BlIoRAAAhthkIi6AAIgMAA");
	this.shape.setTransform(-58.6,85.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#010101").s().p("AgBAOQABgOACgNIAAALIgBAMIABAEIgDAAg");
	this.shape_1.setTransform(-93.1,89.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AmNNOIgCAAQgfgJgWgTIAAgBQAxgTAqgbIAqgaQAWgOADgZIAGgIIAPgXIABAAIAHgBQABAHgBAGIgDALIgJAqQgBADACACQAFAGAEgCQADgBACgIIALgoIABgCIACgKQACgJgDgGQAZgBAXAFQAZAHAWAOIAIAGIAAAAQAAAJgRAKIgNAJIgLAJQgHgBgKAFQAKgJALgHQALgGAFgKQAGgJgDgGQgCgDgFgDQgFAAgBAFIgBABQgEAOgPAGQgBAAAAAAQgBAAgBABQAAAAAAABQgBAAAAAAIgcAeQgDADADADQACAEADABIgWARQgbATgcARQgHAEgGAGQgHAMABAMIAAACIhNgEgAjKKnIgDABQgBAAAAABQgBAAAAAAQgBABAAAAQAAABAAAAIgBAJIgFAGIgGAFQgVARgTATQgDADACADQAEAPALgLIApgmQAGgFADgIIAAgBQAGgNgMgFgAmqJ4IgBAAQAAgLgDgNIABAAQACgJgBgDIABgBQAHgiATgXIACAAQA5ABAwgOIAQgMIAIgGIADALIgDAAQAAABgBAAQAAAAgBABQAAAAAAABQAAAAgBABQgBACABADIgLAKIgRAOQgGAFgIAFIgHACQgJACgFAHQgCADACACQAFAFAGAAIgBAKIgMADQgOADACAMQAAABAAABQAAAAABAAQAAABABAAQAAAAABAAQAKAAAKgCQAJgCAJgEIAGgDQAYgPAXgQQgFAMgCAOQgCAQgEAOIgEABIgIgCIgPgCIgBgBIgBAAIAAABIgfgBIgHgBQgYgDgWAGIgBADQgOAFgRAAIgMgBgAGWqPQgJgGgJgIIgFgEIgIgHIgMgNIgGgHQgFgJAEgIIgBAAIAAgCIADgCIAEgEIACgCQAGAAAFACQAIADAEAKIABABQANAIAHAMQAIAFAIADIAOAEIAAABIgaAZIgCABIgEgDgAGRsBIgCgBIgDgCQgCgEACgGQgEgKABgLQABgKACgKIABgBIABgDIACgDIAAgBQAHgJAJgFIADgCIADgCQARgCAHAOIADAEQADAIABAHIgEgCIgPgBQgFADgDAHQgDAKAHAHQAIAJAMgEIACAAIgGAEQgFACgFAFIgGAEQgJAGgLAAIgJgBg");
	this.shape_2.setTransform(-17.7,5.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF0000").s().p("AjqEHIgBgBIgNAAIgCAAIgFgCIghgTIAAgBQgMAKgQAFIAAACQgYACgXgFIgDAAIgCgBIgDgBIgBAFQgBAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAIgSAAIgBAAIAAABQgNAEgIgEQgHgDgEgGIgIgEQgDgBgCgDIgBAAIgCABQgMgQgGgVIgBgCQAGggARgUQAAAAABgBQAAAAABAAQAAAAAAAAQABAAAAABIAFgCIACgBIAGAAIAAAAIACgBQACgCAFABQAJACgHATQgFAOAGAPQAQAjAcARIAFADQAIgFgMgKQgfgYgHguQADgGACgFIAAgCIAAgEQABgIAEgHIADgEIABgDIAAAAIACgEIABgCIAWgwQAMgdAbgPQAPgIAQgFQATgGAVgCQAegBAiAIQAhAJAXAUQAhAfAJA4QAFAjgKAqQgDAHgFAEIAAABQgDAHgFAGQgNAQgQAJQgOAIgSACQgQABgPgBIgHAAIAAABQgMgDgJgFgACHA3QgLgBgNgCQgIgCAFgEQAFgRgOAMIAAACQgGAAgGgFIgBgBQgUgVgMgaIgBgBQgBgTgFgQIAAgCQADgTAIgHIAAgBQAPgFASAAIAAABQgCAuAYAcQAJAHAKAGIABAAQAYAMAOAMQAAANgNAIIgCABIgPABIgGAAgACcAKIgDgCIgHgEIgHgDIgCgBIgDgCIgFgEQgRgOgFgVIgBgBIgDgKIgBgDIAAgBIgEgPQgDgKgBgLQgBgMAEgMIAAgNIAAgCQAMgfASgaQAjguA5gXIAKgEQAvgQA7AKQBJANAjA1QALARAIAUQADAZgFAfIAAABQgRA1gtAhQgXASghgBQgVgBggACIgggRIgBAAQgDAMgKAIQgOAMgSACIgUACQgTAAgQgGgAC4hcQAAAZAhADQANABAPgDQALgCALgFQAsgRACg9IgBAAQgMgXgYgKIgCAAQgigFgtADIgBABQgHAFgFgCIgBABQgOAKgLAFQADAKAMgHQAZgOAegCQA0gDAWAjIAAACQADAhgYAWIgBAAQgJADgGAEIgCABQgdAJgagIIgBgBQgMgDgCgMIAAgBIgCgBQgDAAgCAHg");
	this.shape_3.setTransform(45.6,-32.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#CC9966").s().p("AmTMZQgKgFgOgEQgNgEgIgGQgUADgZgCIAAgBQAQgnAMgtQACgIAGgGIAsgsIAigTQATgLAUABQALgEAIgGQAMgJAIgPIAHgDIAAgCQADgHgKAAIgCAAQgOgWgYgTQgTgPgPgRQgogtgkgxIgKgQQApgqA8gXQAogQAxgIQAZgFAngBQAKgBAKAGQAYA3ASA/IABAAQAEAkAGAbQAHAjgIAfIABADQAAAGABAFIAEASIAAAHIAAADIgGAUIgBABIgBAAQgLAHgKAVQgGAOgIAMQhFBihrA7QgEACgCAEQgZgGgYgMgAipKeIAIgKIAGgHIAEgIQADgGAEgFQAKgOAHgPIAAgBIAEgLIADgMIABgCIABgCIAHgTIgBgXQAAgEAFAAQgHg2gRhFQgNg0gRg0QAMgHgGgTIAAgBQAXgNAigKIAAgBQAPAAAQgIIAAgCQAyABAsAGQAGAAAHgBIAeA1IABAAQAKAWADAcIAAACQAKAgAFAmQAFAqgBAaIAAAiQgBAmgPAdQgGAMgIALQgOARgXAHQg0ARg2ALQgaAGgcAFQgVADgiACIAKgOgAnUKOQgHgOgDgOQgDgJgGgFQAKgKALgJQAigYA0gIQAngGAXAHIAAACQgHASgUAGQgKgCgLAEIgIADQg5AYgkAsQABgDgCgEgAikBKQg1gCg8gJIgTgCIgLgDQhVgRgng7IAAgDIAAgCQALgHgEgHIgCgBIgCABIADgLIACgEIAHAJIACADQAZAhArAPQAbAKAeAGQAdAGAhACIAwABIAggBQA+gEAogaQAMAEAOACQANABAGAGIAAAAQgVAcgbAWIgBAAIgBAEIgEADIgDACQgBgHgDgGQgmANgxAAIgQAAgAixASQhcAFhMgYIgCgBIgxgaQgEgDADgGQgQgIgJgSQgFgMgEgOQgNgpADg4QAMhAAYg0IABgCQgTg4AUgqQAHgNAMgNQAogrBFgNQAXgEAZAAIAOgBQAygKAegcIAAACQAKAAAHAHIABAAQAhgKAbgYQAFgEgCgKQARgGAOgJQAGgDACgIQgIgPgVgDIABgCQANAEANgBQgJgGgEgIQgIgDgLgCIgBgBQACgFAMAAIACAAQgDgOAIgVIgEgEIgBgCIgIACIgBgDQALgCgDgKIgBgBIAGgHIABAAIAJAGIAIgNIgDgCIAAgBIAAgDQABgEAGgCIAEgCIAAAAIABgBIAAgCIgBgBIgCgDIAAAAIAEgCIABACIAAAAQAWgdAfgVIgDgCIACgGQABAAABAAQAAABABAAQAAAAABAAQABAAAAAAIACgBIACACIAOgHIAOABQAEgEAHgEIAKABIAFgEQAGgEgKABQABgOAOAFIABAAQgMAPAUgBIAAABIgBABIAMAAIAHAAQANgKAFADIgBACQgEADgBACIAoABIANALQASATAAASIADgBIAFgCIAAAAQAHAegFAaIgBACQgFAFgCAHQgBAGADAIIAAABIAHAEQADgHAIgEIAGgCQADgDAFgCQAVgCgBAUIgCAGQAAAKgHAGQgLAGgMgCQgTAAgOgFIgCgBQgFABAGAGIABABQAEAGAJACIAAABQgBAdgPAQIgBABIgWAAIgCAAQgLgDgIgEQgbgOgHgbIAAgCQAOgHgLgJIgBAAIgCAAQgNAEgFAMIgBACQgNAHgIAMIAAABIgBAAQgSAHAPAJIACABIAMgBIAAABIAQASIABAAQgDAEAEAEIABACIALALIAHAJIAAACQAKADAHAGIACABQAGAFAEAHIABABIAAABQgPAPgWADIgCAAQgIABgIgBQghgCgggJQgJgKgLgGIAAADQgEATAaAHIACAAQgOAOACAOQAVgBARAKQAfAGAWAQIABABQAfAXgDAwIALAIIAIAFIAIAIQAUAVAQAZQAHALADAMQADAKgFAHIADALIgOgEQgFABgEgDIgGgCIgcgJIAAAAQgTgCgWACIgBAAQALgegJgkIgBAAQgDAAgCADQgDAEgCAHIgBABQACANgBALIgBABQgHAMAAAMIAAACIgdAMIgWAIQgnAOgQAnIgPAkQgEALgGAIQAAADgDAEQgBAEgDAAQgXAEgWgFIgIgCQgKgEgLgCQgKgDgJgFQgJgGgMgCIgDAAIgSgKIgIgDIgHgCIgJgDIAAAAIgFgBQgGAAgFgCIgLADIgCAAIAAAAQACgVgJgbIABAAQgFgFABgKIABAAIgNgUIAAgCQASgTALgbIAAgCQgGgDgJANIgYAfIAAAGQAHAFADAJIADAJQAKAcACAeQAAAEgDAEQgGAGgGgBIgEABIgGALIAHgHQAFgDAGgCIAKgCQANgBAMACIAKABIAFABIANAGIAbAKIAWAJIANAHIADACIABAAIABAAIANAIIACABQAAAXgLAQIAAABIABATQADAcANARIABABQgsAZgyAFIgGAAQgNAAgKgFgAlUj3IgBABQgSAjgKArQAEATAKALQANAPAMgCIgBgCQgGgLgMgGIAAgBIgJgPIAAgCQABgzAZgcIAAgCQACgFgEAAIgGABgACqqMIACABQARAEAMgJIAGgEQAFgFAGgCIAFgEQADgBABgCQABAEAFgBIABgCQABgMgFgLQgDgOgGgMQgDgIgGgEQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgCgBQgGgCgGACQgFAAgEACQgNAGgGAMQgHAJACALIABAUQABAKgBAKQgBAHAHgBIABgBIAAgCIACACgAC7sHQgQAHgLAMIgEAGQgEAHAJAAIAHgHQAKgKANgFIABAAQAIgBAFAFQAEAEAGABIACgDQACgDgDgDQgKgKgNAAIgGAAgAE3guQAGgNACgQQAJg8gXgzIgBAAQgKgOgJgQQA9gVA5gZQATgJAFgWIAPABIABAFQAJA3AqAdQggAngjAjQgHAIADABIAAABIgCACQgLAOgMAMQglAig2ASIAEgHgACprEIABgBIgCADIAAABIABgDgACsrKIAAgBIACgCIAFgFIAAgBIADgBIAIgFIgCACQgJAFgHAJIgBABIABgCg");
	this.shape_4.setTransform(5.2,-6.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AmSQxQg1gBhBgEIhIgFQgjgDgpACQgQgHgTADIgCAAQgSgGgaABQgbABgYgHQgJADgRgMIgCAAQAJgZgFgZIAAgCQAGgPAIgPIAAgBIABgBQA1glA3glIAAgBQAZgHATgMIAAgBQBCgSAwgkIABgCQgDgHAOgKQAXgPASgUQATgUAOgZIAEgLIACgGQgIAEgJAAQgOAFgUAAIhjABQgWAAgKgDQgaATgXAVIgMANIgDACIi6AAIC6AAIgVATQgaAdgWAgIgMASQgHAJgFALQgQAhgcAWQgJAIgLAGQgfARgcgVQgPgLgBgRIAAgEIAAgPIAAgLIADgKIACgKQABgHAEgDQAGgQAJgOIAAgCQAAgHACgNIAAgCIAGgHIACAAQAFgSAFgOIABgCIAFgJIAAgBQAbgnAXgrIAAgBQApg2AxgsIATgQQAIgGAMgEQAdAIAUAQQAWARAVADQADAMAVgKIAAgCQAwAEAugLIACAAQAFgGAIgDIACAAQADgDACgFIAAgBQAEADAEgFIACAAQALgMAMgLQAXgSAagMQAjgRAzAFQAKABAJgEQhHhFg8hQIgBgEIAAAAQgDgBgBgDIgKgUQgGgLgJgIIgEgFIgKgXQgGgNgBgPQgBgSgDgRIgBgIIAAgtIAAgsIAAgrIAAgTIADgKQAGgVAJgSIACgGIABgCIADgDIAJgIIAEgEIAHgDQAMgOALgQQAJgOACgQIACgBIADgJIADgKIABgBIAAAAQABgSgFgQIgEgLQgFgKgCgLQgEgaABgoQALhDAYgxIABAAQgTgxAUgwIADgGQAghEBRgTQAGgCADABIACABQANgJAXACQAmAEAlgUQAMgHAJgBQASgLABgRIAAgCQgQgKAVADIACAAQAPgTADgUIgBAAQgJgGgHADIgBABQgUAaghAKIgHACQgFABgHgCQgKgIAJgFIABAAIATAHIAAgBQAXgSAQgVIgCAAQgFgFgHAKIgBAAQgQAIgTgCIgBABIgBABQgFANgMgDIAAABQgFgDgKABIgBAAIgagQIgCgBQAGgKAQgCIACAAIg0gnQgsABgIgtQgIguAtgPQAGgVACgWQABgLAFgLQANgXAbgFQAGgRAPgKQAWgPAdAGQgEgVAOgQQAFgGAGgFQARgNAXADQAggoA4AEIAFgFQAQgNAQgHQAzgOAbAlIAFAGQAYgHAYACQAaADAYAOQATALAAAQIAHgBIABAAQAJACgDAEIAAABQgRACABALIABAAQAFAJAIgGIAAABQAUgPAaAAIACAAQgLAOgXAKIABAAQACAOAFADIACAAQAUgQAYADIACAAQAGACgGAFIgCAAIghAMIAAABQANADAHAGIABAAQACgCABgDQAUgDAQATQAGAHgBAGQgJAEgMgNIgHgHQgJATgDAOIABAAQAGAFAFAAIACABQADgKAHgHIABAAQAaACAEAYIALACIABAAQAQALACAQIgBAAQgLAEgFgNIgBAAQgJARgRABIgBAAQgFgJgGADIAAABQgMAOgSAHIgEgBQgEgIgIADIgBACIgMALIAAABQALAlgIArQALgFALgCIACgBQAKAFAIAHIABABQACAJgDAMIABAAQgKAegdABIgEAAIgCAAQgEAvgdANIgCABIgEAHQgLATgPAQIgBACQgHAHgGAKIgDAEQgMAJgSACIgCABQgkAFgXgHQgHAGgEAJIAAACQAIADAHACQAIABAIgBIACAAQAPAIALACIACAAIALAHIAAAAQAlAZADA0IAAACQAjAZAYAjIAEAJIAAACIADARIABAGIAAABIABAKQABALAFAJIgBAEIgBACIAAAAIACACQAHADAEAFIACACIAAABIABAAIADgBQAHABAIgEIADgEIAXgJIAIgCQAagFAWgNIAEgBIACgBQAVgNAYgSIABAAQgFAWgTAJQg5AZg9AVQAJAQAKAOIABAAQAXAzgJA8QgCAQgGANIgEAHQA2gSAlgiQAMgMALgOIACgCIAAgBQgDgBAHgIQAjgjAggnQgqgdgJg3IgBgFIABgKQAAgIgHgFQAGgTAOgKIAGgDIAAgBQAJgBAGgDIACAAQADgHAGgEIACAAQAAgRACgOQAEgcAOgVIAAgBQAjgrAuggIAJgFQAKgFALgCIAJgCQAVgLAogBQAnAAAYAFQBBAOAkAxQAHAJAGALQAUAkgNAxIgCAHQgSA8gsAjQgPALgVADQggAGgYABQgaABgTgKIgLgHQgaAigwgBIgBAAQgCANgGAKQgGAJgKAFIAAACIgbgDIgggEIAAgBQguA/g4A0QgTARgUARQgdAXgqAJIgJAKQgLALgNAJIgBABQg4AUg2gSIgCAAQgRgHgPgJIgBAAQgkAQgtgEIgNgBIgCAAQgYA0grAVIgBAAIAAgBIgHAEIAAABIgBACIBJBYIABAAQASAkAVAiIACAAQAJAaAQAcQAWAoAHA5QAGA3ACAkQABAfgFAoQgDAUgGAPQgWA6hGAMQhAALg9AOQgpAKgkgFQg7BIhQAzIgUANIgOAJQgGAFgIADQgFAEABACIABACQghAUgdAZIgBABQgLgIgPANQgZAWgeARQgKAGgDAMQAPAZAgAJQAXAGAcADIBNAJQARABAPAEQASAGAQAJQAHAlgDAeIAAACIgFALIAAABIgpAcIgCAAQg3gEg7gBgAsYQGQAEADAGABIgLgFIABABgAkWO6IoTAAgAnCLYIgBAAIgQAXIgFAIQgDAZgXAOIgpAaQgrAbgxATIABABQAVATAgAJIACAAIBNAEIAAgCQgCgMAIgMQAFgGAIgEQAbgRAbgTIAWgRQgCgBgDgEQgCgDADgDIAbgeQABAAAAAAQAAgBABAAQAAgBABAAQABAAAAAAQAQgGAEgOIAAgBQACgFAEAAQAFADACADQADAGgFAJQgGAKgKAGQgMAHgJAJQAJgFAIABIALgJIAMgJQARgKAAgJIABAAIgBAAIgHgGQgXgOgZgHQgXgFgZABQADAGgBAJIgDAKIAAACIgLAoQgCAIgEABQgDACgGgGQgBgCAAgDIAKgqIACgLQACgGgCgHIgGABgAl5LPQAOAEAKAFQAYAMAZAGQACgEAEgCQBrg7BFhiQAIgMAGgOQAKgVALgHIABAAIAAgBIAHgUIAAgDIAAgHIgEgSQgBgFAAgGIgBgDQAIgfgHgjQgGgbgEgkIgBAAQgSg/gYg3QgKgGgKABQgnABgZAFQgxAIgoAQQg8AXgpAqIAKAQQAkAxAoAtQAPARATAPQAYATAOAWIACAAQAKAAgDAHIAAACIgHADQgIAPgMAJQgIAGgLAEQgUgBgTALIgiATIgsAsQgGAGgCAIQgMAtgQAnIAAABQAZACAUgDQAIAGANAEgApeKtIABAAQAZACATgGIAAgDQAXgGAXADIAIABIAeABIAAgBIABAAIABABIAQACIAIACIADgBQAEgOACgQQACgOAGgMQgXAQgYAPIgGADQgJAEgKACQgKACgKAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAgBQgCgMAPgDIALgDQAcgIAXgTQAIgHAIgIIAEgDIADAAIAAAAIgHgNIgCADQgCAFgFACIgKAHQgKARgUAHIgFADQgGAEgGAAQgFAAgFgFQgDgCACgDQAFgHAJgCIAHgCQAIgFAHgFIAQgOIALgKQAAgDABgCQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABgBIACAAIgDgLIgIAGIgPAMQgxAOg4gBIgCAAQgTAXgIAiIgBABQABADgCAJIgBAAQAEANgBALgAg+HWIABAXIgHATIgBACIgBACIgDAMIgEALIAAABQgHAPgKAOQgEAFgDAGIgEAIIgGAHIgIAKIgKAOQAigCAVgDQAcgFAagGQA0gLA2gRQAXgHAOgRQAIgLAGgMQAPgdABgmIAAgiQABgagFgqQgFgmgKggIAAgCQgDgcgKgWIgBAAIgeg1QgHABgGAAQgugGgwgBIAAACQgQAIgPAAIAAABQgiAKgXANIAAABQAGATgMAHQARA0ANA0QARBFAHA2IgBAAQgEAAAAAEgAmoJcIAAABIABgBIgBAAgAlKHwQg0AIgiAYQgLAJgKAKQAGAFADAJQADAOAHAOQACAEgBADQAkgsA5gYIAIgDQALgEAKACQAUgGAHgSIAAgCQgNgDgSAAQgOAAgRACgAl2hmQAEAHgLAHIAAACIgBADQAoA9BVARIALADIATACQA8AHA1ACQA7ACAsgNQADAEABAHIADgCIAEgDIAAgEIAAAAQAbgUAVgcIAAAAQgGgGgNgBQgOgCgMgEQgmAag+AEIggABIgwgBQghgCgegGQgdgGgbgKQgrgRgZghIgCgDIgHgJIgCAEIgDALIACgBIACABgAhigoQAygFAsgbIgBgBQgNgRgDgcIgBgTIAAgBQALgQAAgXIgCgBIgNgIIgBAAIgBAAIgDgCIgNgHIgWgJIgbgKIgNgGIgFgBIgKgBQgMgCgNABIgKACQgGACgFADIgHAHIAGgLIAEgBQAGABAGgGQADgEAAgEQgCgegKgcIgDgJQgDgJgHgFIAAgGIAYgfQAJgNAGADIAAACQgLAbgSATIAAACIANAUIgBAAQgBAKAFAFIgBAAQAJAbgCAVIAAAAIACAAIALgDQAFACAGAAIAFABIAAAAIAJADIAHACIAIADIASAKIADAAQAMACAJAGQAJAFAKADQALACAKAEIAHACQAVAFAXgEQADAAADgEQADgEAAgDQAGgIAEgLIAPgkQAQgnAngOIAWgIIAdgMIAAgCQAAgMAHgMIABgBQABgLgCgNIABgBQACgHADgEQACgDADAAIABAAQAJAkgLAeIABAAQAWgBATABIAAAAIAcAJIAGACQAEADAFgBIAOAEIgDgLQAFgHgDgKQgDgMgHgLQgQgZgUgVIgIgIIgIgFIgLgIQADgwgfgXIgBgBQgWgQgfgGQgRgKgVABQgCgOAOgOIgCAAQgagHAEgTIAAgDQALAGAJAKQAgAJAhACQAIABAIgBIACAAQAWgDAPgPIAAgBIgBgBQgEgHgGgFIgCgBQgHgGgKgDIAAgCIgHgJIgLgLIgBgCQgEgEADgEIgBAAIgQgSIAAgBIgMABIgCgBQgPgJASgHIABAAIAAgBQAIgMANgHIABgCQAFgMANgEIACAAIABAAQALAJgOAHIAAACQAHAbAbAOQAIAEALADIACAAIAWAAIABgBQAPgQABgdIAAgBQgJgCgEgGIgBgBQgGgGAFgBIACABQAOAFATAAQAMACALgGQAHgGAAgKIACgGQABgUgVACQgFACgDADIgGACQgIAEgDAHIgHgEIAAgBQgDgIABgGQABgHAGgFIABgCQAFgagHgeIAAAAIgFACIgDABQAAgSgSgTIgNgLIgogBQABgCAEgDIABgCQgFgDgNAKIgHAAIgMAAIABgBIAAgBQgUABAMgPIgBAAQgOgFgBAOQAKgBgGAEIgFAEIgKgBQgHAEgFAEIgNgBIgOAHIgCgCIgCABQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAgBAAIgCAGIADACQgfAVgWAdIAAAAIgCgCIgFACIAAAAIACADIAAABIABACIgBABIAAAAIgEACQgGACgBAEIAAADIAAABIADACIgIANIgJgGIgBAAIgGAHIABABQADAKgLACIABADIAIgCIABACIAEAEQgIAVADAOIgCAAQgMAAgCAFIABABQALACAHADQAFAIAJAGQgNABgNgEIgBACQAVADAIAPQgCAIgGADQgOAJgPAGQACAKgFAEQgbAYghAKIgBAAQgHgHgKAAIAAgCQgeAcgyAKIgOABQgZAAgXAEQhFANgoArQgMANgHANQgUAqATA4IgBACQgYA0gMBAQgDA4AMApQAFAOAFAMQAJASAQAIQgDAGAEADIAxAaIACABQBMAaBcgFQANAGAQgBgADZg/IABABQAJAFAMADIAAgBIAHAAQAPABAQgBQASgCAOgIQAQgJANgQQAFgGADgHIAAgBQAFgEADgHQAKgqgFgjQgJg4ghgfQgXgUghgJQgigIgeABQgVACgTAGQgQAFgPAIQgbAPgMAdIgWAwIgBACIgCAEIAAAAIgBADIgDAEQgDAHgCAIIAAAEIAAACQgCAFgDAGQAHAuAfAYQAMAKgIAFIgFgDQgcgRgQgjQgGgPAFgOQAHgTgJgCQgFgBgCACIgCABIAAAAIgGAAIgCABIgFACQAAgBAAAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgPAUgGAgIABACQAGAVAKAQIACgBIABAAQACADADABIAIAEQAEAGAHADQAIAEANgEIAAgBIABAAIASAAQABAAAAAAQABAAAAAAQABgBAAAAQAAgBABAAIABgFIADABIACABIADAAQAXAFAYgCIAAgCQAQgFAMgKIAAABIAhATIAFACIACAAIAHAAIAGAAgAIykXQgFAEAIACQANACALABQALAAAKgBIACgBQANgIAAgNQgOgMgYgMIgBAAQgKgGgJgJQgYgcACguIAAgBQgSAAgPAFIAAABQgIAHgDATIAAACQAFAQABATIABABQAMAcAUAVIABABQAGAFAGAAIAAgCQAGgFACAAQAEAAgDAKgAKrpMIgKAEQg5AXgjAuQgSAagMAfIAAACIAAANQgEAMABAMQABALADAKIAEAPIAAABIABADIADAKIABABQAFAVARAOIAFAEIADAEIACABIAHADIAHAEIADACQAZAJAegFQASgCAOgNQAKgJADgMIABAAIAgARQAggCAVABQAhABAXgSQAtghARg1IAAgBQAFgfgDgZQgIgUgLgRQgjg1hJgNQgXgDgVAAQghAAgdAJgAC6qiIgCACIgFAEIgCACIAAACIAAAAQgDAIAFAJIAFAHIANANIAHAHIAGAEQAIAIAJAGIAFADIABgBIAbgZIgBgBIgNgEQgJgDgIgFQgHgMgMgIIgBgBQgEgKgIgDQgEgCgEAAIgDAAgAm4MeQgBgDADgDQATgTAVgRIAFgFIAFgGIABgJQAAAAABgBQAAAAAAgBQABAAAAAAQABgBAAAAIAEgBIAAAAQALAFgFANIgBABQgDAIgGAFIgoAmQgFAFgEAAQgEAAgDgJgAkxjLQgKgLgEgTQAKgrASgjIABgBQALgDgDAHIAAACQgZAcgBAzIAAACIAJAPIAAABQAMAGAGALIABACIgDAAQgKAAgMgNgAKdjvIABgIIABAAIABAIIgDAAgAKfmHQghgDAAgZQADgJAEADIAAABQACAMAMADIABABQAaAIAdgJIACgBQAGgEAJgDIABAAQAYgWgDghIAAgCQgWgjg0ADQgeACgZAOQgMAHgDgKQALgFAOgKIABgBQAFACAHgFIABgBQAtgDAiAFIACAAQAYAKAMAXIABAAQgCA9gsARQgLAFgLACQgLACgKAAIgHAAgADTrSQABgKgBgKIgBgUQgCgLAHgJQAGgMANgGQAEgCAFAAQAGgCAGACIACABQABAAABAAQAAAAABAAQAAABABAAQAAAAABABQAGAEADAIQAGAMADAOQAFALgBAMIgBACQgFABgBgEQgBACgDABIgBAAQgNAEgIgJQgHgHAEgKQACgHAGgDIAPABIAEACQgCgHgDgIIgCgEQgIgOgQACIgEACIgIAFIgDABIAAABIgFAFIgCACIAAABIgBACIgCADIAAABIgBADQgDAKgBAKQAAALADAKQgCAGADAEIAAACIgBABIgCAAQgFAAABgGgADOsvIAEgGQALgMAQgHQARgCAMAMQADADgCADIgCADQgGgBgEgEQgFgFgIABIgBAAQgNAFgKAKIgHAHQgJAAAEgHg");
	this.shape_5.setTransform(0.2,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-93.3,-107.9,186.6,215.8);


(lib.hepronounstill = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#9933CC").s().p("Ag9BtQgOgNAAgtIAAgUIACgXIgCgHQABgDACgEQADgpAAgTIgCgQIgBgPQAAgRAOAAQAGAAAEAEQARgEAQgDQAPgCALAAQAiAAAVAIQAKAEAAAKQAAAFgFAFQgDAFgHAAIgEgBQgYgHgWAAQgLAAgMACQgOACgQAFIABAPIgCA2IA8gGIAhgDQAGAAAFAEQAEAEAAAGQAAALgNACIghADIhAAGIgBATIgBARQABAfAEAFQADAEATAAIAZAAIAagBIAJAAIAIgBQAPAAAAAOQAAAMgMADQgNACgqAAQgsAAgNgLg");
	this.shape.setTransform(11.7,1.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#9933CC").s().p("AhXBvQgEgEgBgGQAAgOADgfQACgdAAgQIAAgVIAAgYIABghIABghQAAgHAEgDQAEgFAGAAQAFAAAFAFQADADAAAHIgBAhIgBAiIAAAiIA8gJQAkgIAZAAQABgUAAgpQAAgKADgLQAFgPAJgBQAFAAAEAFQAEADAAAGIgBAGQgCAGAAALIABANIAAAMQgBAPgCAcQgCAagBAOIACAgIACAhQAAAFgEAFQgEADgGAAQgGAAgEgDQgDgFAAgFIgCghIgCggIABgVQgYAAgiAHIg7AMQAAANgCAXQgDAYgBAMQAAAGgDAEQgEAFgGAAQgGAAgDgFg");
	this.shape_1.setTransform(-8.7,1.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22.2,-22.2,44.5,44.4);


(lib.general_buttoncolor = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{resetRed:1});

	// timeline functions:
	this.frame_0 = function() {
		this.play();
	}
	this.frame_8 = function() {
		this.gotoAndPlay("resetRed");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(8).call(this.frame_8).wait(2));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#D5FFD7","#61EF01","#1DA400","#004A00"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgvAAgjgjQgjgjAAgwQAAgvAjgjQAjgjAvAAQAwAAAjAjQAjAjAAAvQAAAwgjAjQgjAjgwAAIAAAAg");
	this.shape.setTransform(11.9,11.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FFFFFF","#EC0000","#9D0000","#480000"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgvAAgjgjQgjgjAAgwQAAgvAjgjQAjgjAvAAQAwAAAjAjQAjAjAAAvQAAAwgjAjQgjAjgwAAIAAAAg");
	this.shape_1.setTransform(11.9,11.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},8).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,23.7,23.6);


(lib.Copyright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAbAHIgDgKIgEAKQgEAIgDAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBgBAAgBIgCgIIgBgHQgGASgCAAIgDgBIgBgCIABgCQADgFABgFIACgNQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAEAAACAJIADAKIACgGIADgJQADgEACAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAEAKIACAGIACAIIABACIgBACIgCABQgDAAgDgJgAgTANIgBgIIAAgGIgBgHIgFAAIgGAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAgBAAAAQAAgBAAgBQAAAAABgBQAAAAABgBQAAAAABAAIAFABIAEAAIAPAAIADgBIAEAAQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAABAAAAQAAAAAAABQAAAAgBAAIgOAAIAAAIIABAFIABAEIABAEIgCACIgCABQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAgBAAAAg");
	this.shape.setTransform(57.3,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgLAYQgGgDgBgEIABgDQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAIAEACIAEABIAFABIAFgBQADgBAAgDQABgGgJgCIgCgBIgIgDQgEAAAAgFQAAgKAIgEIAHgCIAIgDIAEgBIADABIABAEIABADIAAAEIgBADIgCABQgBAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIgCgFIgJADQgFADgBAEIADABQAIACAFACQAHADAAAJQAAAHgGAEQgFADgGAAQgFAAgGgCg");
	this.shape_1.setTransform(51,2.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgLATQgHgGABgKQAAgGAFgKQAHgKAGAAQAEAAAGACQAGACABAEIgBADQgBAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgDgBIgBgBQgDgCgGAAQgCAAgFAIQgDAHAAADQAAAGADAEQAEADAEAAIAGgCIAEgCIACgBIAEABIABADQgBADgGADQgGADgEAAQgHAAgGgFg");
	this.shape_2.setTransform(46.6,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgDAfQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAAAIAAgJIAAgIIAAgKIAAgIQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBIACgBIACABQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABIAAAIIgBAKIAAAIIABAJQAAAAAAAAQAAABgBAAQAAABAAAAQAAAAgBAAIgBABIgDgBgAgBgXQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQAAAAAAAAQAAAAAAgBQABABAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBAAAAgBg");
	this.shape_3.setTransform(43.1,1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAKAVIgBgJIgBgKIABgDIAAgDQAAgKgEAAQgFAAgCAFQgEAGgCAGIgBAEIAAAFIAAADIAAAFIgBADIgDABIgDgBIgBgDIAAgFIgBgDIABgMIAAgLIAAgFIAAgEIABgDIAEgBQAEAAAAAFIAAAGQAHgKAGAAQAHAAADAGQACAEAAAJIAAAEIAAACIABAKIABAJIgBADIgDABQgEAAgBgEg");
	this.shape_4.setTransform(39.5,2.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_5.setTransform(34.8,2.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AALAhIgBgLIgBgKIAAgDIAAgEQAAgGgEAAQgFAAgDADIgGAKQAAARgCACQAAABgBABQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDIABgBIAAgHIAAgHIAAgeIABgHIgBgFIAAgEQAAAAAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQAEAAAAAEIABAIIAAAKIAAAJIAAAEQADgFAEgCQACgDAFAAQAHAAADAFQABADABAGIABAJIAAAIIACAKIAAABQAAABAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIgDABQgEAAgBgDg");
	this.shape_6.setTransform(30,1.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgLATQgHgGABgKQAAgGAFgKQAHgKAGAAQAEAAAGACQAGACABAEIgBADQgBAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgDgBIgBgBQgDgCgGAAQgCAAgFAIQgDAHAAADQAAAGADAEQAEADAEAAIAGgCIAEgCIACgBIAEABIABADQgBADgGADQgGADgEAAQgHAAgGgFg");
	this.shape_7.setTransform(25,2.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgOATQgGgGAAgKQAAgKAFgHQAGgJAJAAQAGABAFACQAGADAAAHQAAAEgFADIgKAEIgOAHQACAEAEABQAEADACAAIAIgBQAFgCABgDQABAAAAAAQAAgBABAAQAAAAABAAQAAAAAAAAIADAAIABADQAAAFgIADQgGADgHABQgIgBgGgEgAgIgKQgDAEgCAGIANgFQAGgDAEgDQgEgDgGgBQgEAAgEAFg");
	this.shape_8.setTransform(20.3,2.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAaAgIgCgGIgBgIQgCgHgEgWIgJAYIgDAJIgDAIQgBAEgCAAQgDgBgBgDIgCgEIgBgFIgIgfIgCAHIgFAWIgCAMQgBAEgDAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgEQAAgHADgLIAFgPIADgOQACgKABgDQACgCADAAQACAAACADQACAEABAMQADAOAFAPQAFgPAEgSIACgGIACgHQABgDADAAQAEAAACAIIACAKQADASADAOIACAHIACAHQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgCABQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBgBg");
	this.shape_9.setTransform(13.8,1.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgQAUIAAgdIAAgEIABgFQAAgEADAAQAFAAAAAHQAHgIAKAAQADAAACADQACACAAAGIAAADQgBAFgEAAQgEAAAAgEIAAgDIAAgEQgHABgCADQgEADgDAGIABAWQAAAEgFAAQgEAAAAgEg");
	this.shape_10.setTransform(5.1,2.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_11.setTransform(0.5,2.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgBAZQAAAAgBAAQAAgBAAAAQAAAAAAgBQgBAAAAgBIgBgPIgBgOQAAgFgBgCQgDABgDADIgFAGIgDADIAAAGIgBAHIABAEIAAADQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABQgFAAAAgLIAAgIIABgGIgBgHIAAgHQAAgKAFAAIACACQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAADIgBACIAAAFQADgFAEgDQAFgEADAAQAGAAACAHQACgEADgBQAEgCAEAAQAHAAADAIIACAMIADAYIgBADIgDABQgEAAgBgEIgBgOIgCgLIgBgGQgCgEgCAAIgFADIgGAEIAAAHIABALIABALIgBADIgDACQAAAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBg");
	this.shape_12.setTransform(-5.2,2.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgBAZQAAAAgBAAQAAgBAAAAQAAAAAAgBQgBAAAAgBIgBgPIgBgOQABgFgCgCQgDABgDADIgFAGIgCADIgBAGIgBAHIABAEIABADQAAABgBAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABQgFAAAAgLIABgIIAAgGIAAgHIgBgHQAAgKAEAAIADACQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAADIgBACIAAAFQADgFAEgDQAFgEADAAQAGAAABAHQADgEADgBQADgCAFAAQAHAAADAIIACAMIADAYIgCADIgCABQgEAAgBgEIgCgOIgBgLIgBgGQgCgEgCAAIgFADIgGAEIAAAHIABALIABALIgBADIgDACQAAAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBg");
	this.shape_13.setTransform(-12.2,2.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_14.setTransform(-18.1,2.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgQAUIAAgdIAAgEIABgFQAAgEADAAQAFAAAAAHQAHgIAKAAQADAAACADQACACAAAGIAAADQgBAFgEAAQgEAAAAgEIAAgDIAAgEQgHABgCADQgEADgDAGIABAWQAAAEgFAAQgEAAAAgEg");
	this.shape_15.setTransform(-22.4,2.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgVAeQgFgGgBgMQABgMAFgKQAFgMAIgIQAHgEAEAAQAEAAAGACQAIAEAAADIgBADIgEABIgCgBQgHgDgEAAQgDgBgCAEIgGAGQgKAOAAAOQABAIACADQACAEAIAAQAGgBAGgFQAGgEACgLQgMABgGAEIgDABQAAgBAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQAIgEAXAAIADABIABACQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQgDANgIAJQgJAHgKABQgKgBgGgFg");
	this.shape_16.setTransform(-27.7,1.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgNAhIgBgDIACgJIAKgWQAFgOAHgIIABgBIgVAAIgJgBQgFAAAAgEQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAQAAIAPABIAIAAQAFAAAAACQAAADgDADIgEAFQgGAGgFAKIgHAPIgCAKIgEAKQgBABAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIgDgBg");
	this.shape_17.setTransform(-36.2,1.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AABAiIgHAAIgFgBQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQgBgEAIAAIACAAIABAAIAAgHIgBgGIABgPIABgRQgFAFgCAAIgDgBIgBgDQAAgDADgCIAHgGQACgEAEAAQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAADIAAADIAAAEIAAAEIgBAPIgBANIAAAGIABAGIAFAAQAAAAAAAAQABAAAAABQABAAAAAAQAAAAABABIAAADIAAADIgDABg");
	this.shape_18.setTransform(-41,1.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgSAXQgFgKAAgNQAAgMAGgKQAHgMAKAAQAMABAGAJQAGAJAAANQAAARgGAKQgGAJgMAAQgMABgGgMgAgLgRQgEAIAAAJQAAAMAEAHQAEAHAHAAQAIABAEgLQADgIAAgJQAAgMgDgGQgEgGgIAAQgGAAgFAIg");
	this.shape_19.setTransform(-45.9,1.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AANAhIgDgBIgHAAIgFABIgFAAIgFAAIgBAAIgCAAQgDAAgBgDIAAgFQAAgKAGgHQACgDALgFIAHgHQADgEAAgGQAAgDgDgCQgDgCgDAAQgDAAgDADIgGAEIgDACQgFAAAAgEQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAFgFAEgCQAFgDAEAAQAHAAAFAEQAGAEAAAHIgBAIIgEAHQgDACgIAFQgGAFgDADQgFAFABAHIAJgBIALAAIAGABQAEABAAADQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAIgDABIgDAAg");
	this.shape_20.setTransform(-51.3,1.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgeAAQAAgKALgJQALgKALAAQAOAAAHAIQAHAIAAAMQAAAJgJAKQgKALgMAAIAAABQgeAAAAgegAgOgOQgIAGAAAIQAAAMAGAFQAGAEAKAAQAJAAAIgIQAGgIAAgGQAAgJgEgFQgFgGgIAAIgCAAQgKAAgIAHgAgKAJQgGgEAAgFQAAgGAIgFQAGgFAFAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAIgCgBIgBAAQgDAAgEADQgEACAAADQAAABADACIAFABQABAAAEgCIAEgCIADAAIABADQAAADgEADQgGADgDAAQgFAAgFgDg");
	this.shape_21.setTransform(-57.7,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.3,-7.1,126.6,16.6);


(lib.proword = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.prowordstill();
	this.instance.setTransform(0.4,-1.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-16.9,-19.2,34.6,31.9);


(lib.proboxingmove = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.proboxstill();
	this.instance.setTransform(-23,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:5,y:-21},4).to({x:-2,y:-10},5).to({x:23.4,y:-9.4},5).to({x:0,y:0},10).to({x:-23},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-116.3,-107.9,186.6,215.8);


(lib.proboxingjump = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.proboxingmove();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-30},4).to({y:0},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-116.3,-107.9,186.6,215.8);


(lib.proboxing = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.proboxingstill();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-116.7,-22.2,292.2,44.4);


(lib.hepronoun = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.hepronounstill();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22.2,-22.2,44.5,44.4);


(lib.goNext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,11.3).s().p("AhLAqQghgSACgYQgCgXAhgRQAggTArAAQAsAAAgATQAfARAAAXQAAAYgfASQggASgsAAQgrAAgggSg");
	this.shape.setTransform(22.8,8.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.502)").s().p("AhThcICoBdIioBcg");
	this.shape_1.setTransform(25.1,20.4);

	this.blinker = new lib.general_buttoncolor();
	this.blinker.setTransform(23.4,20.1,1.5,1.5,0,0,0,11.9,11.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,14.8).s().p("AhiA3QgrgXACggQgCgfArgWQApgYA5AAQA5AAAqAYQAqAWAAAfQAAAggqAXQgqAXg5AAQg5AAgpgXg");
	this.shape_2.setTransform(23.4,8.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("rgba(0,0,0,0.502)").ss(1,1,1,3,true).p("AAACxQhIAAg0g0Qg0g1AAhIQAAhHA0g1QA0g0BIAAQBJAAA0A0QA0A1AABHQAABIg0A1Qg0A0hJAAg");
	this.shape_3.setTransform(23.3,20.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["rgba(103,103,103,0.839)","rgba(134,134,134,0)"],[0.678,0.918],-0.8,0,0,-0.8,0,24.9).s().p("AisCkQhFhEAAhgQAAhgBFhDQBEhFBhAAQBfAABBAwQBCAwAVCqQAVCskMAbQhhAAhEhFgAgHCQQBEAAAzgwIABAAIADgEQA0g0AAhHQAAhJg0g0IgFgFIgBgBQgyguhDAAIAAAAIgBAAIAAAAIgBAAQhEAAgyAuIgBABIgCACIgBABIAAAAIgCACQg0A0AABJQAABHA0A0IACACIABABQAzAxBHAAIAAAAIAAAAIAAAAIAAAAQhHAAgzgxIgBgBIgCgCQg0g0AAhHQAAhJA0g0IACgCIAAAAIABgBIACgCIABgBQAyguBEAAIABAAIAAAAIABAAIAAAAQBDAAAyAuIABABIAFAFQA0A0AABJQAABHg0A0IgDAEIgBAAQgzAwhEAAIAAAAIgBAAIABAAIAAAAg");
	this.shape_4.setTransform(24.2,23.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},2).wait(1));

	// Layer 2
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#33FFFF").s().p("AioCqQhGhHAAhjQAAhiBGhGQBGhHBiAAQBjAABGBHQBHBGgBBiQABBjhHBHQhGBGhjAAQhiAAhGhGg");
	this.shape_5.setTransform(24.4,21.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0099FF").s().p("AioCqQhGhHAAhjQAAhiBGhGQBGhHBiAAQBjAABGBHQBHBGgBBiQABBjhHBHQhGBGhjAAQhiAAhGhGg");
	this.shape_6.setTransform(24.4,21.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.5,46.7);


(lib.Pronounboxing2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// pro
	this.instance = new lib.proboxingjump();
	this.instance.setTransform(-67.9,19.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// mirror lines
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AhFQVIAOgVIAAgBQAJgCAEgPIAAgCQAJgBAIgHIAAABIAAgBQALgVAQgNIACAAQAMgUAPgQIAAgBQAIADAFgOIACgCIARgWIAAgCQAEADADgGIABgBQAFgNAJgBIACAAQAKgRAOgLIACAAQAIgVAPgPIABgBIARgLIABAAIAQgdQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAAAQAKgHAJgEIACAAQgDALgMANIifCtQgsAzgvAvgAkfLWQAJgQAPgNIACgBQAGgPARgNIAAgBQADgGAGgIIABgBQAPgIAPgUIAGgJQAJgQAOgCQASgdAageQAKgMAOABQAAAIgNANQhSBXhLBVQgEAFgHADIgDABQAAAAgBAAQAAAAAAAAQgBgBAAgBQAAAAAAgBgAlnLUIALgHIACAAQAMgUAKgKIAAgCIAMgKIABgBQBKhbBVhSIAGgHQAVgVAWgUQAMgNAQgRQAQgPAOgQQAIgIAPgKIACAAQADAKgPANQgsAngpApIgiAkIgBAAQhABDg9BFQgkAqgqAlIgBAAQgCAAgBgEgAExH3IAAgEQASgmAkgVIABAAQgdAdgYAiIgCABIAAgBgAkEF9IABgCQADACAFgFIABgBQBRhUBVhRICnijQAIgGAHgFQAJgBAGgDIABAEIgBAAIhRBLIhZBVQhUBShTBTQgnAngpAlQgHAGgKABQAdgaAgglgAjsGnIAAgBQAJgEACgCIABgCQAHgPALgDIACAAQAGgNALgGIAAACIABAAQAggvAogeIACAAQAmgtArgoIACAAQgDgEAHgCIAAgBQAngmAmgnIAAABIABgBQAngoAogoIACAAQAFACAFAAIihChIinClIg0A1QgJAAAJgLgAlLnPIAfgYQBOg9BGhFIBHhGQANgNATABQgOAVgYAUIiwCcQgXAUgZARQgGAFgGAAQgEAAgEgDgAlInvIAAgDICbiRIAAgBQAdgVAfgcQAdgbAVgbQAAgBAAAAQABgBAAgBQAAAAgBAAQAAgBgBAAQALgNANgKIACgBQALgDAHADIACAAIgBABQgkAmgmAlQguAsgxAqQg2Awg0AyQgJAIgIAGQgIAFgJADgAkfqlQArgxA1gnIACgBQAOgUAYgVQAtglArgpQAqgpAhgxQADgFAEgBQAEgBAFACQAEANgPAMQgMAJgIALQhQBWhXBOIg7AxIg5AugABvtlQAMgNAMAEIACAAQBYhLBKhPIAAgBQAHgDAKgIQAAgBABAAQAAAAABgBQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQABAAAAAAQABABAAABQAIACgPANQhTBThbBLIgIAFQgFACgDAAIgBAAQgHAAgHgHg");
	this.shape.setTransform(62.4,-21.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AJaTtIAAAXgAJCT/IgngGIAAAAIgbgFIAAAAQjfgjjfgnIAAAAQj9gtj8g1IAAAAQhRgRhQgTIAAAAQATgNAFgjIAAAAQAGgigFghIAAAAIgBgOIAAAAQACgqgFgrIAAAAIgBgGIAAAAQACgeAEgeIAAAAQAbipAGiqIAAAAQAChRgKhQIAAAAQgLhUgGhVIAAAAQgLioAeioIAAAAQAThsgfhnIAAAAQgGgVAAgWIAAAAQABgVgEgRIAAAAQABiKgNiGIAAAAQgEgsgTghIAAAAIAAgCIAAACIAAgCQAJgiAGgjIAAAAQAKg6gQgoIAAAAQASgJAagEIAAAAIAIgBIAAAAQALgEANgDIAAAAQCvgmCwggIAAAAQD2guDyhAIAAAAQBTgWBOgZIAAAAQA0gBAiATIAAAAQgLAcABAeIAAAAQADCMABCLIAAAAQAGAbAEAbIAAAAQADAWAAAWIAAAAIgBAPIAAAAQgCAaABAaIAAAAIACAhIAAAAQAGAGgCAKIAAAAIAAAPIAAAAIAAA8IAAAAIAAA8IAAAAIAAA8IAAAAIAAA8IAAAAIAAApIAAAAQAEAFgBAJIAAAAIgBANIAAAAIABAkIAAAAQAHAYgGAhIAAAAQgFAcAHAbIAAAAQAPA+gRA3IAAAAQAWCDgJCLIAAAAQgCAagLAOIAAAAQAWAYgFAyIAAAAQgEAqAAAsIAAAAIAAFVIAAAAQAACqADCqIAAAAQABAtgCAtIAAAAIADAIIAAAAIABAGIAAAAQADAPgCAPIAAAAQgCAIABAJIAAAAIAAARIAAAAQACAHAAAHIAAAAIgCAFIAAAAIgCAwIAAAAIAAAAIAAAAIACABIAAAAIAAAXIgYgFg");
	mask.setTransform(62.1,-6.2);

	// pro reflection
	this.instance_1 = new lib.proboxingjump();
	this.instance_1.setTransform(132.5,18.5,1,1,0,0,180);

	this.instance_1.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// background
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(5,1,1).p("AkjA+IB5gaIKWiLIBJgQIALgCIBPgRAkqA/IkhA+IgBAAIAAAAIhCAO");
	this.shape_1.setTransform(60.9,-124.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(3,1,1).p("AbHAeIAAg7Mg2NAAA");
	this.shape_2.setTransform(-10.2,-147.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1.5,1,1).p("ACqmWIgGiAIAAgIIgCg1IgIlCIgBgLIADg9ADAKSIgGACIgiAAIAYAGAVLOLIF7BTA2QHJIAkgBIC5AAIDPAAIDVAAIACAAIATAAIADgCA15HJIgXAAArBHSIg1gPIgLgDA66KUIgLAAA6lHJIEVAAACYKUItZjC");
	this.shape_3.setTransform(-11.4,32.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(3,1,1).p("A7G4EMAAAAjvIAADLIAAJPMA2NAAAIAAiDIAAiCMAAAgrH");
	this.shape_4.setTransform(-10.2,3.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#0066FD","#CCCCCC","#FFFFFF","#FFFFFF","#FFFFFF","#996600","#FFCC00"],[0,0.184,0.788,0.937,1,1,1],61.8,-6.7,61.8,-6.7).s().p("AJHUCQgqgGgfgGIhkgWIiAgaQiHgbh9gbQiEgdiJgZIAAgBQgHgBgCgEQg7gIg9gMQg8gNg6gQQgIABgMgBQgPgCACgJIAAgBIgMADIAAAAIgGADIgiAAIAlgHIABAAIAAgBIAIgOIABgyIgBgwQgDg5AAgsIgCh+IgEhqIgDhDIgChGIgDhEQgDhMAChCQgIgrAAgmIAAhbQgBgfgEgdIADgjQABgWAAgaQgBgtgEghIgBgJIgBAAIAAAAIgCg1IgIlCQACABAEgCIABAAQACgFAAgFQAAgJgHgKIAAgqIgBggQgCglADghQgFgZgBgZIgCgyIgFhhIgFiDQgBgMgCgDIAAAAIgCgOIAAAAIABAAIEhg+IACAAIAFgBIB5gZIAKgDIBegSIBagSICoghIB+gYIAIgBIABAAQBDgNA8gRIAAABIAXgBIAAgBQAUgEAWgIIACAAQALABALgDIALgDIABACIAAABQAOAtADAsQADAmgBAiIgDA3QgHBPAOA7QAEAQABAQQAEA0ACA6IABAnIAAAGIAAAnIAAAJIABA+IABBGQADAEAAAEQABAOgEAIQACAfAAAgIABBNQACBEgBA0QAEAMgDAPIgBAEIABACIABAAIACB2IAAAWQADACABADQACAIAAAIIgBA7IAAAmIACAOQAAAUgCATIAAAaIAAA7IAAAlQAGAfgFAcIAAAXQAAAKgCAJIADCbIAABeIAABkIgBAAQAHAXgCAgIgBAdIADAGQABADgBADIAAALIAAAOQAAALgEAGQACAiABAsIABBNQABAZgBAbIAAA+IAABdQABA3ACAqIABARQADASgHAPQgLgFgJgCgAglNUIAAACQgEAPgJACIAAABIgOAVIAAACQAwgvAsgzICfitQALgNADgLIgCAAQgJAEgJAHQgBAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAABIgPAdIgCAAIgRALIAAABQgQAPgIAVIgBAAQgPALgKARIgCAAQgJABgFANIgBABQgDAGgEgDIAAACIgQAWIgDACQgFAOgHgDIAAABQgQAQgMAUIgBAAQgRANgLAVIAAABIAAgBQgHAHgKABgAHtKdIABAAIACgBIAAgBgAHNJoIAAgBIAAAAIAAABgACfJVIAAAAIAAgBgAh4GCQgaAegSAdQgNACgKAQIgGAJQgOAUgQAIIAAABQgHAIgCAGIAAABQgSANgGAPIgBABQgPANgKAQQABAGAFgEQAGgDAEgFQBLhVBShXQANgNAAgIIgCAAQgNAAgJALgAliI8QACAGACgCQAqglAkgqQA9hFBAhDIABAAIAigkQApgpAtgnQAOgNgCgKIgCAAQgQAKgIAIQgOAQgQAPQgQARgLANQgXAUgVAVIgGAHQhUBShLBbIgBABIgMAKIAAACQgKAKgMAUIgCAAIgLAHgACMIIIAAgBIAAAAIAAABgACdH8IAAABIAAgCgAG3H5IACgBIAAAAIgCABgAD3HxIACAAIAAgBIgCABgAFsEgQgkAVgSAmIAAAEQAAABAAAAQAAAAAAAAQAAAAABAAQAAAAABgBQAYgiAdgdIgBAAgAj/DlQggAlgcAaQAKgBAGgGQApglAngnQBThTBVhSIBYhTIBRhLIABAAIgBgEQgGAEgJAAQgHAFgHAGIinChQhWBRhRBUIgBABQgEAFgEgCIgBACgAjbEGIgBACQgCACgIAEIgBABQgJALAKAAIAzg1ICnilIChifQgFAAgFgCIgCAAQgoAognAoIgBAAQgmAlgnAmIAAABQgHACADAEIgBAAQgsAogmAtIgBAAQgoAeggAvIgCAAIAAgCQgLAGgGANIgCAAQgKADgIAPgABXluIABAAIAAgBIgBABgAhMtHIhHBGQhGBFhOA9IgfAYQAJAGALgIQAagRAWgUICwicQAYgUAOgVIgDAAQgRAAgMAMgAghufIgBABQgOAKgLANQABAAAAABQABAAAAABQAAAAgBABQAAAAAAABQgVAbgdAbQgfAcgdAVIAAABIiaCRIAAADIAAACQAIgCAIgGQAIgGAJgIQA0gyA2gwQAxgqAugsQAmglAkgmIABgBIgBAAIgIgBIgLABgAAYxsQgEABgDAEQghAxgqApQgrApgtAlQgYAVgOAUIgCABQg1AngrAxIABABIA6guIA6gxQBYhOBOhWQAKgLALgJQAPgMgEgNIgGgBIgDABgAB0v9QAHAHAIAAQADAAAFgCIAIgFQBbhLBUhTQAOgNgIgCQAAgBgBAAQAAgBgBAAQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQgKAIgHADIAAABQhKBPhYBLIgCAAIgFgBQgJAAgKAKgApfiwQAGgJACgOIACAAQAPABANgEIACA1g");
	this.shape_5.setTransform(61.8,-6.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFCC").s().p("Aa6WDIl8hTIAAgFQgDgdAAgeIAAiBIgBhXIgBiDIgDg7QgDghAHgUQgGgsAAgvIABhLIgBhrIgChtQAAg9gCguIgDhiIAAhGIgBh4IgBhsIgChXIgChjIgCh3QgCg+AAhVIgBghQgCggAAg1QgBhGgDhCQgDhNABhMQAAgdgDgoQgFg3gBhTQAAghACglQACgYgFgRQgCgIgEgGIgCAAIgBgEIBOgQIhOAQIgLADQgHgEgJACQglALglAGIgmAGIAAABQhLAThBAIIAAABQgDAAgCAEQgbABgYAGIgxAMQg0ANg0AHIhkAVIh0AZIiFAaQiDAaiLAYQgmAHgcANQAAAFAEAAIACAAIABAFIgBAAIhBAOIBBgOIADAOQgDgBgEAIQAGA1ABA2IABBXQgBApADAfQAGBKAAA3QAAA0AEAzIAFAAIAAAMIAJFCQgNAEgQgBIgBAAQgCAOgGAJIAnAbIABAAIAAAIIgBgIIABAIQgDA+gEA3IABA9QgBAjACAYQAEBGACA7QAAAlgBApQgBAbAFATQABAuACAnIADBeIACA7IAFCVQACBWAAA6IAABCQABALgCAUQgCAmAJAfIglAHItZjCIAAAAIg1gQIgLgDIALADIgBAEIgDgBIgBADIgSAAIgCAAIjVAAIjPAAIi5AAIgkABIkVAAIgVAAMAAAgjwMA2NAAAIAAA9MAAAArIgAsbNuIACgBIASAAIAAABgA2FNuIgXAAIAkgBIgBABgA14NtIAAAAgAsCNng");
	this.shape_6.setTransform(-10.2,-9.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#993300").s().p("A7GGOIAApNIAAjLIAVAAIEVAAIAXAAIAMAAIABgBIC5AAIAAABIDPAAIAAgBIDVAAIAAABIAUAAIAAgBIABgCIADAAIgEACIAEgCIA2ANIAAAAINZDBIAYAGQAGAJASACQARACAPADQB2AYByAYICAAdQAUAEAMgDIAAABIAJAFIC6AlID9AyIECA1IABAAQABAFAHAEIABABQAGACAGgBQACgFAAgGIF8BSIANAAIAACCIAACDg");
	this.shape_7.setTransform(-10.2,117.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#CC9966").s().p("ACmBSIADgCIAAABIgCABgAiohNIAAAAIAAACIAAgCgAByhRIAAAAIgCABIACgBg");
	this.shape_8.setTransform(94.5,52);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AJXURIgBgBQgHgDgBgGIgBAAIkCg1Ij9gzIi4gmIgJgEIAAgBQgMADgUgFIiAgcQhygZh2gYQgPgDgRgBQgSgCgGgJIABgBIAJgFIAGgDIAAAAIALgDIAAABQgCAJAPACQANABAIgBQA5AQA8ANQA9AMA7AIQADAEAHABIAAABQCIAZCFAdQB8AbCIAbIB/AaIBlAWQAeAGAqAGQAJACAMAFQAHgPgDgSIgBgRQgDgqAAg3IgBhdIABg+QABgbgBgZIgChNQAAgsgCgiQAEgGgBgLIABgOIAAgLQABgDgCgDIgCgGIAAgdQACgggHgXIACAAIAAhkIAAheIgEibQADgJAAgKIgBgXQAGgcgGgfIAAglIAAg7IAAgaQACgUgBgTIgBgPIAAglIAAg7QAAgIgCgIQgBgDgCgCIgBgWIgBh2IgBAAIgBgDIAAgDQAEgPgEgMQABg0gChEIgBhNQAAgggDgfQAFgIgBgOQAAgEgDgEIgBhGIgBg+IAAgJIgBgnIAAgGIAAgnQgCg6gEg0QgBgQgEgQQgPg7AHhPIADg3QABgigCgmQgDgtgOgsIAMAAQACASAJATIABAAIgBglIAHAAQAFARgCAYQgCAlAAAhQABBTAFA3QADAoAAAdQgBBMADBNQADBCABBGQAAA1ACAgIABAhQAABVACA+IACB3IACBjIACBXIABBuIABB2IAABGIADBiQACAuAAA9IACBtIABBrIgBBLQAAAvAGAsQgHAUADAhIADA7IABCDIABBXIAACBQAAAeADAdIABAFQAAAGgDAFIgEABQgEAAgEgCgAopQQIAGgDgAomQJQgJgfACgmQACgUgBgLIAAhCQAAg6gChWIgFiVIgCg7IgDheQgCgngBguQgFgTABgbQABgpAAglQgCg7gEhGQgCgYABgjIgBg7QAFg5ACg+IAGB/IgGh/IACABQAEAhAAAtQABAagBAWIgDAjQADAdABAfIABBbQAAAmAIArQgCBCADBMIADBEIACBGIACBDIAEBqIACB+QABAsACA5IABAwIAAAyIgIAOIAAABIgBAAgAHFJaIAAAAIAAABIAAgBgACXJIIAAgBIAAABgACEH6IAAAAIAAABIAAgBgADvHkIACgBIAAABgAo/iaIAAAAgABPl7IAAgBIAAABgApKolIACg8IgCA8IgFAAQgEgzAAg0QAAg3gGhKQgDgfABgpIgBhXQgBg2gGg1QAEgJADACIAAAAQACADABAMIAFCDIAEBhIADAyQABAZAFAZQgDAhABAlIABAgIABAqQAHAKAAAJIgKgBgAplw2QAcgNAmgHQCLgYCDgaICFgaIB0gZIBigVQA0gHA0gNIAxgMQAYgGAbgBQACgEADAAIAAgBQBBgIBLgTIAAgBIAmgGIARAAIAzAAQgMADgLgBIgCAAQgWAIgUAEIAAABIgWABIAAgBQg9ARhCAMIgBABIgIABIh+AYIioAhIhaASIheASIgKACIKWiNIqWCNIh6AaIgEABIgpAIIjFAoQgdAGgZACIgBAAIgCABQgEAAAAgFg");
	this.shape_9.setTransform(62.7,-5.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#010101").s().p("AAvAJIAAgDIgBgKIADAAQADAEACAJgAAYAJIAAgBIgBgDIgLAEIgxAAIgRAAQAlgHAjgIQAJgDAHAEIhHAOIBHgOIABABIABALIAAACgAAigFIAAAAg");
	this.shape_10.setTransform(114,-136.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FEFEFE").s().p("AgMWlIAAiCMAAAgrHIAYAAMAAAAtJIgYAAg");
	this.shape_11.setTransform(164.6,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-185.9,-152.1,351.8,311.4);


(lib.proisboxingsentence = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// he
	this.instance = new lib.hepronoun();
	this.instance.setTransform(17.3,0.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0},4).to({alpha:1},5).to({alpha:0},5).to({alpha:1},5).to({alpha:0},5).to({x:-172.7},5).to({alpha:1},5).to({alpha:0},5).to({alpha:1},5).to({alpha:0},10).wait(1));

	// pro
	this.instance_1 = new lib.proword();
	this.instance_1.setTransform(-175.6,2.9,1.64,1.64);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},4).to({alpha:1},5).to({alpha:0},5).to({alpha:1},5).to({alpha:0},5).to({x:12.8,y:3.9},5).to({alpha:1},5).to({alpha:0},5).to({alpha:1},5).to({alpha:0},10).wait(1));

	// Layer 1
	this.instance_2 = new lib.proboxing();
	this.instance_2.setTransform(-29.4,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(55));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-203.4,-28.7,349.5,52.3);


// stage content:



(lib.pronoun_Scene1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.btn_menu.addEventListener("click", openMenu.bind(this));
		this.btn_goNext.addEventListener("click", openNext.bind(this));
		this.btn_goBack.addEventListener("click", openPrev.bind(this));
		
		function openMenu(){
		
		 window.open ("../menu/main_menu.html","_self");
		}
		
		function openNext(){
		
		 window.open ("pronoun_Scene2.html","_self");
		}
		
		function openPrev(){
		
		 window.open ("pronoun_intro.html","_self");
		}
		this.stop();
		playSound("_2a");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(48));

	// actions
	this.instance = new lib.Copyright("synched",0);
	this.instance.setTransform(275,389.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(48));

	// btn
	this.btn_goBack = new lib.goNext();
	this.btn_goBack.setTransform(57.6,352.3,1,1,0,0,180);
	new cjs.ButtonHelper(this.btn_goBack, 0, 1, 2, false, new lib.goNext(), 3);

	this.btn_goNext = new lib.goNext();
	this.btn_goNext.setTransform(494,352.3);
	new cjs.ButtonHelper(this.btn_goNext, 0, 1, 2, false, new lib.goNext(), 3);

	this.btn_menu = new lib.skiptomenu();
	this.btn_menu.setTransform(514.1,20.3);
	new cjs.ButtonHelper(this.btn_menu, 0, 1, 2, false, new lib.skiptomenu(), 3);

	this.instance_1 = new lib.pronounheader();
	this.instance_1.setTransform(275,18);

	this.instance_2 = new lib.proisboxingsentence();
	this.instance_2.setTransform(302.5,361.2);

	this.instance_3 = new lib.Pronounboxing2();
	this.instance_3.setTransform(284.5,184.7,0.98,0.98);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AglAsQgCgCAAgCQgDgSAIgQQADgLAFgNIADgHQAIgOAPgFQAWABAKAWIAEALIAEASQABAGgFABQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgFgCgEIgFgPQgCgHgEgHQgJgNgNADIgCABIgBABQgGAFgFAHIgGALIgCAJQgBAFgEAHQgEANACANQABAEgDADIgCABIgCgBg");
	this.shape.setTransform(241.6,95.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FEFEFE").s().p("AgLWlMAAAgtJIAXAAIAAFMIAAFMIAAFLIAAFMIAAFKIAAFMIAAFMIAAFMIAADsIgXAAg");
	this.shape_1.setTransform(455.4,168.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.btn_menu},{t:this.btn_goNext},{t:this.btn_goBack}]}).wait(48));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(284.2,198.6,537.1,400.3);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;