(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.vol_pos = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.5,1,1).p("ABagwIAABgQAAAWgZAAIiBAAQgZAAAAgWIAAhgQAAgVAZAAICBAAQAZAAAAAVg");
	this.shape.setTransform(9,7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgKA0QgDgDAAgGIAAgfIgFABIgTAAQgVAAAAgNQAAgHAHgDQADAAALAAIAYgBIAAgQIABgRQABgFADgDQADgCAEAAQAFAAADADQAEAEgBAFIAAAHIgBAIIABAPIAAAAIAKABIAIAAIAHgBIABAAIAJABQAKABADAGIABAEIgBAFIgDADIgDADIgFABIgEgBIgCAAIgEAAIgNAAIgOAAIAAAgQAAAMgLAAQgGAAgDgDg");
	this.shape_1.setTransform(9.6,6.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00CCFF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICBAAQAYAAABAWIAABfQgBAWgYAAgAgHAqQAAAGADADQAEADAEAAQAMAAABgMIAAggIANAAIAOAAIADAAIACAAIAFABIAFgBIADgDIACgDIABgFIgBgEQgCgGgKgBIgJgBIgBAAIgHABIgIAAIgKgBIAAAAIgBgPIABgIIAAgHQAAgFgEgEQgDgDgGAAQgEAAgBACQgEADgBAFIgBARIAAAQIgYABQgKAAgDAAQgHADgBAIQABAMAUAAIATAAIAFgBg");
	this.shape_2.setTransform(9,7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0099FF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICBAAQAYAAABAWIAABfQgBAWgYAAgAgHAqQAAAGADADQAEADAEAAQAMAAABgMIAAggIANAAIAOAAIADAAIACAAIAFABIAFgBIADgDIACgDIABgFIgBgEQgCgGgKgBIgJgBIgBAAIgHABIgIAAIgKgBIAAAAIgBgPIABgIIAAgHQAAgFgEgEQgDgDgGAAQgEAAgBACQgEADgBAFIgBARIAAAQIgYABQgKAAgDAAQgHADgBAIQABAMAUAAIATAAIAFgBg");
	this.shape_3.setTransform(9,7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_1},{t:this.shape_2},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape_3},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,19.9,16);


(lib.vol_neg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.5,1,1).p("AhAhFICBAAQAZAAAAAVIAABgQAAAWgZAAIiBAAQgZAAAAgWIAAhgQAAgVAZAAg");
	this.shape.setTransform(9,7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgMALIgCAAIgPAAQgLAAAAgKQAAgJALAAIAdgBIAdgBIAEABQAIAAAAAJQAAAIgKABIgVABIgJABIgNAAg");
	this.shape_1.setTransform(9.1,6.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICAAAQAaAAAAAWIAABfQAAAWgaAAgAABgLIgdAAQgLAAAAAKQAAAJALAAIAPAAIACAAIANAAIAJAAIAVgBQAKgBAAgIQAAgJgIAAIgEgBIgdABg");
	this.shape_2.setTransform(9,7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00CCFF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICAAAQAaAAAAAWIAABfQAAAWgaAAgAABgLIgdAAQgLAAAAAKQAAAJALAAIAPAAIACAAIANAAIAJAAIAVgBQAKgBAAgIQAAgJgIAAIgEgBIgdABg");
	this.shape_3.setTransform(9,7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0099FF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICAAAQAaAAAAAWIAABfQAAAWgaAAgAABgLIgdAAQgLAAAAAKQAAAJALAAIAPAAIACAAIANAAIAJAAIAVgBQAKgBAAgIQAAgJgIAAIgEgBIgdABg");
	this.shape_4.setTransform(9,7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_1},{t:this.shape_3},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape_4},{t:this.shape}]},1).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,19.9,16);


(lib.vol_mute = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AASBRQAAgIgQgQQgMgNgHAAIAAhZQAHAAANgOQAPgOAAgHg");
	this.shape.setTransform(15.6,13.9,1.2,1.201);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AgGglIANAAQABAAAAABIAABJQAAABgBAAIgNAAQgBAAAAgBIAAhJQAAgBABAAg");
	this.shape_1.setTransform(10.5,13.8,1.2,1.201);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#990000").ss(1,1,1).p("AhHBRQgCgDgDgCQgDgDgBgCQgbgeAAgpQAAgsAfgfQAgggAsAAQAjAAAcAUQAGAEAHAIQACACADACQAbAeAAApQAAAtggAfQgfAggtAAQgpAAgegbICYiY");
	this.shape_2.setTransform(15.1,14.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1,1,1).p("AAJAAQAAANgJAJQgCAFgGACIAAg5QAGADACAFQAJAIAAAMg");
	this.shape_3.setTransform(20.6,13.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1.5,1,1).p("ACWAAQAAA7gsAoQgtAqg9AAQg+AAgsgqQgrgoAAg7QAAg6ArgqQAKgIAKgHQAFgDAGgDQAJgFAKgEQAEgBAFgCQAWgHAZAAQAaAAAXAHQAEACAEABQAKAEAJAFQAFADAFADQAKAHAKAIQAsAqAAA6g");
	this.shape_4.setTransform(15,14.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAAABtQAuAAAfggQAfggAAgsQAAgpgbgeIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfQgfAgAAAsQAAApAaAeIAFAFIAFAFQAeAbAoAAgAhGBSICXiYQAbAeAAApQAAAsgfAgQgfAgguAAQgoAAgegbgAAuAaQAHgCACgGQAJgJAAgMQAAgMgJgJQgCgFgHgDIAAA6IAAAAgAhGBSIAAAAgAhLBNIgFgFQgageAAgpQAAgsAfggQAggfArAAQAkAAAbAUQAHAEAHAHIAEAFIiXCYIgFgFgAAuAagAAuggQAHADACAFQAJAJAAAMQAAAMgJAJQgCAGgHACgABAgDIAAAAgABRhGIAAAAg");
	this.shape_5.setTransform(15,14.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#00CCFF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAhLhLQgfAgAAAsQAAApAaAeIAFAFIAFAFQAeAbAoAAQAuAAAfggQAfggAAgsQAAgpgbgeIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfg");
	this.shape_6.setTransform(15,14.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhHBRICYiYQAbAeAAApQAAAtggAfQgfAggtAAQgpAAgegbgAAuAZQAGgCADgGQAJgIAAgMQAAgNgJgJQgDgFgGgDIAAA6IAAAAgAhMBMIgEgFQgbgeAAgpQAAgsAfgfQAgggAsAAQAjAAAcAUQAGAEAHAIIAFAEIiYCYIgFgFgAAuAZgAAughQAGADADAFQAJAJAAANQAAAMgJAIQgDAGgGACgABAgDIAAAAg");
	this.shape_7.setTransform(15.1,14.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0099FF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAhLhLQgfAgAAAsQAAApAaAeIAFAFIAFAFQAeAbAoAAQAuAAAfggQAfggAAgsQAAgpgbgeIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfg");
	this.shape_8.setTransform(15,14.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAhGBSQAeAbAoAAQAuAAAfggQAfggAAgsQAAgpgbgeQAbAeAAApQAAAsgfAgQgfAgguAAQgoAAgegbICXiYIiXCYgAhqABQAAApAaAeIAFAFIAFAFIgFgFIgFgFQgageAAgpQAAgsAfggQAggfArAAQAkAAAbAUQAHAEAHAHIAEAFIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfQgfAgAAAsIAAAAgAAuAaQAHgCACgGQAJgJAAgMQAAgMgJgJQgCgFgHgDIAAA6IAAAAgAAuAagAAuggQAHADACAFQAJAJAAAMQAAAMgJAJQgCAGgHACgABAgDIAAAAg");
	this.shape_9.setTransform(15,14.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_2},{t:this.shape_4},{t:this.shape_3},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_7},{t:this.shape_8},{t:this.shape_2},{t:this.shape_4},{t:this.shape_3},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_9},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,32,30.1);


(lib.Symbol96 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0000FF").s().p("AicDRQgsg0gKhjQgGgsAAiFQAAgwACgfQACggAFgNQAJgZAWAAQAhAAAAA7IAADOQAADVCTAAQCNAAAAlmIAAgjIgBgcQAAgWAIgQQAJgVAUgBQAjAAAAAyIABArIAAArQAAGXjTAAQhsgBg2g+g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-21.7,-27.1,43.3,54.3);


(lib.Symbol95 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0000FF").s().p("AjsESQgKgKAAgQIACgsQADgeAAgPIABhBIABhBIAAhFIgChHQAAgXgEgrQgEgrAAgXQAAgQAOgOQAOgNASAAQASAAAbAoQBYCEBGBWQBSBnBkBeQABgPgBgeIgBgsQAAiZgMhcQgBgIgJgdQgHgXAAgOQAAgpAlAAQA9AAAADlIAAB0IgCB0QAAARgFAnQgGAkggAAQgTAAgbgZQiPiIi4j+IgCCfIAABXIACBYQAABfglAAQgUAAgLgNg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-25,-28.7,50.1,57.4);


(lib.Symbol94 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0000FF").s().p("AixDaQhKhAABhjQgBh5BJhkQBQhuB3AAQB0AAA5AzQA5A3AAB0QAAB6hCBiQhMBvh3AAQhiAAhFg7gAh7h3Qg4BQAABeQAABDAyArQAxAoBGAAQBVAAA4hWQAxhNAAhgQAAhTgmgjQgjgghWAAQhVAAg7BVg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-25.1,-27.7,50.3,55.5);


(lib.R = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0000FF").s().p("AizEKQgKgLAAgPQAAgcgDg2QgCg4AAgbQgBghAIg/QAGhAAAggQAAgSgDgjQgDgjAAgSQAAgUAMgPQANgTAXACIBVAGQAwAGAgASQCPBMgBBtQABA1gxAoQgnAhg6ASQBtA6A2BBQAKAMgBAMQAAAPgKALQgMALgOAAQgNAAgMgLQh0h0iPgoIAFCLQAAAPgJALQgKAKgPAAQgPAAgKgKgAhwieQACAaAAARQAAAbgEArIgJBEIAPAAIAQABQBaAAAsgYQAUgJAQgSQAUgUgBgOQAAgwg3grQgygmg4gGIg0gEg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-19.5,-27.6,39.1,55.3);


(lib.proboxstill = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.5,1,1).p("AE0BmIoSAAAhthkIi6AAIgMAA");
	this.shape.setTransform(-58.6,85.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#010101").s().p("AgBAOQABgOACgOIAAALIAAAOIAAAEIgDgBg");
	this.shape_1.setTransform(-93.1,89.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AmNNPIgCAAQgggJgVgTIgBgCQAxgTArgaIApgaQAXgPADgYIAFgIIAQgXIABgBIAGgBQACAHgCAHIgCALIgKAqQAAADABACQAGAFADgBQAEgCACgHIALgoIABgCIACgKQABgJgCgHQAYgBAXAGQAZAGAXAPIAHAFIAAABQAAAJgRAKIgMAJIgLAJQgIgCgJAGQAJgKAMgGQAKgGAGgKQAFgJgDgGQgCgEgFgCQgEAAgCAFIAAABQgEAOgQAFQAAABgBAAQAAAAgBAAQgBABAAAAQAAAAgBABIgbAeQgDADACADQADADACACIgWAQQgbAUgbAQQgIAFgFAGQgIAMACAMIAAABIhNgDgAjKKoIgEAAQAAABgBAAQAAAAgBABQAAAAAAABQgBAAAAABIgBAJIgFAGIgFAFQgVARgTATQgDACABAEQAFAOALgLIAogmQAGgFADgHIABgBQAFgNgLgGgAmrJ5IgBAAQABgLgEgNIABAAQACgJgBgEIABAAQAIgjATgWIACAAQA4ABAxgOIAPgMIAIgHIAEALIgDABQgBAAAAABQgBAAAAAAQAAABgBAAQAAABAAAAQgBADAAADIgLAKIgQANQgHAGgIAEIgHADQgJACgFAGQgCADADADQAFAEAFABIgBAKIgLACQgPADACANQAAABABAAQAAAAAAABQABAAAAAAQABAAAAAAQAKAAAKgCQAKgCAJgEIAGgDQAYgOAXgRQgGANgCAOQgCAPgEAOIgDACIgIgCIgQgCIgBgBIgBAAIAAABIgegCIgIgBQgXgCgXAGIAAADQgPAEgRAAIgMAAgAGXqPQgKgGgIgIIgGgEIgHgIIgNgNIgFgGQgFgKADgHIAAgBIAAgBIACgCIAFgFIACgBQAGgBAFACQAIADAEAKIABABQAMAJAHAMQAIAEAJADIANAEIABABIgbAaIgBAAIgEgCgAGRsBIgCgBIgCgDQgDgEACgGQgDgJAAgLQABgLADgJIAAgBIACgDIABgEIABAAQAHgJAJgGIACgBIAEgCQAQgDAIAPIACAEQADAHACAIIgEgCIgPgBQgGACgCAHQgEAKAHAIQAIAIANgDIABgBIgFAEQgGADgFAEIgGAFQgJAGgKAAIgKgBg");
	this.shape_2.setTransform(-17.7,5.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF0000").s().p("AjrEIIAAgBIgNAAIgCAAIgGgDIgggSIgBgCQgLAKgQAGIAAABQgZACgWgEIgDgBIgCAAIgDgBIgCAEQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAIgSAAIgBAAIgBABQgMADgJgEQgGgCgEgHIgJgEQgDgBgCgCIgBAAIgCAAQgLgQgHgVIAAgCQAFgfARgUQABgBAAAAQABAAAAgBQABAAAAABQAAAAAAAAIAFgCIACgBIAHABIAAgBIABgBQADgBAFAAQAJACgHATQgFAPAGAOQAPAjAcASIAFACQAJgFgNgJQgegYgIguQAEgGABgGIAAgCIABgDQABgIAEgIIACgEIACgCIAAgBIABgDIACgDIAVgvQANgeAbgPQAOgIAQgFQATgGAVgBQAfgCAhAJQAiAJAWAUQAiAeAIA4QAFAkgKAqQgDAHgEADIgBACQgDAGgFAGQgNAQgQAKQgOAIgSABQgQACgPgCIgGABIAAABQgMgDgKgFgACHA3QgLAAgMgDQgIgBAEgEQAFgRgNAMIgBABQgGAAgFgFIgCAAQgTgVgNgcIgBAAQgBgTgEgQIAAgCQACgTAIgHIABgCQAOgEATAAIAAABQgCAtAYAcQAIAJAKAFIACABQAYAMANALQABAOgOAIIgCAAIgOABIgHAAgACdAKIgEgCIgHgEIgGgDIgCAAIgDgEIgFgEQgRgNgGgVIAAgCIgDgKIgBgCIAAgBIgEgPQgDgLgBgKQgCgNAEgMIAAgMIAAgCQAMggATgZQAiguA5gYIAKgDQAwgQA6AKQBKANAiA0QALARAIAVQADAYgEAfIAAACQgRA1gtAhQgYARgggBQgWgBggACIgfgQIgCAAQgDAMgKAIQgOAMgSADIgTABQgTAAgQgGgAC4hcQABAYAgADQAOACAPgEQAKgCAMgEQArgRACg9IgBgBQgLgXgZgJIgCgBQgigFgtAEIAAABQgHAFgGgDIAAACQgPAKgLAFQAEAJAMgHQAYgOAegBQA1gDAVAiIAAACQAEAhgYAXIgCAAQgIADgHAEIgBAAQgeAKgagIIAAgBQgMgDgDgNIAAgBIgCAAQgDAAgCAHg");
	this.shape_3.setTransform(45.6,-32.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#CC9966").s().p("AmUMZQgKgFgNgEQgOgDgIgGQgTACgZgBIAAgBQAPgoAMgsQADgJAFgGIAsgrIAigUQAUgLAUABQAKgDAJgGQAMgJAHgPIAHgDIABgCQADgHgKgBIgCAAQgPgWgYgTQgSgOgQgSQgogtgjgxIgLgPQApgqA8gYQAogQAxgIQAagEAngCQAKAAAKAFQAXA3ASA/IABAAQAEAkAGAbQAIAkgJAfIACADQgBAFACAFIAEASIAAAHIgBAEIgGAUIAAABIgBgBQgMAIgJAVQgGANgJANQhEBhhrA7QgFACgCAFQgYgHgZgMgAiqKeIAJgJIAFgIIAFgIQACgGAEgFQALgNAGgQIABgBIAEgKIADgNIABgBIAAgCIAHgTIgBgYQAAgEAFABQgHg3gRhFQgMgzgRg0QAMgHgHgTIAAgCQAXgMAigLIAAgBQAPAAAQgIIABgBQAyABAtAFQAGABAGgCIAfA2IABAAQAJAWAEAcIAAACQAKAfAEAmQAGAqgBAbIgBAhQAAAngPAdQgGAMgJAKQgNASgYAHQg1AQg1AMQgbAGgbAEQgWAEgiACIAKgPgAnVKOQgGgNgEgPQgCgJgGgEQAJgLAMgIQAigZAzgIQAngFAYAHIAAACQgIASgUAGQgJgCgMAEIgHADQg5AYgkAsQAAgDgCgFgAilBKQg1gCg7gIIgTgDIgMgCQhVgRgng8IAAgDIAAgCQALgHgEgHIgBgCIgCABIACgLIADgEIAGAKIADADQAZAhAqAPQAbALAeAGQAeAGAgABIAwACIAggBQA+gFApgaQALAFAPABQANACAFAFIABAAQgVAcgcAWIgBAAIAAAFIgFADIgDACQgBgHgDgHQglAOgyAAIgQgBgAiyATQhcAFhMgaIgCAAIgwgbQgFgCAEgGQgRgJgIgSQgGgMgEgNQgMgqACg4QANhAAYg0IAAgCQgSg4AUgpQAHgOALgMQAogrBGgNQAWgEAZAAIAPgCQAygJAdgdIAAACQAKABAHAGIACABQAggKAcgYQAEgEgCgKQASgGAOgJQAFgEACgHQgIgPgUgEIABgBQAMADAOAAQgKgGgEgJQgIgDgKgCIgCAAQADgGAMABIACAAQgDgPAHgVIgEgEIAAgBIgJABIAAgDQALgCgEgJIAAgCIAGgHIAAABIAJAGIAIgOIgCgBIgBgBIAAgDQABgEAHgDIADgBIABAAIABgCIgBgBIgBgCIgBgCIAAAAIAEgDIACACIAAABQAWgeAfgVIgEgBIADgHQABABAAAAQABAAAAAAQABAAABAAQAAABABgBIACAAIACACIANgIIAOABQAFgEAHgDIAKAAIAEgDQAHgFgLACQABgPAOAFIACAAQgMAPATgBIAAABIAAABIALABIAIAAQANgKAEACIgBACQgDADgBADIAnAAIANALQASAUABARIADAAIAEgDIAAABQAHAdgFAaIAAACQgGAGgBAGQgCAHADAHIAAACIAHAEQADgIAIgDIAGgDQADgDAFgBQAVgDgBAUIgBAHQAAAJgIAHQgKAGgNgDQgTABgOgGIgBAAQgGABAGAGIACAAQAEAGAIACIAAABQAAAegQAPIAAABIgWAAIgCAAQgLgCgJgFQgagNgHgcIgBgBQAOgIgKgIIgCgBIgCABQgNAEgFAMIAAACQgNAHgIAMIAAABIgBAAQgTAHAPAJIACAAIANgBIAAABIAPASIACABQgEAEAFAEIAAABIALALIAHAKIABABQAKADAHAGIABABQAGAFAFAIIAAABIAAAAQgPAPgWADIgBAAQgIABgJAAQghgDgggIQgJgLgLgFIAAADQgEASAaAHIACAAQgOAOADAOQAVgBAQAKQAfAHAWAQIABAAQAfAYgCAvIALAJIAIAFIAHAHQAVAVAQAZQAHALADAMQACAKgEAIIADAKIgOgEQgFABgEgCIgGgCIgcgJIgBAAQgTgCgVACIgCAAQAMgfgJgjIgBgBQgDABgDADQgDADgBAIIgBAAQACAOgCAKIAAACQgIALAAANIABACIgeAMIgWAIQgnANgPAoIgPAkQgFALgFAHQgBAEgCADQgCAEgEABQgXADgWgEIgHgCQgLgEgLgDQgKgCgIgGQgKgGgMgBIgCgBIgSgKIgJgCIgHgCIgIgDIgBAAIgFgBQgGAAgEgCIgMACIgBABIgBAAQACgVgIgbIABAAQgGgFABgKIABAAIgMgVIgBgBQATgTAKgbIABgCQgHgDgJAMIgXAfIAAAGQAGAFADAKIAEAJQAKAcABAeQABAEgDADQgGAHgHgBIgDABIgHAKIAIgGQAEgEAHgCIAJgCQANgBAMACIALABIAEACIAOAGIAaAJIAXAJIANAHIADADIAAgBIABAAIAOAJIABAAQAAAXgKAQIgBACIABATQADAbANASIACAAQgsAagyAFIgHABQgMAAgLgFgAlUj3IgBAAQgSAkgLArQAEASALAMQANAOALgCIAAgBQgGgMgMgFIgBgCIgJgPIAAgCQACgzAYgcIABgCQACgEgEAAIgGABgACrqMIACABQAQADANgIIAGgFQAFgEAFgDIAGgEQACgBACgCQAAAEAFgBIACgBQABgMgGgMQgCgNgGgNQgEgHgGgFQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBgBAAAAIgDAAQgFgCgHABQgEABgEACQgNAGgGAMQgHAIABAMIACAUQAAAKgBAJQAAAHAGgBIABAAIAAgDIADADgAC7sHQgPAGgMANIgEAFQgEAIAJAAIAIgHQAJgLANgFIABAAQAIgBAGAGQAEAEAFAAIACgCQACgEgCgDQgKgKgOAAIgGABgAE4gvQAFgMADgRQAIg7gWg0IgBAAQgLgNgIgQQA9gVA4gaQATgIAGgWIAPABIAAAFQAKA2ApAeQgfAngjAjQgIAIAEABIAAABIgDACQgKANgMAMQglAjg2ASIAEgIgACprFIABAAIgBADIgBABIABgEgACtrLIAAAAIACgCIAEgGIABAAIACgCIAJgEIgDABQgJAGgHAJIAAAAIABgCg");
	this.shape_4.setTransform(5.2,-6.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AmTQyQg1gBhAgFIhIgFQgkgCgoABQgQgGgTACIgCAAQgSgFgaABQgbABgZgIQgIAEgSgMIgCgBQAKgZgGgZIAAgCQAHgPAIgOIAAgCIAAAAQA2gmA2gkIABgBQAYgHAUgNIAAgBQBCgSAwgkIAAgBQgDgIAOgJQAXgPATgUQASgUAOgaIAFgLIACgFQgJADgJABQgOAFgTAAIhkABQgWAAgJgDQgaASgYAWIgMAMIgCADIi6AAIC6AAIgVATQgaAcgXAgIgMASQgGAKgFALQgRAhgbAVQgKAIgLAGQgfASgcgWQgOgKgCgRIAAgFIABgOIAAgLIACgKIACgKQACgIADgDQAGgPAJgOIABgCQgBgIADgMIAAgCIAGgHIABgBQAFgSAGgNIABgCIAEgJIABgCQAagnAXgqIAAgCQApg1AxgtIATgPQAJgGAMgEQAcAIAVAQQAWAQAVAEQADALAUgKIABgBQAvADAvgKIACAAQAEgHAJgCIABgBQAEgDACgEIAAgCQAEADAEgEIABgBQALgMANgKQAWgTAagMQAkgQAyAEQAKABAJgEQhHhFg8hPIAAgEIgBAAQgCgCgCgDIgKgTQgGgLgJgJIgEgFIgKgXQgGgMgBgPQgBgSgDgSIAAgIIAAgsIAAgsIgBgsIABgTIADgJQAGgWAJgTIACgGIAAgBIAEgDIAJgJIADgEIAHgDQAMgNALgQQAJgOACgQIACgBIADgKIAEgKIAAgBIAAAAQACgSgGgQIgEgKQgEgKgCgLQgFgbABgoQAMhCAYgxIABgBQgUgxAVgwIACgGQAghDBRgUQAHgCADACIABAAQANgJAYADQAmAEAlgVQALgGAKgCQARgKABgSIAAgBQgPgKAVACIACAAQAPgSACgVIgBAAQgIgFgIADIAAABQgUAZghAKIgHACQgGABgGgBQgLgJAJgEIACAAIASAGIAAgBQAYgRAQgWIgDAAQgFgEgHAKIgBAAQgQAHgTgCIgBACIgBAAQgEANgMgDIAAABQgGgCgJAAIgCABIgagRIgCAAQAGgLARgCIABAAIgzgnQgsABgIgtQgIgtAsgPQAGgVACgWQABgLAGgLQAMgXAbgGQAHgRAPgKQAWgOAcAFQgDgVANgQQAFgGAHgFQARgMAWADQAhgoA4AEIAGgFQAPgOARgGQAygOAbAlIAFAFQAZgGAXACQAaACAYAOQAUALAAARIAGgBIACAAQAIABgCAEIgBACQgRACACALIABAAQAFAJAIgGIAAABQATgQAbABIABAAQgLANgXALIABAAQADAOAFACIACAAQATgQAZADIACAAQAFADgGAEIgBABIghAMIAAABQAMADAIAGIABgBQACgBABgEQATgCAQASQAHAIgCAGQgIAEgMgNIgIgIQgIATgEAOIABAAQAHAGAEAAIACAAQAEgJAGgHIABgBQAbADAEAXIAKADIACgBQAQAMABAQIgBAAQgKADgFgMIgBAAQgKARgQABIgCAAQgEgJgHACIAAABQgMAOgSAHIgDAAQgFgIgIADIAAABIgMAMIgBABQALAlgHAqQAKgEAMgDIACAAQAKAFAIAGIAAACQACAJgDALIABAAQgJAegeABIgDAAIgCAAQgEAwgdANIgCAAIgFAIQgLATgOAPIgBACQgIAIgFAKIgDAEQgNAIgSADIgBAAQglAGgWgHQgHAGgEAJIAAABQAHAEAIABQAIACAIgBIACAAQAOAHAMACIABAAIALAHIABAAQAkAaAEA0IAAACQAjAYAXAkIAEAIIABADIADARIAAAGIABABIABAJQAAAMAFAJIgBAEIAAABIAAABIACABQAGAEAFAFIABABIABACIABgBIADgBQAGACAIgEIAEgFIAWgIIAIgDQAagFAWgNIAFgBIACAAQAVgNAXgSIACAAQgGAWgTAIQg4Aag9AVQAIAQALANIABAAQAWA0gIA7QgDARgFAMIgEAIQA2gSAkgjQANgMAKgNIADgCIAAgBQgEgBAIgIQAjgjAfgnQgpgegKg2IAAgFIAAgKQABgJgHgFQAFgSAPgKIAFgEIABgBQAIgBAHgCIABAAQAEgHAGgEIABgBQAAgQACgPQAFgcANgUIABgCQAigqAvggIAJgGQAJgEAMgDIAIgBQAWgMAnAAQAngBAYAFQBCAOAjAyQAHAJAGAKQAVAlgNAwIgCAHQgSA9gtAiQgOALgVAEQggAGgZABQgZABgTgKIgLgIQgaAigwgBIgCAAQgCAOgGAJQgGAJgKAGIAAABIgagDIghgDIAAgBQguA+g4A0QgTASgUAQQgcAXgrAJIgIAKQgLAMgOAJIAAABQg5ATg2gRIgCAAQgRgHgOgKIgCAAQgjARgtgEIgOgCIgCAAQgXA0grAWIgCABIAAgBIgIAEIAAAAIAAACIBJBYIACABQASAkAVAhIABABQAJAaAQAcQAWAnAHA6QAHA3ABAjQABAfgFApQgCATgGAQQgWA6hGAMQhBALg9AOQgpAJglgEQg6BIhRAzIgUAMIgNAKQgGAEgIAEQgFAEABACIAAABQghAVgcAZIgCAAQgKgHgPANQgaAVgeASQgKAFgDANQAPAZAhAIQAXAGAbAEIBOAIQAQACAPAEQATAFAQAKQAGAkgCAeIAAACIgGALIAAACIgpAbIgBABQg4gEg7gBgAsZQGQAFAEAGAAIgLgEIAAAAgAkXO7IoTAAgAnDLYIgBABIgPAXIgGAIQgDAYgWAPIgqAaQgqAagxATIAAACQAWATAfAJIACAAIBNADIAAgBQgBgMAHgMQAGgGAHgFQAcgQAagUIAXgQQgDgCgCgDQgDgDADgDIAcgeQAAgBABAAQAAAAAAgBQABAAABAAQAAAAABgBQAPgFAEgOIABgBQABgFAFAAQAFACABAEQAEAGgGAJQgFAKgLAGQgLAGgKAKQAKgGAHACIALgJIANgJQARgKAAgJIABAAIgBgBIgIgFQgWgPgagGQgWgGgZABQADAHgCAJIgCAKIgBACIgLAoQgCAHgDACQgEABgFgFQgCgCABgDIAJgqIADgLQABgHgBgHIgHABgAl5LPQANAEAKAFQAZAMAYAHQACgFAFgCQBrg7BEhhQAJgNAGgNQAJgVAMgIIABABIAAgBIAGgUIABgEIAAgHIgEgSQgCgFABgFIgCgDQAJgfgIgkQgGgbgEgkIgBAAQgSg/gXg3QgKgFgKAAQgnACgaAEQgxAIgoAQQg8AYgpAqIALAPQAjAxAoAtQAQASASAOQAYATAPAWIACAAQAKABgDAHIgBACIgHADQgHAPgNAJQgIAGgKADQgUgBgUALIgiAUIgsArQgFAGgDAJQgMAsgPAoIAAABQAZABATgCQAIAGAOADgApeKuIABAAQAYACATgGIABgDQAWgGAYACIAHABIAfACIAAgBIABAAIABABIAPACIAIACIAEgCQAEgOACgPQACgOAFgNQgXARgYAOIgGADQgJAEgKACQgJACgKAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQgCgNAOgDIAMgCQAcgIAWgTQAJgHAHgJIAEgCIAEgBIAAAAIgIgNIgBAEQgDAEgEADIgKAHQgKARgUAHIgFACQgHAFgFAAQgGgBgFgEQgCgDACgDQAFgGAJgCIAHgDQAIgEAGgGIARgNIALgKQgBgDABgDQAAAAABgBQAAAAAAgBQABAAAAAAQABgBAAAAIADgBIgDgLIgIAHIgQAMQgwAOg5gBIgCAAQgTAWgHAjIgBAAQABAEgCAJIgBAAQADANAAALgAg/HWIABAYIgHATIAAACIgBABIgEANIgDAKIgBABQgGAQgLANQgEAFgCAGIgFAIIgFAIIgJAJIgKAPQAigCAWgEQAbgEAbgGQA0gMA2gQQAYgHANgSQAJgKAGgMQAPgdAAgnIABghQABgbgGgqQgEgmgKgfIAAgCQgEgcgJgWIgBAAIgfg2QgGACgGgBQgugFgxgBIgBABQgQAIgPAAIAAABQgiALgXAMIAAACQAHATgMAHQARA0AMAzQARBFAHA3IgBAAQgEAAAAADgAmpJdIABABIABgCIgCABgAlLHwQgzAIgiAZQgMAIgJALQAGAEACAJQAEAPAGANQACAFAAADQAkgsA5gYIAHgDQAMgEAJACQAUgGAIgSIAAgCQgNgEgSAAQgPAAgRACgAl3hmQAEAHgLAHIAAACIAAADQAnA9BVARIAMACIATADQA7AHA1ACQA8ADArgPQADAGABAHIADgCIAFgDIAAgFIAAAAQAcgVAVgcIgBAAQgFgFgNgCQgPgBgLgFQgoAag+AFIggABIgwgCQgggBgegGQgegGgbgLQgqgQgZghIgDgDIgGgKIgDAEIgCALIACgBIABACgAhigpQAygFAsgbIgCAAQgNgSgDgbIgBgTIABgCQAKgQAAgXIgBAAIgOgJIgBAAIAAABIgDgDIgNgHIgXgJIgagJIgOgGIgEgCIgLgBQgMgCgNABIgJACQgHACgEAEIgIAGIAHgKIADgBQAHABAGgHQADgDgBgEQgBgegKgcIgEgJQgDgKgGgFIAAgGIAXgfQAJgMAHADIgBACQgKAbgTATIABABIAMAVIgBAAQgBAKAGAFIgBAAQAIAbgCAVIABAAIABgBIAMgCQAEACAGAAIAFABIABAAIAIADIAHACIAIACIATAKIACABQAMABAKAGQAIAGAKACQALADALAEIAHACQAVAEAXgDQAEgBADgEQACgDABgEQAFgHAFgLIAPgkQAPgoAngNIAWgIIAegMIgBgCQAAgNAIgLIAAgCQACgKgCgOIABAAQABgIADgDQADgDADgBIABABQAJAjgMAfIACAAQAVgCATACIABAAIAcAJIAGACQAEACAEgBIAPAEIgDgKQAEgIgCgKQgDgMgHgLQgQgZgVgVIgHgHIgIgFIgLgJQACgvgfgYIgBAAQgWgQgfgHQgQgKgVABQgDgOAOgOIgCAAQgagHAEgSIAAgDQALAFAJALQAgAIAhADQAJAAAHgBIACAAQAWgDAPgPIAAAAIAAgBQgFgHgGgGIgBgBQgHgGgKgDIgBgBIgHgKIgLgLIAAgBQgFgEAEgEIgCgBIgPgSIAAgBIgNABIgCAAQgPgJATgHIABAAIAAgBQAIgMANgHIAAgCQAFgMANgEIACgBIACABQAKAIgOAIIABABQAHAcAaANQAJAFALACIACAAIAWAAIAAgBQAQgPAAgeIAAgBQgIgCgEgGIgCAAQgGgGAGgBIABAAQAOAGATgBQAMADALgGQAIgHgBgJIACgHQABgUgVADQgFABgDADIgGADQgIAEgDAHIgHgEIAAgCQgDgHACgHQABgGAGgGIAAgCQAFgagHgdIAAgBIgEADIgDAAQgBgRgSgUIgNgLIgnAAQABgDADgDIABgCQgEgCgNAKIgIAAIgLgBIAAgBIAAgBQgTABAMgPIgCAAQgOgFgBAPQALgCgHAFIgFADIgJAAQgHADgFAEIgOgBIgNAIIgCgCIgCAAQgBABAAAAQgBAAgBgBQAAAAgBAAQAAAAgBgBIgDAHIAEABQgfAVgWAeIAAgBIgDgCIgEADIAAAAIABACIABACIABABIgBACIgBAAIgEABQgGADgBAEIAAADIABABIACABIgIAOIgJgGIAAgBIgGAHIAAACQAEAJgLACIAAADIAJgBIAAABIAEAEQgHAVACAPIgBAAQgMgBgDAGIACAAQAKACAIADQAEAJAJAGQgNAAgMgDIgBABQAUAEAIAPQgCAHgFAEQgOAJgRAGQACAKgEAEQgcAYggAKIgCgBQgHgGgKgBIAAgCQgdAdgyAJIgPACQgZAAgWAEQhGANgoArQgLAMgHAOQgVApATA4IAAACQgYA0gNBAQgCA4AMAqQAEANAGAMQAIASARAJQgEAGAFACIAwAbIACAAQBMAbBcgFQANAGARgCgADag/IAAABQAKAFAMADIAAgBIAGgBQAQACAPgCQASgBAOgIQAQgKANgQQAFgGADgGIABgCQAEgDADgHQAKgqgFgkQgIg4gigeQgWgUgigJQghgJgfACQgVABgTAGQgQAFgOAIQgbAPgNAeIgVAvIgCADIgBADIAAABIgCACIgCAEQgEAIgBAIIgBADIAAACQgBAGgEAGQAIAuAeAYQANAJgJAFIgFgCQgcgSgPgjQgGgOAFgPQAHgTgJgCQgFAAgDABIgBABIAAABIgHgBIgCABIgFACQAAAAAAAAQAAgBgBAAQAAABgBAAQAAAAgBABQgQAUgFAfIAAACQAHAVAKAQIACAAIABAAQACACADABIAJAEQAEAHAGACQAJAEAMgDIABgBIABAAIASAAQAAAAABAAQAAgBABAAQAAAAAAgBQABAAAAgBIACgEIADABIACAAIADABQAXAEAYgCIAAgBQAQgGALgKIABACIAgASIAGADIACAAIAGAAIAHAAgAIykXQgEAEAIABQAMADALAAQAMABAJgCIACAAQAOgIgBgOQgNgLgYgMIgCgBQgKgFgIgKQgYgcACgtIAAgBQgTAAgOAEIgBACQgIAHgCATIAAACQAEAQABATIABAAQANAdATAVIACAAQAFAFAGAAIABgBQAFgFADAAQADAAgDAKgAKrpMIgKADQg5AYgiAuQgTAZgMAgIAAACIAAAMQgEAMACANQABAKADALIAEAPIAAABIABACIADAKIAAACQAGAVARANIAFAEIADAFIACAAIAGADIAHAEIAEACQAYAJAegEQASgDAOgMQAKgJADgMIACAAIAfAQQAggCAWABQAgABAYgRQAtghARg1IAAgCQAEgfgDgYQgIgVgLgRQgig0hKgNQgWgEgVAAQgiAAgdAKgAC6qiIgCABIgEAFIgDACIAAABIAAABQgDAHAFAKIAGAGIAMANIAIAIIAFAEQAJAIAJAGIAEACIACAAIAagaIAAgBIgOgEQgIgDgIgEQgHgMgNgJIgBgBQgEgKgIgDQgDgBgFAAIgDAAgAm4MfQgCgEADgCQATgTAVgRIAGgFIAFgGIABgJQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABgBIADAAIAAgBQAMAGgGANIAAABQgDAHgGAFIgpAmQgFAFgDAAQgFAAgCgIgAkxjLQgLgMgEgSQALgrASgkIABAAQALgEgDAHIgBACQgYAcgCAzIAAACIAJAPIABACQAMAFAGAMIAAABIgDABQgKAAgLgNgAKejwIAAgIIABAAIABAJIgCgBgAKfmIQgggDgBgYQADgJAEACIAAABQADANAMADIAAABQAaAIAegKIABAAQAHgEAIgDIACAAQAYgXgEghIAAgCQgVgig1ADQgeABgYAOQgMAHgEgJQALgFAPgKIAAgCQAGADAHgFIAAgBQAtgEAiAFIACABQAZAJALAXIABABQgCA9grARQgMAEgKACQgLADgKAAIgIgBgADTrTQABgJAAgKIgCgUQgBgMAHgIQAGgMANgGQAEgCAEgBQAHgBAFACIADAAQAAAAABABQABAAAAAAQABAAAAABQABAAAAAAQAGAFAEAHQAGANACANQAGAMgBAMIgCABQgFABAAgEQgCACgCABIgCABQgMADgIgIQgHgIADgKQADgHAFgCIAPABIAEACQgBgIgDgHIgDgEQgHgPgRADIgEACIgIAEIgCACIgBAAIgEAGIgCACIAAAAIgBACIgCAEIgBAAIgBAEQgCAJgBALQgBALAEAJQgCAGACAEIAAADIgBAAIgBABQgFAAAAgHgADOswIAEgFQAMgNAPgGQASgDAMAMQACADgCAEIgCACQgFAAgEgEQgGgGgIABIgBAAQgNAFgJALIgIAHQgJAAAEgIg");
	this.shape_5.setTransform(0.2,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.proboxstill, new cjs.Rectangle(-93.3,-107.9,186.6,215.8), null);


(lib.P = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0000FF").s().p("AiUEPQgKgKAAgOIAAhoQAAgzAHhdQAGhmABgsIAAgwQAAgjAFgQQAHgfAbAEQALgDAUgDIA0gBQA/AAA4AsQA+AwAABEQAABYhCAzQg7AvhSAAQgKAAghgGQgCA2AACFQAAAOgKAKQgJAJgOABQgNgBgJgJgAg6jUIgUACIgIDNIAmAEQA6AAAogeQAsghAAg4QAAgngqgcQgngagsAAIgbABg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-15.9,-28,31.8,56.1);


(lib.menu_main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgWAoQgQgMAAgdIAAgIIAAgIIABgHIAAgGQAAgFABgEQADgFAEgBQADAAADACQADADgBADIAAAKIAAAKIAAAIIAAAIQAAAJABAHQADAJAFAEQADABAIABQAPAAAGgaQADgNAAgaIABgFQADgFAFAAQADAAADAEQAAAAAAABQAAAAABABQAAAAAAABQAAAAAAABQAAAXgCANQgDATgKAOQgEAFgGAEQgHAFgIgBQgPABgGgGg");
	this.shape.setTransform(37.7,11.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgoAtQgDgCAAgDIABgIIAAgHIAAgKIAAgKIAAgKIAAgMIgBgKIAAgLQAAgDADgDQADgDAEAAQAEAAAFAIQAaAmAaAXIAAgJIgBgmIgBgGIAAgHQAAgIAJAAQAJAAAAAeIAAAJIgBAkIAAAJQgBAIgIAAQgEAAgFgFQgWgUgcgkIgBASIABAOIAAAOQAAARgJAAQgDAAgDgDg");
	this.shape_1.setTransform(28.5,10.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgaAsQgHgFAAgTIABgXIACgXIgBgGIgBgGQAAgJAJAAQAAAAABAAQABAAAAAAQABABAAAAQABAAAAAAIANgCIALgBQAPAAAIADQAGACAAAGQAAADgCACQgDADgDAAIgDAAQgJgDgJAAIgJABIgKACIgBAXIAWgDIAOgBQAEABACACQADACAAADQAAAHgIAAIgOABIgYADIAAAMQAAAMABABQABABAGAAIAKgBIALAAIAEAAIADAAQAEAAACABQADADAAAEQAAAGgHACQgGABgRAAQgUAAgFgGg");
	this.shape_2.setTransform(20,10.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAfAmIgCgOQgDgKgEgTIgJAXIgDALIgFALQgDAFgEAAQgFAAgEgHIgDgLIgIgeIgIAcIgBANQgDAJgHgBQgDAAgDgCQgCgDAAgDQAAgKAFgNIAGgWIADgSQADgMADgFQADgEAEAAQAGABACAFQADAFADAQQACAPAFARQAGgRAGgVIADgNQADgIAHAAQAGgBADAKIADAPQADAYAGASIAFAUQAAADgDACQgDACgDAAQgGABgEgKg");
	this.shape_3.setTransform(10.9,11);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1.5,1,1).p("Ai4hoIFxAAQAxAAAAAwIAABxQAAAwgxAAIlxAAQgxAAAAgwIAAhxQAAgwAxAAg");
	this.shape_4.setTransform(23.4,10.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ai4BpQgxAAAAgwIAAhxQAAgwAxAAIFxAAQAxAAAAAwIAABxQAAAwgxAAg");
	this.shape_5.setTransform(23.4,10.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(1.5,1,1).p("Ai4hoIFxAAQAxAAAAAwIAABwQAAAxgxAAIlxAAQgxAAAAgxIAAhwQAAgwAxAAg");
	this.shape_6.setTransform(23.4,10.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#00CCFF").s().p("Ai4BpQgxAAAAgxIAAhvQAAgxAxAAIFxAAQAxAAAAAxIAABvQAAAxgxAAg");
	this.shape_7.setTransform(23.4,10.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0099FF").s().p("Ai4BpQgxAAAAgxIAAhvQAAgxAxAAIFxAAQAxAAAAAxIAABvQAAAxgxAAg");
	this.shape_8.setTransform(23.4,10.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_8},{t:this.shape_6},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,48.8,23);


(lib.general_buttoncolor = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{resetRed:1});

	// timeline functions:
	this.frame_0 = function() {
		this.play();
	}
	this.frame_8 = function() {
		this.gotoAndPlay("resetRed");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(8).call(this.frame_8).wait(2));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#D5FFD7","#61EF01","#1DA400","#004A00"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgwAAgigjQgjgigBgxQABgwAjgiQAigjAwAAQAxAAAjAjQAjAigBAwQABAxgjAiQgjAjgxAAIAAAAg");
	this.shape.setTransform(11.9,11.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FFFFFF","#EC0000","#9D0000","#480000"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgwAAgigjQgjgigBgxQABgwAjgiQAigjAwAAQAxAAAjAjQAjAigBAwQABAxgjAiQgjAjgxAAIAAAAg");
	this.shape_1.setTransform(11.9,11.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},8).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,23.7,23.6);


(lib.Copyright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAcAIIgEgLIgDAKQgEAJgEAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBIgCgJIgCgHQgGATgDAAIgCgBIgBgDIABgCQACgEACgHIADgMQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQAFAAACAIIACALIADgGIADgJQACgFACAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIADAKIACAHIADAIIABABIgBADIgDABQgDAAgCgJgAgUANIgBgIIAAgGIgBgHIgFAAIgFgBQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAEAAIAFAAIAPAAIADAAIADAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABQAAABAAABQAAAAgBABQAAAAAAAAQgBAAgBAAIgNABIAAAHIABAHIAAAEIABADIgBADIgCAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAgBg");
	this.shape.setTransform(57.3,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgMAYQgGgCAAgEIABgDQAAgBABAAQAAAAABAAQAAgBABAAQAAAAAAAAIAEACIAFACIAEABIAGgBQAEgCAAgCQAAgGgIgCIgEgCIgIgCQgDgCAAgFQAAgJAIgEIAIgDIAIgDIADAAIAEABIABADIABAEIAAADIgBAEIgDABQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBIgCgEIgKADQgGACAAAFIACAAQAJACAGADQAHAEAAAJQAAAHgGADQgFADgIAAQgFAAgGgCg");
	this.shape_1.setTransform(51,2.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgLATQgHgGAAgJQAAgIAGgJQAGgLAIAAQAEAAAGACQAGADAAADIgBADQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgDgBIgCgCQgCgCgGAAQgEAAgEAIQgEAIAAAEQAAAGAEADQADADAGAAIAFgBIAFgDIACgBIADACIABADQAAADgGADQgHADgDAAQgJAAgFgGg");
	this.shape_2.setTransform(46.6,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgDAgQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgIIAAgIIABgKIAAgKQAAAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAIADgBIACABQABAAAAABQAAAAAAABQABAAAAABQAAAAAAAAIgBAKIAAAKIAAAIIAAAIQAAABAAAAQAAAAAAABQAAAAgBAAQAAABAAAAIgCABIgDgBgAgCgXQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAQAAgBgBAAg");
	this.shape_3.setTransform(43.1,1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AALAVIgBgJIgBgKIAAgDIAAgEQAAgKgDAAQgFABgEAFQgEAGgCAGIAAAFIgBAEIABAEIAAAEIgBADIgDACIgEgCIgBgDIAAgEIAAgEIAAgMIABgMIAAgEIAAgEIABgEIADgBQAEABAAAFIABAFQAHgKAHAAQAHAAADAHQABAEABAIIAAAFIAAACIABAKIAAAJIgBAEIgDABQgEAAAAgFg");
	this.shape_4.setTransform(39.5,2.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAOAWIgDgDIgHADIgFACQgKAAgFgGQgEgFAAgMQAAgKAHgHQAIgIAJAAQAEAAAEACQAGADAAADIgBACIAAAGIgBAJIABAIIADAJIABABIAAABIgBAEIgDABIgDgDgAgGgKQgFAGAAAGQAAAHACADQADAEAFAAQADAAADgBIAEgEIgBgQIAAgEIABgFIgDgBIgCgBQgFABgFAFg");
	this.shape_5.setTransform(34.8,2.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAMAiIgCgLIgBgLIAAgDIAAgDQAAgIgDABQgGAAgDADIgHAKQAAARgBADQgBABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgBgEIABgBIAAgGIAAgHIAAggIABgHIgBgEIAAgEQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBQADAAAAAEIABAIIAAAKIAAAJIAAAFQAEgFAEgDQADgDAFABQAGAAAEAEQABAEAAAHIABAIIAAAJIACAJIABACQAAAAgBAAQAAABAAAAQAAABAAAAQgBAAAAAAIgDABQgDAAgBgCg");
	this.shape_6.setTransform(30,1.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgLATQgHgGAAgJQAAgIAGgJQAGgLAIAAQAEAAAGACQAGADAAADIgBADQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgDgBIgCgCQgCgCgGAAQgEAAgEAIQgEAIAAAEQAAAGAEADQADADAGAAIAFgBIAFgDIACgBIADACIABADQAAADgGADQgHADgDAAQgJAAgFgGg");
	this.shape_7.setTransform(25,2.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgOATQgHgFAAgKQAAgLAGgHQAGgJAJAAQAHAAAFACQAFADAAAHQAAAEgFAEIgJAEIgQAHQADAFADABQAEACAEAAIAHgBQAFgCACgCQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAABAAIADABIABADQAAAEgIAEQgHADgGAAQgJAAgGgFgAgIgLQgEAFgCAGIAOgFQAHgEADgCQgDgEgHAAQgFAAgDAEg");
	this.shape_8.setTransform(20.3,2.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAbAhIgCgHIgCgIQgCgGgDgXIgJAZIgDAJIgEAIQgBADgCAAQgDAAgCgDIgBgFIgBgEIgIghIgCAIIgGAWIgBANQgCADgDAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBIAAgDQAAgHACgLIAGgQIACgPQACgJACgDQACgDACAAQADAAABAEQADAEABAMQADAOAFAPQAFgPAFgTIABgGIACgGQACgEADAAQAEAAABAIIADAKQACATADAOIADAIIACAHQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAAAIgDABQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAgBg");
	this.shape_9.setTransform(13.8,1.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgQAUIAAgeIAAgEIAAgEQAAgFAEAAQAEAAAAAIQAIgJAKAAQAEAAABADQACADAAAFIAAADQAAAGgEAAQgEAAAAgFIAAgDIAAgDQgHAAgEAEQgDACgDAGIAAAXQAAAFgEAAQgEAAAAgFg");
	this.shape_10.setTransform(5.1,2.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAOAWIgDgDIgHADIgFACQgKAAgFgGQgEgFAAgMQAAgKAHgHQAIgIAJAAQAEAAAEACQAGADAAADIgBACIAAAGIgBAJIABAIIADAJIABABIAAABIgBAEIgDABIgDgDgAgGgKQgFAGAAAGQAAAHACADQADAEAFAAQADAAADgBIAEgEIgBgQIAAgEIABgFIgDgBIgCgBQgFABgFAFg");
	this.shape_11.setTransform(0.5,2.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgBAaQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIgBgQIgBgPQAAgEgCgDQgDABgCAEIgGAFIgCADIAAAHIgBAIIABADIAAAEQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAABIgEABQgEAAAAgLIAAgIIABgHIgBgHIAAgHQgBgKAFAAIADABQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABIAAACIgBADIAAAFQACgFAFgEQAEgEADAAQAHAAACAHQADgDACgCQAEgBAFAAQAGAAADAIIACAMIAEAYIgCADIgDABQgEAAAAgDIgCgOIgCgNIgBgGQgCgEgBAAIgGADIgGAEIAAAIIACALIABAMIgBADIgEABQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAg");
	this.shape_12.setTransform(-5.2,2.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgCAaQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIgBgQIgBgPQAAgEgBgDQgEABgCAEIgGAFIgCADIgBAHIAAAIIAAADIABAEQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAABIgDABQgGAAAAgLIABgIIAAgHIAAgHIgBgHQABgKAEAAIADABQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAABIAAACIAAADIAAAFQADgFAEgEQAFgEADAAQAGAAACAHQACgDADgCQAEgBAEAAQAIAAACAIIACAMIAEAYIgCADIgDABQgDAAgBgDIgCgOIgCgNIgBgGQgBgEgCAAIgGADIgFAEIAAAIIABALIABAMIgBADIgEABQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAgBAAg");
	this.shape_13.setTransform(-12.2,2.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAOAWIgDgDIgHADIgFACQgKAAgFgGQgEgFAAgMQAAgKAHgHQAIgIAJAAQAEAAAEACQAGADAAADIgBACIAAAGIgBAJIABAIIADAJIABABIAAABIgBAEIgDABIgDgDgAgGgKQgFAGAAAGQAAAHACADQADAEAFAAQADAAADgBIAEgEIgBgQIAAgEIABgFIgDgBIgCgBQgFABgFAFg");
	this.shape_14.setTransform(-18.1,2.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgQAUIAAgeIAAgEIAAgEQAAgFAEAAQAEAAAAAIQAIgJAKAAQAEAAABADQACADAAAFIAAADQAAAGgEAAQgEAAAAgFIAAgDIAAgDQgHAAgEAEQgDACgDAGIAAAXQAAAFgEAAQgEAAAAgFg");
	this.shape_15.setTransform(-22.4,2.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgWAeQgFgGAAgMQAAgLAFgLQAGgMAIgIQAGgFAFAAQAEAAAGACQAJAEgBADIgBAEIgDABIgDgBQgGgEgFAAQgDAAgDAEIgFAFQgKAOAAAPQAAAIADAEQACADAHAAQAIAAAGgFQAGgFACgKQgNAAgHAEIgCABQgBAAAAAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgCgCQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAABAAQAJgFAWAAIAEABIABACQAAABAAABQAAAAgBABQAAAAAAABQgBAAAAABQgDANgJAIQgJAIgLAAQgKAAgGgGg");
	this.shape_16.setTransform(-27.7,1.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgOAhIgBgDIADgIIAKgXQAFgPAHgHIABgBIgVgBIgKAAQgEAAAAgEQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAIARABIAPAAIAIAAQAFAAAAADQAAACgDADIgEAFQgFAHgFAJIgIARIgDAKIgEAKQAAAAgBABQAAAAAAAAQgBABgBAAQAAAAgBAAIgDgCg");
	this.shape_17.setTransform(-36.2,1.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AABAiIgIAAIgEAAQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgFAHAAIACAAIACAAIAAgGIgBgGIABgQIABgRQgGAEgBAAIgDgBIgCgDQAAgCAEgDIAHgFQADgEADAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAADIAAADIAAAFIAAAEIgBAPIgCAOIABAGIABAGIAEAAQABAAAAAAQAAAAABAAQAAAAAAABQABAAAAAAIABADIgBADIgDABg");
	this.shape_18.setTransform(-41,1.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgTAXQgFgJAAgPQAAgMAGgKQAIgLALAAQAMAAAGAKQAGAJAAAMQAAATgHAJQgGAKgMAAQgNAAgGgMgAgLgRQgEAHAAAJQAAANAEAIQAEAHAHAAQAJAAAEgLQADgHAAgLQAAgLgEgHQgEgFgHAAQgHgBgFAJg");
	this.shape_19.setTransform(-45.9,1.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AANAhIgDgBIgGABIgGAAIgFAAIgFABIgCAAIgBAAQgDAAgBgDIgBgGQAAgKAGgGQADgDALgHIAHgGQAEgFAAgFQAAgDgEgCQgDgCgDAAQgDAAgEACIgGAFIgDABQgEAAAAgDQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQAFgFAEgCQAFgDAFAAQAHAAAGAEQAGAEAAAHIgBAJIgEAGQgDADgIAFQgIAFgCADQgFAFAAAHIAJAAIAMgBIAHABQAEACAAACQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBABIgCABIgEgBg");
	this.shape_20.setTransform(-51.3,1.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgeABQgBgLALgKQALgJANAAQANAAAHAIQAIAIAAAMQAAAKgJAKQgKALgNAAIAAAAQgfAAABgdgAgOgPQgJAHABAJQAAALAFAFQAHAFAKAAQAKAAAHgJQAGgIAAgHQAAgJgDgFQgFgFgJAAIgCAAQgLAAgHAGgAgLAJQgFgEAAgFQAAgHAHgFQAGgEAHAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAAAQABABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAABAAABQAAAAgBABQAAAAgBAAQgBAAgBAAIgBAAIgBAAQgEAAgEACQgFADAAADQAAACAEABIAEACQADAAADgDIAEgCIAEABIABADQgBADgEADQgGADgEAAQgFAAgFgEg");
	this.shape_21.setTransform(-57.7,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.3,-7.1,126.6,16.6);


(lib.pronounintro = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_50 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(50).call(this.frame_50).wait(1));

	// Layer 1
	this.instance = new lib.Symbol95("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(506.6,276.4);
	this.instance.alpha = 0.102;

	this.instance_1 = new lib.Symbol96("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(451.3,276.5);
	this.instance_1.alpha = 0.102;

	this.instance_2 = new lib.Symbol94("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(395.8,276.7);
	this.instance_2.alpha = 0.102;

	this.instance_3 = new lib.Symbol95("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(338.6,276.4);
	this.instance_3.alpha = 0.102;

	this.instance_4 = new lib.Symbol94("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(280.9,276.7);
	this.instance_4.alpha = 0.102;

	this.instance_5 = new lib.R("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(230.1,275.9);
	this.instance_5.alpha = 0.102;

	this.instance_6 = new lib.P("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(188.3,275);
	this.instance_6.alpha = 0.102;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_6,p:{alpha:0.102,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:0.102,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:0.102,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:0.102,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:0.102,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:0.102,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:0.102,scaleX:1,scaleY:1,x:506.6,y:276.4}}]}).to({state:[{t:this.instance_6,p:{alpha:0.199,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:0.199,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:0.199,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:0.199,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:0.199,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:0.199,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:0.199,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:0.301,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:0.301,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:0.301,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:0.301,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:0.301,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:0.301,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:0.301,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:0.398,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:0.398,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:0.398,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:0.398,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:0.398,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:0.398,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:0.398,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:0.5,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:0.5,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:0.5,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:0.5,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:0.5,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:0.5,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:0.5,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:0.602,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:0.602,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:0.602,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:0.602,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:0.602,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:0.602,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:0.602,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:0.699,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:0.699,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:0.699,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:0.699,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:0.699,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:0.699,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:0.699,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:0.801,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:0.801,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:0.801,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:0.801,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:0.801,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:0.801,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:0.801,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:0.898,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:0.898,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:0.898,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:0.898,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:0.898,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:0.898,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:0.898,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1.209,scaleY:1.209,x:173.1,y:278.2}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1.209,scaleY:1.209,x:520.9,y:279.8}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1.773,scaleY:1.773,x:132.1,y:286.9}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1.773,scaleY:1.773,x:559.7,y:289.2}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:2.577,scaleY:2.577,x:73.6,y:299.2}},{t:this.instance_5,p:{alpha:1,scaleX:1.01,scaleY:1.01,x:229.6,y:276}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:2.577,scaleY:2.577,x:614.9,y:302.6}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:3.488,scaleY:3.488,x:7.4,y:313.1}},{t:this.instance_5,p:{alpha:1,scaleX:1.304,scaleY:1.304,x:213.7,y:280.8}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1.021,scaleY:1.021,x:452.2,y:276.8}},{t:this.instance,p:{alpha:1,scaleX:3.488,scaleY:3.488,x:677.4,y:317.8}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:4.375,scaleY:4.375,x:-57.2,y:326.7}},{t:this.instance_5,p:{alpha:1,scaleX:1.93,scaleY:1.93,x:179.8,y:290.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1.352,scaleY:1.352,x:466.8,y:282.4}},{t:this.instance,p:{alpha:1,scaleX:4.375,scaleY:4.375,x:738.4,y:332.5}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:5.123,scaleY:5.123,x:-111.7,y:338.1}},{t:this.instance_5,p:{alpha:1,scaleX:2.767,scaleY:2.767,x:134.4,y:304.4}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:2.005,scaleY:2.005,x:495.6,y:293.4}},{t:this.instance,p:{alpha:1,scaleX:5.123,scaleY:5.123,x:789.8,y:345}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:5.123,scaleY:5.123,x:-111.7,y:338.1}},{t:this.instance_5,p:{alpha:1,scaleX:3.684,scaleY:3.684,x:84.7,y:319.2}},{t:this.instance_4,p:{alpha:1,scaleX:1.145,scaleY:1.145,x:276.3,y:279.1}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:2.856,scaleY:2.856,x:533.1,y:307.6}},{t:this.instance,p:{alpha:1,scaleX:5.644,scaleY:5.644,x:825.6,y:353.7}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:5.123,scaleY:5.123,x:-111.7,y:338.1}},{t:this.instance_5,p:{alpha:1,scaleX:4.55,scaleY:4.55,x:37.8,y:333.2}},{t:this.instance_4,p:{alpha:1,scaleX:1.655,scaleY:1.655,x:260.2,y:287.8}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1.082,scaleY:1.082,x:397.4,y:278.1}},{t:this.instance_1,p:{alpha:1,scaleX:3.773,scaleY:3.773,x:573.5,y:323}},{t:this.instance,p:{alpha:1,scaleX:5.884,scaleY:5.884,x:842,y:357.7}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:5.123,scaleY:5.123,x:-111.7,y:338.1}},{t:this.instance_5,p:{alpha:1,scaleX:5.256,scaleY:5.256,x:-0.5,y:344.6}},{t:this.instance_4,p:{alpha:1,scaleX:2.426,scaleY:2.426,x:235.9,y:300.9}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1.522,scaleY:1.522,x:406,y:285.5}},{t:this.instance_1,p:{alpha:1,scaleX:4.628,scaleY:4.628,x:611.3,y:337.4}},{t:this.instance,p:{alpha:1,scaleX:5.829,scaleY:5.829,x:838.2,y:356.7}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:5.123,scaleY:5.123,x:-111.7,y:338.1}},{t:this.instance_5,p:{alpha:1,scaleX:5.72,scaleY:5.72,x:-25.6,y:352.1}},{t:this.instance_4,p:{alpha:1,scaleX:3.328,scaleY:3.328,x:207.4,y:316.2}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:2.249,scaleY:2.249,x:420.1,y:297.9}},{t:this.instance_1,p:{alpha:1,scaleX:5.314,scaleY:5.314,x:641.5,y:348.9}},{t:this.instance,p:{alpha:1,scaleX:5.5,scaleY:5.5,x:815.6,y:351.3}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:5.123,scaleY:5.123,x:-111.7,y:338.1}},{t:this.instance_5,p:{alpha:1,scaleX:5.897,scaleY:5.897,x:-35.2,y:355}},{t:this.instance_4,p:{alpha:1,scaleX:4.229,scaleY:4.229,x:178.9,y:331.4}},{t:this.instance_3,p:{alpha:1,scaleX:1.202,scaleY:1.202,x:337.4,y:279.7}},{t:this.instance_2,p:{alpha:1,scaleX:3.135,scaleY:3.135,x:437.4,y:312.9}},{t:this.instance_1,p:{alpha:1,scaleX:5.751,scaleY:5.751,x:660.8,y:356.2}},{t:this.instance,p:{alpha:1,scaleX:4.951,scaleY:4.951,x:777.9,y:342.1}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:4.256,scaleY:4.256,x:-48.6,y:324.9}},{t:this.instance_5,p:{alpha:1,scaleX:5.78,scaleY:5.78,x:-28.9,y:353.1}},{t:this.instance_4,p:{alpha:1,scaleX:5.008,scaleY:5.008,x:154.3,y:344.7}},{t:this.instance_3,p:{alpha:1,scaleX:1.76,scaleY:1.76,x:334.1,y:289}},{t:this.instance_2,p:{alpha:1,scaleX:4.046,scaleY:4.046,x:455.1,y:328.3}},{t:this.instance_1,p:{alpha:1,scaleX:5.898,scaleY:5.898,x:667.3,y:358.7}},{t:this.instance,p:{alpha:1,scaleX:4.256,scaleY:4.256,x:730.2,y:330.6}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:3.501,scaleY:3.501,x:6.4,y:313.3}},{t:this.instance_5,p:{alpha:1,scaleX:5.399,scaleY:5.399,x:-8.2,y:346.9}},{t:this.instance_4,p:{alpha:1,scaleX:5.573,scaleY:5.573,x:136.4,y:354.2}},{t:this.instance_3,p:{alpha:1,scaleX:2.56,scaleY:2.56,x:329.3,y:302.3}},{t:this.instance_2,p:{alpha:1,scaleX:4.86,scaleY:4.86,x:471,y:342.1}},{t:this.instance_1,p:{alpha:1,scaleX:5.754,scaleY:5.754,x:660.9,y:356.3}},{t:this.instance,p:{alpha:1,scaleX:3.501,scaleY:3.501,x:678.3,y:318}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:2.767,scaleY:2.767,x:59.8,y:302.1}},{t:this.instance_5,p:{alpha:1,scaleX:4.812,scaleY:4.812,x:23.6,y:337.4}},{t:this.instance_4,p:{alpha:1,scaleX:5.864,scaleY:5.864,x:127.2,y:359.2}},{t:this.instance_3,p:{alpha:1,scaleX:3.47,scaleY:3.47,x:323.9,y:317.5}},{t:this.instance_2,p:{alpha:1,scaleX:5.476,scaleY:5.476,x:483,y:352.6}},{t:this.instance_1,p:{alpha:1,scaleX:5.349,scaleY:5.349,x:643,y:349.5}},{t:this.instance,p:{alpha:1,scaleX:2.767,scaleY:2.767,x:627.9,y:305.8}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:2.125,scaleY:2.125,x:106.5,y:292.2}},{t:this.instance_5,p:{alpha:1,scaleX:4.097,scaleY:4.097,x:62.3,y:325.9}},{t:this.instance_4,p:{alpha:1,scaleX:5.859,scaleY:5.859,x:127.4,y:359.1}},{t:this.instance_3,p:{alpha:1,scaleX:4.359,scaleY:4.359,x:318.6,y:332.3}},{t:this.instance_2,p:{alpha:1,scaleX:5.827,scaleY:5.827,x:489.8,y:358.6}},{t:this.instance_1,p:{alpha:1,scaleX:4.746,scaleY:4.746,x:616.4,y:339.4}},{t:this.instance,p:{alpha:1,scaleX:2.125,scaleY:2.125,x:583.8,y:295.1}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1.622,scaleY:1.622,x:143.1,y:284.5}},{t:this.instance_5,p:{alpha:1,scaleX:3.339,scaleY:3.339,x:103.4,y:313.6}},{t:this.instance_4,p:{alpha:1,scaleX:5.574,scaleY:5.574,x:136.4,y:354.3}},{t:this.instance_3,p:{alpha:1,scaleX:5.111,scaleY:5.111,x:314.1,y:344.8}},{t:this.instance_2,p:{alpha:1,scaleX:5.884,scaleY:5.884,x:490.9,y:359.5}},{t:this.instance_1,p:{alpha:1,scaleX:4.023,scaleY:4.023,x:584.6,y:327.2}},{t:this.instance,p:{alpha:1,scaleX:1.622,scaleY:1.622,x:549.3,y:286.7}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1.278,scaleY:1.278,x:168.1,y:279.3}},{t:this.instance_5,p:{alpha:1,scaleX:2.62,scaleY:2.62,x:142.3,y:302}},{t:this.instance_4,p:{alpha:1,scaleX:5.059,scaleY:5.059,x:152.7,y:345.5}},{t:this.instance_3,p:{alpha:1,scaleX:5.637,scaleY:5.637,x:311,y:353.5}},{t:this.instance_2,p:{alpha:1,scaleX:5.655,scaleY:5.655,x:486.4,y:355.6}},{t:this.instance_1,p:{alpha:1,scaleX:3.266,scaleY:3.266,x:551.2,y:314.5}},{t:this.instance,p:{alpha:1,scaleX:1.278,scaleY:1.278,x:525.7,y:281}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1.086,scaleY:1.086,x:182.1,y:276.3}},{t:this.instance_5,p:{alpha:1,scaleX:2.004,scaleY:2.004,x:175.7,y:292.1}},{t:this.instance_4,p:{alpha:1,scaleX:4.383,scaleY:4.383,x:174,y:334.1}},{t:this.instance_3,p:{alpha:1,scaleX:5.883,scaleY:5.883,x:309.5,y:357.6}},{t:this.instance_2,p:{alpha:1,scaleX:5.183,scaleY:5.183,x:477.2,y:347.6}},{t:this.instance_1,p:{alpha:1,scaleX:2.554,scaleY:2.554,x:519.8,y:302.6}},{t:this.instance,p:{alpha:1,scaleX:1.086,scaleY:1.086,x:512.5,y:277.8}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1.011,scaleY:1.011,x:187.5,y:275.2}},{t:this.instance_5,p:{alpha:1,scaleX:1.535,scaleY:1.535,x:201.1,y:284.5}},{t:this.instance_4,p:{alpha:1,scaleX:3.632,scaleY:3.632,x:197.8,y:321.3}},{t:this.instance_3,p:{alpha:1,scaleX:5.833,scaleY:5.833,x:309.8,y:356.8}},{t:this.instance_2,p:{alpha:1,scaleX:4.534,scaleY:4.534,x:464.6,y:336.6}},{t:this.instance_1,p:{alpha:1,scaleX:1.951,scaleY:1.951,x:493.2,y:292.5}},{t:this.instance,p:{alpha:1,scaleX:1.011,scaleY:1.011,x:507.3,y:276.5}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1.225,scaleY:1.225,x:217.9,y:279.5}},{t:this.instance_4,p:{alpha:1,scaleX:2.889,scaleY:2.889,x:221.2,y:308.7}},{t:this.instance_3,p:{alpha:1,scaleX:5.508,scaleY:5.508,x:311.7,y:351.4}},{t:this.instance_2,p:{alpha:1,scaleX:3.792,scaleY:3.792,x:450.2,y:324}},{t:this.instance_1,p:{alpha:1,scaleX:1.497,scaleY:1.497,x:473.2,y:284.8}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1.062,scaleY:1.062,x:226.8,y:276.9}},{t:this.instance_4,p:{alpha:1,scaleX:2.227,scaleY:2.227,x:242.1,y:297.5}},{t:this.instance_3,p:{alpha:1,scaleX:4.963,scaleY:4.963,x:315,y:342.3}},{t:this.instance_2,p:{alpha:1,scaleX:3.041,scaleY:3.041,x:435.5,y:311.3}},{t:this.instance_1,p:{alpha:1,scaleX:1.203,scaleY:1.203,x:460.2,y:279.9}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1.005,scaleY:1.005,x:229.8,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1.698,scaleY:1.698,x:258.9,y:288.5}},{t:this.instance_3,p:{alpha:1,scaleX:4.27,scaleY:4.27,x:319.1,y:330.8}},{t:this.instance_2,p:{alpha:1,scaleX:2.356,scaleY:2.356,x:422.2,y:299.7}},{t:this.instance_1,p:{alpha:1,scaleX:1.052,scaleY:1.052,x:453.5,y:277.4}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1.326,scaleY:1.326,x:270.6,y:282.2}},{t:this.instance_3,p:{alpha:1,scaleX:3.515,scaleY:3.515,x:323.6,y:318.2}},{t:this.instance_2,p:{alpha:1,scaleX:1.796,scaleY:1.796,x:411.3,y:290.2}},{t:this.instance_1,p:{alpha:1,scaleX:1.004,scaleY:1.004,x:451.4,y:276.6}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1.11,scaleY:1.11,x:277.5,y:278.5}},{t:this.instance_3,p:{alpha:1,scaleX:2.78,scaleY:2.78,x:328,y:306}},{t:this.instance_2,p:{alpha:1,scaleX:1.391,scaleY:1.391,x:403.4,y:283.3}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1.018,scaleY:1.018,x:280.4,y:277}},{t:this.instance_3,p:{alpha:1,scaleX:2.136,scaleY:2.136,x:331.8,y:295.3}},{t:this.instance_2,p:{alpha:1,scaleX:1.143,scaleY:1.143,x:398.6,y:279.1}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1.63,scaleY:1.63,x:334.9,y:286.8}},{t:this.instance_2,p:{alpha:1,scaleX:1.029,scaleY:1.029,x:396.4,y:277.2}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1.283,scaleY:1.283,x:336.9,y:281.1}},{t:this.instance_2,p:{alpha:1,scaleX:1.001,scaleY:1.001,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1.088,scaleY:1.088,x:338.1,y:277.8}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1.012,scaleY:1.012,x:338.5,y:276.5}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).to({state:[{t:this.instance_6,p:{alpha:1,scaleX:1,scaleY:1,x:188.3,y:275}},{t:this.instance_5,p:{alpha:1,scaleX:1,scaleY:1,x:230.1,y:275.9}},{t:this.instance_4,p:{alpha:1,scaleX:1,scaleY:1,x:280.9,y:276.7}},{t:this.instance_3,p:{alpha:1,scaleX:1,scaleY:1,x:338.6,y:276.4}},{t:this.instance_2,p:{alpha:1,scaleX:1,scaleY:1,x:395.8,y:276.7}},{t:this.instance_1,p:{alpha:1,scaleX:1,scaleY:1,x:451.3,y:276.5}},{t:this.instance,p:{alpha:1,scaleX:1,scaleY:1,x:506.6,y:276.4}}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(172.4,247,359.2,58.1);


(lib.proboxingmove = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.proboxstill();
	this.instance.parent = this;
	this.instance.setTransform(-23,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:5,y:-21},4).to({x:-2,y:-10},5).to({x:23.4,y:-9.4},5).to({x:0,y:0},10).to({x:-23},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-116.3,-107.9,186.6,215.8);


(lib.proboxingjump = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.proboxingmove();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-30},4).to({y:0},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-116.3,-107.9,186.6,215.8);


(lib.intro = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgJAKQgEgEAAgGQAAgFAEgFQADgDAGAAQAGAAAEADQAEAFABAFQgBAGgEAEQgEAEgGABQgGgBgDgEg");
	this.shape.setTransform(118.1,8.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AAdA5IgEgaIgBgZIAAgKIAAgMQAAgZgJAAQgNAAgLAQQgLAOgGAVIgBALIgBALIABALIABALQAAAFgDADQgEADgFAAQgFAAgDgDQgDgDAAgFIgBgLIgBgLIACggIACghIgBgMIAAgLQAAgFADgDQAEgDAEAAQALAAABAPIABAOQATgbAUAAQATAAAHARQAFALABAWIAAALIAAAKQAAAKACAQQADAPAAAJQAAAGgEADQgDADgFAAQgKAAgBgLg");
	this.shape_1.setTransform(109,2.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF0000").s().p("AAaA4QgPAIgSAAQgPAAgKgHQgLgIgCgOQgFgfAAgXQAAgQAEgVQABgKAKAAQAFAAADADQAEADAAAFIgCASIgCASIABAgQACAOACAIIAIAEIAHABQAPAAARgFIAAgYIAAgWQAAgZACgTQACgKAKAAQAFAAADADQAEADgBAFIgCAsIAAAZIAAAZIABAIIAAAIQAAAFgDADQgEADgEAAQgKAAgCgLg");
	this.shape_2.setTransform(96.3,2.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF0000").s().p("AgiAyQgQgRgBgbQgBgZAOgUQARgYAcAAQAXAAANAVQAJASAAAYQAAAZgNASQgQAVgYAAQgTAAgOgOgAgUgXQgIANAAAQQAAARAJAKQAIAHAKAAQAMAAAIgIQAKgKABgRQACgsgaAAIgBAAQgQAAgJAQg");
	this.shape_3.setTransform(83.5,2.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF0000").s().p("AAdA5IgEgaIgBgZIAAgKIAAgMQAAgZgJAAQgNAAgLAQQgLAOgGAVIgBALIgBALIABALIABALQAAAFgDADQgEADgFAAQgFAAgDgDQgDgDAAgFIgBgLIgBgLIACggIACghIgBgMIAAgLQAAgFADgDQAEgDAEAAQALAAABAPIABAOQATgbAUAAQATAAAHARQAFALABAWIAAALIAAAKQAAAKACAQQADAPAAAJQAAAGgEADQgDADgFAAQgKAAgBgLg");
	this.shape_4.setTransform(71.4,2.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAlA8QgFgFgCgDIgUAJQgJADgEAAQgcAAgMgPQgMgPAAgeQAAgbATgVQAUgUAaAAQAKAAANAGQAQAGAAAJQAAAEgDACIgBAPIgBAYQAAAPACAJQABAFAGAPIADAGIAAACQAAAFgDADQgDADgEAAQgDAAgGgFgAgTgcQgNAPAAASQAAATAHAKQAGAKAOgBQAKAAAIgEQAEgCAIgGQgEgfAAgPIABgLIACgNIgIgDIgFgBQgRAAgNAPg");
	this.shape_5.setTransform(51.6,2.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgtA2IAAhRIAAgMIABgMQAAgMAKAAQALAAABAUQAWgWAaAAQAKAAAFAHQAFAIAAAOIAAAIQgCAPgLAAQgKAAAAgMIAAgIIAAgKQgSACgKAJQgLAHgHAQIAAA/QAAAMgLAAQgLAAAAgMg");
	this.shape_6.setTransform(32.9,2.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgiAyQgQgRgBgbQgBgZAOgUQARgYAcAAQAXAAANAVQAJASAAAYQgBAZgNASQgPAVgYAAQgTAAgOgOgAgUgXQgIANAAAQQAAARAJAKQAJAHAJAAQAMAAAIgIQAKgKABgRQACgsgaAAIgBAAQgQAAgJAQg");
	this.shape_7.setTransform(20.3,2.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgTBkQgDgDAAgFIAAgCQADgPAAgSIgBggIAAghIgSABQgMAAAAgMQAAgLAVgBIALAAIACgSQADgaAKgMQALgPAaAAQARAAAAALQAAALgQAAQgcAAgDAoIgBAHIAagBQATAAAAALQAAAJgKACIgJAAQgFAAgWACIgBAZIABAWIAAAWQAAAWgCANQgBAJgJAAQgFAAgEgDg");
	this.shape_8.setTransform(7.9,0.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AggBCQgSgHAAgMQAAgEADgEQAEgEAFAAQAEAAAFAGQADACAKADIANABQAJAAAIgDQALgDgBgIQABgPgXgGIgLgCQgPgEgHgEQgJgGAAgOQAAgYAWgKQAIgDAOgEIAWgIQAFgCAFAAQAGgBADAEQADADAAAFIACAKIABAKQAAAFgDAEQgEAEgEAAQgHAAgCgFQgCgDgCgJIgbAIQgSAHAAALIAHACQAaAFAOAIQATAMAAAWQAAAUgRAJQgOAIgUAAQgPAAgOgEg");
	this.shape_9.setTransform(-11.3,2.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgnAzQgTgPABgbQAAgdAOgVQARgWAaAAQATAAAMAHQAPAHAAARQAAAMgNAKQgGAEgTAIIgsAVQAHAKAKAFQAJAEAMABQAJAAALgEQANgDAFgHQAEgGAEAAQAEAAADAEQAEACAAAFQAAANgWAJQgRAIgSAAQgZAAgQgNgAgYgeQgJAKgEAVIAkgQQAUgKAIgIQgKgJgRAAQgOAAgKAMg");
	this.shape_10.setTransform(-23.2,2.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgHBTQgDgDAAgFIAAgOIABgNIgDhEIgagBQgKgBAAgLQAAgFADgDQADgEAFAAIAZACIgBgQIAAgPQAAgFADgDQADgCAFAAQAKAAACARIAAAKIAAAHIAAAHIAQgCQANAAADABQAHADAAAJQAAAFgDADQgDADgFAAIgGAAIgGAAIgQABIADBFIAAAFIAAAGQAAAZgMABQgEAAgEgDg");
	this.shape_11.setTransform(-35.7,0.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AAaA4QgPAIgSAAQgPAAgKgHQgLgIgCgOQgFgfAAgXQAAgQAEgVQABgKAKAAQAFAAADADQAEADAAAFIgCASIgCASIABAgQACAOACAIIAIAEIAHABQAPAAARgFIAAgYIAAgWQAAgZACgTQACgKAKAAQAFAAADADQAEADgBAFIgCAsIAAAZIAAAZIABAIIAAAIQAAAFgDADQgEADgEAAQgKAAgCgLg");
	this.shape_12.setTransform(-47.5,2.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgHBTQgDgDAAgFIAAgOIABgNIgDhEIgagBQgKgBAAgLQAAgFADgDQADgEAFAAIAZACIgBgQIAAgPQAAgFADgDQADgCAFAAQAKAAACARIAAAKIAAAHIAAAHIAQgCQANAAADABQAHADAAAJQAAAFgDADQgDADgFAAIgGAAIgGAAIgQABIADBFIAAAFIAAAGQAAAZgMABQgEAAgEgDg");
	this.shape_13.setTransform(-59.5,0.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgLBVQgDgDAAgGIAAgUIgBgVIABgcIACgaQAAgGADgDQADgDAFgBQAEABADADQAEADAAAGIgCAaIgBAcIABAVIAAAUQAAAGgDADQgDADgEAAQgGAAgDgDgAgHhAQgEgEAAgFQAAgGAEgEQAEgEAFAAQAGAAAEAEQAEAEAAAGQAAAFgEAEQgEAEgGAAQgFAAgEgEg");
	this.shape_14.setTransform(-68.2,-0.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgHBTQgDgDAAgFIAAgOIABgNIgDhEIgagBQgKgBAAgLQAAgFADgDQADgEAFAAIAZACIgBgQIAAgPQAAgFADgDQADgCAFAAQAKAAACARIAAAKIAAAHIAAAHIAQgCQANAAADABQAHADAAAJQAAAFgDADQgDADgFAAIgGAAIgGAAIgQABIADBFIAAAFIAAAGQAAAZgMABQgEAAgEgDg");
	this.shape_15.setTransform(-77.5,0.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AggBCQgSgHAAgMQAAgEADgEQAEgEAFAAQAEAAAFAGQADACAKADIANABQAJAAAIgDQALgDgBgIQABgPgXgGIgLgCQgPgEgHgEQgJgGAAgOQAAgYAWgKQAIgDAOgEIAWgIQAFgCAFAAQAGgBADAEQADADAAAFIACAKIABAKQAAAFgDAEQgEAEgEAAQgHAAgCgFQgCgDgCgJIgbAIQgRAHgBALIAHACQAaAFANAIQAUAMAAAWQgBAUgQAJQgOAIgUAAQgPAAgOgEg");
	this.shape_16.setTransform(-89.3,2.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgjBYQgEAFgFAAQgEAAgDgDQgEgDAAgFIAAgJIAAgJIAAglIgBgkIAAggIAAghQAAgHAEgGQADgHAIAAQAIAAAAAKIAAAFIgBAFIAAAaIAAAeQAJgHAKgEQAJgDAHAAQAZAAAQATQAPARAAAbQgBAagQATQgSATgZAAQgRAAgPgHgAgSgFIgQALIgBAUIABASIAAAUIAPAGQAHACAJAAQAQAAALgMQALgLAAgSQAAgSgJgLQgJgMgQAAQgJAAgKAFg");
	this.shape_17.setTransform(-101.7,-0.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAaA4QgPAIgSAAQgPAAgKgHQgLgIgCgOQgFgfAAgXQAAgQAEgVQABgKAKAAQAFAAADADQAEADAAAFIgCASIgCASIABAgQACAOACAIIAIAEIAHABQAPAAARgFIAAgYIAAgWQAAgZACgTQACgKAKAAQAFAAADADQAEADgBAFIgCAsIAAAZIAAAZIABAIIAAAIQAAAFgDADQgEADgEAAQgKAAgCgLg");
	this.shape_18.setTransform(-115.2,2.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AggBCQgSgHAAgMQAAgEADgEQAEgEAFAAQAEAAAFAGQADACAKADIANABQAJAAAHgDQALgDAAgIQAAgPgWgGIgLgCQgQgEgGgEQgKgGAAgOQAAgYAYgKQAGgDAPgEQAQgFAGgDQAFgCAGAAQAFgBADAEQADADAAAFIABAKIACAKQAAAFgDAEQgEAEgFAAQgGAAgDgFQgBgDgBgJIgbAIQgTAHABALIAGACQAaAFAOAIQASAMABAWQAAAUgRAJQgOAIgUAAQgPAAgOgEg");
	this.shape_19.setTransform(-127.7,2.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AAgBYQgDgJgCgSQgCgRAAgLIAAgJIAAgJQAAgWgLAAQgOAAgLANQgGAHgLAUQAAAsgDAJQgEAGgHAAQgEAAgEgDQgEgDAAgFIABgFIACgRIAAgRIAAhWIABgTIgBgLQgBgFAAgGQAAgGADgCQAEgEAFAAQAJABACAJQACAMAAAJIgBAaIgBAZIAAALQAKgNALgHQAKgGAMAAQAUAAAHAMQAFAKABATIABAXIACAZIAEAXIABAEQAAAFgEADQgDADgFAAQgJABgCgKg");
	this.shape_20.setTransform(72.1,-35.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AghA0QgRgQAAgZQAAgXAQgZQASgcAUAAQAMAAAOAFQATAHgBAKQAAAEgCAEQgDAEgFAAQgEgBgBgCIgGgDQgGgGgRAAQgKAAgMAWQgKATAAANQAAAPAKAJQAKAJAPAAQAHAAAHgEIAOgHIAFgCQAEAAADADQADAEABAFQAAAIgSAIQgRAHgJAAQgYAAgQgOg");
	this.shape_21.setTransform(58.9,-32.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgLBVQgDgDAAgGIAAgVIgBgUIABgcIACgaQAAgGADgDQADgEAFAAQAEAAADAEQAEADAAAGIgCAaIgBAcIABAUIAAAVQAAAGgDADQgDADgEAAQgGAAgDgDgAgHhAQgEgEAAgFQAAgGAEgEQAEgEAFAAQAGAAAEAEQAEAEAAAGQAAAFgEAEQgEAEgGAAQgFAAgEgEg");
	this.shape_22.setTransform(49.5,-35.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AAgBYQgDgJgCgSQgCgRAAgLIAAgJIAAgJQAAgWgLAAQgOAAgLANQgGAHgLAUQAAAsgDAJQgEAGgHAAQgEAAgEgDQgEgDAAgFIABgFIACgRIAAgRIAAhWIABgTIgBgLQgBgFAAgGQAAgGADgCQAEgEAFAAQAJABACAJQACAMAAAJIgBAaIgBAZIAAALQAKgNALgHQAKgGAMAAQAUAAAHAMQAFAKABATIABAXIACAZIAEAXIABAEQAAAFgEADQgDADgFAAQgJABgCgKg");
	this.shape_23.setTransform(39.2,-35.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAHAiIgEgbIgDgaIgKAWIgSAwQgBAFgDACQgEAHgHAAQgJAAgJgjQgEgSgEgeIgDgSIgBgRQAAgFADgDQAEgEAEAAQAJAAADAKIACARIACARIAHA0QANgjAOgvQADgNAJAAQAJAAAEAOIAHAqQAFAdAEARIAIggIAPg/QACgHAIAAQAFAAAEADQADADAAAFIgBAFQgJAngPAvQgDAKgHAMQgFAGgHAAQgMAAgIggg");
	this.shape_24.setTransform(23.9,-32.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgpBQQgQgRAAgZQAAggAQgSQARgSAZAAQAOAAAHAEIALAIQACgyACgRQACgKAIAAQAMAAAAALQgBARgEA3IgBAiQAAAnADAUIAAACQAAAFgDADQgEADgEAAQgHAAgDgKQgJAGgJADQgJADgJAAQgYAAgQgQgAgbACQgJAMAAAXQAAAPAKALQALALAOAAQAJAAAHgEQAEgCAJgHIADgEIAAgUIAAgOIAAgOQgEgJgIgEQgHgFgLAAQgSAAgKALg");
	this.shape_25.setTransform(1.4,-35.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgtA2IAAhRIAAgMIABgMQAAgMAKAAQAMAAAAAUQAWgWAaAAQAKAAAFAHQAFAIgBAOIAAAIQAAAPgMAAQgKAAABgMIAAgIIgBgKQgTACgJAJQgLAHgHAQIAAA/QAAAMgMAAQgJAAgBgMg");
	this.shape_26.setTransform(-11,-32.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgiAyQgQgRgBgbQgBgZAOgUQARgYAcAAQAXAAANAVQAJASAAAYQAAAZgNASQgQAVgYAAQgTAAgOgOgAgUgXQgIANAAAQQAAARAJAKQAIAHAKAAQAMAAAIgIQAKgKABgRQACgsgaAAIgBAAQgQAAgJAQg");
	this.shape_27.setTransform(-23.6,-32.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AAHAiIgEgbIgDgaIgKAWIgSAwQgBAFgDACQgEAHgHAAQgJAAgJgjQgEgSgEgeIgDgSIgBgRQAAgFADgDQAEgEAEAAQAJAAADAKIACARIACARIAHA0QANgjAOgvQADgNAJAAQAJAAAEAOIAHAqQAFAdAEARIAIggIAPg/QACgHAIAAQAFAAAEADQADADAAAFIgBAFQgJAngPAvQgDAKgHAMQgFAGgHAAQgMAAgIggg");
	this.shape_28.setTransform(-37.8,-32.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AAlA8QgFgFgCgEIgUAKQgJADgEAAQgcAAgMgPQgMgPAAgeQAAgbATgVQAUgUAaAAQAKAAANAGQAQAGAAAJQAAADgDADIgBAPIgBAZQAAAOACAIQABAGAGAPIADAGIAAACQAAAFgDADQgDADgEAAQgDAAgGgFgAgTgcQgNAPAAASQAAATAHAJQAGALAOgBQAKAAAIgEQAEgCAIgGQgEgfAAgPIABgLIACgNIgIgDIgFgBQgRAAgNAPg");
	this.shape_29.setTransform(-59.4,-32.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AggBCQgSgHAAgMQAAgEADgEQAEgDAFAAQAEgBAFAGQADADAKACIANABQAJAAAIgCQALgEgBgIQABgPgXgGIgLgCQgPgEgHgEQgJgGAAgNQAAgZAWgKQAIgEAOgDIAWgIQAFgDAFABQAGgBADAEQADADAAAFIACAKIABAKQAAAGgDADQgEAEgEAAQgHAAgCgFQgCgDgCgJIgbAIQgSAHAAALIAHACQAaAFAOAIQATAMAAAWQAAAUgRAKQgOAHgUAAQgPAAgOgEg");
	this.shape_30.setTransform(-78.8,-33.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgLBVQgDgDAAgGIAAgVIgBgUIABgcIACgaQAAgGADgDQADgEAFAAQAEAAADAEQAEADAAAGIgCAaIgBAcIABAUIAAAVQAAAGgDADQgDADgEAAQgGAAgDgDgAgHhAQgEgEAAgFQAAgGAEgEQAEgEAFAAQAGAAAEAEQAEAEAAAGQAAAFgEAEQgEAEgGAAQgFAAgEgEg");
	this.shape_31.setTransform(-87.5,-35.6);

	this.instance = new lib.pronounintro();
	this.instance.parent = this;
	this.instance.setTransform(-3.3,-95.3,1,1,0,0,0,351.9,276);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f().s("#000000").ss(3,1,1).p("Af83MMAAAAuZMg/3AAAMAAAguZg");

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#00FF66").s().p("A/7XNMAAAguZMA/3AAAMAAAAuZg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.instance},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.intro, new cjs.Rectangle(-205.8,-150,411.7,300), null);


(lib.goNext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,11.3).s().p("AhLAqQghgRABgYQgBgZAhgRQAfgSAsAAQAsAAAgASQAgARAAAZQAAAYggARQggASgsAAQgsAAgfgSg");
	this.shape.setTransform(22.8,8.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.502)").s().p("AhUhcICpBdIipBcg");
	this.shape_1.setTransform(25.1,20.4);

	this.blinker = new lib.general_buttoncolor();
	this.blinker.parent = this;
	this.blinker.setTransform(23.4,20.1,1.5,1.5,0,0,0,11.9,11.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,14.8).s().p("AhjA3QgqgXABgfQgBggAqgXQAqgYA5AAQA6AAAqAYQApAXAAAgQAAAfgpAXQgqAYg6AAQg5AAgqgYg");
	this.shape_2.setTransform(23.4,8.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("rgba(0,0,0,0.502)").ss(1,1,1,3,true).p("AAACxQhIAAg0g0Qg1g0AAhJQAAhIA1g0QA0g0BIAAQBKAAA0A0QA0A0AABIQAABJg0A0Qg0A0hKAAg");
	this.shape_3.setTransform(23.3,20.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["rgba(103,103,103,0.839)","rgba(134,134,134,0)"],[0.678,0.918],-0.8,0,0,-0.8,0,24.9).s().p("AitClQhEhFAAhgQAAhgBEhEQBEhEBiAAQBfAABCAwQBBAvAWCrQAVCskNAbQhiAAhEhEgAgICRQBGAAAygwIABgBIAEgDQA0g0AAhIQAAhJg0g0IgGgGIAAAAQgyguhEAAIgBgBIAAAAIgBAAIAAABQhEAAgyAuIgBABIgCACIgCABIAAAAIgBACQg1A0AABJQAABIA1A0IABABIACACQAzAxBGAAIAAAAIABAAIgBAAIAAAAQhGAAgzgxIgCgCIgBgBQg1g0AAhIQAAhJA1g0IABgCIAAAAIACgBIACgCIABgBQAyguBEAAIAAgBIABAAIAAAAIABABQBEAAAyAuIAAAAIAGAGQA0A0AABJQAABIg0A0IgEADIgBABQgyAwhGAAIAAAAIAAAAIAAAAIAAAAg");
	this.shape_4.setTransform(24.2,23.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},2).wait(1));

	// Layer 2
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#33FFFF").s().p("AipCqQhGhHAAhjQAAhiBGhGQBGhHBjAAQBjAABHBHQBGBGAABiQAABjhGBHQhHBGhjAAQhjAAhGhGg");
	this.shape_5.setTransform(24.4,21.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0099FF").s().p("AipCqQhGhHAAhjQAAhiBGhGQBGhHBjAAQBjAABHBHQBGBGAABiQAABjhGBHQhHBGhjAAQhjAAhGhGg");
	this.shape_6.setTransform(24.4,21.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.5,46.7);


(lib.UI = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//Menu button -----------------------------------------
		this.btn_menu.addEventListener("click", openMenu.bind(this));
		
		//volume buttons -----------------------------------------
		this.vol_dwn.addEventListener("click", volDwn.bind(this));
		this.vol_up.addEventListener("click", volUp.bind(this));
		this.vol_mute.addEventListener("click", volMute.bind(this));
		
		//Nav buttons -----------------------------------------
		this.btn_goNext.addEventListener("click", openNext.bind(this));
		//this.btn_goBack.addEventListener("click", openPrev.bind(this));
		
		//background music ---------------------------------------
		var bgm = createjs.Sound.play('bgmusic',{loop:-1});
		
		//volume vars -----------------------------------------
		var mute= false;
		bgm.volume = 0.2;
		var prev_vol = bgm.volume;
		
		//Menu function -----------------------------------------
		function openMenu(){
		
		 window.open ("../menu/menu.html","_self");
		}
		
		//volume functions -----------------------------------------
		function volDwn()
		{
			createjs.Sound.volume = createjs.Sound.volume -0.1;
			if(!mute){
				bgm.volume -= 0.1;
				prev_vol = bgm.volume;
			}
			console.log(bgm.volume);
			console.log(prev_vol);
		}
		function volUp()
		{
			createjs.Sound.volume = createjs.Sound.volume +0.1;
			if(!mute){
				bgm.volume += 0.1;
				prev_vol = bgm.volume;
			}
			console.log(bgm.volume);
			console.log(prev_vol);
		}
		
		function volMute()
		{
			if(!mute){
				mute = true
				bgm.volume = 0;
			}
			else{
				mute = false;
				bgm.volume = prev_vol;
			}
			console.log(mute);
		}
		
		
		//Nav functions -----------------------------------------
		
		function openNext(){
		
		 window.open ("pronoun_Scene1.html","_self");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// mute
	this.vol_mute = new lib.vol_mute();
	this.vol_mute.parent = this;
	this.vol_mute.setTransform(31.8,2.1,1,1,0,0,0,15,14.1);
	new cjs.ButtonHelper(this.vol_mute, 0, 1, 2, false, new lib.vol_mute(), 3);

	this.timeline.addTween(cjs.Tween.get(this.vol_mute).wait(1));

	// main
	this.instance = new lib.Copyright("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-220.6,376.5);

	this.btn_goNext = new lib.goNext();
	this.btn_goNext.parent = this;
	this.btn_goNext.setTransform(-1.7,335.3);
	new cjs.ButtonHelper(this.btn_goNext, 0, 1, 2, false, new lib.goNext(), 3);

	this.vol_up = new lib.vol_pos();
	this.vol_up.parent = this;
	this.vol_up.setTransform(-6.7,2.6,1,1,0,0,0,9,7);
	new cjs.ButtonHelper(this.vol_up, 0, 1, 2, false, new lib.vol_pos(), 3);

	this.vol_dwn = new lib.vol_neg();
	this.vol_dwn.parent = this;
	this.vol_dwn.setTransform(-28.7,2.6,1,1,0,0,0,9,7);
	new cjs.ButtonHelper(this.vol_dwn, 0, 1, 2, false, new lib.vol_neg(), 3);

	this.btn_menu = new lib.menu_main();
	this.btn_menu.parent = this;
	this.btn_menu.setTransform(-89.6,2.6,1,1.143,0,0,0,23.4,10.5);
	new cjs.ButtonHelper(this.btn_menu, 0, 1, 2, false, new lib.menu_main(), 3);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.5,1,1).p("AAYBrQgBgLgUgUQgQgRgKAAIAAh1QAKAAASgTQATgTAAgKg");
	this.shape.setTransform(-47.7,2.3,0.687,0.681);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AADBMQgQgRgKAAIAAh1QAKgBASgSQATgTAAgJIAADTQgBgKgUgUg");
	this.shape_1.setTransform(-47.7,2.3,0.687,0.681);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s("#000000").ss(1.5,1,1).rr(-0.75,-3.45,1.5,6.9,0.2);
	this.shape_2.setTransform(-52.2,2.3,1,1.003);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1.5,1,1).p("AAHAAQAAAJgHAHQgCAEgEACIAAgrQAEACACAEQACACACACQADAFAAAGg");
	this.shape_3.setTransform(-43.2,2.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgGgUQAEABACAEIABAAIADAFQADAEAAAGQAAAJgGAHIgBAAQgCAEgEABg");
	this.shape_4.setTransform(-46.5,2.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.btn_menu},{t:this.vol_dwn},{t:this.vol_up},{t:this.btn_goNext},{t:this.instance}]}).wait(1));

	// vol_frame
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s("#000000").ss(1.5,1,1).rr(-33,-12,66,24,4.9);
	this.shape_5.setTransform(-24.7,2.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_5).wait(1));

}).prototype = getMCSymbolPrototype(lib.UI, new cjs.Rectangle(-283.9,-13,331.7,399), null);


// stage content:
(lib.pronoun_intro = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		playSound("introwav");
	}
	this.frame_73 = function() {
		this.gotoAndPlay(0);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(73).call(this.frame_73).wait(73));

	// actions
	this.UI = new lib.UI();
	this.UI.parent = this;
	this.UI.setTransform(548,54.9,1,1,0,0,0,54,40.5);

	this.timeline.addTween(cjs.Tween.get(this.UI).wait(146));

	// Layer 4
	this.instance_7 = new lib.proboxingjump();
	this.instance_7.parent = this;
	this.instance_7.setTransform(223.6,272.8,0.345,0.345);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(146));

	// Layer 3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ADeHRIAAAJgADVHYIgOgDIAAAAIgKgBIAAAAQhSgNhTgPIAAAAQhcgQhdgUIAAAAIg8gNIAAAAQAHgFACgNIAAAAQACgMgBgMIAAAAIgBgGIAAAAQABgPgCgQIAAAAIAAgCIAAAAIACgWIAAAAQAKg/ACg+IAAAAQABgegEgeIAAAAQgEgegCggIAAAAQgEg+ALg+IAAAAQAHgngMgmIAAAAQgCgIAAgIIAAAAQAAgIgBgGIAAAAQAAgzgEgyIAAAAQgCgQgHgMIAAAAIAAgBIAAABIAAgBIAGgZIAAAAQADgVgGgPIAAAAQAHgEAKgBIAAAAIADAAIAAAAIAIgDIAAAAQBBgOBBgMIAAAAQBagRBagXIAAAAIA7gSIAAAAQATAAANAHIAAAAQgEAKAAALIAAAAIABBnIAAAAIAEAUIAAAAIABAQIAAAAIAAAGIAAAAIAAATIAAAAIAAAMIAAAAQACACAAAEIAAAAIAAAGIAAAAIAAAWIAAAAIAAAWIAAAAIAAAWIAAAAIAAAWIAAAAIAAAPIAAAAQABACAAAEIAAAAIAAAEIAAAAIAAAOIAAAAQACAIgCAMIAAAAQgCALADAKIAAAAQAGAXgHAUIAAAAQAIAwgDAzIAAAAQgBAKgEAFIAAAAQAIAJgBASIAAAAIgCAgIAAAAIAAB+IAAAAIABB9IAAAAIAAAhIAAAAIABADIAAAAIAAADIAAAAQABAFAAAFIAAAAIgBAHIAAAAIAAAGIAAAAIABAFIAAAAIgBACIAAAAIAAASIAAAAIAAAAIAAAAIAAAAIAAAAIAAAJIgJgCg");
	mask.setTransform(272.3,265.2);

	// Layer 2
	this.instance_8 = new lib.proboxingjump();
	this.instance_8.parent = this;
	this.instance_8.setTransform(292.7,272.5,0.345,0.345,0,0,180);

	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#0066FD","#CCCCCC","#FFFFFF","#FFFFFF","#FFFFFF","#996600","#FFCC00"],[0,0.184,0.788,0.937,1,1,1],-343.2,-44.4,256.2,-44.4).s().p("AAEAAIgQgCIAZAAIgBAFIgIgDg");
	this.shape.setTransform(293.4,312.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAWAGIgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIAAAAIgsgIIAWAAIARADIAHADIACgGIAEAAIABAHIAAABIgBAFIgCAAIgCgBg");
	this.shape_1.setTransform(292.5,312.8);

	var maskedShapeInstanceList = [this.instance_8,this.shape,this.shape_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape},{t:this.instance_8}]}).wait(146));

	// mirror
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(1.5,1,1).p("AgGkcIADBuIABAUAAFEdIACgB");
	this.shape_2.setTransform(252,275.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(5,1,1).p("ADwgyIghAHIgbAGIjyAyIgRAEAhtAXIhpAXIgBAAAjXAsIgYAH");
	this.shape_3.setTransform(272.1,222.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#CC9966").s().p("AAAAAIAAAAIAAAAIABAAIgBAAIAAAAg");
	this.shape_4.setTransform(290.6,289.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFCC").s().p("AAAgBIAAABIAAABg");
	this.shape_5.setTransform(251.7,260.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#010101").s().p("AARADIAAgBIAAgDIABAAIACAEgAAJADIAAAAIAAgBIgEABIgSAAIAagEIgaAEIgGAAIAagFQADgBADACIAAAAIAAAEIAAAAg");
	this.shape_6.setTransform(291.5,218.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("ADcHVIAAgHIAAgGIgCgkIAAgiIAAgXIAAgTIAAgcIgBgcQABgDAAgEIAAgFIAAgEIAAgCIgBgCIABgLQAAgMgCgIIAAAAIAAgkIAAgjIgBg5IABgGIAAgJQABgKgBgLIAAgOIAAgWIAAgJIAAgPIAAgFIAAgNIAAgWIgBgGIgBgBIAAgJIgBgrIAAAAIgBgBIAAgBQABgGgBgEIAAgsIAAgcIgBgXQABgDAAgFIgBgDIgBgZIAAgXIAAgDIAAgPIAAgCIAAgOIgDgpIgBgLQgEgQAAgVIABgOIABgUIgBgaQgBgQgFgRIAFAAQAAAHAEAHIAAAAIAAgOIACAAQACAHgBAIIAAAaQAAAeACAVIAAABIABAYIABA4IABAyIABAeIAAANIABA1IABAsIABAkIAAAgIABAnIAAAsIAAAaIABAjIABAoIAAAoIABAnIAAAbQgBARADAQQgDAIABAMIABAWIABAvIAAAgIAAAvIAAAPgACrHVIgxgKIhdgTIhDgOIgDgCIAAAAQgEABgIgCIgvgKIhUgSIgMgBQgEgBgDgBIACgFIACgBIAEgBIAAABQgBADAGABIAHAAQAVAGAWAEQAXAFAVADQAAAAABAAQAAABAAAAQABAAAAAAQABAAABAAIAAABIBiATIBfAUIAvAKIAkAIIAJACgAjIGBIAAgBQADgOgGgKIAAAAIABgMIAAgYIgBg1IgCg2IAAgWIgCgiIgBgfQgCgHABgKIAAgcIgCgwIgBgVIAAgVIADgsIAAAAIACAdIAAASIgBAMIABAWIABAhQAAAOADAQQgBAYABAcIABAZIABAZIABAZIABAnIABAuIABAlIAAARIAAASIgDAGIAAAAgAgZFJIAFgIIAAAAQADgBACgFIAAgBQADAAADgDIAAAAIAAAAQAEgIAGgEIAAgBQAEgHAGgGIAAAAQADABACgFIABgBIAGgIIAAgBQAAABAAAAQABAAAAAAQAAAAAAgBQABAAAAgBIAAAAQACgFAEAAIABAAQADgGAFgEIABAAQADgIAGgFIAAgBIAGgEIABAAIAFgLIACAAIAHgEIAAAAQgBAEgEAEIg6BAQgQASgRASgACmDjIABAAIAAABgAhpDUQADgFAGgFIAAgBQACgFAHgFIAAAAIADgFIABgBQAFgDAGgHIACgDQADgGAFgBQAHgLAJgLQAEgEAFAAQAAADgFAFQgeAggbAfIgEADIgBABIgBgCgAiDDTIAEgCIAAAAIAIgLIAAgBIAFgEIAAAAQAbghAfgeIADgDIAPgPIALgLIAKgLIAJgGIABgBQAAAEgFAFQgQAOgPAPIgMANIgBAAIgtAyQgOAPgPAOIAAAAIgBgCgAAxDAIAAAAIAAABIAAgBgABYC4IABAAIAAAAgABvCDIAAgCQAHgOANgHIAAgBQgKALgJANIgBAAIAAAAgAhfBWIAAgBQAAABABAAQAAAAAAgBQABAAAAAAQAAAAABgBIAAAAQAegfAfgdIA9g7IAGgEIAFgCIAAACIAAAAIgeAbIggAeIg9A9IgdAcQgDACgDAAQAKgKAMgNgAhWBlIAAAAIAEgCIAAgBQADgFAEgCIAAAAQACgEAEgCIABAAIAAAAQAMgRAOgLIABAAQAOgRAQgOIAAAAQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIAAgBIAcgbIAAABIAAgBIAdgdIABAAIADABIg6A6Ig9A8IgTATIAAAAQgBAAgBAAQAAAAAAgBQAAAAAAgBQABgBABgBgAjVjBIgCgBIgCglQAAgVgCgbIgBgaIAAggQAAgTgDgTIAAgBQABAAAAgBQAAgBABAAQAAAAAAAAQABgBAAABIAAAAIABADIAAACIACAwIACAkIABASQAAAJACAJQgCAMABAOIABALIAAAQQACADAAAEIgDAAgAh5jfIALgIQAdgXAZgZIAagaQAFgEAHAAQgFAIgJAHIhAA5IgSAOIgEABIgDgBgAh4jqIAAgBIA5g1IAAgBQAKgHAMgLQAKgKAIgJQAAgBAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQADgFAFgDIABgBQAEgBADABIAAAAIAAABIgbAbIgjAgIgnAkIgGAFIgGADgAhpktQAQgSATgOIABAAQAFgIAJgHIAdgbIADgCQAPgPAMgSIADgCIADAAQABAFgFAEIgHAIIgTAUQgVAVgVATIgWASIgVAQgAAulxQgDABgDgDQAFgFAEACIABAAIAAgBQAggbAbgdIAAAAIAGgEIACgBIABACQACAAgFAFQgcAcgfAaIgEAEIgDACIgDAAIAAAAgAjemBQAAAAgBgBQAAAAAAAAQAAAAAAgBQAAAAAAAAQAKgFAOgCIBjgTIAwgJIArgJIAkgIQATgDATgEIASgFQAIgCAKAAIACgCIAAAAQAYgDAbgHIAAgBIAOgCIAGAAIjyA0IgRAEIgdAGIgBAAIgOADIhIAOIgUADIAAAAIAAABIgBAAgAhEmgIDyg0IATAAIgIABIgBAAIgPAFIAAAAIgJAAIAAAAQgWAGgYAFIAAAAIgDAAIgvAJIg9AMIghAHIgiAGIgEABgACunUg");
	this.shape_7.setTransform(272.7,265.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["#0066FD","#CCCCCC","#FFFFFF","#FFFFFF","#FFFFFF","#996600","#FFCC00"],[0,0.184,0.788,0.937,1,1,1],-322.3,2.7,277.1,2.7).s().p("ADEHVIgJgBIglgJIgvgJIhfgUIhigUIAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQgWgDgWgEQgWgFgVgGIgIAAQgFAAAAgEIAAAAIgEABIgCABIABgCIAAAAIAAAAIAAgBIADgFIABgSIgBgSIgBglIgBguIgBgnIgBgYIgBgaIgBgZQgBgbABgZQgDgPAAgOIAAghIgCgXIABgMIAAgSIgBgcIgBgDIAAAAIAAgBIgBgTIABATIgPgJQADgEAAgFIABAAIAKgBIgDhuIAAgHIACgBIABAAIAAgEQAAgDgCgEIAAgPIgBgMQAAgNABgMQgCgJAAgKIgBgSIgCgjIgCgwIAAgCIgBgEIAAAAIgBgFIABAAIBqgWIAAgBIAdgGIARgDIAEgBIAjgHIAggHIA+gLIAugJIADgBIAAAAQAZgEAWgGIAAAAIAIAAIAAgBIAPgEIABAAIAIgBIAEgBIAAABIAAAAQAFAQACARIAAAaIgBAUIgBAOQAAAUAEAQIACAMIACAoIAAAPIAAACIAAAOIAAAEIABAWIAAAaIABADQABAFgCADIABAXIAAAcIABAsQABAEgBAGIgBABIABABIAAAAIABArIAAAIIABACIABAGIAAAVIAAAOIAAAFIAAAOIAAAKIAAAWIAAANQACALgCALIAAAIIgBAHIACA5IAAAiIAAAkIgBAAQADAJgBAMIAAAKIABADIAAACIAAAEIAAAFQAAAEgCACIABAdIABAcIAAATIAAAXIAAAiIABAjIAAAGIAAAHgAgNE7IAAAAQgCAGgDABIAAAAIgFAIIAAAAQARgRAQgTIA6g/QAFgFABgEIgBAAIgHAEIgCABIgFAKIgBABIgGAEIAAAAQgGAGgDAHIAAAAQgGAEgDAGIgBAAQgDABgCAFIgBAAQAAABAAAAQAAAAgBAAQAAABAAgBQgBAAAAAAIAAABIgGAIIgBABQgCAFgDgBIAAAAQgFAGgFAHIAAAAQgGAFgEAIIAAAAIAAAAQgDACgDABgAC0D3IABAAIABAAIgBAAgACpDkIAAAAIAAAAgAgsCQQgJALgHAKQgFABgDAGIgCADQgFAIgGADIAAAAIgEAFIAAAAQgGAFgCAGIgBAAQgFAFgEAGQAAAAAAABQABAAAAAAQAAAAAAAAQABAAAAAAIAEgEQAbgfAegfQAFgFAAgDIgBAAQgEAAgEAEgAiBDUQAAABAAAAQAAAAABABQAAAAAAAAQAAAAAAAAQAQgOANgPIAugyIAAAAIAMgNQAPgPARgPQAFgEgBgEIgBAAIgIAHIgLALIgKALIgQAPIgDACQgeAfgcAhIAAAAIgEAEIgBAAIgHALIgBAAIgEADgAAzDBIAAAAIAAAAIAAAAgABaC4IABABIAAgBIAAAAIgBAAgACFBsQgNAIgHAOIAAABQAAABABAAQAAAAAAAAQAAAAAAAAQAAAAAAgBQAJgMALgLIgBAAgAhdBXQgMANgKAJQAEAAACgCIAdgcIA+g8IAggeIAdgbIABAAIgBgCIgFACIgGADIg8A7QggAegdAeIgBABQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAIAAABgAhQBjIAAAAIgEACIAAABQgBABAAABQgBABAAAAQAAABABAAQAAAAABAAIATgTIA9g9IA6g6IgDAAIgBgBIgdAeIAAAAIgcAbIAAAAQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAABABIgBAAQgQAOgOAQIAAABQgPALgMARIAAAAIAAgBQgEACgCAFIgBAAQgEABgDAGgAgckwIgaAaQgZAZgdAWIgLAJQADACAEgDIASgNIBAg5QAJgIAFgHIgBAAQgGAAgFAEgAgMlQIAAAAQgFAEgEAFQAAAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAQgHAKgLAKQgLAKgLAIIAAAAIg5A1IAAACIAAAAIAGgDIAGgFIAngkIAjgfIAbgbIABgBIgBAAIgCgBIgFABgAAJmbIgDACQgLASgQAOIgCADIgeAaQgJAIgFAHIgBABQgTAOgQASIABAAIAVgQIAVgSQAWgUAUgUIASgUIAIgIQAGgEgCgFIgCAAIgBAAgAAzlwIADgCIAEgEQAfgaAdgcQAFgFgDgBIgBgBIgCABIgGADIAAABQgbAdgfAbIgBAAIgBAAQgEgBgEAFQACACADAAIADAAg");
	this.shape_8.setTransform(272.5,265.2);

	var maskedShapeInstanceList = [this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]}).wait(146));

	// btn
	this.instance_9 = new lib.intro();
	this.instance_9.parent = this;
	this.instance_9.setTransform(275,196.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(146));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(344.2,201.6,472.3,398.7);
// library properties:
lib.properties = {
	id: '4B1EFED6E6497D42B1E5FF63091AFB46',
	width: 550,
	height: 400,
	fps: 12,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"sounds/_12a.mp3?1507752883708", id:"_12a"},
		{src:"sounds/_12b.mp3?1507752883708", id:"_12b"},
		{src:"sounds/_13b.mp3?1507752883708", id:"_13b"},
		{src:"sounds/_13c.mp3?1507752883708", id:"_13c"},
		{src:"sounds/_16a.mp3?1507752883708", id:"_16a"},
		{src:"sounds/_18b.mp3?1507752883708", id:"_18b"},
		{src:"sounds/_19b.mp3?1507752883708", id:"_19b"},
		{src:"sounds/_2a.mp3?1507752883708", id:"_2a"},
		{src:"sounds/_3a.mp3?1507752883708", id:"_3a"},
		{src:"sounds/_4a.mp3?1507752883708", id:"_4a"},
		{src:"sounds/_6a.mp3?1507752883708", id:"_6a"},
		{src:"sounds/_7b.mp3?1507752883708", id:"_7b"},
		{src:"sounds/_9a.mp3?1507752883708", id:"_9a"},
		{src:"sounds/bgmusic.mp3?1507752883708", id:"bgmusic"},
		{src:"sounds/introwav.mp3?1507752883708", id:"introwav"},
		{src:"sounds/bgmusic_1.mp3?1507752883708", id:"bgmusic_1"},
		{src:"sounds/MenuPronoun.mp3?1507752883708", id:"MenuPronoun"},
		{src:"sounds/s_coolcheer.mp3?1507752883708", id:"s_coolcheer"},
		{src:"sounds/hesheit.mp3?1507752883708", id:"hesheit"},
		{src:"sounds/himherit.mp3?1507752883708", id:"himherit"},
		{src:"sounds/i.mp3?1507752883708", id:"i"},
		{src:"sounds/me.mp3?1507752883708", id:"me"},
		{src:"sounds/nominative.mp3?1507752883708", id:"nominative"},
		{src:"sounds/objectis.mp3?1507752883708", id:"objectis"},
		{src:"sounds/objectivecase.mp3?1507752883708", id:"objectivecase"},
		{src:"sounds/objectsof.mp3?1507752883708", id:"objectsof"},
		{src:"sounds/replaces.mp3?1507752883708", id:"replaces"},
		{src:"sounds/subjectis.mp3?1507752883708", id:"subjectis"},
		{src:"sounds/subjectof.mp3?1507752883708", id:"subjectof"},
		{src:"sounds/substitutes.mp3?1507752883708", id:"substitutes"},
		{src:"sounds/them.mp3?1507752883708", id:"them"},
		{src:"sounds/they.mp3?1507752883708", id:"they"},
		{src:"sounds/us.mp3?1507752883708", id:"us"},
		{src:"sounds/we.mp3?1507752883708", id:"we"},
		{src:"sounds/you.mp3?1507752883708", id:"you"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['4B1EFED6E6497D42B1E5FF63091AFB46'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;