(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 550,
	height: 400,
	fps: 12,
	color: "#FFFFFF",
	webfonts: {},
	manifest: [
		{src:"sounds/_12a.mp3", id:"_12a"},
		{src:"sounds/_12b.mp3", id:"_12b"},
		{src:"sounds/_13b.mp3", id:"_13b"},
		{src:"sounds/_13c.mp3", id:"_13c"},
		{src:"sounds/_16a.mp3", id:"_16a"},
		{src:"sounds/_18b.mp3", id:"_18b"},
		{src:"sounds/_19b.mp3", id:"_19b"},
		{src:"sounds/_2a.mp3", id:"_2a"},
		{src:"sounds/_3a.mp3", id:"_3a"},
		{src:"sounds/_4a.mp3", id:"_4a"},
		{src:"sounds/_6a.mp3", id:"_6a"},
		{src:"sounds/_7b.mp3", id:"_7b"},
		{src:"sounds/_9a.mp3", id:"_9a"},
		{src:"sounds/bgmusic.mp3", id:"bgmusic"},
		{src:"sounds/JinglePronoun.mp3", id:"JinglePronoun"},
		{src:"sounds/MenuPronoun.mp3", id:"MenuPronoun"},
		{src:"sounds/s_coolcheer.mp3", id:"s_coolcheer"},
		{src:"sounds/hesheit.mp3", id:"hesheit"},
		{src:"sounds/himherit.mp3", id:"himherit"},
		{src:"sounds/i.mp3", id:"i"},
		{src:"sounds/me.mp3", id:"me"},
		{src:"sounds/nominative.mp3", id:"nominative"},
		{src:"sounds/objectis.mp3", id:"objectis"},
		{src:"sounds/objectivecase.mp3", id:"objectivecase"},
		{src:"sounds/objectsof.mp3", id:"objectsof"},
		{src:"sounds/replaces.mp3", id:"replaces"},
		{src:"sounds/subjectis.mp3", id:"subjectis"},
		{src:"sounds/subjectof.mp3", id:"subjectof"},
		{src:"sounds/substitutes.mp3", id:"substitutes"},
		{src:"sounds/them.mp3", id:"them"},
		{src:"sounds/they.mp3", id:"they"},
		{src:"sounds/us.mp3", id:"us"},
		{src:"sounds/we.mp3", id:"we"},
		{src:"sounds/you.mp3", id:"you"}
	]
};



lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib.Youpointingguy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00CC33").s().p("AACAIIgMgMIAAgMIAGAAIAIAAIAAAKIAAAEIABACQAMAKgNAHg");
	this.shape.setTransform(-45,103.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgJAvQgEgBgCgEQgCgCABgDQgIgNAEgOIABgHQgBgVAIgTIAEgFIACgCIACAAIADAAIABAAIACgCQAPgCACANIABAGIABAJIABAPQgEgCgIABQgFACgDAEQgEANAJAIQAGAFAIgDIAAACIgBACIgCAFQgEAJgJABIgDAAQgCAFgFAAIgEAAg");
	this.shape_1.setTransform(75.2,-85.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#996600").s().p("AgtCPQgHgDgHgNIACgBIABgDIAAgFIAAgHIAWgnIACABQgVAtASAJIABgEQAQg2AMA6QgRAMACgUQABgJgBACQgIAbgJAEIgEAAIgDAAgAihCDIAAgIQAIgPAGghQAIgrAPglIAHgDQABAcgRApQAGBIAKhLQAGgrAPglQAJgEALACIAAACIgBAEQgZA1gLBHIAAADQgaAKgUAPgAhMB7IgBgDQgNgGgKgIQALgNgHgbIAAgFQASgkAKgrIAAgEQAOglAQAMQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQgFAWgHAUIgCACIAAAAQgLAugPAnQgGAVANABIAAgCIAAgEQAPgoAMgtQAAAAAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIAAgDIAAgIIAAgFIAAgFQAKgsAagbIACAAQAHAQgQAWIgBAEIgBADQgHAPgIAOIAAALIAAAEQAAAAAAABQAAAAAAAAQAAAAgBAAQAAABAAAAQgDABgEAAIAAABIgBAEQgDAxgUAgIAAANIAAADIgBAFQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAgBAAQgDAAgFgCgAiqBqQgLgPADgeIAAgEQAMgZAOgWIADAAQgBAxgTAwgAgfA9IAAgLQAIgMAAgRIAAgFQAXgVAOghIACABIgBADQgPA1gdAsgAAwgeQgGAAACgIIATgpIAJgVIABgEIAEgEQALgXgCATQgCARgEAQIgBAGQgHAcgTALIAAAEIgFAAgAgGgiQAGgdALgQQAJgNAKgEIABgBQABAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQANgNgMAWIgBAEIgDAIQgHAPgJAOQgLASgEAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAgABJgyQAEgPAGgOQALgbARgVIADAAQAFAOgIAZQANgbAUgUIACAAQgLAdgPAbIgNAYQgEAHgBgHIAAgIIACgHQgJATgQAJIgEABQgEAAACgJgAB+hDIAEgMQAOgoAfgVIACgBQAFgEgEAJIgHAQIgBADQgLATgJATIgEAIIAAAIIAAAEIgDABQgFADgDAAQgHAAgCgMg");
	this.shape_2.setTransform(61.8,-93.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#009933").s().p("AAtDCIgDgFIgbACIgBAAIgcgCIAAACIgCAAIgFgCIgigFIAAABIgBgBIgLgDIgMgDQgFgBgFgDIgBAAIAAAAIgBgBIgEgDQgLgBgJgHIgIgBIABAFIgCgFQgPgEgHgQIgHgSIALAjQgXgqgQguQgVg1gagUIABgHQAPABAIgHIABgDIgGgPIgGgPIgKgOQgFgHAAgKIAAgJIgOggIgHgPIAUgJIADAAIACAHIABAEIACgGQAAgDADgBIABgBIAAAAIAAgFQANgCAIAHIABgBIAKgEIAEgGQADgFAGgCQAPgDAHAMQAFAAAEADIALABIgCgIQADAEADAEIAfACIAAgCQAHABAGADIAVACIgCgGQAggBABgjIAEgCQAzgWAEA8IAIA5IAAAEQAMALAGASIACAAQAjBuA6BYQAAAAABABQAAAAAAABQAAAAABABQAAAAAAABQghAbghALIgGAEIgDABIgXADQgBAEgDADIgBAAIgCgBgACtB5QgGAEgOgGIgDgBQgHgIgFgJQgHgIgEgKQgKgZgFgaQgJgOgHgOIAAADQgUgegOgpIgCAAIgBgEQgNgmgLgnIAAgFQgCgUgGgQQAMAEAIAIIAAAAIAFgGIACgBIADgBIAAgBIAQABIADAAIAAAAIAJABIgBgBQAkgaAIAmIABAEQARArANAuIADAAQAoBAAfBDQADAEACAHIABADIAKAYIADAJQgGAQgRADIgGACQgLACgLAAQgOAAgOgDgACZB2IADAAIAAgDIgDgCIAAAFg");
	this.shape_3.setTransform(14.2,13.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFCC99").s().p("AiKQFIgBAAQhTAFhHgSQgTgFgSgGQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQgJgHgQAAIgEABQgiAMgjgZQAKAAAJgCIABgCIgEAAIgPABQgsADgjAIIgJAFQgEgHgPACIgFABQgiAIgbgFIgCABIgBABQgZgEgVgOIAAgEIAAgEIABgBIAEAAIABgDIgDAAQBAhGBegpIAYgMIATgMQAUgPAQgSIAVgVIAAgBIACgCQAzg2A1g0QBshqB0hhQAXgTAcgIIAHgDQADgCAAgCQABgFgEgHIgBgDQgTgigNgoQAdgcAugJIAEAAQAqAzATBFQABADgFAEIgBADIgwAxIgEAEIgCACQhaBahpBMIAAAEQgBAAAAAAQgBAAAAAAQAAAAgBABQAAAAAAAAQgkAggmAcIAAAEIgEABQg7Avg9AtIAAAAIgEADIhBAwIgUAPIAAACQABAHADAEIABAEQAAAAABAAQABAAAAAAQABgBAAAAQABAAAAgBIABAAQABgDAAgEIABAAIAAgEQAngfAngdIAEgBIAAgEIACgBQAPgFAMgKIAEAAIBUhHQAAAAABAAQAAgBAAAAQABAAAAgBQAAAAAAAAIAFgEQAqgcAlgjIABgDQB/hjB3hpQAGgFgBgLIACgBQAKgSgGgZIgGgRIgDgBQgagugYgvIADAAIAAgEQAggjAqgBIAFAAIAlBrIABACIAAABIAHASIAAABIATA2IAAADQAAAAgBABQAAAAAAAAQgBAAAAAAQAAABAAAAIg6A8IgBAAIgBABQhJBIhPBCIAAADQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAABQhPBGhZA7IAAAEIgEABQgwAhgtAnIgBAAIAAAFIAAAEIgDABQgDABgBACIADAEQAMAOASAKIACACIATAIQAtAQBDgHIAAACQgWAPgUAQQAAAAAAABQAAAAgBAAQAAAAAAABQgBAAAAAAIgEAAIhTAAIgYAAIgEgBIgHgBIgCAAIgCAAIgBgBIgEAAQgggEghgCIgBgCQgUgKgcgEIgEAAIgEAAQAOAIAQAGQAnAPAzADIAFAAIACAAIABAAIADAAIALAAIAFAAQA0AIA9gFIAAgDQAegeAogCIAEAAQARAlg5AFIAAADQgOAWAvgTQAHgDAIAAQAHADABAJIAAAEQgagCgeAOQgDAKAFgEQAlgTAIAeIAAACIABABIgEAAQg9gDAtAMQABAMgSAAQgJAAgOgEgAg5PbQgNgOgEgWIABgDQAHgZgUgRIAFgCIADgBQApACASAIQABABgDAEQgNAPANgGIAAgEIAAgEQAXgHAhADIADAAQAOADgBARIAAAEQgNASgcACQgKABgDAFQgMANgmAGIAAAEIgEgBgAjJhEQgbgOgmAQIAAgDQgIglgkAIIAAACQgWgTASgYQgBAAAAAAQgBAAAAAAQAAAAAAAAQgBgBAAAAQgIgXACghQAigDAUgQIADgBQAAgvAMgfIABgEQgPguAHg1QAGgrAHglQAUhoAchgQANgPASgGQAZgIAjAGQCSAZCAAmQA5AJA9AEIAEAAQAlgUALgtIABgFIgBgDIgcgtIABgDQAbgIARgSIgBgEQgFgXgGAPQAAABAAAAQAAAAAAABQAAAAAAABQgBAAAAABQgUAggwgMIgBgDQgRgOgHgYIAAgDIAAgPIAAgOIAEgFQAMgOAVgHIAAgDQAWgBAPAEIADABQAHANAIAHQASAQAbgQIAEgCIALgIIAEgBQAAgbgFgWIAAgFQAWglALgwIAAgEQARgBAFgPIACAAIAegJQAfgJAhgHIAEAAQAFATgNADQgcAJgVAZQgLAOgJAUQAHATAOgeIADgHQARgeAggOQgBAXABAXQgJgIgOABIgDADIgGAHIgBABIgBACIAAABIAAABIAAAAIgDAFIgFAGIgBABIgBAjIABAsIABACIABABIABACIAGAAIABAAIADgHQACAEAEABQALACADgGIADgBQAJgBAEgJIACgFQAFgCACgGIAAAAIACgCQAAATAXgSQAigXAgAPQAAApgZAPQgQAJgZAAIgDAAQgJgHAFARIAFAQQADAGgBAJIAAAEQABAmgIAfIgEABQg9AZgygWQgQgHgQgNIgCAAQgBgugSgbQACAoAKAhIAAAEQASAPATAJQAyAWBBgVIAEAAQADAWgTATIAAADIgFABQgyAZhVgGIgCABQgPAfgbASQAPARAigBIAEAAQAfAyAiAvIAAABIACACIABACIhLAIQABAEgEADQgDACgEAAIgKgBIgCAAIgBgBQgEgCgCgEQgCgCgBgDQgCgCgEAAIgBAAIgDgBQgMgBgKAFQiIBNhkBzQgZAdgXAfIgEAAQhVAHhUAJIgBgDIgUgaIAAgCQgcgWg5AIIAAgEIAAheIAfglIAdghIABgDICLh7QAlgjA+gNQgwgZhHgHQhCgGgtgLQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQgKAcgMAZIAAADIgDABQgEAXgHAVQgEAPgHAOIAAAFIAAADIAAAEIgkCfIgCAiQABAgAEAcIABAFQAvADAuAGIAAADQAJALAHANIAAAEIAAACQgGACgGAAQg9gQAcA3QAQAegTAJIAAACQAZADADAfIAAACQgrgEgiAKIgBgCgAJjjNIAAgHIAAAHg");
	this.shape_4.setTransform(21.7,4.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#FFFFFF","#996600"],[0,0.333],-699.8,-24.4,938.6,-24.4).s().p("Ao9EuQgbgGgXgJQg5gWglgqQgYgbAMgFQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBgBQgXgdgSgaIgDgEIgMgTIgBgDQgXgrAChCIAAgBIAAAAIACgTQAHgKABgPIAAgEIAEgOQAoiECEgbQA6gNBLAIQAWADAWAHQA/ATBBASQAsAWAigpIAUgZQAuhCBkgLIAFgBQgOALgTAFIgEABQgaAYgQAkIgDABQgKA/AvAEIAAgCQAigHASAFQABAAABAGIAAAFQgBADgEAAIgEAAIgrAHQhPAMhSAJIgEAFIlaA6IhuATIgDAAQgCgSgMgGIAAADIABACIAHAkIAAAAIAAAFIAAACIAAAFIgDgCIgDgBQgLgHgDgLQgCAXgTAGQAXALgBAkQgCArAQAXQgEg3gHg0IAAgDQAGAAAEAAIAAAAQAPAIgDAoQgCAjgGAcIgBACIAFAFIAHAAQACgVAOgMQgQgEAEglIAAgFIAVgEQgRgBgEgSQAagCAagFIAAgCIA2gHIAEgBIABAAQBEgMBFgKIAEAAIAAgEIABAAIAGgCIABAAIAPgDIABAAIAIgCIAZgEIAAgCIAxgIIABAAQA+gKA9gNIALgCIAMgDIAEgBIAagDIABAAIAEgBQAogGAmgKIAmgLIgMACQgLABgKAAIAAACIgIABIgBABIhQAMIAAAAIglAFIAAADIgFABIgNACIgBAAIh5AVIg4AJIAAAEIgEAAIgBABIgWAEIgQADIAAAAIgFABIiQAbIAAAAIAAAAIgDABIhBAKIgFABIgoAHIAAgEIAAgJIAAgBIAEAAIBngUIADAAICVgbIARgDIAagEIACAAIA3gJIB6gTIAAAAIAOgCIAAAAIAFgBIAlgGIABAAIBNgLIAEAAIAAgEIAHgBQAZgDADgEIgGAAIgMAAIgJAAIgCABIiDAUIgPACIixAdIgCAAIgDABIAAAAIi4AgIgDAAIhuAVIgDAAIAAgBIgBgQIAAgCIgBgGIAFAAIBugQIC4geIAFAAICxgfIAEAAIALgCQBAgLBDgJIABAAIABAAIAwgGIADgBIABAAIAAAEQADAOgHACIABAFIABABQAHAVARgEIggAKIgeAIQAAABAAAAQAAABAAAAQgBAAAAAAQAAABAAAAQgQAJgIARQgIAAgIACIgBAAQgdAGAKgHQAFgEABgCQADgGgeAHIgDABQgGAFgPgCIgFAAQgMABgMADIgHACIgSAGIgDABQg1AGgxAKIAAAAIgFAAIgLADIgDABIg5ANIgFABIgEABIgZAEIAAAAIgCAAIAAAAIgnAHIgFABIhpAbIgEABIhGAQQAjgDAkgGIADgBQA3gJA6gQQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAAAIAlgIIAAAAIAbgEIABAAIADgBIABAAIAAgDIAAAAIA+gLIATgDIAdgFIAEgBIgfALQgkAKgrAGIgEAAIgEABIgaAHIAAAAIgPAEIgYAGQg6AOg4AQIgRAFQgRAEgQAHIATgEIAfgHICWglQBrgXBxgVIAAgCQAWgEATgFIAEAAQAsgFAogGIAHADQAdA5A8AfIAAACQgUgDgaABIAAgDQghgLgjgLQgOgGgXAFQhrAbgmBkQgrByh6AlQgTAGgXAAQgUAAgWgEgApoALIgHACIgxAOIgFABIAugJIAIgBIAIgCICKgZIAAAAIADgBIAAAAIALgCIAOgDIAEAAIAJgCIAAgDQAfABAWgIIABAAIADAAIAAgFIACAAIAJgBIADgBIB8gSIAJgBIAYgEIAQgDIAFgBQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAABAAQAPgEgQgCIgFAAIgaAEIgQACIgKACIh8ATIgBAAIgFABIhOANIAAAEIgDAAIgCAAQgGAAgEACIgBABIgIACIgEAAQhFAOhCAPIAAAAIgBAAgAr7gzIABgFIgCAAIABAFgAgkAbQglgZgMguIAigPIAGAPIgBAAQAEAmAJAgIAAACIgDgBgALFhuQg3hkiCgFIgCABQgSAaAQAeIgEABQgoAMgBgtQgBgLAGgBIAMgCQgYgOAQgGIgNgQQAQgoAxgEIAEgBIAaAUIADABQBBAlBOAYIAEAAQAOAFAOACIAEABQAigBAbAHQAAAAAAAAQAAABAAAAQABAAAAABQAAAAAAABQgQAPgUAKIgBADIgDABQgcAYgeAYQgBAAAAAAQgBAAAAAAQAAAAAAAAQgBgBAAAAgACAimQAMAOAVgKIAFAAQCBgQCPgXIAAgCQAZgGAAATIAAAEIgEAAQhRANhXAHIAAAEIgDAAQgyANg8AEIgBACQgPAKgLAAQgTAAgEghgADeixQgFgCgHAAIAAgCQgGgCgGAAIgDgBIgBgCIAAgEIAAgFQA3gHBggRIAEAAQAIAAAFgEIADgBIBBgKQAAAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAAAQASgEAJAJIABADIgFAAQh2AVh6AUQB5gHB3gaIAFAAQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAAAAAQgKAHgOADIgDAAQhqAOhmATIgBgDgAiPjHIABgIQAGgKABgOIAAgEQAcgtA2gPIAAADQgKARgYAJQgeALgJAhQgIAegHAEIgBABQgDAAACgMg");
	this.shape_5.setTransform(-5.7,6.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AB0REQh9gFhpgcIgEAAQhVgHhWgFIgBgDIgEgFQAjgIAtgEIAPAAIAEAAIgBABQgJADgKAAQAiAZAigMIAFgBQAQAAAJAHQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABQATAGATAFQBGASBSgGIAAABQAqAJgCgRQgtgMA9ADIAFAAIgBgCIAAgBQgJgegkATQgFADACgJQAfgPAaADIgBgEQgBgKgGgCQgJAAgHACQguAUANgWIAAgDQA5gFgQglIgEAAQgoABgeAfIAAACQg8AGg0gIIgEAAIgMAAIgCAAIgCAAIgBAAIgFgBQgzgDgogOQgQgGgOgIIAFAAIAEAAQAbADAVAKIAAADQAiACAfAEIAEAAIACAAIACAAIABABIAIABIAEAAIAYAAIBQAAIAFAAQAAAAAAAAQABAAAAAAQAAAAABgBQAAAAAAAAQAUgRAWgPIAAgCQhEAHgqgQIgTgIIgCgBQgSgKgNgPIgDgDQACgDACgBIAEAAIAAgFIAAgEIAAAAQAtgnAvghIAEgBIAAgEQBZg8BPhFQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAIAAgEQBRhBBJhIIABgBIABgBIA5g7QABgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAAgDIgTg2IAAgBIgHgTIAAAAIgBgCIgmhsIgEAAQgqACggAjIgBADIgCABQAYAvAaAuIACABIAGARQAGAZgJASIgDABQABALgFAFQh5BoiABjIgBAEQgkAigpAdIgFADQAAABAAAAQAAAAAAABQAAAAgBAAQAAABAAAAIhUBGIgEABQgMAKgQAFIgCAAIAAAEIgDABQgoAdgmAgIAAAEIgCAAQABAEgCACIAAABQgBAAAAABQAAAAgBAAQgBAAAAAAQgBABgBAAIgBgEQgDgEAAgHIAAgCIAUgPIBBgwIAEgDIAAgBQA9gtA7gvIADAAIAAgEQAlgdAjgfQABAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAIAAgDQBphMBchaIACgCIAEgEIAwgyIABgCQAEgEgBgDQgShGgqgyIgEAAQgxAJgcAcQAMAoAUAiIABADQAFAHgCAEQgBADgCACIgHACQgcAIgXAUQh1BhhqBqQg1A0gzA2IgBACIgBAAIgUAWQgQASgUAOIgTANIgYAMQheAphABGIADAAIgBACIgFAAIAAABIAAAFIAAAEQAUAOAaAEIAAgBIADgBQAbAFAigIIAEgBQAQgDAEAIIABADIgEABQgvAOgzgKIgEAAQgUAIgPABIgCgJQAMgGgLgMIgBgDIAAgEIAAgKIgKAAIgGAAIAAgHIAIACIAIABIAAgTQCShKB1hlIACgCQA4gxAxg3IAmgtQBfh2CLhOIgBgDQgYhMgsg3IgEAAIgpAAQAAgBAAAAQAAgBAAAAQAAAAAAAAQgBgBAAAAIgEgBQgvgRgwgMIgBgDIhEioQAaAWAUA1QAQAuAXAqIgLgjIAIARQAEARAQAEIACAFIgBgFIAIABQAIAHAMAAIAEAEIABABIAAAAIABAAQAEADAGABIAMADIALADIABAAIAAAAIAhAFIAGACIACAAIgBgCIAfACIAAAAIAcgCIADAFQAAAAAAAAQAAAAAAABQABAAAAAAQABAAAAAAQADgDABgEIAXgDIADgBIAGgFQAhgKAhgbQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQg5hYgjhwIgDAAQgGgSgLgLIAAgEIgIg3QgEg8g2AWIgDACQgBAjggABIACAFIgVgCQgHgCgHgBIABACIgfgCQgEgEgCgEIACAIIgKgCQgEgCgFgBQgHgLgPADQgFACgEAFIgDAGIgKAEIgBAAQgJgGgNACIAAAEIAAABIgBAAQgCACgBADIgBAEIgBgDIgCgHIgEABIgTAHIgiAPQAMAwAlAYIADABIAAgBQgJgjgEglIABAAIAOAgIAAAJQABAKAFAGIAKAPIAFAPIAGAPIgBACQgHAIgQgCIgFAAIgDgBQhCgWhNgKQgNAFgOAHQhTAtgoBdQgtBnh7AdQgpAJgogNQgYgIgVgKQh1g3gyh7QgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgVgqgFg3QAFgoAJglQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAABAAIAAgCIAAgJQAehvBkgqIABgCQAYgHAZgFQBfgRBkAZIAFAAQAxAcA8ARIAEAAQAwgFAjgnIADgBIAAgEIAAgEQA8hRB/AOIAAAAIABAGIgBABQgNAhgoAHIgEAAQgkAeAKA2QAAABAAAAQAAAAAAAAQABAAAAAAQABAAAAAAQAyAFAGgmIABgDQANgPAYgEIAAgCQAAghANgVQAFgGAGgGIAAgDQAFjcA4inIAAAAIADgBIAAgEIAAgHQAOgTAZgHQAegIAtAKIEUA/QAqALA5gCIAtgnIADgCIAAgDQgLg4gtgWQAwAMATghQABAAAAgBQAAAAABgBQAAAAAAAAQAAgBAAAAQAGgPAFAXIABAEQgRASgbAIIgBADIAcAtIABADIgBAEQgMAtgkAVIgFAAQg9gFg5gIQiAgmiUgaQgigGgZAJQgTAGgNAOQgaBhgTBoQgHAlgGArQgHA1APAuIgBADQgNAgABAuIgDABQgVAQghAEQgCAhAIAXQAAAAAAAAQAAAAABAAQAAABABAAQAAAAABAAQgSAYAWASIAAgCQAkgHAIAkIAAAEQAlgQAaANIAAADQAigKAsAEIAAgCQgDgfgZgEIAAgBQASgKgPgeQgcg3A9AQQAGAAAGgBIAAgCIgBgEQgHgNgIgMIAAgDQgvgFgugEIgBgEQgDgcAAghIABghIAjifIAAgEIAAgEIAAgEQAGgOAFgQQAHgUAEgXIACgBIAAgDQAMgaALgbQAAAAAAAAQAAAAAAgBQABAAAAAAQABAAAAAAQAtAMBBAGQBJAHAxAYQg+AOgnAjIiLB6IgBAEIgdAhIggAlIAABeIAAAEQA5gIAcAVIABADIAUAZIABAEQBUgKBXgHIAEAAQAWgeAZgdQBlhzCIhOQAJgFAMACIADABIACgBQADAAADACQABADACADQACAEAEACIAAACQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAQgHABgGgFIgEgEIgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQhvA9hZBUQgVAVgUAWQgVAXgTAYIAAAEIAAAAIABAAQAhgKAogCIAEAAQAMgUAVgMIANgHIACgBQAjgOAUAPIAHAGQAHAFAAgLIgBgOIACAAQAZgCgKAQIgGAHQgEAEALgBQANgCADAGIAAACIgIADIgDAAIAAACIAEABQAVARAcgXQAJgHAFAHQAMAUgGATQAOgKALgOQADgFAHADQApAOgfAZQgDACALAAIADACQAMgGALgTQAJgOAMAMQANAOgNAPIgGAGIAHAAIAFAAQAKgIALgSQABgDAGACQAGADAEADQALAKgNAOQAQgBAKAEIAFACQgJAVgmATQAAABAAABQAAAAAAAAQAAABAAAAQAAAAgBAAQgpAfgnAgIgDgBQgshjiAgOQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAQgVATAXAbQgBATgoAEIgCgFQgRgngTAVIAAADQg/ALhCAHQAAAQAGAJIABAEQAWA9AbA7IAAAEQAtBFAoBKIABADQgLAfgaAOIgEAAQAAAAgBAAQAAAAgBABQAAAAAAAAQAAAAAAAAQgDAFgGgBIgFgBIADAFIABAEQAXA7AVA9IABADIAAAAIAGATIABABIATA8IgCAAIAAADIAAAAQhlBuhyBfQAAABAAAAQgBABAAAAQAAABAAAAQgBAAAAAAQhSBFhYA/IgBADQg4AjgrAvQAKAMAOAIQAKAFALAEQAiAMA2gDIA5gFIAAgEIAlAAIAEAAQAMgJARgEIgKgBIAAgCIABgCIAAAAIACAAIAjgEIANAKIgDAAQAWAUAPAZIABAEQADAUgMADQgsALgcAXIgEAAQgKAGgTgCIgEAAIgIAAIAAAEIgCAAIgBADIAAAAQgGAfgTAPIgFAAgACFO2IgEADQAUARgHAZIgBADQAEAWANAOIADABIAAgEQAngHALgNQAGgFAKAAQAcgCANgSIAAgEQAAgRgNgDIgEAAQghgDgYAHIAAAEIAAADQgNAHANgPQADgEgCgBQgSgJgogBIgBAAIgDAAgAqoikQiEAcgoCDIgEANIAAAEQgCAOgGAKIgCATIAAAAIAAACQgCBEAXAqIABAEIAMATIADAEQASAaAXAdQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAQgMAFAYAcQAlAqA5AWQAXAJAbAFQAwAKAkgLQB6gmArhyQAmhkBrgaQAXgGAOAHQAiAKAiAMIAAACQAaAAAUACIAAgCQg8gegdg8IgBgDIgEAAIgCAAIAAAAQgpAHgrAFIgEAAQgTAFgWADIAAACQhxAWhrAZIiWAlIgfAHIgTAEQAQgHARgEIARgFQA4gQA6gOIAYgGIAPgEIAAAAIAagHIAEgBIAEAAQArgGAkgMIAfgLIgEABIgdAEIgTADIg+AMIAAAAIAAAEIgBAAIgDABIgBAAIgbAFIAAAAIglAHQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAQg6APg3AKIgDAAQgkAGgjAEIBGgQIAEgBIBpgbIAFgBIAngIIAAAAIACAAIAAAAIAZgFIAEgBIAFgBIA5gOIADgBIALgDIAFAAIAAAAQAxgKA1gGIADgBIASgGIAHgCQAMgCAMgBIAFAAQAPACAGgGIADgBQAegEgDAEQgBACgFADQgKAHAdgGIABAAQAIgBAIAAQAIgPAQgKQAAAAAAAAQAAAAAAAAQABgBAAAAQAAgBAAAAIAegIIAggKQgRADgHgUIgBgCIgBgEQAHgDgDgNIAAgEIgBAAIgDAAIgwAGIgBABIgBAAQhDAIhAAMIgLABIgEAAIixAfIgFABIi4AcIhuAQIgFAAIABAGIAAACIABAQIAAAAIADAAIBugUIADgBIC4gdIAAAAIADgBIACgBICxgcIAPgDICDgUIACAAIAJgBIAMAAIAGAAQgDAFgZADIgHABIAAAEIgEAAIhNALIgBAAIglAGIgFAAIAAAAIgOACIAAAAIh6ATIg3AHIgCAAIgaAFIgRADIiVAaIgDABIhnAUIgEAAIAAABIAAALIAAAEIAogIIAFgBIBBgLIADgBIAAAAIAAAAICQgbIAFgBIAAAAIAQgEIAWgEIABAAIAEAAIAAgEIA4gKIB5gSIABAAIANgCIAFgBIAAgEIAlgFIAAAAIBQgMIABAAIAIgBIAAgCQAKAAALgCIAMgBIgmALQgmAKgoAGIgEABIgBAAIgaADIgEABIgMACIgLADQg9AKg+AKIgBAAIgxAIIAAADIgZAEIgIABIgBAAIgPADIgBABIgGABIgBAAIAAAEIgEAAQhFALhEAMIgBAAIgEAAIg2AKIAAACQgaAFgaABQAEATARAAIgVAFIAAAEQgEAlAQAFQgOALgCAVIgHABIgFgGIABgCQAGgbACgkQADgngPgIIAAAAQgEgCgGAAIAAAEQAHA0AEA4QgQgXACgsQAAgjgWgNQASgHADgXQADAMALAGIADACIADABIAAgEIAAgCIAAgFIAAgBIgHgkIgBAAIAAgCQAMAEACARIADAAIBugSIFag4IAEgBIAAgEQBSgJBPgMIArgHIAEAAQAEAAABgDIAAgGQgBgFgBgBQgSgFgiAHIAAADQgvgFAKg/IADAAQAQgkAagYIAEgBQATgGAOgKIgFAAQhkALguBCIgUAZQgiAqgsgWQhCgSg+gUQgWgGgWgDQgegDgbAAQgpAAgjAHgAFuEFIAFgCQASgDAFgQIgCgJIgKgYIgBgDQgCgHgEgEQgfhFgohAIgCAAQgOgugQgpIgBgEQgJgmgjAaIAAABIgJgBIAAAAIgDAAIgPgBIAAAAIgDACIgCAAIgFAHIgBAAQgIgIgLgEQAGAQACAUIAAAEQALAmAMAmIABAEIADAAQANApAVAgIgBgDQAHAOAKAOQAEAaALAZQAEAKAGAIQAFAJAHAIIAEABQAOAGAGgEQAYAFAagEgAHTiZQCCAFA3BkQAAAAABAAQAAAAAAAAQAAABABAAQAAAAABAAQAegYAcgZIADgBIABgCQAUgKAQgQQAAAAAAgBQgBAAAAgBQAAAAAAAAQAAAAAAAAQgbgHgiABIgEgBQgOgCgOgGIgEAAQhOgXhBgmIgDgBIgagTIgEABQgxAEgQAoIANAPQgQAHAYANIgMACQgGABABALQABAuAogNIAEgBQgQgdASgbIACgBIAAABgAB4hRIABgDQA8gDAygNIADgBIAAgDQBXgIBRgNIAEAAIAAgEQAAgSgZAFIAAADQiPAXiBAPIgFABQgVAJgMgNQAGA0ArgdgACZh3IAAACQAHAAAFACIABACQBmgSBqgOIADAAQAOgDAKgHQAAAAAAAAQAAgBAAAAQABAAAAgBQAAAAAAgBIgFABQh3Aah5AGQB6gTB2gWIAFAAIgBgDQgJgIgSADQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAAAAAIhBAKIgDABQgFADgIAAIgEABQhgARg3AHIAAAEIAAAEIABADIADABQAGAAAGACgAjAiuIAAAEQgBAPgGAKIgBAIQgDANAFgCQAHgFAIgdQAJghAegMQAYgIAKgSIAAgCQg2AOgcAtgABWo1QgKAfgMAZIgBAFQgFAdgKAYIgBAEIgBADQgIAxgPAqQADAtAUgaIAKgQQAFgMAKgHQAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBQBihRBchXIgEgBQhQgShbgGQAAABgBAAQAAAAgBAAQAAAAAAAAQAAAAAAAAgAEoEBIAAgFIACABIAAAEgArZBZIAxgOIAHgCIABAAIAAAAQBCgSBFgNIAEgBIAIgBIABgCQAEgCAGAAIACAAIADAAIAAgEIBOgNIAFAAIABgBIB8gSIAKAAIAQgCIAagFIAFAAQAQACgPAFQgBgBAAABQAAAAAAAAQAAAAAAAAQAAAAAAAAIgFAAIgQACIgYAEIgJACIh8ASIgDABIgJABIgCAAIAAAEIgDABIgBAAQgWAIgfgBIAAADIgJABIgEABIgOACIgLADIAAAAIgDABIAAAAIiKAbIgIABIgIACIguAJIAFgBgAs1ADIACAAIgBAFIgBgFgALPmnIAAAAIgBgBIgCgDIAAgBQgigvgfgyIgFAAQgiACgOgSQAagSAQgeIACgBQBUAGAzgaIAEgBIABgCQATgTgDgXIgFAAQhAAWgygXQgUgIgRgPIAAgEQgKgigCgnQARAbACAuIACAAQAPAMARAIQAyAWA8gZIAFgBQAHgfAAgmIAAgEQAAgJgCgHIgGgPQgFgRAKAHIADAAQAZAAAPgJQAagPAAgpQghgQghAYQgYARAAgSIgBABIAAABQgCAGgFACIAAgDIAAgBQgHADgHgGQgKgIAGgMQADgGAFgCQAHgBAFACQAIAEAAALIAAAFIACgCQAngcAyAUIABACQAHAngQAWQgJAMgPAHQgKAFgNADQgBAAABAGQACAWgHALIAAAEQAMBQgtAmIAAACQgZAGgPAMIgFAAQgnAFgsAAIgCAAIgDABQgLAUgTALQAVADAPALIABACIAAAAQAhAyAiAwQAEACADAEIAAABIAAABIgEABIgFAAIgBgBgAHkrJQgSgPgLgVIAAgEIAAgSIAAgTIAAgEIgCAAQgKgZgMgTIAAgEIAAgpQAMguAtgPIAEAAIAAgFQAJgFAIgGIADAAIAAgEQAvgXArgbQAdgSAagUQABAAAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBQA3gIAhgSQABAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIA5gGIAAgCQAEASgNAWIgDAAIgBAFQgFARgIAPIgCAFIAAADQAIAugMAcIAAA2IgBgKIgBgFQgCgNgOACIgEACIgBAAIAAAAIgDAAIgDAAIgBACIgEAEQgJAUABAWIgBAIQgDAOAHANQAAADABACIgDAGIgBAAIgGAAIgBgBIgBgBIgBgCIgBgsIABgjIABgBIAFgGIADgFIAAgBIAAAAIAAgCIABgBIABgBIAGgHIADgDQAOgBAJAHQgCgWABgXQggAOgQAdIgDAHQgPAfgHgUQAJgTAMgPQAUgZAdgIQANgDgFgTIgFAAQggAHgfAIIgeAKIgDAAQgFAOgRACIAAADQgLAxgVAlIAAAEQAEAWAAAcIgDAAIgLAJIgEACQgbAQgTgQQgIgHgGgNIgDgBQgPgEgXABIAAACQgUAIgNAOIgDAFIAAAOIAAAPIAAADQAHAYARAOIABADIgEgBgAJHteIAAAAIgBABIgVAnIAAAIIAAAEIgBADIgDABQAIANAGADQAEABADgBQAJgEAIgaQABgDgBAJQgBAUAQgMQgMg6gQA2IgBAEQgSgIAVgtIABgEIgCABgAHsusQgPAogIArQgGAhgIAOIAAAJIAAAEIACgCQAUgPAagKIABgCQAKhIAZg3IABgEIAAgCQgLgBgJADQgPAngGAsQgKBKgGhHQARgqgBgegAIlu9IgBAEQgJAtgTAlIABAEQAGAbgLAOQALAHAMAHIABACQALAFABgFIABgEIAAgEIAAgMQAUghAEgxIABgDIAAgBQADAAADgCQABAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIAAgFIAAgMQAJgOAGgPIABgEIABgDQASgXgIgQIgBgBIAAAAIgBgCIAAAAIAAAAIgBAEQgaAbgKArIAAAIIAAAEIAAAJIAAADQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAABAAAAQgLAtgQAoIAAAEIAAABQgNAAAGgVQAPgoALguIAAAAIACAAIABgEQAGgTAGgWQAAgBAAgBQABAAAAgBQAAgBAAAAQAAAAgBAAQgEgDgDAAQgMAAgKAbgAHRubQgPAXgMAZIAAAEQgDAdAMAQIAAABIAAgBQATgwABgxIAAgBIAAAAIgCABgAJ4vMQgPAggXAYIAAAEQgBASgIALIAAAMIAAAEIACgDQAdgsASg3IAAgDIAAgBIAAAAIgCABgAK3wTIgEAEIAAAFIgKAUIgTApQgCAIAHABIAEAAIAAgFQAUgLAGgcIACgGQADgPACgSQABgIgCAAQgCAAgGAMgAKIwHQgKAFgJAMQgLARgIAcQAHAJAOgYQAJgOAHgQIAEgIIAAgEQAMgWgMAOQAAAAAAABQgBAAAAABQAAAAAAAAQAAAAAAAAIgCABgALawlQgRAUgMAbQgFAOgFAPQgDAOAJgGQAQgJAJgTIgCAHIAAAJQABAHAEgHIAOgZQAOgbALgcIAAgCIgCABQgUAUgMAbQAIgZgGgOIAAAAIAAAAIgCABgAMbw0IgCABQgfAWgOAnIgEANQAEASANgKIADgBIAAgEIAAgIIAEgIQAKgTAKgSIABgEIAIgQQACgGgCAAIgCABg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-87.7,-109.2,175.5,218.6);


(lib.Youpointingarmstill = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Ai3ETIgegUIgBgBQgcgVgZgYQgRgPgPgSQgZgbgWggIgDgBQgtg6gqg9IgCgEIAKgBIABABQAuA8AuA9IABADQAWAgAaAbQAhAlAnAeIABAAIAbAUIADABQA8gmAvgyQAkgmAdgtQAdgyAdgzIAWgpIAZgzQAJgTASAKIAEAAQAbAMAqgEIABAEQAlAfAogKQAAgGgCgBQhCgagngxIAAgEQgIgZANgXIAMgFQAygTBMAPQBVARAlguQgWgIgrAGQgYADgTgDQhLgLhQAEIgiACQghAqgfArIgNATQgmA2gqAyQhZBihBBnQgBAAgBAAQAAAAAAAAQgBAAAAAAQAAgBgBAAQhJhRhAhWIgBgDIgCgCIgBAAIAAAAIgBgCIgCAAQgCgDgEAAIAAAAIgBgBIgIgBIgCAAIgCgBIgHgBIgLgBIAAAAIgDAAIgBgBQgHgBgIACIgGADIgBAAIgCgBIgBgBQgBAAAAgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQACgEAFgBQAIgCAHABIACAAIAFAAIAHABIAPACIAFABIABAAQAFAAAEADIAHADQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABIACACIACACIABABIAAADQA6BNBABJQAAABABAAQAAAAAAABQABAAAAAAQABAAAAAAQCLiaB1iwIARgaIARgaQABAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAQBXgpByAaQAoAJAggGQAtgJAQAVQACAfgaAHQAAAAAAAAQgBAAAAABQAAAAAAAAQAAABAAABQhAAJg/gEQgkgCgkgGIAAAAIAAADQAqALAaAeIABADQgKAhgTAUIAEACQAAAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAQAsAFgaAnIgCABQglAMgjgdIgBgEQg4AEgigTIgFgBIgnBHQgoBFgpBGQgWAkgbAfQgzA7hCAqQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAAAgBgBgADviiQAAABAAAAQAAABAAAAQAAAAAAAAQAAABgBAAQgkANAIAUIAFABQAfAFASgdIACgBQALgbgRAPIAAADQgigvgwATQAAABAAABQAAAAAAAAQAAABAAAAQABAAAAAAIA8AWg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFCC99").s().p("Ai7EFIgbgUIAAgIIAAAIQgogfghgkQgagcgWgfIgBgEQgug8gug8IAAgCIAlgDQgDgBgBgEQAAgGAFgDIABgBIAHgDQAHgCAIACIABAAIACABIADAAIAJABIAGABIACAAIALACIAAAAQAEABACACIABABIACABIAAAAIAAAAIACABIABACIACACQBABXBIBQQABABAAAAQAAAAABABQAAAAABAAQAAAAABAAQBBhoBahiQApgxAmg3IANgSQAfgsAhgqIAigCQBQgDBLAKQATAEAYgEQArgGAWAJQglAuhVgRQhLgPgzASIgMAFQgNAXAJAZIAAAFQAnAxBBAZQACABAAAGQgnAKgmgfIgBgDQgqAEgbgMIgEAAQgRgKgKASIgZAzIgWAqQgdAzgdAyQgdAtgkAmQgvAyg8AmIgDgBgADWh/IgEgBQgJgUAlgOQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAgBAAgBIg8gWQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBQAwgUAiAvIAAgDQASgPgMAbIgCABQgQAZgaAAIgHAAg");
	this.shape_1.setTransform(0.1,0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-43.9,-27.7,87.9,55.5);


(lib.youobsentstill = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#9900FF").s().p("AhgCCQgbgggIg+QgDgcAAhSQAAgfACgSQAAgUADgIQAGgQAOAAQAVAAAAAlIAACBQgBCDBbAAQBYAAAAjeIAAgVIAAgSQAAgOAFgKQAGgNAMAAQAWAAAAAeIAAAbIAAAbQAAD9iEAAQhCAAghgng");
	this.shape.setTransform(32.7,2.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#9900FF").s().p("AhuCIQgugoAAg+QAAhKAtg/QAzhFBJAAQBIAAAjAhQAlAiAABJQAABKgpA9QgwBGhJAAQg+AAgrglgAhMhJQgjAxAAA6QAAAqAfAbQAfAZAsAAQAzAAAjg2QAfgwAAg6QAAg1gXgVQgXgVg1AAQg0AAglA2g");
	this.shape_1.setTransform(-2,2.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#9900FF").s().p("AguCoQgHgHAAgJQAAgIAUgnIAbgxQgngzgLgbQgKgZgXgjQgggvgGgKQgDgGAAgGQAAgJAHgHQAHgGAJAAQALAAAHAKIARAbIAfAvQARAbAJAXQAHASAWAeIAyh4IAYgvQAGgPAOAAQAJAAAHAGQAHAGAAAKQAAAKgMAVIgOAZIgmBeQgWAygTAoIgaAxIgLAXQgHANgNAAQgIAAgHgGg");
	this.shape_2.setTransform(-35.1,2.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.9,-33.3,101.9,66.7);


(lib.yoububblestill = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgNCsQgJgLAAgJQAAgIAGgGQAHgGAIABQAGgBAJAMQAJAKAAAJQAAAJgGAGQgHAFgIAAQgHAAgIgLgAgPBQIAAgbIgBgaIABheIAAhfQAAgUASAAQATAAAAAUIAADyQAAAUgTAAQgSAAAAgUg");
	this.shape.setTransform(34.8,-6.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#9900FF").s().p("AAxBoQgbAPgiAAQgeAAgSgNQgVgOgEgbQgIg6AAgsQAAgeAGgmQADgTASAAQAJAAAHAGQAGAGAAAJQAAAKgDAWQgEAXABALQAAAlACAYQADAaAFAQIANAGQAHACAIAAQAbAAAhgJIAAgtIgBgpQAAgvAEgjQACgUAUAAQAJAAAGAGQAHAGgBAJIgDBTIAAAuIAAAvIABAPIABAPQgBAJgGAGQgHAGgJAAQgQAAgFgVg");
	this.shape_1.setTransform(18.4,-0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#9900FF").s().p("AhABcQgegdgCg0QgBgwAbglQAegtA1AAQAsAAAXAoQASAhgBAuQAAAvgZAiQgcAngtAAQglAAgagcgAgmgsQgOAaAAAdQAAAgARASQAPAPATAAQAVgBARgQQASgSABggQADhTgxAAQgeAAgSAeg");
	this.shape_2.setTransform(-5.6,-0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#9900FF").s().p("AguCoQgHgHAAgJQAAgIAUgnIAbgxQgngzgLgbQgKgZgXgjQgggvgGgKQgDgGAAgGQAAgJAHgHQAHgGAJAAQALAAAHAKIARAbIAfAvQARAbAJAXQAHASAWAeIAyh4IAYgvQAGgPAOAAQAJAAAHAGQAHAGAAAKQAAAKgMAVIgOAZIgmBeQgWAygTAoIgaAxIgLAXQgHANgNAAQgIAAgHgGg");
	this.shape_3.setTransform(-32,-5.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(3,1,1).p("AiJFYQisgViFhKQi3hnAAiSQAAiPC3hnQC4hnECAAQEDAAC3BnQC4BnAACQQAACRi4BnQieBZjXAM");
	this.shape_4.setTransform(0,-7.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AhCAtQABgGAEgEIgCgNQgEgbgQgYQgJgMgFgNQgDgGAAgFIABgFIAEgGIADgDIABgBQAGACAJABIADAAIAHAEQAHAEAGAHQAGAGAEAJIAEAIQAQAhABAhIAAABIACgBIAEgCQAJgFAHgHIAEgGIAGgDQAKgGAEgLIADgIIACAAIACgCIAOgWIATgcQARAEATgIIAAABIABAFIAAADQgBAGgDAIQgXAxglAlIgCAAQgLAQgQAMQgLAKgQAFQgFACgDAAIgFADIgIAAIgCABQgigDAKghg");
	this.shape_5.setTransform(-3.5,34);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhJFHIgFgIQgEgJgGgGQgFgHgHgEIgIgEIgDAAQgIgBgHgCIgBABIgCgBIgEAEIgDAFIgBAGQisgViEhKQi4hnAAiQQAAiRC4hnQC3hnECAAQEDAAC3BnQC3BnABCSQgBCPi3BnQieBZjXAMIAAgDIAAgDQAAgHgDgEIgBgBQgSAIgRgEIgDgBIgTAdIgNAWIgCACIgCAAIgCAIQgFALgKAIIgGADIgFAGQgIAHgJAFQgDgigQggg");
	this.shape_6.setTransform(0,-2.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-64.1,-43.6,128.2,85.8);


(lib.VertLine = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#333333").ss(1,1,1).p("AAKEiIgTAAIAApDIATAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgIEhIAApBIARAAIAAJBg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2,-30,4,60);


(lib.skiptomenu = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AATApQgLAGgMAAQgMAAgHgFQgJgGgBgKQgEgYABgQQgBgMADgPQABgIAHAAQAEAAADADQACACAAAEIgBANIgBANIABAXQABALACAGIAGADIAFAAQAKAAANgDIAAgSIgBgPQAAgTACgOQABgIAIAAQADAAADACQADADgBADIgBAhIAAARIAAATIAAAGIAAAGQABAEgDACQgDADgDAAQgHAAgCgJg");
	this.shape.setTransform(16.7,0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AAVAqIgDgTIgBgTIABgGIAAgJQAAgSgHgBQgKAAgHAMQgIALgFAOIgBAIIAAAJIAAAIIABAIQAAAEgCADQgDACgEAAQgDAAgDgCQgCgDAAgEIgBgIIAAgIIABgYIABgYIAAgIIAAgJQAAgDACgDQADgDADABQAIAAABALIAAAKQAPgUAOAAQAOAAAFANQAEAIAAAQIAAAJIAAAGIACATQACAMAAAHQAAAEgCADQgDABgEAAQgHABgBgJg");
	this.shape_1.setTransform(7.5,0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgdAmQgNgMAAgTQAAgVALgQQAMgQATgBQAOAAAJAGQALAFAAANQAAAJgKAHQgEADgOAFIggAQQAFAIAHADQAIADAIAAQAGAAAIgBQAKgDADgFQADgFAEAAQADAAACADQACACAAADQAAAKgPAGQgOAHgMAAQgSAAgNgKgAgRgWQgHAIgDAPIAbgLQAOgIAGgFQgHgIgNAAQgKABgHAIg");
	this.shape_2.setTransform(-2.2,0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgEAzQgCgCAAgEIgCggIgCgdQAAgJgDgGQgGADgHAHIgKALIgEAGIgBANIgBAPIAAAIIABAHQAAADgCADQgDACgEAAQgKAAAAgWIABgQIABgOIAAgOIgBgOQAAgUAJAAQADAAADADQADADAAAEIgBAFIAAAFIAAAJQAFgJAIgIQAJgHAHAAQANAAAEAOQAEgHAHgDQAHgDAIAAQAPAAAFAQQACADACAVIAGAxQABADgDADQgDACgDAAQgIAAgBgIIgDgbIgDgZQgBgGgCgGQgDgIgDAAQgEAAgJAGQgIAFgDADIABAQIACAWQACAOAAAJQAAAEgCACQgDADgEAAQgBAAgDgDg");
	this.shape_3.setTransform(-14.1,0.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(2,1,1).p("AkZh7IIzAAIAAD3IozAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AkZB8IAAj3IIzAAIAAD3g");

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAVAuQgMAGgOAAQgMAAgJgGQgJgGgBgMQgEgZAAgSQAAgNADgRQABgJAIAAQAEAAADADQADADAAAEIgCAOIgBAPIABAZQABAMACAHIAGADIAGAAQALAAAPgEIAAgTIAAgRQAAgVABgPQABgJAJAAQAEAAADACQADADgBAEIgBAlIAAATIAAAVIAAAGIAAAHQAAAEgCACQgDADgEAAQgIAAgCgJg");
	this.shape_6.setTransform(18.3,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AAXAvIgDgWIgBgVIAAgHIABgJQAAgVgIAAQgLAAgIANQgJALgFAQIgBAKIAAAJIAAAJIABAJQAAAEgDADQgCACgFAAQgEAAgCgCQgDgDAAgEIgBgJIAAgJIABgaIACgbIgBgJIAAgJQAAgFADgCQACgDAEAAQAJAAABANIAAALQARgWAPAAQAPAAAGAOQAFAJAAASIAAAKIAAAHQAAAIACAMQACANAAAIQAAAEgDADQgDADgEAAQgIAAgBgJg");
	this.shape_7.setTransform(8.2,0.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AggApQgPgMAAgWQAAgXAMgRQAOgSAVAAQAPAAAKAFQANAHAAAOQAAAJgMAIQgEAEgQAFIgjASQAFAIAJAEQAIAEAJAAQAHAAAIgDQALgDAEgFQADgFAEAAQADAAADACQADADAAADQAAALgRAIQgPAGgOAAQgVAAgNgLgAgTgZQgHAJgEARIAdgMQAQgJAIgGQgJgIgOAAQgLAAgIAJg");
	this.shape_8.setTransform(-2.4,0.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgEA5QgDgDAAgFQAAgLgCgXQgDgVAAgMQAAgKgCgGQgHADgHAHIgMANIgEAGIgCAPIgBARIABAIIABAIQAAAEgDACQgDADgEAAQgLAAAAgZIACgRIABgPIgBgQIgBgPQAAgWAKAAQADAAAEADQADAEAAADIgBAGIAAAGIAAAKQAFgKAKgJQAJgIAHAAQAPAAAEAPQAGgHAHgDQAHgEAKAAQAQAAAGARIAEAcIAHA1QAAAEgDADQgDACgEAAQgIAAgBgIQgCgLgCgTIgDgcIgDgNQgEgJgEAAQgDAAgKAGQgJAGgDADIAAASIADAYQACAQAAAJQAAAFgCADQgDACgEAAQgCAAgDgCg");
	this.shape_9.setTransform(-15.6,0.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#000000").ss(2,1,1).p("AE3CJIptAAIAAkRIJtAAg");
	this.shape_10.setTransform(0,0.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#00FFFF").s().p("Ak2CJIAAkRIJsAAIAAERg");
	this.shape_11.setTransform(0,0.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AATApQgLAGgMAAQgMAAgHgFQgJgGgBgKQgEgYABgQQgBgMADgPQABgIAHAAQAEAAADADQACACAAAEIgBANIgBANIABAXQABALACAGIAGADIAFAAQAKAAANgDIAAgSIgBgPQAAgTACgOQABgIAIAAQADAAADACQADADgBADIgBAhIAAARIAAATIAAAGIAAAGQABAEgDACQgDADgDAAQgHAAgCgJg");
	this.shape_12.setTransform(16.7,1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAVArIgDgUIgBgTIABgHIAAgHQAAgUgHAAQgKAAgHAMQgIALgFAOIgBAJIAAAIIAAAIIABAIQAAAEgCACQgDACgEAAQgDAAgDgCQgCgCAAgEIgBgIIAAgIIABgYIABgYIAAgJIAAgIQAAgEACgCQADgCADgBQAIAAABAMIAAAKQAPgTAOgBQAOAAAFANQAEAIAAARIAAAIIAAAGIACAUQACALAAAHQAAAEgCACQgDACgEABQgHgBgBgHg");
	this.shape_13.setTransform(7.5,0.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgdAlQgNgLAAgTQAAgVALgPQAMgSATABQAOAAAJAEQALAHAAAMQAAAJgKAHQgEADgOAFIggAQQAFAHAHAEQAIAEAIAAQAGgBAIgCQAKgDADgEQADgFAEAAQADAAACACQACACAAAEQAAAJgPAIQgOAFgMAAQgSAAgNgKgAgRgWQgHAIgDAPIAbgLQAOgIAGgGQgHgGgNgBQgKAAgHAJg");
	this.shape_14.setTransform(-2.2,0.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgEAzQgCgCAAgEIgCggIgCgdQAAgJgDgGQgGADgHAHIgKALIgEAGIgBANIgBAPIAAAIIABAHQAAADgCADQgDACgEAAQgKAAAAgWIABgQIABgOIAAgOIgBgOQAAgUAJAAQADAAADADQADADAAAEIgBAFIAAAFIAAAJQAFgJAIgIQAJgHAHAAQANAAAEAOQAEgHAHgDQAHgDAIAAQAPAAAFAQQACADACAVIAGAxQABADgDADQgDACgDAAQgIAAgBgIIgDgbIgDgZQgBgGgCgGQgDgIgDAAQgEAAgJAGQgIAFgDADIABAQIACAWQACAOAAAJQAAAEgCACQgDADgEAAQgBAAgDgDg");
	this.shape_15.setTransform(-14.1,1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#000000").ss(2,1,1).p("AEah7IAAD3IozAAIAAj3g");

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#0066CC").s().p("AkZB8IAAj3IIzAAIAAD3g");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},1).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12}]},1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-29.2,-16.9,58.6,30.5);


(lib.redheadeyesstill = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAiAJIABAEIAAABgAgcgNIgDABIAEgBIgBAAIACAAIgGAFIgCADQACgFAEgDg");
	this.shape.setTransform(-1.5,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAYAOIAAACIgFgFIAAgBIACAAIgBgDIgBgEIAAgBQAAgDAEgFIAAgDIAEgEIABgBIgCAEIAFgDQAWgDABAUQAAAKgJAFQgEACgFAAQgHAAgFgHgAgiAPQgDAAgEgBQgEgCgEgEIgDgHIgBAFQAAgHADgJIAAgBIACgDIAGgFIABAAIAGgBIAAAAIAAAAIADAAQAHAAAEADQAHAFAAAMQAAAIgIAFQgFACgEAAIgDAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5.4,-2.1,10.9,4.3);


(lib.pronounyouomeanword = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AA1BrIgGgwQgDgaAAgXIABgSIAAgVQAAgwgRAAQgZAAgUAdQgUAbgLAnIgDAVIgBAWIABATIABAUQAAAKgFAGQgHAGgJAAQgJAAgHgGQgFgGAAgKIgBgUIgDgTQAAgXAEgmQADgoAAgXIgBgVIAAgVQAAgJAGgGQAGgGAJAAQAVAAACAcIAAAaQAlgxAlAAQAjAAAOAfQAKAUABApIAAAWIgBATQAAASAFAdQAEAdABASQAAAJgHAGQgGAGgKAAQgTAAgCgUg");
	this.shape.setTransform(42,7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("ABGBwQgKgJgFgHQgVALgQAGQgQAGgJAAQgzAAgYgdQgWgcAAg4QAAgzAlgmQAkgmAxABQATgBAYALQAeAMAAARQAAAGgFAEQgCAJgBATIgCAvQAAAbAEAQQACAKAMAdIAFALIABAFQAAAIgGAGQgGAFgIABQgEAAgLgKgAgkg2QgZAcAAAiQAAAlANARQANATAZgBQATAAAPgIQAIgDAOgNQgHg4AAgdIACgUIADgZIgOgGIgJgCQggAAgZAcg");
	this.shape_1.setTransform(18.2,7.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AhKBfQgigcAAgxQAAg4AcgmQAegqAyAAQAiAAAYAMQAcAPAAAgQAAAVgZATQgLAHgjAPIhSAoQAMASATAJQASAKAWAAQAQAAAUgGQAZgHAIgMQAHgMAJAAQAIAAAGAGQAGAGAAAHQAAAZgnARQgiAPggAAQgwAAgegYgAgtg6QgRAVgJAnIBEgeQAmgTAQgOQgSgSghAAQgbAAgSAVg");
	this.shape_2.setTransform(-5.3,7.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgLCBQgHgGAAgKQAAgbgFg0QgFgyAAgaQAAgYgHgNQgPAIgQAQIgaAcIgLAPQAAAMgDAYQgCAaAAAMQAAAHACAMIACARQAAAJgHAGQgGAGgJAAQgZAAAAg5QAAgNACgZQADgYAAgOIgCgjQgDgXAAgMQAAgyAXAAQAIAAAIAHQAHAIAAAJIgBANIgBANIAAAXQALgXAXgTQAWgTAPgBQAjAAALAjQAMgQARgIQAQgIAWAAQAlAAANAnQADAJAGA1QAGAkAKBYQAAAJgGAGQgHAGgJAAQgSAAgDgTQgEgYgEgsIgIhCQgCgQgFgOQgIgTgIAAQgIAAgXANQgVANgGAHQgBAWACAUIAGA4QAEAkAAAWQAAAKgFAGQgHAGgJAAQgHAAgGgGg");
	this.shape_3.setTransform(-35.2,7.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.1,-33.3,110.3,66.7);


(lib.pronounyouoIword = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AhgChQgGgGAAgKQAAgJAGgHQAHgGAJAAQAOAAAhgFQACgSAAgXIgBglIgCgkQAAgxAHhMIgdABIgdAAQgJAAgGgGQgHgGAAgKQAAgVAVgCQASgCAwAAQAqAABCAKQAUADAAAUQAAALgIAGQgGAFgJAAQgOAAgVgDIgkgEQgFA/AAA5IABAmIABAmQAAAUgCARIBGgBQAJAAAGAHQAGAGAAAKQAAAJgGAHQgGAGgJAAIglABIglABQgNAAgcAEQgdAEgPAAQgJAAgHgHg");
	this.shape.setTransform(0.2,2.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-14.4,-33.3,28.8,66.7);


(lib.pronounheader = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAdA7IgDgbQgCgOAAgMIABgKIAAgMQAAgagKAAQgOAAgKAQQgLAPgGAVIgBAMIgCALIACALIAAAMQAAAFgDAEQgDADgGAAQgFAAgEgDQgDgEAAgFIAAgMIgBgLIABghIACgiIAAgMIgBgLQABgFADgEQADgEAFAAQAMAAABAQIAAAPQAUgcAUABQATgBAJASQAFALAAAWIAAANIAAAJQAAALACAPQAEAQAAALQgBAFgDAEQgEACgFAAQgLAAgBgLg");
	this.shape.setTransform(134.8,3.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAbA6QgQAHgRAAQgQAAgLgGQgLgJgDgPQgEgfAAgYQAAgQADgWQACgLAKAAQAFAAAEAEQADADAAAGIgCASIgBASIABAhQABAPADAIIAIAEIAIABQAOAAASgGIAAgYIAAgWQAAgbACgSQABgMALAAQAFAAAEAEQADADAAAFIgCAuIAAAZIAAAaIABAIIAAAJQAAAFgEADQgDADgFABQgKgBgCgLg");
	this.shape_1.setTransform(121.5,4.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgjAzQgRgRgBgcQAAgaAOgVQARgYAdAAQAYAAANAWQAKASAAAZQgBAagOATQgPAVgYAAQgVAAgOgPgAgVgXQgIANAAAQQAAASAKAKQAIAIALAAQALAAAJgJQAKgLABgRQACgtgcgBQgQAAgKASg");
	this.shape_2.setTransform(108.2,4.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AhRBfQgDgEgBgFIABgPIABgQIAAgXIABgWIAAgXIgBgYIgBgXIgCgXQAAgGAGgEQAEgFAHAAQAFAAALAOQAdAuAYAeQAcAiAjAgIAAgPIgBgPQAAg0gEggIgDgNQgDgIAAgEQAAgPANAAQAVAAAABQIAAAmIgBApIgCATQgCAMgKAAQgHAAgJgJQgygvg/hWIAAAbIgBAaIABAfIAAAeQAAAhgMAAQgHAAgEgEg");
	this.shape_3.setTransform(92.1,1.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAnA+IgJgJIgUAKQgJADgEAAQgdAAgNgQQgMgPAAggQAAgbAUgVQAVgVAaAAQAKAAAOAFQAQAHAAAKQAAADgCADIgCAPIgBAZQAAAPACAJIAIAWIADAGIAAACQAAAFgDADQgDADgFAAQgCAAgGgFgAgTgdQgOAPAAASQAAAUAHAKQAHAKAOAAQAKAAAIgEIANgJQgEgfAAgQIAAgLIACgNIgHgDIgGgCQgRAAgNAQg");
	this.shape_4.setTransform(68.1,4.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AghBDQgTgHAAgLQAAgFAEgEQAEgEAFAAQAEAAAGAGQADADAKACIAOABQAIAAAIgCQALgEAAgIQAAgQgXgGIgLgDQgQgEgHgEQgKgFAAgOQAAgZAYgLQAIgDAOgFIAXgHQAFgDAGAAQAFAAADAEQAEADAAAGIABAKIACAKQAAAGgEADQgDAEgFgBQgHABgDgFQgCgDgBgKQgJACgTAGQgSAIAAALIAHADQAaAFAOAIQAUALAAAYQAAAVgRAKQgPAIgTAAQgQAAgPgGg");
	this.shape_5.setTransform(47.8,3.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgoA1QgTgQAAgcQAAgdAPgWQARgXAbAAQATAAANAHQAQAIAAARQAAANgOAKQgGAFgUAGIgtAXQAHAKALAFQAKAFALAAQAJAAALgDQAOgEAFgHQAEgGAEAAQAFAAADADQADADAAAFQAAANgVAKQgTAIgSAAQgZAAgRgNgAgYggQgKAMgFAVIAmgQQAUgLAJgIQgKgJgSAAQgOAAgKALg");
	this.shape_6.setTransform(35.4,4.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgiA1QgRgQAAgaQAAgWAQgbQASgdAVAAQAMAAAPAGQATAHAAAKQAAAFgDADQgDAEgFAAQgDAAgDgCIgFgEQgHgGgRAAQgKAAgMAWQgLAVAAAMQAAARALAJQAKAIAOAAQAHAAAJgDIAOgIIAFgCQAEAAAEAEQADADAAAFQAAAJgTAIQgQAHgLAAQgXAAgRgPg");
	this.shape_7.setTransform(22,4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAnA+IgJgJIgUAKQgJADgEAAQgdAAgNgQQgMgPAAggQAAgbAUgVQAVgVAaAAQAKAAAOAFQAQAHAAAKQAAADgCADIgCAPIgBAZQAAAPACAJIAIAWIADAGIAAACQAAAFgDADQgDADgFAAQgCAAgGgFgAgTgdQgOAPAAASQAAAUAHAKQAHAKAOAAQAKAAAIgEIANgJQgEgfAAgQIAAgLIACgNIgHgDIgGgCQgRAAgNAQg");
	this.shape_8.setTransform(9.1,4.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgMBYIABgsIABgsIABgrIAAgsQABgMAJAAQAMAAABAMIgBAsIAAArIgDA8IgBAcQAAAMgKAAQgLAAAAgMg");
	this.shape_9.setTransform(-0.7,0.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AguBjQgDgEAAgFIAAgxIAAgvQAAgbgCgVIgCgZQAAgJADgGQAEgHAHAAQAFAAADAEQADACAAAGIAAADIgBAIQALgIAJgDQAJgEAIAAQAZAAAMAWQAJASAAAdQAAAYgOARQgPATgZAAQgLAAgOgFIgBA7QAAAFgDAEQgDADgFAAQgGAAgDgDgAgKg/QgHADgKAJQACAcAAAcQANAGAMgBQAPABAIgLQAHgJAAgPQAAgXgFgLQgGgLgLAAQgJAAgJAGg");
	this.shape_10.setTransform(-10.7,7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgoA1QgTgQAAgcQAAgdAPgWQARgXAbAAQATAAANAHQAQAIAAARQAAANgOAKQgGAFgUAGIgtAXQAHAKALAFQAKAFALAAQAJAAALgDQAOgEAFgHQAEgGAEAAQAFAAADADQADADAAAFQAAANgVAKQgTAIgSAAQgZAAgRgNgAgYggQgKAMgFAVIAmgQQAUgLAJgIQgKgJgSAAQgOAAgKALg");
	this.shape_11.setTransform(-24.1,4.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AguA4IAAhUIABgMIAAgMQgBgNALAAQAMAAAAAVQAXgXAbAAQALAAAEAIQAFAHAAAPIAAAJQgBAPgMAAQgKAAAAgMIAAgJIAAgKQgUACgKAJQgKAIgIAQIABBBQAAAMgNAAQgKAAAAgMg");
	this.shape_12.setTransform(-36.8,4.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#9C30CE").s().p("AAdA7IgDgbQgCgOAAgMIABgKIAAgMQAAgagKAAQgOAAgKAQQgLAPgGAVIgBAMIgCALIACALIAAAMQAAAFgDAEQgDADgGAAQgFAAgEgDQgDgEAAgFIAAgMIgBgLIABghIACgiIAAgMIgBgLQABgFADgEQADgEAFAAQAMAAABAQIAAAPQAUgcAUABQATgBAJASQAFALAAAWIAAANIAAAJQAAALACAPQAEAQAAALQgBAFgDAEQgEACgFAAQgLAAgBgLg");
	this.shape_13.setTransform(-56.9,3.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#9C30CE").s().p("AAbA6QgQAHgRAAQgQAAgLgGQgLgJgDgPQgEgfAAgYQAAgQADgWQACgLAKAAQAFAAAEAEQADADAAAGIgCASIgBASIABAhQABAPADAIIAIAEIAIABQAOAAASgGIAAgYIAAgWQAAgbACgSQABgMALAAQAFAAAEAEQADADAAAFIgCAuIAAAZIAAAaIABAIIAAAJQAAAFgEADQgDADgFABQgKgBgCgLg");
	this.shape_14.setTransform(-70.2,4.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#9C30CE").s().p("AgjAzQgRgRgBgcQAAgaAOgVQARgYAdAAQAYAAANAWQAKASAAAZQgBAagOATQgPAVgYAAQgVAAgOgPgAgVgXQgIANAAAQQAAASAKAKQAIAIALAAQALAAAJgJQAKgLABgRQACgtgcgBQgQAAgKASg");
	this.shape_15.setTransform(-83.5,4.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#9C30CE").s().p("AAdA7IgDgbQgCgOAAgMIAAgKIABgMQAAgagKAAQgNAAgLAQQgLAPgGAVIgCAMIgBALIABALIABAMQAAAFgDAEQgEADgFAAQgFAAgEgDQgDgEAAgFIAAgMIgBgLIACghIABgiIAAgMIgBgLQABgFADgEQADgEAFAAQAMAAABAQIAAAPQAUgcAUABQATgBAIASQAGALAAAWIAAANIAAAJQAAALACAPQAEAQAAALQAAAFgEAEQgDACgGAAQgLAAgBgLg");
	this.shape_16.setTransform(-96.1,3.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#9C30CE").s().p("AgjAzQgRgRgBgcQAAgaAOgVQARgYAdAAQAYAAANAWQAKASAAAZQgBAagOATQgPAVgYAAQgVAAgOgPgAgVgXQgIANAAAQQAAASAKAKQAIAIALAAQALAAAJgJQAKgLABgRQACgtgcgBQgQAAgKASg");
	this.shape_17.setTransform(-109.8,4.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#9C30CE").s().p("AguA4IAAhUIAAgMIAAgMQAAgNALAAQANAAAAAVQAWgXAbAAQALAAAEAIQAFAHAAAPIAAAJQgBAPgMAAQgKAAAAgMIAAgJIAAgKQgUACgKAJQgKAIgIAQIABBBQAAAMgNAAQgKAAAAgMg");
	this.shape_18.setTransform(-121.7,4.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#9C30CE").s().p("AgyBdQgEgDAAgFIAAgkQAAgRADggIACgyIAAgRQAAgMACgFQADgLAJABIALgBIASgBQAUAAATAQQAWAQAAAYQAAAfgXAPQgVAQgaAAIgPgBIgBBAQAAAFgDADQgEAEgEAAQgFAAgDgEgAgahHIAAAWIgDAxIAOAAQASAAAOgJQAQgMAAgTQAAgOgPgJQgOgJgNAAIgKAAIgHABg");
	this.shape_19.setTransform(-134.5,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-143.2,-19.4,286.4,38.8);


(lib.period = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgQARQgHgHAAgKQAAgIAHgHQAHgIAJAAQAJAAAIAIQAHAHAAAIQAAAKgHAHQgIAHgJAAQgJAAgHgHg");
	this.shape.setTransform(0.2,15.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7,-29.8,14.1,59.8);


(lib.HorizontalLine = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#333333").ss(1,1,1).p("AXWAKMgurAAAIAAgTMAurAAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("A3VAJIAAgRMAurAAAIAAARg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150.5,-2,301,4);


(lib.general_buttoncolor = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{resetRed:1});

	// timeline functions:
	this.frame_0 = function() {
		this.play();
	}
	this.frame_8 = function() {
		this.gotoAndPlay("resetRed");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(8).call(this.frame_8).wait(2));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#D5FFD7","#61EF01","#1DA400","#004A00"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgvAAgjgjQgjgjAAgwQAAgvAjgjQAjgjAvAAQAwAAAjAjQAjAjAAAvQAAAwgjAjQgjAjgwAAIAAAAg");
	this.shape.setTransform(11.9,11.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FFFFFF","#EC0000","#9D0000","#480000"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgvAAgjgjQgjgjAAgwQAAgvAjgjQAjgjAvAAQAwAAAjAjQAjAjAAAvQAAAwgjAjQgjAjgwAAIAAAAg");
	this.shape_1.setTransform(11.9,11.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},8).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,23.7,23.6);


(lib.Copyright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAbAHIgDgKIgEAKQgEAIgDAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBgBAAgBIgCgIIgBgHQgGASgCAAIgDgBIgBgCIABgCQADgFABgFIACgNQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAEAAACAJIADAKIACgGIADgJQADgEACAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAEAKIACAGIACAIIABACIgBACIgCABQgDAAgDgJgAgTANIgBgIIAAgGIgBgHIgFAAIgGAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAgBAAAAQAAgBAAgBQAAAAABgBQAAAAABgBQAAAAABAAIAFABIAEAAIAPAAIADgBIAEAAQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAABAAAAQAAAAAAABQAAAAgBAAIgOAAIAAAIIABAFIABAEIABAEIgCACIgCABQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAgBAAAAg");
	this.shape.setTransform(57.3,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgLAYQgGgDgBgEIABgDQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAIAEACIAEABIAFABIAFgBQADgBAAgDQABgGgJgCIgCgBIgIgDQgEAAAAgFQAAgKAIgEIAHgCIAIgDIAEgBIADABIABAEIABADIAAAEIgBADIgCABQgBAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIgCgFIgJADQgFADgBAEIADABQAIACAFACQAHADAAAJQAAAHgGAEQgFADgGAAQgFAAgGgCg");
	this.shape_1.setTransform(51,2.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgLATQgHgGABgKQAAgGAFgKQAHgKAGAAQAEAAAGACQAGACABAEIgBADQgBAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgDgBIgBgBQgDgCgGAAQgCAAgFAIQgDAHAAADQAAAGADAEQAEADAEAAIAGgCIAEgCIACgBIAEABIABADQgBADgGADQgGADgEAAQgHAAgGgFg");
	this.shape_2.setTransform(46.6,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgDAfQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAAAIAAgJIAAgIIAAgKIAAgIQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBIACgBIACABQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABIAAAIIgBAKIAAAIIABAJQAAAAAAAAQAAABgBAAQAAABAAAAQAAAAgBAAIgBABIgDgBgAgBgXQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQAAAAAAAAQAAAAAAgBQABABAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBAAAAgBg");
	this.shape_3.setTransform(43.1,1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAKAVIgBgJIgBgKIABgDIAAgDQAAgKgEAAQgFAAgCAFQgEAGgCAGIgBAEIAAAFIAAADIAAAFIgBADIgDABIgDgBIgBgDIAAgFIgBgDIABgMIAAgLIAAgFIAAgEIABgDIAEgBQAEAAAAAFIAAAGQAHgKAGAAQAHAAADAGQACAEAAAJIAAAEIAAACIABAKIABAJIgBADIgDABQgEAAgBgEg");
	this.shape_4.setTransform(39.5,2.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_5.setTransform(34.8,2.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AALAhIgBgLIgBgKIAAgDIAAgEQAAgGgEAAQgFAAgDADIgGAKQAAARgCACQAAABgBABQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDIABgBIAAgHIAAgHIAAgeIABgHIgBgFIAAgEQAAAAAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQAEAAAAAEIABAIIAAAKIAAAJIAAAEQADgFAEgCQACgDAFAAQAHAAADAFQABADABAGIABAJIAAAIIACAKIAAABQAAABAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIgDABQgEAAgBgDg");
	this.shape_6.setTransform(30,1.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgLATQgHgGABgKQAAgGAFgKQAHgKAGAAQAEAAAGACQAGACABAEIgBADQgBAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgDgBIgBgBQgDgCgGAAQgCAAgFAIQgDAHAAADQAAAGADAEQAEADAEAAIAGgCIAEgCIACgBIAEABIABADQgBADgGADQgGADgEAAQgHAAgGgFg");
	this.shape_7.setTransform(25,2.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgOATQgGgGAAgKQAAgKAFgHQAGgJAJAAQAGABAFACQAGADAAAHQAAAEgFADIgKAEIgOAHQACAEAEABQAEADACAAIAIgBQAFgCABgDQABAAAAAAQAAgBABAAQAAAAABAAQAAAAAAAAIADAAIABADQAAAFgIADQgGADgHABQgIgBgGgEgAgIgKQgDAEgCAGIANgFQAGgDAEgDQgEgDgGgBQgEAAgEAFg");
	this.shape_8.setTransform(20.3,2.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAaAgIgCgGIgBgIQgCgHgEgWIgJAYIgDAJIgDAIQgBAEgCAAQgDgBgBgDIgCgEIgBgFIgIgfIgCAHIgFAWIgCAMQgBAEgDAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgEQAAgHADgLIAFgPIADgOQACgKABgDQACgCADAAQACAAACADQACAEABAMQADAOAFAPQAFgPAEgSIACgGIACgHQABgDADAAQAEAAACAIIACAKQADASADAOIACAHIACAHQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgCABQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBgBg");
	this.shape_9.setTransform(13.8,1.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgQAUIAAgdIAAgEIABgFQAAgEADAAQAFAAAAAHQAHgIAKAAQADAAACADQACACAAAGIAAADQgBAFgEAAQgEAAAAgEIAAgDIAAgEQgHABgCADQgEADgDAGIABAWQAAAEgFAAQgEAAAAgEg");
	this.shape_10.setTransform(5.1,2.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_11.setTransform(0.5,2.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgBAZQAAAAgBAAQAAgBAAAAQAAAAAAgBQgBAAAAgBIgBgPIgBgOQAAgFgBgCQgDABgDADIgFAGIgDADIAAAGIgBAHIABAEIAAADQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABQgFAAAAgLIAAgIIABgGIgBgHIAAgHQAAgKAFAAIACACQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAADIgBACIAAAFQADgFAEgDQAFgEADAAQAGAAACAHQACgEADgBQAEgCAEAAQAHAAADAIIACAMIADAYIgBADIgDABQgEAAgBgEIgBgOIgCgLIgBgGQgCgEgCAAIgFADIgGAEIAAAHIABALIABALIgBADIgDACQAAAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBg");
	this.shape_12.setTransform(-5.2,2.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgBAZQAAAAgBAAQAAgBAAAAQAAAAAAgBQgBAAAAgBIgBgPIgBgOQABgFgCgCQgDABgDADIgFAGIgCADIgBAGIgBAHIABAEIABADQAAABgBAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABQgFAAAAgLIABgIIAAgGIAAgHIgBgHQAAgKAEAAIADACQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAADIgBACIAAAFQADgFAEgDQAFgEADAAQAGAAABAHQADgEADgBQADgCAFAAQAHAAADAIIACAMIADAYIgCADIgCABQgEAAgBgEIgCgOIgBgLIgBgGQgCgEgCAAIgFADIgGAEIAAAHIABALIABALIgBADIgDACQAAAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBg");
	this.shape_13.setTransform(-12.2,2.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_14.setTransform(-18.1,2.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgQAUIAAgdIAAgEIABgFQAAgEADAAQAFAAAAAHQAHgIAKAAQADAAACADQACACAAAGIAAADQgBAFgEAAQgEAAAAgEIAAgDIAAgEQgHABgCADQgEADgDAGIABAWQAAAEgFAAQgEAAAAgEg");
	this.shape_15.setTransform(-22.4,2.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgVAeQgFgGgBgMQABgMAFgKQAFgMAIgIQAHgEAEAAQAEAAAGACQAIAEAAADIgBADIgEABIgCgBQgHgDgEAAQgDgBgCAEIgGAGQgKAOAAAOQABAIACADQACAEAIAAQAGgBAGgFQAGgEACgLQgMABgGAEIgDABQAAgBAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQAIgEAXAAIADABIABACQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQgDANgIAJQgJAHgKABQgKgBgGgFg");
	this.shape_16.setTransform(-27.7,1.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgNAhIgBgDIACgJIAKgWQAFgOAHgIIABgBIgVAAIgJgBQgFAAAAgEQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAQAAIAPABIAIAAQAFAAAAACQAAADgDADIgEAFQgGAGgFAKIgHAPIgCAKIgEAKQgBABAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIgDgBg");
	this.shape_17.setTransform(-36.2,1.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AABAiIgHAAIgFgBQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQgBgEAIAAIACAAIABAAIAAgHIgBgGIABgPIABgRQgFAFgCAAIgDgBIgBgDQAAgDADgCIAHgGQACgEAEAAQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAADIAAADIAAAEIAAAEIgBAPIgBANIAAAGIABAGIAFAAQAAAAAAAAQABAAAAABQABAAAAAAQAAAAABABIAAADIAAADIgDABg");
	this.shape_18.setTransform(-41,1.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgSAXQgFgKAAgNQAAgMAGgKQAHgMAKAAQAMABAGAJQAGAJAAANQAAARgGAKQgGAJgMAAQgMABgGgMgAgLgRQgEAIAAAJQAAAMAEAHQAEAHAHAAQAIABAEgLQADgIAAgJQAAgMgDgGQgEgGgIAAQgGAAgFAIg");
	this.shape_19.setTransform(-45.9,1.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AANAhIgDgBIgHAAIgFABIgFAAIgFAAIgBAAIgCAAQgDAAgBgDIAAgFQAAgKAGgHQACgDALgFIAHgHQADgEAAgGQAAgDgDgCQgDgCgDAAQgDAAgDADIgGAEIgDACQgFAAAAgEQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAFgFAEgCQAFgDAEAAQAHAAAFAEQAGAEAAAHIgBAIIgEAHQgDACgIAFQgGAFgDADQgFAFABAHIAJgBIALAAIAGABQAEABAAADQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAIgDABIgDAAg");
	this.shape_20.setTransform(-51.3,1.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgeAAQAAgKALgJQALgKALAAQAOAAAHAIQAHAIAAAMQAAAJgJAKQgKALgMAAIAAABQgeAAAAgegAgOgOQgIAGAAAIQAAAMAGAFQAGAEAKAAQAJAAAIgIQAGgIAAgGQAAgJgEgFQgFgGgIAAIgCAAQgKAAgIAHgAgKAJQgGgEAAgFQAAgGAIgFQAGgFAFAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAIgCgBIgBAAQgDAAgEADQgEACAAADQAAABADACIAFABQABAAAEgCIAEgCIADAAIABADQAAADgEADQgGADgDAAQgFAAgFgDg");
	this.shape_21.setTransform(-57.7,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.3,-7.1,126.6,16.6);


(lib.Youredheadeyes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_22 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(22).call(this.frame_22).wait(1));

	// Layer 1
	this.instance = new lib.redheadeyesstill();
	this.instance.setTransform(1,0,0.698,0.698);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.46,scaleY:1.46,x:1.3},12).to({scaleX:1.09,scaleY:1.09,x:0,y:-0.3},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2.8,-1.5,7.6,3);


(lib.Youpointingarm = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_10 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(10).call(this.frame_10).wait(1));

	// Layer 1
	this.instance = new lib.Youpointingarmstill();
	this.instance.setTransform(-36.1,1.1,1,1,83.4,0,0,-36.1,1.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:1,rotation:8.4,x:-36},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.5,-10,65.1,93.6);


(lib.youobjtext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_89 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(89).call(this.frame_89).wait(1));

	// vert2
	this.instance = new lib.VertLine("synched",0);
	this.instance.setTransform(32.8,158.9,0.8,0.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(29).to({_off:false},0).to({startPosition:0},5).wait(56));

	// vert1
	this.instance_1 = new lib.VertLine("synched",0);
	this.instance_1.setTransform(-94.1,168.9,0.8,0.8);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(29).to({_off:false},0).to({startPosition:0},5).wait(56));

	// horz
	this.instance_2 = new lib.HorizontalLine("synched",0);
	this.instance_2.setTransform(0.1,175.9);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(29).to({_off:false},0).to({startPosition:0},5).wait(56));

	// period
	this.instance_3 = new lib.period();
	this.instance_3.setTransform(137.8,170.9);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(26).to({_off:false},0).to({_off:true},3).wait(61));

	// you
	this.instance_4 = new lib.youobsentstill();
	this.instance_4.setTransform(0,167);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({scaleX:1.44,scaleY:1.44,y:163},9).to({scaleX:1,scaleY:1,y:167},5).to({x:81.5,y:170},5).to({_off:true},10).wait(22).to({_off:false,x:91.5,y:152,alpha:0},0).to({alpha:1},8).wait(15).to({alpha:0},0).to({alpha:1},8).wait(8));

	// mean
	this.instance_5 = new lib.pronounyouomeanword();
	this.instance_5.setTransform(-37.9,166.8);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(22).to({_off:false},0).to({alpha:1},3).to({_off:true},4).wait(13).to({_off:false,x:-29.9,y:148.8,alpha:0},0).to({alpha:1},9).wait(23).to({alpha:0},0).to({alpha:1},8).wait(8));

	// i
	this.instance_6 = new lib.pronounyouoIword();
	this.instance_6.setTransform(-123.9,166.8);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(19).to({_off:false},0).to({alpha:1},3).to({_off:true},7).wait(5).to({_off:false,y:150.8,alpha:0},0).to({alpha:1},8).wait(32).to({alpha:0},0).to({alpha:1},8).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.9,133.7,101.9,66.7);


(lib.yoububble = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_6 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(6).call(this.frame_6).wait(1));

	// Layer 1
	this.instance = new lib.yoububblestill();
	this.instance.setTransform(0,0,0.057,0.057);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.65,scaleY:1.65},4).to({scaleX:1,scaleY:1},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3.6,-2.5,7.3,4.9);


(lib.YOU = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.yoububble();
	this.instance.setTransform(25.6,-103.8);

	this.instance_1 = new lib.Youredheadeyes();
	this.instance_1.setTransform(95.7,-34.7);

	this.instance_2 = new lib.Youpointingguy();
	this.instance_2.setTransform(-113.6,18.3);

	this.instance_3 = new lib.Youpointingarm();
	this.instance_3.setTransform(-9.3,-22.1);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(3,1,1).p("EAgjASLIAAFhMhBFAAAIAAkwMAAAgqnMBBFAAAMAAAApu");
	this.shape.setTransform(-11.2,-1.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFCC33").s().p("ABOErIgCAAIAAAAIgagDIgKgGIgBAAQg8gogehIIAAAAQgfhKAEhqIgBgBIgCgBQgEgEACgHIABgDIAAgBIAAgBIAAgCIgBgCQgBgiAKgcQARAdgMAeIAEAEQACAEAAAFQADAEADAFIAAABQAZAHALgmQAAgCAEgEQAKgJAMgCIAFgBIAAAAQABAyAGAqIABAEQAQAvAmAZIADABIAJADQANADATgBIAEAAQAfgUAUgdQAHgKAGgLIABgEIABADQALAdAQAYQAUAgAaAZIAEABQAIAQAUAEQAYAFAFADQgFAKgJAGQgYAUgMgHIAAgCQgbgNgeAJIgIACIAAAEIAIAAQAnADgnAYIgEACIAFAEIAAACQAQgZAhgKIACAAIgBABQgNAdgcARIgCABIAAAAIgIAFIgIADIgCABIgCABIAAAAIgBAAIgCAAQgNAFgQADIgDAAQgDAGgLgCIgDABIgBAAIAAAAQgXAJgaACIgCAAIgHAAIgMgBgAB8D3IgBAFQgDAfAaABQgUgHACgaQAbgCAJAKIABgEQACgMACgGQgWAGgXAEgAAEDdIgDAGQAAAAAAABQAAAAABAAQAAABAAAAQAAABABAAQAUAaAbATIAFAAQAHgBAGgCIALgFQALgGAGgKIgBgEQgGgcgWgNIgEgBQgMgDgKAAQgYAAgNATgADBDlIgIAEIgIACQADAGAFASQAGABADgCQAEgCABgFQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAABAAIAAgCQgMAAADgPIAEgEIAAgDIgEACgAg5B9IAIAwIAAAEIAcAZQACgTgEgIQgOgggVgWIABAEgAAuELQgPgPgMgSIgBgEQA9gCgYAkQgCADgGAAIgBAAgAA8DmIgBgDQgYgBgQgJQAAAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBQA3gVAKA+IAAAEIgXgdgAErCxIAAgCQgSgIgPgKIgCgBQgcgYgSghIAMgHQAdAvA3AUQASAHAMgJQAGgDAEgFQADgFADgHIABgFQgBgPgBgNQgGgpgTgbQAAgBAAAAQAAAAAAAAQgBAAAAAAQgBAAAAAAIgBADIgEAFIAAAEQgUAtAZgcQAEgGAAANQgBAiAJgSQABAAAAAAQAAABABAAQAAAAAAAAQAAAAAAAAQARAtgbAUIgEAAQhJgGgdhHIAPgTQATgXASgZQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAgBQgTAPgNAWIgIANQgMARgJgOIAHgJIABgDIAAgCQgNAMgDgWQACgMAIgHQgHADgEgCIgEgDIAEgEQAQgSANABIAGgEQAMgJgLgBIgLABIgEABQgMAEgJAIIgIAHIAAAfIAAAEIgKACQgEgRgCgRQAJgMAKgMIABgDIAEgCIAYgJIABgBIAOACIABAAQAYAGAUALQAdAQASAaIACACIAAABQATAeAFArIAAACIACAcIAAABIAAAFIAAAEIgJAOIAAAAIgBABQgGAIgHAHQAAAAAAAAQgBAAAAABQAAAAAAAAQAAABAAAAIgEABQgNADgRAAIgHABIgIgBgAgthRQANgLAFgWQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAABAAQAZgFAAAWIAAADQAAABAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQgMARgPANIAAAEIgDABIgFABQgMAAAEgagAhah+IAAgJQAXgSAegJIAEgBIADAAQAggBgWAWIgBAEQgXADgPALIgEAEQgHAKgGAAQgIAAgGgQgAhWjcQASgEAHADIADABQANgKAOgIIAAAAIAEAGQgHAdgJANIAAAAIgCADIAAAEIgEABQgKAFgIAAQgVAAACgrgAlSj8IADgBIBCgfIAEgBQAHgCAEgCQARgPgDAIQgHAPgPAKQgJAFgKADIg0AQIgmAPQAPgLASgJg");
	this.shape_1.setTransform(145.7,84.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#C6FFFF").s().p("EgghAVUMAAAgqmMBBDAAAMAAAAptQhrgThoANIgbADQhCAHhCAAIgrAAIgIAAIAIAAQAWgBAVgEQAegGAdgOIACgBIAAAAIAEgCIAFgDIAJgFIAAAAQAZgNAWgPQAXgQAUgRQAIgGAMgDQAFgLAJgIIACgBIADgBQAkgcgGhFQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAAAgBQgchKg8grIgDgBQgbgFgjACIAAAEIgNADQgWAIgCAaQgEAqgSAcQgbAog7AIIgBAAQgSgOgLgSQgMgUgEgWQgJg2gMgvIADgBQAQgegXgOIgCAAIABAAQARgbgIgmQgPACACgEIABgCQARg0gygKQAAAAgBAAQAAAAAAAAQgBABAAAAQAAAAAAAAIgDgGIACgCIABAAIABgBIABAAQAGgFgCgKQgNgzgkgfQAdghAWgoIAthOQAthMAOhsQhKhGhPhCQhPhChJhHQgjghg/gEQAAABAAAAQAAABgBAAQAAAAAAABQAAAAAAAAQgVAKgPAQIgDABQgQAIgCgNQAAgFABgHQAZgLATgQQApgeAUg0IABgEQASgIAXgEIAEAAQAegTACguIAAgEIgDgBIgBgBIgBAAQgNgLgGgTIAAgBIACAAQgDgfAMADQAAgPgPgeQAEAEAHgCQAAAAABAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIgBgCQgLgFgEgKQAdAAAHgHIgHgCQgWgEAMgLIAFgDQAVgDAIAJIAEABIAPAUIAJANIAAAEQAQAsAFArIABAEIAAACIABAIIABAAIABgPIAhgFQAHgtAVggQAKgRgKgPIgCgBQgFgOgGgKQAHABAEAGIAEAFQgSg0hCgNIgEAAQgvANghAbIgOANIgEAAQgTgBgNAFIAAAJIgIABIAAAAQgIgDgLAFQgmAOgNgSQAFgCACgDIABgDQAdgHAbgPIABAAQAVgLAUgQIABAAIAGgFIAEgDIgDAAIgCABIgMgNIACgBIAGgEIAIgEIAPgIIgRAEIgIACIgJADIgCABIgQgUIARgRIAAAAIANgQIABgCIAIgLIAAgDQgGAFgGAGIgBABIgBABQgGAGgEAIIgEABIgZAOIgFgIQAVgKANgQIACgCIABgCIAFgJIAEgJIAAgCIgJAKIgGAGIgVgOQAFgNADgPIAAgCIghAvIgCAAIgBACIAAABIgDAGQgEAEgCgJQAAAAABAAQAAAAABgBQAAAAAAAAQAAAAAAAAIAAgEQAEg0gbgFQAGAIABAJQAFBGgsAwIgBADIgDAFQgGAFgGgNQAAgIgEgEIgFgFQgKACAPAWIAHAJIAAACIgBAAIgJgFIgDgCIgcgUQAJAQAJAMIgYASQgjg1hEAYIAAAEIgEAAQgPAAgGAIIAHARIgbAMIAAACQALgEAPgCIADgBIAHASIgGADIgCACIgDADIADgBIADgBIAGgDQAsgQApAIIAAAUIgEAAIAAACQgpAMgmAOQglANgiAQQAMAIAdgQIAMgGQAUgKAIAEQgPAKABAXIACAAIACADIgBABIgBAAIAAAAIAAABIAAACIgBABQgIAKgBANIgCADIAAADIgFAIIAAADQgCAOABAOIABADIACABQACAGAFAEIgFAEIgEAEIgJANIAAABQgJAHgGAPQAeA9A4AkIAFACIAEADQAOALAJAQQgRAegwACIgEAAIgEgBIgZgLIAAgCQgVgHgbAAQgWAMgRAQQi5C2iIDnQAAAXANAJIADABQAYALAmgDIAEAAQCHhUBzhnIADAAQAeAFAIAaQAAAAAAAAQABAAAAABQAAAAABAAQAAAAABAAIABADQAlBMAXBcIgEABIjxCSIAAAEIgDAAQh1BRhkBiQgDAPAGAHIABADQBjCtCCCOQAkAnAmAlQg6AEgugYIgRgKIgGgEQhAgDg9gTQgbgHgbgCQjYgGjYgCIgrAGQh4AFh7ABQlDADlEAkIgiADIgCABIAAAAIg9ASIAAAEIg5AEQg2AEgkgMQgLgEgKgGQgOgHgKgMQArgvA6gjIABgDQBYg/BShFQAAAAABAAQAAAAAAgBQAAAAAAgBQAAAAABgBQByhfBlhuIAAAAIAAgDIACAAIgTg8IgBgBIgGgTIAAAAIgBgDQgVg9gXg7IgBgEIgDgFIAEABQAHABADgFQAAAAAAAAQAAAAAAAAQABgBAAAAQABAAAAAAIAEAAQAagOALgfIgBgDQgohKgthFIgBgEQgag7gWg/IgBgEQgHgJAAgQQBDgHA/gLIAAgCQATgWARAnIACAFQAogEAAgSQgWgcAVgSQAAgBABAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQCBAOAsBjIADABQAnggApgfQAAAAABAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQAlgUAKgVIgGgCQgJgEgQACQAMgPgKgKQgEgDgGgDQgGgCgBADQgLASgLAIIgEAAIgHAAIAGgGQANgPgNgOQgMgMgJAOQgLATgMAGQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAQgLAAADgCQAfgZgpgOQgHgDgDAFQgLAOgOALQAGgUgMgVQgGgGgIAHQgcAXgVgRIgEgBIgBgCIAEAAIAIgDIAAgCQgDgGgNACQgLABAEgEIAGgHQAKgQgZACIgCAAIABAOQAAALgIgFIgGgGQgVgPgjAOIgBABIgNAGQgVANgMAUIgEAAQgoACghAKIgBAAIAAAAIAAgEQATgYAVgXQAUgWAVgUQBYhTBwg8QAEgCACADIADAEIgBgEIAIAAQA1gFA1gHIAIgBQglgzgjg2IAAAAIgBgCQgPgLgVgDQATgLALgUIADgBIACAAQArAAAogFIAFAAQAPgMAYgGIABgCQAtgmgMhQIAAgEQAGgLgBgWQgBgGABAAQANgDAKgFQAPgHAJgMQAQgWgHgnIgBgCQgygUgnAcIgCACIAAgCIAAgDQgBgLgHgEIgCgPIAAg2QAMgcgIgtIAAgFIACgEQAIgPAFgRIABgEIADgBQANgWgEgSIAAACIg5AGQAAABAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAQghASg3AIQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBAAQgbAUgdASQgqAbgvAWIAAAFIgDAAQgIAGgJAFIAAAFIgFAAQgsAPgNAuIAAApIAAAEQANATAKAZIACAAIAAAEIAAATIAAASIAAAEQALAVASAPIADABQAuAWALA4IAAADQAAAAgBAAQAAAAAAABQgBAAAAAAQgBABAAAAIgtAnQg5ACgrgLIkTg/QgtgKgeAIQgZAHgOATIAAAHIAAAEIgDABIAAAAQg7CngEDaIAAADQgGAGgFAGQgNAVAAAiIAAABQgYAEgNAPIgBADQgHAmgxgFQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgKg3AkgeIAEAAQAngHAOghIABgBIgBgGIAAAAQh/gOg8BRIAAAEIAAAFIgDAAQgjAngwAGIgEgBQg8gRgxgbIgFgBQhkgZhgARQgYAFgZAHIAAACQhkAqgeBvIAAAJIAAADQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAQgJAlgFAoQAFA3AVAqQAAAAAAAAQAAABABAAQAAAAAAAAQABAAABAAQAyB7B0A3QAWAKAYAIQAoANAogKQB8gcAthnQAohdBTgtQANgHAOgFQBNAKBCAWIADABIAFABIAAAHIBECnIABAEQAyAMAvARIAEABQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIApAAIAEAAQAsA3AYBMIABADQiLBOhhB2IgmAtQgyA3g3AxIgCACQh1BliSBKIAAATIgIgBIgIgCQiagWiegTIgsAMQhuAfh1AGgAjDC6IABAAIgBgIgAWFT/IgBADIgBABQhfhahZhgQgggkg1gOIAAgDQgSgDgCgTQAzheAqhmIABgDIALgdIABgFQA+gYApgSIADgCIAAAIQgCAJAHgBQAbAVAJgdIAAgEQAlAAAVAQIAEAAQAvAHgWAbIgBADQAMAjACAiIACAAIAAAIIAABGIAAADQAEAcAEAFIAAABIABACIgCADQgCAGAFAEIgBAAQgDgBgBgDIAAAVIAAAEQgGDWCIBHIAEABIAdADQh3gFhxgbgAPGUNQhoiBhOieIgBgDQgjg9gugzIAAgDQCzhyDMhYIAIADQg3Ceg6CbQA9BuBjBJQBLA2BPA2IgCARQifgUinADgAUxJVIABgXQAAgSgDgSIgFgKIgDgIIgGgLIgFgGIgDgEQgHgBgCgGQgEgDgDgFIAAgEIgohaIgBgDQgghEAFhoQAOgWAIgfIABAAQAfAMAbAQIADABIABACQB/A+BpBTIAAADQgRCvhZBmIgEAAQghgCgYAHgAvngHQAPgqAIgxIAAgDIACgEQAKgYAFgdIAAgFQANgZAKgeQAAgBAAAAQAAAAAAAAQABAAAAAAQABAAAAAAQBbAFBQASIAEABQhcBXhiBRQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQgKAHgFAMIgKANQgHAKgFAAQgJAAgCgag");
	this.shape_2.setTransform(-11.2,-16.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00CC33").s().p("EgghADVIAAkuIAOAAQACAGADAAQCDATB1gsQALgEAKABQB/APB9AFIA1ABIAEABIAAAMIAOAOIACAJQgIAEgRADQAMAEAPgCQAPgCAUgIIAEAAQAzAKAugNIAFgBIgBgEIAIgFIAEAFIABAEQBWAFBVAHIAEAAQBpAcB/AFIAFAAQATgPAGgfIAAgBIABgCIACAAIAAgFIAIAAIAEAAQATADAKgGIAEgBQAcgXAsgKQAMgDgDgVIgBgDQgQgagVgTIADAAQApABAogFQA4gHA8gEQFTgXFVAEIA1AAQDRgEDQANQAfACAeAEQAbAFAbAGQBhAZBlABQhgAyiHgcQgMgDgMgHQgCgCgEAAIgOAHIgCAAIgDABIgBABIgBAAIgDAHQgEANAKAKIALAMIAIAIIAJAHQAPAMAUgCIAAABIgFABQgvAEguAIQAQAOAkgKQAYgGAegCQAbAQAngFIAcgBQAwgBAdACIAAAFQAwgQAqAPIAEABQAlgEAdAQIADAAQAWgDAEgHQADgGgQgLQgHgEAEgEQADgEgJACIgEABQgIADABgHQAGAAgCgJIgBgEQAFgZgJgLIgUgXQBDAJBDAFQCEAJBugIIABgCIACgBIABACQANASgOAIQgKAGgXABIAAAEQgRADgSAFQg2ARgpgZIgFAAQgSABgSADIgDABQgTAMASALQACAFACAAQALABgCABIgHADQgZANgeAGQAXAVAagMQAFgDgKATQAVgDAKgHQAPgJAGAGIACAEQgEAZAtABQAZAAAbgFIAUgRIABgEQBPgRBZABIAgABIAJAAQALABAMgGQgKg7g1gUQgagKgXgUIgTgSIABAAQAzAoBRAFQEPAQELgdIAAFfgA5WguIADgBIAAgFIAAgDQAVgEAUgGQATgFARgHIAAgDIgDABQgsAMg3AEIAAAEIAAACQgVAFgPAJIgEAAQAdAHAhgKgA32gyIAPgJIAYgOIACgCIgEgBIgIABIAAABIgZAJIgbAKIgEABQgIAEgNgCQAQAWAggUgAHjg/QgCASAWgGIAEgBIAAgDQAegCAagHQAbgHAWgKIAAgDIgDABQgTAMgWgJIgEAAQgrAGgmALg");
	this.shape_3.setTransform(-11.2,129.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#FFFFFF","#FFCC66"],[0,0.333],167,91.1,167,91.1).s().p("AAAAUQgEgMgEgMIgHgYIgBAAIAAAAIAKgCIAGAXQAHAQAKAQIgLAGIgBAAIgFgLg");
	this.shape_4.setTransform(167,91.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AALAoQgFgCgDgGQgDgHAAgJIAAgBIAAgCQAIALAOgGQAIgFAAgKQAAgTgWACIAAgBIABgHIAAAAIAHgIIAGgFQAGgGAIgCIASACQAIABAEAHIAAABIADAGIAFAKIAAABIAAACQAEALgCAKQgBAKgIAHIgOALIgIAEQgJAEgJAAQgIAAgIgEgAg6AnQgLgCgFgJIgCgDIABgCIAAgUIADAEQADAFAEABIABAEQACANARgCQAHAAAFgEQAIgGAHgHQADgDABgEIAEgdQgIgCgDgIQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAIABgBIADgBQAGgBAEAEIAAABQAGADABAGQgCAHAAAIIAAAEIAAAAQgGAKAAAOIAAADIgCADIgEAFQgQAPgTAAIgKgCgAhEgTIAAAAIAAAAgAhCgUIgCAAIACgGIABgBQACgFAEgDIABgCQAEgBADABQADABADAEQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABIgNAHIAAABIgGAAIgBAAIgCABIACgBg");
	this.shape_5.setTransform(98,-34.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF0000").s().p("AgoEnIgEgIIgMgQQgHgJgIgHIgDgEQgOgRgTgJIgFgDQgKAAgFgIIAAgCQAAgEADgCIAAAAIABgBIABAAIABAAIABgBIAKgHIAEgCIAAgCIADgDIAAAAIABAAIAAgBIAEAAIABgBQAIgCAJADQAEACAFAAIADABIAHACIADACQAMACAMADIACAAQAJAEAJAAQAYABAagDIADAAIAGgBIAOgCIAGgBQAKgEALgBQAQgBAOgJIAEgDQAIgHAKgDIACgBIAKgIQADgDAEgCQABgCACgDIABAAIABgBQAOABAGAMIACABQAIAGgBALQgBAHABAGIABAJQAAAHgDAGIgBADQgBAFgDAEIgCAGQgCAEgEADQgBAHgEAHIgCADQAAADgCACIgBACIgBAAQgDACgFgCIgBAAIgEgDIgDgDIgFgBIgGgCIgLgDQgNgDgNAAIgCgBQgXgCgVACIAAABIgBAAIgBAAIgCAAIgBAAQgKACgKAEIgJAEIgCACQgMAIgJAKIgWAXIgFABQgIAAgDgKgAgsEFIAAAAIAAAAIAAAAgACVD0IAAAAIgBAAIABAAgAhvgQIgEgBIgfgDIAAAAIgDgDIgSAAIgQgBIgBAAQgHAAAAgIQAAgEACgEIAIgKQABgGAGgGQALgJAKgMQAIgKAMgCIALABIAGgDQAHgCAGgFIALgIIACgBIABgBQACgDADgBQAEgCADgEIAWgUQADgGAGgCIACgBIAPgTQAFgJAHgIIAEgFQAIgLAJgJQAGgFAEgGIAEgGQAOgQAJgVIAEgIIAPgWIABgCIAEgEQAMABgDALQgBAFgDADIgDADQgNASgJAUQgEAIgFAGQgGAJgFAJIgKASIAAAAIgBADQgBAIgGAGQgFAGgCAGIgEALQgDAFAAAGIgBAWQgBAIADAIIAFATIABAFIAGAHIABACIADAFIABABQAHAFAIADIADABQAFAAAEADQAHgBAHABIAFADIAHgBQAMgBALAEIACABIAAACQAEADgBAFIgBAEIgBAAIgCADQgUAHgVACIhJAGIgZABIg8gCgAimgnIAAAAIgBAAIAAAAIABAAgAhmkOQgDgFAEgEIAHgJIABgEQAAgCACgCIABAAIABgBQALAAAAALQgBAEgCADQgFAHgGAFIgEABQgEAAgCgEg");
	this.shape_6.setTransform(101.7,20);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF6400").s().p("AASCNQAJgDAIgWIAIgQIAEgKIACgDIAGgLQAIgQgLAcQgCAFAAAJIgCAAQgOAegLAfgACvApIgDAAIgBgEIgBgCIAAAAIgDgGIgHgNQAJAHAHAIQAiAkANA7IADAAIghAFQAAgugSgsgABGCCIAAgEIAAgEQAIgXgEgiIAAgEIAAgEQAWADgFAhIAAAFIAAADQAFAdgXAAIgDAAgAAGB2QAWgjAPgpIAAgBIACgFIABgEIACAAQAAAPgDANIAAAAQgJAjgcAZgAicBcQgIAAgLgUIgBgDIAZgVIAdgWQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQgEAMgSAUIgDABQgCAbgGAGQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAIAAAAgACpAIIAAgCQgLAAACgIIAKgBQAMgBAEAHIADAAIAQAWQAbAhgGAbIgDABQgagpgcglgAjlBNIAAgEQAdgeAtgOIADgBIgBACQgJAQgWAUIAAADQgegDgMAOIgBABgADFAAIAMAAIAEAAQAVAEALANIABADQACAWgFAMIgBADQgegJgPgwgAgfA0IACgDQAMgMAQgEIABgBQAVgFARgHIAAAAQgGAAgFgBQglAFgYAHQAXgSAjgFQACgCAEAAIABAAIAHgBIAOgEQAJgBAHACIACACQAEgEAGAAQATgTAYgOIAFgCIAAgBQAQgKAbgBIASAAIADAAQAeANATAYIABAEIgEgBQgXgYgngIIgEAAIgcADQACADgEAEIgEACQgbAOgWASIgIAHQgGAEgHACIgGAAQgEAAgEABQgFACgGgBIgBgBIAAABQAJACgIAEIgBACIgEAAQgWACgQAGQgRAGgNALgAhEAjIABgFIADgEIABgBIAHgKIAAgCIAFgNQABgBAAgEIgCgNIgDgHQgGgKACgLQACgPALgLQAFgGAEgHIAHgLIABgCIABgCQACgFADgFIACgCQABgLAJADIABABIAUgOIACAAQAJgJAGgMIADgIIAVAPIgBAAIgEADQgPAMgQAFIgBACQgGAIgHAGIgEAGQgDAEgFAAQgEAGgGAEIgCAFIgBAAIgOAXIACAAQAAgBAAgBQAAAAABgBQAAAAABgBQAAAAABAAIACgBIABAAQAGgFAHgCQAGgIAKgBQAHABgFAHQgBADgBABIgYAPIgDADQgFAKgLgBQAAgBgBAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIgBgCIgBAHQgBAFACAFQAIALgBAOIAAAHQAFAMgLALQgFAFgDAHIgCACQgDADgEABIgBAAQgEAAAAgFgAhVAdQAGgGAHgDIABAIQgGADgEADgAg8AHQgOgYgaAQIAAAAQgHACgIAHIgEAAIgZAAIAAgTIAAgCQgRgNgTgJIgEAAIgVAAIgXAAIgFAAIgBAAIAAACIAAAAIgFADIgHgRQAFACAIABQALACARAAIAVgBIAEAAQAYANAYAJIAAgCQgXgVgmgHIgDAAIgBgDIgEgCIADgCQAPgPAeAXIAaAVIABABIATARIgBgDIgJgRIAXgRQAMASANAKQAGAEAFAWIAAABIAAABIAAAAIgCgBgAjtgXIACAAIANgCIAlgCIABAAIgBADQgRAEgOAGIgOAIgADJgKIgEgBIgFAAQgfgCgZgKQAGAAAFgBIABgDIApAAIADAAQAqAUgPAAQgFAAgNgDgAgJgXIADAAQAOgOASgNIAAAAIACgBIABAAIACgCIADgCIABgBIACgBIACgBIADgDIACgBIAFgDIACgBIABgBIAAAAIAEgCIAFgDIALAOIgIADIAAAAIgHACIgIADIgFADIgMAFIgCAAQgUAJgQAKIgDACgAgqgfIAIgJIATgVQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAAAAAIAEgBQAPgJAPgLIAEgDIAFgEIAAAAIABgBIAIgHIAQAUIgDACIgEABIgCABIgBAAIgDACIgBABIgCAAIAAABIAAAAIgDABIgCABIgDACIgMAJIgCABIAAAAIgCACIgBABIgOAOQgHAKgHAEQgGADgGAAQgIAAgIgIgAgNhYIARgRQAAAAABgBQAAAAAAgBQAAAAAAAAQABgBAAAAIADgBIADgBIAIgEIAFAJIAAAAIgBAAIAAAAIgHAEIgcAQIgCABIAAgEg");
	this.shape_7.setTransform(114.3,-47.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFCC99").s().p("AB6NiQgFgBgCgEIgDAAIgBgBIgBgBQgBgDACgDQACgFAEgDQgIACgIAFQgEACgDgBIgDgCIAFgFQAMgNACgFIgGABQgNAEgMAGQgXgHAJgFIgBAAQgKgCgIgFQgEgDAAgGQAAgIADgIQABgEAEABQAVgCARAKIABADQACAMgHAHIADgBIAAACQAPgOAmgCQAugBAfgMIAJgBQAJgCAGgDQASgKAAgYIgGgHQgDgDgEgBIgEgBQivhniOiEQghgfgGg4QAohuAnhuIAahKIAAgEIAAgEQAWgeAdgYIAAgDQBSgdAwAuQAFADgFAEQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAQgUA2gkAjIAAAEIgDABIhnAkQAPATAjgBIAAACQAYgJAPAHIAAAAQABAAAAAAQAAAAAAAAQAAABAAAAQAAABAAAAIgCABQgtB1g5BmQAFAcAfAFIADAAQBwBEBQBkQAXAdAaAZIAGAGQApAlAxAcQAcAPAQAYQACACAAAFQgJAMgLAEIgggBIgDgBQgPgHgTAAIhZgEIgFAAQgnAXgnAAIAAgDQgIgGgIgCQADACACAEQABACgBADQgFANgMAAIgGgBgAm2MjIAAgBQAAgBgBAAQAAgBAAAAQgBAAAAgBQAAAAgBAAIgBAAIgDgFQAfgMAWAIIgCgCQgOgOgZgEIAAgCQBXABBFgQQAlgKAfgOQiIiQh9idQgpgzgUhIIAAgEQAYgXAYgWQBMhFBYg6IABgDQBcg8Bkg1IADgBQA8AkAiA6IgDABIgBADIgEABQjRBaiyB4QAAAEABAEQAAAAABAAQAAAAAAABQAAAAABAAQAAAAABAAQArAuAkA3QAAAAAAAAQAAAAAAABQABAAAAAAQABAAAAAAIABABQBXDDCGCVQAHAIgJAJIAAADQhCAEhVgOIAAABQgeAIgXAPIgYAAQgQACgGACQgQAEgNAAQgZAAgPgQgAnOMdIgEgDQgBgFgHgLQAOgNATAIIAEABIAAAEQgEAJgIADIAAAIIgNgBgAnxMEQALACAGgEIgCAHQgBAEAAADQgIgFgGgHgAn7L0IAAAAIABgCIAAgBIABgBIABgBIACgDIAMgCIAEAAQAGANgNAAQgFAAgJgDgAFIC/IABgEQANgkgCghQgNABAAAUQAAAkgUAEIgCAAQgEgcALghIgDAAQgKAigaARIgCgCQAEgggEgVQgJAIAAARQABAygggCIgBgEQgDg0ALglQABAAAAAAQAAgBABAAQAAAAAAAAQAAAAAAAAIAIgMQAJgNAOgHIAAgCQAagDAbABIAAgDQBjhuAOiuIAAgEQhuhTiChBIgDAAQgigXgkgRIgDAAQgBAfgVAeIAAANQAAARADANQAIAlgXARIgEAAQg0gBgNgrIAAgEIAAgkQAjhcA5hFIABgDQASghAsAMIAEABQC7CPCnCkIABACQgiB9g5BiQgfA0gfAuQgWAegFArQgEAYgLAAQgEAAgFgEgAEtBfQAlAMgGgNIgDgBQgagVgxANQgCASAVgIQAGgCAGAAQAIAAAIACgAg+gWIgBgFQghhcgnhXQAAgBAAAAQAAgBAAAAQAAAAAAAAQAAAAgBAAQgGgCADgJQCJAOBqgdIAEgBQAJAgANAdIAAAAIACAEQAWAzASA4QgGADgFAFQgRAPgWAKQgwAXgzAAQgpAAgsgPgAnug3IAAgDQgJgDABgLQCCjtC6i0QAPgPATgMQAXgCAPAGIADAAQAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAQAcAGAAANIgIAGQg1AdgtAiIAAAQQABA2gJgeQgEAAgEACQgRAGgLAPQhJBohTBdQAeAKAggcQA6g1A8gzQAOgMAGgSQADgJAJgCIgEhVIAAgEQAmgaAogWIAEgBIAkAAIAEAAQAXAUgogEQgSgDgMAGQgkARgSAdIADgBQAhgSAZALQAEARgNAAQglAAABAUIAEgBQAzgOgXAXIgMABIgDAAQAbAAAFAcIgBADQgTAmgRgpIgEAAQAEALgHAKQh8Cfi3BlIgEAAIgLAAQgUAAgOgEgAhQlJQgHghABgoIgBgDQgKgJgGgNQAmgGAcgUQAHgFgFgDQgEgFgHgBIAAgCQgRABgHgHIATgSIABgCIAhgRIAFAAQAFgRANgGIADgBQAJADAHgBIAJAAQAWgBAJAKQAEAFABAIIAAAEQg4BihcBSIAAAAIgCgBgAAYoZIgKgDIgEgBQgTgOgTgOIgEgDQgVgRgTgSIgBAAIgBgBQgVgVgTgWIAAgDIAAgEIACgBQACgGADgFQAHgJAEgKIAEgGIAIgHIACgDQANAFAOgCIAHgCQAPgGAJgMIACAGIABABQACAKAKAEQAVAKAUgNQAIgGAIgJIADgGIAIgEIACgBIACgBQAPgHARgFIAEgBIAtABIAAgBIABABQAFAFAEABQADABAEgBIAFAVIgCAHIgEAKIAGgDIADgBIADgCQAbgigGAfIgCAIQAJgfAegFQACAMgCAHQAGgLAKAAIACAAQAAAzgrAKIgEAAQgNgBgJADQgJAEgFAHQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAABAAIADACQgZBXhVAcIgFAAIgMABQgKAAgIgCgAhIqHIgCAAIABAEQAHAKAJAJQAJAIALAGIAEAAQBQgIAogxIAEABQAZAIgIgJIgMgRQgNgXgIAHQgDACgCAGQAIAFgCAEQgeAyhDAPIgHABQgTAFgOgRQgGgHgDgIIgBgEIgBABgAgbqlIAAADQAFACADAFIAHgEIABAAQgIgTgOgIQgUgLggARIgBAAIAAAFIACADIADAFIABABIABACQACgDAEgCIAAAAIgBgCQARgIALAAQAPAAAEAOgABHrzQgLgBgEgQQgIgagWgMQAPgaAPgNIAEAFQgLAKAKASIAAgBQAHgRAIgOIgBAFQAAAFAFgBQAEAAADgDIgGAIQAFAhAagaIABABIAAACIAngKIABADQgpAgAqgXIADAEQgMAMgDAMIAGgDQAMAqg7ACIgcgCgAA2sAIAAgBIgFgKIgDgGQAIAGAAANIAAgCgABVtiIAAADIgHAKIgBABIAIgOg");
	this.shape_8.setTransform(100,40.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("ASgO+IgCgEQgGgGgOAJQgLAHgUACQAJgSgFACQgaAMgWgUQAdgHAagMIAHgDQACgCgMgBQgBAAgDgEQgSgLATgMIADgCQASgCATgBIAEAAQAqAZA2gSQARgFASgCIAAgEQAWgCAKgFQAOgJgNgSIAAgBIgBgCQgkgGgZgRQhPg1hLg3QhjhJg9huQA6ibA3ieIAAAAIABgBIABgEIgCAAIgCAAIgFAAIAAACIgBAAQjMBYiyByIAAAEQAtAyAkA9IABADQBNCeBpCCQCmgECfAUIA+AIIgBADQhvAIiDgKQhEgFhDgJIAUAYQAJALgFAYIABAFQADAIgHAAQgBAHAIgDIAFAAQAIgDgDAEQgDAFAGAEQAQAKgDAHQgDAHgXADIgDgBQgdgQgkAEIgEAAQgqgQgwAQIAAgEQgdgCgxAAIgcABQgnAFgagQQgfADgYAGQgjAJgQgOQAugHAvgFIAEAAIAAgBQgTABgQgMIgIgHIgJgIIgLgLQgJgKAEgNIADgHIABgBIAAgBIADAAIADAAIANgIQAEAAADADQALAHAMACQCHAdBggyQhkgChigYQgagHgcgEQgegFgfgCQjQgNjRAEIg1AAQlVgElTAYQg7AEg4AHQgpAEgpAAIgNgLQFDgjFEgEQB6gBB4gFQAXgBAVgDIAAgBQDXABDZAHQAbABAbAIQA8ASBBADIAFAEIARAKQAvAYA6gEQgnglgjgnQiDiOhjitIgBgDQgFgHADgPQBjhiB2hQIADgBIAAgEIDxiRIADgBQgWhagmhNIgBgDQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQgJgagdgFIgEAAQhyBniHBSIgFAAQglADgYgLIgDgBQgOgIABgXQCIjmC5i2QARgQAVgLQAbgBAVAHIAAACIAaALIADABIAFAAQAvgBARgfQgJgQgOgLIgEgDIgFgDQg3glgfg9QAHgPAJgHIAAgBIAJgNIAEgEIAFgEQgFgEgCgFIgCgCIgCgDQAAgOACgOIAAgDIAEgIIAAgDIACgDQABgNAJgKIAAAAIAAgDIAAgBIABAAIABAAIABgBIABgBQALgNAeADIABgDQAVgVAJgPIABgCIgDAAQgtAOgdAfIAAAEIgCAAQgBgXAQgKQgJgEgUAKIgMAGQgcARgNgJQAigQAmgNQAlgOApgLIAAgDIAFAAIAZAAIAEAAQAHgHAHgEIABAAQAagPANAaQAAAAAAAAQAAAAABAAQAAAAAAAAQABAAAAAAIAAAAIAAgBQgFgYgGgEQgNgLgMgRQgJgNgIgQIAcAVIACABIAKAFIABABIAAgDIgHgJQgQgWALgBIAEAEQAFAEAAAIQAFANAGgFIAEgEIAAgEQAtgwgFhGQgBgJgGgHQAbAEgEA1IAAADQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAQADAKADgEIADgHIABgBIAAgCIADAAIAggvIAAACQgCAPgGANIgDAHQgGAMgJAKIgCgBIgVAOIgBgBQgKgDgBALIgCACQgDAFgBAGIgBABIgBACIgHALQgFAHgFAGQgLAMgCAOQgBAMAFAJIADAIIACANQABADgCAEIgEANIgJANIgCAEQgJAOgHARIAAABQgKgSAMgKQAEgEAGgCIgCgJQgGAEgHAGQgPANgOAbQAWALAHAaQAFAQALABIAcACQA6gCgMgqIgFAEQACgNAMgMIAEgCIgHgCQgpAXAoggIABgDIgBAAIgnAKIAAgCQAMgKASgHQARgGAWgBIAFAAIAAgDQAJgDgJgCIAAgBIAAAAQAGACAFgCQAEgCAEABIAGgBQAIgBAFgFIAIgGQAXgVAagOIAEgCQAEgDgBgDIAbgDIAFAAQAnAIAXAXIADABIgBgDQgSgYgegNIgEAAIgSgBQgaABgQALIgBAAIgFADQgYAOgTATQgFABgFAEIgBgBQgIgEgJADIgOADIAAgIQAOgGATABIAEAAIAOgNQAggbAwgNIADAAQBDANASA0IgFgFQgDgGgHgBQAGAKAEAOIACABQAKAPgKARQgUAggIAtIgCAAQgOg6ghgkQgIgIgIgHIAGANIADAGIABAAIAAABIABAFIADAAQASAsAAAuIAAAPIgCAAIgBgJIAAgBIgBgFQgFgqgPgtIgBgDIgIgOIgQgUIgDAAQgJgKgVADIgFAEQgLAKAVAEIAIACQgIAHgcABQAEAJALAFIABACQAAAAgBABQAAAAAAABQAAAAAAAAQAAAAAAAAQgIACgEgEQAQAeAAAPQgNgDAEAgIgDAAIABAAQAFAUAOAKIAAABIABAAIAEABIAAAEQgDAugdAUIgFAAQgXADgRAJIgBAEQgVAzgoAgQgUAQgZALQgBAHABAFQACANAPgIIAEgBQAOgQAVgKQAAAAABAAQAAAAAAgBQAAAAAAAAQAAgBAAgBQBAAEAiAhQBKBHBPBDQBPBBBKBHQgPBrgsBKIgtBOQgXAogcAhQAkAfAMAzQADAKgGAGIgBAAIgBAAIgBABIgDABIgBAAQgNAIgNAKIgDgBQgHgDgSAEQgDA6AogVIAEAAIAAgEIACgDIAAAAQAJgNAHgdQgBAAABAAQAAAAAAAAQAAAAABAAQAAgBABABQAyAJgSA1IgBABQgBAEAPgCQAIAmgRAbIgBAAIABAAQAYAOgQAfIgDAAQAMAvAJA2QADAWAMAUQALATASANIACAAQA6gIAbgoQATgbAEgrQACgZAWgIIAMgEIAAgEQAjgBAbAFIAEAAQA7ArAcBLQAAAAAAAAQABAAAAAAQAAABABAAQAAAAABAAQAGBFgkAbIgDABIgDABQgIAJgFALQgMACgIAGQgVASgWAPQgXAPgYANIgBABIgIAFIgFACIgEACIAAAAIgDABQgcAOgfAGQgVAEgWABIgIAAIAIABIAsAAQBCgBBBgHIAbgDQBpgMBrASIAFABQACAAABAGIgIABQkLAdkQgRQhQgFg0goIACgDQBxAcB2AEIgdgDIgDgBQiJhHAGjWIAAgEIAAgUQACACACABIABABIACABIAAABQgDBsAeBJIABABQAeBIA+AoIABAAIAAAAIAAABIAHADIADABIAaAEIAAAAIACAAIATABIACAAQAagCAXgJIAAAAIABAAIADgBQALACADgGIADgBQAPgCAOgFIACAAIAAgBIABAAIABAAIADgBIAIgDIAHgFIABAAIACgBQAbgRAOgdIAAgBIgBAAQghAKgQAZIAAgDIgFgDIAEgCQAngYgngDIgIAAIAAgEIAIgDQAegIAbANIAAACQAMAHAYgUQAIgGAFgKQgEgDgYgFQgUgEgIgQIgEgBQgagZgUggQgQgZgLgcIgCgDIAAAEQgGALgHAKQgVAdgeAUIgEAAQgTABgNgDIgJgDIgDgBQgmgZgQgvIgBgEQgHgsgBgyIAAgBIgEACQgOACgKAJQgFAEAAACQgKAogZgJIgBgBQgCgFgDgEQAAgFgDgEIgDgEQAMgegRgdQgKAbABAjIABACIAAABQgEgFgEgcIAAgDIAAhGQAMAeAPgYIAEgDQAOgLAYgDIABgEQAYgWgiABIgEAAIgDABQgeAJgXASIgCAAQgDgigLgjIABgDQAWgagwgHIgDgBQgWgPgkgBIgBAEQgJAdgbgVQgGABABgJIABgIIgDACQgqASg9AYIgBAFIgLAdIgBADQgqBmgzBeQABAUATACIAAADQA1AOAgAkQBYBgBgBaIATASQAWATAbAKQA0AVALA6QgNAHgLgBIgIgBQALgEAIgMQAAgEgBgDQgQgYgdgPQgxgcgoglIgGgGQgbgZgXgdQhQhkhwhEIgDAAQgfgEgHgcQA7hnAth1IADgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAAAAAAAIgBAAQgOgHgZAJIAAgCQgjABgOgTIBngkIADgBIAAgEQAjgjAUg2QAAAAAAAAQAAAAAAAAQABgBAAAAQAAAAABAAQAEgEgEgDQgxguhRAdIgBADQgdAYgYAeIAAAEIAAAEIgaBKQgmBugpBuQAHA4AhAfQCPCECvBnIAEABQAEABADADIAGAHQAAAYgSAKQgGAEgJABIgIABQggAMgtABQgnACgOAOIAAgCIgEABQAIgHgDgMIgBgDQgRgKgVACQgDgBgCAEQgDAIABAIQAAAGADADQAIAFAKACIACAAQgKAGAXAGQAMgFAOgFIAFgBQgBAFgNANIgFAGIADACQAEABADgDQAJgFAHgCQgDADgDAFQgCADABADIACABIABABIACAAQADAEAEABQASAEAFgQQACgDgCgCQgCgEgDgCQAJACAIAHIAAACQAnAAAmgXIAGAAIBYAEQATAAAPAHIAEACQhagBhPARIgBADIgTARQgbAHgaAAQgtgBAEgagAKSOBQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAIAAABQAYAZAtgNQAGgCAQgCIAZAAQAWgPAfgHIAAgCQBUAOBDgEIAAgDQAIgJgHgIQiFiVhYjDIAAgBQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgjg3gsguQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQgCgDAAgEQCyh5DRhaIAEgBIABgCIADgCQghg6g9gkIgDABQhjA2hdA7IgBADQhXA6hNBFQgYAWgXAXIAAAEQATBIApA0QB9CcCJCQQggAPglAJQhEAQhXgBIAAACQAYAEAOAPIACABQgWgHgeALIADAFIAAAAIAAAAgAJyNsQAGALABAFIAEADIANACIAAgJQAJgDADgJIAAgEIgDgBQgIgDgGAAQgLAAgIAIgAJoNyQAAgDABgEIADgHQgHAEgKgCQAGAHAHAFgAJVNOIgBADIgCABIAAABIAAABIgCACIAAAAQAeAIgIgSIgEAAIgNACgANjM0IgBABIACgBIABAAIABgBIgBAAIgBAAIgBgBgAcDHzIgYAJIgEACIgBADQgKAMgJAOQACARAEARIAAAAIAAAAIAHAYQAFAOAGAMIAFALIAAABQASAhAbAYIADABQAPAKARAIIABACIAPAAQARAAANgDIAEgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAQAHgHAGgIIABgBIAAAAIAJgOIAAgEIAAgFIAAgBIgCgcIAAgCQgFgrgTgeIgBgBIgBgCQgSgcgdgRQgUgKgYgGIgBAAIgOgDIgBACgAX5GkQgFAVgNALQgEAgAQgGIAEgBIAAgEQAPgOAMgQQAAAAABAAQAAgBAAAAQABgBAAAAQAAgBAAAAIAAgDQAAgWgZAFIAAgBIgCABgAUHD6IhCAfIgDABQgSAIgQAMIAngPIAzgQQALgDAJgGQAPgJAHgPQADgIgRAOQgEADgHACIAAAAIgEABgAWWEdIgBAEQATAOAFgiQAGgrAVgeQAfguAfg0QA5hiAih9IgBgCQiniki7iPIgEgBQgsgMgRAiIgBACQg6BFgjBcIAAAkIAAAFQANAqA0ABIAFAAQAXgQgJgmQgCgMAAgSIAAgNQAUgeACgfIACAAQAlASAhAWIADAAQCCBBBuBTIABAEQgPCshiBwIgBADQgagBgbADIAAACQgOAHgJANIgHAMQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQgLAlAEA0IAAAEIAAAAQAhACgBgyQAAgRAIgIQAEAWgEAfIAAAEIADgBQAZgSALgiIACAAQgLAiAEAbIADAAQATgEAAgkQAAgUANgBQADAhgOAkgAUBC/IgfA+QAOAEATgMIAEgBIAAgEQAmgEACgpIAAgDQAQgTAOgVIADgBQAXgHAhADIAFAAQBZhnARitIAAgDQhqhTh+g+IgBgCIgDgBQgbgPgfgNIgCABQgHAegPAXQgEBnAfBEIABADIAoBZIABAEQACAFAFACQABAHAHAAIAEAEIAEAGIAGAMIAEAHIAFALQADARgBASIgBAXQgOAggSAeIgDABIgBADgAPxB1QATAJAOARIADADQAIAIAHAIIAMARIAEAIQAEALAMgDIAXgWQAKgKAMgJIACgCIAJgDQAKgFALgCIABAAIABAAIABAAIABAAIAAAAQAWgDAWADIACAAQAOABAMACIALADIAGADIAFABIAEACIADADIACABQAEACADgCIABAAIACgCQACgCAAgDIABgEQAEgGACgHQADgDACgFIACgGQADgEABgFIABgDQADgGAAgGIgBgJQgBgHABgHQACgLgJgFIgCgCQgGgMgOAAIgBABIAAAAQgDACgBADQgEABgDADIgKAJIgCABQgKADgIAGIgEAEQgOAIgPACQgLABgLADIgFACIgPABIgGABIgDABQgZADgbgCQgJAAgJgDIgCgBQgMgDgMgBIgDgCIgHgCIgCgBQgFgBgFgCQgJgCgIACIgBAAIgDABIAAAAIgCABIAAAAIgDADIAAABIgDADIgKAGIgCABIgBAAIgBABIgBAAIAAAAQgDADAAADIABADQAFAIAJgBIAFAEgAPFhsQAnBXAhBbIAAAEQBjAiBYgqQAWgKARgOQAFgGAGgDQgSg2gWgzIgBgEIgBAAIgBAAQgMgdgKgfIgEAAQhsAdiJgOQgCAJAGACIAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAQABABAAAAgAOzmiQgSAMgQAPQi5C1iCDrQgBAKAIADIAAADQATAGAagCIAFAAQC2hjB8ifQAIgKgEgLIADAAQARApATgmIABgDQgFgbgbgBIADAAIAMgBQAXgXgzAPIgEAAQgBgTAlgBQANAAgEgRQgZgLghASIgDACQATgeAjgRQAMgFATACQAoAEgXgUIgFAAIgkAAIgDABQgpAWglAaIAAAEIAEBWQgKABgDAKQgGARgNAMQg9Azg5A1QghAcgdgJQBTheBJhnQALgQARgGQADgBAEgBQAKAegCg2IAAgQQAugiA1gdIAHgGQAAgNgcgGQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIgDgBQgKgEgPAAIgNAAgANbjVQg2A7g5A6IAAACQBAgoBKg0IADAAQAGgzAAgiIgDABQgQAagNAeIgBAAIgDABgAPEjAQgLAMgKAKQgGAFgCAGIgHAKQgCAEAAAFQgBAHAHAAIABAAIAQABIASAAIADADIABAAIAeAEIAEAAIA8ACIAagBIBKgGQAWgBATgIIACgCIABgBIABgEQABgFgDgCIgBgCIgBgBQgLgEgNABIgHAAIgFgCQgHgCgHABQgDgCgGgBIgDgBQgIgCgHgFIgBgCIgDgFIgBgCIgHgHIgBgFIgGgTQgDgHABgJIABgWQAAgFADgFIAGgLQADgHAEgFQAGgGACgJIAAgCIABgBIAJgSQAFgJAGgIQAFgHAEgHQAJgUAOgSIACgDQADgEABgEQADgMgMAAIgDADIgBADIgQAWIgDAIQgJAUgPARIgEAFQgEAHgGAFQgLAJgIAKIgEAGQgGAIgFAJIgQASIgBABQgHACgCAHIgXAUQgCADgEACQgEACgCADIAAABIgCAAIgMAJQgGAEgGADIgHADIgLgBQgMACgHAJgAOHkCQAAAJgEAHQgDAHABAGQAAAKALgDQAHgOACgRQABgLgKAAIAAABIgBAAIgCAAQgBACgBADgAQelxQAHABAEAFQAEADgHAFQgcAUglAGQAGANAJAKIABACQgBAoAHAhQAAAAAAABQAAAAABAAQAAAAAAAAQABAAAAAAQBfhSA3hiIABgDQgCgIgEgGQgJgKgWABIgIAAQgIABgIgDIgEABQgOAHgGARIgEAAIgiAQIAAACIgUASQAIAHARgBgAP/mQIgBADIgHAJQgDAFACAFQADAGAIgDQAGgGAFgHQACgDAAgDQABgMgMABIAAAAIgBAAQgCACgBADgAP3pcIgHAHIgFAGQgEAKgHAJQgDAFgCAGIgCABIAAAEIAAADQATAXAWAUIABABIAAAAQAUATAVAQIAEADQATAPAUANIAEABIALADQAMADASgCIAEAAQBWgcAYhXIgDgCQAAABAAgBQgBAAAAAAQAAAAAAAAQAAgBAAAAQAGgHAJgDQAJgEANABIAEAAQAqgKAAgzIgBAAQgKAAgHALQADgHgCgMQgfAFgJAfIACgIQAGgfgbAiIgCACIgDACIgGACIADgKIADgHQALgfANgeIACAAQAAgIADgFQALgcgJAPIgGAMIgCADIgEAJIgHARQgJAWgJADQgDABgEgBQgEgBgFgFIAAgBIAAABIgtgBIgEABQgSAFgPAIIgCAAIgBABIgIAEIgDAGQgIAJgJAGQgUANgXgKQgJgEgDgKIAAgBIgDgGQgJAMgOAGIgHACQgPACgNgFIgCADgARPqxIgFAFIgIAHIAAABIAAAGIAAABIgDAIIgDACQgDAKAAALIAAAAIAAABQAAAJADAIQADAGAFACQARAHARgIIAIgEIAOgKQAIgHABgKQACgNgDgLQgBgNgIgGIAAAAQgEgHgHgCIgTgCQgIADgGAGgAP+q0IgCADQgEADgBAFIgCAAIgCAHIAAAAIAAAAIAAAEIgBADIgBAFIgBACIgCAFIgBACIgBADIAAAUIAAACIABADQAFAKALACQAZAFAUgSIAFgFIABgEIAAgDQAAgOAHgMIAAAAIgBgDQAAgJAEgHQgBgGgIgDIAAAAQgEgEgGABIgCAAIgCABQgRgGgOAIIgDAAIgDAAgAUnrPIAAADQADAigHAYIAAADIAAAFQAaABgFgeIgBgEIABgEQAFghgWgEIAAAFgAUKrpIgCAGIAAAAQgQAqgWAjIAAAEIACgCQAdgaAIgiIAAAAQADgOAAgOIgBAAIgBADgARgrzIgcAXIgaAVIABADQAMATAHABQADAAACgCQAGgHACgbIACAAQASgVAFgLQgBAAgBAAQAAAAgBAAQAAAAAAAAQgBABAAAAgAWFsFQAdAlAaAqIADAEQABAEgCgJQAHgcgbghIgRgVIgCgBQgFgIgMAAIgJACQgDAKALAAgAXOrUIACgDQAFgMgDgVIgBgDQgLgOgVgDIgDAAIgNAAQAPAvAeAJgAWlsYQAxAKg5gbIgEAAIgoAAIgBACQgFACgHAAQAZAJAgADIAEAAIAAAAIAEABgA6gOpIAEAAQAQgJAVgFIAAgCIAAgEQA2gDAsgMIADgBIAAACQgRAIgTAFQgTAGgWAEIAAADIAAAEIgDABQgTAGgTAAQgMAAgMgDgA4yOhQAOACAIgEIADgBIAbgLIAZgIIAAgCIAJAAIAEAAIgDADIgYAOIgOAJQgQAJgLAAQgNAAgJgLgA3gOlQARgCAHgEIACAJIgIAAQgKAAgIgDgAHXOVQAmgKAsgGIAEAAQAVAJAUgMIADgBIAAACQgXALgaAHQgaAGgeADIAAADIgFABIgIABQgNAAABgOgEggaAOBQgCAAgCgFQB1gGBugfIAsgMQCdATCaAXIAAAGIgEAAIg1gBQh9gFh/gPQgKgCgKAEQhSAfhZAAQgmAAgogGgAaRMUIABgFQAXgEAWgGQgCAFgCANIgBAEQgJgKgbABQgCAaAUAHQgaAAADgfgAZIMrQgbgTgUgaQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAAAIADgGQASgbApALIADABQAXANAFAcIACADQgHALgKAGIgLAFQgGACgIABIgEAAgAYoL+IABAEQAMASAPAPQAHAAABgDQAYgig3AAIgFAAgAYoLuQAAAAAAABQAAAAAAABQAAAAABAAQAAAAAAABQAQAJAYABIABADIAXAdIAAgEQgHgvghAAQgLAAgOAGgAbOMbQgEgSgDgGIAHgDIAJgDIAEgCIAAADIgEAEQgDAPALAAIAAABQAAAAgBABQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBAFgEABQgDACgFAAIgCAAgAXjLIIgBgDIgHgwIgBgEQAVAWAOAgQAEAIgCATIgcgagAdQK3Qg3gUgegvQgJgQgHgSIgIgXIAAgEIAAghIAIgHQAJgIAMgFIAEAAIALgBQALABgMAJIgGAEQgNgBgQAUIgEAEIAEADQAEACAHgDQgIAHgCAMQADAWAMgMIAAACIAAADIgHAJQAIANANgQIAIgNQAMgWAUgPQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQgRAZgTAXIgQATQAdBHBKAGIAEAAQAbgVgRgsQAAAAAAAAQAAAAAAAAQgBgBAAAAQAAAAgBAAQgJASABgiQAAgNgEAGQgZAcAUgtIAAgEIAEgFIABgDQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAABQATAbAGAoQABAOABAPIgBAFQgDAGgEAFQgDAGgGADQgHAFgIAAQgHAAgIgDgAV7DCQgQgGgMAFQgVAIABgSQAygMAZAUIADABQAEAHgJAAQgIAAgRgFgAQwCYIABAAIAAAAIgBAAgATzCHIAAAAIAAAAIAAAAgAO1iTIABgBIAAABIgBAAgAQmoAQgLgGgJgIQgJgIgGgLIgBgDIABgBIACgBIAAAEQADAIAGAHQAPARATgFIAHgBQBEgPAfgyQABgDgHgFQACgHACgCQAIgHANAXIAMARQAJAKgagJIgDgBQgpAxhSAIIgEAAgAQxpAIgBgDQgHgYgnASIABACIgBAAQgEACgBADIgCgCIgBgBIgCgEIgCgEIgBgEIAAAAIABgBIAAAAQAggRAVALQANAIAJATIgCAAIgGAEQgEgEgEgDgAScrgIAGgIIACgDQAEgGAFgFQALgMgGgNIAAgHQABgPgIgLQgCgEABgFIACgHIAAACQAAAAAAABQABAAAAAAQAAABABAAQAAAAAAAAQALABAFgKIADgCIAYgPQADgCABgCQAFgHgIgCQgKACgHAHQgHADgGAFIgBAAIgCAAQgBABAAAAQAAAAgBABQAAAAAAABQAAABAAAAIgCABIANgXIABgBIADgEQAFgFAFgFQAEgBAEgEIAFgGQAHgGAGgHIABgCQARgGAPgLIADgDIABgBIAHgGIAJgKIAAACIgEAJIgGAJIgBACIgCACQgNARgUAJIgIADIgEACIgDAAQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBABIgTAQIAAAFIACgBIAfgRIAHgDIAAAAIAAgBIAAAAIAagOIADgBQAFgHAFgHIABAAIABgCQAGgGAHgFIAAADIgIALIgBACIgNAQIgBAAIgRARIgHAHIgBAAIgBABIgEADIgFAEQgPALgRAJIgEAAQAAABAAAAQAAAAAAABQAAAAAAAAQgBABAAAAIgUAUIgHAJQAMAOAPgJQAIgEAJgKIANgNIABgBIACgCIAAAAIACgCIANgJIACgBIACgBIADgCIAAAAIABAAIABgBIACAAIADgCIAAAAIACgBIAEgCIAEgBIABgBIAKgDIAHgCIARgEIgOAIIgIAEIgHAEIgBABIgFACIgDACIgBABIgBABIgCABIgFADIgBABIgEACIgBABIgCACIgBABIgDABIgDACIgBABIgBABIAAAAQgSAMgRAOIgDABIAAACIADgCQATgKAUgJIABgBIAMgFIAGgCIAHgDIAHgCIAAgBIAIgDIADgBIACAAIgEAEIgFAEIgBABQgUAPgVALIgBAAQgbAPgdAIIgBACQgDADgEACQANASAlgOQAMgFAHADQgDABgDACQglAEgWATQAYgHAngFQAFABAFgBIAAABQgRAHgXAFIAAAAQgRAEgLANIgDADQgLALgHAAQgKAAgDgTgAPtsPIACgBIAFgEIAPgIQAOgGAQgFIABgCIgBAAIglACIgNABIgBABIgEAAQgPADgLADIAAgCIAbgMIAFgCIABAAIAAgDIABAAIAEAAIAXAAIAVAAIAEAAQAUAKAQAMIABADQgpgIgtARIgGACIgDABIgDABIAEgDgARcsrIAAAAIgagVQgfgXgPAOIgCADIADACIABACIADABQAnAHAXAVIAAACQgZgKgYgMIgEAAIgVABQgQAAgLgCQgIgBgFgCQAGgJAOAAIAEAAIAAgEQBFgXAjA0IAKAQIAAAEIgTgSg");
	this.shape_9.setTransform(-10.1,30.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-221,-154.2,419.6,306.2);


(lib.goNext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,11.3).s().p("AhLAqQghgSACgYQgCgXAhgRQAggTArAAQAsAAAgATQAfARAAAXQAAAYgfASQggASgsAAQgrAAgggSg");
	this.shape.setTransform(22.8,8.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.502)").s().p("AhThcICoBdIioBcg");
	this.shape_1.setTransform(25.1,20.4);

	this.blinker = new lib.general_buttoncolor();
	this.blinker.setTransform(23.4,20.1,1.5,1.5,0,0,0,11.9,11.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,14.8).s().p("AhiA3QgrgXACggQgCgfArgWQApgYA5AAQA5AAAqAYQAqAWAAAfQAAAggqAXQgqAXg5AAQg5AAgpgXg");
	this.shape_2.setTransform(23.4,8.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("rgba(0,0,0,0.502)").ss(1,1,1,3,true).p("AAACxQhIAAg0g0Qg0g1AAhIQAAhHA0g1QA0g0BIAAQBJAAA0A0QA0A1AABHQAABIg0A1Qg0A0hJAAg");
	this.shape_3.setTransform(23.3,20.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["rgba(103,103,103,0.839)","rgba(134,134,134,0)"],[0.678,0.918],-0.8,0,0,-0.8,0,24.9).s().p("AisCkQhFhEAAhgQAAhgBFhDQBEhFBhAAQBfAABBAwQBCAwAVCqQAVCskMAbQhhAAhEhFgAgHCQQBEAAAzgwIABAAIADgEQA0g0AAhHQAAhJg0g0IgFgFIgBgBQgyguhDAAIAAAAIgBAAIAAAAIgBAAQhEAAgyAuIgBABIgCACIgBABIAAAAIgCACQg0A0AABJQAABHA0A0IACACIABABQAzAxBHAAIAAAAIAAAAIAAAAIAAAAQhHAAgzgxIgBgBIgCgCQg0g0AAhHQAAhJA0g0IACgCIAAAAIABgBIACgCIABgBQAyguBEAAIABAAIAAAAIABAAIAAAAQBDAAAyAuIABABIAFAFQA0A0AABJQAABHg0A0IgDAEIgBAAQgzAwhEAAIAAAAIgBAAIABAAIAAAAg");
	this.shape_4.setTransform(24.2,23.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},2).wait(1));

	// Layer 2
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#33FFFF").s().p("AioCqQhGhHAAhjQAAhiBGhGQBGhHBiAAQBjAABGBHQBHBGgBBiQABBjhHBHQhGBGhjAAQhiAAhGhGg");
	this.shape_5.setTransform(24.4,21.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0099FF").s().p("AioCqQhGhHAAhjQAAhiBGhGQBGhHBiAAQBjAABGBHQBHBGgBBiQABBjhHBHQhGBGhjAAQhiAAhGhGg");
	this.shape_6.setTransform(24.4,21.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.5,46.7);


// stage content:



(lib.pronoun_Scene13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.btn_menu.addEventListener("click", openMenu.bind(this));
		this.btn_goNext.addEventListener("click", openNext.bind(this));
		this.btn_goBack.addEventListener("click", openPrev.bind(this));
		
		function openMenu(){
		
		 window.open ("../menu/main_menu.html","_self");
		}
		
		function openNext(){
		
		 window.open ("pronoun_Scene14.html","_self");
		}
		
		function openPrev(){
		
		 window.open ("pronoun_Scene12.html","_self");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// text
	this.instance = new lib.youobjtext();
	this.instance.setTransform(275,182.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 1
	this.btn_menu = new lib.skiptomenu();
	this.btn_menu.setTransform(514.1,20.3);
	new cjs.ButtonHelper(this.btn_menu, 0, 1, 2, false, new lib.skiptomenu(), 3);

	this.instance_1 = new lib.pronounheader();
	this.instance_1.setTransform(275,18);

	this.instance_2 = new lib.YOU();
	this.instance_2.setTransform(284.5,176.8,0.868,0.868);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.btn_menu}]}).wait(1));

	// btn
	this.instance_3 = new lib.Copyright("synched",0);
	this.instance_3.setTransform(275,389.5);

	this.btn_goBack = new lib.goNext();
	this.btn_goBack.setTransform(57.6,352.3,1,1,0,0,180);
	new cjs.ButtonHelper(this.btn_goBack, 0, 1, 2, false, new lib.goNext(), 3);

	this.btn_goNext = new lib.goNext();
	this.btn_goNext.setTransform(494,352.3);
	new cjs.ButtonHelper(this.btn_goNext, 0, 1, 2, false, new lib.goNext(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.btn_goNext},{t:this.btn_goBack},{t:this.instance_3}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(284.2,198.6,537.1,400.3);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;