(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 550,
	height: 400,
	fps: 12,
	color: "#FFFFFF",
	webfonts: {},
	manifest: [
		{src:"sounds/bgmusic.mp3", id:"bgmusic"},
		{src:"sounds/dentaku_groove.mp3", id:"dentaku_groove"},
		{src:"sounds/futureAli.mp3", id:"futureAli"},
		{src:"sounds/pastali.mp3", id:"pastali"},
		{src:"sounds/presentAli.mp3", id:"presentAli"},
		{src:"sounds/space_blip.mp3", id:"space_blip"},
		{src:"sounds/verbtense.mp3", id:"verbtense"}
	]
};



lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib.Tween30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AiJDxQgegcAAhkIABgsIADg0QgDgHgBgJQAAgIAHgJQAFhaAAgrQAAgMgDgWQgCgWAAgMQAAglAeAAQAOgBAJAKQAmgLAigFQAhgEAbAAQBMgBAtATQAWAIgBAWQAAAMgIAKQgIALgOAAIgKgCQg0gPgyAAQgZAAgdAFQgeAFgkAJQADAVAAAMQABArgGBNICHgOQA9gGANAAQAOAAAKAJQAJAJAAAOQAAAbgcAEIhMAGIiOANIgCArIgBAlQAABEAKANQAHAJArAAIA4gBIA7gBIASgDIASgCQAiABgBAgQAAAagbAFQgdAHhgAAQhhgBgcgZg");
	this.shape.setTransform(181.5,2.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("Ah9DYQg6gbgBguQgBgNAKgJQAJgJANAAQAQABALARQAQAYANAIQAbASAyAAQAvAAAqgVQA1gbAAgwQAAgngtgXQgmgUg2gCQgxAAgjgTQgtgZAAgwQAAg3BAgvQA8gsA/AAQAeAAAmALQAzAOAAAUQAAAcgcAAQgMAAgggGQgfgIgRABQgvAAgiAYQgkAYAAAiQAAAaAvALQARAFAwADQBHAFApAoQAlAiAAA1QAABKhFAtQg8AnhNgBQg5ABgwgXg");
	this.shape_1.setTransform(138.6,4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF0000").s().p("AjSD0QgJgKAAgNIACgoIACgoIABg6IACg7IgBg8IgBg/QAAgTgEgnQgEgnAAgUQAAgOANgMQAMgMAQAAQAQAAAZAkQBOB1A+BOQBIBZBZBUQABgNgBgaIgBgoQAAiIgKhRIgJghQgGgWAAgLQAAglAhAAQA3AAAADLIgBBnIgBBnQAAAPgFAkQgFAfgdAAQgRAAgYgWQh/h5ikjiIgBBHIgBBGIABBOIABBOQAABVghAAQgRAAgKgLg");
	this.shape_2.setTransform(90.8,3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF0000").s().p("AiJDxQgegcAAhkIABgsIADg0QgDgHgBgJQAAgIAHgJQAFhaAAgrQAAgMgDgWQgCgWAAgMQAAglAeAAQAOgBAJAKQAmgLAigFQAggEAcAAQBMgBAtATQAWAIgBAWQAAAMgHAKQgJALgOAAIgKgCQg0gPgyAAQgZAAgdAFQgeAFgkAJQADAVAAAMQABArgGBNICHgOQA8gGAOAAQAOAAAKAJQAJAJAAAOQAAAbgcAEIhMAGIiOANIgCArIgBAlQAABEAKANQAHAJArAAIA4gBIA7gBIASgDIASgCQAiABgBAgQAAAagbAFQgdAHhgAAQhhgBgcgZg");
	this.shape_3.setTransform(45.7,2.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF0000").s().p("AgVDlQgKgIAAgOIABgOIACgOIgCguQgDgfAAgQQAAgtgGhPQgIhXgBgnIgcABQhFAAgngKQgZgHAAgYQgBgNAJgKQAJgLAOABIAzAGQAfADAUAAIA5AAIA2gBQAZAAAvADQAwAEAYAAQAOAAAJAJQAIAJABAOQgBANgIAKQgJAJgOAAQgXAAgxgEQgugDgZAAIgWAAQABArAHBhQAHBZAAAyIACAhQACAXABALQAAAVgIAQQgIAUgSAAQgMAAgJgJg");
	this.shape_4.setTransform(5.6,2.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF0000").s().p("AiSDxQgMgNAAgOIAAhbQAAgtAGhRQAGhZABgoQgBgdAEg5QACgQAIgFQArgNA2AAQA1AAAzAmQA7ArAAA/QAABRg/AsQAvAUAYAZQAXAYAAAdQAAAmgpAjQgdAZgfANQhFAbhtAAQgOAAgMgMgAhgB8IAABBQBSgDAygUQAWgJAUgRQATgRAAgIQAAgPgogSQgegOgbgHIghgFIgMAAIgNAAQgRAAgTgCQgCAnAAAfgAhTi6IAAA3IgHB5IAwAEQAtgEAegaQAhgcAAgsQAAgdghgaQghgZgjAAQgiAAgOACg");
	this.shape_5.setTransform(-56.7,2.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF0000").s().p("AifDtQgJgKAAgOQAAgYgCgxQgDgxAAgZQAAgdAHg3QAGg5AAgdQAAgQgDgfQgDgfAAgQQAAgSAKgOQAMgQAVABIBLAGQArAGAcAPQB/BEAABhQAAAvgrAjQgjAeg0APQBhA0AwA6QAJAKAAAMQAAANgKAJQgKAKgMAAQgMAAgLgKQhnhmh9gkIACA+IACA9QAAAOgJAKQgJAJgOAAQgNAAgJgJgAhjiMQACAXAAAPQAAAZgEAlIgHA9IAOAAIAOAAQBQAAAmgVQARgIAPgPQARgSAAgMQAAgsgyglQgrgjgygFIgugEg");
	this.shape_6.setTransform(-98,2.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF0000").s().p("AiJDxQgegcAAhkIABgsIADg0QgDgHgBgJQAAgIAHgJQAFhaAAgrQAAgMgDgWQgCgWAAgMQAAglAeAAQAOgBAJAKQAmgLAigFQAhgEAbAAQBMgBAtATQAWAIgBAWQAAAMgIAKQgIALgOAAIgKgCQg1gPgxAAQgZAAgdAFQgeAFgkAJQADAVAAAMQABArgGBNICHgOQA9gGANAAQAOAAAKAJQAJAJAAAOQAAAbgcAEIhMAGIiOANIgCArIgBAlQAABEAKANQAHAJArAAIA4gBIA7gBIASgDIASgCQAiABgBAgQAAAagbAFQgdAHhgAAQhhgBgcgZg");
	this.shape_7.setTransform(-138,2.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF0000").s().p("Ag4DkQgmhfgvixIgYhXQgShAgBgVQABgNAJgKQAKgIANAAQAXAAAHAZIAMA3IAeBqQAeBzAcBVIADgGIBRjhIAbhNQASguAUgYQAKgNAPAAQAMAAAKAKQAKAJgBAOQAAAKgFAJQgUAdgNAgIgXBEIhVDiQgOAogUAnQgIASgSAAQgYABgKgZg");
	this.shape_8.setTransform(-177.8,3.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-206.7,-50.5,413.6,101.1);


(lib.Tween9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgIAJQgEgEAAgFQAAgEAEgEQAEgEAEAAQAFAAAEAEQAEAEAAAEQAAAFgEAEQgEAEgFAAQgEAAgEgEg");
	this.shape.setTransform(111.3,24.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgdA7QgQgGAAgKQAAgFADgDQADgEAFABQADgBAFAGQADACAJACIAMABQAHAAAHgCQAKgDAAgHQAAgOgUgGIgKgCQgOgDgGgFQgJgDAAgNQAAgWAWgJQAGgEAMgDIAUgHQAFgCAFAAQAFAAADADQADADAAAEIABAKIABAJQAAAFgDADQgDADgEAAQgGAAgDgEQgBgDgBgJIgZAHQgPAIgBAJIAHADQAWAEAMAIQASAJAAAVQAAASgPAIQgNAIgRAAQgOAAgNgFg");
	this.shape_1.setTransform(102.8,19.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgoAxIAAhJIAAgLIAAgLQAAgLAKAAQAKAAAAASQAUgUAYAAQAJABAEAGQAEAHAAANIAAAHQAAANgKAAQgKAAAAgKIAAgIIAAgJQgRACgJAIQgJAHgGAOIAAA5QAAAKgLAAQgJAAAAgKg");
	this.shape_2.setTransform(92.8,20);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAYAzQgOAHgPAAQgOAAgJgHQgKgGgDgOQgEgcAAgUQAAgPADgSQACgKAIAAQAGAAACADQAEADAAAEIgCARIgCAQIABAcQACANACAIIAHADIAHABQAMAAAQgFIAAgVIAAgTQAAgYACgRQABgKAJABQAFAAADACQADADAAAFIgCApIAAAVIAAAXIAAAIIABAGQAAAFgDADQgDADgFAAQgIAAgCgKg");
	this.shape_3.setTransform(81.6,20);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgeAuQgPgOAAgXQAAgTAPgYQAQgZASAAQAKAAANAFQARAGAAAJQAAAEgDADQgDAEgEAAQgDgBgCgBIgEgEQgHgFgOAAQgJAAgLAUQgKARAAALQAAAPAKAIQAJAIAMAAQAHAAAHgEIAMgHIAFgBQAEAAADADQADADAAAEQAAAIgRAHQgOAHgKAAQgUAAgPgOg");
	this.shape_4.setTransform(70.2,19.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgeAuQgPgOAAgXQAAgTAPgYQAQgZASAAQAKAAANAFQARAGAAAJQAAAEgDADQgDAEgEAAQgDgBgCgBIgEgEQgHgFgOAAQgJAAgLAUQgKARAAALQAAAPAKAIQAJAIAMAAQAHAAAHgEIAMgHIAFgBQAEAAADADQADADAAAEQAAAIgRAHQgOAHgKAAQgUAAgPgOg");
	this.shape_5.setTransform(58.9,19.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgfAtQgPgPAAgZQgBgWANgTQAPgWAZABQAVgBALAVQAJAPAAAWQAAAXgNAQQgNAUgVAAQgSAAgNgOgAgSgUQgHAMAAANQAAAPAJAKQAGAGAKAAQAJAAAJgIQAIgIABgQQABgogYAAQgNABgJAPg");
	this.shape_6.setTransform(47.3,20);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AAaA0IgDgXIgCgYIABgIIAAgKQAAgYgJAAQgMABgJAOQgKANgFARIgBALIgBALIABAJIABAKQAAAFgDADQgDACgFAAQgFAAgDgCQgDgDAAgFIAAgKIgBgJIACgeIABgeIAAgKIgBgKQAAgFAEgDQADgDAEAAQAKAAABAOIAAAMQASgXARAAQARAAAHAPQAFAKAAAUIAAALIAAAHQAAAKADAOQACAOAAAIQAAAFgDADQgDADgFAAQgJAAgBgKg");
	this.shape_7.setTransform(29.7,19.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgfAtQgPgPAAgZQgBgWANgTQAPgWAZABQAVgBALAVQAJAPAAAWQAAAXgNAQQgNAUgVAAQgSAAgNgOgAgSgUQgHAMAAANQAAAPAIAKQAHAGAKAAQAJAAAIgIQAJgIABgQQABgogYAAQgNABgJAPg");
	this.shape_8.setTransform(17.8,20);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgJBNQgDgDAAgEIgBgUIAAgTIABgZIACgXQAAgFADgDQADgDAEAAQADAAADADQADADAAAFIgBAXIgBAZIAAATIAAAUQAAAEgDADQgDADgCAAQgFAAgDgDgAgGg6QgDgEAAgFQAAgFADgEQAEgDADAAQAFAAAEADQAEAEAAAFQAAAFgEAEQgEAEgFAAQgDAAgEgEg");
	this.shape_9.setTransform(9.4,17.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgGBLQgDgCAAgFIAAgMIABgNIgCg8IgYgCQgKgBAAgJQAAgGADgCQADgDAFgBIAWADIAAgQIgBgMQAAgFADgDQADgDAFAAQAIAAABAPIAAAKIAAAHIAAAGIAPgCQAMAAADACQAHABAAAJQAAAEgDAEQgDADgFAAIgFAAIgGgBIgOABIACA+IAAAFIAAAFQAAAYgLAAQgDAAgDgDg");
	this.shape_10.setTransform(0.9,18.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgeAuQgPgOAAgXQAAgTAPgYQAQgZASAAQAKAAANAFQARAGAAAJQAAAEgDADQgDAEgEAAQgDgBgCgBIgEgEQgHgFgOAAQgJAAgLAUQgKARAAALQAAAPAKAIQAJAIAMAAQAHAAAHgEIAMgHIAFgBQAEAAADADQADADAAAEQAAAIgRAHQgOAHgKAAQgUAAgPgOg");
	this.shape_11.setTransform(-9.9,19.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AAiA2IgIgIIgSAJQgIADgDAAQgZAAgLgPQgLgNAAgbQAAgYASgSQASgTAWAAQAKAAALAEQAPAHAAAIQAAADgCACIgCAOIgBAVQAAAOACAIIAHATIACAGIABABQAAAFgDADQgDACgEAAQgCAAgFgFgAgRgaQgMAOAAAQQAAASAGAIQAGAJANAAQAIAAAHgEIALgIQgDgbAAgNIAAgLIACgLIgHgDIgEgBQgPAAgMANg");
	this.shape_12.setTransform(-21.2,20);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AAaA0IgDgXIgCgYIABgIIAAgKQAAgYgJAAQgMABgJAOQgKANgFARIgBALIgBALIABAJIABAKQAAAFgDADQgDACgFAAQgFAAgDgCQgDgDAAgFIAAgKIgBgJIACgeIABgeIAAgKIgBgKQAAgFAEgDQADgDAEAAQAKAAABAOIAAAMQASgXARAAQARAAAHAPQAFAKAAAUIAAALIAAAHQAAAKADAOQACAOAAAIQAAAFgDADQgDADgFAAQgJAAgBgKg");
	this.shape_13.setTransform(-38.8,19.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAiA2IgIgIIgSAJQgIADgDAAQgZAAgLgPQgLgNAAgbQAAgYASgSQASgTAWAAQAKAAALAEQAPAHAAAIQAAADgCACIgCAOIgBAVQAAAOACAIIAHATIACAGIABABQAAAFgDADQgDACgEAAQgCAAgFgFgAgRgaQgMAOAAAQQAAASAGAIQAGAJANAAQAIAAAHgEIALgIQgDgbAAgNIAAgLIACgLIgHgDIgEgBQgPAAgMANg");
	this.shape_14.setTransform(-50.4,20);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AAaA0IgDgXIgCgYIABgIIAAgKQAAgYgJAAQgMABgJAOQgKANgFARIgBALIgBALIABAJIABAKQAAAFgDADQgDACgFAAQgFAAgDgCQgDgDAAgFIAAgKIgBgJIACgeIABgeIAAgKIgBgKQAAgFAEgDQADgDAEAAQAKAAABAOIAAAMQASgXARAAQARAAAHAPQAFAKAAAUIAAALIAAAHQAAAKADAOQACAOAAAIQAAAFgDADQgDADgFAAQgJAAgBgKg");
	this.shape_15.setTransform(-68.1,19.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgkAuQgQgNAAgZQAAgZAOgTQAOgVAYAAQAQAAAMAGQAOAHAAAQQgBALgLAIQgGAEgRAGIgoAUQAHAJAJAEQAJAFAJAAQAIAAAKgDQANgEADgFQAEgGAEAAQAEAAADADQADADAAADQAAAMgUAJQgQAHgQAAQgVAAgQgMgAgVgbQgJAKgEASIAhgOQARgJAIgHQgJgJgPAAQgMAAgJALg");
	this.shape_16.setTransform(-79.9,19.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAdBRQgDgJgCgQQgCgQAAgKIAAgIIABgJQAAgSgKAAQgNAAgKAKQgFAHgKASQAAAogDAIQgDAHgHAAQgEAAgDgDQgEgDAAgFIABgEQABgDAAgNIABgQIAAhNIABgSIgBgKIgBgKQAAgFADgDQADgDAFAAQAIAAACAKQACAKAAAIIgBAYIgBAXIAAAKQAJgMAKgGQAIgGAMAAQARAAAHAMQAFAIAAARIABAVIACAWQACANACAJIABAEQAAAEgEADQgDADgEAAQgIAAgCgIg");
	this.shape_17.setTransform(-92.3,17);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAZA8QgMAAgHgdIgEgZIgCgWIgIASIgRAtQgBAEgDACQgDAGgHAAQgIABgIghQgEgQgEgbIgCgQIgCgQQAAgFAEgDQADgDAEAAQAIAAACAJIADAQIABAQIAHAuIAYhKQAEgMAHAAQAIAAADANIAHAnIAIAoIAIgdIANg5QACgGAIAAQAEAAAEADQADADAAAEIgBAFQgJAjgNAqQgDAKgHAKQgDAGgGAAIgBAAg");
	this.shape_18.setTransform(-106.3,20.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgkAuQgQgNAAgZQAAgZANgTQAPgVAYAAQARAAALAGQANAHAAAQQABALgMAIQgGAEgRAGIgnAUQAFAJAKAEQAJAFAKAAQAHAAAKgDQAMgEAEgFQAEgGAEAAQAEAAADADQADADAAADQAAAMgUAJQgQAHgPAAQgXAAgPgMgAgVgbQgJAKgEASIAhgOQASgJAHgHQgIgJgQAAQgNAAgIALg");
	this.shape_19.setTransform(154.8,-12.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgFA/QgDgEAAgEQAAgNgDgaQgCgXAAgNQAAgLgDgHQgIAEgIAHIgMAPIgGAGIgBARIgBATIABAJIABAIQAAAFgDADQgEADgEAAQgMAAAAgcIABgTIABgRIgBgRIgBgSQAAgYALAAQAEAAAEAEQADADAAAFIAAAGIgBAHIAAALQAGgMALgJQALgJAHAAQARAAAEAQQAGgHAJgEQAIgEAKAAQASAAAHATQABAEADAaIAIA8QAAAEgDADQgDADgFAAQgJAAgBgJIgEghIgEggQgBgHgCgHQgEgKgEAAQgEAAgLAHIgOAKIABAUIADAbQACARAAALQAAAEgDAEQgDADgEAAQgDAAgDgDg");
	this.shape_20.setTransform(140.1,-12.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgJBNQgDgDAAgEIAAgUIgBgTIACgZIAAgXQAAgFADgDQAEgDAEAAQADAAACADQADADAAAFIgBAXIgBAZIAAATIABAUQAAAEgDADQgDADgDAAQgEAAgDgDgAgFg6QgEgEAAgFQAAgFAEgEQADgDAEAAQAEAAAFADQADAEAAAFQAAAFgDAEQgFAEgEAAQgEAAgDgEg");
	this.shape_21.setTransform(128.6,-15.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgGBLQgDgCAAgFIAAgMIABgNIgCg8IgYgCQgKgBAAgJQAAgFADgEQADgCAFAAIAWACIAAgQIgBgMQAAgFADgDQADgDAFAAQAIAAABAPIAAAKIAAAGIAAAHIAPgBQAMAAADABQAHABAAAJQAAAFgDADQgDACgFAAIgFAAIgGAAIgOABIACA+IAAAFIAAAFQAAAYgLAAQgDAAgDgDg");
	this.shape_22.setTransform(120.1,-14.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgkAuQgQgNAAgZQAAgZANgTQAPgVAYAAQARAAALAGQANAHAAAQQABALgMAIQgGAEgRAGIgnAUQAFAJAKAEQAJAFAKAAQAHAAAKgDQAMgEAEgFQAEgGAEAAQAEAAADADQADADAAADQAAAMgUAJQgQAHgPAAQgXAAgPgMgAgVgbQgJAKgEASIAhgOQASgJAHgHQgIgJgQAAQgNAAgIALg");
	this.shape_23.setTransform(102.6,-12.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAdBRQgDgJgCgQQgCgQAAgKIAAgIIABgJQAAgSgKAAQgNAAgKAKQgFAHgKASQAAAogDAIQgDAHgHAAQgEAAgDgDQgEgDAAgFIABgEQABgDAAgNIABgQIAAhNIABgSIgBgKIgBgKQAAgFADgDQADgDAFAAQAIAAACAKQACAKAAAIIgBAYIgBAXIAAAKQAJgMAKgGQAIgGAMAAQARAAAHAMQAFAIAAARIABAVIACAWQACANACAJIABAEQAAAEgEADQgDADgEAAQgIAAgCgIg");
	this.shape_24.setTransform(90.1,-15.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgGBLQgDgCAAgFIAAgMIABgNIgCg8IgYgCQgKgBAAgJQAAgFADgEQADgCAFAAIAWACIAAgQIgBgMQAAgFADgDQADgDAFAAQAIAAABAPIAAAKIAAAGIAAAHIAPgBQAMAAADABQAHABAAAJQAAAFgDADQgDACgFAAIgFAAIgGAAIgOABIACA+IAAAFIAAAFQAAAYgLAAQgDAAgDgDg");
	this.shape_25.setTransform(78.4,-14.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgdA7QgQgGAAgLQAAgEADgDQADgDAFAAQADAAAFAFQADACAJACIAMABQAHAAAHgCQAKgDAAgHQAAgPgUgEIgKgDQgOgDgGgFQgJgEAAgMQAAgWAWgJQAGgEAMgEIAUgGQAFgCAFAAQAFAAADADQADADAAAEIABAKIABAJQAAAFgDADQgDADgEAAQgGAAgDgEQgBgDgBgJIgZAIQgPAGgBALIAHACQAWAEAMAHQASAKAAAVQAAASgPAJQgNAHgRAAQgOAAgNgFg");
	this.shape_26.setTransform(61.1,-13.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AAZA8QgMAAgHgdIgEgZIgCgWIgIASIgRAtQgBAEgDACQgDAGgHAAQgIABgIghQgEgQgEgbIgCgQIgCgQQAAgFAEgDQADgDAEAAQAIAAACAJIADAQIABAQIAHAuIAYhKQAEgMAHAAQAIAAADANIAHAnQAEAZAEAPIAIgdIANg5QACgGAIAAQAEAAAEADQADADAAAEIgBAFQgJAjgNAqQgDAKgHAKQgDAGgGAAIgBAAg");
	this.shape_27.setTransform(48.5,-12.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgfAtQgPgPAAgZQgBgWANgTQAPgVAZAAQAVAAALATQAJAQAAAWQAAAWgNARQgNAUgVgBQgSAAgNgNgAgSgVQgHAMAAAOQAAAPAIAKQAHAGAKABQAKgBAHgHQAJgJABgQQABgogYAAQgNAAgJAPg");
	this.shape_28.setTransform(35.1,-12.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AAdBRQgDgJgCgQQgCgQAAgKIAAgIIABgJQAAgSgKAAQgNAAgKAKQgFAHgKASQAAAogDAIQgDAHgHAAQgEAAgDgDQgEgDAAgFIABgEQABgDAAgNIABgQIAAhNIABgSIgBgKIgBgKQAAgFADgDQADgDAFAAQAIAAACAKQACAKAAAIIgBAYIgBAXIAAAKQAJgMAKgGQAIgGAMAAQARAAAHAMQAFAIAAARIABAVIACAWQACANACAJIABAEQAAAEgEADQgDADgEAAQgIAAgCgIg");
	this.shape_29.setTransform(23.3,-15.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgdA7QgQgGAAgLQAAgEADgDQADgDAFAAQADAAAFAFQADACAJACIAMABQAHAAAHgCQAKgDAAgHQAAgPgUgEIgKgDQgOgDgGgFQgJgEAAgMQAAgWAWgJQAGgEAMgEIAUgGQAFgCAFAAQAFAAADADQADADAAAEIABAKIABAJQAAAFgDADQgDADgEAAQgGAAgDgEQgBgDgBgJIgZAIQgPAGgBALIAHACQAWAEAMAHQASAKAAAVQAAASgPAJQgNAHgRAAQgOAAgNgFg");
	this.shape_30.setTransform(11.1,-13.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FF0000").s().p("AguBSQgKgJAAgjIAAgPIABgSIgBgEQAAgCACgDIACguIgBgLIgBgNQAAgMALAAQAEAAADADQANgEAMgBQALgCAIAAQAaAAAQAGQAHADAAAHQAAAFgDADQgDAEgEAAIgEAAQgSgGgRAAQgIAAgJACIgXAFIABALIgBApIAtgFIAZgBQAFAAADACQADADAAAFQAAAIgKABIgZADIgwAEIAAAPIgBAMQAAAYAEAEQACADAPAAIASAAIAUgBIAGAAIAGgBQAMAAAAALQAAAKgJABQgLACgfAAQghAAgKgJg");
	this.shape_31.setTransform(-7,-15.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FF0000").s().p("AgqBKQgUgJAAgQQAAgFADgDQADgDAEAAQAGAAAEAGQAFAIAFADQAJAGARAAQAPAAAOgHQASgJAAgQQAAgOgPgIQgNgHgRAAQgRAAgMgGQgPgIAAgQQAAgUAVgPQAVgPAUAAQALAAANADQARAFAAAHQAAAJgKAAIgPgCQgKgCgGAAQgPAAgMAIQgMAJAAALQAAAJAQAEQAGABAPABQAZACANAOQANAKAAASQAAAagXAPQgVANgZAAQgUAAgQgHg");
	this.shape_32.setTransform(-21.7,-15);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FF0000").s().p("AhHBTQgDgDAAgFIABgNIABgOIAAgUIAAgUIAAgTIAAgWIgBgUIgCgUQAAgFAEgEQAEgEAGAAQAGAAAIANQAbAoAUAaQAZAdAeAdIAAgOIAAgNQAAgtgEgcIgCgMQgDgGAAgFQAAgNAMAAQASAAAABGIAAAiIAAAjIgCASQgCAKgKAAQgFAAgIgHQgtgpg2hNIgBAZIAAAXIAAAaIABAbQAAAdgMAAQgFAAgEgEg");
	this.shape_33.setTransform(-38.1,-15.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FF0000").s().p("AguBSQgKgJAAgjIAAgPIABgSIgBgEQAAgCACgDIACguIgBgLIgBgNQAAgMALAAQAEAAADADQANgEAMgBQALgCAIAAQAaAAAQAGQAHADAAAHQAAAFgDADQgDAEgEAAIgEAAQgSgGgRAAQgIAAgJACIgXAFIABALIgBApIAtgFIAZgBQAFAAADACQADADAAAFQAAAIgKABIgZADIgwAEIAAAPIgBAMQAAAYAEAEQACADAPAAIASAAIAUgBIAGAAIAGgBQAMAAAAALQAAAKgJABQgLACgfAAQghAAgKgJg");
	this.shape_34.setTransform(-53.6,-15.5);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FF0000").s().p("AgGBOQgEgDAAgFIABgEIAAgFIAAgQIgBgQQAAgPgCgaQgDgeAAgNIgKAAQgYAAgNgEQgJgCAAgIQAAgFADgDQADgEAFABIARABIASACIATAAIASgBIAZABIAYACQAFAAADADQADADAAAFQAAAEgDADQgDAEgFAAIgYgCIgZgBIgIAAIADAwQADAdAAASIAAALIABALQAAAIgCAFQgDAHgGAAQgDAAgDgDg");
	this.shape_35.setTransform(-67.3,-15.5);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FF0000").s().p("AgxBTQgEgFAAgEIAAggIACgqIACgsQAAgKABgUQABgFADgBQAOgGATAAQARAAARANQAUAQAAAWQAAAbgVAOQAQAGAIAJQAIAIAAAKQAAANgOANQgKAIgLAEQgWAJglAAQgFAAgEgDgAggAqIAAAXQAcgBAQgIQAHgCAHgHQAHgFAAgDQAAgFgOgGQgKgFgJgDIgKgBIgFAAIgEAAIgMgBIgBAYgAgbg+IgBASIgCAqIARABQAOgCAKgIQALgJAAgPQAAgLgLgJQgLgIgLgBIgQACg");
	this.shape_36.setTransform(-88.7,-15.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FF0000").s().p("Ag1BRQgEgDAAgFIAAgZIgBgaIACgbQACgUAAgJIgBgRIgBgQQAAgGAEgFQAEgFAHAAIAaACQAOACAIAFQAsAYAAAhQAAAQgPALQgMAKgSAFQAiASAQAUQADADAAAEQAAAFgDADQgDADgFAAQgEAAgDgDQgkgjgpgMIAAAVIABAVQAAAFgDADQgDADgFAAQgEAAgDgDgAghgvIABANIgCAWIgCATIAFAAIAFAAQAaAAANgHQAGgCAFgFQAFgGAAgEQAAgPgRgNQgNgMgRgCIgQgBg");
	this.shape_37.setTransform(-102.8,-15.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FF0000").s().p("AguBSQgKgJAAgjIAAgPIABgSIgBgEQAAgCACgDIACguIgBgLIgBgNQAAgMALAAQAEAAADADQANgEAMgBQALgCAIAAQAaAAAQAGQAHADAAAHQAAAFgDADQgDAEgEAAIgEAAQgSgGgRAAQgIAAgJACIgXAFIABALIgBApIAtgFIAZgBQAFAAADACQADADAAAFQAAAIgKABIgZADIgwAEIAAAPIgBAMQAAAYAEAEQACADAPAAIASAAIAUgBIAGAAIAGgBQAMAAAAALQAAAKgJABQgLACgfAAQghAAgKgJg");
	this.shape_38.setTransform(-116.5,-15.5);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FF0000").s().p("AgSBOQgNghgQg7IgJgeQgGgWAAgHQAAgFAEgDQADgDAEAAQAIAAADAJIADATIALAkQAKAmAKAdIABgBIAbhMIAJgbQAGgQAGgIQAEgEAFAAQAEAAADADQAEADAAAFQAAADgCADQgHAKgEALIgIAYIgdBMQgFAOgHANQgBAGgHAAQgIAAgDgIg");
	this.shape_39.setTransform(-130.2,-15.2);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AAlA3IgHghIgdAFIgaAGIgTApQgDAGgGAAQgEAAgEgDQgDgDAAgFQAAgFARgiQgCgDAAgDQgBgJALgCQAMgWATgdQAXgpAHgBQAIABADALIAHAkIAQBKIAGARQADAIAAADQAAAFgDADQgEACgEAAQgJAAgIgZgAgMAHQAMgDAZgEIgJgog");
	this.shape_40.setTransform(-152.8,-15.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-162.7,-33.6,325.5,67.3);


(lib.Tween4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.3,1,1).p("AgBA6QgBgBgBAAQgkgVgpgVQgxgXgngTQglgSgfgbQgDgBgDgBQglgOglgYQgmgYgqgSQgrgTgogaQglgXglgUQgogUgigaQgkgcgCglQABgGACgEQAAgCABgBQAIgWAUgNQAMgIAPgFQAwgQAkAaQACACADACQAIAHAIAGQAdAZAtAbQApAZAlAVQAMAHAMAHQAZAOAXAPQAlAYAkAUQAtAZAhAZQApAfAkAaQAJAGAJAGAHHDoQAVgOAbABQABAAABAAQAZAAAVAIQAQAFANgEAJYFKQACgDACgDQABAAAAgBQACgDACgCQASgQAWAJQAWAJgHAdQgFAWgRARQgCABgBABAI1FwQgEABgFAAQgWABgMgUQgFACgFACQgWAIgHggQgKAHgMgDQgTgFgJgWAJOFYQgHAPAAATQABAjAXACQgBABgBAAQgTAMgKgQQgOgUADgYQAAAAABgBQAHgDAGgGQAGgHAFgHgAJXFLQgCACgBACQgEAEgCAFAJ+GHQgNAMgSAMADoC2QADgGAFgGQAQgOARgSQAIgKAJgIQAAgBABgBQADgDADgCQABgBABgBQAQgPAaADQAKABAIAHAAkgoQAjAdAlATQAlAVAnAbQAVAOAVAOAFoBsQAIgBAKADQADABADABAEzC9QANgRARgOQATgPARgLQAMgIAKACQAKABAIANQAFAIgBAIQALACAFATQAHAYgJANQAEADAFADQADACAEADQAEADAEAEAFmBtQgZAEgNAUQgLASgSAPADPCrQgfgQgqgSQgCgBgCgBQgbgOgTgLQglgXgqgZAGQEZQAHgMAJgIQASgQASgMQABgBACAAAF/EQQgCAAgBgBQgQgHgOgLQAUgMAQgSQAMgLAOgLQADgDAEgDAGhCcQgIgCgLAHQgTALgTANQgSAMgSAPAHjFKQABAAABgBQAQgMAFgVAIKFeQAFgDAFgDQAQgLAHgQAEoENQgBgMgNgLQgQgPgUgLQgRgJAAgNQgBgIADgI");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFCC99").s().p("Ah/CLIAEAAIAAADgABOBsIALgGQAPgLAHgQQgHAQgPALIgLAGIgKAEQgWAIgGggIABAAQAQgNAGgUQgGAUgQANIgBAAQgKAHgMgDQgSgFgJgWIAAAAIgBABQgDAEgEACQgWAKgKgcIABgCIAGgNQAHgLAKgJQASgQAQgKIACgBQAVgNAbAAIACAAQAZAAAWAIQAPAGANgEQAbAOAXAUQAOAMAOAGIgTAKQgSAKgMAPIgCACQgFAFgDAHIgDADIgGAJIgLAOQgFAHgIACIgBABIgIACIgCAAQgWAAgLgUgAiRAbQgCgMgNgLQgQgMgUgLQgQgKgBgMQgBgJAEgHIAAgBQADgGAGgFQAPgPARgSIARgSIABgBIAGgGIACgCQAQgOAaADQAKAAAIAIIAAAAIAAABIAAAAIABAAQAIgBALACIAFACQAIAAADAIIAAAGIgEAAIAAAAIAAAAQgIAAgKAGQgRALgSAPQgRAOgOARQAOgRARgOQASgPARgLQAKgGAIAAIAAAAIAAAAIAEAAQAKACAIAMQAFAIgBAIQAMACAFATQAGAYgJANIgTgNIAHgFIgHAFQgOALgMAMQgQAQgTALQANALAQAHIADABIADADQgCAIgBAJIgFAlQgegrgzgRgAgrhPIgnAYQgSAMgRAPQARgPASgMIAngYIABgBIABAAIABgBQAFgCAFgBIACAAIAAAAIADAAIgDAAIAAAAIgCAAQgFABgFACIgBABIgBAAIgBABgAh5hqQgMARgRAQQARgQAMgRQANgUAZgFQgZAFgNAUg");
	this.shape_1.setTransform(44.4,24.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#993300").s().p("AJAGcQgOgUADgYIABgBQAHgDAGgGIALgOQgHAOAAARIAAADQABAjAXACQgXgCgBgjIAAgDQAAgRAHgOIAKgOIAEgGIABgBIAEgFQASgQAWAJQAWAJgHAdQgFAWgRARIgDACIgBABQgNAMgSAMIgCABQgIAFgHAAQgIAAgGgJgAGCETIABgBIgEgCIgDgBQgQgHgOgLQAUgMAQgSQAMgLAOgLIATANIAJAGIAHAFIAIAHIgDABQgSAMgSAQQgJAIgHAMQgIgBgGgFgADWCvIgGgEIgBAAQgfgQgqgSIgEgCIgugZIhPgwIgGgEIgCgBQgkgVgpgVIhYgqQglgSgfgbIgGgCQglgOglgYQgmgYgqgSQgrgTgogaQglgXglgUQgogUgigaQgkgcgCglIADgKIABgDQAIgWAUgNQAMgIAPgFQAwgQAkAaIAFAEIAQANQAdAZAtAbQApAZAlAVIAYAOIAwAdQAlAYAkAUQAtAZAhAZQApAfAkAaIASAMQAhAYAiATQAjAdAlATQAlAVAnAbIAqAcIAfASQAPAKASAIIgRASQgRASgQAOQgFAGgDAGIgBAAIgRgHg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-67.6,-43.1,135.2,86.3);


(lib.skiptomenu = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AATApQgLAGgMAAQgMAAgHgFQgJgGgBgKQgEgYABgQQgBgMADgPQABgIAHAAQAEAAADADQACACAAAEIgBANIgBANIABAXQABALACAGIAGADIAFAAQAKAAANgDIAAgSIgBgPQAAgTACgOQABgIAIAAQADAAADACQADADgBADIgBAhIAAARIAAATIAAAGIAAAGQABAEgDACQgDADgDAAQgHAAgCgJg");
	this.shape.setTransform(16.7,0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AAVAqIgDgTIgBgTIABgGIAAgJQAAgSgHgBQgKAAgHAMQgIALgFAOIgBAIIAAAJIAAAIIABAIQAAAEgCADQgDACgEAAQgDAAgDgCQgCgDAAgEIgBgIIAAgIIABgYIABgYIAAgIIAAgJQAAgDACgDQADgDADABQAIAAABALIAAAKQAPgUAOAAQAOAAAFANQAEAIAAAQIAAAJIAAAGIACATQACAMAAAHQAAAEgCADQgDABgEAAQgHABgBgJg");
	this.shape_1.setTransform(7.5,0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgdAmQgNgMAAgTQAAgVALgQQAMgQATgBQAOAAAJAGQALAFAAANQAAAJgKAHQgEADgOAFIggAQQAFAIAHADQAIADAIAAQAGAAAIgBQAKgDADgFQADgFAEAAQADAAACADQACACAAADQAAAKgPAGQgOAHgMAAQgSAAgNgKgAgRgWQgHAIgDAPIAbgLQAOgIAGgFQgHgIgNAAQgKABgHAIg");
	this.shape_2.setTransform(-2.2,0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgEAzQgCgCAAgEIgCggIgCgdQAAgJgDgGQgGADgHAHIgKALIgEAGIgBANIgBAPIAAAIIABAHQAAADgCADQgDACgEAAQgKAAAAgWIABgQIABgOIAAgOIgBgOQAAgUAJAAQADAAADADQADADAAAEIgBAFIAAAFIAAAJQAFgJAIgIQAJgHAHAAQANAAAEAOQAEgHAHgDQAHgDAIAAQAPAAAFAQQACADACAVIAGAxQABADgDADQgDACgDAAQgIAAgBgIIgDgbIgDgZQgBgGgCgGQgDgIgDAAQgEAAgJAGQgIAFgDADIABAQIACAWQACAOAAAJQAAAEgCACQgDADgEAAQgBAAgDgDg");
	this.shape_3.setTransform(-14.1,0.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(2,1,1).p("AkZh7IIzAAIAAD3IozAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AkZB8IAAj3IIzAAIAAD3g");

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAVAuQgMAGgOAAQgMAAgJgGQgJgGgBgMQgEgZAAgSQAAgNADgRQABgJAIAAQAEAAADADQADADAAAEIgCAOIgBAPIABAZQABAMACAHIAGADIAGAAQALAAAPgEIAAgTIAAgRQAAgVABgPQABgJAJAAQAEAAADACQADADgBAEIgBAlIAAATIAAAVIAAAGIAAAHQAAAEgCACQgDADgEAAQgIAAgCgJg");
	this.shape_6.setTransform(18.3,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AAXAvIgDgWIgBgVIAAgHIABgJQAAgVgIAAQgLAAgIANQgJALgFAQIgBAKIAAAJIAAAJIABAJQAAAEgDADQgCACgFAAQgEAAgCgCQgDgDAAgEIgBgJIAAgJIABgaIACgbIgBgJIAAgJQAAgFADgCQACgDAEAAQAJAAABANIAAALQARgWAPAAQAPAAAGAOQAFAJAAASIAAAKIAAAHQAAAIACAMQACANAAAIQAAAEgDADQgDADgEAAQgIAAgBgJg");
	this.shape_7.setTransform(8.2,0.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AggApQgPgMAAgWQAAgXAMgRQAOgSAVAAQAPAAAKAFQANAHAAAOQAAAJgMAIQgEAEgQAFIgjASQAFAIAJAEQAIAEAJAAQAHAAAIgDQALgDAEgFQADgFAEAAQADAAADACQADADAAADQAAALgRAIQgPAGgOAAQgVAAgNgLgAgTgZQgHAJgEARIAdgMQAQgJAIgGQgJgIgOAAQgLAAgIAJg");
	this.shape_8.setTransform(-2.4,0.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgEA5QgDgDAAgFQAAgLgCgXQgDgVAAgMQAAgKgCgGQgHADgHAHIgMANIgEAGIgCAPIgBARIABAIIABAIQAAAEgDACQgDADgEAAQgLAAAAgZIACgRIABgPIgBgQIgBgPQAAgWAKAAQADAAAEADQADAEAAADIgBAGIAAAGIAAAKQAFgKAKgJQAJgIAHAAQAPAAAEAPQAGgHAHgDQAHgEAKAAQAQAAAGARIAEAcIAHA1QAAAEgDADQgDACgEAAQgIAAgBgIQgCgLgCgTIgDgcIgDgNQgEgJgEAAQgDAAgKAGQgJAGgDADIAAASIADAYQACAQAAAJQAAAFgCADQgDACgEAAQgCAAgDgCg");
	this.shape_9.setTransform(-15.6,0.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#000000").ss(2,1,1).p("AE3CJIptAAIAAkRIJtAAg");
	this.shape_10.setTransform(0,0.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#00FFFF").s().p("Ak2CJIAAkRIJsAAIAAERg");
	this.shape_11.setTransform(0,0.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AATApQgLAGgMAAQgMAAgHgFQgJgGgBgKQgEgYABgQQgBgMADgPQABgIAHAAQAEAAADADQACACAAAEIgBANIgBANIABAXQABALACAGIAGADIAFAAQAKAAANgDIAAgSIgBgPQAAgTACgOQABgIAIAAQADAAADACQADADgBADIgBAhIAAARIAAATIAAAGIAAAGQABAEgDACQgDADgDAAQgHAAgCgJg");
	this.shape_12.setTransform(16.7,1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAVArIgDgUIgBgTIABgHIAAgHQAAgUgHAAQgKAAgHAMQgIALgFAOIgBAJIAAAIIAAAIIABAIQAAAEgCACQgDACgEAAQgDAAgDgCQgCgCAAgEIgBgIIAAgIIABgYIABgYIAAgJIAAgIQAAgEACgCQADgCADgBQAIAAABAMIAAAKQAPgTAOgBQAOAAAFANQAEAIAAARIAAAIIAAAGIACAUQACALAAAHQAAAEgCACQgDACgEABQgHgBgBgHg");
	this.shape_13.setTransform(7.5,0.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgdAlQgNgLAAgTQAAgVALgPQAMgSATABQAOAAAJAEQALAHAAAMQAAAJgKAHQgEADgOAFIggAQQAFAHAHAEQAIAEAIAAQAGgBAIgCQAKgDADgEQADgFAEAAQADAAACACQACACAAAEQAAAJgPAIQgOAFgMAAQgSAAgNgKgAgRgWQgHAIgDAPIAbgLQAOgIAGgGQgHgGgNgBQgKAAgHAJg");
	this.shape_14.setTransform(-2.2,0.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgEAzQgCgCAAgEIgCggIgCgdQAAgJgDgGQgGADgHAHIgKALIgEAGIgBANIgBAPIAAAIIABAHQAAADgCADQgDACgEAAQgKAAAAgWIABgQIABgOIAAgOIgBgOQAAgUAJAAQADAAADADQADADAAAEIgBAFIAAAFIAAAJQAFgJAIgIQAJgHAHAAQANAAAEAOQAEgHAHgDQAHgDAIAAQAPAAAFAQQACADACAVIAGAxQABADgDADQgDACgDAAQgIAAgBgIIgDgbIgDgZQgBgGgCgGQgDgIgDAAQgEAAgJAGQgIAFgDADIABAQIACAWQACAOAAAJQAAAEgCACQgDADgEAAQgBAAgDgDg");
	this.shape_15.setTransform(-14.1,1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#000000").ss(2,1,1).p("AEah7IAAD3IozAAIAAj3g");

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#0066CC").s().p("AkZB8IAAj3IIzAAIAAD3g");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},1).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12}]},1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-29.2,-16.9,58.6,30.5);


(lib.general_buttoncolor = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{resetRed:1});

	// timeline functions:
	this.frame_0 = function() {
		this.play();
	}
	this.frame_8 = function() {
		this.gotoAndPlay("resetRed");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(8).call(this.frame_8).wait(2));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#D5FFD7","#61EF01","#1DA400","#004A00"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgvAAgjgjQgjgjAAgwQAAgvAjgjQAjgjAvAAQAwAAAjAjQAjAjAAAvQAAAwgjAjQgjAjgwAAIAAAAg");
	this.shape.setTransform(11.9,11.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FFFFFF","#EC0000","#9D0000","#480000"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgvAAgjgjQgjgjAAgwQAAgvAjgjQAjgjAvAAQAwAAAjAjQAjAjAAAvQAAAwgjAjQgjAjgwAAIAAAAg");
	this.shape_1.setTransform(11.9,11.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},8).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,23.7,23.6);


(lib.Copyright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAbAHIgDgKIgEAKQgEAIgDAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBgBAAgBIgCgIIgBgHQgGASgCAAIgDgBIgBgCIABgCQADgFABgFIACgNQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAEAAACAJIADAKIACgGIADgJQADgEACAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAEAKIACAGIACAIIABACIgBACIgCABQgDAAgDgJgAgTANIgBgIIAAgGIgBgHIgFAAIgGAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAgBAAAAQAAgBAAgBQAAAAABgBQAAAAABgBQAAAAABAAIAFABIAEAAIAPAAIADgBIAEAAQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAABAAAAQAAAAAAABQAAAAgBAAIgOAAIAAAIIABAFIABAEIABAEIgCACIgCABQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAgBAAAAg");
	this.shape.setTransform(57.3,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgLAYQgGgDgBgEIABgDQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAIAEACIAEABIAFABIAFgBQADgBAAgDQABgGgJgCIgCgBIgIgDQgEAAAAgFQAAgKAIgEIAHgCIAIgDIAEgBIADABIABAEIABADIAAAEIgBADIgCABQgBAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIgCgFIgJADQgFADgBAEIADABQAIACAFACQAHADAAAJQAAAHgGAEQgFADgGAAQgFAAgGgCg");
	this.shape_1.setTransform(51,2.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgLATQgHgGABgKQAAgGAFgKQAHgKAGAAQAEAAAGACQAGACABAEIgBADQgBAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgDgBIgBgBQgDgCgGAAQgCAAgFAIQgDAHAAADQAAAGADAEQAEADAEAAIAGgCIAEgCIACgBIAEABIABADQgBADgGADQgGADgEAAQgHAAgGgFg");
	this.shape_2.setTransform(46.6,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgDAfQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAAAIAAgJIAAgIIAAgKIAAgIQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBIACgBIACABQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABIAAAIIgBAKIAAAIIABAJQAAAAAAAAQAAABgBAAQAAABAAAAQAAAAgBAAIgBABIgDgBgAgBgXQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQAAAAAAAAQAAAAAAgBQABABAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBAAAAgBg");
	this.shape_3.setTransform(43.1,1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAKAVIgBgJIgBgKIABgDIAAgDQAAgKgEAAQgFAAgCAFQgEAGgCAGIgBAEIAAAFIAAADIAAAFIgBADIgDABIgDgBIgBgDIAAgFIgBgDIABgMIAAgLIAAgFIAAgEIABgDIAEgBQAEAAAAAFIAAAGQAHgKAGAAQAHAAADAGQACAEAAAJIAAAEIAAACIABAKIABAJIgBADIgDABQgEAAgBgEg");
	this.shape_4.setTransform(39.5,2.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_5.setTransform(34.8,2.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AALAhIgBgLIgBgKIAAgDIAAgEQAAgGgEAAQgFAAgDADIgGAKQAAARgCACQAAABgBABQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDIABgBIAAgHIAAgHIAAgeIABgHIgBgFIAAgEQAAAAAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQAEAAAAAEIABAIIAAAKIAAAJIAAAEQADgFAEgCQACgDAFAAQAHAAADAFQABADABAGIABAJIAAAIIACAKIAAABQAAABAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIgDABQgEAAgBgDg");
	this.shape_6.setTransform(30,1.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgLATQgHgGABgKQAAgGAFgKQAHgKAGAAQAEAAAGACQAGACABAEIgBADQgBAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgDgBIgBgBQgDgCgGAAQgCAAgFAIQgDAHAAADQAAAGADAEQAEADAEAAIAGgCIAEgCIACgBIAEABIABADQgBADgGADQgGADgEAAQgHAAgGgFg");
	this.shape_7.setTransform(25,2.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgOATQgGgGAAgKQAAgKAFgHQAGgJAJAAQAGABAFACQAGADAAAHQAAAEgFADIgKAEIgOAHQACAEAEABQAEADACAAIAIgBQAFgCABgDQABAAAAAAQAAgBABAAQAAAAABAAQAAAAAAAAIADAAIABADQAAAFgIADQgGADgHABQgIgBgGgEgAgIgKQgDAEgCAGIANgFQAGgDAEgDQgEgDgGgBQgEAAgEAFg");
	this.shape_8.setTransform(20.3,2.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAaAgIgCgGIgBgIQgCgHgEgWIgJAYIgDAJIgDAIQgBAEgCAAQgDgBgBgDIgCgEIgBgFIgIgfIgCAHIgFAWIgCAMQgBAEgDAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgEQAAgHADgLIAFgPIADgOQACgKABgDQACgCADAAQACAAACADQACAEABAMQADAOAFAPQAFgPAEgSIACgGIACgHQABgDADAAQAEAAACAIIACAKQADASADAOIACAHIACAHQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgCABQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBgBg");
	this.shape_9.setTransform(13.8,1.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgQAUIAAgdIAAgEIABgFQAAgEADAAQAFAAAAAHQAHgIAKAAQADAAACADQACACAAAGIAAADQgBAFgEAAQgEAAAAgEIAAgDIAAgEQgHABgCADQgEADgDAGIABAWQAAAEgFAAQgEAAAAgEg");
	this.shape_10.setTransform(5.1,2.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_11.setTransform(0.5,2.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgBAZQAAAAgBAAQAAgBAAAAQAAAAAAgBQgBAAAAgBIgBgPIgBgOQAAgFgBgCQgDABgDADIgFAGIgDADIAAAGIgBAHIABAEIAAADQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABQgFAAAAgLIAAgIIABgGIgBgHIAAgHQAAgKAFAAIACACQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAADIgBACIAAAFQADgFAEgDQAFgEADAAQAGAAACAHQACgEADgBQAEgCAEAAQAHAAADAIIACAMIADAYIgBADIgDABQgEAAgBgEIgBgOIgCgLIgBgGQgCgEgCAAIgFADIgGAEIAAAHIABALIABALIgBADIgDACQAAAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBg");
	this.shape_12.setTransform(-5.2,2.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgBAZQAAAAgBAAQAAgBAAAAQAAAAAAgBQgBAAAAgBIgBgPIgBgOQABgFgCgCQgDABgDADIgFAGIgCADIgBAGIgBAHIABAEIABADQAAABgBAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABQgFAAAAgLIABgIIAAgGIAAgHIgBgHQAAgKAEAAIADACQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAADIgBACIAAAFQADgFAEgDQAFgEADAAQAGAAABAHQADgEADgBQADgCAFAAQAHAAADAIIACAMIADAYIgCADIgCABQgEAAgBgEIgCgOIgBgLIgBgGQgCgEgCAAIgFADIgGAEIAAAHIABALIABALIgBADIgDACQAAAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBg");
	this.shape_13.setTransform(-12.2,2.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_14.setTransform(-18.1,2.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgQAUIAAgdIAAgEIABgFQAAgEADAAQAFAAAAAHQAHgIAKAAQADAAACADQACACAAAGIAAADQgBAFgEAAQgEAAAAgEIAAgDIAAgEQgHABgCADQgEADgDAGIABAWQAAAEgFAAQgEAAAAgEg");
	this.shape_15.setTransform(-22.4,2.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgVAeQgFgGgBgMQABgMAFgKQAFgMAIgIQAHgEAEAAQAEAAAGACQAIAEAAADIgBADIgEABIgCgBQgHgDgEAAQgDgBgCAEIgGAGQgKAOAAAOQABAIACADQACAEAIAAQAGgBAGgFQAGgEACgLQgMABgGAEIgDABQAAgBAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQAIgEAXAAIADABIABACQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQgDANgIAJQgJAHgKABQgKgBgGgFg");
	this.shape_16.setTransform(-27.7,1.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgNAhIgBgDIACgJIAKgWQAFgOAHgIIABgBIgVAAIgJgBQgFAAAAgEQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAQAAIAPABIAIAAQAFAAAAACQAAADgDADIgEAFQgGAGgFAKIgHAPIgCAKIgEAKQgBABAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIgDgBg");
	this.shape_17.setTransform(-36.2,1.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AABAiIgHAAIgFgBQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQgBgEAIAAIACAAIABAAIAAgHIgBgGIABgPIABgRQgFAFgCAAIgDgBIgBgDQAAgDADgCIAHgGQACgEAEAAQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAADIAAADIAAAEIAAAEIgBAPIgBANIAAAGIABAGIAFAAQAAAAAAAAQABAAAAABQABAAAAAAQAAAAABABIAAADIAAADIgDABg");
	this.shape_18.setTransform(-41,1.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgSAXQgFgKAAgNQAAgMAGgKQAHgMAKAAQAMABAGAJQAGAJAAANQAAARgGAKQgGAJgMAAQgMABgGgMgAgLgRQgEAIAAAJQAAAMAEAHQAEAHAHAAQAIABAEgLQADgIAAgJQAAgMgDgGQgEgGgIAAQgGAAgFAIg");
	this.shape_19.setTransform(-45.9,1.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AANAhIgDgBIgHAAIgFABIgFAAIgFAAIgBAAIgCAAQgDAAgBgDIAAgFQAAgKAGgHQACgDALgFIAHgHQADgEAAgGQAAgDgDgCQgDgCgDAAQgDAAgDADIgGAEIgDACQgFAAAAgEQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAFgFAEgCQAFgDAEAAQAHAAAFAEQAGAEAAAHIgBAIIgEAHQgDACgIAFQgGAFgDADQgFAFABAHIAJgBIALAAIAGABQAEABAAADQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAIgDABIgDAAg");
	this.shape_20.setTransform(-51.3,1.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgeAAQAAgKALgJQALgKALAAQAOAAAHAIQAHAIAAAMQAAAJgJAKQgKALgMAAIAAABQgeAAAAgegAgOgOQgIAGAAAIQAAAMAGAFQAGAEAKAAQAJAAAIgIQAGgIAAgGQAAgJgEgFQgFgGgIAAIgCAAQgKAAgIAHgAgKAJQgGgEAAgFQAAgGAIgFQAGgFAFAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAIgCgBIgBAAQgDAAgEADQgEACAAADQAAABADACIAFABQABAAAEgCIAEgCIADAAIABADQAAADgEADQgGADgDAAQgFAAgFgDg");
	this.shape_21.setTransform(-57.7,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.3,-7.1,126.6,16.6);


(lib.Background = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF3366").ss(3,1,1).p("EAlaAVAMhKzAAAMAAAgp/MBKzAAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#DDF5FF","#3399FF"],[0,1],0,-134.5,0.1,134.6).s().p("EglZAVAMAAAgp/MBKzAAAMAAAAp/g");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-240.9,-135.9,481.9,272);


(lib.goNext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,11.3).s().p("AhLAqQghgSACgYQgCgXAhgRQAggTArAAQAsAAAgATQAfARAAAXQAAAYgfASQggASgsAAQgrAAgggSg");
	this.shape.setTransform(22.8,8.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.502)").s().p("AhThcICoBdIioBcg");
	this.shape_1.setTransform(25.1,20.4);

	this.blinker = new lib.general_buttoncolor();
	this.blinker.setTransform(23.4,20.1,1.5,1.5,0,0,0,11.9,11.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,14.8).s().p("AhiA3QgrgXACggQgCgfArgWQApgYA5AAQA5AAAqAYQAqAWAAAfQAAAggqAXQgqAXg5AAQg5AAgpgXg");
	this.shape_2.setTransform(23.4,8.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("rgba(0,0,0,0.502)").ss(1,1,1,3,true).p("AAACxQhIAAg0g0Qg0g1AAhIQAAhHA0g1QA0g0BIAAQBJAAA0A0QA0A1AABHQAABIg0A1Qg0A0hJAAg");
	this.shape_3.setTransform(23.3,20.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["rgba(103,103,103,0.839)","rgba(134,134,134,0)"],[0.678,0.918],-0.8,0,0,-0.8,0,24.9).s().p("AisCkQhFhEAAhgQAAhgBFhDQBEhFBhAAQBfAABBAwQBCAwAVCqQAVCskMAbQhhAAhEhFgAgHCQQBEAAAzgwIABAAIADgEQA0g0AAhHQAAhJg0g0IgFgFIgBgBQgyguhDAAIAAAAIgBAAIAAAAIgBAAQhEAAgyAuIgBABIgCACIgBABIAAAAIgCACQg0A0AABJQAABHA0A0IACACIABABQAzAxBHAAIAAAAIAAAAIAAAAIAAAAQhHAAgzgxIgBgBIgCgCQg0g0AAhHQAAhJA0g0IACgCIAAAAIABgBIACgCIABgBQAyguBEAAIABAAIAAAAIABAAIAAAAQBDAAAyAuIABABIAFAFQA0A0AABJQAABHg0A0IgDAEIgBAAQgzAwhEAAIAAAAIgBAAIABAAIAAAAg");
	this.shape_4.setTransform(24.2,23.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},2).wait(1));

	// Layer 2
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#33FFFF").s().p("AioCqQhGhHAAhjQAAhiBGhGQBGhHBiAAQBjAABGBHQBHBGgBBiQABBjhHBHQhGBGhjAAQhiAAhGhGg");
	this.shape_5.setTransform(24.4,21.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0099FF").s().p("AioCqQhGhHAAhjQAAhiBGhGQBGhHBiAAQBjAABGBHQBHBGgBBiQABBjhHBHQhGBGhjAAQhiAAhGhGg");
	this.shape_6.setTransform(24.4,21.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.5,46.7);


(lib.animCarmen_ready = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_10 = function() {
		this.gotoAndPlay(1);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(10).call(this.frame_10).wait(10));

	// Layer 3
	this.instance = new lib.Tween4("synched",0);
	this.instance.setTransform(234.5,-135.5,1,1,0,0,0,46,28);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:46.1,regY:27.9,scaleX:1,scaleY:1,rotation:13.8,x:234.6},5).to({regX:46,regY:28,scaleX:1,scaleY:1,rotation:0,x:234.5},5).wait(10));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.3,1,1).p("Aovr8QAAgDAAgCQABgDAAgDQADgUADgSQAEgcAIgZQACgEABgEQAHgRALgPQAOgTAQgRQARgRAbgKQASgHAVAAQAGAAAHAAQALAAALABAkpvBQABABACAAQgBABgBAAQgQAKgRAKQAAAAgBAAQgUALgMAWQgLAUgJAUQgLAWABAgQABAGAAAGQACAWAFAUQAGAXAGAXQAIAZALAVQAJARAGAZQAAABABABQAGABAHADQAaAIAWAJQAEABAEACQABAAABAAQABABAAAAQASAFAVABQAdADAdAAQAeABALgVQAJgPAGgQQAUAMAKATQAKATAMASQANATADAbQABAIgBAGQgBAKgGAHQgEAJgHAGQgPAOghgFQgagEgSgMQgSgNgRgOQgQgNgKgUQgGgLgIgGQgTgMgRgTQAAgCgBgCAkpvBQgSgGgVgEQgRgCgSgCQAVgLAVgMQASgKAbgMQAYgLAaAFQAaAFATAKQAVAMAUAQQASAPANASQAOASAJAVQAJAVANAWQAMATANAXQAJARAKATQADAFADAFQAMAYAOAPQAMAMAMAJQAcgDAZgDQAEgBAEAAQAYgDAaACQAcACAfAAQAbABAcgBQAcAAAeABQAcACAbgDQAdgDAcACQAeACAZAEQAJABAIABQAGABAGABQAQAHAIAPQAMAXgGAdQgFAXgNAUQgOAWgKATQgKAUgMAUQgKARgUALQgBAAgBABQgCAEgDADQAAABgBABQgJALgNAJQgUAPgRAPQgJAIgKAHQgJAHgLAGQgCACgDABQAAABgBAAQgTALgRAJQgXANgUAOQgTAOgZANQgUALgYALQgFACgEACQgDABgDABQgOAJgQAGQgCABgDABQgZAJgYAHQgXAHgWAGAkpvBQAXgLAeAAQAdAAATAMQAEADAEADQAPALAQALQACABABACAD5oAQgBgBgBgBQgBgCgCgCQgDgGgGgJQgLgUgQgOQgQgOgJgTQAYgBAXgBQAegBAbgCQACAAABAAQAdgCAYgFQAFgBAEgCQgCAPgIAJQgGAHgGAHQgJAKgIALQgOATgSAOQgLAJgMAKQgGAEgGAFQgJAHgIAHQgFAFgGAFQgEAEgEADQgNALgPAKQgVANgQANQgRAOgTALQgBAAgBABQgKAFgJAFQgCABgCAAQgZADgZAGQgNACgLAFQgRAJggACQgPACgPAAQgdABgZAIQgCABgDAAQgYAGgagFQgUgEgOgPQgQAVgBAaQAAABAAABQgBACAAADQgDAJgEAJQABAEAAAEAgoq7QABAAABgBQALgCALgDQAWgGAWgHQABAAABAAQgBgBgBgBAD8n8QABABABABQgGgCgWAAQgVABgTAEQgCAAgCABQgeAHgXgEQgegEgTgKQgVgKgTgPQgUgPgPgSQgNgSgMgVIAAAAQgLgSgIgYQgIgXAHgYQgMADgMADQgRAFgPAHQADgIADgJQAEgMADgOQAHgbgEgaQgEgXgTgUQgCAEgDAFQgLAPgOAMAD8n8QgCgCgBgCAECn4QgEgCgCgCQgBgBgBgBQgBgBAAgBABYl9QgLAGgKAFQgWAMgVALQgPAIgPAHQgBABgCAAQgEACgEABIAAABQgdATgnAGAALh4QgHgPgFgTIAAAAQgIgWgMgSQgMgSgMgVQgJgSgYgNQgXgMgLgVQgLgUgFgYAARj7QgeAFgfAEABGhkQAUAEATAEQANADANABQAgACAYgGQAdgIAXgIQAWgIAWgKQAagMAVgLQAUgLAUgMQAUgMAWgNQAUgMAOgaQAMgXALgTAA7hmQABABABAAQAEABAFAAQgGgBgFgBQgYgHgXgIQgBgBAAgCAgQhjQAAgCAAgBQAAAAAAgBQAAgBABgBQABACABACIAAAAQAKAUAOAQAgNhlQANgIAKgKIABgBAgQhjQABAaAEAaQACAMAFAMAgQhjQgMASgSAOQgQALgWAQQgWAQgVAOQgXANgVATQgNALgLALQgJAJgJAJQgVAUgYAPQgTAMgLAQQAAAAAAABQARASAfAGQADAAACABQACAAABAAQAaAFAZAGQATAFAVAIQASAHAPAKQAPAJAPALQAHAFAHAFACCh/QAPAEAGgNQgMACgJAHgAFLmPQAGAWAPAPQAIAJAHAIQAPASAVANQASAMAUALQAPAJARAFQABgBAAAAQAEABADACQAQAKAQAPQAUASAHAbQAIAaADAcQADAcgHAbQgHAbgIAYQgJAbgLATQgLAXgOAUQAAABgBAAQgGAKgCAMQgFAZgNAUQgMATgLAcQgCADgBADQgIAXgIARQgKAYgJARAHhkTQgEgBgEgBAinuJQAGgGAEgIQACgFABgFQATANAOASQAOASgFAWAh9tDQgGAEgIgBQgFgBgEgBQgMgFgHgLQgEgHgEgHQgGgMgEgNQAAAAAAAAIABAAQAGgFgBgLQAAgKgBgKAh9tDQAFAAAEAAQANAAABAHQABADgCAFAhztPQgDAGgDADQgCACgCABAiHtnQgDABgCAAAi4t5QAKgHAHgJQADgJgCgIQgBgEgBgDAjutvQACgBABgBQAFABAFAEQAPAPAFAaQAEAegXAIQgZAKgbgKQgZgIgJgTQgEgJgBgIQgDgdgLgTQAJAIANAEQACABACAAQADABAEABQgCgCgCgDQgCgCgBgCQgIgLgFgOAjutvQgCgBgEAAQgLgFgBgOAj+tqQACgBACAAQAIgCAEgCAkYuAQAIAMAJAGQAEADAFABAj/rMQADgGADgFQAKgNAPgFQASgGASAIQAXAKAaAAQARABAGgJAlMueQAXACAVAEQAFABAEABQAMADAJAGAkPtoQgDgDgDgCQgCgBgBgBQgMgIgDgQAkotqQAMACANAAQAIgBAJgBAlJt5QgIgHgEgKAkqrsQgNAYASARAlJouQADgGAEgGIABAAQAFgHALgCQAAABAAABQAAAZAMASQABACABACQAIAIAFAKQAGAKAFAKQALAWAMAWQANAVACAeQABANAIAOQAEAGAEAFAlRpuQAGAaABAcQABAFAAAFAkJpSQAAABAAABQgBAAgBABQgSAIgUAGAl6nMIABAAQgEAHgEAGQACgFACgEQABgCACgDQALgSAJgSQAKgVAKgWQgBgBgBgBQACAAABgBQAAABgBACAkjoSQAGAJAFAKAlRofIAAAAQABgCABgCQACgEABgDQACgCABgCAhwp/QADgGACgGQABgBAAgCQAFgMAFgNQAAgBAAgBAovpjQgBgCgBgCQgDgQACgUQADgdgBgeQgCgbACgZQABgBAAgBAowr6QAAgBABgBAoupbQAAgDgBgDQAAgBAAgBQAAABAAABQAAADABADQACATADAVQADAYAAAbQABAdgEAcQgDAagFAbQgEAagKAWQgKAWgMASQgMATgSAPQgQAOgRANQgHAGgOACQAVAQAlABQAjAAAdgHQAcgIAYgKQAKgDAHgFAovpjQAAgCgBgDQADADAEADAmBm/QgHALgHAKQgMARgOATQgMARgLATQgLAUgIAVQgIAWgKAUQgCAEgCAEQAAABgBABQgHAOgHAPQAAACgBADQgFAWgIARQgLAWgGAXQgGAXgIAZQgJAeAMATQAEAGAHADQAZANAXgMQAUgKATgNQAXgQASgPQAOgNAOgNQARgOARgRQAVgUARgSQATgTAQgSQAPgQALgZQAFgMAEgMQAAgcgCgbAjkk4QAAABgBABAm4jXQAUgMANgSQAMgSAUgOQANgJAMgLQATgQAOgRQAAgBAAgCQAJgmAMgiAjrCXQgBABgCACQgBACgCACQgHAHgHAIQABABABABAhJDvQAEgGADgGQAAgDACgCQAAABABAAQALAIAJAIQAFAFAHABQgUAGgWgMQgHANgNAMQgPAPgSAQQgRAOgTANQAQANAKATQAKATAKAYQALAZAKAWQALAXAHAaQAGAZAIAYQAIAYAJAaQAJAaAIAXQAJAYAMAUQALAWAJAaQAKAbARAQQASAQAQASQATAUAQAQQAHACABAHQgCgEgDgDQgBgBgCgBAj/CtQgGAHgHAHQgGAHgHAHQgJAKgKAKQgSAUgTASQgRATgMAVQACAaAIAXQAIAZAHAYQAIAaANAWQANAWALAYQALAXAPAVQAOAUAQAYQAOAWANAWQAMAWAPATQAPATAQAWQAPAUASATQARATAQAPQAKAJAIAMQADAEADAEQAKAOAFAPQgSAQgVAJQgDACgDABQgVAJgVAIQgYAJgaAKQgZAJgYAHQgYAGgYAKQgEACgDACQgBAAgCAAQgXAGgPAQQgLALALAIQAFADADADQAAAAABAAQAAgBAAgBQAGgWAeADQAMACAEgDAkgB+QAAAAgBgBQAAAAABAAAj/CtQgIgEgEgFQgRgOgEgYAknPfQAFgCAFgFQAGgGAKgCQAQgCgFACAknPfQAKANATAAQAHAAAJgCQANgCAMgFAlDPVQAPAPANgFAkKPsQAJAVAdADQAfACAXgKQAXgJATgNQAWgOAXgNQAVgLAagCQAfgCAZgDQAagDAXgIAGBD0QAEACADABQABAAABAAQACAAACAAQgBABAAABQgCAAgCAAQgBAAgBAAQAAAAgBAAQgFAEgNACQgbAFgbADAGGD5QgCgDgDgCQgTgNgTgIQgDgBgCAAQAAgBAAAAQgJgDgIgCQgSgFgSgCQgggEgegDQgigDggAGQgbAFgZAMQgCABgCACQgBAAgBAAQgEASgFAQQgWgBgDgQIAAAAQAAAAAAAAQAQgIASgJAGKD3QACgCADABQgBAAAAABAFWDdQgLATgLATQgBACgBACQgKATgNARQgOASgNAUQgOAVgMAWQgLAUgOASQAXgEARARQAUATAPASQAQAUAOATQAQAWAMAXQANAYALAWQALAXALAWQAMAZAJAXQAJAZASAUQAPAQATASQALAKAMAIQADACADACQACABACABQASAKAVAOQAVAPATAMQATALAUAIQACABACAAQAVAIASAPQAWASgaARIAAAAQAHAZgjAGQAFAVgdACQAAAWgXAEQgCABgCAAQgBAAgBgBQgNgFgNgHQgIgFgHgFQgTgQgWgOQgXgPgPgQQgRgTgNgVQgFgIgEgIQgIgOgFgNQgCAAgBgCQgRgMgXgOQgXgOgTgUQgRgRgSgSQgSgTgSgSQgQgRgSgVQgSgVgPgVQgPgXgQgSQgVgWgNgUQgNgTgRgVQgQgTgMgZQgLgYgMgSQgFgdAJgWQAKgaAKgUQAKgUAIgXQABgCABgCQACgFACgGABWCbQgBABgCACQgJAJgKAKQgSATgQAMQgRANgSAPQgLAJgJAAQgDABgDgBABYCWQgDACgCACIAAAAQADgCACgCgABTCaQABABADgCQAAABgBABABcCVQABAAAAAAQAAgCAAgCQADgDACgEQALgRAHgbQAHgXACgbABdCRQgCADgDACABdCVQgDAAgCABABcCVQgDADgDADABEDvQAHgVAHgWQAHgUADgbABFDyQgBAAgBABQAAgCABgCQAAABABACgABMOlQAMgKAJgMQAOgSAFgZQAAgCAAgCQABgFgBgEQADAEADAFABMOlQgCAFgFACQgBABgBAAQAAAAgBAAQgBABAAAAQAGgFAFgEgAGfNFQAFAEADgBAKAO6QgBgDgBgDQgIgSgUgJAJoPRQAAgbgegEAKcObQgHgXgVgIAi8u6QgTANgJAV");
	this.shape.setTransform(249.2,-104.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("Ag9AYQgHgPAHgGQAEgCAHgBIALAAQADACADAHQAHAPgQAEIgJACQgIAAgCgGgAAjgHQgOgQAOgEIAGgCIAEAAQAHADAIAHIAEADQAEAHgHAEIgEACQgFACgFAAQgHAAgFgGg");
	this.shape_1.setTransform(231.4,-188.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag3A/QgZgIgJgTQgEgJgBgIQgDgbgLgTQAJAIAOAEIADABIAHACQAMACANAAIARgCIAEgBIAMgEIADgBQAFAAAFAEQANAOAFAZQAEAegVAIQgMAFgNAAQgNAAgOgFgAgHAUQgGAAgEADQgHAGAGAPQAEAIAOgEQAQgEgHgPQgEgIgDgBIgFAAIgEAAgABQAcIgJgCQgMgFgHgLIgIgMQgGgMgEgNIABAAIAAAAQAKgHAHgJQAGgGAEgIIAEgKQASANAOASQAOASgFAUIgDgCQgIgGgIgDIgEAAIgFABQgOAFANANQAIAKAPgFIADgCQgCAGgEAEIgEACQgFAEgIAAIgBgBg");
	this.shape_2.setTransform(227.1,-190.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#996600").s().p("AkoGPQgmAAgUgRQANgCAIgGIAhgbQASgPAMgTQAMgSAJgVQAKgXAFgZQAFgbADgbQADgcAAgcQgBgcgDgXIgFgpIABgCIgBgEIAFAAIgGgGIgBAAQgEgOADgUQADgdgCgdQgBgcACgZIAAgCIABgFIABgGIAFglQAFgdAIgYIADgJQAHgRAKgOQAOgUARgRQAQgRAbgKQASgHAWAAIAMAAIAXABIAjAFQATADASAHIABACIgfATIgBABQgUALgNAWIgUAnQgKAWABAgIABANQACAWAFAUIAMAtQAHAaALAUQAKARAGAXIAAACQAGAbACAbIAAAKIgCAEIgDAHIgCAEIAAAAIgEABIADACIgVAsQgIARgLASIgEAGIgEAJIgNAUIgaAkQgNARgLAUQgKATgIAVQgJAXgKAUIgDAHIgBACQgIAFgJAEQgYAKgdAHQgbAHggAAIgEAAgAg7C1IAAAAgAg3CsIAEgGIAAABIAAAAIgIAOIAEgJgAjoASIAAAAIABAEIgBACIAAgGgAjoASIAAAAgADqhEIAIgaQAGgcgEgZQgDgYgTgTQACgFgBgEQgBgHgOAAIgIAAIADgCQAEgEADgGQAHgEgEgHQAFgWgPgSQgNgSgTgNIgEgDIgegWIgJgFQgSgNgeAAQgeABgWALQgSgHgTgDIgjgFIApgWQARgLAagLQAYgLAaAFQAbAEASALQAWAMATAQQASAOAOASQANASAJAVQAKAVANAWIAYAqIAUAkIAFALQAMAYAQAPIAYAUIABADQgXAGgYAGIgVAGIgCAAIgZAHQgRAFgOAGIAFgQgAjpiFIAAgCIAAACg");
	this.shape_3.setTransform(216.5,-167.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFCC99").s().p("AkkPoQgdgCgJgVIABAAIAAAAQAHAAAIgCQANgDAMgEQgMAEgNADQgIACgHAAIAAAAIgBAAQgTgBgKgMQAFgCAFgFQAGgHAKgBIABAAIABgBIABAAIAGAAQABgBABAAQABAAAAABQAAAAAAAAQAAAAgBAAIAAAAIAAAAQABAAAAAAQAAAAAAAAQAAgBgBAAQgBAAgBABIgGAAIgBAAIgBABIgBAAQgKABgGAHQgFAFgFACQgNAFgPgQIAAAAIABgBIAAgBQAFgRAVAAIABAAIAAAAIAGABIABAAIAAAAIAAAAIABAAQAMABAEgCQgEACgMgBIgBAAIAAAAIAAAAIgBAAIgGgBIAAAAIgBAAQgVAAgFARIAAABIgBABIAAAAIgBACIgIgGQgLgHALgLQAPgQAYgGIACgBIAHgDQAYgKAYgHQAYgGAZgKIAygTIAqgRIAGgCQAVgJASgRQgFgPgKgNIgGgIQgIgMgKgKQgQgPgRgSQgSgUgPgUIgfgoQgPgUgMgWIgbgrIgegtQgPgVgLgXQgLgYgNgWQgNgWgIgaIgPgxQgIgXgCgZQAMgWARgSIAlgmIAUgUIAMgPIANgNIACABIgCgBIAOgPIAEgFIACgDIADABQAaAEAZAHQATAFAVAIQASAGAPAKIAeAVIAOAKQgBAAAAAAQAAABgBABQAAAAAAABQAAAAAAABIgGANQgIANgNAMIghAfQgRAOgTAMQAQAOAKASQAKATAKAYIAVAvQALAYAHAZQAGAaAIAXIARAyIARAxQAJAYAMAUQANAWAJAbQAKAaARAQQASARAOARIAkAlIACACIAFAGIABAJIgBAFQgFAYgOASQgJAMgMAKIgLAJQgVAIgaADIg6AFQgaACgVAMQgXAMgWAPQgTAMgXAKQgTAIgYAAIgLgBgAILPQIgagNQgIgEgHgGQgTgQgWgOQgXgOgPgQQgRgTgNgWIgJgQQgIgOgFgMIABAAIACABIADACIABAAIAAAAIABAAIgBAAIAAAAIgBAAIgDgCIgCgBIgBAAIgDgCIgogaQgXgPgTgUIgjgjIgkglIgiglQgSgWgPgVQgPgXgQgRQgVgXgNgUQgNgSgRgVQgQgUgMgZQgJgYgMgRQgEgdAIgWQAKgaAIgUQAKgVAJgWIABgFIAEgKIAJgiIACgBIAEgCQAZgMAbgFQAggHAiAEIA+AGQASACASAFIARAGIgWAmIgCAEQgKASgNARIgbAnQgOAUgMAWQgLAUgNASQAXgDAQAQQAUATAPASQAQAUAOAUQAQAVAMAYIAYAuIAWAtQAMAYAJAXQAJAZASAUQAPARATARQALALANAIIAFADIAEACIAnAZIAoAaQATALAUAIIAEACQAVAIASAPQAWASgaAQQgHgWgVgIQAVAIAHAWIAAABQAHAYgjAHIgCgGQgIgSgUgKQAUAKAIASIACAGQAFAUgdADQAAgcgegDQAeADAAAcQAAAVgXAFIgEABIgCgBgAJcN/IAAAAgApXhAQgHgEgEgFQgMgUAJgeIAOgvQAGgYALgVQAIgSAFgVIACgGIANgcIABgDIAEgHQAKgUAIgXQAIgVALgTQALgUAMgRIAagkIAOgUIAIgOIAAAAIgBAAQALgTAJgRIAUgsIABgDIABAAIABgDIAEgIIACgEIAIgLIAAgBQAFgGALgDIAAACQAAAaAMASIADADIAKATIADgBIAKAVQALAWAMAVQANAVACAeQABAOAIANIAJAMQgRAUgBAaIABAAIgBACIAAgBIAAgBIAAABIAAABIgBAFIgGASIgDg3IADA3IgKAYQgLAagPAQIgjAkIgmAmIgiAgIgcAZQgSAPgXARQgTANgUAKQgLAFgMAAQgMAAgNgGgAl8loIgBADQgOAQgTARQgMAKgNAKQgUAOgMARQgNATgUALQAUgLANgTQAMgRAUgOQANgKAMgKQATgRAOgQIABgDQAIgnAMgiQgMAigIAngABHhzQgNgBgNgDIgngIIgJgCIgvgPIgBgDQgHgQgGgTIAAAAQgJgVgMgSIgYgnQgJgSgYgNQgXgNgLgVQgLgUgFgXIAFgCQAZgHAdgBIAegCQAggDATgIQALgFANgDQAZgFAXgEIAEAAIATgLIACgBQATgKARgOQAQgNAVgOIAcgUIAIgIIAMgJIAQgOIAMgKIAXgSQASgPAOgSIARgVIAMgOQAIgKACgPIgJADQgYAGgcACIgEAAIg5ACIguACQAJATAPAPQAQAOALATIAKAPIACAEIACADIADAEIACACQgGgDgWABQgVAAgTAEIgEABQgeAHgXgDQgegFgTgKQgTgKgTgOQgUgQgPgRQgPgTgMgUIAAAAQgLgTgIgXQgIgYAHgYIACAAIAWgGQAYgFAXgHIACgBIgDgCIAzgGIAIgBQAYgCAaACQAcACAfAAIA3AAQAcgBAeACQAcABAbgDQAdgDAcACQAeADAZADIASADIAMABQAPAIAIAPQAMAWgGAeQgFAWgNAVQgOAVgKATIgWAoQgKARgTALIgDACIgFAHIgBABQgJALgNAKQgUAPgRAPIgTAPIgUANIgFADIgBAAQAGAXAPAPIAPARQAPASAVANIAmAXQAPAJARAFIgXAqQgOAZgUAMIgqAZIgoAXIgvAYQgWAKgWAIQgXAIgdAIQgSAEgWAAIgQAAgABJiZQAJAAAFgJIAAgBIAAgBQgMADgJAHIAEABIACAAIAAAAIABAAgAhskOIA/gJIg/AJgADnmWQgXAMgUAOQgTAOgZANQgUAMgYAKIgJAEIgGADQgOAJgPAGIgGACIgxAPIgqAOIAqgOIAxgPIAGgCQAPgGAOgJIAGgDIAJgEQAYgKAUgMQAZgNATgOQAUgOAXgMIAkgVIgkAVgAADmNIgpAXIgfAOIgEACIgHADIgBAAQgdAUgnAGQAngGAdgUIABAAIAHgDIAEgCIAfgOIApgXIAVgLIgVALgABIiZIgCAAIgEgBQAJgHAMgDIAAABIAAABQgFAJgJAAIgBAAIAAAAgABCiaIAAAAgAjxmZIAAgBIABACIgBgBgAkLmkIAAABIAAABIAAgCgAiunxQgagEgSgMQgSgNgRgOQgQgNgKgVQgGgLgIgFQgTgNgRgTIABgDQARAFAVACQAdACAdABIABAAIABAAIAAAAIABAAQAaAAALgSIAAgBIABgBQAJgPAHgQQgHAQgJAPIgBABIAAABQgLASgaAAIgBAAIAAAAIgBAAIgBAAQgdgBgdgCQgVgCgRgFIgBAAIgCgBIgJgDQgWgJgagIIgNgEIgBgBQgGgZgJgSQgLgUgIgaIgMgtQgFgUgCgWIgBgNQgBggALgWIAUgnQAMgWAUgLIACgBIAggTIACgBIgDgBQAXgLAegBQAdAAATANIAIAGIAfAVIAEADIgEAKQgEAIgGAHQACgGAAgFIgBgHIgCgHIACAHIABAHQAAAFgCAGQgHAJgKAGQAFgEAAgKIAAgCIgBgTIABATIAAACQAAAKgFAEIAAAAIgBABQAEANAGALIAIAOQAHALAMAFIAJADQAIAAAGgDIAJgBQANABACAHQAAADgCAFIgFAJQgLAPgOALQAOgLALgPIAFgJQATATAEAYQAEAZgHAcIgHAaIgFARIgBACIgJAZIgCADIgEAMQATALAKATQAKAUAMASQANASADAcQABAHgBAHQgBAJgGAIQgEAIgHAGQgLALgVAAIgQgBgAllreQgLgKAAgMQAAgJAGgLQgGALAAAJQAAAMALAKgAkgsEQgPAFgJANIgHALIAHgLQAJgNAPgFIABAAQAHgDAIAAIAAAAIAAAAQAIAAAIADIABAAIABABIABAAIABAAQAXALAaAAIABAAIABAAIAAAAIAAAAQAPAAAGgIQgGAIgPAAIAAAAIAAAAIgBAAIgBAAQgaAAgXgLIgBAAIgBAAIgBgBIgBAAQgIgDgIAAIAAAAIAAAAQgIAAgHADIgBAAgAl7tlQABAJAEAIQAJATAZAJQAbAJAZgJQAXgJgEgdQgFgbgPgOQgFgEgFgBIgDACIgFgCQgMgEgBgOQABAOAMAEIAFACIgMADIgEABQgFgBgEgDQgJgFgIgMQAIAMAJAFQAEADAFABIgRACIgGgEIgDgCQgMgIgDgRQADARAMAIIADACIAGAEQgNABgMgCIgEgFIgDgFQgIgKgFgOQAFAOAIAKIADAFIAEAFIgHgCIgDgBQgOgFgJgHQALASADAdgAmJuUQgIgIgEgKQAEAKAIAIgAlfuzIAIACQAMADAJAFQgJgFgMgDIgIgCQgWgFgXgBQAXABAWAFgAkYuzQAJgVATgNQgTANgJAVgAmUo6IADgBIgBADIgCgCgAjnukIAAAAg");
	this.shape_4.setTransform(255.6,-101.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#339966").s().p("ADFHeIAWgmIAAAAIAFACQATAIATANQgTgNgTgIIgFgCIAAAAIgRgGQgRgFgTgCIg+gGQgigEggAHQgbAFgXAMIgEACIgCABIghAQIAhgQIgJAiQgWgBgDgRIABAAIgCgDIAOgrQAHgUAEgaIAAgBIAAgEIAFgGQALgRAHgbQAFgYACgaQgCAagFAYQgHAbgLARIgFAGIgFAGIgFAEIAAAAIAEgBIgBABIgCADIgUAUQgSASgQANIglAcQgKAIgKABIgGgBQgGgBgGgFIgUgQIgBAAIABAAIAUAQQAGAFAGABQgUAGgVgLIAGgNQAAgBAAAAQAAgBABgBQAAAAAAgBQAAAAABAAIgOgKIgegVQgPgKgSgGQgVgIgTgFQgZgHgagFIgDAAIgFgBQgegFgSgTIAAgBQALgQATgMQAYgOAVgUIASgSIAYgWQAVgUAXgPIArgeIAmgbQASgNAMgTQABAbAEAZQACANAFALQgFgLgCgNQgEgZgBgbIADgCIAAAAQAOgHALgLIACADIAvAPIACAAIAJACIAnAIQAMADAMABQAgACAYgGQAdgIAXgIQAWgIAWgKIAvgYIAogXIAqgZQAUgMAOgXIAXgqIAIACQAQAKAQAOQAUATAHAZQAIAZADAcQADAdgHAaIgPAzQgJAbgLAWQgLAWgOAVIgBABQgGAJgCAMQgFAagNAUQgMASgLAcIgDAHIgQAoQgJAXgKARQgDAAgCACIgCgBIgHgCIAGAEQgFAFgOACIg2AIIACgEgAhuCXQgQgPgKgVQAKAVAQAPgAmGF/QgRgPgEgYQASATAeAFIAFABIgCADIgEAFIgOAOQgIgEgEgEgAkth6QgUgEgNgOIgJgMQgIgNgBgOQgCgegNgVQgMgVgLgWIgKgVIgNgSIANASIgDABIgKgTIgDgDQgMgTAAgZQAVgFASgJIABgBIAAgCQARATATANQAIAFAGALQAKAVAQANQARAOASANQASAMAaAEQAhAFAPgPQAHgGAEgIQAGgIABgKQABgGgBgHQgDgcgNgSQgMgSgKgUQgKgTgTgLIAEgMIACgDIAJgZIABgDQAOgGARgFIAYgHQgHAYAIAYQAIAXALASIAAABQAMAUAPATQAPARAUAQQATAOAVAKQATAKAcAFQAXADAegHIAEgBQATgEAVAAQAWgBAGADIgCgCIAGADIgMAKIgQAOIgMAJIgIAHIgcAVQgVAOgQANQgRAOgRAKIgCABIgTALIgEAAQgZAEgZAFQgNADgLAFQgTAIggADIgeABQgdACgZAHIgFABQgNAEgNAAQgMAAgMgDgAksijIABABIgBgCgAlGisIAAgBIAAgBIAAACg");
	this.shape_5.setTransform(261.5,-126.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(20));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(120.9,-208.3,197.5,207.8);


(lib.contentverbtenseintro = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// character
	this.instance = new lib.animCarmen_ready();
	this.instance.setTransform(-144,-65,0.397,0.397,0,0,0,219.6,-104.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(184));

	// text1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AiJDxQgdgcAAhkIABgtIACgzQgEgHABgIQAAgJAFgJQAHhaAAgrQAAgMgDgWQgEgXAAgLQAAglAgAAQANgBAJAKQAmgKAhgGQAhgEAcAAQBMgBAuATQAUAIAAAWQABAMgJAKQgJALgNAAIgKgCQg1gPgxAAQgZAAgdAFQgfAFgiAJQACAVAAAMQAAArgFBNICHgOQA9gGAOAAQAOAAAIAJQAKAJAAAOQAAAbgdAEIhLAGIiOANIgCArIgBAlQAABFAKAMQAIAJApAAIA5gBIA6gBIATgDIASgCQAhABABAgQgBAagaAFQgdAHhhgBQhhABgcgag");
	this.shape.setTransform(224.4,30.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("Ah9DYQg6gbgBguQgBgNAKgJQAJgJANABQAQAAALARQAQAYANAIQAbASAyAAQAvAAAqgVQA1gbAAgwQAAgngtgXQgmgUg2gCQgxAAgjgTQgtgZAAgwQAAg3BAgvQA8gsA/AAQAeAAAmALQAzAOAAAUQAAAcgcAAQgMAAgggGQgfgHgRAAQgvAAgiAYQgkAYAAAiQAAAbAvAKQARAEAwAEQBHAFApAoQAlAiAAA0QAABLhFAtQg8AnhNAAQg5AAgwgXg");
	this.shape_1.setTransform(181.5,32);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF0000").s().p("AjSD0QgJgKAAgOIACgnIACgoIABg6IACg7IgBg8IgBg/QAAgTgEgnQgEgnAAgUQAAgOANgMQAMgMAQAAQAQAAAZAkQBOB1A+BOQBIBZBZBUQABgNgBgaIgBgoQAAiIgKhSIgJggQgGgWAAgLQAAglAhAAQA3AAAADLIgBBnIgBBnQAAAPgFAkQgFAfgdAAQgRAAgYgWQh/h5ikjiIgBBHIgBBGIABBOIABBOQAABVghAAQgRAAgKgLg");
	this.shape_2.setTransform(133.7,31);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF0000").s().p("AiJDxQgdgcAAhkIABgtIACgzQgEgHABgIQAAgJAFgJQAHhagBgrQAAgMgCgWQgDgXgBgLQABglAfAAQANgBAJAKQAmgKAhgGQAigEAbAAQBMgBAuATQAUAIAAAWQABAMgJAKQgIALgOAAIgKgCQg1gPgxAAQgZAAgdAFQgfAFgiAJQACAVAAAMQAAArgFBNICHgOQA9gGAOAAQANAAAKAJQAJAJAAAOQAAAbgdAEIhLAGIiOANIgCArIgBAlQAABFAKAMQAIAJApAAIA5gBIA6gBIATgDIASgCQAhABAAAgQAAAagbAFQgcAHhhgBQhhABgcgag");
	this.shape_3.setTransform(88.6,30.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF0000").s().p("AgWDlQgJgIgBgOIACgOIACgOIgCguQgCgfgBgQQABgtgIhPQgHhXgBgnIgdABQhEAAgogKQgZgHAAgYQABgNAHgKQAKgLAPABIAyAGQAfADATAAIA6AAIA3gBQAYAAAwADQAvAEAYAAQAOAAAIAJQAJAJAAAOQAAANgJAKQgIAJgOAAQgXAAgwgEQgwgDgYAAIgXAAQACArAHBhQAHBZAAAyIACAhQADAXAAALQgBAVgGAQQgJAUgSAAQgLAAgLgJg");
	this.shape_4.setTransform(48.5,30.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF0000").s().p("AiSDxQgMgNAAgOIAAhbQAAgtAGhRQAGhZABgoQgBgdAEg5QACgQAIgFQArgNA2AAQA1AAAzAmQA7ArAAA/QAABRg/AsQAvAUAYAZQAXAYAAAdQAAAmgpAjQgdAZgfANQhFAbhtAAQgOAAgMgMgAhgB8IAABBQBSgDAygUQAWgJAUgRQATgRAAgIQAAgPgogSQgegOgbgHIghgFIgMAAIgNAAQgRAAgTgCQgCAnAAAfgAhTi6IAAA3IgHB5IAwAEQAtgEAegaQAhgcAAgsQAAgdghgaQghgZgjAAQgiAAgOACg");
	this.shape_5.setTransform(-13.8,30.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF0000").s().p("AifDtQgJgKAAgOQAAgYgCgxQgDgxAAgZQAAgdAHg3QAGg5AAgdQAAgQgDgfQgDgfAAgQQAAgSAKgOQAMgQAVABIBLAGQArAGAcAPQB/BEAABhQAAAvgrAjQgjAeg0APQBhA0AwA6QAJAKAAAMQAAANgKAJQgKAKgMAAQgMAAgLgKQhnhmh9gkIACA+IACA9QAAAOgJAKQgJAJgOAAQgNAAgJgJgAhjiMQACAXAAAPQAAAZgEAlIgHA9IAOAAIAOAAQBQAAAmgVQARgIAPgPQARgSAAgMQAAgsgyglQgrgjgygFIgugEg");
	this.shape_6.setTransform(-55.1,30.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF0000").s().p("AiJDxQgdgcAAhkIABgtIACgzQgEgHABgIQAAgJAFgJQAHhagBgrQAAgMgCgWQgEgXAAgLQAAglAgAAQANgBAJAKQAmgKAhgGQAhgEAcAAQBMgBAuATQAUAIAAAWQABAMgJAKQgJALgNAAIgKgCQg1gPgxAAQgZAAgdAFQgfAFgiAJQACAVAAAMQAAArgFBNICHgOQA9gGAOAAQAOAAAIAJQAKAJAAAOQAAAbgdAEIhLAGIiOANIgCArIgBAlQAABFAKAMQAIAJApAAIA5gBIA6gBIATgDIASgCQAhABAAAgQAAAagbAFQgcAHhhgBQhhABgcgag");
	this.shape_7.setTransform(-95.1,30.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF0000").s().p("Ag4DkQgmhfguixIgZhWQgThBAAgVQAAgOAKgIQAKgJANAAQAXAAAHAZIALA3IAfBqQAeBzAcBVIACgGIBTjhIAahNQASguAUgYQAKgNAPAAQAMAAAKAKQAJAJAAAOQABAKgHAJQgTAdgMAgIgYBEIhUDjQgPAogUAmQgIASgSAAQgYAAgKgYg");
	this.shape_8.setTransform(-134.9,31.3);

	this.instance_1 = new lib.Tween30("synched",0);
	this.instance_1.setTransform(42.9,28);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.instance_1}]},19).to({state:[{t:this.instance_1}]},10).wait(155));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(19).to({_off:false},0).to({scaleX:0.42,scaleY:0.42,y:-95.3},10).wait(155));

	// text2
	this.instance_2 = new lib.Tween9("synched",0);
	this.instance_2.setTransform(51.8,25.4,0.091,0.091);
	this.instance_2._off = true;

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF0000").s().p("AgKBVQgFgFAAgHIAAgFIABgFIgBgQIgBgRQAAgPgCgZQgDgfAAgMIgHAAQgaAAgPgDQgNgEAAgMQAAgGAEgFQAFgFAIAAIATACIASABIAWAAIATAAIAbABIAbABQAHAAAEAFQAFAFAAAGQAAAHgFAFQgEAEgHAAIgdgBIgcgBIADAvQACAdAAARIABAMIABAMQAAAJgEAHQgFAJgIAAQgFAAgFgEg");
	this.shape_9.setTransform(-77.7,131.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF0000").s().p("Ag+BMQgPgLAAgOQAAgIAFgFQAFgEAHAAQALAAAFAKQAHAOAXAAQASABATgJQAUgJAAgLQgBgPgMgFQgIgDgYAAQgVgBgPgGQgWgJAAgSQABgXAYgTQAYgTAbAAQALAAARAGQAUAGAAAIQAAAHgDAEQgFAGgIAAQgFgBgLgCIgQgCQgPAAgMAHQgOAHgBAJQABAFAEADQAEACAJABIAbACQAbACAPAMQARANAAAYQAAAegjARQgbALgfAAQgeAAgRgNg");
	this.shape_10.setTransform(-94.5,132.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FF0000").s().p("AA7BYQgJgBgJgVQgHgOgEgSIgcADQgRABgKACQgFANgOAaQgFAIgJAAQgGAAgFgEQgGgFAAgHQAAgGASgiQgCgEAAgDQABgGAKgDQARgbAVgfQAbgsAHAAQANAAAEAQIAHAlIASBLIAGAQQAEAKAAAFQAAAHgFAEQgFAFgGAAIgBAAgAgIAKIAPgCIAQgBIgHglIgYAog");
	this.shape_11.setTransform(-111.7,132);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FF0000").s().p("Ag0BZQgEgFAAgGIAAghQAAgSACgiIACg2QABgfARACIALgBIARgBQAVAAAUAPQAWAQAAAZQAAAdgYAQQgVAQgbAAIgKgBIAAA2QAAAGgFAFQgEAEgHAAQgGAAgFgEgAgVgtIgCAoIAIABQAQABANgJQAMgKAAgOQAAgLgMgHQgLgIgMAAIgHAAIgEAAIgBARg");
	this.shape_12.setTransform(-126.7,131.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FF0000").s().p("AhRBaQgEgFAAgHIAAgOIABgOIABgVIAAgUIAAgVIgBgWIgBgVIgCgVQAAgHAHgFQAGgGAHAAQAJAAALAPQAzBMA0AuIAAgSQAAg4gCgUIgBgNIgBgMQAAgRARAAQATAAAAA7IAAATIgBBIIgCASQgCAQgPAAQgIAAgLgKQgtgog2hIIgBAkIAAAcIABAbQAAAjgRAAQgJAAgFgFg");
	this.shape_13.setTransform(50.5,131.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FF0000").s().p("Ag1BZQgNgLAAgmQAAgQACgdIACgvIgBgMIgBgNQAAgRARAAQAFAAAEACIAagFIAVgBQAdAAATAGQAKAFAAAKQAAAGgEAFQgFAGgHAAIgFgBQgTgFgSAAIgRABQgKABgLADIgBAvIAsgFIAcgCQAHAAAFAEQAEAFABAHQAAAMgPACIgcACIgwAFIgBAYQAAAXADADQABABANAAIAUAAIAWAAIAHgBIAHgBQAHAAAEAEQAGAFAAAHQAAAOgOACQgLACgjAAQgmAAgMgKg");
	this.shape_14.setTransform(33.6,131.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FF0000").s().p("Ag+BMQgPgLAAgOQABgIAEgFQAFgEAHAAQALAAAFAKQAHAOAXAAQASABATgJQATgJABgLQAAgPgNgFQgIgDgZAAQgTgBgRgGQgVgJAAgSQABgXAYgTQAYgTAbAAQALAAARAGQAUAGAAAIQAAAHgDAEQgFAGgIAAQgFgBgLgCIgQgCQgQAAgMAHQgOAHABAJQAAAFAEADQAEACAJABIAbACQAbACAPAMQARANAAAYQAAAegjARQgbALgfAAQgeAAgRgNg");
	this.shape_15.setTransform(17.5,132.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FF0000").s().p("Ag1BZQgNgLAAgmQAAgQACgdIADgvIgBgMIgCgNQAAgRAQAAQAGAAAEACIAagFIAVgBQAdAAATAGQAKAFAAAKQAAAGgEAFQgFAGgHAAIgFgBQgTgFgSAAIgQABQgLABgLADIgBAvIArgFIAdgCQAHAAAFAEQAFAFgBAHQAAAMgOACIgcACIgwAFIgBAYQAAAXACADQACABAOAAIATAAIAWAAIAHgBIAHgBQAGAAAFAEQAGAFAAAHQAAAOgOACQgLACgkAAQgmAAgLgKg");
	this.shape_16.setTransform(2,131.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FF0000").s().p("Ag/BXQgEgEAAgHIAAgaIAAgbIAAhcQAAgIAFgGQAGgIAKABIAeACQAQACAJAGQAyAZAAAlQAAAQgKAJQgLAMgVAIQAgASAPASQAEAEAAAGQAAAHgFAEQgEAFgHAAQgHAAgFgFQgjghgpgNIABAmQAAAHgEAEQgFAFgHAAQgHAAgFgFgAgjADIAFAAQAdAAAMgFQAGgDAFgFQAFgFAAgDQAAgNgRgMQgOgMgRgBIgOgBg");
	this.shape_17.setTransform(-13.3,131.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FF0000").s().p("AgnALQgHgEAAgHQAAgEAHgFQAFgDAIAAIAaAAIAbgBQAHAAAGADQAHADAAAHQAAALgSACIg3ABQgIAAgFgDg");
	this.shape_18.setTransform(-51.8,134.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FF0000").s().p("AgKBVQgFgFAAgHIAAgFIABgFIgBgQIgBgRQAAgPgCgZQgDgfAAgMIgHAAQgaAAgPgDQgNgEAAgMQAAgGAEgFQAFgFAIAAIATACIASABIAWAAIATAAIAbABIAbABQAHAAAEAFQAFAFAAAGQAAAHgFAFQgEAEgHAAIgdgBIgcgBIADAvQACAdAAARIABAMIABAMQAAAJgEAHQgFAJgIAAQgFAAgFgEg");
	this.shape_19.setTransform(-77.7,131.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FF0000").s().p("Ag0BZQgEgFAAgGIAAghQAAgSACgiIACg2QABgfARACIALgBIARgBQAVAAAUAPQAWAQAAAZQAAAdgYAQQgVAQgbAAIgKgBIAAA2QAAAGgFAFQgEAEgHAAQgGAAgFgEgAgVgtIgCAoIAIABQAQABANgJQAMgKAAgOQAAgLgMgHQgLgIgMAAIgHAAIgEAAIgBARg");
	this.shape_20.setTransform(-126.7,131.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FF0000").s().p("Ag1BZQgNgLAAgmQAAgQACgdIACgvIgBgMIgBgNQAAgRARAAQAFAAAEACIAagFIAVgBQAdAAATAGQAKAFAAAKQAAAGgEAFQgFAGgHAAIgFgBQgTgFgSAAIgRABQgKABgLADIgBAvIAsgFIAcgCQAHAAAFAEQAEAFABAHQAAAMgPACIgcACIgxAFIAAAYQAAAXADADQABABANAAIAUAAIAWAAIAHgBIAHgBQAHAAAEAEQAGAFAAAHQAAAOgOACQgMACgiAAQgmAAgMgKg");
	this.shape_21.setTransform(202.3,131.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FF0000").s().p("AguBPQgfgXAAg5IABgRIABgRIAAgNIAAgOQAAgJADgIQAFgLAIAAQAHAAAFAFQAFADAAAIIAAATIAAAUIgBARIgBAQQAAAQAFAQQAFASAJAHQAFAEATAAQAcAAALg1QAGgZAAgyQAAgGAEgHQAFgIAKAAQAIAAAEAGQADAFAAAFQAAAugFAaQgGAmgUAaQgIAMgMAHQgPAKgNAAQgeAAgPgMg");
	this.shape_22.setTransform(170.1,132.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FF0000").s().p("AguBPQgfgXAAg5IABgRIABgRIAAgNIAAgOQAAgJADgIQAFgLAIAAQAHAAAFAFQAFADAAAIIAAATIAAAUIgBARIgBAQQAAAQAFAQQAFASAJAHQAFAEATAAQAcAAALg1QAGgZAAgyQAAgGAEgHQAFgIAKAAQAIAAAEAGQADAFAAAFQAAAugFAaQgGAmgUAaQgIAMgMAHQgPAKgNAAQgeAAgPgMg");
	this.shape_23.setTransform(135.7,132.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FF0000").s().p("Ag7BdQgEgEAAgHIAAiFIAAgNIABgOQgBgHAFgEQAFgFAGAAQAFAAADACIAZgEIATgBQANAAAUAGQAaAHAAAIQAAAIgFAEQgEAFgHAAIgGgBQgQgFgVAAIgOABIgWADIAAAmQATgEALAAQAUAAAQACQAPACAAAOQAAAHgEACQgFAFgHAAIgSgBIgRgBQgJAAgVAGIAABJQAAAHgEAEQgGAFgHAAQgHAAgEgFg");
	this.shape_24.setTransform(120,131.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FF0000").s().p("Ag/BXQgEgEAAgHIAAgaIAAgbIAAhcQAAgIAFgGQAGgIAKABIAeACQAQACAJAGQAyAZAAAlQAAAQgKAJQgLAMgVAIQAgASAPASQAEAEAAAGQAAAHgFAEQgEAFgHAAQgHAAgFgFQgjghgpgNIABAmQAAAHgEAEQgFAFgHAAQgHAAgFgFgAgjADIAFAAQAdAAAMgFQAGgDAFgFQAFgFAAgDQAAgNgRgMQgOgMgRgBIgOgBg");
	this.shape_25.setTransform(-13.3,131.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FF0000").s().p("AgnALQgHgEAAgHQAAgEAHgFQAFgDAIAAIAaAAIAbgBQAHAAAGADQAHADAAAHQAAALgSACIg3ABQgIAAgFgDg");
	this.shape_26.setTransform(-51.8,134.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FF0000").s().p("AgKBVQgFgFAAgHIAAgFIABgFIgBgQIgBgRQAAgPgCgZQgDgfAAgMIgHAAQgaAAgPgDQgNgEAAgMQAAgGAEgFQAFgFAIAAIATACIASABIAWAAIATAAIAbABIAbABQAHAAAEAFQAFAFAAAGQAAAHgFAFQgEAEgHAAIgdgBIgcgBIADAvQACAdAAARIABAMIABAMQAAAJgEAHQgFAJgIAAQgFAAgFgEg");
	this.shape_27.setTransform(-77.7,131.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_2}]},19).to({state:[{t:this.instance_2}]},10).to({state:[{t:this.instance_2}]},5).to({state:[{t:this.instance_2},{t:this.shape_12,p:{x:-126.7}},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9,p:{x:-77.7}}]},55).to({state:[{t:this.instance_2},{t:this.shape_20},{t:this.shape_11},{t:this.shape_10},{t:this.shape_19,p:{x:-77.7}},{t:this.shape_18,p:{x:-51.8}},{t:this.shape_12,p:{x:-27.6}},{t:this.shape_17,p:{x:-13.3}},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_9,p:{x:68.7}}]},16).to({state:[{t:this.instance_2},{t:this.shape_20},{t:this.shape_11},{t:this.shape_10},{t:this.shape_27},{t:this.shape_26},{t:this.shape_12,p:{x:-27.6}},{t:this.shape_25},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_19,p:{x:68.7}},{t:this.shape_18,p:{x:94.6}},{t:this.shape_24},{t:this.shape_23},{t:this.shape_9,p:{x:153.1}},{t:this.shape_22},{t:this.shape_17,p:{x:187}},{t:this.shape_21}]},14).wait(65));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(19).to({_off:false},0).to({scaleX:0.9,scaleY:0.9},10).to({scaleX:1.31,scaleY:1.31},5).wait(55).to({startPosition:0},0).wait(16).to({startPosition:0},0).wait(14).to({startPosition:0},0).wait(65));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-182.8,-105.8,432.5,184.4);


// stage content:



(lib.intro__Scene1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{scene1:0,scene1_repeat:141});

	// timeline functions:
	this.frame_0 = function() {
		this.play();
		playSound("dentaku_groove");
		playSound("dentaku_groove",-1);
		this.btn_menu.addEventListener("click", openMenu.bind(this));
		this.btn_goNext.addEventListener("click", openNext.bind(this));
		
		function openMenu(){
		
		 window.open ("../menu/menu.html","_self");
		}
		
		function openNext(){
		
		 window.open ("intro_Scene2.html","_self");
		}
		
		/*function openPrev(){
		
		 window.open ("puzzle_aux.html","_self");
		}*/
	}
	this.frame_1 = function() {
		playSound("space_blip");
	}
	this.frame_11 = function() {
		playSound("verbtense");
	}
	this.frame_90 = function() {
		playSound("pastali");
	}
	this.frame_107 = function() {
		playSound("presentAli");
	}
	this.frame_124 = function() {
		playSound("futureAli");
	}
	this.frame_148 = function() {
		this.gotoAndPlay("scene1_repeat");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(10).call(this.frame_11).wait(79).call(this.frame_90).wait(17).call(this.frame_107).wait(17).call(this.frame_124).wait(24).call(this.frame_148).wait(1));

	// content
	this.instance = new lib.contentverbtenseintro();
	this.instance.setTransform(272.4,190,1,1,0,0,0,44,28.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(149));

	// main
	this.instance_1 = new lib.Background();
	this.instance_1.setTransform(275,188.5,1.038,1.067);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(149));

	// buttons
	this.btn_menu = new lib.skiptomenu();
	this.btn_menu.setTransform(514.1,20.3);
	new cjs.ButtonHelper(this.btn_menu, 0, 1, 2, false, new lib.skiptomenu(), 3);

	this.instance_2 = new lib.Copyright("synched",0);
	this.instance_2.setTransform(275,393.5);

	this.btn_goNext = new lib.goNext();
	this.btn_goNext.setTransform(494,352.3);
	new cjs.ButtonHelper(this.btn_goNext, 0, 1, 2, false, new lib.goNext(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.btn_goNext},{t:this.instance_2},{t:this.btn_menu}]}).wait(149));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(300,201.8,521.3,401.2);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;