(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 550,
	height: 400,
	fps: 12,
	color: "#FFFFFF",
	manifest: [
		{src:"sounds/auxillaryverbs_female.mp3?1493941066637", id:"auxillaryverbs_female"},
		{src:"sounds/auxillaryverbsarehelpingverbsthatmakeup.mp3?1493941066638", id:"auxillaryverbsarehelpingverbsthatmakeup"},
		{src:"sounds/BeautifulDrumnbass.mp3?1493941066638", id:"BeautifulDrumnbass"},
		{src:"sounds/bump.mp3?1493941066638", id:"bump"},
		{src:"sounds/clickwav.mp3?1493941066638", id:"clickwav"},
		{src:"sounds/flying.mp3?1493941066638", id:"flying"},
		{src:"sounds/High_Screaming_Gtr.mp3?1493941066638", id:"High_Screaming_Gtr"},
		{src:"sounds/quick_pad_chord.mp3?1493941066638", id:"quick_pad_chord"},
		{src:"sounds/square_bits.mp3?1493941066638", id:"square_bits"}
	]
};



// symbols:



(lib.Tween3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF9900").s().p("AgGAHQgDgDAAgEQAAgDADgDQADgDADAAQAEAAADADQADADAAADQAAAEgDADQgDADgEAAQgDAAgDgDg");
	this.shape.setTransform(109,19.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF9900").s().p("AgWAuQgNgFAAgIQAAgEADgCQADgCADgBQADAAADAFQACACAIAAIAJABQAFABAFgCQAIgDAAgFQAAgLgQgEIgGgCQgLgCgFgDQgHgDAAgKQAAgRARgHIAOgFQAKgEAFgCQADgCAEABQAEgBADADQABADAAADIABAHIABAHQAAAEgCACQgCACgEAAQgEAAgCgCIgCgKIgTAHQgLAFAAAHIAEACQASADAJAGQANAHAAAQQAAAOgLAHQgKAFgNABQgLgBgKgDg");
	this.shape_1.setTransform(102.5,15.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF9900").s().p("AgbAjQgNgKAAgTQAAgTALgPQALgQASAAQANAAAIAFQAMAFAAAMQAAAJgKAGIgRAIIgfAPQAFAHAHADQAHAEAHAAQAGAAAIgDQAKgCACgFQADgEAEAAQACAAACACQADACAAADQAAAJgPAHQgMAGgNAAQgQAAgMgKgAgQgVQgGAIgEANIAagKQAMgHAHgFQgHgHgMAAQgJAAgHAIg");
	this.shape_2.setTransform(94.1,15.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF9900").s().p("AgWAuQgMgFAAgIQgBgEADgCQADgCADgBQACAAAEAFQADACAGAAIAKABQAFABAFgCQAIgDAAgFQAAgLgQgEIgGgCQgMgCgEgDQgHgDAAgKQAAgRAQgHIAOgFQAMgEAEgCQAEgCAEABQADgBACADQACADABADIABAHIABAHQAAAEgCACQgDACgDAAQgFAAgCgCIgCgKIgTAHQgMAFAAAHIAGACQAQADAJAGQAOAHAAAQQAAAOgMAHQgJAFgNABQgLgBgKgDg");
	this.shape_3.setTransform(84.9,15.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF9900").s().p("AAaAqIgGgGIgNAGQgHACgBAAQgUAAgJgLQgJgKABgVQAAgSANgOQAOgPASAAQAHAAAJAEQALAFAAAGIgBAEIgCALIAAAQQAAALABAFIAFAPIACAFIABABQgBADgCACQgCACgDABQgCAAgEgEgAgMgUQgKALAAAMQAAANAFAHQAEAHALAAQAFAAAGgDIAIgGQgCgVAAgKIAAgIIABgJIgFgCIgDgBQgLAAgJAKg");
	this.shape_4.setTransform(76.6,15.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF9900").s().p("AgfAlIAAg3IABgJIAAgIQAAgIAHAAQAIgBAAAOQAPgPATAAQAGAAAEAFQADAFAAALIAAAFQgBALgHAAQgIgBAAgHIAAgHIAAgHQgNACgGAGQgHAFgFALIAAArQAAAJgIAAQgIAAAAgJg");
	this.shape_5.setTransform(68.4,15.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF9900").s().p("AAWA+IgDgTIgCgUIAAgHIAAgGQAAgNgHAAQgKAAgHAHQgEAFgIAOQAAAfgCAGQgDAGgFAAQgDAAgDgDQgCgCAAgDIABgFIAAgMIABgLIAAg7IABgPIgBgIIgBgHQAAgEACgCQADgCADAAQAHgBABAIIACAOIgBASIAAASIAAAIQAGgJAIgFQAGgEAJAAQANAAAGAJQADAGABANIAAAQIACARIADASIAAABQAAAEgCADQgDABgDABQgGAAgCgHg");
	this.shape_6.setTransform(59.3,13.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF9900").s().p("AgfBDQgCgDAAgDIAAghIAAgfIgBgiIgBgRQAAgFACgFQACgEAFAAQADAAACACQADACAAAEIgBACIAAAFQAHgFAHgCQAFgDAFAAQARAAAIAPQAGANAAATQAAAQgJAMQgKAMgRAAQgHAAgKgDIAAAoQAAADgCADQgCACgEAAQgEAAgCgCgAgGgqQgFACgHAGIABAlQAKAEAHAAQAKAAAFgHQAFgFAAgLQAAgPgDgIQgEgHgIAAQgFAAgGAEg");
	this.shape_7.setTransform(49.8,17.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF9900").s().p("AgmA/QgDgDAAgEIAAgYIACggIABgiIABgXQABgEACgBQALgEAPAAQAMAAAOAKQAPAMAAARQAAAVgQAKQAMAGAGAGQAHAGAAAIQAAAKgLAKQgIAGgIADQgRAIgdAAQgEAAgDgEgAgYAhIAAARQAVgBAMgFQAGgDAFgEQAFgFAAgCQAAgEgKgFIgPgFIgIgCIgDABIgDAAIgKgBIAAATgAgVgwIAAAOIgCAhIANAAQAKgBAIgGQAJgIAAgLQAAgIgJgHQgIgHgIAAIgNABg");
	this.shape_8.setTransform(35.2,13.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF9900").s().p("AgpA+QgCgCAAgEIgBgTIgBgUIACgVIACgWIgBgNIgBgMQAAgFADgEQADgEAGAAIAUACQALABAGAEQAhASAAAaQAAANgLAHQgJAIgOAEQAaAOANAPQACADAAADQAAAEgDACQgCADgEAAQgDAAgDgDQgbgbgggKIABARIAAAQQAAAEgCACQgCADgEAAQgEAAgCgDgAgZgkIAAAKIgBARIgBAOIADAAIAEAAQAUAAAKgFQAEgBAEgEQAFgFAAgDQAAgMgNgKQgKgJgOgBIgMgBg");
	this.shape_9.setTransform(24.2,13.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF9900").s().p("AgjA/QgIgHAAgbIABgLIAAgOIgBgEIACgDIABgjIgBgJIAAgJQAAgLAIAAQAEAAACADIATgEIAOgBQAVAAALAFQAGACAAAGQAAADgCACQgDADgDABIgDgBQgOgEgNAAIgMABIgSAEIABAJIgBAfIAigDIATgCQAEAAADADQACACAAADQAAAGgIABIgTACIgkADIgBALIAAAKQAAATADADQACACAKAAIAOAAIAQAAIAEgBIAFAAQAJgBAAAKQAAAGgHACQgIABgYAAQgZAAgIgHg");
	this.shape_10.setTransform(13.7,13.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FF9900").s().p("AgOA8QgJgZgNgtIgHgYQgEgQAAgGQAAgDACgDQADgDADABQAGgBACAIIADAOIAIAcQAIAdAHAWIABgBIAVg6IAHgVQAEgMAGgGQADgEADABQADgBADADQACADAAADIgBAFQgFAIgEAIIgGASIgWA7IgJAUQgBAFgFABQgGAAgDgHg");
	this.shape_11.setTransform(3.2,13.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FF9900").s().p("AgfBDQgCgDAAgDIAAghIAAgfIgBgiIgBgRQAAgFACgFQACgEAFAAQADAAACACQADACAAAEIgBACIAAAFQAHgFAHgCQAFgDAFAAQARAAAIAPQAGANAAATQAAAQgJAMQgKAMgRAAQgHAAgKgDIAAAoQAAADgCADQgCACgEAAQgEAAgCgCgAgGgqQgFACgHAGIABAlQAKAEAHAAQAKAAAFgHQAFgFAAgLQAAgPgDgIQgEgHgIAAQgFAAgGAEg");
	this.shape_12.setTransform(-12.5,17.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FF9900").s().p("AASAnQgLAGgLAAQgKgBgIgEQgIgGgBgJQgDgXgBgPQABgLACgPQABgHAHAAQADAAADADQADACgBADIgBANIgBAMIABAWQABAKABAGIAGACIAFABQAJAAAMgEIAAgQIAAgPQABgRABgOQABgIAHABQADAAADACQADACgBAEIgBAfIAAAQIAAASIAAAGIAAAFQAAADgCADQgCACgEAAQgGAAgCgIg");
	this.shape_13.setTransform(-21.5,15.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FF9900").s().p("AgbAjQgNgKAAgTQAAgTALgPQALgQASAAQANAAAIAFQAMAFAAAMQAAAJgKAGIgRAIIgfAPQAFAHAHADQAHAEAHAAQAGAAAIgDQAKgCACgFQADgEAEAAQACAAACACQADACAAADQAAAJgPAHQgMAGgNAAQgQAAgMgKgAgQgVQgGAIgEANIAagKQAMgHAHgFQgHgHgMAAQgJAAgHAIg");
	this.shape_14.setTransform(-35.5,15.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FF9900").s().p("AAWA/QgFgJgJgLIgMgUIgPALIgBAZQAAAEgCACQgCACgEAAQgIAAAAgLIAAgVIABgUIABgbIAAgdIAAgJIgBgJQABgDACgDQACgCADAAQAEAAADACQACADAAADIAAAKIAAAJIAAAaIAAAbIATgRIASgTQAEgCACAAQAEAAADACQACADAAADQAAADgCADQgLALgOAMIASAZQAMARAAAGQAAADgDACQgCADgEAAQgEAAgCgFg");
	this.shape_15.setTransform(-44.4,13.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FF9900").s().p("AAaAqIgGgGIgNAGQgHACgBAAQgUAAgJgLQgJgKABgVQAAgSANgOQAOgPASAAQAHAAAJAEQALAFAAAGIgBAEIgCALIAAAQQAAALABAFIAFAPIACAFIABABQgBADgCACQgCACgDABQgCAAgEgEgAgMgUQgKALAAAMQAAANAFAHQAEAHALAAQAFAAAGgDIAIgGQgCgVAAgKIAAgIIABgJIgFgCIgEgBQgKAAgJAKg");
	this.shape_16.setTransform(-53.9,15.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FF9900").s().p("AgDAwQgDgCAAgEIgCgdIgCgcQAAgJgCgFQgGADgGAGIgKALIgEAFIgBANIgBAOIABAHIABAGQAAAEgDACQgCACgEAAQgJAAAAgVIABgPIABgNIgBgNIgBgNQAAgTAJAAQADAAACADQADADAAADIAAAFIgBAFIAAAJQAFgJAIgHQAJgHAFAAQANAAADAMQAFgGAGgDQAHgDAIAAQAOAAAFAPIADAYIAGAtQAAADgCADQgDACgDAAQgHAAgBgHIgDgaIgDgYIgDgLQgDgHgDAAQgDAAgIAFQgIAFgDADIAAAPIADAUQACAOAAAIQAAAEgDACQgCADgEAAQgBAAgCgDg");
	this.shape_17.setTransform(-64.7,15.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FF9900").s().p("AgEA6QgCgCAAgDIAAgKIAAgJIgCgvIgSgBQgHgBAAgIQAAgDACgDQACgCAEAAIARABIAAgLIgBgKQAAgEADgCQACgCAEAAQAFAAABAMIABAHIgBAFIAAAFIAMgBIALABQAFACAAAGQAAADgCADQgCACgEAAIgEAAIgEAAIgLABIABAvIAAAEIABAEQAAASgJAAQgBAAgDgCg");
	this.shape_18.setTransform(-80.6,14.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FF9900").s().p("AAaAqIgFgGIgPAGQgFACgCAAQgUAAgJgLQgIgKAAgVQgBgSAOgOQAPgPAQAAQAIAAAJAEQALAFAAAGIgBAEIgCALIAAAQQAAALABAFIAFAPIACAFIABABQAAADgDACQgCACgDABQgCAAgEgEgAgMgUQgKALAAAMQAAANAFAHQAEAHALAAQAFAAAGgDIAIgGQgCgVAAgKIAAgIIABgJIgFgCIgEgBQgKAAgJAKg");
	this.shape_19.setTransform(-88.9,15.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FF9900").s().p("AAWA+IgDgTIgCgUIAAgHIAAgGQAAgNgHAAQgKAAgHAHQgEAFgIAOQAAAfgCAGQgDAGgFAAQgDAAgDgDQgCgCAAgDIABgFIAAgMIABgLIAAg7IABgPIgBgIIgBgHQAAgEACgCQADgCADAAQAHgBABAIIACAOIgBASIAAASIAAAIQAGgJAIgFQAGgEAJAAQANAAAGAJQADAGABANIAAAQIACARIADASIAAABQAAAEgCADQgDABgDABQgGAAgCgHg");
	this.shape_20.setTransform(-98,13.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FF9900").s().p("AgEA6QgCgCAAgDIAAgKIAAgJIgCgvIgSgBQgHgBAAgIQAAgDACgDQACgCAEAAIARABIAAgLIgBgKQAAgEADgCQACgCAEAAQAFAAABAMIABAHIgBAFIAAAFIAMgBIALABQAFACAAAGQAAADgCADQgCACgEAAIgEAAIgEAAIgLABIABAvIAAAEIABAEQAAASgJAAQgBAAgDgCg");
	this.shape_21.setTransform(-107.1,14.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FF9900").s().p("AgWAuQgMgFAAgIQgBgDADgDQADgCADAAQADAAAEADQABACAIABIAJACQAFAAAFgCQAIgCAAgFQAAgMgQgEIgHgCQgLgCgEgEQgHgCAAgKQAAgRAQgHIAOgGQAMgDAEgCQADgCAFAAQADAAACADQADADAAADIABAHIABAHQAAAEgCADQgDACgEAAQgEAAgCgEIgCgJIgTAGQgMAFAAAJIAFABQARADAJAGQAOAHAAARQAAANgMAHQgJAGgNgBQgLAAgKgDg");
	this.shape_22.setTransform(140.3,-10.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FF9900").s().p("AgYA9QgDAFgDAAQgEAAgCgDQgCgCAAgDIAAgHIAAgGIAAgbIgBgXIABgYIAAgXQAAgEACgFQACgEAFAAQAGgBAAAIIAAADIAAADIgBASIAAAWQAHgGAHgCQAGgCAEAAQASAAALANQALAMAAASQAAATgNANQgMANgQABQgNAAgKgGgAgMgCIgMAGIAAAOIAAANIAAANIAMAFQAFABAGAAQAKAAAIgIQAIgIAAgNQAAgMgHgJQgGgGgMgBQgFABgHAEg");
	this.shape_23.setTransform(131.5,-12.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FF9900").s().p("AgfAmIAAg5IABgIIAAgIQAAgJAHAAQAIAAAAAPQAPgQATAAQAGAAAEAFQADAFAAAKIAAAGQgBAKgHAAQgIABAAgJIAAgFIAAgHQgNABgGAGQgHAGgFAKIAAAsQAAAIgIAAQgIAAAAgIg");
	this.shape_24.setTransform(122.5,-10);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FF9900").s().p("AgbAjQgNgKAAgTQAAgTAKgPQAMgQASAAQANAAAIAFQALAFAAAMQABAJgKAGIgSAIIgdAPQAEAHAHADQAHAEAHAAQAGAAAIgDQAKgCADgFQACgEAEAAQADAAABACQADACAAADQAAAJgPAHQgNAGgMAAQgQAAgMgKgAgQgVQgHAIgDANIAagKQANgHAGgFQgHgHgMAAQgJAAgHAIg");
	this.shape_25.setTransform(113.7,-10.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FF9900").s().p("AgIAlIgMghIgPgkIgBgEQAAgDACgDQADgCADAAQAFAAADAFIAUA4IAOgkIAHgTQADgGAFAAQADAAADACQACADAAADQAAADgNAhIgRAlQgBAIgGAAQgFAAgDgIg");
	this.shape_26.setTransform(104.8,-10.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FF9900").s().p("AgbBAQgLgCAAgHQAAgHAHAAIAKABIAPABQAOAAAHgPQADgKAAgVQgEAIgGAFQgGADgGAAQgPABgJgLQgKgKAAgPQAAgWANgOQANgOAVAAQAIABAFACQAFACADADQAJABAAAJIgCAQIgCAQIgCAZQAAARgEALQgDANgJAGQgJAJgRgBQgMABgGgCgAgOgpQgIALAAAPQAAALAFAFQAEAFAJABQAHgBAHgGQAIgJABgJIAEgcIgHgEIgIgBQgOAAgIAKg");
	this.shape_27.setTransform(90.9,-7.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FF9900").s().p("AATAoIgBgSIgCgTIABgFIAAgIQgBgSgGAAQgJAAgHALQgHAKgEANIgBAIIgBAIIABAIIAAAHQAAAEgCACQgCADgEAAQgDAAgDgDQgCgCAAgEIAAgHIgBgIIABgWIABgXIAAgIIgBgIQABgDACgDQACgCAEAAQAHAAABALIABAKQANgTANAAQAOAAAEAMQAEAIABAPIAAAIIAAAGQAAAHACALIABARQAAAEgCACQgCADgFAAQgHAAgBgIg");
	this.shape_28.setTransform(82.3,-10.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FF9900").s().p("AgGA8QgDgCAAgFIAAgOIAAgPIAAgTIABgSQAAgEACgCQADgDADAAQACAAACADQADACAAAEIgCASIgBATIABAPIAAAOQAAAFgCACQgDACgBAAQgDAAgCgCgAgEgsQgDgDAAgEQAAgEADgDQADgDACAAQAEAAADADQACADAAAEQAAAEgCADQgDACgEAAQgCAAgDgCg");
	this.shape_29.setTransform(75.4,-12.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FF9900").s().p("AgfBDQgCgCAAgEIAAgiIAAgfIgBggIgBgRQAAgHACgDQACgFAFAAQADAAACACQADACAAADIgBADIAAAFQAHgFAHgCQAFgDAFABQARgBAIAQQAGALAAAUQAAAQgJALQgKANgRAAQgHAAgKgDIAAAoQAAAEgCACQgCACgEAAQgEAAgCgCgAgGgrQgFACgHAHIABAlQAKAEAHAAQAKAAAFgHQAFgFAAgLQAAgPgDgHQgEgIgIAAQgFAAgGADg");
	this.shape_30.setTransform(68.4,-8.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FF9900").s().p("AgIA7IABgeIABgdIAAgdIAAgeQAAgIAHAAQAIAAAAAIIAAAeIgBAdIgBAoIgBAUQAAAIgGAAQgIAAAAgJg");
	this.shape_31.setTransform(61.5,-12.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FF9900").s().p("AgbAjQgNgKAAgTQAAgTAKgPQAMgQASAAQANAAAIAFQALAFAAAMQAAAJgJAGIgSAIIgdAPQAEAHAHADQAHAEAIAAQAFAAAIgDQAKgCADgFQACgEADAAQAEAAABACQADACAAADQAAAJgPAHQgMAGgMAAQgSAAgLgKgAgQgVQgGAIgEANIAZgKQAOgHAGgFQgHgHgMAAQgJAAgHAIg");
	this.shape_32.setTransform(54.6,-10.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FF9900").s().p("AAWA/IgDgUIgCgUIAAgGIAAgHQAAgOgHAAQgKAAgHAIQgEAFgIANQAAAhgCAFQgDAFgFAAQgDABgDgDQgCgDAAgDIABgDIAAgNIABgMIAAg7IABgNIgBgIIgBgJQAAgDACgCQADgCADgBQAHABABAHIACAPIgBASIAAASIAAAHQAGgJAIgEQAGgFAJAAQANAAAGAJQADAGABANIAAAQIACARIADARIAAADQAAADgCACQgDACgDAAQgGAAgCgFg");
	this.shape_33.setTransform(45,-12.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FF9900").s().p("AgbAjQgNgKAAgTQAAgTAKgPQAMgQASAAQANAAAIAFQALAFAAAMQABAJgKAGIgSAIIgdAPQAEAHAHADQAHAEAIAAQAFAAAIgDQAKgCADgFQACgEAEAAQADAAABACQADACAAADQAAAJgPAHQgNAGgLAAQgRAAgMgKgAgQgVQgHAIgDANIAagKQANgHAGgFQgHgHgMAAQgJAAgHAIg");
	this.shape_34.setTransform(30.4,-10.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FF9900").s().p("AgfAmIAAg5IABgIIAAgIQAAgJAHAAQAIAAAAAPQAPgQATAAQAGAAAEAFQADAFAAAKIAAAGQgBAKgHAAQgIABAAgJIAAgFIAAgHQgNABgGAGQgHAGgFAKIAAAsQAAAIgIAAQgIAAAAgIg");
	this.shape_35.setTransform(21.8,-10);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FF9900").s().p("AAaAqIgFgGIgPAHQgFACgDAAQgTgBgJgKQgJgLAAgVQABgSAOgPQAOgOAQABQAIgBAIAEQAMAFAAAGIgCAFIgBAJIgBARQABAKABAHIAFAOIACAEIABACQgBADgBADQgDABgDAAQgCAAgEgDgAgNgTQgJAKAAALQAAAPAFAGQAEAHAKAAQAHAAAFgDIAJgHQgEgUAAgKIABgIIABgJIgFgCIgEgBQgKAAgKALg");
	this.shape_36.setTransform(13.1,-10);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FF9900").s().p("AgWAuQgMgFAAgIQAAgDACgDQADgCADAAQACAAAEADQACACAHABIAKACQAFAAAFgCQAIgCAAgFQAAgMgQgEIgGgCQgMgCgEgEQgHgCAAgKQAAgRAQgHIAOgGQAMgDAEgCQADgCAFAAQADAAACADQACADAAADIACAHIABAHQAAAEgDADQgCACgDAAQgFAAgCgEIgCgJIgTAGQgMAFAAAJIAGABQAQADAKAGQANAHAAARQAAANgMAHQgJAGgNgBQgLAAgKgDg");
	this.shape_37.setTransform(-0.7,-10.4);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FF9900").s().p("AgYA9QgDAFgDAAQgEAAgCgDQgCgCAAgDIAAgHIAAgGIAAgbIgBgXIABgYIAAgXQAAgEACgFQACgEAFAAQAGgBAAAIIAAADIAAADIgBASIAAAWQAHgGAHgCQAGgCAEAAQASAAALANQALAMAAASQAAATgNANQgMANgQABQgNAAgKgGgAgMgCIgMAGIAAAOIAAANIAAANIAMAFQAFABAGAAQAKAAAIgIQAIgIAAgNQAAgMgHgJQgGgGgMgBQgFABgHAEg");
	this.shape_38.setTransform(-9.5,-12.3);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FF9900").s().p("AgfAmIAAg5IABgIIAAgIQAAgJAHAAQAIAAAAAPQAPgQATAAQAGAAAEAFQADAFAAAKIAAAGQgBAKgHAAQgIABAAgJIAAgFIAAgHQgNABgGAGQgHAGgFAKIAAAsQAAAIgIAAQgIAAAAgIg");
	this.shape_39.setTransform(-18.6,-10);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FF9900").s().p("AgbAjQgNgKAAgTQAAgTAKgPQAMgQASAAQANAAAIAFQAMAFgBAMQAAAJgJAGIgSAIIgdAPQAEAHAHADQAHAEAIAAQAFAAAIgDQAJgCAEgFQACgEADAAQAEAAACACQACACAAADQAAAJgPAHQgMAGgMAAQgSAAgLgKgAgQgVQgGAIgEANIAZgKQANgHAHgFQgHgHgMAAQgJAAgHAIg");
	this.shape_40.setTransform(-27.4,-10.1);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FF9900").s().p("AgIAlIgMghIgPgkIgBgEQAAgDACgDQADgCADAAQAFAAADAFIAUA4IAOgkIAHgTQADgGAFAAQADAAADACQACADAAADQAAADgNAhIgRAlQgBAIgGAAQgFAAgDgIg");
	this.shape_41.setTransform(-36.2,-10.1);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FF9900").s().p("AgRA/QgCgCAAgEQAAgDAIgPIAKgSQgPgTgEgJQgEgKgJgNIgOgWIgBgEQAAgEADgCQACgDAEAAQADAAADAEIAHALIALARQAHALADAIQADAHAHAKIATgsIAJgSQACgFAGAAQADAAACACQADACAAAEQAAAEgEAIIgFAJIgPAjIgQAhIgJATIgDAJQgDAFgEAAQgEAAgDgDg");
	this.shape_42.setTransform(-51.2,-12);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FF9900").s().p("AgpA+QgCgCAAgEIgBgTIgBgUIACgVIACgWIgBgNIgBgMQAAgFADgEQADgEAGAAIAUACQALABAGAEQAhASAAAaQAAANgLAHQgJAIgOAEQAaAOANAPQACADAAADQAAAEgDACQgCADgEAAQgDAAgDgDQgbgbgggKIABARIAAAQQAAAEgCACQgCADgEAAQgEAAgCgDgAgZgkIAAAKIgBARIgBAOIADAAIAEAAQAUAAAKgFQAEgBAEgEQAFgFAAgDQAAgMgNgKQgKgJgOgBIgMgBg");
	this.shape_43.setTransform(-61.5,-12.2);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FF9900").s().p("AAcAqIgFgaIgWAFIgUAEIgPAgQgCAEgFAAQgDABgCgDQgDgDAAgDQAAgEANgaQgCgDAAgDQAAgGAIgCQAKgQAOgWQASggAFAAQAGAAADAJIAEAcIANA4IAFAMIACAJQAAAEgDADQgCACgDAAQgIAAgGgUgAgJAGIAcgGIgHgfg");
	this.shape_44.setTransform(-73.3,-11.9);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FF9900").s().p("AgjA8QgCgCgBgDQABgEACgDQACgCAEAAIARgCIABgPIAAgOIgBgOQAAgRACgdIgKABIgLAAQgEgBgCgCQgCgCgBgEQAAgHAJgBIAZgBQAOAAAZADQAHABAAAIQAAAFgCACQgDACgDAAIgNgBIgOgCIgCAsIAAAOIABAPIgBAOIAbgBQADAAADADQACACAAAEQAAADgCADQgDACgDAAIgPABIgNAAIgPACIgQABQgEAAgCgDg");
	this.shape_45.setTransform(-84.1,-12);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FF9900").s().p("AgjBBQgEgEAAgJIABgbQACgkAAgvQAAgDADgDQACgCADAAQAEAAADACQABADAAADQAAAvgBAlIgBAMIgBAMQAVABAggLIACAAQAEAAADADQABACAAAEQAAAFgFACQgJAFgVADQgQADgLAAQgJAAgEgCg");
	this.shape_46.setTransform(-93.2,-12);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FF9900").s().p("AgjA8QgCgCgBgDQABgEACgDQACgCAEAAIASgCIAAgPIAAgOIAAgOQAAgRABgdIgKABIgLAAQgDgBgDgCQgDgCABgEQgBgHAJgBIAYgBQAPAAAZADQAHABABAIQAAAFgDACQgDACgDAAIgOgBIgNgCIgBAsIAAAOIAAAPIAAAOIAagBQADAAACADQACACABAEQgBADgCADQgCACgDAAIgPABIgNAAIgOACIgRABQgEAAgCgDg");
	this.shape_47.setTransform(-102.7,-12);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FF9900").s().p("AAoBAQgHgGgHgKIgLgRIgMgTIgbAhIgPARQgDADgEAAQgCAAgEgDQgCgCAAgEQAAgDACgCIAPgRIAfgiIgTgZIgKgNIgLgMQgDgCAAgEQAAgEADgCQACgDAEAAQAGAAAMAPIAKAOIAQAXIATgaQASgaAFAAQAEAAACADQADACAAAEQAAADgCACIgRAWIgLAQIgLANIATAaIASAaQADADAAADQAAADgDADQgCACgEAAQgDAAgCgCg");
	this.shape_48.setTransform(-113.6,-11.9);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FF9900").s().p("AgkAxQgKgMgDgYQgBgKAAgeIABgSIABgLQACgGAGAAQAHAAAAAOIAAAwQAAAxAhAAQAiAAAAhTIAAgIIgBgGQAAgGACgEQADgFAEAAQAIAAAAAMIABAKIAAAKQAABfgyAAQgYAAgNgPg");
	this.shape_49.setTransform(-125.9,-12);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FF9900").s().p("AAdAqIgGgaIgWAFIgUAEIgOAgQgDAEgEAAQgEABgDgDQgCgDAAgDQAAgEAMgaQgBgDAAgDQAAgGAIgCQAJgQAPgWQASggAEAAQAHAAACAJIAFAcIANA4IAFAMIACAJQAAAEgCADQgDACgDAAQgIAAgFgUgAgKAGIAdgGIgHgfg");
	this.shape_50.setTransform(-138.5,-11.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-146.7,-26.7,293.5,53.4);


(lib.Tween1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AhCBzQgfgPAAgZQAAgHAFgEQAFgFAHAAQAIABAGAIQAJAOAGAEQAOAJAbAAQAYAAAWgLQAcgOAAgZQAAgWgYgMQgUgKgbgBQgaAAgTgJQgXgOAAgZQAAgdAhgZQAggXAgAAQAQAAAVAFQAbAIAAAKQAAAPgPAAQgHAAgRgDQgQgEgJAAQgYAAgSANQgTANAAASQAAAOAZAFQAJADAYACQAmADAVAUQAUARAAAdQAAAngkAYQggAUgoAAQgeAAgagLg");
	this.shape.setTransform(147.5,2.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AhMB/QgHgHAAgGIAAgxQAAgYADgqIAEhFQgBgPACgeQACgIAEgDQAXgHAcAAQAcAAAbAUQAeAXAAAiQABAqgiAXQAZALANANQAMAMAAAQQAAAUgVASQgQAOgRAHQgjAOg6AAQgHAAgGgHgAgyBCIAAAiQAsgBAZgMQALgEALgKQAKgIAAgEQAAgIgVgKQgQgHgOgEIgQgDIgHABIgHAAIgTgCIgBAmgAgrhiIAAAdIgEBBIAZACQAXgCARgPQAQgOAAgXQAAgQgQgNQgSgOgSAAIgZABg");
	this.shape_1.setTransform(125.6,1.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF0000").s().p("AhUB9QgEgFAAgHIgBgnIgCgnQAAgQADgcQAEgeAAgPIgCgZIgBgZQAAgKAFgHQAGgJALABIAoADQAXADAOAJQBDAjAAA0QAAAZgXARQgSAQgcAIQA0AcAZAfQAFAFAAAGQAAAHgFAFQgGAFgGAAQgHAAgFgFQg3g3hBgSIABAgIABAhQAAAHgFAFQgFAFgHAAQgHAAgFgFgAg0hJIABAUQAAANgCAUIgDAfIAHAAIAHAAQAqAAAUgLQAJgDAIgJQAJgJAAgGQAAgXgbgUQgWgTgagCIgZgCg");
	this.shape_2.setTransform(103.8,1.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF0000").s().p("AhIB/QgQgPAAg0IABgYIABgbQgCgEAAgEQAAgEAEgEQADgxAAgXIgCgSIgBgSQAAgTAQAAQAHAAAFAEIAmgIQARgCAOAAQAoAAAZAJQALAFAAALQAAAIgFAEQgFAGgHAAIgFgBQgcgIgaAAQgNAAgPACQgQADgSAFIABARQAAAYgDAoIBHgHIAngDQAIAAAFAEQAFAFAAAIQAAANgQACIgnADIhLAIIgBAVIAAAVQAAAkAFAGQAEAFAWAAIAdAAIAfgBIAKgBIAKgCQARABAAARQAAAOgOADQgQADgxAAQg0AAgPgOg");
	this.shape_3.setTransform(82.6,1.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF0000").s().p("AgdB5QgUgzgYhdIgOgtQgKgjABgKQAAgIAFgFQAEgEAIAAQAMAAAEANIAGAdIAQA5QAQA7APAtIABgDIArh2IANgpQAKgYAKgNQAGgHAIAAQAGAAAFAGQAGAFAAAHQAAAFgEAFQgKAPgGARIgNAkIgtB3QgIAVgKAVQgEAKgJAAQgNAAgFgNg");
	this.shape_4.setTransform(61.6,1.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF0000").s().p("AgjB/QgFgFAAgHQAAgGAQgdIAUgmQgegmgIgUQgIgTgRgaIgcgsQgDgEAAgFQAAgGAFgFQAGgGAGAAQAIABAGAHIANAVIAXAjQANAVAHASQAFANAQAWIAmhbIASgjQAFgMALAAQAGAAAFAGQAGAEAAAHQAAAIgJAQIgLATIgcBHQgRAmgPAdIgTAlIgIASQgGAKgJAAQgGAAgGgFg");
	this.shape_5.setTransform(28,1.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF0000").s().p("AhUB9QgEgFAAgHIgBgnIgCgnQAAgQADgcQAEgeAAgPIgCgZIgBgZQAAgKAFgHQAGgJALABIAoADQAXADAOAJQBDAjAAA0QAAAZgXARQgSAQgcAIQA0AcAZAfQAFAFAAAGQAAAHgFAFQgGAFgGAAQgHAAgFgFQg3g3hBgSIABAgIABAhQAAAHgFAFQgFAFgHAAQgHAAgFgFgAg0hJIABAUQAAANgCAUIgDAfIAHAAIAHAAQAqAAAUgLQAJgDAIgJQAJgJAAgGQAAgXgbgUQgWgTgagCIgZgCg");
	this.shape_6.setTransform(7.4,1.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF0000").s().p("AA5BWQgEgPgHgmQgQADgcAGIgqAJQgIAVgUAqQgGAKgIAAQgHAAgGgFQgFgFAAgHQAAgIAZg1QgDgEAAgGQAAgNARgEQATgiAcguQAmg/AKAAQAMAAAGATIAKA3IAZByIAJAaQAFANAAAFQAAAHgFAFQgGAFgGAAQgPAAgMgngAgUAMQAUgGAngGIgNg/g");
	this.shape_7.setTransform(-16.3,1.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF0000").s().p("AhIB6QgFgFAAgHQAAgHAFgGQAFgEAHAAQALAAAYgEQACgNAAgSIgBgbIgBgcQAAglAFg6IgWABIgWABQgHAAgEgFQgFgFAAgIQAAgPAPgBQAOgBAlgBQAfAAAxAHQAPADAAAPQAAAIgFAFQgFADgHABQgKAAgRgCIgagEQgEAwAAAqIABAdIAAAdIgBAcIA0AAQAHAAAFAEQAFAGAAAHQAAAGgFAFQgFAFgHABIgcAAIgbABQgJAAgWACQgWADgLAAQgHAAgFgEg");
	this.shape_8.setTransform(-37.8,1.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF0000").s().p("AhHCCQgKgHAAgTIADg2QAFhLAAhcQAAgHAEgFQAFgFAIAAQAGAAAFAFQAFAFAAAHQAABegFBLIgBAZQgCAOABAKQArABBAgVIAFgBQAIAAAEAGQAFAFgBAGQAAALgLAFQgSAJgoAHQgjAGgXAAQgSAAgHgFg");
	this.shape_9.setTransform(-56,1.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF0000").s().p("AhIB6QgFgFAAgHQAAgHAFgGQAFgEAHAAQALAAAYgEQACgNAAgSIgBgbIgBgcQAAglAFg6IgWABIgWABQgHAAgEgFQgFgFAAgIQAAgPAPgBQAOgBAlgBQAfAAAxAHQAPADAAAPQAAAIgFAFQgFADgHABQgKAAgRgCIgagEQgEAwAAAqIABAdIAAAdIgBAcIA0AAQAHAAAFAEQAFAGAAAHQAAAGgFAFQgFAFgHABIgcAAIgbABQgJAAgWACQgWADgLAAQgHAAgFgEg");
	this.shape_10.setTransform(-75.1,1.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FF0000").s().p("ABPCAQgMgMgOgUIgWgiIgagmIg3BDIgfAiQgFAFgGAAQgIAAgEgFQgGgFAAgHQAAgGAEgFIAfgiIA+hGQgTgYgUgZIgUgaQgLgQgKgIQgHgGAAgHQAAgHAFgFQAEgGAIAAQAOAAAWAeIAUAdQAUAXAOAWIAmg0QAlg0AMAAQAGAAAFAFQAFAGABAHQAAAFgFAGQgXAbgMARIgUAfQgMARgLALIAlA0QAWAgARAUQAEAFAAAGQAAAHgFAGQgFAFgHAAQgGAAgGgFg");
	this.shape_11.setTransform(-96.9,1.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FF0000").s().p("AhIBiQgVgYgGgvQgCgVAAg9IABgmQABgPACgGQAFgLAKAAQAPAAABAcIAABhQAABjBEAAQBCAAAAioIAAgQIAAgNQAAgLADgHQAFgKAKAAQAQAAAAAWIAAAVIAAAVQAAC9hkAAQgxAAgZgdg");
	this.shape_12.setTransform(-121.4,1.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FF0000").s().p("AA6BWQgFgPgGgmQgSADgaAGIgrAJQgIAVgUAqQgFAKgKAAQgGAAgFgFQgGgFAAgHQAAgIAZg1QgCgEAAgGQAAgNAQgEQASgiAeguQAlg/AJAAQAOAAAEATIALA3IAYByIAKAaQAFANAAAFQAAAHgFAFQgGAFgGAAQgPAAgLgngAgUAMQAUgGAngGIgOg/g");
	this.shape_13.setTransform(-146.7,1.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-161.1,-25.7,322.2,51.4);


(lib.static_buffy_activebuble = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(4,1,1).p("AGBAAQAACfhxBwQhxByifAAQieAAhxhyQhxhwAAifQAAieBxhxQBxhxCeAAQCfAABxBxQBxBxAACeg");
	this.shape.setTransform(38.5,38.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,204,102,0.502)").s().p("AkPEQQhwhxgBifQABieBwhxQBxhxCeABQCfgBBwBxQBxBxABCeQgBCfhxBxQhwBwifAAQieAAhxhwg");
	this.shape_1.setTransform(38.5,38.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2,-2,81,81);


(lib.BuffyStill = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.1,1,1).p("AAUASQgGgGAEgKQABgCACgEQAGgIAJgEQAJgEAJACQAKADAFAIQAEAGAAAEQgBADgBAEQgDAHgGAGQABACABADAAUASQgDABgDACAA0ARQgIgCgIgBQgEAAgEABQgEABgEACABJADQgGgFgJADQgLAHAFAJQABAAAAAAQAGACADAEAgZgHQAAAAAAgBQABgKgKgFQgIgFgJACQgKADgEAKQgDAJAEAIQAFgCAGABQAFAAAFACQAEABAEACQABAAACAAQAAAAAAAAQAHgIAAgHgAgrAFQgCgLALgDQAGgBADADQAAAAAAAAAhAAEQgEABgEAD");
	this.shape.setTransform(-6,-11.7,2.365,2.365);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAnALIgBAAQgFgKALgEQAJgFAFAGIgBAFQgDAIgGAGQgDgEgGgCgAgxABIgIgBQgCgNALgCQAGgCADADIAAABQgBAIgGAGIgBABIgCgBg");
	this.shape_1.setTransform(-2.6,-10.3,2.365,2.365);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAPAGQABgEADgCQAGgHAJgEQAJgFAJADQAKACAFAJQADAEAAAFQgGgGgJAFQgLAGAGAKQgIgDgIAAQgFgBgEACIgIADQgFgGADgLgAg4AHQgGAAgFACQgDgJADgJQADgKAKgCQAKgCAIAFQAJAFAAAKIgBAAQgDgCgFABQgLACABAMIgKgDg");
	this.shape_2.setTransform(-5.3,-12.9,2.365,2.365);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(0.1,1,1).p("AisiaQgDgMAIgLQALgRATgCQAEgBAEABQADgMAMgIQAPgMATgCQATgDAHASQABAEACACQgDgSARgKQAPgKARAEQANADANAGQAQAIADARQAJgKAMgFQARgIAQAIQAPAIAEASQADAQgEAQQAJgDAKAAQAMABAJAHQAIAGgCAKQgFATAUAHQAUAHgEATQgBALgKAFQAKADALAAQAQABAMAMQAJAJgEANQgGARgNAIQALAAAKADQAKADABAJQABAUgNANQAGABAEACQAIAFgCAOQABAJgGALQgNAUgXAFQgEABgEgGQgIAPgVACQgZAPgagRQgGgDgBgEQABAFgCADQgGAJgMgBQgNAAgJgIQABADABADQACAGADAFQAGACAGACQAIADAHABQAFABAEACQADAAAEABQAJADAJABIgyBkIiiAAIhHhaQAFAAAHgCQABgBACAAQAIgDAIgEQAHgDAHgFQAGgEAFgGQAAgBAAgCQAAgDgBgDQgGAAgGACQgOAEgOAGQgUAHABgSQgVATgcgDQgfgEAHgUQgXAGgEgYQgFgbAVgHQgJgDgBgJQgDgQAHgQQALgXAYgJQgMgFADgMQAFgVAVgFQAJgCAEgHQADgHgDgLABMAJQAAgGABgDQAAAAABgBQACgBABgCQABgCAAgDQAAgKgEgIQAAgBAAgBQAFABgBgGQAAgBAAgBQABgIgBgHQAAgCAAgCQAAgFgBgDQAAgDAAgBQABgBAAAAQABgEAAgDQgBgFgDgDQgEgEgEgEQgBgBgBgBQAAgBAAAAQgCgBgBgCQgEgIgGgFQgEgEgEgCQgCAAgBgCQgCgCgCgBIAAgBQgDgCgCgCQgBAAgBAAQgDAAgDABQgBAAgBABQgEABgCAAQAAgBgBAAQgBAAgBgCQAAgBgBAAQgDAAgBgCQgCgCgDABQgFACgCACQgBAAgBABQgDACgEgBQgDAAgDACQgBACgBABQgFAFgGABQgCABgBgBQgCgCgBgCQgBgBgBgBQAAAAgBAAQgCgBgBgBQgFgDgHABQgBAAgBABQgBAAAAAAQgBABgBAAQgHACgHgCQgBAAAAAAQgDAAAAACQgBABgBABQgBAAgBABQgDABgEAEQgBABgBAAQgCADgBADQAAACAAACQAAABAAABIAAAAQAAADgDAAQgBAAAAABQgDACgBACQAAABAAABIAAAAQgMADgGAJQgDAEgCAFQgDAHgCAHQgDAKAAAMIgBAAQgLgCgHALQgDAEgCAGQgFAMgBAOQgBATAKASQAJAPANAMQAOANAPAKQAEADADACQANAHAPACQAUADATgGQATgGANgLQACgDAEAAAAUhXQAFgCAGgCQADgBAEAAQAKAAAIAFQACABABACQADADACADAhMhdQACgDABgDQABgCACgBQAIgEAJAAQAFABAFACQACAAABABQADADAEACAishFQgSgEgJgPQgKgSAIgVQAIgTASABQAEAAACACQgBgCAAgCQgCgDAAgEQABADABADQAAAAAAABAipiPQACACABADAiCgfQAAABAAABQAAAGABAFAhDgLQAEgKAKAAQALAAAFAJAhqAFQAJgBAKgBQAKgCAFAGQABACABACQACADACACQgHgCgGgCQgJgDgKgCQgEgBgEgBQgEgBgDgBIgBAAQgEAIACAJQABAKAEAIQAEAJAHAGQACACACACQAKgBAJgCQAJgDAJAAQAKgBAKAAQAJgBAJgEQACgCADgBQACgBACgBQAEgGACgHQgKgDgKgDQgJgCgIgFQgLgHgFALQgBAAgBgBQgDAAgCgBAhgA5QAGADAGADQAJADAJABQAKAAAJgEQAJgDAJgFQAHgFAHgHQABgBACgCAhdBqQADAGACAGAhXB/QABAGAAAGQAAAHgBAHQAAADAAACABMAJQgDADgCAEABDBIQADAAAEgBQAKgDAHgHQAHgHAEgIQAEgJAAgJQAAgGgDgGQgBgDgCgDQgGgJgLAEQgEABgDADABDBIQgGAAgFgCABIBwQgBgEgBgEQgCgKgBgJQAAgGAAgHAgGAbQgJAAgJgBQgJAAgJgDQgJgCgIgD");
	this.shape_3.setTransform(0,0,2.365,2.365);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#B5783E").s().p("AgaAcIgMgHQAJAAAJgCQAJgDAKAAIARgBQAKgBAIgEIAFgDIABABQgHAHgHAFQgIAFgKADQgIAEgJAAQgJgBgIgDgAAfgHQgJAAgJgDIgPgFQADgLALAHQAIAFAJACIAUAGIgGAAIgMgBgAgWgVIgTgFIgIgCIATgCQAKgCAFAGIACAEIAFAFIgOgEg");
	this.shape_4.setTransform(-13.6,8.3,2.365,2.365);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AglAXQgHgGgFgJQgEgIgBgIQgBgJAEgIIAAAAIAIACIAIACIASAFIAOAEIADABIACABIAQAFQAJADAJAAIATABQgCAFgEAFIgEADIgGADQgIAEgKABIgTABQgIAAgJADQgJACgJAAIgEgDg");
	this.shape_5.setTransform(-14.9,7.2,2.365,2.365);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#CC9A67").s().p("Ag9C8IhHhaQAFAAAHgCIADgBIAQgHIAOgIQAGgEAFgGIABAMIgBAOIAAAFIAAgFIABgOIgBgMIAAgDIgBgGQgCgGgDgGQANAHAPACIANABIAAAAIAAAAQANAAANgEQARgGAPgLQACgDAEAAQgEAAgCADQgPALgRAGQgNAEgNAAIAAAAIAAAAIgNgBQgPgCgNgHIgHgFQgPgKgOgNQgNgMgJgNQgKgSABgTQABgPAFgNIAFgKQAHgLALACIABAAQAAgLADgLIAFgOIAFgJQAGgJAMgDIAAAAIAAgCIAEgEIABgBQAAAAABAAQABAAAAAAQABgBAAAAQAAgBAAgBIAAAAIAAgCIAAgEQABgDACgDIACgBIAHgFIACgBIACgCQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAABAAIABAAQAHACAHgCIACgBIABAAIACgBQAHgBAFADIADACIABAAIACACIADAEQAAAAAAAAQAAABABAAQAAAAABAAQAAAAABgBQAGgBAFgFIACgDQADgCABAAQAEABADgCIADgBIAIgEQADgBACACQAAAAAAABQABAAAAABQABAAAAAAQABAAABAAIABABIACACIABABQACAAAEgBIACgBIAGgBIACAAIAFAEIAAABIAEADIADACQAEADAEADQAFAFAFAIIADADIAAABIACACIAIAIQADADABAFQAAAEgBADIgBABIAAAEIABAIIAAAEIAAAPIAAACQABAGgFgBIAAACQAEAIAAAKIgBAFIgDADIgBACQgBAEAAAGQgDADgCAEQACgEADgDIAHgEQALgEAGAJIADAGQADAGAAAGQAAAJgEAJQgEAIgHAFQgHAHgKADIgHABIgBAAIgBAAIgDAAIgBgBIgEgBIgBAAIABAAIAEABIABABIADAAIABAAIABAAIAAANIADATIACAIIACAGIAFALIAMAEIAPAEIAJADIAHABIASAEIgyBkgAhng0QgEAIACAJQABAKAEAIQAEAJAHAGIAEACIAMAGQAJADAJABQAKAAAJgEQAJgDAJgDQAHgFAHgHIADgDQACgGACgHIgSgGQgJgCgIgFQgLgHgFALIgCgBIgFgBIgEgFIgCgEQgFgGgKACIgTACIgHgCgAgqhOQgKAAgEAKQAEgKAKAAIABAAIAAAAIAAAAIAAAAQAKABAEAHIABAAIAAABIAAgBIgBAAQgEgHgKgBIAAAAIAAAAIAAAAIgBAAgAh3hWQAAAGABAFQgBgFAAgGIAAgCIAAACIAAAAgABDiQIADADIAFAGIgFgGIgDgDQgIgFgKAAIgHABIgLAEIALgEIAHgBQAKAAAIAFgAg7ifIgDADIgDAGIADgGIADgDIABAAQAGgDAHgBIABAAIAAAAIABAAIABAAQAFABAFACIADABIAHAFIgHgFIgDgBQgFgCgFgBIgBAAIgBAAIAAAAIgBAAQgHABgGADIgBAAg");
	this.shape_6.setTransform(-2.6,13.5,2.365,2.365);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#271B0E").s().p("AjEC+QgfgEAHgUQgXAGgEgYQgFgbAVgHQgJgDgBgJQgDgQAHgQQALgZAYgJQgMgFADgMQAFgTAVgFQAJgDAEgGQgSgEgJgPQgKgSAIgVQAIgTASABQAEAAACACIgBgEIAAgBIgCgGQgDgMAIgLQALgRATgCQAEgBAEABQADgMAMgIQAPgMATgCQATgDAHASIADAGQgDgSARgKQAPgKARAEQANADANAGQAQAIADARQAJgKAMgFQARgIAQAIQAPAIAEASQADAQgEAQQAJgDAKAAQAMABAJAHQAIAGgCAKQgFATAUAHQAUAHgEATQgBALgKAFQAKADALAAQAQABAMAMQAJAHgEANQgGARgNAIQALAAAKADQAKADABALQABATgNAOQAGAAAEADQAIAFgCANQABAKgGALQgNAUgXAFQgEABgEgGQgIAPgVACQgZAPgagRQgGgEgBgDQABAFgCADQgGAJgMgBQgNgBgJgHIgCgIIgDgTIAAgNIAHgBQAKgDAHgHQAHgHAEgIQAEgJAAgJQAAgHgDgFIgDgGQgGgJgLAEIgHADQAAgFABgEIABgCIADgDIABgFQAAgKgEgIIAAgCQAFABgBgGIAAgCIAAgPIAAgCIgBgIIAAgEIABgCQABgDAAgDQgBgFgDgDIgIgIIgCgCIAAgBIgDgDQgEgIgGgFQgEgEgEgCIgDgCIgEgEIAAAAIgFgEIgCAAIgGABIgCABQgEABgCgBIgBAAIgCgCIgBgBQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAAAQgCgCgDABIgHADIgCACQgDACgEgBQgDAAgDACIgCADQgFAFgGABQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAAAAAAAIgDgEIgCgCIgBAAIgDgCQgFgDgHABIgCAAIgBABIgCABQgHACgHgCIgBAAQgBAAAAAAQgBAAAAAAQgBAAAAABQAAAAAAABIgCACIgCABIgHAFIgCABQgCADgBADIAAAEIAAACIAAAAQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIgBABIgEAEIAAACIAAAAQgMADgGAJIgFAJIgFAMQgDAKAAAMIgBAAQgLgDgHALIgFALQgFANgBAPQgBATAKASQAJAPANAMQAOANAPAKIAHAFQADAFACAHQgGAAgGACIgcAKQgUAHABgSQgSAQgXAAIgIAAgAisgOQABgEAAgEIgBgKIABAKQAAAEgBAEgAimhTQgBgDgCgCQACACABADg");
	this.shape_7.setTransform(0,-12.9,2.365,2.365);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60,-59,120.1,118.1);


(lib.skiptomenu = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_1 = function() {
		playSound("clickwav");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(1).call(this.frame_1).wait(3));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AATApQgLAGgMAAQgMAAgHgFQgJgGgBgKQgEgYABgQQgBgMADgPQABgIAHAAQAEAAADADQACACAAAEIgBANIgBANIABAXQABALACAGIAGADIAFAAQAKAAANgDIAAgSIgBgPQAAgTACgOQABgIAIAAQADAAADACQADADgBADIgBAhIAAARIAAATIAAAGIAAAGQABAEgDACQgDADgDAAQgHAAgCgJg");
	this.shape.setTransform(16.7,0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AAVAqIgDgTIgBgTIABgGIAAgJQAAgSgHgBQgKAAgHAMQgIALgFAOIgBAIIAAAJIAAAIIABAIQAAAEgCADQgDACgEAAQgDAAgDgCQgCgDAAgEIgBgIIAAgIIABgYIABgYIAAgIIAAgJQAAgDACgDQADgDADABQAIAAABALIAAAKQAPgUAOAAQAOAAAFANQAEAIAAAQIAAAJIAAAGIACATQACAMAAAHQAAAEgCADQgDABgEAAQgHABgBgJg");
	this.shape_1.setTransform(7.5,0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgdAmQgNgMAAgTQAAgVALgQQAMgQATgBQAOAAAJAGQALAFAAANQAAAJgKAHQgEADgOAFIggAQQAFAIAHADQAIADAIAAQAGAAAIgBQAKgDADgFQADgFAEAAQADAAACADQACACAAADQAAAKgPAGQgOAHgMAAQgSAAgNgKgAgRgWQgHAIgDAPIAbgLQAOgIAGgFQgHgIgNAAQgKABgHAIg");
	this.shape_2.setTransform(-2.2,0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgEAzQgCgCAAgEIgCggIgCgdQAAgJgDgGQgGADgHAHIgKALIgEAGIgBANIgBAPIAAAIIABAHQAAADgCADQgDACgEAAQgKAAAAgWIABgQIABgOIAAgOIgBgOQAAgUAJAAQADAAADADQADADAAAEIgBAFIAAAFIAAAJQAFgJAIgIQAJgHAHAAQANAAAEAOQAEgHAHgDQAHgDAIAAQAPAAAFAQQACADACAVIAGAxQABADgDADQgDACgDAAQgIAAgBgIIgDgbIgDgZQgBgGgCgGQgDgIgDAAQgEAAgJAGQgIAFgDADIABAQIACAWQACAOAAAJQAAAEgCACQgDADgEAAQgBAAgDgDg");
	this.shape_3.setTransform(-14.1,0.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(2,1,1).p("AkZh7IIzAAIAAD3IozAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AkZB8IAAj3IIzAAIAAD3g");

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAVAuQgMAGgOAAQgMAAgJgGQgJgGgBgMQgEgZAAgSQAAgNADgRQABgJAIAAQAEAAADADQADADAAAEIgCAOIgBAPIABAZQABAMACAHIAGADIAGAAQALAAAPgEIAAgTIAAgRQAAgVABgPQABgJAJAAQAEAAADACQADADgBAEIgBAlIAAATIAAAVIAAAGIAAAHQAAAEgCACQgDADgEAAQgIAAgCgJg");
	this.shape_6.setTransform(18.3,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AAXAvIgDgWIgBgVIAAgHIABgJQAAgVgIAAQgLAAgIANQgJALgFAQIgBAKIAAAJIAAAJIABAJQAAAEgDADQgCACgFAAQgEAAgCgCQgDgDAAgEIgBgJIAAgJIABgaIACgbIgBgJIAAgJQAAgFADgCQACgDAEAAQAJAAABANIAAALQARgWAPAAQAPAAAGAOQAFAJAAASIAAAKIAAAHQAAAIACAMQACANAAAIQAAAEgDADQgDADgEAAQgIAAgBgJg");
	this.shape_7.setTransform(8.2,0.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AggApQgPgMAAgWQAAgXAMgRQAOgSAVAAQAPAAAKAFQANAHAAAOQAAAJgMAIQgEAEgQAFIgjASQAFAIAJAEQAIAEAJAAQAHAAAIgDQALgDAEgFQADgFAEAAQADAAADACQADADAAADQAAALgRAIQgPAGgOAAQgVAAgNgLgAgTgZQgHAJgEARIAdgMQAQgJAIgGQgJgIgOAAQgLAAgIAJg");
	this.shape_8.setTransform(-2.4,0.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgEA5QgDgDAAgFQAAgLgCgXQgDgVAAgMQAAgKgCgGQgHADgHAHIgMANIgEAGIgCAPIgBARIABAIIABAIQAAAEgDACQgDADgEAAQgLAAAAgZIACgRIABgPIgBgQIgBgPQAAgWAKAAQADAAAEADQADAEAAADIgBAGIAAAGIAAAKQAFgKAKgJQAJgIAHAAQAPAAAEAPQAGgHAHgDQAHgEAKAAQAQAAAGARIAEAcIAHA1QAAAEgDADQgDACgEAAQgIAAgBgIQgCgLgCgTIgDgcIgDgNQgEgJgEAAQgDAAgKAGQgJAGgDADIAAASIADAYQACAQAAAJQAAAFgCADQgDACgEAAQgCAAgDgCg");
	this.shape_9.setTransform(-15.6,0.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#000000").ss(2,1,1).p("AE3CJIptAAIAAkRIJtAAg");
	this.shape_10.setTransform(0,0.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#00FFFF").s().p("Ak2CJIAAkRIJsAAIAAERg");
	this.shape_11.setTransform(0,0.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AATApQgLAGgMAAQgMAAgHgFQgJgGgBgKQgEgYABgQQgBgMADgPQABgIAHAAQAEAAADADQACACAAAEIgBANIgBANIABAXQABALACAGIAGADIAFAAQAKAAANgDIAAgSIgBgPQAAgTACgOQABgIAIAAQADAAADACQADADgBADIgBAhIAAARIAAATIAAAGIAAAGQABAEgDACQgDADgDAAQgHAAgCgJg");
	this.shape_12.setTransform(16.7,1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAVArIgDgUIgBgTIABgHIAAgHQAAgUgHAAQgKAAgHAMQgIALgFAOIgBAJIAAAIIAAAIIABAIQAAAEgCACQgDACgEAAQgDAAgDgCQgCgCAAgEIgBgIIAAgIIABgYIABgYIAAgJIAAgIQAAgEACgCQADgCADgBQAIAAABAMIAAAKQAPgTAOgBQAOAAAFANQAEAIAAARIAAAIIAAAGIACAUQACALAAAHQAAAEgCACQgDACgEABQgHgBgBgHg");
	this.shape_13.setTransform(7.5,0.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgdAlQgNgLAAgTQAAgVALgPQAMgSATABQAOAAAJAEQALAHAAAMQAAAJgKAHQgEADgOAFIggAQQAFAHAHAEQAIAEAIAAQAGgBAIgCQAKgDADgEQADgFAEAAQADAAACACQACACAAAEQAAAJgPAIQgOAFgMAAQgSAAgNgKgAgRgWQgHAIgDAPIAbgLQAOgIAGgGQgHgGgNgBQgKAAgHAJg");
	this.shape_14.setTransform(-2.2,0.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgEAzQgCgCAAgEIgCggIgCgdQAAgJgDgGQgGADgHAHIgKALIgEAGIgBANIgBAPIAAAIIABAHQAAADgCADQgDACgEAAQgKAAAAgWIABgQIABgOIAAgOIgBgOQAAgUAJAAQADAAADADQADADAAAEIgBAFIAAAFIAAAJQAFgJAIgIQAJgHAHAAQANAAAEAOQAEgHAHgDQAHgDAIAAQAPAAAFAQQACADACAVIAGAxQABADgDADQgDACgDAAQgIAAgBgIIgDgbIgDgZQgBgGgCgGQgDgIgDAAQgEAAgJAGQgIAFgDADIABAQIACAWQACAOAAAJQAAAEgCACQgDADgEAAQgBAAgDgDg");
	this.shape_15.setTransform(-14.1,1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#000000").ss(2,1,1).p("AEah7IAAD3IozAAIAAj3g");

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#0066CC").s().p("AkZB8IAAj3IIzAAIAAD3g");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},1).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12}]},1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-29.2,-16.9,58.6,30.5);


(lib.general_buttoncolor = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{resetRed:1});

	// timeline functions:
	this.frame_0 = function() {
		this.play();
	}
	this.frame_8 = function() {
		this.gotoAndPlay("resetRed");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(8).call(this.frame_8).wait(2));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#D5FFD7","#61EF01","#1DA400","#004A00"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgvAAgjgjQgjgjAAgwQAAgvAjgjQAjgjAvAAQAwAAAjAjQAjAjAAAvQAAAwgjAjQgjAjgwAAIAAAAg");
	this.shape.setTransform(11.9,11.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FFFFFF","#EC0000","#9D0000","#480000"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgvAAgjgjQgjgjAAgwQAAgvAjgjQAjgjAvAAQAwAAAjAjQAjAjAAAvQAAAwgjAjQgjAjgwAAIAAAAg");
	this.shape_1.setTransform(11.9,11.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},8).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,23.7,23.6);


(lib.Copyright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAbAHIgDgKIgEAKQgEAIgDAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBgBAAgBIgCgIIgBgHQgGASgCAAIgDgBIgBgCIABgCQADgFABgFIACgNQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAEAAACAJIADAKIACgGIADgJQADgEACAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAEAKIACAGIACAIIABACIgBACIgCABQgDAAgDgJgAgTANIgBgIIAAgGIgBgHIgFAAIgGAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAgBAAAAQAAgBAAgBQAAAAABgBQAAAAABgBQAAAAABAAIAFABIAEAAIAPAAIADgBIAEAAQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAABAAAAQAAAAAAABQAAAAgBAAIgOAAIAAAIIABAFIABAEIABAEIgCACIgCABQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAgBAAAAg");
	this.shape.setTransform(57.3,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgLAYQgGgDgBgEIABgDQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAIAEACIAEABIAFABIAFgBQADgBAAgDQABgGgJgCIgCgBIgIgDQgEAAAAgFQAAgKAIgEIAHgCIAIgDIAEgBIADABIABAEIABADIAAAEIgBADIgCABQgBAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIgCgFIgJADQgFADgBAEIADABQAIACAFACQAHADAAAJQAAAHgGAEQgFADgGAAQgFAAgGgCg");
	this.shape_1.setTransform(51,2.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgLATQgHgGABgKQAAgGAFgKQAHgKAGAAQAEAAAGACQAGACABAEIgBADQgBAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgDgBIgBgBQgDgCgGAAQgCAAgFAIQgDAHAAADQAAAGADAEQAEADAEAAIAGgCIAEgCIACgBIAEABIABADQgBADgGADQgGADgEAAQgHAAgGgFg");
	this.shape_2.setTransform(46.6,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgDAfQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAAAIAAgJIAAgIIAAgKIAAgIQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBIACgBIACABQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABIAAAIIgBAKIAAAIIABAJQAAAAAAAAQAAABgBAAQAAABAAAAQAAAAgBAAIgBABIgDgBgAgBgXQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQAAAAAAAAQAAAAAAgBQABABAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBAAAAgBg");
	this.shape_3.setTransform(43.1,1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAKAVIgBgJIgBgKIABgDIAAgDQAAgKgEAAQgFAAgCAFQgEAGgCAGIgBAEIAAAFIAAADIAAAFIgBADIgDABIgDgBIgBgDIAAgFIgBgDIABgMIAAgLIAAgFIAAgEIABgDIAEgBQAEAAAAAFIAAAGQAHgKAGAAQAHAAADAGQACAEAAAJIAAAEIAAACIABAKIABAJIgBADIgDABQgEAAgBgEg");
	this.shape_4.setTransform(39.5,2.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_5.setTransform(34.8,2.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AALAhIgBgLIgBgKIAAgDIAAgEQAAgGgEAAQgFAAgDADIgGAKQAAARgCACQAAABgBABQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDIABgBIAAgHIAAgHIAAgeIABgHIgBgFIAAgEQAAAAAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQAEAAAAAEIABAIIAAAKIAAAJIAAAEQADgFAEgCQACgDAFAAQAHAAADAFQABADABAGIABAJIAAAIIACAKIAAABQAAABAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIgDABQgEAAgBgDg");
	this.shape_6.setTransform(30,1.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgLATQgHgGABgKQAAgGAFgKQAHgKAGAAQAEAAAGACQAGACABAEIgBADQgBAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgDgBIgBgBQgDgCgGAAQgCAAgFAIQgDAHAAADQAAAGADAEQAEADAEAAIAGgCIAEgCIACgBIAEABIABADQgBADgGADQgGADgEAAQgHAAgGgFg");
	this.shape_7.setTransform(25,2.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgOATQgGgGAAgKQAAgKAFgHQAGgJAJAAQAGABAFACQAGADAAAHQAAAEgFADIgKAEIgOAHQACAEAEABQAEADACAAIAIgBQAFgCABgDQABAAAAAAQAAgBABAAQAAAAABAAQAAAAAAAAIADAAIABADQAAAFgIADQgGADgHABQgIgBgGgEgAgIgKQgDAEgCAGIANgFQAGgDAEgDQgEgDgGgBQgEAAgEAFg");
	this.shape_8.setTransform(20.3,2.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAaAgIgCgGIgBgIQgCgHgEgWIgJAYIgDAJIgDAIQgBAEgCAAQgDgBgBgDIgCgEIgBgFIgIgfIgCAHIgFAWIgCAMQgBAEgDAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgEQAAgHADgLIAFgPIADgOQACgKABgDQACgCADAAQACAAACADQACAEABAMQADAOAFAPQAFgPAEgSIACgGIACgHQABgDADAAQAEAAACAIIACAKQADASADAOIACAHIACAHQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgCABQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBgBg");
	this.shape_9.setTransform(13.8,1.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgQAUIAAgdIAAgEIABgFQAAgEADAAQAFAAAAAHQAHgIAKAAQADAAACADQACACAAAGIAAADQgBAFgEAAQgEAAAAgEIAAgDIAAgEQgHABgCADQgEADgDAGIABAWQAAAEgFAAQgEAAAAgEg");
	this.shape_10.setTransform(5.1,2.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_11.setTransform(0.5,2.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgBAZQAAAAgBAAQAAgBAAAAQAAAAAAgBQgBAAAAgBIgBgPIgBgOQAAgFgBgCQgDABgDADIgFAGIgDADIAAAGIgBAHIABAEIAAADQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABQgFAAAAgLIAAgIIABgGIgBgHIAAgHQAAgKAFAAIACACQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAADIgBACIAAAFQADgFAEgDQAFgEADAAQAGAAACAHQACgEADgBQAEgCAEAAQAHAAADAIIACAMIADAYIgBADIgDABQgEAAgBgEIgBgOIgCgLIgBgGQgCgEgCAAIgFADIgGAEIAAAHIABALIABALIgBADIgDACQAAAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBg");
	this.shape_12.setTransform(-5.2,2.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgBAZQAAAAgBAAQAAgBAAAAQAAAAAAgBQgBAAAAgBIgBgPIgBgOQABgFgCgCQgDABgDADIgFAGIgCADIgBAGIgBAHIABAEIABADQAAABgBAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABQgFAAAAgLIABgIIAAgGIAAgHIgBgHQAAgKAEAAIADACQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAADIgBACIAAAFQADgFAEgDQAFgEADAAQAGAAABAHQADgEADgBQADgCAFAAQAHAAADAIIACAMIADAYIgCADIgCABQgEAAgBgEIgCgOIgBgLIgBgGQgCgEgCAAIgFADIgGAEIAAAHIABALIABALIgBADIgDACQAAAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBg");
	this.shape_13.setTransform(-12.2,2.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAOAWIgDgDIgIADIgDABQgKABgFgHQgFgFAAgLQAAgJAIgHQAHgIAIAAQAEAAAFACQAGADAAADIgBACIgBAFIAAAJIABAIIACAIIACACIAAABIgBADIgDABIgDgCgAgGgKQgFAGAAAGQAAAGADAEQACAEAFgBQADABADgCIAEgDIgBgPIAAgFIABgEIgDgBIgCgBQgFAAgFAFg");
	this.shape_14.setTransform(-18.1,2.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgQAUIAAgdIAAgEIABgFQAAgEADAAQAFAAAAAHQAHgIAKAAQADAAACADQACACAAAGIAAADQgBAFgEAAQgEAAAAgEIAAgDIAAgEQgHABgCADQgEADgDAGIABAWQAAAEgFAAQgEAAAAgEg");
	this.shape_15.setTransform(-22.4,2.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgVAeQgFgGgBgMQABgMAFgKQAFgMAIgIQAHgEAEAAQAEAAAGACQAIAEAAADIgBADIgEABIgCgBQgHgDgEAAQgDgBgCAEIgGAGQgKAOAAAOQABAIACADQACAEAIAAQAGgBAGgFQAGgEACgLQgMABgGAEIgDABQAAgBAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQAIgEAXAAIADABIABACQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQgDANgIAJQgJAHgKABQgKgBgGgFg");
	this.shape_16.setTransform(-27.7,1.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgNAhIgBgDIACgJIAKgWQAFgOAHgIIABgBIgVAAIgJgBQgFAAAAgEQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAQAAIAPABIAIAAQAFAAAAACQAAADgDADIgEAFQgGAGgFAKIgHAPIgCAKIgEAKQgBABAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIgDgBg");
	this.shape_17.setTransform(-36.2,1.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AABAiIgHAAIgFgBQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQgBgEAIAAIACAAIABAAIAAgHIgBgGIABgPIABgRQgFAFgCAAIgDgBIgBgDQAAgDADgCIAHgGQACgEAEAAQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAADIAAADIAAAEIAAAEIgBAPIgBANIAAAGIABAGIAFAAQAAAAAAAAQABAAAAABQABAAAAAAQAAAAABABIAAADIAAADIgDABg");
	this.shape_18.setTransform(-41,1.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgSAXQgFgKAAgNQAAgMAGgKQAHgMAKAAQAMABAGAJQAGAJAAANQAAARgGAKQgGAJgMAAQgMABgGgMgAgLgRQgEAIAAAJQAAAMAEAHQAEAHAHAAQAIABAEgLQADgIAAgJQAAgMgDgGQgEgGgIAAQgGAAgFAIg");
	this.shape_19.setTransform(-45.9,1.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AANAhIgDgBIgHAAIgFABIgFAAIgFAAIgBAAIgCAAQgDAAgBgDIAAgFQAAgKAGgHQACgDALgFIAHgHQADgEAAgGQAAgDgDgCQgDgCgDAAQgDAAgDADIgGAEIgDACQgFAAAAgEQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAFgFAEgCQAFgDAEAAQAHAAAFAEQAGAEAAAHIgBAIIgEAHQgDACgIAFQgGAFgDADQgFAFABAHIAJgBIALAAIAGABQAEABAAADQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAIgDABIgDAAg");
	this.shape_20.setTransform(-51.3,1.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgeAAQAAgKALgJQALgKALAAQAOAAAHAIQAHAIAAAMQAAAJgJAKQgKALgMAAIAAABQgeAAAAgegAgOgOQgIAGAAAIQAAAMAGAFQAGAEAKAAQAJAAAIgIQAGgIAAgGQAAgJgEgFQgFgGgIAAIgCAAQgKAAgIAHgAgKAJQgGgEAAgFQAAgGAIgFQAGgFAFAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAIgCgBIgBAAQgDAAgEADQgEACAAADQAAABADACIAFABQABAAAEgCIAEgCIADAAIABADQAAADgEADQgGADgDAAQgFAAgFgDg");
	this.shape_21.setTransform(-57.7,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.3,-7.1,126.6,16.6);


(lib.blank_gr = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00CCFF").s().p("Aj9CqIAAlSIH7AAIAAFSg");
	this.shape.setTransform(32.5,17,1.275,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,65,34);


(lib.Bk = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(3,1,1).p("EAnFgX3MhOJAAAMAAAAvvMBOJAAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FFFFFF","#3399FF"],[0,1],0.4,-207.7,-1,217.9).s().p("EgnEAX4MAAAgvvMBOJAAAMAAAAvvg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-251.6,-154.3,503.3,308.7);


(lib.anim_buffy_talk = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 7
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.1,1,1).p("AAUASQgGgGAEgKQABgCACgEQAGgIAJgEQAJgEAJACQAKADAFAIQAEAGAAAEQgBADgBAEQgDAHgGAGQABACABADAA0ARQgIgCgIgBQgEAAgEABQgEABgEACQgDABgDACABJADQgGgFgJADQgLAHAFAJQABAAAAAAQAGACADAEAgZgHQAAAAAAgBQABgKgKgFQgIgFgJACQgKADgEAKQgDAJAEAIQAFgCAGABQAFAAAFACQAEABAEACQABAAACAAQAAAAAAAAQAHgIAAgHgAgrAFQgCgLALgDQAGgBADADQAAAAAAAAAhAAEQgEABgEAD");
	this.shape.setTransform(22.5,19.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAnALIgBAAQgFgKALgEQAJgFAFAGIgBAFQgDAIgGAGQgDgEgGgCgAgxABIgIgBQgCgNALgCQAGgCADADIAAABQgBAIgGAGIgBABIgCgBg");
	this.shape_1.setTransform(23.9,20.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAPAGQABgEADgCQAGgHAJgEQAJgFAJADQAKACAFAJQADAEAAAFQgGgGgJAFQgLAGAGAKQgIgDgIAAQgFgBgEACIgIADQgFgGADgLgAg4AHQgGAAgFACQgDgJADgJQADgKAKgCQAKgCAIAFQAJAFAAAKIgBAAQgDgCgFABQgLACABAMIgKgDg");
	this.shape_2.setTransform(22.7,19.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(0.1,1,1).p("AATAFQADgBADgCQADgBAEgBQAEAAAFAAQAIAAAIABQAAAAABABQAFABADAEQACACAAADAhDgGQADgDAEgBQAFgCAGABQAFABAFABQAFABAEAC");
	this.shape_3.setTransform(22,21.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(0.1,1,1).p("AAYgHQAFgGAHgDQAJgEAJACQAKADAFAIQAEAGAAAEQgBADgBAEQgDAHgGAGQABACABADAARAHQAAgCABgDQABgCACgEQACgCABgBIAAAAQAEAAADADQADADAAACQAAAEgDADQgDADgEAAQgCAAgCgBQgBgBgCgBQAAAAAAgBQgBAHAEAEQAEgCAEgBQAEgBAEAAQAIABAIACQABAAAAAAQAGACADAEAAUASQgDABgDACAhBACQgCgHACgIQABgBAAgBQAEgJAJgCQAJgCAIAFQAKAFgBAKQAAABAAAAQAAAHgHAIQAAAAAAAAQgCAAgBAAQgEgCgEgBQgFgCgFAAQgGgBgFACAhAgPQACAAABAAQAEAAADADQADADAAAEQAAAEgDABQgDADgEAAQgCAAgCgBQAAABABABQgEABgEADAgZgHQAAAAAAAA");
	this.shape_4.setTransform(22.5,19.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAyATIgBAAQgIgCgIgBQgEAAgEABIgIADQgEgEAAgGIABAAIADACIAEABQAEAAADgDQADgDAAgEQAAgDgDgCQgDgDgEAAIAAAAQAFgFAHgEQAJgEAJACQAKADAFAIQADAFAAAFIgBAHQgDAHgGAGQgDgEgGgCgAgmAKIgIgDIgKgCQgGgBgGACIAAgCIAEABQAEAAADgDQADgCAAgDQAAgEgDgDQgDgDgEAAIgDABQADgJAKgDQAJgCAIAFQAKAFgBAKIAAABIAAAAQgBAHgGAIIgBABIgCgBg");
	this.shape_5.setTransform(22.8,19.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAkANIgCgCIgBgBIABgGQABgEADgBIACgDIABAAQAEAAADADQADABAAAEQAAAEgDADQgDADgEAAIgFgBgAgxAEQgCgHADgIIAAgBIAEgBQAEAAADADQADADAAAEQAAADgDACQgDADgEAAIgFgBg");
	this.shape_6.setTransform(20.8,19.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#000000").ss(0.1,1,1).p("AAUASQgGgGAEgKQABgCACgEQAGgIAJgEQAJgEAJACQAKADAFAIQAEAGAAAEQgBADgBAEQgDAHgGAGQABACABADAAUASQgDABgDACAA0ARQgIgCgIgBQgEAAgEABQgEABgEACABJADQgGgFgJADQgLAHAFAJAA+AXQgDgEgGgCQAAAAgBAAAgZgHQAAAAAAgBQABgKgKgFQgIgFgJACQgKADgEAKQgDAJAEAIQAFgCAGABQAFAAAFACQAEABAEACQABAAACAAQAAAAAAAAQAHgIAAgHQAAAAAAAAQgDgDgGABQgLADACALAhAAEQgEABgEAD");
	this.shape_7.setTransform(22.5,19.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#000000").ss(0.1,1,1).p("AAYgHQAFgGAHgDQAJgEAJACQAKADAFAIQAEAGAAAEQgBADgBAEQgDAHgGAGQgDgEgGgCQAAAAgBAAQgIgCgIgBQgEAAgEABQgEABgEACQgEgEABgHQAAABAAAAQACABABABQACABACAAQAEAAADgDQADgDAAgEQAAgCgDgDQgDgDgEAAIAAAAQgBABgCACQgCAEgBACQgBADAAACAAUASQgDABgDACAA+AXQABACABADAhAgPQACAAABAAQAEAAADADQADADAAAEQAAAEgDABQgDADgEAAQgCAAgCgBQgCgHACgIQABgBAAgBgAgZgHQAAAAAAgBQABgKgKgFQgIgFgJACQgJACgEAJAhAAEQAFgCAGABQAFAAAFACQAEABAEACQABAAACAAQAAAAAAAAQAHgIAAgHQAAAAAAAAAhBACQAAABABABQgEABgEAD");
	this.shape_8.setTransform(22.5,19.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3}]},2).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4}]},2).to({state:[{t:this.shape_1},{t:this.shape_2},{t:this.shape_7}]},3).to({state:[{t:this.shape_3}]},2).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_8}]},2).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape_7}]},3).to({state:[{t:this.shape_3}]},3).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},2).wait(4));

	// Layer 8
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#000000").ss(0.1,1,1).p("AisiaQgDgMAIgLQALgRATgCQAEgBAEABQADgMAMgIQAPgMATgCQATgDAHASQABAEACACQgDgSARgKQAPgKARAEQANADANAGQAQAIADARQAJgKAMgFQARgIAQAIQAPAIAEASQADAQgEAQQAJgDAKAAQAMABAJAHQAIAGgCAKQgFATAUAHQAUAHgEATQgBALgKAFQAKADALAAQAQABAMAMQAJAJgEANQgGARgNAIQALAAAKADQAKADABAJQABAUgNANQAGABAEACQAIAFgCAOQABAJgGALQgNAUgXAFQgEABgEgGQgIAPgVACQgZAPgagRQgGgDgBgEQABAFgCADQgGAJgMgBQgNAAgJgIQABADABADQACAGADAFQAGACAGACQAIADAHABQAFABAEACQADAAAEABQAJADAJABIgyBkIiiAAIhHhaQAFAAAHgCQABgBACAAQAIgDAIgEQAHgDAHgFQAGgEAFgGQAAgBAAgCQAAgDgBgDQgGAAgGACQgOAEgOAGQgUAHABgSQgVATgcgDQgfgEAHgUQgXAGgEgYQgFgbAVgHQgJgDgBgJQgDgQAHgQQALgXAYgJQgMgFADgMQAFgVAVgFQAJgCAEgHQADgHgDgLABMAJQAAgGABgDQAAAAABgBQACgBABgCQABgCAAgDQAAgKgEgIQAAgBAAgBQAFABgBgGQAAgBAAgBQABgIgBgHQAAgCAAgCQAAgFgBgDQAAgDAAgBQABgBAAAAQABgEAAgDQgBgFgDgDQgEgEgEgEQgBgBgBgBQAAgBAAAAQgCgBgBgCQgEgIgGgFQgEgEgEgCQgCAAgBgCQgCgCgCgBIAAgBQgDgCgCgCQgBAAgBAAQgDAAgDABQgBAAgBABQgEABgCAAQAAgBgBAAQgBAAgBgCQAAgBgBAAQgDAAgBgCQgCgCgDABQgFACgCACQgBAAgBABQgDACgEgBQgDAAgDACQgBACgBABQgFAFgGABQgCABgBgBQgCgCgBgCQgBgBgBgBQAAAAgBAAQgCgBgBgBQgFgDgHABQgBAAgBABQgBAAAAAAQgBABgBAAQgHACgHgCQgBAAAAAAQgDAAAAACQgBABgBABQgBAAgBABQgDABgEAEQgBABgBAAQgCADgBADQAAACAAACQAAABAAABIAAAAQAAADgDAAQgBAAAAABQgDACgBACQAAABAAABIAAAAQgMADgGAJQgDAEgCAFQgDAHgCAHQgDAKAAAMIgBAAQgLgCgHALQgDAEgCAGQgFAMgBAOQgBATAKASQAJAPANAMQAOANAPAKQAEADADACQANAHAPACQAUADATgGQATgGANgLQACgDAEAAAAUhXQAFgCAGgCQADgBAEAAQAKAAAIAFQACABABACQADADACADAhMhdQACgDABgDQABgCACgBQAIgEAJAAQAFABAFACQACAAABABQADADAEACAishFQgSgEgJgPQgKgSAIgVQAIgTASABQAEAAACACQgBgCAAgCQgCgDAAgEQABADABADQAAAAAAABAipiPQACACABADAiCgfQAAABAAABQAAAGABAFAhDgLQAEgKAKAAQALAAAFAJAhqAFQAJgBAKgBQAKgCAFAGQABACABACQACADACACQgHgCgGgCQgJgDgKgCQgEgBgEgBQgEgBgDgBIgBAAQgEAIACAJQABAKAEAIQAEAJAHAGQACACACACQAKgBAJgCQAJgDAJAAQAKgBAKAAQAJgBAJgEQACgCADgBQACgBACgBQAEgGACgHQgKgDgKgDQgJgCgIgFQgLgHgFALQgBAAgBgBQgDAAgCgBAhgA5QAGADAGADQAJADAJABQAKAAAJgEQAJgDAJgFQAHgFAHgHQABgBACgCAhdBqQADAGACAGAhXB/QABAGAAAGQAAAHgBAHQAAADAAACABMAJQgDADgCAEABDBIQADAAAEgBQAKgDAHgHQAHgHAEgIQAEgJAAgJQAAgGgDgGQgBgDgCgDQgGgJgLAEQgEABgDADABDBIQgGAAgFgCABIBwQgBgEgBgEQgCgKgBgJQAAgGAAgHAgGAbQgJAAgJgBQgJAAgJgDQgJgCgIgD");
	this.shape_9.setTransform(25,24.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#B5783E").s().p("AgaAcIgMgHQAJAAAJgCQAJgDAKAAIARgBQAKgBAIgEIAFgDIABABQgHAHgHAFQgIAFgKADQgIAEgJAAQgJgBgIgDgAAfgHQgJAAgJgDIgPgFQADgLALAHQAIAFAJACIAUAGIgGAAIgMgBgAgWgVIgTgFIgIgCIATgCQAKgCAFAGIACAEIAFAFIgOgEg");
	this.shape_10.setTransform(19.3,28);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AglAXQgHgGgFgJQgEgIgBgIQgBgJAEgIIAAAAIAIACIAIACIASAFIAOAEIADABIACABIAQAFQAJADAJAAIATABQgCAFgEAFIgEADIgGADQgIAEgKABIgTABQgIAAgJADQgJACgJAAIgEgDg");
	this.shape_11.setTransform(18.7,27.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#CC9A67").s().p("Ag9C8IhHhaQAFAAAHgCIADgBIAQgHIAOgIQAGgEAFgGIABAMIgBAOIAAAFIAAgFIABgOIgBgMIAAgDIgBgGQgCgGgDgGQANAHAPACIANABIAAAAIAAAAQANAAANgEQARgGAPgLQACgDAEAAQgEAAgCADQgPALgRAGQgNAEgNAAIAAAAIAAAAIgNgBQgPgCgNgHIgHgFQgPgKgOgNQgNgMgJgNQgKgSABgTQABgPAFgNIAFgKQAHgLALACIABAAQAAgLADgLIAFgOIAFgJQAGgJAMgDIAAAAIAAgCIAEgEIABgBQAAAAABAAQABAAAAAAQABgBAAAAQAAgBAAgBIAAAAIAAgCIAAgEQABgDACgDIACgBIAHgFIACgBIACgCQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAABAAIABAAQAHACAHgCIACgBIABAAIACgBQAHgBAFADIADACIABAAIACACIADAEQAAAAAAAAQAAABABAAQAAAAABAAQAAAAABgBQAGgBAFgFIACgDQADgCABAAQAEABADgCIADgBIAIgEQADgBACACQAAAAAAABQABAAAAABQABAAAAAAQABAAABAAIABABIACACIABABQACAAAEgBIACgBIAGgBIACAAIAFAEIAAABIAEADIADACQAEADAEADQAFAFAFAIIADADIAAABIACACIAIAIQADADABAFQAAAEgBADIgBABIAAAEIABAIIAAAEIAAAPIAAACQABAGgFgBIAAACQAEAIAAAKIgBAFIgDADIgBACQgBAEAAAGQgDADgCAEQACgEADgDIAHgEQALgEAGAJIADAGQADAGAAAGQAAAJgEAJQgEAIgHAFQgHAHgKADIgHABIgBAAIgBAAIgDAAIgBgBIgEgBIgBAAIABAAIAEABIABABIADAAIABAAIABAAIAAANIADATIACAIIACAGIAFALIAMAEIAPAEIAJADIAHABIASAEIgyBkgAhng0QgEAIACAJQABAKAEAIQAEAJAHAGIAEACIAMAGQAJADAJABQAKAAAJgEQAJgDAJgDQAHgFAHgHIADgDQACgGACgHIgSgGQgJgCgIgFQgLgHgFALIgCgBIgFgBIgEgFIgCgEQgFgGgKACIgTACIgHgCgAgqhOQgKAAgEAKQAEgKAKAAIABAAIAAAAIAAAAIAAAAQAKABAEAHIABAAIAAABIAAgBIgBAAQgEgHgKgBIAAAAIAAAAIAAAAIgBAAgAh3hWQAAAGABAFQgBgFAAgGIAAgCIAAACIAAAAgABDiQIADADIAFAGIgFgGIgDgDQgIgFgKAAIgHABIgLAEIALgEIAHgBQAKAAAIAFgAg7ifIgDADIgDAGIADgGIADgDIABAAQAGgDAHgBIABAAIAAAAIABAAIABAAQAFABAFACIADABIAHAFIgHgFIgDgBQgFgCgFgBIgBAAIgBAAIAAAAIgBAAQgHABgGADIgBAAg");
	this.shape_12.setTransform(23.9,30.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#271B0E").s().p("AjEC+QgfgEAHgUQgXAGgEgYQgFgbAVgHQgJgDgBgJQgDgQAHgQQALgZAYgJQgMgFADgMQAFgTAVgFQAJgDAEgGQgSgEgJgPQgKgSAIgVQAIgTASABQAEAAACACIgBgEIAAgBIgCgGQgDgMAIgLQALgRATgCQAEgBAEABQADgMAMgIQAPgMATgCQATgDAHASIADAGQgDgSARgKQAPgKARAEQANADANAGQAQAIADARQAJgKAMgFQARgIAQAIQAPAIAEASQADAQgEAQQAJgDAKAAQAMABAJAHQAIAGgCAKQgFATAUAHQAUAHgEATQgBALgKAFQAKADALAAQAQABAMAMQAJAHgEANQgGARgNAIQALAAAKADQAKADABALQABATgNAOQAGAAAEADQAIAFgCANQABAKgGALQgNAUgXAFQgEABgEgGQgIAPgVACQgZAPgagRQgGgEgBgDQABAFgCADQgGAJgMgBQgNgBgJgHIgCgIIgDgTIAAgNIAHgBQAKgDAHgHQAHgHAEgIQAEgJAAgJQAAgHgDgFIgDgGQgGgJgLAEIgHADQAAgFABgEIABgCIADgDIABgFQAAgKgEgIIAAgCQAFABgBgGIAAgCIAAgPIAAgCIgBgIIAAgEIABgCQABgDAAgDQgBgFgDgDIgIgIIgCgCIAAgBIgDgDQgEgIgGgFQgEgEgEgCIgDgCIgEgEIAAAAIgFgEIgCAAIgGABIgCABQgEABgCgBIgBAAIgCgCIgBgBQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAAAQgCgCgDABIgHADIgCACQgDACgEgBQgDAAgDACIgCADQgFAFgGABQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAAAAAAAIgDgEIgCgCIgBAAIgDgCQgFgDgHABIgCAAIgBABIgCABQgHACgHgCIgBAAQgBAAAAAAQgBAAAAAAQgBAAAAABQAAAAAAABIgCACIgCABIgHAFIgCABQgCADgBADIAAAEIAAACIAAAAQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIgBABIgEAEIAAACIAAAAQgMADgGAJIgFAJIgFAMQgDAKAAAMIgBAAQgLgDgHALIgFALQgFANgBAPQgBATAKASQAJAPANAMQAOANAPAKIAHAFQADAFACAHQgGAAgGACIgcAKQgUAHABgSQgSAQgXAAIgIAAgAisgOQABgEAAgEIgBgKIABAKQAAAEgBAEgAimhTQgBgDgCgCQACACABADg");
	this.shape_13.setTransform(25,19);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#CC9A67").s().p("AAAAAIABAAIgBABg");
	this.shape_14.setTransform(23.4,28.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#000000").ss(0.1,1,1).p("AgZABQAPAQAOgGQALgFAFgGQAFAAAEAAQgCgDgKgGQgEgDgDABQgHACgHgCQgUgDgMAPQgFAAgFAAAgZABQAJAAAJAAQANAAAOgBAgkABQAFAAAGAAAAdAAQABAAAAAAQAIAAAJAA");
	this.shape_15.setTransform(18.1,28.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#000000").ss(0.1,1,1).p("AisiaQgDgMAIgLQALgRATgCQAEgBAEABQADgMAMgIQAPgMATgCQATgDAHASQABAEACACQgDgSARgKQAPgKARAEQANADANAGQAQAIADARQAJgKAMgFQARgIAQAIQAPAIAEASQADAQgEAQQAJgDAKAAQAMABAJAHQAIAGgCAKQgFATAUAHQAUAHgEATQgBALgKAFQAKADALAAQAQABAMAMQAJAJgEANQgGARgNAIQALAAAKADQAKADABAJQABAUgNANQAGABAEACQAIAFgCAOQABAJgGALQgNAUgXAFQgEABgEgGQgIAPgVACQgZAPgagRQgGgDgBgEQABAFgCADQgGAJgMgBQgNAAgJgIQABADABADQACAGADAFQAGACAGACQAIADAHABQAFABAEACQADAAAEABQAJADAJABIgyBkIiiAAIhHhaQAFAAAHgCQABgBACAAQAIgDAIgEQAHgDAHgFQAGgEAFgGQAAgBAAgCQAAgDgBgDQgGAAgGACQgOAEgOAGQgUAHABgSQgVATgcgDQgfgEAHgUQgXAGgEgYQgFgbAVgHQgJgDgBgJQgDgQAHgQQALgXAYgJQgMgFADgMQAFgVAVgFQAJgCAEgHQgSgEgJgPQgKgSAIgVQAIgTASABQAEAAACACQgBgCAAgCQgCgDAAgEgABMAJQAAgGABgDQAAAAABgBQACgBABgCQABgCAAgDQAAgKgEgIQAAgBAAgBQAFABgBgGQAAgBAAgBQABgIgBgHQAAgCAAgCQAAgFgBgDQAAgDAAgBQABgBAAAAQABgEAAgDQgBgFgDgDQgEgEgEgEQgBgBgBgBQAAgBAAAAQgCgBgBgCQgEgIgGgFQgEgEgEgCQgCAAgBgCQgCgCgCgBIAAgBQgDgCgCgCQgBAAgBAAQgDAAgDABQgBAAgBABQgEABgCAAQAAgBgBAAQgBAAgBgCQAAgBgBAAQgDAAgBgCQgCgCgDABQgFACgCACQgBAAgBABQgDACgEgBQgDAAgDACQgBACgBABQgFAFgGABQgCABgBgBQgCgCgBgCQgBgBgBgBQAAAAgBAAQgCgBgBgBQgFgDgHABQgBAAgBABQgBAAAAAAQgBABgBAAQgHACgHgCQgBAAAAAAQgDAAAAACQgBABgBABQgBAAgBABQgDABgEAEQgBABgBAAQgCADgBADQAAACAAACQAAABAAABIAAAAQAAADgDAAQgBAAAAABQgDACgBACQAAABAAABIAAAAQgMADgGAJQgDAEgCAFQgDAHgCAHQgDAKAAAMIgBAAQgLgCgHALQgDAEgCAGQgFAMgBAOQgBATAKASQAJAPANAMQAOANAPAKQAEADADACQANAHAPACQAUADATgGQATgGANgLQACgDAEAAAAUhXQAFgCAGgCQADgBAEAAQAKAAAIAFQACABABACQADADACADAhMhdQACgDABgDQABgCACgBQAIgEAJAAQAFABAFACQACAAABABQADADAEACAiqiTQAAgBAAAAQgBgDgBgDAipiPQACACABADAishFQADgHgDgLAiCgfQAAABAAABQAAAGABAFAhDgLQAEgKAKAAQALAAAFAJAhdBqQADAGACAGAhXB/QABAGAAAGQAAAHgBAHQAAADAAACABDBIQADAAAEgBQAKgDAHgHQAHgHAEgIQAEgJAAgJQAAgGgDgGQgBgDgCgDQgGgJgLAEQgEABgDADQgDADgCAEABIBwQgBgEgBgEQgCgKgBgJQAAgGAAgHQgGAAgFgC");
	this.shape_16.setTransform(25,24.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#B5783E").s().p("AgVABIgLAAQAMgPAUADQAHACAGgCQAEgBAEADQAKAGACADIgJAAQgOABgNAAIgSAAIASAAQANAAAOgBQgFAGgLAFQgFABgDAAQgKAAgLgLg");
	this.shape_17.setTransform(17.7,28.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#CC9A67").s().p("Ag9C8IhHhaQAFAAAHgCIADgBIAQgHIAOgIQAGgEAFgGIABAMIgBAOIAAAFIAAgFIABgOIgBgMIAAgDIgBgGQgCgGgDgGQANAHAPACIANABIAAAAIAAAAQANAAANgEQARgGAPgLQACgDAEAAQgEAAgCADQgPALgRAGQgNAEgNAAIAAAAIAAAAIgNgBQgPgCgNgHIgHgFQgPgKgOgNQgNgMgJgNQgKgSABgTQABgPAFgNIAFgKQAHgLALACIABAAQAAgLADgLIAFgOIAFgJQAGgJAMgDIAAAAIAAgCIAEgEIABgBQAAAAABAAQABAAAAAAQABgBAAAAQAAgBAAgBIAAAAIAAgCIAAgEQABgDACgDIACgBIAHgFIACgBIACgCQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAABAAIABAAQAHACAHgCIACgBIABAAIACgBQAHgBAFADIADACIABAAIACACIADAEQAAAAAAAAQAAABABAAQAAAAABAAQAAAAABgBQAGgBAFgFIACgDQADgCABAAQAEABADgCIADgBIAIgEQADgBACACQAAAAAAABQABAAAAABQABAAAAAAQABAAABAAIABABIACACIABABQACAAAEgBIACgBIAGgBIACAAIAFAEIAAABIAEADIADACQAEADAEADQAFAFAFAIIADADIAAABIACACIAIAIQADADABAFQAAAEgBADIgBABIAAAEIABAIIAAAEIAAAPIAAACQABAGgFgBIAAACQAEAIAAAKIgBAFIgDADIgBACQgBAEAAAGIAHgEQALgEAGAJIADAGQADAGAAAGQAAAJgEAJQgEAIgHAFQgHAHgKADIgHABIgBAAIgBAAIgDAAIgBgBIgEgBIgBAAIABAAIAEABIABABIADAAIABAAIABAAIAAANIADATIACAIIACAGIAFALIAMAEIAPAEIAJADIAHABIASAEIgyBkgAhegSIALABQAPAPAQgGQALgEAFgHIAJgBIABAAIARgBIgRABIgBAAQgCgEgKgGQgEgCgEABQgGABgJgBIgGgBQgQAAgKAOgAhegSIgKAAIAKAAgABSgnQACgEADgDQgDADgCAEgAgqhOQgKAAgEAKQAEgKAKAAIABAAIAAAAIAAAAIAAAAQAKABAEAHIABAAIAAABIAAgBIgBAAQgEgHgKgBIAAAAIAAAAIAAAAIgBAAgAh3hWQAAAGABAFQgBgFAAgGIAAgCIAAACIAAAAgABDiQIADADIAFAGIgFgGIgDgDQgIgFgKAAIgHABIgLAEIALgEIAHgBQAKAAAIAFgAg7ifIgDADIgDAGIADgGIADgDIABAAQAGgDAHgBIABAAIAAAAIABAAIABAAQAFABAFACIADABIAHAFIgHgFIgDgBQgFgCgFgBIgBAAIgBAAIAAAAIgBAAQgHABgGADIgBAAg");
	this.shape_18.setTransform(23.9,30.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#000000").ss(0.1,1,1).p("AisiaQgDgMAIgLQALgRATgCQAEgBAEABQADgMAMgIQAPgMATgCQATgDAHASQABAEACACQgDgSARgKQAPgKARAEQANADANAGQAQAIADARQAJgKAMgFQARgIAQAIQAPAIAEASQADAQgEAQQAJgDAKAAQAMABAJAHQAIAGgCAKQgFATAUAHQAUAHgEATQgBALgKAFQAKADALAAQAQABAMAMQAJAJgEANQgGARgNAIQALAAAKADQAKADABAJQABAUgNANQAGABAEACQAIAFgCAOQABAJgGALQgNAUgXAFQgEABgEgGQgIAPgVACQgZAPgagRQgGgDgBgEQABAFgCADQgGAJgMgBQgNAAgJgIQABADABADQACAGADAFQAGACAGACQAIADAHABQAFABAEACQADAAAEABQAJADAJABIgyBkIiiAAIhHhaQAFAAAHgCQABgBACAAQAIgDAIgEQAHgDAHgFQAGgEAFgGQAAgBAAgCQAAgDgBgDQgGAAgGACQgOAEgOAGQgUAHABgSQgVATgcgDQgfgEAHgUQgXAGgEgYQgFgbAVgHQgJgDgBgJQgDgQAHgQQALgXAYgJQgMgFADgMQAFgVAVgFQAJgCAEgHQgSgEgJgPQgKgSAIgVQAIgTASABQAEAAACACQgBgCAAgCQgCgDAAgEgABMAJQAAgGABgDQAAAAABgBQACgBABgCQABgCAAgDQAAgKgEgIQAAgBAAgBQAFABgBgGQAAgBAAgBQABgIgBgHQAAgCAAgCQAAgFgBgDQAAgDAAgBQABgBAAAAQABgEAAgDQgBgFgDgDQgEgEgEgEQgBgBgBgBQAAgBAAAAQgCgBgBgCQgEgIgGgFQgEgEgEgCQgCAAgBgCQgCgCgCgBIAAgBQgDgCgCgCQgBAAgBAAQgDAAgDABQgBAAgBABQgEABgCAAQAAgBgBAAQgBAAgBgCQAAgBgBAAQgDAAgBgCQgCgCgDABQgFACgCACQgBAAgBABQgDACgEgBQgDAAgDACQgBACgBABQgFAFgGABQgCABgBgBQgCgCgBgCQgBgBgBgBQAAAAgBAAQgCgBgBgBQgFgDgHABQgBAAgBABQgBAAAAAAQgBABgBAAQgHACgHgCQgBAAAAAAQgDAAAAACQgBABgBABQgBAAgBABQgDABgEAEQgBABgBAAQgCADgBADQAAACAAACQAAABAAABIAAAAQAAADgDAAQgBAAAAABQgDACgBACQAAABAAABIAAAAQgMADgGAJQgDAEgCAFQgDAHgCAHQgDAKAAAMIgBAAQgLgCgHALQgDAEgCAGQgFAMgBAOQgBATAKASQAJAPANAMQAOANAPAKQAEADADACQANAHAPACQAUADATgGQATgGANgLQACgDAEAAAAUhXQAFgCAGgCQADgBAEAAQAKAAAIAFQACABABACQADADACADAhMhdQACgDABgDQABgCACgBQAIgEAJAAQAFABAFACQACAAABABQADADAEACAiqiTQAAgBAAAAQgBgDgBgDAipiPQACACABADAishFQADgHgDgLAiCgfQAAABAAABQAAAGABAFAhDgLQAEgKAKAAQALAAAFAJAhqAFQAJgBAKgBQAKgCAFAGQABACABACQACADACACQACABADAAQABABABAAQAFgLALAHQAIAFAJACQAKADAKADAgMAoQgCACgBABQgHAHgHAFQgJAFgJADQgJAEgKAAQgJgBgJgDQgGgDgGgDQgCgCgCgCQgHgGgEgJQgEgIgBgKQgCgJAEgIIABAAQADABAEABQAEABAEABQAKACAJADQAGACAHACAgMAoQgCABgCABQgDABgCACQgJAEgJABQgKAAgKABQgJAAgJADQgJACgKABAhdBqQADAGACAGAhXB/QABAGAAAGQAAAHgBAHQAAADAAACABDBIQADAAAEgBQAKgDAHgHQAHgHAEgIQAEgJAAgJQAAgGgDgGQgBgDgCgDQgGgJgLAEQgEABgDADQgDADgCAEABIBwQgBgEgBgEQgCgKgBgJQAAgGAAgHQgGAAgFgCAg7ASQAIADAJACQAJADAJAAQAJABAJAAQgCAHgEAG");
	this.shape_19.setTransform(25,24.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#CC9A67").s().p("Ag9C8IhHhaQAFAAAHgCIADgBIAQgHIAOgIQAGgEAFgGIABAMIgBAOIAAAFIAAgFIABgOIgBgMIAAgDIgBgGQgCgGgDgGQANAHAPACIANABIAAAAIAAAAQANAAANgEQARgGAPgLQACgDAEAAQgEAAgCADQgPALgRAGQgNAEgNAAIAAAAIAAAAIgNgBQgPgCgNgHIgHgFQgPgKgOgNQgNgMgJgNQgKgSABgTQABgPAFgNIAFgKQAHgLALACIABAAQAAgLADgLIAFgOIAFgJQAGgJAMgDIAAAAIAAgCIAEgEIABgBQAAAAABAAQABAAAAAAQABgBAAAAQAAgBAAgBIAAAAIAAgCIAAgEQABgDACgDIACgBIAHgFIACgBIACgCQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAABAAIABAAQAHACAHgCIACgBIABAAIACgBQAHgBAFADIADACIABAAIACACIADAEQAAAAAAAAQAAABABAAQAAAAABAAQAAAAABgBQAGgBAFgFIACgDQADgCABAAQAEABADgCIADgBIAIgEQADgBACACQAAAAAAABQABAAAAABQABAAAAAAQABAAABAAIABABIACACIABABQACAAAEgBIACgBIAGgBIACAAIAFAEIAAABIAEADIADACQAEADAEADQAFAFAFAIIADADIAAABIACACIAIAIQADADABAFQAAAEgBADIgBABIAAAEIABAIIAAAEIAAAPIAAACQABAGgFgBIAAACQAEAIAAAKIgBAFIgDADIgBACQgBAEAAAGIAHgEQALgEAGAJIADAGQADAGAAAGQAAAJgEAJQgEAIgHAFQgHAHgKADIgHABIgBAAIgBAAIgDAAIgBgBIgEgBIgBAAIABAAIAEABIABABIADAAIABAAIABAAIAAANIADATIACAIIACAGIAFALIAMAEIAPAEIAJADIAHABIASAEIgyBkgAhng0QgEAIACAJQABAKAEAIQAEAJAHAGIAEACIAMAGQAJADAJABQAKAAAJgEQAJgDAJgDQAHgFAHgHIADgDIgDADIgBgBIAEgCQACgGACgHIgSgGQgJgCgIgFQgLgHgFALIgCgBIgFgBIgEgFIgCgEQgFgGgKACIgTACIgHgCgABSgnQACgEADgDQgDADgCAEgAgqhOQgKAAgEAKQAEgKAKAAIABAAIAAAAIAAAAIAAAAQAKABAEAHIABAAIAAABIAAgBIgBAAQgEgHgKgBIAAAAIAAAAIAAAAIgBAAgAh3hWQAAAGABAFQgBgFAAgGIAAgCIAAACIAAAAgABDiQIADADIAFAGIgFgGIgDgDQgIgFgKAAIgHABIgLAEIALgEIAHgBQAKAAAIAFgAg7ifIgDADIgDAGIADgGIADgDIABAAQAGgDAHgBIABAAIAAAAIABAAIABAAQAFABAFACIADABIAHAFIgHgFIgDgBQgFgCgFgBIgBAAIgBAAIAAAAIgBAAQgHABgGADIgBAAg");
	this.shape_20.setTransform(23.9,30.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#000000").ss(0.1,1,1).p("AgrgcQAJgBAKgBQAJgCAFAGQACACABACQACADACACQACAAABABQAAAAACABQAFgLAKAHQAIAFAKACQAJADALADAAxAEQgCACgCACQgGAHgIAFQgIAFgKADQgJAEgIAAQgJgBgIgDQgGgDgGgEQgCgBgCgCQgHgGgFgJQgEgGgBgKQgBgJAEgIIAAAAQAEABAEABQAEABAEABQAJACAJADQAHACAHACAAxAEQgCACgCABQgDABgDACQgIAEgKABQgJAAgKABQgIAAgJADQgJACgJAAAACgPQAIACAIADQAJADAJAAQAKABAJAAQgCAGgEAE");
	this.shape_21.setTransform(18.7,28);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f().s("#000000").ss(0.1,1,1).p("AAUAAQgOABgNAAQgJAAgJAAQAPAQAOgGQALgFAFgGgAgkABQAMgPAUADQAHACAHgCQADgBAEADQAKAGACADQABAAAAAAQAIAAAJAAAgkABQgFAAgFAAAgZABQgGAAgFAAAAdAAQgEAAgFAA");
	this.shape_22.setTransform(18.1,28.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f().s("#000000").ss(0.1,1,1).p("AgZgKQADgBADgBQAOgFANgFQAEgBAEgBQgMgEgGgDQgGAHgIgCQgFgBgFADQgHAHgDALQAFgCAGgCQARAOgBAUQADABAEABQAHAFAJABQADAAACgCQAHgHAFgJQgIAGgJADQgGADgGAAQgCAAgCAAAAkAJIABAAIgBAAgAAfAOQADgCACgDAAkAJQADgNgJgWQgGABgGABQgBAAgBAAAACAaQgGgWAXAAQAKgBAHAG");
	this.shape_23.setTransform(18.7,28.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#B5783E").s().p("AARAgQgJgBgIgFIAFAAQAGAAAGgDQAJgDAIgGQgFAJgHAHIgEACIgBAAgAgXgYQAFgDAFABQAIACAFgHIATAHIgIACIgbAKIgGACIgLAEQADgLAHgHg");
	this.shape_24.setTransform(18.4,28.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FF0000").s().p("AAAgKQAKAAAIAFIAAABIgGAEQgIAEgHAEQgGACgGABQgIgUAXgBg");
	this.shape_25.setTransform(20.5,30.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgIAaIgHgCQABgUgQgOIAGgCIAagJIAIgCIADgBIAMgCQAJAWgDANQgIgFgKAAQgXABAIAVIgBABIgFgBg");
	this.shape_26.setTransform(19.2,28.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f().s("#000000").ss(0.1,1,1).p("AAZADQgFgFgGgGQgHgGgHAAQgFgCgFgEQgEgDgFAKQABAAABABQAEAAAGACQAQAFAQAIgAgWADQAAABAAAAQgBABAAAAQABADABACQAAABABABQADAEAFAAQALABAIgDQgHAGgHABQgJADgGgIQgBgBgBgCQAAgCADgBAgWADQAAABgBAAQAAABAAAAAAHAOQACgBACgBQgPgMgSADAgRgMQgBAJgEAGAALAMQAGgDAIgGIAAAA");
	this.shape_27.setTransform(18.6,28.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#B5783E").s().p("AgWAQIgCgDIADgDIABACQADAEAGAAQAKABAIgDQgHAGgHABIgDABQgHAAgFgGgAgHgKIgKgCIgCgBQAFgKAFADQAEAEAFACQAHAAAHAGQAHAGAEAFQgQgIgQgFg");
	this.shape_28.setTransform(18.6,28.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FF0000").s().p("AgFAGQgFAAgDgEIgCgCIgBgCIAAgCIABAAQAQgEARAKIgEACQgIACgHAAIgEAAgAgQgCIAAgCIABAAIgBAAIAAACIAAAAg");
	this.shape_29.setTransform(17.9,29);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgXAEQAEgGABgKIAKADQAQAFAQAIIAAAAQgIAGgGADQgPgNgSAEg");
	this.shape_30.setTransform(18.7,28);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f().s("#000000").ss(0.1,1,1).p("AgbgKQAFgDAGgCQAQgHASAHQACABADACQgBgHgDgCQgJgGgKgDQgFgDgFAEQgFAEgFADQgEACgEgCQgGAHgCAJQAEgCAFgCQAPAKgFASQAAAAABABQAEAJAJADQAIADAJgFQAFgDACgFQgFADgIABQgDAAgCAAAgQATQAJAGAKAAQgDgPAAgFQAAgVAcAHQgDgCgCgBAAVAVQAMgHAEgPQgDgFgGgD");
	this.shape_31.setTransform(18.1,28.8);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#B5783E").s().p("AACAfQgHgDgEgJQAJAGAKAAIAFAAQAIgBAFgDQgCAFgFADQgGADgFAAIgIgBgAgVgWQAEACAEgCIAKgHQADgEAHADQAKADAJAGQADACABAHIgFgDQgSgHgQAHIgLAFIgJAEQACgJAGgHg");
	this.shape_32.setTransform(17.3,28.8);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FF0000").s().p("AgNASQgFgPAAgDQAAgWAcAGQAGAEADAEQgEAQgLAGQgEAEgIAAIgEAAIgBAAg");
	this.shape_33.setTransform(19.8,29.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgQAQIgBgBQAFgRgPgLIALgEQAQgIASAIIAFACIAFADQgcgHAAAVQAAAFADAPIAAAAQgKAAgJgGg");
	this.shape_34.setTransform(18,29.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f().s("#000000").ss(0.1,1,1).p("AgSABQAFAEAFACAgPgZQgHAPgDAJQADABAEABAAfgIQgBgBgBgBQgGgEgHgEQgQgJgPACQgBAAAAAAQABgEADgFQAFgKAIAJQAKgEAIAHQAFAGAFAGQACAGAAAGQABALgGANQgEALgIAJQgBAAgBAAQgBAAgBAAQgBAAAAAAQgGgCgEgDQgMgHgOgEAAKAkQgJAFgIAAQgGAAgFgGQgHgHgFgJQACAAABABQADgMAGgH");
	this.shape_35.setTransform(18.3,29.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#B5783E").s().p("AgSAjQgHgHgFgJIADABQAOAEAMAHQAEADAGACIABAAQgJAFgIAAQgGAAgFgGgAAdgKIgNgIQgQgJgPACIgBAAIAEgJQAFgKAIAJQAKgEAIAHIAKAMIACAMIgCgCg");
	this.shape_36.setTransform(18.3,29.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AALAfIgCAAIgCAAQgGgCgDgDQgNgHgNgEQADgMAFgFIALAEIgLgEIgGgEQADgJAHgPQAQgBAPAIIANAIIABACQABANgFALQgFALgHAJIgBAAIgBAAg");
	this.shape_37.setTransform(18.5,29.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9}]}).to({state:[{t:this.shape_13},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15}]},3).to({state:[{t:this.shape_13},{t:this.shape_20},{t:this.shape_10},{t:this.shape_11},{t:this.shape_19}]},2).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_21}]},2).to({state:[{t:this.shape_17},{t:this.shape_22}]},3).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_21}]},2).to({state:[{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23}]},2).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27}]},2).to({state:[{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31}]},2).to({state:[{t:this.shape_37},{t:this.shape_36},{t:this.shape_35}]},2).wait(3));

	// eyes
	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f().s("#000000").ss(0.1,1,1).p("AisiaQgDgMAIgLQALgRATgCQAEgBAEABQADgMAMgIQAPgMATgCQATgDAHASQABAEACACQgDgSARgKQAPgKARAEQANADANAGQAQAIADARQAJgKAMgFQARgIAQAIQAPAIAEASQADAQgEAQQAJgDAKAAQAMABAJAHQAIAGgCAKQgFATAUAHQAUAHgEATQgBALgKAFQAKADALAAQAQABAMAMQAJAJgEANQgGARgNAIQALAAAKADQAKADABAJQABAUgNANQAGABAEACQAIAFgCAOQABAJgGALQgNAUgXAFQgEABgEgGQgIAPgVACQgZAPgagRQgGgDgBgEQABAFgCADQgGAJgMgBQgNAAgJgIQABADABADQACAGADAFQAGACAGACQAIADAHABQAFABAEACQADAAAEABQAJADAJABIgyBkIiiAAIhHhaQAFAAAHgCQABgBACAAQAIgDAIgEQAHgDAHgFQAGgEAFgGQAAgBAAgCQAAgDgBgDQgGAAgGACQgOAEgOAGQgUAHABgSQgVATgcgDQgfgEAHgUQgXAGgEgYQgFgbAVgHQgJgDgBgJQgDgQAHgQQALgXAYgJQgMgFADgMQAFgVAVgFQAJgCAEgHQgSgEgJgPQgKgSAIgVQAIgTASABQAEAAACACQgBgCAAgCQgCgDAAgEgABMAJQAAgGABgDQAAAAABgBQACgBABgCQABgCAAgDQAAgKgEgIQAAgBAAgBQAFABgBgGQAAgBAAgBQABgIgBgHQAAgCAAgCQAAgFgBgDQAAgDAAgBQABgBAAAAQABgEAAgDQgBgFgDgDQgEgEgEgEQgBgBgBgBQAAgBAAAAQgCgBgBgCQgEgIgGgFQgEgEgEgCQgCAAgBgCQgCgCgCgBIAAgBQgDgCgCgCQgBAAgBAAQgDAAgDABQgBAAgBABQgEABgCAAQAAgBgBAAQgBAAgBgCQAAgBgBAAQgDAAgBgCQgCgCgDABQgFACgCACQgBAAgBABQgDACgEgBQgDAAgDACQgBACgBABQgFAFgGABQgCABgBgBQgCgCgBgCQgBgBgBgBQAAAAgBAAQgCgBgBgBQgFgDgHABQgBAAgBABQgBAAAAAAQgBABgBAAQgHACgHgCQgBAAAAAAQgDAAAAACQgBABgBABQgBAAgBABQgDABgEAEQgBABgBAAQgCADgBADQAAACAAACQAAABAAABIAAAAQAAADgDAAQgBAAAAABQgDACgBACQAAABAAABIAAAAQgMADgGAJQgDAEgCAFQgDAHgCAHQgDAKAAAMIgBAAQgLgCgHALQgDAEgCAGQgFAMgBAOQgBATAKASQAJAPANAMQAOANAPAKQAEADADACQANAHAPACQAUADATgGQATgGANgLQACgDAEAAAAUhXQAFgCAGgCQADgBAEAAQAKAAAIAFQACABABACQADADACADAhMhdQACgDABgDQABgCACgBQAIgEAJAAQAFABAFACQACAAABABQADADAEACAiqiTQAAgBAAAAQgBgDgBgDAipiPQACACABADAishFQADgHgDgLAiCgfQAAABAAABQAAAGABAFAhDgLQAEgKAKAAQALAAAFAJAhdBqQADAGACAGAhXB/QABAGAAAGQAAAHgBAHQAAADAAACABDBIQADAAAEgBQAKgDAHgHQAHgHAEgIQAEgJAAgJQAAgGgDgGQgBgDgCgDQgGgJgLAEQgEABgDADQgDADgCAEABIBwQgBgEgBgEQgCgKgBgJQAAgGAAgHQgGAAgFgC");
	this.shape_38.setTransform(25,24.5);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#CC9A67").s().p("Ag9C8IhHhaQAFAAAHgCIADgBIAQgHIAOgIQAGgEAFgGIABAMIgBAOIAAAFIAAgFIABgOIgBgMIAAgDIgBgGQgCgGgDgGQANAHAPACIANABIAAAAIAAAAQANAAANgEQARgGAPgLQACgDAEAAQgEAAgCADQgPALgRAGQgNAEgNAAIAAAAIAAAAIgNgBQgPgCgNgHIgHgFQgPgKgOgNQgNgMgJgNQgKgSABgTQABgPAFgNIAFgKQAHgLALACIABAAQAAgLADgLIAFgOIAFgJQAGgJAMgDIAAAAIAAgCIAEgEIABgBQAAAAABAAQABAAAAAAQABgBAAAAQAAgBAAgBIAAAAIAAgCIAAgEQABgDACgDIACgBIAHgFIACgBIACgCQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAABAAIABAAQAHACAHgCIACgBIABAAIACgBQAHgBAFADIADACIABAAIACACIADAEQAAAAAAAAQAAABABAAQAAAAABAAQAAAAABgBQAGgBAFgFIACgDQADgCABAAQAEABADgCIADgBIAIgEQADgBACACQAAAAAAABQABAAAAABQABAAAAAAQABAAABAAIABABIACACIABABQACAAAEgBIACgBIAGgBIACAAIAFAEIAAABIAEADIADACQAEADAEADQAFAFAFAIIADADIAAABIACACIAIAIQADADABAFQAAAEgBADIgBABIAAAEIABAIIAAAEIAAAPIAAACQABAGgFgBIAAACQAEAIAAAKIgBAFIgDADIgBACQgBAEAAAGIAHgEQALgEAGAJIADAGQADAGAAAGQAAAJgEAJQgEAIgHAFQgHAHgKADIgHABIgBAAIgBAAIgDAAIgBgBIgEgBIgBAAIABAAIAEABIABABIADAAIABAAIABAAIAAANIADATIACAIIACAGIAFALIAMAEIAPAEIAJADIAHABIASAEIgyBkgABSgnQACgEADgDQgDADgCAEgAgqhOQgKAAgEAKQAEgKAKAAIABAAIAAAAIAAAAIAAAAQAKABAEAHIABAAIAAABIAAgBIgBAAQgEgHgKgBIAAAAIAAAAIAAAAIgBAAgAh3hWQAAAGABAFQgBgFAAgGIAAgCIAAACIAAAAgABDiQIADADIAFAGIgFgGIgDgDQgIgFgKAAIgHABIgLAEIALgEIAHgBQAKAAAIAFgAg7ifIgDADIgDAGIADgGIADgDIABAAQAGgDAHgBIABAAIAAAAIABAAIABAAQAFABAFACIADABIAHAFIgHgFIgDgBQgFgCgFgBIgBAAIgBAAIAAAAIgBAAQgHABgGADIgBAAg");
	this.shape_39.setTransform(23.9,30.2);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#271B0E").s().p("AjEC+QgfgEAHgUQgXAGgEgYQgFgbAVgHQgJgDgBgJQgDgQAHgQQALgZAYgJQgMgFADgMQAFgTAVgFQAJgDAEgGQgSgEgJgPQgKgSAIgVQAIgTASABQAEAAACACIgBgEIAAgBIgCgGQgDgMAIgLQALgRATgCQAEgBAEABQADgMAMgIQAPgMATgCQATgDAHASIADAGQgDgSARgKQAPgKARAEQANADANAGQAQAIADARQAJgKAMgFQARgIAQAIQAPAIAEASQADAQgEAQQAJgDAKAAQAMABAJAHQAIAGgCAKQgFATAUAHQAUAHgEATQgBALgKAFQAKADALAAQAQABAMAMQAJAHgEANQgGARgNAIQALAAAKADQAKADABALQABATgNAOQAGAAAEADQAIAFgCANQABAKgGALQgNAUgXAFQgEABgEgGQgIAPgVACQgZAPgagRQgGgEgBgDQABAFgCADQgGAJgMgBQgNgBgJgHIgCgIIgDgTIAAgNIAHgBQAKgDAHgHQAHgHAEgIQAEgJAAgJQAAgHgDgFIgDgGQgGgJgLAEIgHADQAAgFABgEIABgCIADgDIABgFQAAgKgEgIIAAgCQAFABgBgGIAAgCIAAgPIAAgCIgBgIIAAgEIABgCQABgDAAgDQgBgFgDgDIgIgIIgCgCIAAgBIgDgDQgEgIgGgFQgEgEgEgCIgDgCIgEgEIAAAAIgFgEIgCAAIgGABIgCABQgEABgCgBIgBAAIgCgCIgBgBQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAAAQgCgCgDABIgHADIgCACQgDACgEgBQgDAAgDACIgCADQgFAFgGABQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAAAAAAAIgDgEIgCgCIgBAAIgDgCQgFgDgHABIgCAAIgBABIgCABQgHACgHgCIgBAAQgBAAAAAAQgBAAAAAAQgBAAAAABQAAAAAAABIgCACIgCABIgHAFIgCABQgCADgBADIAAAEIAAACIAAAAQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIgBABIgEAEIAAACIAAAAQgMADgGAJIgFAJIgFAMQgDAKAAAMIgBAAQgLgDgHALIgFALQgFANgBAPQgBATAKASQAJAPANAMQAOANAPAKIAHAFQADAFACAHQgGAAgGACIgcAKQgUAHABgSQgSAQgXAAIgIAAgAisgOQABgEAAgEIgBgKIABAKQAAAEgBAEgAimhTQgBgDgCgCQACACABADg");
	this.shape_40.setTransform(25,19);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38}]},7).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38}]},3).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38}]},2).wait(11));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,52,51.1);


(lib.object_buffy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{talk:0});

	// timeline functions:
	this.frame_22 = function() {
		this.gotoAndPlay("talk");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(22).call(this.frame_22).wait(1));

	// Layer 1
	this.instance = new lib.anim_buffy_talk();
	this.instance.setTransform(24.9,24.5,1,1,0,0,0,24.9,24.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(23));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,50.1,49.2);


(lib.intro = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_8 = function() {
		playSound("flying");
	}
	this.frame_14 = function() {
		playSound("auxillaryverbs_female");
	}
	this.frame_19 = function() {
		playSound("bump");
	}
	this.frame_40 = function() {
		playSound("quick_pad_chord");
	}
	this.frame_47 = function() {
		playSound("auxillaryverbsarehelpingverbsthatmakeup");
	}
	this.frame_104 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(8).call(this.frame_8).wait(6).call(this.frame_14).wait(5).call(this.frame_19).wait(21).call(this.frame_40).wait(7).call(this.frame_47).wait(57).call(this.frame_104).wait(1));

	// Layer 3
	this.instance = new lib.Tween1("synched",0);
	this.instance.setTransform(-272.6,-80.2,1,1,0,0,0,162.2,0);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({_off:false},0).to({regX:159.7,x:171.1},9).to({regX:161,scaleX:0.52,scaleY:2.04,x:172.3},3).to({regX:160.9,scaleX:1,scaleY:1},3).to({startPosition:0},6).to({y:-112.7},4).wait(71));

	// Layer 8
	this.instance_1 = new lib.Tween3("synched",0);
	this.instance_1.setTransform(8.1,-68.9,0.187,0.187);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(39).to({_off:false},0).to({scaleX:1,scaleY:1},8).wait(58));

	// buffy face
	this.instance_2 = new lib.object_buffy();
	this.instance_2.setTransform(16.2,80.2,0.424,0.424,0,0,0,25,24.4);

	this.instance_3 = new lib.BuffyStill();
	this.instance_3.setTransform(18.4,55.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2}]}).to({state:[{t:this.instance_2}]},9).to({state:[{t:this.instance_2},{t:this.instance_3}]},1).to({state:[{t:this.instance_2}]},5).to({state:[{t:this.instance_2},{t:this.instance_3}]},16).to({state:[{t:this.instance_2}]},15).to({state:[{t:this.instance_3}]},51).wait(8));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({regX:24.9,regY:24.5,scaleX:2.37,scaleY:2.37,x:18,y:55.1},9).wait(37).to({_off:true},51).wait(8));

	// Layer 1
	this.instance_4 = new lib.static_buffy_activebuble("synched",0);
	this.instance_4.setTransform(15.8,80.5,0.424,0.424,0,0,0,38.5,38.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({scaleX:2.37,scaleY:2.37,y:56.4},9).wait(96));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.6,63.1,34.7,34.7);


(lib.goNext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_1 = function() {
		playSound("clickwav");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(1).call(this.frame_1).wait(3));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,11.3).s().p("AhLAqQghgSACgYQgCgXAhgRQAggTArAAQAsAAAgATQAfARAAAXQAAAYgfASQggASgsAAQgrAAgggSg");
	this.shape.setTransform(22.8,8.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.502)").s().p("AhThcICoBdIioBcg");
	this.shape_1.setTransform(25.1,20.4);

	this.blinker = new lib.general_buttoncolor();
	this.blinker.setTransform(23.4,20.1,1.5,1.5,0,0,0,11.9,11.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,14.8).s().p("AhiA3QgrgXACggQgCgfArgWQApgYA5AAQA5AAAqAYQAqAWAAAfQAAAggqAXQgqAXg5AAQg5AAgpgXg");
	this.shape_2.setTransform(23.4,8.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("rgba(0,0,0,0.502)").ss(1,1,1,3,true).p("AAACxQhIAAg0g0Qg0g1AAhIQAAhHA0g1QA0g0BIAAQBJAAA0A0QA0A1AABHQAABIg0A1Qg0A0hJAAg");
	this.shape_3.setTransform(23.3,20.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["rgba(103,103,103,0.839)","rgba(134,134,134,0)"],[0.678,0.918],-0.8,0,0,-0.8,0,24.9).s().p("AisCkQhFhEAAhgQAAhgBFhDQBEhFBhAAQBfAABBAwQBCAwAVCqQAVCskMAbQhhAAhEhFgAgHCQQBEAAAzgwIABAAIADgEQA0g0AAhHQAAhJg0g0IgFgFIgBgBQgyguhDAAIAAAAIgBAAIAAAAIgBAAQhEAAgyAuIgBABIgCACIgBABIAAAAIgCACQg0A0AABJQAABHA0A0IACACIABABQAzAxBHAAIAAAAIAAAAIAAAAIAAAAQhHAAgzgxIgBgBIgCgCQg0g0AAhHQAAhJA0g0IACgCIAAAAIABgBIACgCIABgBQAyguBEAAIABAAIAAAAIABAAIAAAAQBDAAAyAuIABABIAFAFQA0A0AABJQAABHg0A0IgDAEIgBAAQgzAwhEAAIAAAAIgBAAIABAAIAAAAg");
	this.shape_4.setTransform(24.2,23.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},2).wait(1));

	// Layer 2
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#33FFFF").s().p("AioCqQhGhHAAhjQAAhiBGhGQBGhHBiAAQBjAABGBHQBHBGgBBiQABBjhHBHQhGBGhjAAQhiAAhGhGg");
	this.shape_5.setTransform(24.4,21.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0099FF").s().p("AioCqQhGhHAAhjQAAhiBGhGQBGhHBiAAQBjAABGBHQBHBGgBBiQABBjhHBHQhGBGhjAAQhiAAhGhGg");
	this.shape_6.setTransform(24.4,21.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.5,46.7);


(lib.blank = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.blank_gr("synched",0);
	this.instance.setTransform(32.6,17,1,1,0,0,0,32.5,17);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,0,65,34);


// stage content:
(lib.aux_scene0 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{scene0:0,scene0repeat:110});

	// timeline functions:
	this.frame_0 = function() {
		playSound("BeautifulDrumnbass",-1);
		this.btn_menu.addEventListener("click", openMenu.bind(this));
		this.btn_goNext.addEventListener("click", openNext.bind(this));
		this.btn_goBack.addEventListener("click", openPrev.bind(this));
		
		function openMenu(){
		
		 window.open ("verb_menu.html","_self");
		}
		
		function openNext(){
		
		 window.open ("aux_scene1.html","_self");
		}
		
		function openPrev(){
		
		 window.open ("puzzle_aux.html","_self");
		}
	}
	this.frame_126 = function() {
		this.gotoAndPlay("scene0repeat");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(126).call(this.frame_126).wait(1));

	// Layer 2
	this.instance = new lib.intro();
	this.instance.setTransform(261.5,175.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(127));

	// main
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AgzA/QgNgJAAgMQAAgGAFgEQADgEAHAAQAJAAADAJQAGAMATAAQAPAAARgIQAQgHAAgJQAAgMgLgEQgHgDgUgBQgRAAgNgFQgSgHABgPQAAgTATgQQAVgQAWAAQAJAAAPAEQARAGAAAHQAAAFgEAEQgDAEgHAAIgNgCIgOgCQgNABgJAGQgMAGAAAHQAAADAEADQADACAIABIAWACQAWABAMALQAOAJABAVQgBAZgcANQgWAKgaAAQgZAAgOgLg");
	this.shape.setTransform(208.9,25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AgvBKQgFgFAAgGIAAhlIAAgOIAAgMQACgJAQgCQAHgDARAAQARAAAQANQAUANAAAVQAAAMgEAHQgDAHgIAFQAJAEAIAKQAIAJAAALQAAANgOAMQgKAHgKAEQgVAJgiAAQgGgBgFgEgAgZA0QARgBARgGQASgEgBgGQAAgIgLgFQgIgFgHgBIgZAAgAgZgeIAAAVIANAAQAcgCAAgUQAAgHgJgGQgHgHgKAAIgPAAg");
	this.shape_1.setTransform(196,24.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF0000").s().p("Ag0BIQgEgEAAgFIAAgWIABgWIAAhNQAAgGADgFQAFgHAJABIAYACQAOABAIAFQAqAVAAAfQgBANgIAIQgJAKgRAGQAaAPANAPQADAEAAAFQAAAFgEAEQgEAEgGAAQgFAAgEgEQgegcghgLIABAgQAAAFgFAEQgDAEgHAAQgFAAgEgEgAgdACIAEAAQAYAAAKgEQAEgCAFgEQAEgFAAgCQAAgLgOgKQgLgJgOgCIgMgBg");
	this.shape_2.setTransform(183.2,24.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF0000").s().p("AgsBKQgLgJAAggIACglIACgoIgBgKIgBgKQAAgPANAAQAFAAADADIAWgFIASgBQAYABAPAFQAJADAAAJQAAAFgDAEQgEAFgGAAIgFgBQgPgEgPAAIgPABIgRADIgBAnIAkgEIAYgCQAGAAAEAFQADADAAAGQAAAKgMABIgXACIgoAEIAAAUQgBATADADQABABALAAIAQAAIASgBIAGAAIAGgBQAFAAAFAEQAEADAAAHQAAALgLACQgKABgcAAQghABgJgJg");
	this.shape_3.setTransform(170.6,24.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF0000").s().p("AgUBFQgMgcgOg0IgJgaQgFgTAAgHQAAgGAEgDQAEgEAGAAQAJAAAEAJIAEARIAJAgIAPAvIAVg4IAIgYQAGgOAGgHQAFgGAGAAQAGAAAEAFQAEAEAAAFQAAAEgCAEQgFAHgFALIgHAUIgbBBQgEAMgGAMQgFAHgGABQgKgBgEgJg");
	this.shape_4.setTransform(157.4,24.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF0000").s().p("AgWBKQgFgEAAgGQAAgFAVgjIgWgfIgfgxQgCgDAAgEQAAgGAFgEQAEgDAFAAQAHAAAFAGIAHAMIARAcIAQAcIAVgtIAJgUQAEgJAJAAQAFAAAEADQAFAEAAAGQAAADgGAMIgUAsQgMAbgJAQIgPAeQgFAIgIAAQgFAAgEgDg");
	this.shape_5.setTransform(135.3,24.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF0000").s().p("Ag0BIQgEgEAAgFIAAgWIAAgWIAAhNQAAgGAFgFQAEgHAJABIAYACQAOABAIAFQAqAVgBAfQABANgKAIQgIAKgSAGQAbAPANAPQADAEAAAFQAAAFgEAEQgFAEgFAAQgFAAgFgEQgdgcgigLIABAgQAAAFgDAEQgEAEgGAAQgGAAgEgEgAgdACIAEAAQAYAAAKgEQAFgCAEgEQAEgFAAgCQAAgLgOgKQgLgJgOgCIgMgBg");
	this.shape_6.setTransform(123,24.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF0000").s().p("AAhA3QgEgMgFgPQgHACgQABIgWACIgPAgQgEAHgIAAQgFAAgFgDQgEgEAAgFQAAgFAOgdIgBgGQAAgFAJgCIAfgwQAWglAHAAQAKAAADANIAHAfIAPA/IAEAMQAEAJAAAEQAAAGgFAEQgDADgGAAQgHAAgJgSgAgGAJIALgCIAOgBIgGgfIgTAig");
	this.shape_7.setTransform(109,24.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF0000").s().p("AgtBGQgEgDAAgGQAAgFAEgEQAEgEAHAAIASgCIAAgsQAAgYACgYIgVAAQgGAAgEgEQgEgEAAgFQAAgGAEgEQADgDAGAAIAcgBQARAAAdAEQAMACAAALQAAAHgFADQgDADgFAAIgagCIgBAtIAAAsIAaAAQAGAAAEAEQAEAEAAAFQAAAGgEAEQgEADgGAAIgRABIgQAAIgSACIgUABQgGAAgEgEg");
	this.shape_8.setTransform(96.1,24.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF0000").s().p("AgzA6IACgfQADgoAAg0QAAgGAEgDQADgEAGAAQAGAAAEAEQAEADAAAGQAAA0gDAqIgCAYQAYgBAigKIAEgBQAGAAAEAEQAEAEAAAFQAAAJgJAEQgMAFgYAEQgUADgOAAQgYAAAAgVg");
	this.shape_9.setTransform(85.6,24.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF0000").s().p("AgtBGQgEgDAAgGQAAgFAEgEQAEgEAHAAIASgCIAAgsQAAgYACgYIgVAAQgGAAgEgEQgEgEAAgFQAAgGAEgEQADgDAGAAIAcgBQARAAAdAEQAMACAAALQAAAHgFADQgDADgFAAIgagCIgBAtIAAAsIAaAAQAGAAAEAEQAEAEAAAFQAAAGgEAEQgEADgGAAIgRABIgQAAIgSACIgUABQgGAAgEgEg");
	this.shape_10.setTransform(74.2,24.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FF0000").s().p("AAcA4IgNgTIgMgRIgdAhIgSATQgEAEgGAAQgFAAgEgDQgFgEAAgGQAAgFAEgDIASgTIAigkIgVgZIgLgPQgHgIgFgFQgGgEAAgGQAAgFAEgFQAEgEAGAAQAFAAAJAIQAGAFAEAGIAMAPIAQAWIAZggQATgYAHAAQAGAAAEAEQAEAEAAAGQAAAEgEAEIgUAZIgXAeIAUAcIAWAcQADAEAAAEQAAAGgEAEQgEAEgGAAQgJAAgQgWg");
	this.shape_11.setTransform(61.4,24.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FF0000").s().p("AgmBCQgagUAAgvIABgOIAAgOIABgLIAAgLQAAgIADgGQADgKAHABQAGAAAEACQAEAEAAAGIAAARIAAAQIgBAOIAAAOQAAANADAMQAFAQAHAFQAFAEAPAAQAYABAJgtQAEgVAAgpQAAgGAEgFQAEgGAIAAQAHgBADAFQADAEAAAEQAAAngEAWQgFAegRAWQgHAKgKAHQgMAHgLABQgZAAgMgKg");
	this.shape_12.setTransform(46.9,25);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FF0000").s().p("AAiA3QgGgMgDgPQgHACgRABIgWACIgPAgQgFAHgHAAQgGAAgEgDQgEgEAAgFQAAgFAOgdIgBgGQABgFAIgCQAOgWASgaQAVglAHAAQAKAAAEANIAGAfIAPA/IAEAMQAEAJAAAEQAAAGgFAEQgEADgFAAQgIAAgHgSgAgGAJIALgCIAOgBIgHgfIgSAig");
	this.shape_13.setTransform(32.2,24.8);

	this.instance_1 = new lib.Bk("synched",0);
	this.instance_1.setTransform(275,194.2);

	this.btn_menu = new lib.skiptomenu();
	this.btn_menu.setTransform(514.1,20.3);
	new cjs.ButtonHelper(this.btn_menu, 0, 1, 2, false, new lib.skiptomenu(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.btn_menu},{t:this.instance_1},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(127));

	// button
	this.instance_2 = new lib.Copyright("synched",0);
	this.instance_2.setTransform(275,393.5);

	this.btn_goBack = new lib.goNext();
	this.btn_goBack.setTransform(57.6,352.3,1,1,0,0,180);
	new cjs.ButtonHelper(this.btn_goBack, 0, 1, 2, false, new lib.goNext(), 3);

	this.btn_goNext = new lib.goNext();
	this.btn_goNext.setTransform(494,352.3);
	new cjs.ButtonHelper(this.btn_goNext, 0, 1, 2, false, new lib.goNext(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.btn_goNext},{t:this.btn_goBack},{t:this.instance_2}]}).wait(127));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(284.2,201.8,537.1,401.2);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;