(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.vol_pos = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.5,1,1).p("ABagwIAABgQAAAWgZAAIiBAAQgZAAAAgWIAAhgQAAgVAZAAICBAAQAZAAAAAVg");
	this.shape.setTransform(9,7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgKA0QgDgDAAgGIAAgfIgFABIgTAAQgVAAAAgNQAAgHAHgDQADAAALAAIAYgBIAAgQIABgRQABgFADgDQADgCAEAAQAFAAADADQAEAEgBAFIAAAHIgBAIIABAPIAAAAIAKABIAIAAIAHgBIABAAIAJABQAKABADAGIABAEIgBAFIgDADIgDADIgFABIgEgBIgCAAIgEAAIgNAAIgOAAIAAAgQAAAMgLAAQgGAAgDgDg");
	this.shape_1.setTransform(9.6,6.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00CCFF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICBAAQAYAAABAWIAABfQgBAWgYAAgAgHAqQAAAGADADQAEADAEAAQAMAAABgMIAAggIANAAIAOAAIADAAIACAAIAFABIAFgBIADgDIACgDIABgFIgBgEQgCgGgKgBIgJgBIgBAAIgHABIgIAAIgKgBIAAAAIgBgPIABgIIAAgHQAAgFgEgEQgDgDgGAAQgEAAgBACQgEADgBAFIgBARIAAAQIgYABQgKAAgDAAQgHADgBAIQABAMAUAAIATAAIAFgBg");
	this.shape_2.setTransform(9,7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0099FF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICBAAQAYAAABAWIAABfQgBAWgYAAgAgHAqQAAAGADADQAEADAEAAQAMAAABgMIAAggIANAAIAOAAIADAAIACAAIAFABIAFgBIADgDIACgDIABgFIgBgEQgCgGgKgBIgJgBIgBAAIgHABIgIAAIgKgBIAAAAIgBgPIABgIIAAgHQAAgFgEgEQgDgDgGAAQgEAAgBACQgEADgBAFIgBARIAAAQIgYABQgKAAgDAAQgHADgBAIQABAMAUAAIATAAIAFgBg");
	this.shape_3.setTransform(9,7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_1},{t:this.shape_2},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape_3},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,19.9,16);


(lib.vol_neg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.5,1,1).p("AhAhFICBAAQAZAAAAAVIAABgQAAAWgZAAIiBAAQgZAAAAgWIAAhgQAAgVAZAAg");
	this.shape.setTransform(9,7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgMALIgCAAIgPAAQgLAAAAgKQAAgJALAAIAdgBIAdgBIAEABQAIAAAAAJQAAAIgKABIgVABIgJABIgNAAg");
	this.shape_1.setTransform(9.1,6.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICAAAQAaAAAAAWIAABfQAAAWgaAAgAABgLIgdAAQgLAAAAAKQAAAJALAAIAPAAIACAAIANAAIAJAAIAVgBQAKgBAAgIQAAgJgIAAIgEgBIgdABg");
	this.shape_2.setTransform(9,7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00CCFF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICAAAQAaAAAAAWIAABfQAAAWgaAAgAABgLIgdAAQgLAAAAAKQAAAJALAAIAPAAIACAAIANAAIAJAAIAVgBQAKgBAAgIQAAgJgIAAIgEgBIgdABg");
	this.shape_3.setTransform(9,7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0099FF").s().p("AhABGQgZAAAAgWIAAhfQAAgWAZAAICAAAQAaAAAAAWIAABfQAAAWgaAAgAABgLIgdAAQgLAAAAAKQAAAJALAAIAPAAIACAAIANAAIAJAAIAVgBQAKgBAAgIQAAgJgIAAIgEgBIgdABg");
	this.shape_4.setTransform(9,7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_1},{t:this.shape_3},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape_4},{t:this.shape}]},1).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,19.9,16);


(lib.vol_mute = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AASBRQAAgIgQgQQgMgNgHAAIAAhZQAHAAANgOQAPgOAAgHg");
	this.shape.setTransform(15.6,13.9,1.2,1.201);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AgGglIANAAQABAAAAABIAABJQAAABgBAAIgNAAQgBAAAAgBIAAhJQAAgBABAAg");
	this.shape_1.setTransform(10.5,13.8,1.2,1.201);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#990000").ss(1,1,1).p("AhHBRQgCgDgDgCQgDgDgBgCQgbgeAAgpQAAgsAfgfQAgggAsAAQAjAAAcAUQAGAEAHAIQACACADACQAbAeAAApQAAAtggAfQgfAggtAAQgpAAgegbICYiY");
	this.shape_2.setTransform(15.1,14.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1,1,1).p("AAJAAQAAANgJAJQgCAFgGACIAAg5QAGADACAFQAJAIAAAMg");
	this.shape_3.setTransform(20.6,13.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1.5,1,1).p("ACWAAQAAA7gsAoQgtAqg9AAQg+AAgsgqQgrgoAAg7QAAg6ArgqQAKgIAKgHQAFgDAGgDQAJgFAKgEQAEgBAFgCQAWgHAZAAQAaAAAXAHQAEACAEABQAKAEAJAFQAFADAFADQAKAHAKAIQAsAqAAA6g");
	this.shape_4.setTransform(15,14.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAAABtQAuAAAfggQAfggAAgsQAAgpgbgeIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfQgfAgAAAsQAAApAaAeIAFAFIAFAFQAeAbAoAAgAhGBSICXiYQAbAeAAApQAAAsgfAgQgfAgguAAQgoAAgegbgAAuAaQAHgCACgGQAJgJAAgMQAAgMgJgJQgCgFgHgDIAAA6IAAAAgAhGBSIAAAAgAhLBNIgFgFQgageAAgpQAAgsAfggQAggfArAAQAkAAAbAUQAHAEAHAHIAEAFIiXCYIgFgFgAAuAagAAuggQAHADACAFQAJAJAAAMQAAAMgJAJQgCAGgHACgABAgDIAAAAgABRhGIAAAAg");
	this.shape_5.setTransform(15,14.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#00CCFF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAhLhLQgfAgAAAsQAAApAaAeIAFAFIAFAFQAeAbAoAAQAuAAAfggQAfggAAgsQAAgpgbgeIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfg");
	this.shape_6.setTransform(15,14.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhHBRICYiYQAbAeAAApQAAAtggAfQgfAggtAAQgpAAgegbgAAuAZQAGgCADgGQAJgIAAgMQAAgNgJgJQgDgFgGgDIAAA6IAAAAgAhMBMIgEgFQgbgeAAgpQAAgsAfgfQAgggAsAAQAjAAAcAUQAGAEAHAIIAFAEIiYCYIgFgFgAAuAZgAAughQAGADADAFQAJAJAAANQAAAMgJAIQgDAGgGACgABAgDIAAAAg");
	this.shape_7.setTransform(15.1,14.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0099FF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAhLhLQgfAgAAAsQAAApAaAeIAFAFIAFAFQAeAbAoAAQAuAAAfggQAfggAAgsQAAgpgbgeIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfg");
	this.shape_8.setTransform(15,14.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhqBjQgrgoAAg7QAAg6ArgqQAKgIALgGIAKgHIAUgJIAIgCQAXgIAYAAQAaAAAXAIIAIACIAUAJIAKAHQAKAGAJAIQAsAqAAA6QAAA7gsAoQgtApg9AAQg9AAgtgpgAhGBSQAeAbAoAAQAuAAAfggQAfggAAgsQAAgpgbgeQAbAeAAApQAAAsgfAgQgfAgguAAQgoAAgegbICXiYIiXCYgAhqABQAAApAaAeIAFAFIAFAFIgFgFIgFgFQgageAAgpQAAgsAfggQAggfArAAQAkAAAbAUQAHAEAHAHIAEAFIgEgFQgHgHgHgEQgbgUgkAAQgrAAggAfQgfAgAAAsIAAAAgAAuAaQAHgCACgGQAJgJAAgMQAAgMgJgJQgCgFgHgDIAAA6IAAAAgAAuAagAAuggQAHADACAFQAJAJAAAMQAAAMgJAJQgCAGgHACgABAgDIAAAAg");
	this.shape_9.setTransform(15,14.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_2},{t:this.shape_4},{t:this.shape_3},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_7},{t:this.shape_8},{t:this.shape_2},{t:this.shape_4},{t:this.shape_3},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_9},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,32,30.1);


(lib.static_pro_rock = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.1,1,1).p("ABIABQgCgDgEgEQgCgCgEgEQgGgGgIgDQgJgEgHgEQgJgEgHgDQgHgDgFABQgCABgCACQgHAGgGAGQgGAGgFAGQgDADgCACAggAaQgDAEgDADQgBABgBABQgDACgEABQgKACgJgDQgBAAgBgCQgEgIABgMQAJgBAIgEQAHgFAHgFQAEgBADgE");
	this.shape.setTransform(-29.7,-3.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(0.1,1,1).p("AABj7QAGAAAFAAQAKAAAJAAQAKAAAJAAQAKAAAKAAQAJAAAJADQAIACAIAEQAIADAIAFQAHAGAGAFQAGAGAGAGQAGAHAGAIQAFAHADAJQACAJAFAIQAEAHAAALQAAAAAAABQABADAAAEQAAAAAAABQgBAEgEAEQgHAGgHAGQgHAGgHAFQgIAGgIAFQgIAFgJAEQgIADgJADQgJADgKABQgIAAgJAAAgSjfQAHgEAKgBQAIgBAKAAQAJAAAJAAQAJAAAKAAQAKAAAIADQAKACAIAFQAJAEAIAEQAJADAGAGQAIAGAIAFACxiJQABAAAAAAQAIAEAFAHQAGAHAGAHQAFAHADAJQADAJAAAKQAAAKgDAKQgCAIgDAIQgDAGgDAGQgBABAAABQAAABAAAAQACAIAEAGQADAGAEAGAiPjOQAIgDAIgDQAJgDAJgEQAIgCAIgEQAJgDAIgEQAIgDAJgEQAIgDAJgDQAJgCAJgCQAIgDALABQAEAAACAAAA5hLQAAAAgBAAABIh1QgGgHgLABQgEAAgEAAQADAHgCAKQgBAJgHAFAA5hLQABAAAAAAQgBgCgBACQAAAAgBAAQgFAGgLAAQgHABgIgBQgBAAgBAAQgBABgCACQgGAGgHAFQgGAEgJADQgJACgJgEQAEgEAEgEQAHgIAEgHQAEgJACgKQAAgEAAgFAAEhuQAGgFAJgEQAHgEAKAAQAFAAAGAAACFAkQgFgBgGgDQgIgDgHgEQgIgFgJgEQgIgEgJgEQgHgEgIgEQgIgFgJgEQgIgCgHgEQgJgEgJAAIAAAAQAEgBAEgGQAEgIAFgHQAFgHAEgFQAFgHAHgFQAHgFAEgFAg2DsQgBgBgBgCQgDgJAFgIQAGgIAGgBQAFgCADACQAFAGAEAIQAFAJAHADQAHAEAKgBQAJgBAKgBQAJAAAJgBQAKgBAGgGQAGgGAAgJQAAgKgJgEQgIgEgHgFQgGgEgJgEQgIgEgIgEQgIgEgHgFQgIgEgIgFQgIgFgHgFQgHgFgIgHQgFgEgHgCQgCgBgCAAQgCgCgCgEQgFgHgBgKQgCgJACgJQADgJAEgHQAFgIAGgGQAGgHAGgHQAFgHAGgHQAFgHAGgHQAFgIAHgFQAFgFAFgEQAGgFAHgEADYAIQAAgHgBgFQgCgJABgJQABgKAEgIQAEgIAFgIQAFgIADgJQACgIAFgIQADgGADgFQAAgBgBgBQgCgIgEgHQgCgDgCgDQgEgHAAgKQAAgKAHgEQAJgDAJAEQAIADAJACQAKACAJADQAJACAJABQABAAAAAAQADgDAIABQADgFAKACQgBACAAADQAGAAAHAAQABAAAAAAQAKAAAFgGQACgDADgCQADgDAFgDQAKgFAFAJQADAHgBAKQgBAKgKACQgDABgDgBQgCgCgCgBQgBgBgBAAQAAgBgBAAQgFAEgGADQgBABgBABQgGADgHACQgJACgJADQgHACgKADQgIAEgCAKQgBAHgBAJQgBAJgBAJQgBAJgDAJQgDAJgBAIQgCAFgCAIQgDANgFAWQgIAigBAFQAAAGgLAQQgKARgTAFQgTAFgHgCQgHgBgbgPQgagOgOgMQgBgBgBgBQAKgNAPgPQgGAAgGgCQgDgBgDgBAFEiMQABgBAAgBAFEiMQAEAAAEAAQACAAADAAAE6iMQAFAAAFAAAFeiUQgCADACAFAFeiUQACgCACgBQAIgDAJADAFSiRQADgGAJADADHgbQAAAAgBABQAAAAAAABQgFAHgEAHQgFAIgFAGQgEAGgFAEQgGAGgFAHQgEAHgEAHQAIgJAIgMQASgIAOgIQAFgDAIAAQABABAAACQACADABACQABADACACQACADACADQAEAGAEACABqAyQAGgDAFgCQAJgFAHgEABqAyQgCABgCABQgFACgFADQgGAEgHACQgJADgJADQgHADgJADQgIADgIADQgHADgHACQgHgEgIABQgKABgJgBAB+BEQgNgLgHgHAAPBWQAAAAABAAQAIAFAJADQAHACAHAFQAHAGAFAGQAFAGAHAHQABABAAAAQABACABABQAEAGAEAHQAFAJAFAIQAEAIAFAHQAGAIAGAHQAGAHAFAGQADAEAAAGQABACACABQAGAEAGAGQADADABAFQAEAKgDAJQgDAIgIADQgIAEgJAAQgKAAgKAAQgJAAgJgDQgIgCgIgDQgJgEgJAEQgIADgHAGQgGAFgKAAQgKAAgGgCQAAAFgGABQgIACgCgHQAAAAgBAAQgJAEgEgIQAAAAgBgBQAAgBgBgCQgCgIAJAAAAWByQAIAFAHAHQAHAGAGAIQABACADADABzDiQAHAJgKAEQgEABgFABAiPjOQACgGAFgIQAGgIAHgFQAHgHAHgHQAHgGAHgEQAIgEAHgGQAHgFAJgDQAHgEALACQAKABAIAEQAIAEAJAFQAHAEAFAIAjNiJQgBgDgCgCQgGgHgKAFQgJAEACAKQABABAAAAQgKADgKgBQgCgDgDgBQABANgMAAQgDAAgCAAQAEAJgKAHQgGADgHgBQABAJgJADQgCABgDAAQAEAFgFAHAmDh2QgFgBgDgHQgCgHADgHQAGgQAPgDQgHgBgDgIQgFgMAHgJQAJgNALABQgDgBABgDQAHgOANgHQANgHAKAJQAAgFADgEQAHgIALgBQARAAAHAIQADgEAJAAQAKABADAFQAHgHALACQALABADAGQAHgGAJAIQAGAEACAHQgEABgEADAmBh2QgBgBgBABQABAAAAAAQABAAAAAAQAGABABAAAlRgsQgBABgBABIgBAAQgFgBgFAAQgFgBAAgHQgFABgBgDQgCgGADgFQgJgBgHgFQgEgEAAgGQABgHAFgEQgEACgGgDQgKgEABgKQAAgIAGgEAk7gSQAAABgBABQgDAHgIACQgJADgJABAkIhJQAEAEAGADQAHAEgBgKQAAgKgHgGQgBgBgBgBQACAOgJADQgCgBgCgCQgDgDABgDQAAgIAIAAQACAAADAAIAAAAAi3g/QAAgBAAgCQABgLgGgGQgGgGgJgBQgJgBgIABQAEAEAAAIQAAAJAAAJQAAABAAABQABAEgEgBQgBAIABAIQgBgBgCAAQgIgDgJAAAj4gCQAAAAgBABQgEAFgHABQAAABAAABQgDAJgLgDQgJgCgDgIQgBAAgBAAQgKAAABgKQgEABgEgCQgHgDgDgHQADgGAEgGAj4gCQABgCABgBQADgEAAgEAjmiBQABAEAEAAAhEiLQALgBAGAHQAFAHAFAHQAGAIgCAKQgCAJgDAJQgCADgDABAiri8QAEgEAIgFQAHgFAIgDQAAAAABgBAjCjZQABAAABAAQANAAABAPQAAACABABQAHAEgBAHQAAAEgDAFQACACgBAGQgBAEgDABQgFACAAAFQgBAMgMABQgBAKgJgBAiLhWQgBgEABgEQABgKADgIQADgIAHgEQAFgDAEgDAi3g/QAAAJAKgFQAFgDACgGQACgIAGgGQAFgFALABQACAAABAAQABAFAEAEQgFAEgEAFQgHAIgGAHQgFAIgEAIQgCAGABAEQgBAAAAAAQgJgCgJgBQgKgCgJgDQgHgCgIgCAimgbQABAAABAAQAHACAEAFQAFAHADAIAjYg8QAJgEAJAAQAIAAAHABAgbgyQgCACgBABQgEAFgFAEQgBABgBABQAAACAAABQAAAKgDAJQgDAIgEAIQgEAJgFAHQgGAHgGAHQgFAGgIAGQgFAFgIAEQgIADgFAEQgJAFgJAAQgJAAgKAAQgKAAgJAAQgKAAgIgFQgGgDgIgGQgHgFgGgHQgHgHgGgHQgFgIgHgGQgHgHgEgGAjLh+QABgHgDgEAguECQgFgBgEgFQgGgIAGgIQABAAAAAAQACADAFgCAgnDmQgKgBgFAHAgjD2QgKABgBALQADAAAEgBAgfEMQgBABgCAAQgMAAAAgLAgQERQAAAAAAAAQAFgCABgDAgHEEQgMAAACALQABABAAAB");
	this.shape_1.setTransform(1,0.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAIgCQgBgIgEgEIARAAQAKABAGAGQAGAGgCAKIAAADIgOgBQgKAAgIAEIAAgRgAgeAJIgKgGQAKgDgDgNIADABQAGAGABAJQAAAHgEAAIgDgBg");
	this.shape_2.setTransform(-21.5,-7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CC9966").s().p("AgWAGIABgCQACgEALABIgCAFIACgFQACgFAJADQAAAAgBABQAAAAAAAAQAAAAAAABQgBAAAAABIABAEIgBgEQAAgBABAAQAAgBAAAAQAAAAAAAAQABgBAAAAIAEgDQAHgDAJADIgFAEQgEAGgKAAIgCAAIgMAAIgFAAIgHAAg");
	this.shape_3.setTransform(35.7,-14.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0C0C0C").s().p("ADGCJIALgFIAQgIIAFACIAEAAIAGABIABAAIAAAAIABAAQgOAPgLAOIgTgTgADwB/IgGgBIgEAAIgFgCIgMgEIgPgHIgQgJIgRgJIgQgJQgIgFgJgDIgPgGQgJgEgIAAIgBAAQAFgCADgGQAEgIAFgGIAKgNQAFgGAHgFQAGgGAFgFIAAAAIASAAQAJAAAJgDIARgHQAJgCAIgFIARgLIAOgLIANgNQAEgDACgFIAAAAQAJADAFAHIALAOQAFAIADAJQADAIAAAKQAAAKgCAJIgGAQIgGANIgBACIAAAAIgBABIgJAPIgKAPQgEAFgFAEQgGAGgEAIIgJANIgBAAIAAAAIgBAAgAD7ByQAEgIAGgGQAFgEAEgFIAKgPIAJgPIABgBIABABQABAHAEAHIAHAMQgHAAgGADQgOAJgRAHIgRAVIAJgNgAj4AtIgKgCQgFgBAAgGQgFABgBgDQgDgHADgFQgJgBgGgFQgEgDAAgHQAAgGAFgDQgEABgGgCQgJgEAAgKQAAgJAHgEQgGgBgCgGQgDgHADgHQAGgQAPgEQgHgBgCgHQgFgNAHgJQAJgMAKAAQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBABgBQAHgOAMgGQAOgHAJAIQAAgFADgEQAHgIAMAAQARgBAGAJQAEgFAJABQAKAAACAGQAIgHAKABQALABAEAHQAGgGAKAHQAGAEACAHQgFABgEAEQAEgEAFgBIABAAQANAAABAQQAAAAAAAAQABABAAAAQAAAAAAAAQAAABABAAQAGAFAAAHQgBAEgDAFQACACgBAGQAAAEgDABQgGACAAAEQAAANgNABQAAAJgJgBIgEgFQgGgGgKAEQgJAFADAKIAAABQgJADgKgCQgCgDgEAAQABAMgMAAIgFAAQAFAJgLAHQgFAEgIgBQACAIgJADIgGABQAFAFgGAGIgFADIgMAMIgMANIgEAEIgCACgAkfgeIgGAAQgBgBAAAAQAAAAAAAAQgBAAAAAAQAAAAAAAAIABABIABAAIAGAAgAixAKQgCgDAAgCQABgHAIgBIAEABIAAAAQADAMgKAEIgEgEg");
	this.shape_4.setTransform(-8.2,-8.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#BE9670").s().p("AgZERIAAAAQAFgCACgDQgCADgFACIgBgCIAAgDQAAgIAKAAQgKAAAAAIIAAADIAAACQgJAEgEgIIAAgBIgCgDIAAAAIAAAAQgBgIAHAAIABAAIAAAAIAAAAIAAAAIAAAAIAAAAIAAAAIAAAAIAAAAIgBAAQgHAAABAIIAAAAIAAAAIACADIgEABQgLAAAAgLIAAAAIABAAIAAAAIAAAAIAFgBIgFABIAAAAIAAAAIgBAAIAAAAQAAgLAKgBQgKABAAALQgGgBgEgFQgGgIAHgIIAAAAIgBgDQgEgJAFgIQAGgIAGgBQAFgCADACQAFAGAEAIQAFAJAHADQAHAEALgBIASgCIATgBQAJgBAGgGQAGgGAAgJQABgKgKgEIgPgJQgGgEgJgEIgPgIIgQgJIgQgJIgOgKIgQgMQgFgEgGgCIgFgBIgEgGQgEgHgCgKQgCgJACgJQADgJAEgHQAFgIAGgGIAMgOIALgOIALgOQAGgIAGgFIAKgJIAOgJQAIAAAJAEIAPAGQAJAEAIAFIAPAIIARAIIARAJIAPAHIAMAEIgRAJIgKAFIgFACIgKAFQgGAEgHACIgRAGIgRAGIgQAGIgOAFIgBgBQgFgCgEAAIgBAAIAAAAIgBAAIgDAAIgDAAIgDAAIAAAAIAAAAIgFAAIgHAAIAHAAIAFAAIAAAAIAAAAIADAAIADAAIADAAIABAAIAAAAIABAAQAEAAAFACIABABIABAAQAIAFAJADQAHACAHAFIAMAMIAMANIABABIACADIAIANIAKARIAJAPIANAPIAKANQAEAEgBAGIAEADQAGAEAFAGQADADABAFQAFAKgEAJQgCAIgJADQgIAEgJAAIgUAAQgJAAgJgDIgQgFQgJgEgJAEQgIADgGAGQgHAFgKAAQgJAAgHgCQAAAFgGABIgDABQgFAAgCgGgABoDvIgKACIAKgCQAFgCAAgEQAAgDgCgEQACAEAAADQAAAEgFACgAg5DuIAAgBIABAAIgBAAIAAABIgCAAIAAAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIAAAAIABgBQAEgFAHAAIABAAIAAAAIACAAIAAAAIAAAAIgCAAIAAAAIgBAAQgHAAgEAFIgBABIAAAAQAAAAABABQAAAAABAAQAAAAABABQAAAAABAAIAAAAIACAAgAAcB+QAIAGAFAIIAEAFIgEgFQgFgIgIgGIgPgMIAPAMgAgaEPIAAAAgAg/DsIAAAAgADBBwQgHgBgbgPQgagOgOgMIgCgCQAKgNAPgPIARgVQARgIAOgIQAFgDAIAAIACADIACAFIADAFIAEAGQAEAGAFACQgFgCgEgGIgEgGIgDgFIgBgMQgCgJABgJQABgKAEgIIAJgQQAFgIADgJQACgIAFgIIAGgLIAAgCQgDgIgEgHIgDgGQgFgHAAgKQAAgKAIgEQAIgDAJAEQAIADAKACIASAFQAJACAKABIAAAAIAKAAIAIAAIAFAAIANAAIABAAQALAAAEgGIAFgFIAIgGQAKgFAFAJQAEAHgCAKQAAAKgKACQgEABgDgBIgEgDIgCgBIgBgBIgLAHIgCACQgFADgIACIgSAFIgQAFQgJAEgBAKIgDAQIgCASQgBAJgDAJIgEARIgDANIgJAjIgIAnQgBAGgKAQQgLARgTAFQgPAEgIAAIgDgBgAiwBBQgKAAgIgFIgNgJIgOgMIgNgOIgLgOQgIgHgEgGIADgDQACgEAAgEQAAAEgCAEIgDADIgBABQgEAFgHABIAAACQgDAJgLgDQgJgCgDgIIgCAAQgKAAABgKQgEABgEgCQgHgDgDgHIAIgMIgIAMIAAACQgDAHgJACQgJADgIABIAFgHIgFAHIgDACIgGACQgLACgIgDIgDgBQgDgIAAgMQAJgBAIgEIAOgKIAIgGIACgCIAEgEIALgMIANgMIAFgDIABAAIABAAIAAAAIABgBIABAAIAAAAQAEABAEACIAQAHIAQAIQAIADAHAGIAGAGIAFAIIgFgIQAJAAAIADIAEABIAOAEQAJADAKACIASADIABAAQgBgEADgGIAJgQIAMgPIAJgJQgEgEgBgFIAAgEIAAgEQABgKADgIQAEgIAGgEIAJgGIgJAGQgGAEgEAIQgDAIgBAKIAAAEIAAAEIgDAAQgLgBgFAFQgGAGgCAIQgBAGgGADQgKAFAAgJIAAgDQACgLgHgGQgFgGgKgBIgRAAQAEAEAAAIIAAASIAAACQABAEgEgBIABAQIgEgBQgIgDgJAAIgGgGQgHgGgIgDIgQgIIgQgHQgEgCgEgBIAAAAIgBAAIgBABIAAAAIgBAAIgBAAQAFgHgEgFIAGgBQAJgDgCgJQAHABAGgDQAKgHgEgJIAFAAQAMAAgBgNQADABACADQALABAJgDIgBgBQgCgKAJgEQAKgFAGAHIADAFQAKABAAgKQANgBAAgMQAAgFAFgCQAEgBAAgEQABgGgCgCQADgFAAgEQAFgEAHgFIAPgIIABgBQACgGAGgIQAFgIAHgFIAPgOQAGgGAHgEQAIgEAHgGQAIgFAIgDQAIgEAKACQALABAHAEIARAJQAHAEAGAIIgHAAIgCAAIgBAAIAAAAIgBAAQgHAAgHABIgBABIAAAAIgSAEIgRAGIgRAHIgRAHIgPAGIgSAHIgRAGIARgGIASgHIAPgGIARgHIARgHIARgGIASgEIAAAAIABgBQAHgBAHAAIABAAIAAAAIABAAIACAAIAHAAIAKAAIAUAAIATAAIATAAQAJAAAJADIARAGQAHADAIAFIAOALIALAMIAMAPQAFAHADAJQADAJAEAIQAFAHAAALIAAABIAAAHIABABQgCAEgEAEIgNAMIgPALIgQALQgIAFgJAEIgRAGQgJADgKABIgRAAQAAgBAAAAQgBAAAAAAQAAAAAAAAQgBAAAAABIgBAAQgFAGgLAAIgPAAIgCAAIgDADQgFAGgHAFQgGAEgKADQgIACgKgEIAIgIQAHgIAEgHQAEgJACgKIABgJIgBAJQgCAKgEAJQgEAHgHAIIgIAIIgDADIgJAJIgCACIAAADQAAAKgDAJQgDAIgEAIQgEAJgFAHIgMAOQgFAGgHAGQgGAFgIAEIgNAHQgJAFgJAAIgSAAIgUAAgAisgbQAGACAEAFQAGAHACAIQgCgIgGgHQgEgFgGgCIgDAAIADAAgAkOhaQgJAAAAAIQgBADADADIAEADIAKAHQAHAEgBgKQAAgKgGgGIgDgCIAAAAIgEAAIAAAAgAgthlQgCAJgEAJQgBADgDABQADgBABgDQAEgJACgJIAAgFQAAgHgFgGIgKgOIAAAAQgFgGgIAAIgBAAIAAAAIgDAAIADAAIAAAAIABAAQAIAAAFAGIAAAAIAKAOQAFAGAAAHIAAAFgAAnhqQgBAJgHAFQAHgFABgJIABgHQAAgFgCgFIAIAAIABAAIABAAIAAAAIAAAAQAJAAAFAFIAAAAIAAABIABAAIAAAAIAAAAIgBAAIAAgBIAAAAQgFgFgJAAIAAAAIAAAAIgBAAIgBAAIgIAAQACAFAAAFIgBAHgAAKh3QgJAEgEAFQAEgFAJgEIABgBIAAAAIADgBQAFgCAFAAIABAAIAAAAIABAAIABAAIALAAIgLAAIgBAAIgBAAIAAAAIgBAAQgFAAgFACIgDABIAAAAIgBABgAjqh9QgEAAgBgEQABAEAEAAgAjUh+IAAgDQAAgFgCgDQACADAAAFIAAADgAAajlIATAAQAKAAAIADQAKACAIAFIARAIQAJADAHAGQAHAGAIAFQgIgFgHgGQgHgGgJgDIgRgIQgIgFgKgCQgIgDgKAAIgTAAIgSAAIgSABQgJABgIAEQAIgEAJgBIASgBIASAAg");
	this.shape_5.setTransform(1.9,0.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-39.7,-28.3,81.3,57.8);


(lib.static_pro_dance = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.1,1,1).p("ACijXQAJACAKgBQAJgBAHgIQAAgBAAgBQACgBABgBQAEgEABgIQADgKgHgHQgBgBABgCQAHgIAAgKQAAgKgHgIQgEgFgEAEQACgMgJgGQgIgGgHADQgEACgDAEQgCgNgMgDQgFgCgEAFQgCADgBAEQgBgNgPgFQgWgHgYAFQgGABgCAEQgCADAAAEQAAgHgHgBQgNgDgIAKQgFAGAAAHQgCgKgLADQgMACgGAKQgFAGACAIQgCgJgKgBQgHAAgFAEQgJAHgEARQgCAFAFAGQgHgHgLAEQgMAEgIAKQgDADgBAGQgCAHADAGQgIADAAAKQgFgDgGgCQgOgMgTgDQgTADgRAAQgHADgHACQgCAAgDABQgLgFgQABQgRAHgPADQgMAJgQAIQgMALgKAPQgHAJgCAQQgEAMgDAMQgIAKgFAEQgQABgRACQgGAUgFATQgCARAQABQgEAGACADQAIAKARgBQANAFAHAGQAHADAKgHQAQABAFgWQAQgCAEgPQAGgIgDgHQgMgOgTAKQALgHABgSQAQADAQgLQARgFAMgIQADABADgEQAOgFAKgGQgEAQARAGQAEAEAFACQgEASgKANQgJASgKAKQgMANgIAPQgBABgCABQgIAJAGAPQAOAPALALQALALAOAEQAIAAAFgBQANgGALgIQAOgKAQgGQAOgIASgGQAPgJASAAQAUAFAIAPQAMAJgCAQACijXQACgGACgFQAAgFgBgEQgBgDgBgDQgBgBAAgBQAAgEACgFQgIACgFADQgVAAgOgJQgCADgFACQgWAHgRgJQgCAEgFACQgKAFgLgCQADAEADAGQABAGgCAFQgGAMgLADQAFAEgCAGQgEAKgIABQgBgIgGgFQgDgDgFAEQgGAGgEAIQgEAJAHAIQABACACABQACABACAAQABALgLgDQgCAAgCAAQgDgFgEgFQgBgBgBgBQgJgJgOAAQgIgBgHgBQgLgBgIABAB7hvQAEgCADgBQAHgHAGgHQAFgIAEgGQABgBABgBQAFgEADgGQAEgIAAgIQACgKAAgJQgDgIgFgFQgCgDABgBQACgFABgEAB3jWQAKADgDAKQgCAJgLgDQgGgCgDgEAB+jrQAEgIAKABQAEAAADABABJi6QAMANATgBQAUAIAKgLQADgGABgEQAAAPgGAPQgBAFgDAFQgEAEgFAEQgaARgNgYQgGgEgEgFQgDgGAAgGQgBgOAHgFQABgEADgEACAjcQAJAAAIACABAjUQAGgIAIgBQAHgCAEADAA7jfQABgHAJgEQAIgBAGgCAAGikQABABACgBQADgBACgCAD1hyQgCgCgCgCQgGgGgLABQgJABgKACQgJACgIAFQgJAEgJADIAAABQgBAAAAAAQgFAAgFABQgJgEgJAAQgJgCgJgBQgEACgEACQgBABAAAAQgJAAgJgBQgFAAgEgBACghbQACgEADgFQABgCACgCQABAAAAgBQAAAAABAAAB2ggQAKABAJACQAKABAIACQAJADAKgBQAJADAKACQAJABAJABQAKgBAJABQAKgBAJgCQAJgDAKgCQAHgCAIgGQAFgDAFgEAB5glQgCADgBACAE1iuQADgCADgDQAGgIgCgIQgBgDgDgCQgJgEgFAGQACgGAAgGQAAgHgEAAQgJgCgIADAEtjGQgBADgBADQgFAIgHAFQgBABgBAAQADAJALgCQAFgBAFgCAE+hHQADgFADgFQAFgJAAgKQABgIgFgJQgFgIgGgIQgBgHgHgIQgFgIgGgDQAAAAABAAQAJgDAEgMAD2jWQAAgCAAgDQAAgKgDgKQgEgGgIgEQgLgDgHACQgEABACACQAEAHADAHQADAIAEAGQADAHAAAIQgBABgBAAQgGAAgHABQgBAAgBABQgEAGADAIQAEAHAJABQACAAACABQALAFACAKQACAJACAJQAFAHgDAKQAAAHgBAHQAAADAAACQgBAHABAEAD6jNQABgDgEgFQAAAAgBgBAEDi7QABgDABgDQABgDgDgDQgEgEgFgCAEQi7QAFgCACgGQACgJABgJQAAgBAAgCQABgGgEgEQgJgDgMACQgIAEgEAJADkjMQAHgBAIgBQAEAAADABADjiyQAHAAAIABQAJgCAGgGQABgBABgBAEdiyQgHAFgEgHQgCgDAAgEQgEABgEgBQgDABgCgBAEnifQgIACgJAAAEKguQAGAEAKACQAGABAFgBQAEAAADgCQAIgDAEgIQAFgIABgKQgCACgCACQgFAGgHAEAD8AbQAkADAjgHQAngJAEgjAgJBfQAGgOAHgQQAFgSgBgTQAAgDABgCQAggHAggIQAdgKAQgeAA1DEQADgFAAgHQAAgKgFgGQgCgCgCgCABODDQABAAAAgBQAQgKgCgWQgDgZgUAGQgKADgGAMQgEADgDADQgFgDgFABQgKAAgDAIQgIgHgHAGQgFADgCAFQAAAAgBAAQgCgCgDgBQgKgEgDAKQgCAEgBAEIABAAQADAAAAACQABAJgGAIQAAADgEAAQgGABgFgBAACCyQAAAAAAgBAABCxQAAABABAAQACADACAEQACAHgCAJQgDAEgEACQgFABgDgEAAYCqQADACABAEQABADAAAEQAAAJgCAGQgFANgJgEQgFgBgCgFAAbDGQADAGAKABQAHAAAEgEQABgCABgDAheEgQAFAEAHABQAQAIAhgZQAIgOAHgOQADgHAGgBQAPgEATAAQARgBALgJQATgHAGgYQgOAHgLgGACPBzQAaAfgSAoAlbi3QAIgkAYgVQAKgIAMgFQALgEASAGAg3izQgGgPgJgNQgGgIgIgEAiZh6QAKAEANgGQATgBANgOAgKBmQAAgEABgDQgBABAAAAQgBAEABACgAhhBmQgBAHgBAHQAAAIgBAIQgIABgJAEQgIADgHADQAJAHAFARQACATABASQgUAEgOAIQgRAIgKAKQgMAMgCAUQgOAGgRAHQgUAHgMAHQgHALgBAQQATAIAfAFQACAAADAAQACAAADABQAEAEAJgCQABAAAAAAQACgBABgBQACgBAAgCQADgIAAgIQAAgBAAgBQgBgCgBgBQgFgFgCgIQAJgHAMgFQAPgKAQgGQAOgIARAAIAEgEQgCAEgCAEQABAQAKAHAhJA1QgIAQgKAOQgEAKgCAJAiUAfQgGADgGADQgMAIgEAMQgHASgCATQAJAQAHARQAEADALAEQACADACACQAFAEAEAAQADAAADgCQACgDADgEQAFgEgDgFQAMgJATgOAiHCNQABABACABAiWCLQAFgCARgMAjRghQgWATgHANQgMAQgGAQQgFATgDARQAHAUAGAPQAHARAMAMQALALAWADQAKABAKgBQAJABAJABQALAAAJgEAhzDMQAEAMgFABAgaC6QACgHACgJQAEgRACgTQADgQADgQAhkCEQAAANABALQAGARAEASQALANgFAUQgBADgBAFQgJAKgHAPAgUC8QgDgCgDAAQgEAAgEABQgFAIgFAJQgLAVAIALQgCAKgIAEQgHAEgHADQgJAEgHADQgFACgBAGQgDAKACAGAkcAWQgKAlgGAuQAFARAKAMAlOAxQgSAfABAoQABAVAOAAAjkEuQAMgNAXALIAAAAQADABABAHQAAACAAACQAAAVgRAAAi+EdQAAAHACAFAinFDIAAABQABAIgEAGQAAABgBAAQABAAABAAQAGgBACABQABAAAAABQACAAABAAQACAAABAAQAFAAACgEQABgCABgCQgDABgDgBQgCAAgCgBQAAgBgBgBQgDgHgIABQgCgHgKgBAi9E0QABABACAAQADAAACABAi4FOQAIAFAFAAAibFLQABAFgGAEAgBiLQgBgJgGgI");
	this.shape.setTransform(0.8,0.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgVAOQgGgFgEgFQgDgEAAgGQgBgOAHgGQAMANASAAQAUAHAKgKQADgGABgFQAAAPgGAPQgBAFgDAEQgEAFgFAEQgLAHgHAAQgMAAgIgOg");
	this.shape_1.setTransform(11,-15.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0C0C0C").s().p("AiXDyQgJAAgLgBQgWgCgLgMQgMgMgHgRIgMgiQADgSAFgTQAGgQALgQQAIgNAWgTQgIAIAFAPIAaAcQALAKANAFIAOgBIgMAGQgMAHgFAMQgHATgBASIAQAhQAEADAKAFIAEAEQAEAEAEABIABAAIABAAQgKADgKAAIgTgBgAhyDwQgEgBgEgEQAFgCARgMIABAEQAAADgDACIgFAHQgCADgDAAIgBAAIgBAAgAhwDwIAAAAgAhrDtIAFgHQADgCAAgDIgBgEIAggXIgCAPIgBAPQgIACgJADIgQAGIgDgCgAhrDtIAAAAgAAYg7IgEAAIgHgKIgCgCQgJgJgNAAIgPgDQgGgOgJgOQgGgHgIgFQgBgKAJgDQgEgGACgHQACgFADgEQAIgJAMgEQALgEAHAGQgFgFABgGQAFgQAHgIQAFgEAHABQAKAAADAJQgCgHAFgHQAHgJALgDQALgCACAKQAAgIAFgFQAIgKANACQAHACABAGQAAgDABgDQADgFAGgBQAXgEAXAHQAPAEABANIADgHQADgFAGACQALAEADANQACgFAFgCQAHgDAIAGQAIAHgBALQADgEAFAGQAGAHAAAKQAAAKgGAIQgBABAAAAQAAABAAAAQAAABAAAAQAAAAABAAQAHAHgDALQgCAHgEAFIgCACIgBABQgHAIgJABQgKABgIgCIAEgKQAAgFgBgFIgDgFIAAgCQgBgFACgEIgNAEQgVABgNgKQgCAEgGACQgVAHgRgKQgDAFgEACQgKAFgMgCQAEAEADAGQAAAGgCAFQgFALgLADQAFAFgDAGQgDAKgJABQAAgIgGgFQgEgDgEAEQgHAFgEAJQgFAJAHAHIAEAEIAEABQABAIgHAAIgEAAg");
	this.shape_2.setTransform(-2.1,-9.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#BE9670").s().p("AiNEqQAEgDAAgEIAAgCIAAACQAAAEgEADIgBAAQgCgCgGACIgCgBIAAABQgGAAgHgFIACgEQACgGAAgIIAAgBIAAABQAAAIgCAGIgCAEIgEACIAAAAQgJABgEgEIgGAAQARgBAAgVIAAgBIAAgCIAEAAIAEACIgEgCIgEAAIAAACIAAABQAAAVgRABIgFgBQgegFgTgIQABgQAGgLQAMgGAUgHIAggOQABgTANgMQAKgKAQgJQAOgHAVgEIgDglQgGgRgJgIIAQgGQAIgDAJgCIAAAEIABAVQAFAQAEATQAIAJAAAMIgBALIgDAIQgJALgHAOIgEAEQgRAAgOAJQgQAGgOAJQgNAGgJAGIgBgLIABALQADAIAEAGIACADIAAACQAKABACAHIAAAAIABAFQAAAFgEAFQAEgFAAgFIgBgFIAAAAQAIgBAEAGIAAACIAEACIAGAAIgBADQgCAFgFgBIgDAAIgCABIgBgBgAivEDIAAAAQAEABAAAHQAAgHgEgBIAAAAIAAAAIgBAAQgJgFgIAAIAAAAIgBAAQgIAAgHAGIAAAAIAAAAIAAAAIgBABIABgBIAAAAIAAAAIAAAAQAHgGAIAAIABAAIAAAAQAIAAAJAFIABAAIAAAAIAAAAgAhhCwQACgBAAgEIgBgIIABAIQAAAEgCABgAhAD8QgHgCgFgDIAAgGIABgLQACgFAFgDIAPgGIAPgIQAIgEABgJQgDgFAAgGQAAgJAHgNIAKgQIAAAAIAHgCIAAAAIAAAAIgHACIAAAAIgKAQQgHANAAAJQAAAGADAFQgBAJgIAEIgPAIIgPAGQgFADgCAFIgBALIAAAGQgJgIgCgPIAEgJQAHgOAJgLIADgIIABgLQAAgMgIgJQgEgTgFgQIgBgVIAAgEIABgPIACgPIggAXQgRAMgFACIgEgEQgKgFgEgDIgQghQABgSAHgTQAFgMAMgGIAMgGQAMgHAMgIQAOgJAQgHQANgJASgGIABAAQAOgIAQAAIABAAIAAAAIABAAIABAAQASAEAJAPQALAJAAAMIgBAFIgBAFQACATgGARIgOAeIAAACIgBAGIgFAgQgCASgDASIgFAPQAEAAADACIABgIQADgKAKAEIAGAEIABABIABgBQACgFAEgEQAHgFAIAGQAEgHAJgBQAGAAAEADIAIgGQAFgNAKgCQAUgGADAYQADAXgQAKIgCABIgBAAIgBABQgGACgFABIgBAAIAAAAQgFgBgEgCIgBAAIABAAQAEACAFABIAAAAIABAAQAFgBAGgCIABgBIABAAQgFAYgTAGQgLAKgSAAQgSAAgQAEQgGABgDAIQgGAOgJANQgZAUgQAAQgEAAgEgCgAgKCpIABAAIADAAQABAAAAAAQABgBABAAQAAAAAAgBQABAAAAgBQADgGAAgHIAAgEQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBIAAAAIAAAAQABABAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAEQAAAHgDAGQAAABgBAAQAAABAAAAQgBAAgBABQAAAAgBAAIgDAAIgBAAIgBAAIAAAAIgGAAIAAgBIAAABIAGAAIAAAAIABAAgAAjCnQAGAAADgJIABgBQAEAGAKAAIAAAAIABAAIAAAAIABAAQAEAAADgDIABgBIADgEIgDAEIgBABQgDADgEAAIgBAAIAAAAIgBAAIAAAAQgKAAgEgGQACgFAAgIIAAgDIgBgGQgBgEgDgDQADADABAEIABAGIAAADQAAAIgCAFIgBABQgDAJgGAAIAAAAIAAAAIgEgBQgFgCgCgFIABgIIgBgIQgBgDgDgDQADADABADIABAIIgBAIQgCAFgFABIgBABIgCAAIAAAAQgDgBgDgCIAAAAIAAAAQADACADABIAAAAIACAAIABgBQAFgBACgFQACAFAFACIAEABIAAAAIAAAAgABICbQADgGAAgGQgBgLgFgGIgEgDIAEADQAFAGABALQAAAGgDAGgAhJAqIgFASIAFgSQAKgPAIgQQgIAQgKAPgAAYCfIAAAAgABgCaIAAAAgAhRBaIAAAAgAingXIgagcQgGgPAJgIIADgDQAIgPAMgNQAKgKAJgSQAKgNADgSQgEgCgEgEQgSgFAFgQIgZALQgDADgDgBQgLAJgSAFQgPAKgRgCQAAARgLAHQASgJAMANQADAHgGAIQgEAQgQACQgEAWgQgBQgLAHgGgDQgHgHgNgFQgRABgIgJQgDgDAEgHQgPAAACgRIALgoIAggDQAFgDAJgKQACgMAFgNQACgPAGgJQAKgQANgLQAPgHANgJQAPgEAQgGQAQgBALAEIAGgBIAOgEQARAAASgEQAUADAOAMIAKAFQAIAFAHAHQAIAOAGAOIgBAAIgEAAIgBAAIgCAAIAAAAIAAAAIgGAAIgDABIgCAAIACAAIADgBIAGAAIAAAAIAAAAIACAAIABAAIAEAAIABAAIAQADQAOAAAIAJIACACIAHAKQAFAIACAIQgCgIgFgIIAEAAQALACgBgKIABAAIADAAIAFgDIgFADIgDAAIgBAAIgEgBIgEgEQgHgHAFgJQAEgJAHgFQAEgEAEADQAGAFAAAIQAJgBADgKQADgGgFgFQALgDAFgLQACgFAAgGQgDgGgEgEQAMACAKgFQAEgCADgFQARAKAVgHQAGgCACgEQANAKAVgBIANgEQgCAFABAEIAAACIADAFQABAFAAAFIgEAKIgDAJQgBABAAAAQAAABAAAAQAAABABAAQAAABABAAQAFAGADAIQAAAIgDAKQAAAJgEAIQgDAGgEAEIgDABIgJAOIgNAOIgGADIARADQAJABAJADIAKgBIAAACIgEAEQgDAEgBAFQABgFADgEIAEgEIABgBIAAgBIABAAIARgHQAIgGAKgCIATgDQAKAAAGAGIAFAEIAAgPQAEgJgFgIIgEgRQgCgKgMgGIAQACQAIgCAHgHIABgCIgBACQgHAHgIACIgQgCIgDAAQgKgBgDgIQgDgIAEgGIACAAIANgCIACAAIAPgCIABAAIAAAAIADAAIAAAAIACABIABAAQAEABAEAEQADADAAACIAAABIgDAGIADABIABAAIABAAIABgBQAEABADgBIACAHIABABQACAEADAAIAAAAIABAAIABAAIACgBIABgBIgBABIgCABIgBAAIgBAAIAAAAQgDAAgCgEIgBgBIgCgHQAFgBACgHQADgIAAgJIABgDIgBADQAAAJgDAIQgCAHgFABQgDABgEgBIgBABIgBAAIgBAAIgDgBIADgGIAAgBQAAgCgDgDQgEgEgEgBIAAgBQAAgDgDgEIgBgCQAEgJAIgEQALgCAJAEQAEAEAAAGQAHgDAJACQAFAAgBAGQAAAHgCAGQAGgGAJAEQADABAAAEQACAHgFAIIgGAFQgFADgFABIgBAAIgDAAIAAAAIgBAAQgHAAgDgHIADgCQAHgEAEgIIACgGIgCAGQgEAIgHAEIgDACQADAHAHAAIABAAIAAAAIADAAIABAAQAFgBAFgDQgFAMgJADIgBABQAHADAFAIQAGAIABAGIALARQAFAIAAAJQAAAKgGAIIgGALIgDAEQgGAGgGAEQAGgEAGgGIADgEQgBAJgEAJQgFAIgHADIgIACIgCAAIgBAAIAAAAIgDAAIgEAAIAAgBQgLgCgFgDQAFADALACIAAABIAEAAIADAAIAAAAIABAAIACAAIgJAHQgIAFgIACIgSAGIgTADQgJgCgKABIgTgCQgJgBgJgEQgKACgJgDQgJgDgJAAQgJgDgLAAIADgGIgDAGQgQAegcALQggAIghAGIABgFQAAgMgLgJQgJgPgSgEIgBAAIgBAAIAAAAIgBAAQgQAAgOAIIgBAAQgSAGgNAJQgQAHgOAJQgMAIgMAHIgOABQgNgFgLgKgAEIiMIgBgGIAAgFIABgEIgBAEIAAAFIABAGgAByiUIATAAIAAAAIAJgFIgJAFIAAAAIgTAAIgJgBIAJABgAh8iiQAEAAAFgCIAAAAIACgBIABgBQAUgBAMgNQgMANgUABIgBABIgCABIAAAAQgFACgEAAIgCAAIAAAAIgIgBIgBgBIABABIAIABIAAAAIACAAgABbjkQgGAGAAAOQABAGADAFQADAGAHAEQANAXAZgQQAGgEADgFQADgEACgFQAFgQAAgPQAAAFgDAGQgLAKgTgHQgUAAgMgNQABgEADgDQgDADgBAEIAAAAgAEpjGIAQgCIgQACgACJjsQAGAAACgHIAAgDQAAgHgHgDQAHADAAAHIAAADQgCAHgGAAIgBAAIAAAAIgDAAIgBgBQgHgBgCgFQACAFAHABIABABIADAAIAAAAIABAAgABhkHQgJACgGAHQAGgHAJgCIAEAAIAEAAIACABIgCgBIgEAAIAAAAIgEAAgACjkEIgBAAIgMgBIAAAAIgBAAIAAAAIgCAAIACAAIAAAAIABAAIAAAAIAMABIABAAgABXkUQgJAFgBAGQABgGAJgFIAPgCIgPACgACQkUQAEgHAIAAIAAAAIAAAAIABAAIABAAQAFgBACACQgCgCgFABIgBAAIgBAAIAAAAIAAAAQgIAAgEAHgAFQhwIAAAAgAD1jcIAAAAgAEijlIAAAAgAD0kEIgIgPQgCgHgFgGQAAgBAAAAQAAAAAAgBQAAAAABgBQAAAAABAAQAIgCALADQAHADAFAHQACAKAAAJIABAFIABACQADAEAAADIAAABIgBAAIgCgBIAAAAIgDAAIAAAAIgBAAIgPACQAAgIgDgHgAENj2IAAAAg");
	this.shape_3.setTransform(-1.1,4.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-36.8,-34.5,75.2,70);


(lib.menu_main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgWAoQgQgMAAgdIAAgIIAAgIIABgHIAAgGQAAgFABgEQADgFAEgBQADAAADACQADADgBADIAAAKIAAAKIAAAIIAAAIQAAAJABAHQADAJAFAEQADABAIABQAPAAAGgaQADgNAAgaIABgFQADgFAFAAQADAAADAEQAAAAAAABQAAAAABABQAAAAAAABQAAAAAAABQAAAXgCANQgDATgKAOQgEAFgGAEQgHAFgIgBQgPABgGgGg");
	this.shape.setTransform(37.7,11.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgoAtQgDgCAAgDIABgIIAAgHIAAgKIAAgKIAAgKIAAgMIgBgKIAAgLQAAgDADgDQADgDAEAAQAEAAAFAIQAaAmAaAXIAAgJIgBgmIgBgGIAAgHQAAgIAJAAQAJAAAAAeIAAAJIgBAkIAAAJQgBAIgIAAQgEAAgFgFQgWgUgcgkIgBASIABAOIAAAOQAAARgJAAQgDAAgDgDg");
	this.shape_1.setTransform(28.5,10.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgaAsQgHgFAAgTIABgXIACgXIgBgGIgBgGQAAgJAJAAQAAAAABAAQABAAAAAAQABABAAAAQABAAAAAAIANgCIALgBQAPAAAIADQAGACAAAGQAAADgCACQgDADgDAAIgDAAQgJgDgJAAIgJABIgKACIgBAXIAWgDIAOgBQAEABACACQADACAAADQAAAHgIAAIgOABIgYADIAAAMQAAAMABABQABABAGAAIAKgBIALAAIAEAAIADAAQAEAAACABQADADAAAEQAAAGgHACQgGABgRAAQgUAAgFgGg");
	this.shape_2.setTransform(20,10.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAfAmIgCgOQgDgKgEgTIgJAXIgDALIgFALQgDAFgEAAQgFAAgEgHIgDgLIgIgeIgIAcIgBANQgDAJgHgBQgDAAgDgCQgCgDAAgDQAAgKAFgNIAGgWIADgSQADgMADgFQADgEAEAAQAGABACAFQADAFADAQQACAPAFARQAGgRAGgVIADgNQADgIAHAAQAGgBADAKIADAPQADAYAGASIAFAUQAAADgDACQgDACgDAAQgGABgEgKg");
	this.shape_3.setTransform(10.9,11);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1.5,1,1).p("Ai4hoIFxAAQAxAAAAAwIAABxQAAAwgxAAIlxAAQgxAAAAgwIAAhxQAAgwAxAAg");
	this.shape_4.setTransform(23.4,10.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ai4BpQgxAAAAgwIAAhxQAAgwAxAAIFxAAQAxAAAAAwIAABxQAAAwgxAAg");
	this.shape_5.setTransform(23.4,10.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(1.5,1,1).p("Ai4hoIFxAAQAxAAAAAwIAABwQAAAxgxAAIlxAAQgxAAAAgxIAAhwQAAgwAxAAg");
	this.shape_6.setTransform(23.4,10.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#00CCFF").s().p("Ai4BpQgxAAAAgxIAAhvQAAgxAxAAIFxAAQAxAAAAAxIAABvQAAAxgxAAg");
	this.shape_7.setTransform(23.4,10.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0099FF").s().p("Ai4BpQgxAAAAgxIAAhvQAAgxAxAAIFxAAQAxAAAAAxIAABvQAAAxgxAAg");
	this.shape_8.setTransform(23.4,10.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_8},{t:this.shape_6},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,48.8,23);


(lib.general_buttoncolor = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{resetRed:1});

	// timeline functions:
	this.frame_0 = function() {
		this.play();
	}
	this.frame_8 = function() {
		this.gotoAndPlay("resetRed");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(8).call(this.frame_8).wait(2));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#D5FFD7","#61EF01","#1DA400","#004A00"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgwAAgigjQgjgigBgxQABgwAjgiQAigjAwAAQAxAAAjAjQAjAigBAwQABAxgjAiQgjAjgxAAIAAAAg");
	this.shape.setTransform(11.9,11.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FFFFFF","#EC0000","#9D0000","#480000"],[0,0.345,0.635,0.937],0.4,7,0,0.4,7,18.8).s().p("AAAB2QgwAAgigjQgjgigBgxQABgwAjgiQAigjAwAAQAxAAAjAjQAjAigBAwQABAxgjAiQgjAjgxAAIAAAAg");
	this.shape_1.setTransform(11.9,11.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},8).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,23.7,23.6);


(lib.Copyright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAcAIIgEgLIgDAKQgEAJgEAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBIgCgJIgCgHQgGATgDAAIgCgBIgBgDIABgCQACgEACgHIADgMQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQAFAAACAIIACALIADgGIADgJQACgFACAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIADAKIACAHIADAIIABABIgBADIgDABQgDAAgCgJgAgUANIgBgIIAAgGIgBgHIgFAAIgFgBQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAEAAIAFAAIAPAAIADAAIADAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABQAAABAAABQAAAAgBABQAAAAAAAAQgBAAgBAAIgNABIAAAHIABAHIAAAEIABADIgBADIgCAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAgBg");
	this.shape.setTransform(57.3,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgMAYQgGgCAAgEIABgDQAAgBABAAQAAAAABAAQAAgBABAAQAAAAAAAAIAEACIAFACIAEABIAGgBQAEgCAAgCQAAgGgIgCIgEgCIgIgCQgDgCAAgFQAAgJAIgEIAIgDIAIgDIADAAIAEABIABADIABAEIAAADIgBAEIgDABQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBIgCgEIgKADQgGACAAAFIACAAQAJACAGADQAHAEAAAJQAAAHgGADQgFADgIAAQgFAAgGgCg");
	this.shape_1.setTransform(51,2.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgLATQgHgGAAgJQAAgIAGgJQAGgLAIAAQAEAAAGACQAGADAAADIgBADQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgDgBIgCgCQgCgCgGAAQgEAAgEAIQgEAIAAAEQAAAGAEADQADADAGAAIAFgBIAFgDIACgBIADACIABADQAAADgGADQgHADgDAAQgJAAgFgGg");
	this.shape_2.setTransform(46.6,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgDAgQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgIIAAgIIABgKIAAgKQAAAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAIADgBIACABQABAAAAABQAAAAAAABQABAAAAABQAAAAAAAAIgBAKIAAAKIAAAIIAAAIQAAABAAAAQAAAAAAABQAAAAgBAAQAAABAAAAIgCABIgDgBgAgCgXQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAQAAgBgBAAg");
	this.shape_3.setTransform(43.1,1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AALAVIgBgJIgBgKIAAgDIAAgEQAAgKgDAAQgFABgEAFQgEAGgCAGIAAAFIgBAEIABAEIAAAEIgBADIgDACIgEgCIgBgDIAAgEIAAgEIAAgMIABgMIAAgEIAAgEIABgEIADgBQAEABAAAFIABAFQAHgKAHAAQAHAAADAHQABAEABAIIAAAFIAAACIABAKIAAAJIgBAEIgDABQgEAAAAgFg");
	this.shape_4.setTransform(39.5,2.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAOAWIgDgDIgHADIgFACQgKAAgFgGQgEgFAAgMQAAgKAHgHQAIgIAJAAQAEAAAEACQAGADAAADIgBACIAAAGIgBAJIABAIIADAJIABABIAAABIgBAEIgDABIgDgDgAgGgKQgFAGAAAGQAAAHACADQADAEAFAAQADAAADgBIAEgEIgBgQIAAgEIABgFIgDgBIgCgBQgFABgFAFg");
	this.shape_5.setTransform(34.8,2.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAMAiIgCgLIgBgLIAAgDIAAgDQAAgIgDABQgGAAgDADIgHAKQAAARgBADQgBABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgBgEIABgBIAAgGIAAgHIAAggIABgHIgBgEIAAgEQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBQADAAAAAEIABAIIAAAKIAAAJIAAAFQAEgFAEgDQADgDAFABQAGAAAEAEQABAEAAAHIABAIIAAAJIACAJIABACQAAAAgBAAQAAABAAAAQAAABAAAAQgBAAAAAAIgDABQgDAAgBgCg");
	this.shape_6.setTransform(30,1.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgLATQgHgGAAgJQAAgIAGgJQAGgLAIAAQAEAAAGACQAGADAAADIgBADQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgDgBIgCgCQgCgCgGAAQgEAAgEAIQgEAIAAAEQAAAGAEADQADADAGAAIAFgBIAFgDIACgBIADACIABADQAAADgGADQgHADgDAAQgJAAgFgGg");
	this.shape_7.setTransform(25,2.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgOATQgHgFAAgKQAAgLAGgHQAGgJAJAAQAHAAAFACQAFADAAAHQAAAEgFAEIgJAEIgQAHQADAFADABQAEACAEAAIAHgBQAFgCACgCQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAABAAIADABIABADQAAAEgIAEQgHADgGAAQgJAAgGgFgAgIgLQgEAFgCAGIAOgFQAHgEADgCQgDgEgHAAQgFAAgDAEg");
	this.shape_8.setTransform(20.3,2.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAbAhIgCgHIgCgIQgCgGgDgXIgJAZIgDAJIgEAIQgBADgCAAQgDAAgCgDIgBgFIgBgEIgIghIgCAIIgGAWIgBANQgCADgDAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBIAAgDQAAgHACgLIAGgQIACgPQACgJACgDQACgDACAAQADAAABAEQADAEABAMQADAOAFAPQAFgPAFgTIABgGIACgGQACgEADAAQAEAAABAIIADAKQACATADAOIADAIIACAHQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAAAIgDABQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAgBg");
	this.shape_9.setTransform(13.8,1.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgQAUIAAgeIAAgEIAAgEQAAgFAEAAQAEAAAAAIQAIgJAKAAQAEAAABADQACADAAAFIAAADQAAAGgEAAQgEAAAAgFIAAgDIAAgDQgHAAgEAEQgDACgDAGIAAAXQAAAFgEAAQgEAAAAgFg");
	this.shape_10.setTransform(5.1,2.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAOAWIgDgDIgHADIgFACQgKAAgFgGQgEgFAAgMQAAgKAHgHQAIgIAJAAQAEAAAEACQAGADAAADIgBACIAAAGIgBAJIABAIIADAJIABABIAAABIgBAEIgDABIgDgDgAgGgKQgFAGAAAGQAAAHACADQADAEAFAAQADAAADgBIAEgEIgBgQIAAgEIABgFIgDgBIgCgBQgFABgFAFg");
	this.shape_11.setTransform(0.5,2.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgBAaQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIgBgQIgBgPQAAgEgCgDQgDABgCAEIgGAFIgCADIAAAHIgBAIIABADIAAAEQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAABIgEABQgEAAAAgLIAAgIIABgHIgBgHIAAgHQgBgKAFAAIADABQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABIAAACIgBADIAAAFQACgFAFgEQAEgEADAAQAHAAACAHQADgDACgCQAEgBAFAAQAGAAADAIIACAMIAEAYIgCADIgDABQgEAAAAgDIgCgOIgCgNIgBgGQgCgEgBAAIgGADIgGAEIAAAIIACALIABAMIgBADIgEABQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAg");
	this.shape_12.setTransform(-5.2,2.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgCAaQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIgBgQIgBgPQAAgEgBgDQgEABgCAEIgGAFIgCADIgBAHIAAAIIAAADIABAEQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAABIgDABQgGAAAAgLIABgIIAAgHIAAgHIgBgHQABgKAEAAIADABQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAABIAAACIAAADIAAAFQADgFAEgEQAFgEADAAQAGAAACAHQACgDADgCQAEgBAEAAQAIAAACAIIACAMIAEAYIgCADIgDABQgDAAgBgDIgCgOIgCgNIgBgGQgBgEgCAAIgGADIgFAEIAAAIIABALIABAMIgBADIgEABQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAgBAAg");
	this.shape_13.setTransform(-12.2,2.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAOAWIgDgDIgHADIgFACQgKAAgFgGQgEgFAAgMQAAgKAHgHQAIgIAJAAQAEAAAEACQAGADAAADIgBACIAAAGIgBAJIABAIIADAJIABABIAAABIgBAEIgDABIgDgDgAgGgKQgFAGAAAGQAAAHACADQADAEAFAAQADAAADgBIAEgEIgBgQIAAgEIABgFIgDgBIgCgBQgFABgFAFg");
	this.shape_14.setTransform(-18.1,2.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgQAUIAAgeIAAgEIAAgEQAAgFAEAAQAEAAAAAIQAIgJAKAAQAEAAABADQACADAAAFIAAADQAAAGgEAAQgEAAAAgFIAAgDIAAgDQgHAAgEAEQgDACgDAGIAAAXQAAAFgEAAQgEAAAAgFg");
	this.shape_15.setTransform(-22.4,2.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgWAeQgFgGAAgMQAAgLAFgLQAGgMAIgIQAGgFAFAAQAEAAAGACQAJAEgBADIgBAEIgDABIgDgBQgGgEgFAAQgDAAgDAEIgFAFQgKAOAAAPQAAAIADAEQACADAHAAQAIAAAGgFQAGgFACgKQgNAAgHAEIgCABQgBAAAAAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgCgCQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAABAAQAJgFAWAAIAEABIABACQAAABAAABQAAAAgBABQAAAAAAABQgBAAAAABQgDANgJAIQgJAIgLAAQgKAAgGgGg");
	this.shape_16.setTransform(-27.7,1.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgOAhIgBgDIADgIIAKgXQAFgPAHgHIABgBIgVgBIgKAAQgEAAAAgEQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAIARABIAPAAIAIAAQAFAAAAADQAAACgDADIgEAFQgFAHgFAJIgIARIgDAKIgEAKQAAAAgBABQAAAAAAAAQgBABgBAAQAAAAgBAAIgDgCg");
	this.shape_17.setTransform(-36.2,1.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AABAiIgIAAIgEAAQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgFAHAAIACAAIACAAIAAgGIgBgGIABgQIABgRQgGAEgBAAIgDgBIgCgDQAAgCAEgDIAHgFQADgEADAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAADIAAADIAAAFIAAAEIgBAPIgCAOIABAGIABAGIAEAAQABAAAAAAQAAAAABAAQAAAAAAABQABAAAAAAIABADIgBADIgDABg");
	this.shape_18.setTransform(-41,1.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgTAXQgFgJAAgPQAAgMAGgKQAIgLALAAQAMAAAGAKQAGAJAAAMQAAATgHAJQgGAKgMAAQgNAAgGgMgAgLgRQgEAHAAAJQAAANAEAIQAEAHAHAAQAJAAAEgLQADgHAAgLQAAgLgEgHQgEgFgHAAQgHgBgFAJg");
	this.shape_19.setTransform(-45.9,1.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AANAhIgDgBIgGABIgGAAIgFAAIgFABIgCAAIgBAAQgDAAgBgDIgBgGQAAgKAGgGQADgDALgHIAHgGQAEgFAAgFQAAgDgEgCQgDgCgDAAQgDAAgEACIgGAFIgDABQgEAAAAgDQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQAFgFAEgCQAFgDAFAAQAHAAAGAEQAGAEAAAHIgBAJIgEAGQgDADgIAFQgIAFgCADQgFAFAAAHIAJAAIAMgBIAHABQAEACAAACQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBABIgCABIgEgBg");
	this.shape_20.setTransform(-51.3,1.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgeABQgBgLALgKQALgJANAAQANAAAHAIQAIAIAAAMQAAAKgJAKQgKALgNAAIAAAAQgfAAABgdgAgOgPQgJAHABAJQAAALAFAFQAHAFAKAAQAKAAAHgJQAGgIAAgHQAAgJgDgFQgFgFgJAAIgCAAQgLAAgHAGgAgLAJQgFgEAAgFQAAgHAHgFQAGgEAHAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAAAQABABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAABAAABQAAAAgBABQAAAAgBAAQgBAAgBAAIgBAAIgBAAQgEAAgEACQgFADAAADQAAACAEABIAEACQADAAADgDIAEgCIAEABIABADQgBADgEADQgGADgEAAQgFAAgFgEg");
	this.shape_21.setTransform(-57.7,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.3,-7.1,126.6,16.6);


(lib.blank_gr = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00CCFF").s().p("Aj+CqIAAlTIH9AAIAAFTg");
	this.shape.setTransform(32.5,17,1.275,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,65,34);


(lib.Background = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#009933").ss(4,1,1).p("EAoDAWQMhQFAAAMAAAgsfMBQFAAAg");
	this.shape.setTransform(-2.3,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FED370","#FFFFCC"],[0,1],0,-172,0,172.1).s().p("EgoCAWQMAAAgsfMBQFAAAMAAAAsfg");
	this.shape_1.setTransform(-2.3,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-260.6,-144.4,516.6,288.8);


(lib.goNext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,11.3).s().p("AhLAqQghgRABgYQgBgZAhgRQAfgSAsAAQAsAAAgASQAgARAAAZQAAAYggARQggASgsAAQgsAAgfgSg");
	this.shape.setTransform(22.8,8.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.502)").s().p("AhUhcICpBdIipBcg");
	this.shape_1.setTransform(25.1,20.4);

	this.blinker = new lib.general_buttoncolor();
	this.blinker.parent = this;
	this.blinker.setTransform(23.4,20.1,1.5,1.5,0,0,0,11.9,11.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["rgba(255,255,255,0.961)","rgba(255,255,255,0)","#2B2B2B"],[0,1,1],0,0.1,0,0,0.1,14.8).s().p("AhjA3QgqgXABgfQgBggAqgXQAqgYA5AAQA6AAAqAYQApAXAAAgQAAAfgpAXQgqAYg6AAQg5AAgqgYg");
	this.shape_2.setTransform(23.4,8.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("rgba(0,0,0,0.502)").ss(1,1,1,3,true).p("AAACxQhIAAg0g0Qg1g0AAhJQAAhIA1g0QA0g0BIAAQBKAAA0A0QA0A0AABIQAABJg0A0Qg0A0hKAAg");
	this.shape_3.setTransform(23.3,20.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["rgba(103,103,103,0.839)","rgba(134,134,134,0)"],[0.678,0.918],-0.8,0,0,-0.8,0,24.9).s().p("AitClQhEhFAAhgQAAhgBEhEQBEhEBiAAQBfAABCAwQBBAvAWCrQAVCskNAbQhiAAhEhEgAgICRQBGAAAygwIABgBIAEgDQA0g0AAhIQAAhJg0g0IgGgGIAAAAQgyguhEAAIgBgBIAAAAIgBAAIAAABQhEAAgyAuIgBABIgCACIgCABIAAAAIgBACQg1A0AABJQAABIA1A0IABABIACACQAzAxBGAAIAAAAIABAAIgBAAIAAAAQhGAAgzgxIgCgCIgBgBQg1g0AAhIQAAhJA1g0IABgCIAAAAIACgBIACgCIABgBQAyguBEAAIAAgBIABAAIAAAAIABABQBEAAAyAuIAAAAIAGAGQA0A0AABJQAABIg0A0IgEADIgBABQgyAwhGAAIAAAAIAAAAIAAAAIAAAAg");
	this.shape_4.setTransform(24.2,23.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.blinker},{t:this.shape_1},{t:this.shape}]},2).wait(1));

	// Layer 2
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#33FFFF").s().p("AipCqQhGhHAAhjQAAhiBGhGQBGhHBjAAQBjAABHBHQBGBGAABiQAABjhGBHQhHBGhjAAQhjAAhGhGg");
	this.shape_5.setTransform(24.4,21.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0099FF").s().p("AipCqQhGhHAAhjQAAhiBGhGQBGhHBjAAQBjAABHBHQBGBGAABiQAABjhGBHQhHBGhjAAQhjAAhGhGg");
	this.shape_6.setTransform(24.4,21.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,48.5,46.7);


(lib.blank = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.blank_gr("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(32.6,17,1,1,0,0,0,32.5,17);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.blank, new cjs.Rectangle(0.1,0,65,34), null);


(lib.anim_pro_rock = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.static_pro_rock();
	this.instance.parent = this;
	this.instance.setTransform(0.2,1.4,0.999,0.999,-19.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:40.7,x:0,y:0},6).to({rotation:-19.3,y:1.9},6).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-45.3,-37.8,93.3,78.9);


(lib.anim_pro_dance = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.static_pro_dance();
	this.instance.parent = this;
	this.instance.setTransform(0,-4.1,1,1,-8);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:7,y:0},5).to({rotation:-8,y:-4.1},8).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40.1,-42.5,82,77.6);


(lib.UI = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//Menu button -----------------------------------------
		this.btn_menu.addEventListener("click", openMenu.bind(this));
		
		//volume buttons -----------------------------------------
		this.vol_dwn.addEventListener("click", volDwn.bind(this));
		this.vol_up.addEventListener("click", volUp.bind(this));
		this.vol_mute.addEventListener("click", volMute.bind(this));
		
		//Nav buttons -----------------------------------------
		this.btn_goNext.addEventListener("click", openNext.bind(this));
		//this.btn_goBack.addEventListener("click", openPrev.bind(this));
		
		//background music ---------------------------------------
		var bgm = createjs.Sound.play('bgmPN',{loop:-1});
		
		//volume vars -----------------------------------------
		var mute= false;
		bgm.volume = 0.05;
		var prev_vol = bgm.volume;
		
		//Menu function -----------------------------------------
		function openMenu(){
		
		 window.open ("../miniMenu/miniMenu.html","_self");
		}
		
		//volume functions -----------------------------------------
		function volDwn()
		{
			createjs.Sound.volume = createjs.Sound.volume -0.1;
			if(!mute){
				bgm.volume -= 0.1;
				prev_vol = bgm.volume;
			}
			console.log(bgm.volume);
			console.log(prev_vol);
		}
		function volUp()
		{
			createjs.Sound.volume = createjs.Sound.volume +0.1;
			if(!mute){
				bgm.volume += 0.1;
				prev_vol = bgm.volume;
			}
			console.log(bgm.volume);
			console.log(prev_vol);
		}
		
		function volMute()
		{
			if(!mute){
				mute = true
				bgm.volume = 0;
			}
			else{
				mute = false;
				bgm.volume = prev_vol;
			}
			console.log(mute);
		}
		
		
		//Nav functions -----------------------------------------
		
		function openNext(){
		
		 window.open ("predNoun_scene2.html","_self");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// mute
	this.vol_mute = new lib.vol_mute();
	this.vol_mute.parent = this;
	this.vol_mute.setTransform(31.8,2.1,1,1,0,0,0,15,14.1);
	new cjs.ButtonHelper(this.vol_mute, 0, 1, 2, false, new lib.vol_mute(), 3);

	this.timeline.addTween(cjs.Tween.get(this.vol_mute).wait(1));

	// main
	this.instance = new lib.Copyright("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-220.6,376.5);

	this.btn_goNext = new lib.goNext();
	this.btn_goNext.parent = this;
	this.btn_goNext.setTransform(-1.7,335.3);
	new cjs.ButtonHelper(this.btn_goNext, 0, 1, 2, false, new lib.goNext(), 3);

	this.vol_up = new lib.vol_pos();
	this.vol_up.parent = this;
	this.vol_up.setTransform(-6.7,2.6,1,1,0,0,0,9,7);
	new cjs.ButtonHelper(this.vol_up, 0, 1, 2, false, new lib.vol_pos(), 3);

	this.vol_dwn = new lib.vol_neg();
	this.vol_dwn.parent = this;
	this.vol_dwn.setTransform(-28.7,2.6,1,1,0,0,0,9,7);
	new cjs.ButtonHelper(this.vol_dwn, 0, 1, 2, false, new lib.vol_neg(), 3);

	this.btn_menu = new lib.menu_main();
	this.btn_menu.parent = this;
	this.btn_menu.setTransform(-89.6,2.6,1,1.143,0,0,0,23.4,10.5);
	new cjs.ButtonHelper(this.btn_menu, 0, 1, 2, false, new lib.menu_main(), 3);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1.5,1,1).p("AAYBrQgBgLgUgUQgQgRgKAAIAAh1QAKAAASgTQATgTAAgKg");
	this.shape.setTransform(-47.7,2.3,0.687,0.681);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AADBMQgQgRgKAAIAAh1QAKgBASgSQATgTAAgJIAADTQgBgKgUgUg");
	this.shape_1.setTransform(-47.7,2.3,0.687,0.681);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s("#000000").ss(1.5,1,1).rr(-0.75,-3.45,1.5,6.9,0.2);
	this.shape_2.setTransform(-52.2,2.3,1,1.003);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1.5,1,1).p("AAHAAQAAAJgHAHQgCAEgEACIAAgrQAEACACAEQACACACACQADAFAAAGg");
	this.shape_3.setTransform(-43.2,2.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgGgUQAEABACAEIABAAIADAFQADAEAAAGQAAAJgGAHIgBAAQgCAEgEABg");
	this.shape_4.setTransform(-46.5,2.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.btn_menu},{t:this.vol_dwn},{t:this.vol_up},{t:this.btn_goNext},{t:this.instance}]}).wait(1));

	// vol_frame
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s("#000000").ss(1.5,1,1).rr(-33,-12,66,24,4.9);
	this.shape_5.setTransform(-24.7,2.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_5).wait(1));

}).prototype = getMCSymbolPrototype(lib.UI, new cjs.Rectangle(-283.9,-13,331.7,399), null);


(lib.predicateNoun_intro = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// characters
	this.instance = new lib.anim_pro_rock();
	this.instance.parent = this;
	this.instance.setTransform(639.3,216.8);

	this.instance_1 = new lib.anim_pro_dance();
	this.instance_1.parent = this;
	this.instance_1.setTransform(139.1,181.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance}]},49).to({state:[{t:this.instance}]},1).to({state:[{t:this.instance}]},29).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance}]},66).to({state:[{t:this.instance}]},14).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:44.1,y:221.8},49).wait(1).to({skewY:180,x:18.1,y:213.8},0).to({x:129.8,y:177.2},29).to({_off:true},1).wait(66).to({_off:false,skewY:0},0).to({x:19.8,y:201.2},14).wait(1));

	// title
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0099FF").s().p("Ah1CAQgFgHAAgJIABgUIABgUIAAgeIABgdIAAgfIgBgfIgCgeIgCgeQAAgKAIgHQAJgIALAAQAMAAAPAVQBLBsBJBCIAAgZQAAhRgBgcIgDgSIgCgSQAAgXAYAAQAcAAAABTIgBAaIAABoQAAAJgDASQgEAVgVAAQgLAAgPgNQhAg6hPhnIgBA0IAAAoIABAnQAAAxgYAAQgMAAgIgHg");
	this.shape.setTransform(521.4,22.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0099FF").s().p("AhCByQgsgjAAhSIABgYIABgYIAAgTIABgTQAAgMAEgMQAHgPALAAQAKAAAHAFQAHAGAAAKIAAAcIAAAcIgBAYIgBAYQAAAYAGAWQAHAaANAKQAHAFAbAAQAqABAQhMQAIglAAhHQAAgJAFgJQAIgLANAAQAMgBAFAJQAFAGAAAHQAABCgGAlQgKA4gbAlQgMAQgRALQgVANgVAAQgrAAgUgPg");
	this.shape_1.setTransform(494.8,23);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0099FF").s().p("AhXBnQgmgfAAgwQAAg3AkguQAog1A7AAQA5AAAdAbQAdAaAAA2QABA3ghAuQgmA1g7AAQgxAAgigcgAg1gxQgYAiAAAnQAAAcAVARQAUARAgAAQAjAAAZgkQAXghgBgoQABgjgRgOQgOgNgmAAQglAAgaAkg");
	this.shape_2.setTransform(468.8,22.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0099FF").s().p("Ah1CAQgFgHgBgJIABgUIACgUIAAgeIABgdIAAgfIgBgfIgCgeIgCgeQAAgKAIgHQAJgIALAAQAMAAAPAVQBKBsBKBCIAAgZQAAhRgBgcIgDgSIgCgSQAAgXAZAAQAbAAAABTIAAAaIgBBoQAAAJgEASQgDAVgUAAQgMAAgPgNQg/g6hQhnIgBA0IABAoIAAAnQAAAxgYAAQgMAAgIgHg");
	this.shape_3.setTransform(441.5,22.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0099FF").s().p("AhNB/QgSgQAAg2QAAgWAEgrQADguAAgWIgCgRIgBgRQAAgZAXAAQAHAAAGAEQATgFASgCQARgCAPgBQApAAAZAKQAQAGAAAPQAAAJgGAGQgHAIgKAAIgHgBQgbgHgZAAQgNAAgNACIgfAGIgBBBIBAgFIAogEQAKAAAHAHQAHAFAAALQAAATgVACIgoAEIhGAGIgBAiQAAAgAEAFQABACAUAAIAeAAIAfgBIAJgBIAKgBQAKABAHAFQAHAGAAALQAAASgTAEQgRADgzAAQg2AAgRgOg");
	this.shape_4.setTransform(402.7,22.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0099FF").s().p("AgPB5QgIgHAAgKIABgGIABgIIgBgXIgCgXQAAgWgDglIgEg9IgJAAQglAAgWgFQgTgEABgSQgBgIAHgHQAGgIAMABIAbADIAaABIAeAAIAdAAIAnACIAlABQAKAAAHAHQAHAGgBAKQABAJgHAHQgHAGgKAAIgogCIgogBQAAATAEAwQAEAqAAAZIABARIABAQQAAANgGAKQgGANgNAAQgIAAgHgGg");
	this.shape_5.setTransform(380,22.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0099FF").s().p("ABVB9QgOAAgNgfQgIgTgHgaQgNACgbACQgaACgOACQgHASgTAlQgHAMgNAAQgJAAgIgGQgHgGAAgKQAAgIAYgxQgCgGABgEQAAgIAQgFQAXgnAdgsQAog/AKAAQASAAAHAWIAKA1IAZBtIAIAWQAGAOAAAHQAAAKgHAGQgHAGgIAAIgBAAgAgMAPIAWgCIAXgCIgKg3IgjA7g");
	this.shape_6.setTransform(355.4,22.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0099FF").s().p("AhJBmQgZgbAAgjQAAg3Awg6QAqgxAqAAIANABIAKABQAIgHAKgBQARAAAEAUQADAOAAATQAAAIgFAGQgHAJgLAAQgPAAgHgPQgDgHgEgCQgDgBgKAAQgVAAgbAgQgmAtABAoQgBARAMANQAMAOASAAQAPAAARgJIAZgQQANgJAGAAQALAAAGAIQAHAGAAAJQAAAKgIAHQguAnguAAQgmAAgZgbg");
	this.shape_7.setTransform(332.9,22.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0099FF").s().p("AhOB5QgGgHAAgJQgBgJAIgHQAGgHALAAQAMAAAUgCIgBhLQAAgtADgpIgkABQgJAAgHgGQgGgHAAgJQAAgKAGgGQAGgGAIgBQAOgBAkAAQAeAAAyAHQAUADAAAUQgBALgHAFQgHAGgIAAQgHAAgkgFQgDAfAAAxIAABLIAtAAQAKgBAHAHQAGAGABAKQgBAJgGAHQgHAHgKAAIgdAAIgcAAQgKAAgXADQgWADgLAAQgKAAgHgGg");
	this.shape_8.setTransform(312.7,22.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0099FF").s().p("AgzCGQgTgFgLgGQgKgBgHgGQgHgHAAgJIACgxIACgzIgBg2IgBg3QAAgJAJgJQAJgJAKAAQAFAAAWAKIAfAOQAvAQAjAgQApAoAAAvQAAAcgOAaQgOAagZAQQgcATgwgBQgNAAgPgDgAg5BVQAGAEAJACQAIACAKAAQAjAAAQgKQAPgKAIgQQAJgQAAgSQAAgogwgeQgPgKg1gWg");
	this.shape_9.setTransform(291.9,22.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#0099FF").s().p("AhNB/QgSgQAAg2QAAgWAEgrQADguAAgWIgCgRIgBgRQAAgZAXAAQAHAAAGAEQATgFASgCQARgCAPgBQApAAAZAKQAQAGAAAPQAAAJgGAGQgHAIgKAAIgHgBQgbgHgZAAQgNAAgNACIgfAGIgBBBIBAgFIAogEQAKAAAHAHQAHAFAAALQAAATgVACIgoAEIhGAGIgBAiQAAAgAEAFQABACAUAAIAeAAIAfgBIAJgBIAKgBQAKABAHAFQAHAGAAALQAAASgTAEQgRADgzAAQg2AAgRgOg");
	this.shape_10.setTransform(268.8,22.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#0099FF").s().p("AhaB8QgGgHAAgJIAAglIAAgmIAAiFQAAgKAHgJQAIgLAPABIAqADQAXADAPAIQBHAkAAA1QAAAVgPAQQgPARgdALQArAZAXAZQAFAHABAIQgBAJgGAHQgIAHgJAAQgJAAgIgHQgygvg7gTIACA2QAAAJgHAHQgHAHgKAAQgJAAgHgHgAgzAFIAIAAQAoAAASgJQAJgFAHgHQAHgHAAgDQAAgTgYgRQgUgRgagCIgTgBg");
	this.shape_11.setTransform(247.3,22.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#0099FF").s().p("AhKB+QgHgGAAgJIAAguQAAgaAEgxQADg0AAgZQAAgrAYABQAGgBAKgBIAYgBQAfAAAdAWQAgAYAAAhQAAAqgiAZQgeAWgoAAIgOgBIgBBMQAAAJgGAGQgGAHgKAAQgJAAgGgHgAgehYIAAAYIgDA5IALABQAZAAARgMQASgNAAgWQAAgOgRgLQgQgKgTAAIgJAAIgHAAg");
	this.shape_12.setTransform(227,21.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AhNB/QgSgQAAg2QAAgWAEgrQADguAAgWIgCgRIgBgRQAAgZAXAAQAHAAAGAEQATgFASgCQARgCAPgBQApAAAZAKQAQAGAAAPQAAAJgGAGQgHAIgKAAIgHgBQgbgHgZAAQgNAAgNACIgfAGIgBBBIBAgFIAogEQAKAAAHAHQAHAFAAALQAAATgVACIgoAEIhGAGIgBAiQAAAgAEAFQABACAUAAIAeAAIAfgBIAJgBIAKgBQAKABAHAFQAHAGAAALQAAASgTAEQgRADgzAAQg2AAgRgOg");
	this.shape_13.setTransform(193,22.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("ABHB+QgIgGAAgJIgBgkIgBglIABgQQgaABgmAHIhAAMIgCAjIgBAjQAAAJgHAGQgGAGgKAAQgKAAgGgHQgHgGAAgJQAAgQADghQADggAAgQIABg+IABg+QAAgJAHgHQAGgGAKAAQAJAAAHAHQAGAGAAAJIgBAmIgBAmIgBAQIgBARIBAgMQAlgHAbgBIACg8QAAgNAIgRQAJgVAMAAQAIAAAHAGQAIAGAAAKIgBAFQgDAMAAAJIgBAPIgBAOIgCAvIgCAuIACAkIACAlQAAAJgGAGQgHAHgJAAQgKAAgHgHg");
	this.shape_14.setTransform(169.2,22.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgPB5QgIgHAAgKIABgGIABgIIgBgXIgBgXQgBgWgDglIgFg9IgIAAQglAAgWgFQgSgEgBgSQABgIAFgHQAIgIALABIAaADIAbABIAeAAIAeAAIAlACIAmABQAKAAAHAHQAGAGABAKQgBAJgGAHQgHAGgKAAIgogCIgpgBQABATAEAwQADAqAAAZIABARIACAQQAAANgFAKQgIANgMAAQgIAAgHgGg");
	this.shape_15.setTransform(144.1,22.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(161));

	// Layer 1
	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgNALQgFgFAAgFQAAgGAFgFQAGgFAHAAQAIAAAGAFQAFAFAAAGQAAAFgGAFQgFAFgIAAQgHAAgGgFg");
	this.shape_16.setTransform(486.6,208.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgKBSQgFgFAAgGIAAgNIAAgMIgCg8IgVgCQgPgBAAgOQAAgHAFgEQAEgFAHAAIAUACIgBgNIAAgLQgBgHAGgEQAFgFAGAAQARAAAAAdIAAAKIALgBQAOAAAEACQAKADAAALQAAAHgEAEQgGAEgHABIgFAAIgGAAIgLABIACA8IAAAGIAAAGQAAAbgRAAQgFAAgFgDg");
	this.shape_17.setTransform(475.8,201.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgkAzQgSgPAAgZQAAgXAQgZQATgcAYAAQAMAAAQAHQAUAIAAAKQAAAGgEAEQgEAFgHAAQgFAAgHgFQgHgGgOAAQgIAAgLASQgKARAAAMQAAAMAJAHQAIAHANgBQAIAAAMgFQALgHADAAQAHABAEAEQAEAEABAHQgBAIgTAKQgTAIgLAAQgYAAgSgPg");
	this.shape_18.setTransform(463.7,203.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgnAyQgUgOAAgbQAAgcAQgVQARgXAdAAQATAAAOAHQASAJAAARQAAAOgOAKQgHAEgUAIIgmARQAFAHAIADQAIACAJAAQAQABALgHQAKgGAGAAQAMAAAAAMQAAAOgUAIQgQAHgTAAQgbAAgRgOgAgPgcQgIAIgFAPIAagMQAPgHAKgGQgIgFgMAAQgLABgHAGg");
	this.shape_19.setTransform(450.9,203.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgpBTQgCgEAAgEQAAgGAFgFQAFgEAHAAQAHAAAGAIIAJAPQAEAIAEAAQAGAAACgQQAAgNgEg0IgEg+QAAgHAEgFQAFgHAHAAQAGAAAFAEQAGAEAAAFIAEBAIADBGQAAARgKAOQgMAQgSAAQgbAAgSgogAAFhcQgFgFAAgHQAAgHAFgFQAFgGAHAAQAIAAAFAGQAGAFAAAHQAAAHgGAFQgFAFgIAAQgHAAgFgFg");
	this.shape_20.setTransform(438.4,203.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgiBZQgFAEgFAAQgHAAgEgEQgFgEAAgGIAAgJIABgJIAAiDQAAgJAEgGQAEgJAJAAQANAAAAAOIgBAFIAAAFIAAAsIAQgHQAIgCAGAAQAcAAARAUQAQASAAAaQAAAbgSATQgTAUgbAAQgQAAgPgGgAgMgCQgJADgJAHIAAAyQAPAHAMAAQAOAAAJgKQAKgKAAgQQAAgPgHgKQgJgJgOAAQgEAAgIADg");
	this.shape_21.setTransform(427.6,200.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AAXA6QgPAFgOAAQgRAAgLgHQgNgIgDgPQgEgdgBgWQAAgPAEgUQACgNAOAAQAHAAAFAEQAEAEAAAHIgBAQIgCARIABAbIAEAVIAFACIAGAAQAMAAAPgDIAAgVIAAgTQAAgYACgRQACgOAOAAQAHAAAFAEQAEAFABAGIgDAqIAAAWIABAYIAAAHIAAAIQAAAGgFAEQgEAFgHAAQgKAAgFgJg");
	this.shape_22.setTransform(414.1,203.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AggA9QgSgGAAgNQAAgMAOAAQAFAAAKAEQALADAFAAQAXAAAAgJQAAgHgQgHQgYgKgGgEQgQgMAAgQQAAgYAYgIQAPgFAcAAQAMAAAGADQAIAEAAALQAAAVgLAAQgMAAgDgJIgJgBQgbAAgBAIQABAEAQAIQAXAKAIAGQARAMAAAPQAAAUgTAKQgPAJgVAAQgQAAgMgFg");
	this.shape_23.setTransform(402,203.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgoAyQgTgOAAgbQAAgcAQgVQARgXAdAAQATAAAOAHQASAJAAARQAAAOgPAKQgGAEgUAIIgmARQAFAHAIADQAIACAJAAQAQABALgHQAKgGAGAAQAMAAAAAMQAAAOgUAIQgQAHgTAAQgbAAgSgOgAgPgcQgIAIgFAPIAagMQAQgHAJgGQgIgFgMAAQgLABgHAGg");
	this.shape_24.setTransform(379,203.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AAbBWQgDgKgCgRQgCgQAAgLIAAgJIABgJIgBgKQgBgFgFgBQgNABgJAKQgGAHgJAQQAAArgEAIQgFAKgKAAQgGAAgFgFQgFgEAAgHIABgGQABgCAAgdIAAhOIABgDIAAgTIgBgLIgBgLQAAgGAFgEQAFgEAHAAQALAAAEAMQACAGAAAPIAAAYIgBAXQAJgJAJgEQAJgEALAAQAUAAAJAMQAHAHABARIABAdIADAXIAEAXIAAAEQAAAGgFAFQgFAFgGgBQgMABgEgMg");
	this.shape_25.setTransform(365.8,200.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgKBSQgFgFAAgGIAAgNIAAgMIgBg8IgXgCQgOgBAAgOQAAgHAEgEQAFgFAHAAIAUACIgBgNIAAgLQAAgHAEgEQAFgFAHAAQAQAAAAAdIAAAKIAMgBQANAAAGACQAJADAAALQAAAHgFAEQgFAEgGABIgGAAIgGAAIgLABIACA8IAAAGIABAGQAAAbgRAAQgGAAgFgDg");
	this.shape_26.setTransform(353,201.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AghA9QgRgGAAgNQAAgMAOAAQAFAAALAEQAKADAGAAQAWAAAAgJQAAgHgRgHQgWgKgHgEQgRgMAAgQQAAgYAZgIQAPgFAdAAQAMAAAFADQAIAEAAALQAAAVgMAAQgLAAgCgJIgKgBQgbAAAAAIQAAAEAPAIQAYAKAIAGQARAMAAAPQAAAUgSAKQgQAJgVAAQgQAAgNgFg");
	this.shape_27.setTransform(330.9,203.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgoAyQgTgOAAgbQAAgcAQgVQARgXAdAAQATAAAOAHQASAJAAARQAAAOgPAKQgGAEgUAIIgmARQAFAHAIADQAIACAJAAQAQABALgHQAKgGAGAAQAMAAAAAMQAAAOgUAIQgQAHgTAAQgaAAgTgOgAgPgcQgIAIgEAPIAZgMQAQgHAJgGQgIgFgMAAQgLABgHAGg");
	this.shape_28.setTransform(318.4,203.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgJBEQgFgFAAgGQAAgOgDgaQgDgZAAgNQAAgHgBgFQgOAIgNASIgCADIgBAkIAAAJIAAAIQAAAGgFAEQgFADgHAAQgKAAgEgIQgCgGAAgNIAAgrIAAgRIgBgRQAAgKAEgJQAEgKAJAAQAGAAAFAFQAGAFAAAGIgBAKQARgUAQAAQASAAAIANQAHgGAIgDQAJgDAKAAQAXAAAIAWIAFAgQAEASAFAsQAAAHgFAEQgFAFgHAAQgNAAgCgOQgDgMgCgWIgEghQgDgVgFAAQgCAAgKAGQgKAFgEAEQAAANADAYQADAaAAANQAAAGgEAFQgFAEgHAAQgGAAgEgEg");
	this.shape_29.setTransform(302.7,203.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AAcA2IgTAIQgIADgFgBQgcABgOgQQgOgPAAgeQAAgbAVgUQAVgVAcABQALAAAOAGQASAIAAAJQAAAFgDACIgBANIgBAQQAAAVADAKIAFAMIAFALQAAAGgFAFQgEADgHAAQgFAAgMgKgAgQgXQgMANAAAPQAAAQAGAHQAGAJALgBQAGAAAHgCQAGgCAGgFQgEgbAAgOIABgIIABgLIgEgBIgDgBQgPAAgMAMg");
	this.shape_30.setTransform(286.6,203.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AAYA2IgDgYQgCgNAAgMIAAgJIABgKIAAgFIAAgFQAAgKgEAAQgLAAgIANQgKANgFATIgBAKIgBALIgBAKIAAAKQAAAHgFAFQgFAEgHAAQgHAAgEgEQgFgFAAgHIgBgKIAAgKIABggIACgfIAAgKIgBgLQAAgHAFgEQAFgEAHAAQAPAAABASIAAABQARgRASAAQAWAAAJATQAFAMAAAZIAAAIIAAAHQAAAJADAOQACAPAAAJQAAAGgEAFQgFAEgHAAQgOAAgCgOg");
	this.shape_31.setTransform(273.7,203.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgoAyQgTgOAAgbQAAgcAQgVQARgXAcAAQAVAAANAHQASAJAAARQAAAOgPAKQgGAEgUAIIgmARQAFAHAIADQAIACAJAAQAQABALgHQAKgGAFAAQANAAAAAMQAAAOgUAIQgQAHgTAAQgaAAgTgOgAgPgcQgIAIgEAPIAagMQAOgHAKgGQgIgFgNAAQgJABgIAGg");
	this.shape_32.setTransform(260.4,203.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AguA9QgDgEAAgHIAAhMIAAgKIAAgLQAAgHAEgEQAEgFAIAAQANAAACAOQATgQAaAAQAYAAAAAfIgBAIQgBASgPAAQgPAAAAgPIgBgMQgZAEgLAXIAAA6QAAAHgEAEQgFAFgIAAQgGAAgFgFg");
	this.shape_33.setTransform(248.3,203.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgKBSQgFgFAAgGIAAgNIAAgMIgBg8IgWgCQgPgBAAgOQAAgHAEgEQAFgFAHAAIAUACIgBgNIAAgLQAAgHAEgEQAGgFAGAAQAQAAABAdIAAAKIALgBQAOAAAFACQAJADAAALQAAAHgFAEQgEAEgIABIgFAAIgGAAIgLABIACA8IAAAGIABAGQgBAbgRAAQgFAAgFgDg");
	this.shape_34.setTransform(226.3,201.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAcA2IgTAIQgIADgFgBQgcABgOgQQgOgPAAgeQAAgbAVgUQAVgVAcABQALAAAOAGQASAIAAAJQAAAFgDACIgBANIgBAQQAAAVADAKIAFAMIAFALQAAAGgFAFQgEADgHAAQgFAAgMgKgAgQgXQgMANAAAPQAAAQAGAHQAGAJALgBQAGAAAHgCQAGgCAGgFQgEgbAAgOIABgIIABgLIgEgBIgDgBQgPAAgMAMg");
	this.shape_35.setTransform(214,203.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AAbBWQgDgKgCgRQgCgQAAgLIAAgJIABgJIgBgKQgBgFgFgBQgNABgJAKQgGAHgJAQQAAArgEAIQgFAKgKAAQgGAAgFgFQgFgEAAgHIABgGQABgCAAgdIAAhOIABgDIAAgTIgBgLIgBgLQAAgGAFgEQAFgEAHAAQALAAAEAMQACAGAAAPIAAAYIgBAXQAJgJAJgEQAJgEALAAQAUAAAJAMQAHAHABARIABAdIADAXIAEAXIAAAEQAAAGgFAFQgFAFgGgBQgMABgEgMg");
	this.shape_36.setTransform(200.6,200.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgKBSQgFgFAAgGIAAgNIAAgMIgCg8IgVgCQgPgBAAgOQAAgHAFgEQAEgFAHAAIAUACIgBgNIgBgLQAAgHAGgEQAFgFAGAAQARAAAAAdIAAAKIALgBQAOAAAEACQAKADAAALQAAAHgEAEQgGAEgHABIgFAAIgGAAIgLABIACA8IAAAGIAAAGQAAAbgRAAQgFAAgFgDg");
	this.shape_37.setTransform(187.8,201.4);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FF0000").s().p("AgiBZQgFAEgFAAQgHAAgEgEQgFgEAAgGIAAgJIABgJIAAiDQAAgJAEgGQAEgJAJAAQAMAAAAAOIAAAFIgBAFIAAAsIARgHQAIgCAHAAQAbAAARAUQAQASAAAaQAAAbgSATQgTAUgbAAQgQAAgPgGgAgNgCQgHADgLAHIAAAyQARAHALAAQAOAAAJgKQAKgKAAgQQAAgPgIgKQgIgJgNAAQgGAAgIADg");
	this.shape_38.setTransform(490.8,164.7);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FF0000").s().p("AgtA9QgFgEAAgHIAAhMIABgKIAAgLQAAgHAEgEQAEgFAIAAQANAAACAOQAUgQAZAAQAXAAAAAfIAAAIQgBASgPAAQgPAAAAgPIAAgMQgaAEgLAXIAAA6QAAAHgFAEQgEAFgHAAQgIAAgDgFg");
	this.shape_39.setTransform(478.1,167.9);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FF0000").s().p("AgoAyQgTgOAAgbQAAgcAPgVQASgXAcAAQAVAAANAGQASAKAAARQAAANgPALQgGAEgUAIIgmARQAFAGAIADQAIADAKAAQAPABALgHQAKgGAFAAQANAAAAAMQAAAOgUAIQgQAHgSAAQgcAAgSgOgAgQgcQgHAIgEAPIAagMQAOgHAKgGQgIgFgNABQgJAAgJAGg");
	this.shape_40.setTransform(465.3,167.9);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FF0000").s().p("AgZBTQgOgigSg/IgJggQgHgWAAgIQAAgHAFgFQAFgEAHAAQALAAAFAMIAEAUIALAmQAJAgAJAaIAahGIALgcQAHgRAIgJQAFgGAHAAQAHAAAFAFQAFAFAAAGQAAAFgDAFQgHAJgFANIgIAXIggBQQgFAOgIAOQgFAKgJAAQgMAAgFgMg");
	this.shape_41.setTransform(450.7,165.2);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FF0000").s().p("AgoAyQgTgOAAgbQAAgcAQgVQARgXAdAAQATAAAOAGQASAKAAARQAAANgOALQgHAEgUAIIgmARQAFAGAIADQAIADAJAAQAQABALgHQAKgGAGAAQAMAAAAAMQAAAOgUAIQgQAHgTAAQgbAAgSgOgAgPgcQgIAIgFAPIAagMQAPgHAKgGQgIgFgMABQgLAAgHAGg");
	this.shape_42.setTransform(425.3,167.9);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FF0000").s().p("AgkAzQgSgPgBgZQABgXAQgZQATgcAYAAQAMAAAQAHQAUAHAAALQAAAGgEAEQgEAFgHAAQgFAAgHgGQgHgFgOAAQgIAAgKASQgLARAAAMQAAAMAJAHQAIAHANAAQAIgBALgFQAMgHADAAQAGABAFAEQAEAFABAGQgBAJgTAJQgTAIgLAAQgZAAgRgPg");
	this.shape_43.setTransform(412.3,167.9);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FF0000").s().p("AAYA2IgDgYQgCgNAAgMIAAgJIABgKIAAgFIAAgFQAAgKgEAAQgLAAgIANQgKANgFATIgBAKIgBALIgBAKIAAAKQAAAHgFAFQgFAEgHAAQgHAAgEgEQgFgFAAgHIgBgKIAAgKIABggIACgfIAAgKIgBgLQAAgHAFgEQAFgEAHAAQAPAAABASIAAABQARgRASAAQAWAAAJATQAFAMAAAZIAAAIIAAAHQAAAJADAOQACAPAAAJQAAAGgEAFQgFAEgHAAQgOAAgCgOg");
	this.shape_44.setTransform(400.2,167.7);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FF0000").s().p("AgoAyQgTgOAAgbQAAgcAQgVQARgXAcAAQAVAAANAGQASAKAAARQAAANgPALQgGAEgUAIIgnARQAGAGAIADQAIADAKAAQAPABALgHQAKgGAFAAQANAAAAAMQAAAOgUAIQgQAHgSAAQgcAAgSgOgAgQgcQgHAIgEAPIAagMQAOgHAKgGQgIgFgNABQgKAAgIAGg");
	this.shape_45.setTransform(387,167.9);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FF0000").s().p("AgKBSQgFgEAAgHIAAgNIAAgMIgCg8IgVgCQgPgCAAgNQAAgHAEgEQAFgFAHAAIAUACIgBgNIAAgMQAAgGAEgEQAGgFAGAAQAQAAABAeIAAAJIALgBQANAAAGACQAJADAAALQAAAHgFAEQgEAEgIABIgFAAIgGAAIgLAAIACA9IAAAGIABAGQgBAbgQAAQgGAAgFgDg");
	this.shape_46.setTransform(374.8,165.9);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FF0000").s().p("AghA9QgRgGAAgNQAAgMAOAAQAGAAAKAEQAKADAFAAQAXAAAAgJQAAgGgRgIQgWgKgHgEQgQgMAAgQQgBgYAZgIQAPgFAdAAQALAAAGADQAIAEAAALQAAAVgMAAQgLAAgCgJIgKgBQgcgBAAAJQAAAEAQAIQAYAKAIAGQARAMAAAPQAAAVgSAJQgQAJgVAAQgPAAgOgFg");
	this.shape_47.setTransform(363.1,167.8);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FF0000").s().p("AgOBVQgFgEAAgHIAAgVIAAgWIABgaIABgZQAAgHAEgFQAFgEAHAAQAGAAAFAEQAEAFAAAHIgBAZIgBAaIAAAWIABAVQAAAHgFAEQgEAEgGABQgHgBgFgEgAgKg7QgGgFAAgHQAAgHAGgFQAFgGAHAAQAHAAAGAGQAFAFAAAHQAAAHgFAFQgGAFgHAAQgHAAgFgFg");
	this.shape_48.setTransform(354.3,165.1);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FF0000").s().p("AAhA+IgigqIgdAcIgKAJQgFAFgHAAQgGAAgFgEQgEgFAAgGQAAgHAJgJIAPgNIAXgVIgOgSQgIgLgGgGQgHgFAAgGQAAgGAFgFQAEgFAHAAQAJAAAOARIARAYIAVgRQAMgKAGgIQAFgHAHAAQAHAAAEAEQAGAFAAAGQgBAHgLAMIgSAPIgSARIAkArQAEAEAAAFQAAAGgFAFQgFAEgHAAQgGAAgFgFg");
	this.shape_49.setTransform(343.6,167.5);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FF0000").s().p("Ag1BaQgOgMAAgmQAAgPADgfIACgvIgBgMIgBgMQAAgSAQAAQAFAAAFADIAZgFIAWgCQAeAAASAHQALAEgBALQAAAGgEAFQgEAFgHAAIgGgBQgTgFgSAAIgRACQgLABgKADIgCAuIAtgEIAdgCQAHAAAEAEQAFAEAAAIQAAANgOABIgcADIgyAEIgBAYQABAXACADQACACANAAIAUAAIAXgBIAHAAIAGgBQAHAAAFAEQAGAEgBAIQAAANgNADQgMACgkAAQgmAAgLgKg");
	this.shape_50.setTransform(329.4,164.9);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("AAYA2IgDgYQgCgNAAgMIAAgJIABgKIAAgFIAAgFQAAgKgEAAQgLAAgIANQgKANgFATIgBAKIgBALIgBAKIAAAKQAAAHgFAFQgFAEgHAAQgHAAgEgEQgFgFAAgHIgBgKIAAgKIABggIACgfIAAgKIgBgLQAAgHAFgEQAFgEAHAAQAPAAABASIAAABQARgRASAAQAWAAAJATQAFAMAAAZIAAAIIAAAHQAAAJADAOQACAPAAAJQAAAGgEAFQgFAEgHAAQgOAAgCgOg");
	this.shape_51.setTransform(305,167.7);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#000000").s().p("AAcA2IgTAIQgIADgFgBQgcABgOgPQgOgQAAgeQAAgbAVgUQAVgVAcABQALAAAOAGQASAIAAAKQAAADgDADIgBANIgBAQQAAAVADAKIAFAMIAFALQAAAGgFAFQgEADgHAAQgFAAgMgKgAgQgXQgMANAAAPQAAAQAGAHQAGAJALgBQAGABAHgDQAGgCAGgFQgEgbAAgOIABgIIABgLIgEgCIgDAAQgPAAgMAMg");
	this.shape_52.setTransform(292,167.9);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#000000").s().p("Ag7BLQAAgGADgEQAFgFAHAAIAOACQAKADAIAAQAQAAAJgLQAIgLABgWQgFAGgIADQgIADgHAAQgYAAgOgPQgPgQAAgWQAAggATgUQAVgUAhAAQALAAAIACQAHADAGAGQAOABAAAQQAAAJgCANQgFAbgBAeQgBAmgMARQgPAXgmAAQgtAAAAgSgAgRg0QgKALAAATQAAAPAFAGQAGAHAKgBQAIABAKgKQAKgLABgKIAFgjIgIgEQgEgBgEgBQgSABgLANg");
	this.shape_53.setTransform(268.3,171);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#000000").s().p("AAYA2IgDgYQgCgNAAgMIAAgJIABgKIAAgFIAAgFQAAgKgEAAQgLAAgIANQgKANgFATIgBAKIgBALIgBAKIAAAKQAAAHgFAFQgFAEgHAAQgHAAgEgEQgFgFAAgHIgBgKIAAgKIABggIACgfIAAgKIgBgLQAAgHAFgEQAFgEAHAAQAPAAABASIAAABQARgRASAAQAWAAAJATQAFAMAAAZIAAAIIAAAHQAAAJADAOQACAPAAAJQAAAGgEAFQgFAEgHAAQgOAAgCgOg");
	this.shape_54.setTransform(255.9,167.7);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#000000").s().p("AgOBVQgFgEAAgHIAAgVIAAgWIABgaIABgZQAAgHAEgFQAFgEAHAAQAGAAAFAEQAEAFAAAHIgBAZIgBAaIAAAWIABAVQAAAHgFAEQgEAEgGABQgHgBgFgEgAgKg7QgGgFAAgHQAAgHAGgFQAFgGAHAAQAHAAAGAGQAFAFAAAHQAAAHgFAFQgGAFgHAAQgHAAgFgFg");
	this.shape_55.setTransform(246.4,165.1);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#000000").s().p("AAEAlQgDgLgDgcIgDAGIgSAtQgCAFgDADQgFAIgKAAQgGAAgGgKQgGgKgEgQQgEgOgHgwIgCgRQAAgGAFgEQAFgFAGAAQANAAADANIADAQIABAQIAFAdIAUg6QAFgPAMAAQANAAAEARIAGAfIAGAgIAThGQACgLAMAAQAHAAAFAFQAFAEAAAHIAAADQgNAugMAkQgEALgIALQgFAIgKAAQgOAAgJgdg");
	this.shape_56.setTransform(234.7,168.1);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#000000").s().p("AgmAxQgRgQgBgbQgBgZAPgUQASgYAfAAQAXAAAOASQANARAAAZQAAAbgPATQgQAVgbAAQgVAAgQgPgAgQgTQgHALAAAOQAAAOAIAHQAGAGAIAAQAKAAAHgHQAJgIAAgNQACglgVAAQgOAAgIANg");
	this.shape_57.setTransform(220,168);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#000000").s().p("AgKBcQgFgFAAgGIAAihQAAgIAFgDQAFgFAFAAQAHAAAFAFQAEADAAAIIAACaQAAAXgQAAQgGAAgEgFg");
	this.shape_58.setTransform(210.4,164.6);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#000000").s().p("AgKBcQgFgFAAgGIAAihQAAgIAFgDQAFgFAFAAQAHAAAFAFQAEADAAAIIAACaQAAAXgQAAQgGAAgEgFg");
	this.shape_59.setTransform(203.9,164.6);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#000000").s().p("AgmAxQgRgQgBgbQgBgZAPgUQASgYAfAAQAXAAAOASQANARAAAZQAAAbgPATQgQAVgbAAQgVAAgQgPgAgQgTQgHALAAAOQAAAOAIAHQAGAGAIAAQAKAAAHgHQAJgIAAgNQACglgVAAQgOAAgIANg");
	this.shape_60.setTransform(194.3,168);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#000000").s().p("AgWBjQgEgEAAgHIAAgDQACgRABgOIAAg6IgIABIgHABQgHAAgFgFQgEgEgBgHQAAgLAMgDQAFgCAQAAIABgNQADgaAMgNQAMgQAcAAQAVAAABAPQgBAPgTAAQgPAAgGAKQgFAIgBAQIgBADIAWgCQAXAAgBAPQAAAQgXgBIgWABIgBAfIABAfQAAAWgDAMQgCANgMAAQgHAAgFgEg");
	this.shape_61.setTransform(181.9,165.3);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#000000").s().p("AgJBEQgFgFAAgGQAAgOgDgaQgDgZAAgNQAAgHgBgFQgOAIgNASIgCADIgBAkIAAAJIAAAIQAAAGgFAEQgFADgHAAQgKAAgEgIQgCgGAAgNIAAgrIAAgRIgBgRQAAgKAEgJQAEgKAJAAQAGAAAFAFQAGAFAAAGIgBAKQARgUAQAAQASAAAIANQAHgGAIgDQAJgDAKAAQAXAAAIAWIAFAgQAEASAFAsQAAAHgFAEQgFAFgHAAQgNAAgCgOQgDgMgCgWIgEghQgDgVgFAAQgCAAgKAGQgKAFgEAEQAAANADAYQADAaAAANQAAAGgEAFQgFAEgHAAQgGAAgEgEg");
	this.shape_62.setTransform(455.7,132.5);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#000000").s().p("AguA9QgDgEAAgHIAAhMIAAgKIAAgLQAAgHAEgEQAEgFAIAAQANAAACAOQATgQAaAAQAYAAgBAfIAAAIQgBASgPAAQgPAAAAgPIAAgMQgaAEgLAXIAAA6QAAAHgEAEQgFAFgHAAQgHAAgFgFg");
	this.shape_63.setTransform(440.6,132.5);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#000000").s().p("AgmAxQgRgQgBgbQgBgZAPgUQASgYAfAAQAXAAAOASQANARAAAZQAAAbgPATQgQAVgbAAQgVAAgQgPgAgQgTQgHALAAAOQAAAOAIAHQAGAGAIAAQAKAAAHgHQAJgIAAgNQACglgVAAQgOAAgIANg");
	this.shape_64.setTransform(428.2,132.5);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#000000").s().p("AgWBjQgEgEAAgHIAAgDQADgRgBgOIAAg6IgHABIgHABQgHAAgFgFQgEgEAAgHQAAgLALgDQAFgCAPAAIACgNQADgaALgNQANgQAcAAQAWAAgBAPQAAAPgTAAQgOAAgHAKQgFAIgBAQIgBADIAWgCQAXAAAAAPQgBAQgXgBIgWABIAAAfIAAAfQAAAWgDAMQgDANgLAAQgGAAgGgEg");
	this.shape_65.setTransform(415.8,129.8);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#0099FF").s().p("AhRBaQgFgEAAgHIABgOIABgOIAAgVIAAgVIAAgVIAAgXIgCgUIgBgVQAAgHAGgGQAGgGAIAAQAIAAALAPQA0BMA0AvIAAgRQAAg5gBgUIgCgNIgBgNQAAgQARAAQATAAAAA7IAAASIAABJIgCATQgDAPgPAAQgIAAgKgJQgtgpg4hIIgBAkIABAcIAAAcQAAAjgRAAQgIAAgFgGg");
	this.shape_66.setTransform(389.7,129.6);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#0099FF").s().p("AguBQQgfgYAAg6IAAgRIABgQIAAgNIABgOQAAgKADgIQAFgKAIgBQAGABAFAEQAFAEAAAHIAAAUIAAAUIAAAQIgBARQAAARAEAPQAFATAKAHQAEADATAAQAeABALg1QAFgbAAgxQAAgHAEgGQAFgJAKAAQAIAAAEAHQADAEAAAFQAAAvgEAZQgHAngTAaQgJAMgMAIQgOAKgPAAQgeAAgOgMg");
	this.shape_67.setTransform(370.9,130);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#0099FF").s().p("Ag+BIQgagVAAgiQAAgnAZggQAcglAqAAQApAAAVASQATATAAAmQABAngXAgQgbAlgpAAQgjAAgZgUgAglgiQgRAXAAAcQAAAUAPAMQAOAMAXAAQAYAAASgaQAPgXAAgcQAAgZgLgJQgKgKgbAAQgZAAgTAag");
	this.shape_68.setTransform(352.6,129.7);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#0099FF").s().p("AhRBaQgFgEAAgHIABgOIABgOIAAgVIAAgVIAAgVIAAgXIgCgUIgBgVQAAgHAGgGQAGgGAIAAQAIAAALAPQA0BMA0AvIAAgRQAAg5gBgUIgCgNIgBgNQAAgQARAAQATAAAAA7IAAASIAABJIgCATQgDAPgPAAQgIAAgKgJQgtgpg4hIIgBAkIABAcIAAAcQAAAjgRAAQgIAAgFgGg");
	this.shape_69.setTransform(333.3,129.6);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#000000").s().p("AAcA2IgTAIQgIACgFAAQgcAAgOgOQgOgQAAgeQAAgbAVgUQAVgVAcABQALAAAOAGQASAIAAAKQAAADgDADIgBANIgBAQQAAAVADAJIAFANIAFALQAAAHgFAEQgEADgHAAQgFAAgMgKgAgQgXQgMANAAAPQAAAQAGAHQAGAJALgBQAGABAHgDQAGgCAGgFQgEgbAAgNIABgJIABgLIgEgCIgDgBQgPAAgMANg");
	this.shape_70.setTransform(306.6,132.5);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#000000").s().p("AggA9QgSgGAAgNQAAgMAOAAQAFAAALAEQAKADAGAAQAWAAAAgKQAAgFgQgIQgYgKgGgEQgRgMAAgQQAAgYAZgIQAPgFAdAAQAMAAAFADQAIAEAAALQAAAVgLAAQgMAAgCgKIgKAAQgcgBABAJQgBAEARAHQAXAMAIAFQARALAAAQQAAAVgTAJQgPAJgVAAQgPAAgNgFg");
	this.shape_71.setTransform(283.4,132.4);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#000000").s().p("AgKBcQgFgFAAgGIAAihQAAgIAFgDQAFgFAFAAQAHAAAFAFQAEADAAAIIAACaQAAAXgQAAQgGAAgEgFg");
	this.shape_72.setTransform(274.3,129.1);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#000000").s().p("AAcA2IgTAIQgIACgFAAQgcAAgOgOQgOgQAAgeQAAgbAVgUQAVgVAcABQALAAAOAGQASAIAAAKQAAADgDADIgBANIgBAQQAAAVADAJIAFANIAFALQAAAHgFAEQgEADgHAAQgFAAgMgKgAgQgXQgMANAAAPQAAAQAGAHQAGAJALgBQAGABAHgDQAGgCAGgFQgEgbAAgNIABgJIABgLIgEgCIgDgBQgPAAgMANg");
	this.shape_73.setTransform(264.6,132.5);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#000000").s().p("AAYA6QgQAFgPAAQgQAAgMgHQgNgIgCgPQgEgdAAgWQgBgPAEgUQACgNAOAAQAHAAAEAEQAGAEAAAHIgCAQIgCARIABAbIAEAVIAGACIAEAAQANAAAPgDIAAgVIAAgTQAAgYACgRQACgOAOAAQAHAAAFAEQAEAFAAAGIgCAqIAAAWIABAYIAAAHIAAAIQAAAGgFAEQgFAFgGAAQgKAAgEgJg");
	this.shape_74.setTransform(251.5,132.5);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#000000").s().p("AAMBLIAAgGIADghIgIABQgbAAgRgOQgSgPAAgZQAAgiAUgVQAVgWAkAAQAGAAAEADQAEgCAEAAQAHAAAFAFQAEAFAAAGQAAAhgEAnIgFApQgDAYAAATQAAAHgEAEQgFAFgHAAQgQAAAAgUgAgOgvQgJANAAASQAAALAHAGQAIAIAOgBQAIAAAEgIQAFgLAAgdIACgZIgEAAIgHgBQgSAEgKAPg");
	this.shape_75.setTransform(238.8,135.3);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#000000").s().p("AgnAyQgUgOAAgbQAAgdAPgUQASgXAcAAQAVAAANAGQASAKAAARQAAANgOALQgHAEgUAIIgnARQAHAGAHADQAIADAKABQAPAAALgHQAKgGAFAAQANAAAAAMQAAAOgTAIQgRAHgSAAQgbAAgSgOgAgQgcQgHAIgFAPIAbgMQAPgHAJgGQgIgFgNABQgJAAgJAGg");
	this.shape_76.setTransform(226.1,132.4);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#000000").s().p("AgiBzQgEgEAAgGQAAgHAHgFIAMgJQAYgaAAg3QAAgUgFgXQgHgZgMgNIgMgMQgHgIAAgFQAAgGAEgFQAFgEAGAAQAFAAAFAEQAYAQAPAkQANAgAAAfQAABXgzAcQgGADgFAAQgGAAgFgEg");
	this.shape_77.setTransform(558.3,95.9);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#000000").s().p("Ag1BaQgNgMgBgmQABgPACgfIACgvIgBgMIgCgMQAAgSARAAQAFAAAEADIAagFIAXgCQAdAAASAHQAKAEAAALQAAAGgDAFQgGAFgHAAIgEgBQgUgFgRAAIgSACQgLABgLADIgBAuIAtgEIAcgCQAHAAAGAEQAEAEAAAIQAAANgOABIgdADIgxAEIAAAYQgBAXADADQACACANAAIAUAAIAXgBIAGAAIAHgBQAHAAAFAEQAFAEAAAIQAAANgOADQgLACgkAAQgmAAgLgKg");
	this.shape_78.setTransform(546.4,94);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#000000").s().p("AgZBTQgOgigSg/IgJggQgHgWAAgIQAAgHAFgFQAFgEAHAAQALAAAFAMIAEAUIALAmQAJAgAJAaIAahGIALgcQAHgRAIgJQAFgGAHAAQAHAAAFAFQAFAFAAAGQAAAFgDAFQgHAJgFANIgIAXIggBQQgFAOgIAOQgFAKgJAAQgMAAgFgMg");
	this.shape_79.setTransform(530.6,94.3);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#000000").s().p("Ag3BVQgEgFAAgGQAAgGAEgFQAGgFAHAAQAJAAANgCIAAg1QAAgfACgdIgZABQgHAAgFgEQgEgFAAgHQgBgGAFgFQAEgEAGAAIAjgBQAVAAAkAEQANACAAAOQAAAIgFAEQgFAEgFAAIgfgEQgBAXAAAiIAAA1IAfAAQAIgBAEAFQAFAEgBAHQABAHgFAFQgFAEgHAAIgVAAIgTAAIgXACIgYADQgHAAgFgFg");
	this.shape_80.setTransform(515.7,94.3);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#000000").s().p("AgKBVQgGgEAAgHIABgFIAAgFIAAgRIgBgQQAAgQgDgaQgDgfAAgLIgGAAQgaAAgQgEQgNgDAAgMQAAgGAFgFQAFgGAIABIASACIATABIAVAAIAVAAIAaABIAbABQAHAAAFAFQAFAEAAAHQAAAGgFAFQgFAFgHAAIgcgCIgdgBIADAwQADAdAAASIABAMIAAALQAAAJgDAHQgFAJgJAAQgFAAgFgEg");
	this.shape_81.setTransform(501,94);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#000000").s().p("AA8BYQgKAAgJgWQgGgNgFgSIgcACQgRABgKACQgGANgNAaQgFAIgJAAQgHAAgFgEQgFgEAAgHQAAgGARgjQgCgDABgDQAAgGALgDQARgcAUgfQAcgsAHAAQANAAAEAPIAIAmIARBMIAGAPQAEALAAAFQAAAGgFAFQgEAEgGAAIgBAAgAgIALIAPgCIARgBIgIgnIgYAqg");
	this.shape_82.setTransform(483.7,94.3);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#000000").s().p("AhRBaQgFgEAAgHIABgOIABgOIAAgVIAAgVIAAgVIAAgXIgCgUIgBgVQAAgHAGgGQAGgGAIAAQAIAAALAPQA0BMA0AvIAAgRQAAg5gBgUIgCgNIgBgNQAAgQARAAQATAAAAA7IAAASIAABJIgCATQgDAPgPAAQgIAAgKgJQgtgpg4hIIgBAkIABAcIAAAcQAAAjgRAAQgIAAgFgGg");
	this.shape_83.setTransform(465.3,94.2);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#000000").s().p("Ag2BVQgGgFAAgGQAAgGAGgFQAFgFAHAAQAIAAAOgCIAAg1QAAgfADgdIgaABQgHAAgEgEQgGgFAAgHQABgGAEgFQAEgEAHAAIAigBQAVAAAkAEQANACAAAOQABAIgGAEQgEAEgGAAIgfgEQgCAXAAAiIAAA1IAhAAQAGgBAFAFQAFAEgBAHQABAHgFAFQgFAEgHAAIgVAAIgUAAIgWACIgYADQgHAAgEgFg");
	this.shape_84.setTransform(448.9,94.3);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#000000").s().p("ABABNIgHgdQgFgVgIgmIgRAwIgHAWQgEAMgFAJQgGALgKAAQgLAAgGgNIgHgWQgIgegIggIgPA4IgEAaQgFARgNAAQgIAAgEgGQgEgEgBgHQABgTAHgbIAOgsIAHgkQAFgZAGgIQAGgJAKAAQAKAAAFALQAFAKAFAgQAFAeAKAjQANgiAMgqIAGgbQAHgRANAAQAMAAAHAUQACAIADAVQAHAxAKAkQALAkAAADQAAAHgGAFQgFAEgGAAQgNAAgGgSg");
	this.shape_85.setTransform(432,94.3);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#000000").s().p("Ag9BIQgbgVAAgiQABgnAZggQAcglApAAQApAAAUASQAVATAAAmQgBAngWAgQgaAlgrAAQgiAAgYgUgAgkgiQgSAXAAAcQAAAUAPAMQAPAMAVAAQAZAAARgaQAQgXAAgcQABgZgLgJQgLgKgbAAQgZAAgSAag");
	this.shape_86.setTransform(411.6,94.3);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#000000").s().p("AhRBaQgFgEAAgHIABgOIABgOIAAgVIAAgVIAAgVIAAgXIgCgUIgBgVQAAgHAGgGQAGgGAIAAQAIAAALAPQA0BMA0AvIAAgRQAAg5gBgUIgCgNIgBgNQAAgQARAAQATAAAAA7IAAASIAABJIgCATQgDAPgPAAQgIAAgKgJQgtgpg4hIIgBAkIABAcIAAAcQAAAjgRAAQgIAAgFgGg");
	this.shape_87.setTransform(392.3,94.2);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#000000").s().p("AANB0QgzgcAAhXQAAgfANggQAPgkAXgQQAGgEAFAAQAGAAAFAEQAEAFAAAGQAAAGgJAIIgKALQgMANgIAZQgFAXAAAUQAAAZAFAUQAIAcAQALQAPAKAAAIQAAAGgEAEQgFAEgGAAQgFAAgGgDg");
	this.shape_88.setTransform(378.5,95.9);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#0099FF").s().p("AhRBaQgFgEAAgHIABgOIABgOIAAgVIAAgVIAAgVIAAgXIgCgUIgBgVQAAgHAGgGQAGgGAIAAQAIAAALAPQA0BMA0AvIAAgRQAAg5gBgUIgCgNIgBgNQAAgQARAAQATAAAAA7IAAASIAABJIgCATQgDAPgPAAQgIAAgKgJQgtgpg4hIIgBAkIABAcIAAAcQAAAjgRAAQgIAAgFgGg");
	this.shape_89.setTransform(353.6,94.2);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#0099FF").s().p("AguBQQgfgXAAg7IAAgRIABgQIAAgOIABgNQAAgKADgHQAFgMAIAAQAGAAAFAFQAFAEAAAHIAAAUIAAAUIAAAQIgBARQAAARAEAPQAFATAKAHQAEADATAAQAeABALg1QAFgbAAgxQAAgHAEgGQAFgJAKAAQAIABAEAFQADAFAAAFQAAAugEAaQgHAogTAZQgJANgMAHQgOAKgPAAQgeAAgOgMg");
	this.shape_90.setTransform(334.9,94.5);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#0099FF").s().p("Ag9BIQgagVAAgiQAAgnAZggQAcglApAAQApAAAUASQAVATAAAmQgBAngWAgQgaAlgrAAQgiAAgYgUgAgkgiQgSAXAAAcQAAAUAPAMQAPAMAVAAQAaAAAQgaQAQgXABgcQgBgZgKgJQgLgKgbAAQgZAAgSAag");
	this.shape_91.setTransform(316.6,94.3);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#0099FF").s().p("AhRBaQgFgEAAgHIABgOIABgOIAAgVIAAgVIAAgVIAAgXIgCgUIgBgVQAAgHAGgGQAGgGAIAAQAIAAALAPQA0BMA0AvIAAgRQAAg5gBgUIgCgNIgBgNQAAgQARAAQATAAAAA7IAAASIAABJIgCATQgDAPgPAAQgIAAgKgJQgtgpg4hIIgBAkIABAcIAAAcQAAAjgRAAQgIAAgFgGg");
	this.shape_92.setTransform(297.3,94.2);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#0099FF").s().p("Ag1BaQgOgMAAgmQAAgPADgfIACgvIgBgMIgBgMQAAgSAQAAQAFAAAFADIAZgFIAWgCQAeAAASAHQALAEgBALQAAAGgEAFQgEAFgHAAIgGgBQgTgFgSAAIgRACQgLABgKADIgCAuIAtgEIAdgCQAHAAAEAEQAFAEAAAIQAAANgOABIgcADIgyAEIgBAYQABAXACADQACACANAAIAUAAIAXgBIAHAAIAGgBQAHAAAFAEQAGAEgBAIQAAANgNADQgMACgkAAQgmAAgLgKg");
	this.shape_93.setTransform(270,94);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#0099FF").s().p("AgKBVQgGgEAAgHIABgFIAAgFIAAgRIgBgQQAAgQgDgaQgDgfAAgLIgGAAQgaAAgQgEQgNgDAAgMQAAgGAFgFQAFgGAIABIASACIATABIAVAAIAVAAIAaABIAbABQAHAAAFAFQAFAEAAAHQAAAGgFAFQgFAFgHAAIgcgCIgdgBIADAwQADAdAAASIABAMIAAALQAAAJgDAHQgFAJgJAAQgFAAgFgEg");
	this.shape_94.setTransform(253.9,94);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#0099FF").s().p("AA8BYQgKAAgJgWQgGgNgFgSIgcACQgRABgKACIgTAnQgFAIgJAAQgHAAgFgEQgFgEAAgHQAAgGARgjQgCgDABgDQAAgGALgDQARgcAUgfQAcgsAHAAQANAAAEAPIAIAmIARBMIAGAPQAEALAAAFQAAAGgFAFQgEAEgGAAIgBAAgAgIALIAPgCIARgBIgIgnIgYAqg");
	this.shape_95.setTransform(236.5,94.3);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#0099FF").s().p("Ag0BHQgRgSAAgZQAAgnAigoQAegjAdAAIAJAAIAIABQAFgFAHAAQAMAAADAOQACAKAAANQAAAGgDAFQgFAGgIAAQgLAAgFgLQgCgFgDgCIgJAAQgPAAgSAXQgbAfAAAcQAAANAIAJQAJAJAMAAQALAAAMgGIARgMQAJgGAFAAQAHAAAFAFQAFAFAAAGQAAAHgGAFQghAcggAAQgaAAgTgUg");
	this.shape_96.setTransform(220.6,94);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#0099FF").s().p("Ag3BVQgEgFAAgGQAAgGAEgFQAFgFAIAAQAJAAAOgCIgBg1QAAgfACgdIgZABQgHAAgFgEQgEgFAAgHQgBgGAFgFQAFgEAFAAIAjgBQAVAAAjAEQAOACAAAOQAAAIgFAEQgEAEgGAAIgegEQgCAXAAAiIAAA1IAfAAQAIgBAEAFQAEAEAAAHQAAAHgEAFQgFAEgHAAIgUAAIgUAAIgXACIgYADQgHAAgFgFg");
	this.shape_97.setTransform(206.4,94.3);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#0099FF").s().p("AgkBeQgOgCgHgGQgIABgEgFQgFgFABgGIABgjIAAgjIAAgnIAAgnQgBgGAHgGQAGgHAHAAQAEAAAPAIIAWAJQAhALAYAYQAdAcAAAgQAAAUgKATQgKASgRALQgTANgjAAQgIAAgLgDgAgpA7QAFAEAGABQAGABAHAAQAYABALgIQALgGAHgMQAFgLABgMQgBgdghgVQgLgHgmgQg");
	this.shape_98.setTransform(191.8,94.3);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#0099FF").s().p("Ag1BaQgOgMAAgmQAAgPADgfIACgvIgBgMIgBgMQAAgSAQAAQAFAAAFADIAZgFIAWgCQAeAAASAHQALAEgBALQAAAGgDAFQgFAFgHAAIgGgBQgSgFgTAAIgRACQgLABgKADIgCAuIAtgEIAdgCQAHAAAEAEQAFAEAAAIQAAANgOABIgcADIgyAEIgBAYQABAXACADQACACANAAIAUAAIAXgBIAHAAIAGgBQAHAAAFAEQAGAEgBAIQAAANgNADQgMACgkAAQgmAAgLgKg");
	this.shape_99.setTransform(175.5,94);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#0099FF").s().p("Ag/BYQgFgFAAgHIAAgaIABgaIAAheQAAgHAEgHQAGgIALABIAdACQAQACALAGQAyAaAAAlQAAAPgKALQgLAMgVAIQAfARAQASQAEAFAAAGQAAAGgFAFQgFAFgHAAQgGAAgFgFQgkgigpgMIABAlQAAAHgFAFQgFAEgHAAQgHAAgEgEgAgkAEIAGAAQAcAAANgHQAGgDAFgFQAFgFAAgCQAAgNgRgNQgOgLgSgCIgOgBg");
	this.shape_100.setTransform(160.2,94);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#0099FF").s().p("Ag0BZQgFgFAAgGIAAghQAAgRADgkIACg2QAAgeARABIALgBIARAAQAWgBAUAPQAXARAAAYQAAAegYAQQgVAQgcAAIgKAAIgBA1QAAAGgEAFQgFAFgGAAQgHAAgEgFgAgVguIgCApIAIABQARAAAMgIQANgKAAgPQAAgKgMgIQgMgHgMgBIgHABIgFAAIAAAQg");
	this.shape_101.setTransform(145.9,93.8);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#000000").s().p("AA8BYQgKAAgJgWQgGgNgFgSIgcACQgRABgKACQgGANgNAaQgFAIgJAAQgHAAgFgEQgFgEAAgHQAAgGARgjQgCgDABgDQAAgGALgDQARgcAUgfQAcgsAHAAQANAAAEAPIAIAmIARBMIAGAPQAEALAAAFQAAAGgFAFQgEAEgGAAIgBAAgAgIALIAPgCIARgBIgIgnIgYAqg");
	this.shape_102.setTransform(120.2,94.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16}]}).wait(161));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(106.8,-4.7,580.4,262.5);


// stage content:
(lib.predNoun_scene1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{scene1:0,scene1_repeat:106});

	// timeline functions:
	this.frame_5 = function() {
		playSound("apredicatenounnominative");
	}
	this.frame_105 = function() {
		/* _root.gonow = true;*/
	}
	this.frame_339 = function() {
		this.gotoAndPlay(1);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(5).call(this.frame_5).wait(100).call(this.frame_105).wait(234).call(this.frame_339).wait(1));

	// Layer 4 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgnnAWQMAAAgsfMBPPAAAMAAAAsfg");
	mask.setTransform(272.1,199.9);

	// Layer 2
	this.instance = new lib.predicateNoun_intro();
	this.instance.parent = this;
	this.instance.setTransform(284,183.5,1,1,0,0,0,342.1,111.4);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(340));

	// Layer 1
	this.UI = new lib.UI();
	this.UI.parent = this;
	this.UI.setTransform(548,54.9,1,1,0,0,0,54,40.5);

	this.instance_1 = new lib.Background();
	this.instance_1.parent = this;
	this.instance_1.setTransform(275.4,199.9);
	new cjs.ButtonHelper(this.instance_1, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.UI}]}).wait(340));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(289.8,201.6,526.7,398.7);
// library properties:
lib.properties = {
	id: '5FA1547B57193440BF18D56539F365FE',
	width: 550,
	height: 400,
	fps: 12,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"sounds/apredicatenounnominative.mp3", id:"apredicatenounnominative"},
		{src:"sounds/High_Screaming_Gtr.mp3", id:"High_Screaming_Gtr"},
		{src:"sounds/right_answer.mp3", id:"right_answer"},
		{src:"sounds/bgmPN.mp3", id:"bgmPN"},
		{src:"sounds/wrong_answer.mp3", id:"wrong_answer"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['5FA1547B57193440BF18D56539F365FE'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;